### ISSUE TITLE
Extracting Technical Metadata by MediaInfo in Archivemtica as PBCore 2.0 Standard

### ISSUE THREAD

**Issue by JG260914** [archivematica/Issues#1000]
How do I configure MediaInfo technical metadata extraction in Archivemtica so that the data output is PBCore 2.0 standard?

**Comment by ablwr** [comment]
Hi @JG260914,

These kinds of questions are best suited for the [Archivematica user forum](https://groups.google.com/forum/#!forum/archivematica), where you can get help from the community. This issues tracker is better suited for tracking errors or bugs with the codebase.

But, to answer your question, you can modify MediaInfo's output in the Format Policy Registry (aka the Preservation Planning tab). In our sandbox, it is on this page: https://sandbox.archivematica.org/fpr/fpcommand/114c9525-d676-4fac-9962-4672faa924bb/ (demo@example.com and demodemo to log in). You can replace this command with the command that exports PBCore by changing --Output=XML to --Output=PBCore2

**Comment by JG260914** [comment]
Dear Ashley, I apologize for sending this message here. Anyway, I thank
you for the friendliness and promptness you always have. I followed your
recommendation and it worked here! Thanks

---
João Guilherme Nogueira Machado
Cargo: Tecnologista em Saúde Pública
guilherme.machado@icict.fiocruz.br
Telefone: (21)3882-9213

ICICT - Instituto de Comunicação e Informação Científica e Tecnológica
em Saúde
http://www.icict.fiocruz.br 

Fundação Oswaldo Cruz | Ministério da Saúde
Av. Brasil, 4036 | Prédio da Expansão do Campus| Manguinhos | CEP
21040-361 | Rio de Janeiro | Brasil 

Em 2019-11-19 11:31, Ashley escreveu:

> Hi @JG260914 [1], 
> 
> These kinds of questions are best suited for the Archivematica user forum [2], where you can get help from the community. This issues tracker is better suited for tracking errors or bugs with the codebase. 
> 
> But, to answer your question, you can modify MediaInfo's output in the Format Policy Registry (aka the Preservation Planning tab). In our sandbox, it is on this page: https://sandbox.archivematica.org/fpr/fpcommand/114c9525-d676-4fac-9962-4672faa924bb/ (demo@example.com and demodemo to log in). You can replace this command with the command that exports PBCore by changing --Output=XML to --Output=PBCore2 
> 
> --
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub [3], or unsubscribe [4].
 

Links:
------
[1] https://github.com/JG260914
[2] https://groups.google.com/forum/#!forum/archivematica
[3]
https://github.com/archivematica/Issues/issues/1000?email_source=notifications&amp;email_token=ALRV3XDHQPSBRLRK4GA6LS3QUP2E3A5CNFSM4JOZLZR2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEEOMKOY#issuecomment-555533627
[4]

**Comment by JG260914** [comment]
Dear Ashley,

I apologize for sending this message here.
Anyway, I thank you for the friendliness and promptness you always have.
I followed your recommendation and it worked here!
Thanks

**Comment by ablwr** [comment]
não tem problema, de nada
