### ISSUE TITLE
Problem: transfer tab not displaying correctly

### ISSUE THREAD

**Issue by jorikvankemenade** [archivematica/Issues#1002]
**Expected behaviour**
When running the docker images using the `qa/1.x` branch I should be able to use the basic Archivematica functionality. 

**Current behaviour**
The frontend is not built correctly: 

![image](https://user-images.githubusercontent.com/7934339/69348320-42866680-0c76-11ea-9d80-c0400c539824.png)

I am missing the interface for starting transfers. When looking at the stacktrace upon loading the page I get a `404 not found` on `/media/js/build/dashboard.js`. When I look at th the `qa/1x` branch I see that the `frontend` folder changed 4 months ago, and the docker recipe 8 months ago. Also the docker recipe. Maybe something needs to be updated? :)

**Steps to reproduce**

Build and run a new set of docker containers with the Archivematica `qa/1.x` branch.

**Your environment (version of Archivematica, operating system, other relevant details)**
Docker-compose setup on `qa/1x`, but similar problems when trying to install on CentOS using the git sources.

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged (if applicable)
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by jorikvankemenade** [comment]
If I look in the CentOS packages I see that the `/usr/share/archivematica/dashboard/media/js/` directory contains a `build` directory. This directory is missing on my docker images. My hunch is that I need to build the frontend somehow. But I can't find any hints in the documentation. 

@ross-spencer or @sevein does anyone of you know the answer? In return, I'll deliver you guys a tested PR :).

**Comment by sevein** [comment]
Have you tried running `make bootstrap-dashboard-frontend` manually? When using Docker for Mac, that build used to break in different ways. We had a section added to the FAQ with some instructions: https://github.com/artefactual-labs/am/tree/master/compose#make-bootstrap-fails-to-run. Hopefully that'll work!

**Comment by jorikvankemenade** [comment]
Thanks for the quick reply. The thing that confuses me is that the `frontend` folder changed completely between [1.9](https://github.com/artefactual/archivematica/tree/stable/1.9.x/src/dashboard/frontend) and [1.10](https://github.com/artefactual/archivematica/tree/stable/1.10.x/src/dashboard/frontend). The bootstrap instructions are clearly aimed at the 1.9 version and not at the 1.10 version. So I have the feeling that I am completely missing something.

**Comment by sevein** [comment]
You're right. We used to have two AngularJs apps and they were merged. I've just pushed a new commit updating the instructions. `make bootstrap-dashboard-fronted` is the preferred way, but it's not going to work if you've checked out and old tree of the AM repo for that reason.

**Comment by jorikvankemenade** [comment]
It seems that something went wrong with my Docker installation, that works now. However, the problem remains in my Puppet installation. Could it be the `npm` version? I have `3.10.10` on my failing node and `6.4.1` on my Docker container. 

Some extra context. If I run npm on Docker and on my failing node I get different results:

``` 
root@564bd43fae62:/src/dashboard/frontend# npm install
npm WARN lifecycle dashboard@0.0.0~prepare: cannot run in wd dashboard@0.0.0 webpack --progress --colors --entry ./app.js (wd=/src/dashboard/frontend)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

audited 3489 packages in 2.962s
found 512 vulnerabilities (188 low, 28 moderate, 295 high, 1 critical)
  run `npm audit fix` to fix them, or `npm audit` for details
```

```
[root@archivematica-afs frontend]# npm install
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
```

It seems that both have the `dashboard` package installed:

```
root@564bd43fae62:/src/dashboard/frontend# npm list | grep dashboard
dashboard@0.0.0 /src/dashboard/frontend
```

```
[root@archivematica-afs frontend]# npm list | grep dashboard
dashboard@0.0.0 /home/archivematica/archivematica/src/dashboard/frontend
```

But the docker package has the build directory while the other node does not:

```
root@564bd43fae62:/src/dashboard/frontend# ls -al /src/dashboard/src/media/js/build
total 4704
drwxr-xr-x 2 root root    4096 Nov 21 16:38 .
drwxrwxr-x 9 1000 1000    4096 Nov 21 16:38 ..
-rw-r--r-- 1 root root 4808482 Nov 21 16:38 dashboard.js
```

```
[root@archivematica-afs frontend]# ls -al /home/archivematica/archivematica/src/dashboard/src/media/js/build
ls: cannot access /home/archivematica/archivematica/src/dashboard/src/media/js/build: No such file or directory
```

**Comment by sevein** [comment]
> Could it be the npm version? I have 3.10.10 on my failing node and 6.4.1 on my Docker container.

It could be! For reference, we're doing similarly from Ansible: https://github.com/artefactual-labs/ansible-archivematica-src/blob/ee1e304ace5671e702cc4860c1a4904247b44846/tasks/pipeline-instcode.yml#L66-L88. IIRC the permission change was important for npm. It didn't do well when running as root. I think that some users had more success using yarn instead.

**Comment by jorikvankemenade** [comment]
The problem is my npm version. Thanks for your help!
