### ISSUE TITLE
Problem: external PIDs are not searchable through the Identifiers option of the Archive storage

### ISSUE THREAD

**Issue by replaceafill** [archivematica/Issues#1006]
**Expected behaviour**

SIP and file identifiers in a `metadata/identifiers.json` file can be searched in the Archival storage using the `Identifiers` option of the field name dropdown.

**Current behaviour**

In the Archival storage only external identifiers from [MODS and Islandora](https://github.com/artefactual/archivematica/blob/c302f4149b83c0a348f36d36cf611bbfd7fa0150/src/MCPClient/lib/clientScripts/index_aip.py#L26-L42) are searchable through the `Identifiers` option in the field name dropdown.

Note: it's possible to search for external **file** identifiers using the "Any" option of the field name dropdown since the `amdSec` of the file is indexed, but it's not possible to search SIP identifiers.

**Steps to reproduce**

1. Run a `SampleTransfers/DemoTransferCSV` transfer
2. Once the transfer finishes go to the Archival storage tab and use the `Identifiers` option in the field name dropdown and search for `01D9T8MJM9NEQ390H239VT50CQ` ([one of the external SIP identifiers](https://github.com/artefactual/archivematica-sampledata/blob/6e299d0c43e3ccc19f6eb1132a7b04b70e300866/SampleTransfers/DemoTransferCSV/metadata/identifiers.json#L4-L13))
3. The search will return no results

**Your environment (version of Archivematica, operating system, other relevant details)**

qa/1x (https://github.com/artefactual/archivematica/commit/c302f4149b83c0a348f36d36cf611bbfd7fa0150) on docker-compose

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [x] All pull requests related to this issue are properly linked
- [x] All pull requests related to this issue have been merged
- [x] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged (if applicable)
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by ablwr** [comment]
Tested in qa/1.x on Ubuntu Bionic via Docker (last commit: https://github.com/artefactual/archivematica/commit/baf565e4abc3bcf9480ee0784734ce9b0b223f63)
