### ISSUE TITLE
Problem: DSpace transfer fails at Verify AIP if there were hidden files in the package

### ISSUE THREAD

**Issue by sallain** [archivematica/Issues#1013]
**Expected behaviour**
DSpace transfers should succeed and become AIPs!

**Current behaviour**
I'd say that this is an edge case (it happened once out of 13,000 AIPs created by a user), but here's how it happens:

1. The researcher uploads their material to DSpace. The upload includes a ZIP package of data including hidden files, such as Mac dotfiles.
2. The record is exported as a DSpace AIP, which includes a checksum manifest for everything in the AIP (including the contents of the ZIP package). The DSpace AIP contains the ZIP package:

```
DSpaceExport/
└── my-research-data.zip
```

3. The DSpace export is transferred into Archivematica using the DSpace transfer type.
4. The ZIP package is extracted, including the hidden files:

```
DSpaceExport/
├── my-research-data
│   ├── some-data.xlsx
│   ├── supplementary-materials.docx
│   ├── ._some-data.xlsx
│   └── ._supplementary-materials.docx
└── my-research-data.zip
```

5. Archivematica automatically removes hidden files from the transfer during `Microservice: Remove cache files`:

```
DSpaceExport/
├── my-research-data
│   ├── some-data.xlsx
│   └── supplementary-materials.docx
└── my-research-data.zip
```

6. During `Job: Verify AIP` Archivematica uses the DSpace-generated checksum manifest to check the contents of the AIP. It tries to check the checksums of all the files, including the hidden files. The hidden files no longer exist. The job fails because a checksum error is considered critical.

This results in a transfer that cannot be processed unless (maybe?) the ZIP package is never unpacked. However, this workaround has knock-on effects for the preservation of the contents of the ZIP package so it's not ideal.

**Steps to reproduce**
See above.

**Your environment (version of Archivematica, operating system, other relevant details)**
1.10.1

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged (if applicable)
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by sromkey** [comment]
We feel this would be better addressed in the DSpace environment than by Archivematica.
