### ISSUE TITLE
Problem: Interval setting for updating the UI is being ignored by the frontend code

### ISSUE THREAD

**Issue by replaceafill** [archivematica/Issues#1017]
**Expected behaviour**

The (polling) interval setting affects how frequently the Transfer and Ingest tabs are updated (e.g. refreshed).

**Current behaviour**

The `POLLING_INTERVAL` setting was [added](https://github.com/artefactual/archivematica-history/commit/082047d78f5c7bf5e8969b2b7fa263b83c239ea8) to allow user modify the frequency in which the frontend code of the Dashboard asks the server for the status of transfers and ingests.

However this [setting is currently being ignored by the Backbone view](https://github.com/artefactual/archivematica/blob/473bb9df38eb1ba3cba4cb04b0c40eb0bcbc0293/src/dashboard/src/media/js/jobs.js#L611) because it relies on jQuery's [document.ready](https://github.com/artefactual/archivematica/blob/473bb9df38eb1ba3cba4cb04b0c40eb0bcbc0293/src/dashboard/src/templates/ingest/grid.html#L22-L33) to be executed first to store the value in the `window` object. Since that doesn't happen in the right order, the interval time is set to a hardcoded value of 5 seconds.

Additionally there's a separate [`STATUS_POLLING_INTERVAL`](https://github.com/artefactual/archivematica/blob/473bb9df38eb1ba3cba4cb04b0c40eb0bcbc0293/src/dashboard/src/settings/base.py#L425) setting which I don't think is being used by any frontend code and it can be removed.

**Note (Personal opinion)**

This setting is not documented and it may have some value when it works again.

As a beginner user of the application I've struggled with the refreshing behavior of decision points. Normalization comes to mind. Five seconds is usually not enough for me to go through each option, and by the time I made my mind the UI refreshes and the dropdown disappears. I've seen the same happening to other users in trainings.

I started investigating this because some of our Selenium based AMAUATs have the same problem. A few tests sometimes fail and after a second or third run they pass and when they fail Selenium usually complains about the elements it expects not being there (the UI has refreshed already).

**Steps to reproduce**

1. Change the [`POLLING_INTERVAL`](https://github.com/artefactual/archivematica/blob/473bb9df38eb1ba3cba4cb04b0c40eb0bcbc0293/src/dashboard/src/settings/base.py#L424) from 5 to 10.
2. Restart the dashboard service
3. Go to the Transfer or Ingest tab and using the development tools in the web browser look for the Network tab and check how often the `/status/`, `/transfer/status/` and `/ingest/status/` URLs are requested. It will always be 5 seconds.

**Your environment (version of Archivematica, operating system, other relevant details)**

qa/1.x (https://github.com/artefactual/archivematica/commit/473bb9df38eb1ba3cba4cb04b0c40eb0bcbc0293) in the docker-compose environment.

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged (if applicable)
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by ross-spencer** [comment]
Following on from Slack, there's a chance we feel this will make AMAUAT slightly more reliable to run too, those using Selenium. One that I'm seeing some UI failures only on (intermittent) that can be run via Compose is:

* `sudo make test-at-behave TAGS=mo-aip-reingest BROWSER=Firefox`

**Comment by ross-spencer** [comment]
This is being felt in the wild now with a client using multiple different storage locations they might choose from during ingest. This brings up the modal UI component: 

![image](https://user-images.githubusercontent.com/1880412/91222096-b1ed2300-e6ec-11ea-8255-880e13017f73.png)

While trying to select the values in this drop down, the page may have refreshed and the selections no longer "valid" so user clicks them and the modal disappears without affecting anything. The user needs to make their selection within 5s. 

This is outside of my intuition, but I can see that following some of the notes above and then setting the line here: https://github.com/artefactual/archivematica/blob/396015a44723e6b2dd2f4d7bed1443514a429c12/src/dashboard/src/media/js/jobs.js#L906-L920

To an interval like 30,000 does improve the experience for the user. 

30,000 is too high for the user interface on the whole as the user interface shows the progression of a transfer. 

I'll see if I can figure out a way to apply the configurable setting in `jobs.js` but another question is **_do we also want a higher default to ease some of the pains of this issue for users? 10 seconds might make all the difference?_**

**Comment by uofmsean** [comment]
I think a 10 second default would definitely improve the user experience. Having the configurable value honoured would be better. Never interrupting the user while choosing an action would be best.

**Comment by sromkey** [comment]
Ross has demonstrated to me how this works, so I'm moving to Done.
