### ISSUE TITLE
Problem: Sanitize file and directory names in metadata job fails when the transfer structure report is not generated

### ISSUE THREAD

**Issue by replaceafill** [archivematica/Issues#1018]
**Expected behaviour**

If the transfer structure report is not generated the workflow works with any transfer type and content.

**Current behaviour**

If a transfer doesn't contain a `metadata` directory (for example `SampleTransfers/Images/pictures`) and the `Generate transfer structure report` processing configuration is set to `No`, the `Sanitize file and directory names in metadata` job in the Ingest tab fails like this:

![3](https://user-images.githubusercontent.com/560781/70115641-fea44180-1625-11ea-9868-4e84c45d6f9a.png)

A transfer containing a `metadata` directory like `SampleTransfers/DemoTransferCSV` finishes successfully in the same conditions.

**Steps to reproduce**

1. Reset the default processing configuration and set the `Generate transfer structure report` option to `No`.

2. Create a Standard transfer using `SampleTransfers/Images/pictures`

3. Answer the default decision points like this:

   Transfer:
   *  Do you want to perform file format identification? **Yes**
   *  Examine contents? **Skip examine contents**
   * Create SIP(s)? **Create single SIP and continue processing**

   Ingest:
   * Normalize? **Normalize for preservation and access**
   * Approve normalization? **Approve**
   * Reminder: add metadata if desired **Continue**
   * Transcribe SIP contents? **No**

4. You should get a `Failed SIP` microservice and in the `Process metadata directory` microservice, the `Sanitize file and directory names in metadata` job failed. The output of the job should have an error starting with `OSError: [Errno 2] No such file or directory: ...`

5. Run a new transfer with `SampleTransfers/DemoTransferCSV` and answer the decision points the same way. It should finish successfully.

**Your environment (version of Archivematica, operating system, other relevant details)**

qa/1.x (https://github.com/artefactual/archivematica/commit/473bb9df38eb1ba3cba4cb04b0c40eb0bcbc0293) in the docker-compose environment. Also verified in a Jenkins VM.

Confirmed as a regression using http://am110bionic.qa.archivematica.net/

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [x] All pull requests related to this issue are properly linked
- [x] All pull requests related to this issue have been merged
- [x] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [x] Documentation regarding this issue has been written and merged (if applicable)
- [x] Details about this issue have been added to the release notes (if applicable)

**Comment by replaceafill** [comment]
As seen in the error message in the issue description, an nonexistent directory is being passed to the  `Sanitize file and directory names` job which makes it fail. Why is the `objects/metadata` directory not there?

The `metadata` directory is originally created outside the `objects` directory by the `Attempt restructure for compliance` job of the `Verify transfer compliance` microservice in the Transfer tab:

```
Creating directory /var/archivematica/sharedDirectory/currentlyProcessing/pictures-test/metadata
```

And if the transfer structure report is generated, a file `directory_tree.txt` is produced and placed in this directory. Otherwise the directory continues being empty.

Then a few jobs later, in the Ingest tab, the `Move metadata to objects directory` job of the `Process metadata directory` microservice calls the `move_or_merge` client script to move the `metadata` directory and its contents to `objects/metadata`. If `objects/metadata` exists at that point (e.g. `SampleTransfers/DemoTransferCSV`) the contents of the two directories should be merged together.

In 1.10 [the existence of `objects/metadata` is verified](https://github.com/artefactual/archivematica/blob/3ba67bf461f2f35f549cc2ac5c85dd1bfb39cfa4/src/MCPClient/lib/clientScripts/move_or_merge.py#L19-L20) and if it doesn't exist (e.g. `SampleTransfers/Images/pictures`) the original `metadata` directory is moved to its new location.

But recently [the `move_or_merge` script was changed](https://github.com/artefactual/archivematica/commit/ad687b3677254eec90e1b82a87d917e0fabbd937#diff-6468963731b851d91a0130b41935a766) and that check was removed and only the contents of the directory are considered for the move. So if the `metadata` directory is empty (no `directory_tree.txt` inside), nothing happens and the script just deletes the original directory. A new `objects/metadata` directory is never created.

If I restore the previous version of the `move_or_merge` client script in my dev environment the workflow continues successfully.

**Comment by ablwr** [comment]
Nice find @replaceafill, and thanks for the clear instructions on how to replicate.

Tested this in qa/1.x (proto-1.11 RC)
