### ISSUE TITLE
Problem: Transfer browser breaks if transfer source contains read protected directories

### ISSUE THREAD

**Issue by replaceafill** [archivematica/Issues#1019]
**Expected behaviour**

The transfer browser ignores read protected subdirectories in the Transfer Source location and works as expected.

**Current behaviour**

Part of the `scandir` refactoring of the Storage Service [doesn't check for access permissions](https://github.com/artefactual/archivematica-storage-service/commit/78b8aaf07968dcf96496dcad3989c61c9bffab71#diff-ed5ab696cbe211f947dd0b482624c8eeL816-L817) on subdirectories anymore.

If the Transfer Source location contains subdirectories that the OS user that runs the `archivematica-storage-service` process cannot access (e.g. belong to another user and have `drwx------` permissions), the transfer browser widget is displayed empty like this:

![Screenshot_2019-12-04 Archivematica Dashboard - Transfer](https://user-images.githubusercontent.com/560781/70117870-21395900-162c-11ea-9203-545f54aced16.png)

and and error like this is produced in the Storage Service logs:

```
ERROR     2019-12-03 15:43:31  django.request.tastypie:resources:_handle_500:301:  Internal Server Error: /api/v2/location/2c057478-ec72-42b8-8355-cd44412f328f/browse/
Traceback (most recent call last):
  File "/usr/share/archivematica/virtualenvs/archivematica-storage-service/local/lib/python2.7/site-packages/tastypie/resources.py", line 220, in wrapper
    response = callback(request, *args, **kwargs)
  File "/usr/lib/archivematica/storage-service/locations/api/resources.py", line 135, in wrapper
    result = func(resource, request, bundle, **kwargs)
  File "/usr/lib/archivematica/storage-service/locations/api/resources.py", line 449, in browse
    objects = self.get_objects(location.space, path)
  File "/usr/lib/archivematica/storage-service/locations/api/v2.py", line 31, in get_objects
    objects = space.browse(path)
  File "/usr/lib/archivematica/storage-service/locations/models/space.py", line 276, in browse
    return self.browse_local(path)
  File "/usr/lib/archivematica/storage-service/locations/models/space.py", line 697, in browse_local
    return path2browse_dict(path)
  File "/usr/lib/archivematica/storage-service/locations/models/space.py", line 838, in path2browse_dict
    "object count": count_objects_in_directory(entry.path)
  File "/usr/lib/archivematica/storage-service/locations/models/space.py", line 849, in count_objects_in_directory
    for entry in _scandir_files(path):
  File "/usr/lib/archivematica/storage-service/locations/models/space.py", line 814, in _scandir_files
    for subentry in _scandir_files(entry.path):
  File "/usr/lib/archivematica/storage-service/locations/models/space.py", line 812, in _scandir_files
    for entry in scandir.scandir(path):
OSError: [Errno 13] Permission denied: '/home/archivematica/.ssh'
```

This may be one of the reasons why the acceptance tests runs have started failing.

**Steps to reproduce**

@ross-spencer provided [a way to test this issue in a docker compose environment](https://github.com/archivematica/Issues/issues/1019#issuecomment-566319673)

**Your environment (version of Archivematica, operating system, other relevant details)**

Found this on a Jenkins VM where [the home directory for `archivematica` user is just a symbolic link to the home directory of the `ubuntu` user](https://github.com/artefactual/deploy-pub/blob/d1fe7bd95922d3cdcd8ab0cf0147c0ea66868bcb/playbooks/archivematica-bionic/.Jenkinsfile#L55). And the `archivematica` user has no read permissions on the `/home/ubuntu/.ssh` directory.

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged (if applicable)
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by ross-spencer** [comment]
### To recreate in Docker: 

1. Go to the mounted directory `archivematica-sampledata/`.
2. `mkdir any-dir-name`.
3. `chmod 0744 any-dir-name`. <-- At this point everything will still work.
4. `cd any-dir-name`.
5. `mkdir another-dir-name`. <-- Transfer browser breaks. 

You should have `archivematica-sampledata/any-dir-name/another-dir-name/` and `any-dir-name` has `0744` permissions, and you shouldn't be able to access the remainder of your mounted transfer source.

**Comment by ablwr** [comment]
I'm still experiencing this one... nothing comes up in the storage-service logs, but instead in the mcp-server logs:

```
archivematica-mcp-server_1       | WARNING  ThreadPoolExecutor-0_1 2020-01-04 02:17:54 storageService:copy_files:265:  Unable to move files with {'files': [{u'source': u'archivematica/archivematica-sampledata/write-ok/.', u'destination': u'/var/archivematica/sharedDirectory/tmp/tmpuWoshZ/ok/.'}], 'pipeline': u'/api/v2/pipeline/625b5c18-5eb7-4d5c-a1f1-83cfa161d843/', 'origin_location': u'/api/v2/location/e696567d-f33e-48f1-ae57-59937d8e058f/'} because 500 Server Error: INTERNAL SERVER ERROR for url: http://archivematica-storage-service:8000/api/v2/location/82f149c4-5f24-4868-8381-15524981c851/
archivematica-mcp-server_1       | ERROR    ThreadPoolExecutor-0_1 2020-01-04 02:17:54 packages:wrap:388:  Exception occurred during transfer processing
archivematica-mcp-server_1       | Traceback (most recent call last):
archivematica-mcp-server_1       |   File "/src/MCPServer/lib/server/packages.py", line 381, in wrap
archivematica-mcp-server_1       |     return fn(*args, **kwargs)
archivematica-mcp-server_1       |   File "/src/MCPServer/lib/server/packages.py", line 440, in _start_package_transfer_with_auto_approval
archivematica-mcp-server_1       |     _copy_from_transfer_sources([path], transfer_rel)
archivematica-mcp-server_1       |   File "/usr/local/lib/python2.7/site-packages/contextdecorator.py", line 102, in inner
archivematica-mcp-server_1       |     _reraise(*exc)
archivematica-mcp-server_1       |   File "/usr/local/lib/python2.7/site-packages/contextdecorator.py", line 95, in inner
archivematica-mcp-server_1       |     result = f(*args, **kw)
archivematica-mcp-server_1       |   File "/src/MCPServer/lib/server/packages.py", line 246, in _copy_from_transfer_sources
archivematica-mcp-server_1       |     % {"message": ", ".join(message)}
archivematica-mcp-server_1       | Exception: The following errors occurred: 500 Server Error: INTERNAL SERVER ERROR for url: http://archivematica-storage-service:8000/api/v2/location/82f149c4-5f24-4868-8381-15524981c851/
```

Perhaps a similar change is needed there?

**Comment by replaceafill** [comment]
@ablwr I think you're seeing a different problem. I notice your error log shows `_start_package_transfer_with_auto_approval` which I think means the transfer has already been started?

**Comment by ablwr** [comment]
@replaceafill Ooh okay, maybe that was from when I was trying to test another issue -- getting weird with [this one](https://github.com/archivematica/Issues/issues/1038) trying to force that error by taking down Gearman at the same time.

Anyway, then I guess I don't get any error, but I also wasn't able to get any transfer to initiate.

**Comment by ross-spencer** [comment]
**NB.** I am seeing the same MCP Server exception with the following permissions `0640`:
```
-rw-r-----  1 ross-spencer ross-spencer 12446432 Aug  9 02:27 beihai.tif
```
It doesn't break the transfer browsing function (i.e. browsing to the directory with this file works and I can try to start the transfer) but it doesn't let the transfer to start. Output along the lines of https://github.com/archivematica/Issues/issues/1011 would help. Currently seeing this while trying to investigate a normalization error.

**Comment by sallain** [comment]
I changed a directory to `drwx------` as per the original comment. The transfer browser works fine, but the directory shows up like an individual file - file icon + strikethrough. You cannot add it to a transfer (the Add button is greyed out.)

![Screenshot of Archivematica Dashboard - Transfer.jpg](https://codetreeusercontent.s3.amazonaws.com/uploads/f7d066cb-43ad-4f13-9ff9-519d77c4e5ba/Screenshot+of+Archivematica+Dashboard+-+Transfer.jpg)

IMO this is acceptable - directories need certain permissions to be picked up by Archivematica. This isn't really documented, though.

@sromkey thoughts on this one?

**Comment by sromkey** [comment]
@sallain I agree, I think this is a workable solution. Wouldn't hurt to have some documentation on the matter but "check the permissions" is a leap that I think a lot of people will make in the meantime.

**Comment by sallain** [comment]
I'm adding a documentation label and closing - I will try to get to the docs this week.
