### ISSUE TITLE
Problem: The Extract Packages user-choice could be further up the workflow chain

### ISSUE THREAD

**Issue by ross-spencer** [archivematica/Issues#102]
**Please describe the problem you'd like to be solved.**

The user choice 'Extract Packages?' happens after two other 'extract packages' microservices.

* Move to Extract Packages
* Determine if transfer contains packages

The user is then provided with the option to choose whether or not packages should be extracted from the transfer, and then the follow-up option, delete packages after extraction. 

![image](https://user-images.githubusercontent.com/1880412/44304111-1dd76c80-a318-11e8-999b-e6308160fbd4.png)

**Describe the solution you'd like to see implemented.**

I'd like to seethe decision point about extracting packages moved sooner in the Archivematica workflow. This would save us moving the transfer once, and then save us from running a microservice checking for packages that can be extracted.

As far as I can tell, if the user has configured this, e.g. does not want to extract packages, then the first two microservices don't need to happen at all. If the user does want to extract packages, then the workflow isn't interrupted significantly by moving the decision-point to an earlier point in the workflow.

**Describe alternatives you've considered.**

This is a potential optimization and may only produce minor results, so it doesn't need to happen at all, but it might be worth considering. 

**Additional context**

This consideration has popped up as a result of some work I am doing to create a new transfer type in Archivematica where sometimes I want extract packages to happen, and sometimes I don't want it to happen, based on the content of a transfer. To create this workflow, the database migration is more complicated, i.e. we do need to make sure packages are moved to the extract packages watched directory, and then we do need to override the user choice to make sure extract packages happens. This results in a number of new database rows and modified chain-links for that specific workflow. The short-cut is to move the files to the watched directory and have a microservice chain kick-off from that point without the user-choice happening after.

**Comment by sallain** [comment]
@ross I'd actually love to see this whole microservice be moved much earlier in the workflow, if possible. It would be ideal to have this microservice occur before file ID, validation, and characterization - maybe even before virus scanning - so that the files within the package could benefit from those microservices.

**Comment by ross** [comment]
You're probably looking for @ross-spencer rather than @ross 😁

**Comment by sallain** [comment]
@ross haha sorry about that! Slack handles vs. GitHub handles :woman_facepalming:

@ross-spencer that comment above is for you!

**Comment by ross-spencer** [comment]
I hear you @sallain - it would be a great streamlining. 

![image](https://user-images.githubusercontent.com/1880412/54545124-553af400-49a1-11e9-9c9f-af22a7df19cf.png)

In the screenshot above, those tasks do run separately in that microservice group but that does seem like a duplication. If we can just do it once we know all of the objects in a package like you say, then there could be a few benefits.

**Comment by sromkey** [comment]
@sallain @ross-spencer it just would mean we'd need some way of identifying package formats I guess? Because currently that happens in File ID, and that's how extraction is called.

**Comment by sallain** [comment]
@sromkey I thought about that, and couldn't decide if that was how it worked, so I didn't include a note about it - does `Job: Determine if transfer contains packages` use the file ID output to identify if package formats are present?

**Comment by sromkey** [comment]
I think (definitely could be wrong) it uses the File ID info.

**Comment by ross-spencer** [comment]
Ooooh! That's a really good catch. I think you're right because it'll be driven by the extraction rules in the FPR...

**Comment by sromkey** [comment]
Stumbled on this blast from the past and am pretty confident this is not something we're going to pursue, so I'm closing it :)
