### ISSUE TITLE
Problem: bags with metadata fail to ingest when additional metadata is added by automation tools   

### ISSUE THREAD

**Issue by hakamine** [archivematica/Issues#1022]
**Expected behaviour**
Bags ingested without errors

**Current behaviour**
Failure (transfer tab, `Microservice: Characterize and extract metadata`, `Job: Store file modification dates`)

**Steps to reproduce**
1. Have an unzipped bag transfer source with metadata (i.e., a "metadata" directory under the "data" directory of the bag)
2. Set up automation tools to add metadata with a pre-transfer script, for example with the [`add_metadata.py`](https://github.com/artefactual/automation-tools/blob/084d4291fa3a4a68cf55e221935e9de801f9ead7/transfers/examples/pre-transfer/add_metadata.py) script
3. Automation tools will start and approve the transfer, but the transfer will fail at  `Microservice: Characterize and extract metadata`,  `Job: Store file modification dates`)

**Your environment (version of Archivematica, operating system, other relevant details)**
AM1.10.x (also tried with 1.8.x),  automation tools master branch ([084d429](https://github.com/artefactual/automation-tools/commit/084d4291fa3a4a68cf55e221935e9de801f9ead7))

**Additional information**
The SIP (in progress) in the `failed` directory has a directory structure with a duplicated `metadata` directory one inside the other, where the original metadata files from the transfer source are inside the inner one, and the metadata added by automation tools one level above:
```
├── [4.0K]  logs
...
├── [4.0K]  metadata
│   ├── [2.5K]  manifest-md5.txt
│   ├── [4.0K]  metadata
│   │   └── [4.0K]  submissionDocumentation   => (original metadata from the 
│   │       ├── [4.0K]  BitCurator_reports    => bag transfer source)
...
│   │       │   └── [4.0K]  reports
...
│   │       │       ├── [4.4K]  bulk_extractor_report.pdf
...
│   ├── [  45]  metadata.csv                  => (metadata added by automation 
│   ├── [  44]  netx.json                     => tools pre-transfer scripts)
│   └── [4.0K]  submissionDocumentation
├── [4.0K]  objects
...
└── [5.9K]  processingMCP.xml
```
The error message in the failed `Job: Store file modification dates` shows that failure occurred because Archivematica was looking for one of the original bag metadata files under `metadata` (while it is actually under `metadata/metadata`):
```
Module storeFileModificationDates_v0.0
...
Standard streams
Standard error (stderr)
...
OSError: [Errno 2] No such file or directory: '/var/archivematica/sharedDirectory/watchedDirectories/
workFlowDecisions/extractPackagesChoice/
<TRANSFERNAME-UUID>/metadata/submissionDocumentation/BitCurator_reports/reports/bulk_extractor_report.pdf'
```

The problematic directory structure (double `metadata` directory) seems to be produced by a bug in the [`verify_and_restructure_transfer_bag.py`](https://github.com/artefactual/archivematica/blob/ef3af9fb58ac700dfca2a350095ef13a0c396e9c/src/MCPClient/lib/clientScripts/verify_and_restructure_transfer_bag.py) client script 

**Testing notes**

**[RS]** I am adding this bag that I've created which I believe will enable testers to observe the behavior without automation tools. With `1.10` either unzip and run as an unzipped bag, or run as a zipped bag and it will fail at characterization:

[Issue-1022-DemoTransferCSV.zip](https://github.com/archivematica/Issues/files/3961198/Issue-1022-DemoTransferCSV.zip)

I see the following trace in the microservice output:

```
[Errno 2] No such file or directory: '/var/archivematica/sharedDirectory/watchedDirectories/workFlowDecisions/extractPackagesChoice/DemoTransferCSV-9342cb5a-c4df-454f-a7ee-29fac288cd2f/metadata/submissionDocumentation/Agreement-Gift-MBRS-project.pdf'Traceback (most recent call last):
  File "/src/MCPClient/lib/job.py", line 111, in JobContext
    yield
  File "/src/MCPClient/lib/clientScripts/store_file_modification_dates.py", line 75, in call
    main(transfer_uuid, shared_directory_path)
  File "/src/MCPClient/lib/clientScripts/store_file_modification_dates.py", line 62, in main
    transfer_file.modificationtime = get_modification_date(file_path)
  File "/src/MCPClient/lib/clientScripts/store_file_modification_dates.py", line 39, in get_modification_date
    mod_time = os.path.getmtime(file_path)
  File "/usr/lib/python2.7/genericpath.py", line 62, in getmtime
    return os.stat(filename).st_mtime
OSError: [Errno 2] No such file or directory: '/var/archivematica/sharedDirectory/watchedDirectories/workFlowDecisions/extractPackagesChoice/DemoTransferCSV-9342cb5a-c4df-454f-a7ee-29fac288cd2f/metadata/submissionDocumentation/Agreement-Gift-MBRS-project.pdf'
```

I think the file it's failing on will be arbitrary, seeing also it fail with:
```
[Errno 2] No such file or directory: '/var/archivematica/sharedDirectory/watchedDirectories/workFlowDecisions/extractPackagesChoice/d2-de78997d-4dbe-46ed-a1a9-2443cbdb721f/metadata/metadata.csv'Traceback (most recent call last):
  File "/src/MCPClient/lib/job.py", line 111, in JobContext
    yield
  File "/src/MCPClient/lib/clientScripts/store_file_modification_dates.py", line 75, in call
    main(transfer_uuid, shared_directory_path)
  File "/src/MCPClient/lib/clientScripts/store_file_modification_dates.py", line 62, in main
    transfer_file.modificationtime = get_modification_date(file_path)
  File "/src/MCPClient/lib/clientScripts/store_file_modification_dates.py", line 39, in get_modification_date
    mod_time = os.path.getmtime(file_path)
  File "/usr/lib/python2.7/genericpath.py", line 62, in getmtime
    return os.stat(filename).st_mtime
OSError: [Errno 2] No such file or directory: '/var/archivematica/sharedDirectory/watchedDirectories/workFlowDecisions/extractPackagesChoice/d2-de78997d-4dbe-46ed-a1a9-2443cbdb721f/metadata/metadata.csv'
```

Outside of `1.10` and in `qa/1.x` I see the transfer fail at scan for viruses before the patch is applied:

```
archivematicaclamscan_v0.0: INFO      2019-12-13 15:23:29,106  archivematica.mcp.client.clamscan.scan_file:347  Using scanner ClamAV (clamd) (ClamAV 0.99.2 - 25662/Fri Dec 13 09:56:54 2019)
archivematicaclamscan_v0.0: INFO      2019-12-13 15:23:29,106  archivematica.mcp.client.clamscan.pass_by_stream:184  File contents being streamed to Clamdscan.
archivematicaclamscan_v0.0: ERROR     2019-12-13 15:23:29,115  archivematica.mcp.client.clamscan.clamd_exception_handler:160  Virus scanning failed: [Errno 2] No such file or directory: '/var/archivematica/sharedDirectory/currentlyProcessing/Issue-1022-DemoTransferCSV-d210e540-37f7-44d6-ad83-b52d605863fe/metadata/metadata.csv'
Traceback (most recent call last):
  File "/src/MCPClient/lib/clientScripts/archivematica_clamscan.py", line 124, in scan
    result = getattr(self, method_name)(path)
  File "/src/MCPClient/lib/clientScripts/archivematica_clamscan.py", line 185, in pass_by_stream
    return self.client.instream(open(path))
IOError: [Errno 2] No such file or directory: '/var/archivematica/sharedDirectory/currentlyProcessing/Issue-1022-DemoTransferCSV-d210e540-37f7-44d6-ad83-b52d605863fe/metadata/metadata.csv'
archivematicaclamscan_v0.0: INFO      2019-12-13 15:23:29,116  archivematica.mcp.client.clamscan.scan_file:361  File /var/archivematica/sharedDirectory/currentlyProcessing/Issue-1022-DemoTransferCSV-d210e540-37f7-44d6-ad83-b52d605863fe/metadata/metadata.csv scanned!
archivematicaclamscan_v0.0: INFO      2019-12-13 15:23:29,116  archivematica.mcp.client.clamscan.queue_event:243  Recording new event for file 9d7f8fde-c228-4c59-82ec-217e24b2f09c (outcome: Fail)
```

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged (if applicable)
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by hakamine** [comment]
Fixed by https://github.com/artefactual/archivematica/pull/1517

**Comment by sallain** [comment]
This has been tested and works in MoMA's 1.8 environment but should be tested on a qa instance to ensure that it will continue to work when MoMA upgrades.

**Comment by ablwr** [comment]
Tested in qa/1.x on Ubuntu Bionic via Docker (last commit: https://github.com/artefactual/archivematica/commit/baf565e4abc3bcf9480ee0784734ce9b0b223f63)
