### ISSUE TITLE
Problem: urllib3 dependency is outdated

### ISSUE THREAD

**Issue by sevein** [archivematica/Issues#1025]
**Expected behaviour**
We should use urllib3 1.24.2 or newer.

**Current behaviour**
Our project depends on urllib3 1.24.1.

**Your environment (version of Archivematica, operating system, other relevant details)**
qa/1.x

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged (if applicable)
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by ross-spencer** [comment]
As a by-product, the commit [here](https://github.com/artefactual/archivematica/pull/1531/files) moves the dependency to `urllib3==1.24.3` so we can place this in review.

**Comment by replaceafill** [comment]
As @ross-spencer mentions in the previous https://github.com/archivematica/Issues/issues/1025#issuecomment-569852648 we're now using `urllib3==1.24.3` which [is the highest possible `1.24.x` version supported by `requests==2.21.0`](https://github.com/psf/requests/blob/5a1e738ea9c399c3f59977f2f98b083986d6037a/setup.py#L47) which is the `requests` version all the components (except the MCPServer) currently use.
