### ISSUE TITLE
Problem: Typo in AUTH_LDAP_GROUP_SEARCH_FILTERSTR variable name

### ISSUE THREAD

**Issue by mamedin** [archivematica/Issues#1026]
**Expected behaviour**

The [Dashboard README.md]( https://github.com/artefactual/archivematica/blob/qa/1.x/src/dashboard/install/README.md) file should show the same variable name for LDAP GROUP FILTER than the one used in code.

**Current behaviour**

In README.md file it is `AUTH_LDAP_GROUP_SEARCH_BASE_FILTERSTR`:

https://github.com/artefactual/archivematica/blob/qa/1.x/src/dashboard/install/README.md:

But in code we are using `AUTH_LDAP_GROUP_SEARCH_FILTERSTR` (missing `_BASE` string):

https://github.com/artefactual/archivematica/blob/qa/1.x/src/dashboard/src/settings/components/ldap_auth.py#L18
https://github.com/artefactual/archivematica/blob/qa/1.x/src/dashboard/src/settings/components/ldap_auth.py#L50

**Steps to reproduce**

N/A

**Your environment (version of Archivematica, operating system, other relevant details)**

AM qa/1.x

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged (if applicable)
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by sallain** [comment]
@mamedin feel free to fix for 1.11!

**Comment by ablwr** [comment]
I'll grab this one

**Comment by replaceafill** [comment]
@ablwr Does the [Storage Service README](https://github.com/artefactual/archivematica-storage-service/blob/qa/0.x/install/README.md) need the same update?

**Comment by ablwr** [comment]
Oh yes, nice catch @replaceafill! I see it here: https://github.com/artefactual/archivematica-storage-service/blob/stable/0.15.x/storage_service/storage_service/settings/base.py#L369

I'll update this quickly too.
