### ISSUE TITLE
Problem: Broken link(s) on Storage Service README and rewrite of URL patterns may be incorrect

### ISSUE THREAD

**Issue by ross-spencer** [archivematica/Issues#1029]
**Version of the documentation**

The production installation [link](https://github.com/artefactual/archivematica-storage-service/tree/302c8825a35173df886003694afac5c60059e83b#installation) in the storage service README is broken. 

**Page (and section, if applicable) where the issue occurs**

As above.

**Description of the issue**

The link goes to (sorry about the verbosity):

* https://www.archivematica.org/docs/latest/admin-manual/installation/installation/

Which resolves at time of writing as:

![image](https://user-images.githubusercontent.com/1880412/70670896-6ff87b80-1c48-11ea-8c7f-e1d80e9817da.png)

So it may need to go to:

* https://www.archivematica.org/en/docs/latest/admin-manual/installation-setup/installation/installation/

Or possibly:

* https://www.archivematica.org/en/docs/storage-service-0.15/install/#install

Except that second one also wont work if changed to:

* https://www.archivematica.org/en/docs/latest/install/#install

**Suggested fix**

1. Correct the link at a minimum.
2. Look up .htaccess (?) on the server and ensure the storage service docs can resolve when not given a version, i.e. they can dynamically resolve to the `latest` docs given that argument. (I'm not sure if they're supposed to).
3. Audit the rest of the links on that page to check in-case anything else is broken. 

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by sallain** [comment]
Thanks @ross-spencer - for some reason, we didn't add the `latest` resolver to the SS docs when we added it to the AM docs. There was an [old issue](https://github.com/artefactual/archivematica-docs/issues/39) for this that I've now replaced with #1030.

**Comment by ross-spencer** [comment]
Ah, cool, thanks @sallain.

**Comment by sallain** [comment]
@ross-spencer Should the link to the development installation be pointing to the Ansible & Vagrant wiki instructions? Should I replace it with the link to Docker instead?

**Comment by ross-spencer** [comment]
Ah, great catch @sallain Docker would be perfect for that one!
