### ISSUE TITLE
Problem: Failure Report not generated when email not configured

### ISSUE THREAD

**Issue by joel-simpson** [archivematica/Issues#1033]
**Expected behaviour**
When a Transfer fails the Failed Transfer Microservice is called and a Failure report should be generated and made accessible from the Administration --> Failures screen; regardless of whether the failure report could be emailed or not. 

**Current behaviour**
When the Failed Transfer Microservice attempts to email a failure report but can't, no failure report is produced, and nothing is visible from the Admin screen. 
![Screenshot from 2019-12-13 17-47-57](https://user-images.githubusercontent.com/17187309/70837327-4fa7f880-1dd1-11ea-92c3-0cc1b4bb867b.png)
![Screenshot from 2019-12-13 17-45-09](https://user-images.githubusercontent.com/17187309/70837333-52a2e900-1dd1-11ea-9390-5ac42ff3321d.png)

**Steps to reproduce**
Don't configure email correctly when deploying Archivematica. Choose any transfer that will fail (e.g. because it has invalid checksums included). The transfer will fail; you'll get a warning that an email could not be sent; but you won't see the failure report in the dashboard. 

**Your environment (version of Archivematica, operating system, other relevant details)**
Testing using qa/1.x (from week of Dec 10). No smtp server is configured. Our environment is in a secure data centre without access to internet; so we will not be attempting to configure or use email. But for this very reason, we'd like to be able to see Failure Reports in the dashboard. 

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged (if applicable)
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by sallain** [comment]
Related to archivematica/Issues#709

**Comment by ross-spencer** [comment]
Related to https://github.com/archivematica/Issues/issues/1397 (a fix to one might enable us to close the other)
