### ISSUE TITLE
Responsive top menu on dashboard blocks view of content

### ISSUE THREAD

**Issue by jfcarrano** [archivematica/Issues#1034]
**Expected behaviour**
Responsive top menu on Archivematica dashboard should be responsive to resizing of browser and allow for dashboard processes to be seen.

**Current behaviour**
Responsive top menu on Archivematica dashboard blocks content of dashboard when resizing 
browser window and does not allow for scrolling past it to see content. 
![header_BlockingDashboard](https://user-images.githubusercontent.com/22666196/71015001-deae5c80-20c0-11ea-904b-40827fffa3f4.png)

**Steps to reproduce**
1. Open Archivematica dashboard. 
2. Resize browser to 50% or less of maximum screen size.

**Your environment (version of Archivematica, operating system, other relevant details)**
Archivematica 1.10.1, Firefox 68.3.0esr (32-bit), Chrome Version 79.0.3945.79 (Official Build) (64-bit)

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged (if applicable)
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by sallain** [comment]
@jfcarrano Thanks for filing this! Definitely something that has bothered all of us at one time or another but has never been reported.

**Comment by jraddaoui** [comment]
Addressed in https://github.com/artefactual/archivematica/pull/1604.

Attached in that PR are two GIFs from before and after the fixes. One thing that is not noticeable in there is that we'll loose the fixed header with those changes (it will disappear when you scroll down).  We discussed the implementation of an expandable menu to be able to keep that fixed header without taking half the page in smaller widths but we may want to do it in a different issue and PR.

**Comment by sallain** [comment]
@jraddaoui this is really nice! I've got it working in my Docker env running qa/1.x and it behaves just like the GIFs above.

If I had tested this during a release process, I'd have closed it at this point; however I'm going to leave the issue open for now so that we can talk about the best way to close off issues in our new working style.

**Comment by sallain** [comment]
Tested on 1.11.2 on Centos and this is working as expected.
