### ISSUE TITLE
Problem: Missing string substitution in a dashboard log

### ISSUE THREAD

**Issue by alexwlchan** [archivematica/Issues#1038]
**Expected behaviour**
Interesting information is printed into the logs.

**Current behaviour**
I got an error when trying to start a transfer in the dashboard:

```
ERROR     2019-12-20 10:26:01  archivematica.dashboard:views:_package_create:831:  Package cannot be created: %s failed (check the logs)
```

That `%s` looks suspiciously like a string substitution gone wrong!

**Steps to reproduce**
Not sure, I hit it once while starting a transfer.

**Your environment (version of Archivematica, operating system, other relevant details)**
Our custom fork of Archivematica at Wellcome, based on v1.10.x.

Fix available in https://github.com/artefactual/archivematica/pull/1527

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged (if applicable)
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by ablwr** [comment]
Any hints as to how to recreate this issue, @alexwlchan? I tried mussing things up a bit (gearman in particular) but didn't have any luck.

**Comment by alexwlchan** [comment]
@ablwr Sorry, no idea! I hit it once, and when I retried the transfer it worked again. It was a simple enough patch that I didn't spent time trying to come up with a repro.

**Comment by ablwr** [comment]
@alexwlchan I agree! Although @sromkey will have to be the judge of letting this pass into the Closed Zone instead of me.

**Comment by sromkey** [comment]
lol @ "Closed Zone." Let's mark it as closed, we can always re-open if it emerges again in the future!
