### ISSUE TITLE
Problem: Dataverse integration documentation "optional fields" are not optional in the Storage Service

### ISSUE THREAD

**Issue by ablwr** [archivematica/Issues#1043]
**Expected behaviour**
According to the current [documentation](https://www.archivematica.org/en/docs/storage-service-0.15/administrators/#dataverse), `Agent name`, `Agent type`, and `Agent identifier` definitions say "This field is optional."

**Current behaviour**
When creating a Dataverse space, the three above fields must be filled out in order to save the space. Otherwise, this error appears for each:

![Screenshot from 2020-01-07 11-27-02](https://user-images.githubusercontent.com/3260492/71910807-9a066600-3140-11ea-8a64-27a209888586.png)

**Steps to reproduce**
1. Create a space for Dataverse
2. Fill out the usual required fields, but not the last three fields (`Agent name`, `Agent type`, and `Agent identifier`)

**Your environment (version of Archivematica, operating system, other relevant details)**
1.10.2 and qa/1.x

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged (if applicable)
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by sromkey** [comment]
@joel-simpson Do you recall whether these fields should be optional or not?

**Comment by ross-spencer** [comment]
I'll await Joel's thoughts on what was required in the previous Dataverse effort. 

Separate from that, there are a few things we know:

* The docs describe this as [optional](https://www.archivematica.org/en/docs/storage-service-0.15/administrators/#dataverse), but,
* We have a single migration for Dataverse in the storage-service [here](https://github.com/artefactual/archivematica-storage-service/commit/1adcb61a646dbcbd9575fcdf3129561c52cbaad0) going back to `0.9` which never configured this as optional. 
* The agents used in the storage service for Dataverse are tied to [parse_dataverse_mets.py](https://github.com/artefactual/archivematica/blob/6946cb55158ca3fe33e2504c358ace79b1be1ed5/src/MCPClient/lib/clientScripts/parse_dataverse_mets.py#L147-L174) but if the `agents.json` file isn't available then we'll see a database error without an agent to write that is associated with the dataset. 
* If we hack the database to simulate the agent information not being set but `agents.json` is output then they're still picked up in AIP METS but show as blank
```
  <premis:linkingAgentIdentifier>
    <premis:linkingAgentIdentifierType>URI</premis:linkingAgentIdentifierType>
    <premis:linkingAgentIdentifierValue></premis:linkingAgentIdentifierValue>
  </premis:linkingAgentIdentifier>
```
So there'd be a few modifications to make to make across the two systems to them optional. There may be a few solutions if this were considered desirable.

**Comment by joel-simpson** [comment]
I can't say I recall @sromkey whether there was some idea that this should be optional, but I doubt that it was intentional. The key requirement was to record some of the provenance using the dataverse premis agent; I can't really see why you wouldn't want to do this, and filling in premis agent information is hardly onerous. 

Looks like the workflow would fail given what @ross-spencer has pointed out (thanks for the info Ross) so I'd say we should leave the system behaviour as-is and fix the documentation to indicate that these fields are mandatory.
