### ISSUE TITLE
Problem: Tesseract is out of 4.0.0-beta and 4.1.1 available

### ISSUE THREAD

**Issue by ross-spencer** [archivematica/Issues#1045]
**Please describe the problem you'd like to be solved**

It stands out that in current environments we're using a beta release of tesseract 4.0.0:

```
Transcribing original 83709451-7068-499e-8d7f-5eda5dacc56b
Tesseract Open Source OCR Engine v4.0.0-beta.1 with Leptonica
```

**Describe the solution you'd like to see implemented**

Keep tools up-to-date for the latest bug fixes, optimizations, and best performance for users of the system. 

[4.1.1](https://github.com/tesseract-ocr/tesseract/releases) is now available. And 4.0.0 is out of beta.

Additionally, as we wrap so many different tools, where interfaces aren't changed between updates, is this something we should be considering more carefully per release cycle? 

**Describe alternatives you've considered**

Not replacing it. There will likely only be a measurable impact for some users and use-cases. 

**Additional context**

Output while thoroughly testing the transcribe workflow in AM `qa/1.x`.

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged
- [ ] Details about this issue have been added to the release notes

**Comment by scollazo** [comment]
We usually rely on the operating systems ( Ubuntu / Centos / Redhat ) to update the package on their side.

We have had issues in the past when a new version of a tool is added to the upstream repositories, and the interface changes, so this might be worth exploring.

**Comment by ross-spencer** [comment]
Ah, that makes sense.Thanks Santi. I'll close this and it can be discussed outside of this channel, or reopened if it is relevant to someone.

Related to https://github.com/archivematica/Issues/issues/522
