### ISSUE TITLE
Problem: Handle.net integration is limited to custom IISH work and should be noted

### ISSUE THREAD

**Issue by ablwr** [archivematica/Issues#1046]
**Version of the documentation**
1.10+

**Page (and section, if applicable) where the issue occurs**
https://www.archivematica.org/en/docs/archivematica-1.10/admin-manual/installation-setup/integrations/handlenet-setup/, et al

**Description of the issue**
The Archivematica documentation notes the integration of the Handle System as a possible way for people using the system to use the "Bind PIDs?" option in Archivematica to mint persistent identifiers. However, this integration is in use by IISH and not possible without some customized work creating a web service, or by integrating this IISH-specific one: https://github.com/IISH/PID-webservice

**Suggested fix**
Update the docs to let the above information be clearly known, so that folks aren't under the impression that they can create a simple integration.

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [x] All pull requests related to this issue are properly linked
- [x] All pull requests related to this issue have been merged
- [x] Details about this issue have been added to the release notes (if applicable)

**Comment by ablwr** [comment]
@sallain did this :muscle: !

**Comment by sallain** [comment]
Thanks @ablwr!
