### ISSUE TITLE
Problem: Centos/RHEL 8 is unsupported

### ISSUE THREAD

**Issue by scollazo** [archivematica/Issues#1047]
**Expected behaviour**

Archivematica works in the latest stable Centos/RHEL version

**Current behaviour**

Archivematica doesn't work on Centos/RHEL 8

**Steps to reproduce**

Try to install archivematica using a Centos 8 base server

**Your environment (version of Archivematica, operating system, other relevant details)**

Archivematica qa/1.x, Centos 8

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged (if applicable)
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by ross-spencer** [comment]
Via Tessa: https://www.redhat.com/en/blog/faq-centos-stream-updates: 

Looks like CentOS is going to be (slowly) phased out: https://www.redhat.com/en/blog/faq-centos-stream-updates

Q: What about the other releases of CentOS Linux?
* There will not be a CentOS Linux 9.
* Updates for the CentOS Linux 8 distribution continue until December 31, 2021.
* Updates for the CentOS Linux 7 distribution continue as before until June 30, 2024.
* Updates for the CentOS Linux 6 distribution ended November 30, 2020.”

**Comment by sromkey** [comment]
> Via Tessa: https://www.redhat.com/en/blog/faq-centos-stream-updates:
> 
> Looks like CentOS is going to be (slowly) phased out: https://www.redhat.com/en/blog/faq-centos-stream-updates
> 
> Q: What about the other releases of CentOS Linux?
> 
> * There will not be a CentOS Linux 9.
> * Updates for the CentOS Linux 8 distribution continue until December 31, 2021.
> * Updates for the CentOS Linux 7 distribution continue as before until June 30, 2024.
> * Updates for the CentOS Linux 6 distribution ended November 30, 2020.”

This seems like a good argument for closing this issue? The effort doesn't seem worth it to support an OS for exactly one calendar year :roll_eyes:

**Comment by ross-spencer** [comment]
@sromkey that seems reasonable, though it will be interesting to hear what support folks might need in the wider world. So a tentative narrow-field of vision +! here :slightly_smiling_face: 

You might have already been thinking ahead on this, but if CentOS 8 isn't to be supported then then it might still be a good idea to use this ticket as an opportunity to update the documentation here https://www.archivematica.org/en/docs/archivematica-1.12/admin-manual/installation-setup/installation/installation/ and make some statement about it? maybe just the details above? Coming from a perspective that it seems reasonable we might once have supported it until the news yesterday.

**Comment by sromkey** [comment]
> You might have already been thinking ahead on this, but if CentOS 8 isn't to be supported then then it might still be a good idea to use this ticket as an opportunity to update the documentation here https://www.archivematica.org/en/docs/archivematica-1.12/admin-manual/installation-setup/installation/installation/ and make some statement about it? maybe just the details above? Coming from a perspective that it seems reasonable we might once have supported it until the news yesterday.

For sure- the SAD-Support collab has been coincidentally wanting to start a conversation on supported OS's, more to say about that soon!

**Comment by scollazo** [comment]
A first attempt has been made, and is available in https://github.com/artefactual/deploy-pub/tree/wip/centos8/playbooks/archivematica-centos8


The main changes have been

 - Update roles and use dnf in some cases
 - Create/update osdeps files
 - Remove fits, nailgun and ufraw packages (fits is disabled by default for now)
 - Add a new development repo with centos8-extras packages

**Comment by sromkey** [comment]
We've now phased Centos support out and phased in Rocky Linux.
