### ISSUE TITLE
Problem: Pointer file for reingested AIP has two compression Events, one linked to a non-existent Agent

### ISSUE THREAD

**Issue by evelynPM** [archivematica/Issues#1062]
**Expected behaviour**
A pointer file for a reingested AIP has the same structure and content as for an AIP that hasn't been reingested.

**Current behaviour**
The pointer file for a reingested AIP has an additional compression Event. This Event  has Archivematica-Storage-Service-0.15.0 as a linkingAgentIdentifier but there is no Archivematica-Storage-Service-0.15.0 Agent.

``` 
    <mets:digiprovMD ID="digiprovMD_11" CREATED="2020-01-15T17:14:34">
      <mets:mdWrap MDTYPE="PREMIS:EVENT">
        <mets:xmlData>
          <premis:event xmlns:premis="http://www.loc.gov/premis/v3" xsi:schemaLocation="http://www.loc.gov/premis/v3 http://www.loc.gov/standards/premis/v3/premis.xsd" version="3.0">
            <premis:eventIdentifier>
              <premis:eventIdentifierType>UUID</premis:eventIdentifierType>
              <premis:eventIdentifierValue>bf1c7db4-c983-439f-a705-878e3149f431</premis:eventIdentifierValue>
            </premis:eventIdentifier>
            <premis:eventType>compression</premis:eventType>
            <premis:eventDateTime>2020-01-15T17:14:34</premis:eventDateTime>
            <premis:eventDetailInformation>
              <premis:eventDetail>program="7z"; version="p7zip Version 9.20 (locale=en_US.UTF-8,Utf16=on,HugeFiles=on,2 CPUs)"</premis:eventDetail>
            </premis:eventDetailInformation>
            <premis:eventOutcomeInformation>
              <premis:eventOutcome>success</premis:eventOutcome>
              <premis:eventOutcomeDetail>
                <premis:eventOutcomeDetailNote></premis:eventOutcomeDetailNote>
              </premis:eventOutcomeDetail>
            </premis:eventOutcomeInformation>
            <premis:linkingAgentIdentifier>
              <premis:linkingAgentIdentifierType>preservation system</premis:linkingAgentIdentifierType>
              <premis:linkingAgentIdentifierValue>Archivematica-Storage-Service-0.15.0</premis:linkingAgentIdentifierValue>
            </premis:linkingAgentIdentifier>
          </premis:event>
        </mets:xmlData>
      </mets:mdWrap>
    </mets:digiprovMD>
```

**Steps to reproduce**
Reingest an AIP and view the pointer file.

**Your environment (version of Archivematica, operating system, other relevant details)**
AM 1.11-qa (xenial)

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged (if applicable)
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by evelynPM** [comment]
I'm labelling this as a regression, because in AM 1.10.1 the second compression Event is there but so is the related Agent. The Agent seems to have disappeared in 1.11-qa. So we should either remove the second compression Event or keep it and add the Agent back.

**Comment by sromkey** [comment]
It seems sensible to remove the second compression Event since it's no longer relevant.

**Comment by replaceafill** [comment]
@evelynPM @sromkey I have a couple of questions:

1. I'm wondering if this is a regression from 1.10.1 or if I'm missing something. I just tested a metadata-only reingest (no replication or encryption) in the sandbox and this is the [original pointer file](https://github.com/archivematica/Issues/files/4126698/1.10.1.txt) and this is the [reingested one](https://github.com/archivematica/Issues/files/4126700/1.10.1-reingest.txt). I see the second compression event but not the SS agent in the pointer file of the reingest.

2. It seems like an encrypted setup also creates the second compression event in the pointer file of the reingest but it also creates the SS agent (sorry that I can't provide samples at the moment, my dev instance is broken). I'm wondering if we should we consider the second compression event no longer relevant in this case too?

**Comment by evelynPM** [comment]
Now I'm not sure it's a regression either, @replaceafill, since I can't recreate the 1.10.1 pointer file with the SS Agent. In any case, whether or not the second compression event is relevant depends on why it's being created. Is compression actually happening twice? If not, then it would seem like a good idea to get rid of the second event.

**Comment by replaceafill** [comment]
@evelynPM Yes, AIPs are compressed twice during reingest:

1. The "Prepare AIP -> Compress AIP" job compresses the AIP in the AM side and [generates a `compression` event](https://github.com/artefactual/archivematica/blob/46273947514507d7c51bba581fe0ff6e1966af4d/src/MCPClient/lib/clientScripts/compress_aip.py#L129-L142) with the AM agents. At this point even though a new compressed file has been generated, the rest of the directories and files are still present.

2. Later in the "Store AIP -> Store AIP" job [the SS is called passing it the information of the first compression event](https://github.com/artefactual/archivematica/blob/46273947514507d7c51bba581fe0ff6e1966af4d/src/MCPClient/lib/clientScripts/store_aip.py#L68-L81). The SS finishes the reingest by [generating a new compressed AIP](https://github.com/artefactual/archivematica-storage-service/blob/a5045c356466dbe117e397fc0b68663f14bc90b1/storage_service/locations/models/package.py#L2381-L2391) and [inserting the second `compression` event](https://github.com/artefactual/archivematica-storage-service/blob/a5045c356466dbe117e397fc0b68663f14bc90b1/storage_service/locations/models/package.py#L2651-L2655). The problem with this second event is that [it carries the SS agent as a linked agent](https://github.com/artefactual/archivematica-storage-service/blob/a5045c356466dbe117e397fc0b68663f14bc90b1/storage_service/common/premis.py#L145-L146), but the SS agent is not added to the pointer file unless the space (like an encrypted one) does it as a "storage effect".

If we decide to keep this second event, we should make sure the SS agent is always included after the second compression.

**Comment by ross-spencer** [comment]
nice spot @replaceafill. I was interested to check two things about the second compression event. 

1. What compression algorithm was being used: reading the code, and testing shows, the algorithm as selected in the dashboard, e.g. if you select `7Zip uncomp` to get that on reingest: ✔️ 
2. Whether a verification check e.g like `Module verifyAIP_v1.0` was called in the storage service for the second compression: ❌ (as far as I read it)

Aside from the redundancy, it seems that the lack of verification also leaves open the small opportunity for the zip process to introduce side-effects to the AIP package.

**Comment by replaceafill** [comment]
That seems accurate according to my reading/testing @ross-spencer :+1:

**Comment by sallain** [comment]
After lots and lots of discussion, we cannot determine a reason for the second compression event. Since the agent issue is happening on the second compression event, we've come up with the following plan:

1. @replaceafill is going to try removing the second compression event.
2. Then we'll test to see what breaks. If nothing breaks, great! That should solve the agent issue, because the second compression event will never happen.
3. If things break, we will evaluate the effort required to fix them. If the amount of effort required is a lot, we might have to defer this issue to the next release.

We could, in theory, just fix the agent issue, but the double-compression issue actually seems like a more important thing to fix, as per comments by @replaceafill and @ross-spencer above.

**Comment by sallain** [comment]
We decided to fix this by removing the second PREMIS event from the pointer file and removing the second compression action that occurs in the Storage Service (issue #1095). This is the first part of that work. We plan to do the second part in a point release.

For now, there is one compression event appearing in the pointer file for a reingested AIP. Tested on qa/1.x on Bionic.
