### ISSUE TITLE
Problem: Behavior of verify transfer compliance has changed in qa/1.x --> 1.11 

### ISSUE THREAD

**Issue by ross-spencer** [archivematica/Issues#1063]
**Expected behaviour**

Verify transfer compliance pauses and generates a decision point. See below screenshot from `1.10.1` (it is difficult to describe)

![image](https://user-images.githubusercontent.com/1880412/72471193-23a4dc00-37b0-11ea-9e6f-b1f4644311cb.png)

**Current behaviour**

The microservice group processes through to `Failed compliance`, forks, and then creates a separate new transfer which contains the single job `Find a branch to continue processing`. This creates a new active transfer in AM that never stops and exaggerates the behavior of https://github.com/archivematica/Issues/issues/1055. 

See the screenshot below:

![image](https://user-images.githubusercontent.com/1880412/72471261-4df69980-37b0-11ea-9b2c-9fea0fcda1c4.png)

This started as the same transfer.

The reason that the second "Transfer" remains active and doesn't move through the workflow is that it cannot look up the right variable link pull in the database. 

The reason for the branching is as-of-yet unknown to me. 

**Steps to reproduce**

1. Create a transfer with no objects in it. 
2. Start the transfer.
3. The behavior will quickly occur. 

**Your environment (version of Archivematica, operating system, other relevant details)**

Tested locally but verified on Xenial and a 1.10.1 server.

**Additional information**

Other combinations of transfer compliance failures you can use:

1. A transfer consisting of just one hidden file (empty).
2. A transfer consisting of just one hidden file (containing data).
3. A transfer consisting of just one empty folder below the top-level folder.

Notes here related to https://github.com/artefactual/archivematica-sampledata/issues/28 

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged (if applicable)
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by ross-spencer** [comment]
The `Find branch to continue processing` microservice job is connected to the `autoRestructureForCompliance` watched directory and one opportunity to reduce the complexity of the system here (once the root cause is known) is to modify the verify for transfer compliance directory microservice and remove the use of this directory, simply failing the transfer. This would make the fix for #1055 a touch easier. It has been suggested in the past as well [here](https://github.com/artefactual/archivematica/pull/948#issuecomment-371230551).

**Comment by ross-spencer** [comment]
Chatting to @replaceafill it looks like https://github.com/artefactual/archivematica/pull/1570/commits/f750532b30eb5896aa8c12de423fefec128aaeea will fix this issue once merged, running in the test branch seems to confirm that for me:

![image](https://user-images.githubusercontent.com/1880412/74999154-ce9c5b80-5428-11ea-9dcb-0aff0a652732.png)

So I think once we confirm https://github.com/artefactual/archivematica/pull/1570 and merge that, we can probably close this one (as it was a related regression) entirely!

**Comment by sallain** [comment]
I think this is fixed - if I start an empty transfer, it fails compliance check and ends up at a decision point, `Job: Attempt restructure for compliance?`

![image](https://user-images.githubusercontent.com/4612276/75497774-2e8b8880-597a-11ea-97db-acd2ce53b1c4.png)

From here I have three options: 

![image](https://user-images.githubusercontent.com/4612276/75497824-4ebb4780-597a-11ea-8d97-1827a2c213d2.png)

I'm not quite sure what `Move transfer back to activeTransfers directory` does, but I presume it (and `Attempt restructure for compliance`) give the user a chance to address any issues and then retry the compliance check, as it seems to loop the transfer back through the previous jobs. That seems logical, though I didn't test it substantively. `Reject transfer` rejects the transfer, as expected.

Tested on qa/1.x on Bionic.
