### ISSUE TITLE
Problem: rebuild_elasticsearch_aip_index_from_files issues

### ISSUE THREAD

**Issue by hakamine** [archivematica/Issues#1064]
**Expected behaviour**
The `rebuild_elasticsearch_aip_index_from_files` management command should be flexible enough to work in different scenarios.

**Current behaviour**
When using `rebuild_elasticsearch_aip_index_from_files` on production client environments, found the following issues:

* It creates a temp directory (for storing AIP files required during processing) in the system's default location (normally /tmp in linux ). In some environments the partition/volume used for /tmp is limited in size, and the command fails when it becomes full.

* There are cases in which the indexes contain AIP data that needs to be deleted (e.g., an AIP was deleted from the storage service database/aipstore, but for some reason the archival storage tab still shows an entry for it). The management command does not provide a way to remove a specified AIP's data from the index (it provides a `--delete` option that deletes the AIP info from the index previous to re-indexing it, but this option is not useful to just delete the AIP info from the index)

**Steps to reproduce**
Run the management command under the conditions described above.

**Your environment (version of Archivematica, operating system, other relevant details)**
AM/SS 1.10/0.15

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged (if applicable)
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by ross-spencer** [comment]
Related to https://github.com/archivematica/Issues/issues/127

**Comment by sevein** [comment]
Adding the triage label since Héctor submitted a PR for it.

**Comment by hakamine** [comment]
@sromkey np, yes, I think the changes in the associated PR (#1538) are useful. Should I rebase?

**Comment by sevein** [comment]
I just did the rebase for you @hakamine. Both `--tmp-dir` and `--delete-only --uuid=...` are working great. I had to solve a couple of conflicts, please take a look at your pull request before I merge. Thanks.

**Comment by hakamine** [comment]
All good, thank you @sevein !

**Comment by sromkey** [comment]
Thanks both!!

**Comment by replaceafill** [comment]
I've verified that:
* The new options of the command are documented
* The `--delete-only` option deletes Elasticsearch data about an AIP in the `aips` and `aipfiles` indexes:
  ```
  $ make manage-dashboard ARG="rebuild_elasticsearch_aip_index_from_files --delete-only --uuid 113121a3-429a-448a-ad51-e50f9cf7ef3b /src/aips"
  ...
  INFO      2021-07-07 14:21:26  elasticsearch:base:log_request_success:194:  HEAD http://elasticsearch:9200/aips,aipfiles,transfers,transferfiles [status:200 request:0.005s]
  INFO      2021-07-07 14:21:26  archivematica.common:elasticSearchFunctions:create_indexes_if_needed:215:  All indexes already created.
  Deleting AIP 113121a3-429a-448a-ad51-e50f9cf7ef3b from aips/aip and aips/aipfile.
  INFO      2021-07-07 14:21:26  archivematica.common:elasticSearchFunctions:_delete_matching_documents:1440:  Deleting with query {'query': {'term': {'uuid': '113121a3-429a-448a-ad51-e50f9cf7ef3b'}}}
  INFO      2021-07-07 14:21:26  elasticsearch:base:log_request_success:194:  POST http://elasticsearch:9200/aips/_delete_by_query [status:200 request:0.058s]
  INFO      2021-07-07 14:21:26  archivematica.common:elasticSearchFunctions:_delete_matching_documents:1442:  Deleted by query {'took': 43, 'timed_out': False, 'total': 1, 'deleted': 1, 'batches': 1, 'version_conflicts': 0, 'noops': 0, 'retries': {'bulk': 0, 'search': 0}, 'throttled_millis': 0, 'requests_per_second': -1.0, 'throttled_until_millis': 0, 'failures': []}
  INFO      2021-07-07 14:21:26  archivematica.common:elasticSearchFunctions:_delete_matching_documents:1440:  Deleting with query {'query': {'term': {'AIPUUID': '113121a3-429a-448a-ad51-e50f9cf7ef3b'}}}
  INFO      2021-07-07 14:21:26  elasticsearch:base:log_request_success:194:  POST http://elasticsearch:9200/aipfiles/_delete_by_query [status:200 request:0.021s]
  INFO      2021-07-07 14:21:26  archivematica.common:elasticSearchFunctions:_delete_matching_documents:1442:  Deleted by query {'took': 18, 'timed_out': False, 'total': 14, 'deleted': 14, 'batches': 1, 'version_conflicts': 0, 'noops': 0, 'retries': {'bulk': 0, 'search': 0}, 'throttled_millis': 0, 'requests_per_second': -1.0, 'throttled_until_millis': 0, 'failures': []}
  ```
* The `--tmp-dir` option extracts the AIP in the specified directory:
  ```
  $ make manage-dashboard ARG="rebuild_elasticsearch_aip_index_from_files --tmp-dir /src/tmp /src/aips"
  ...
  Processing AIP e3a11bf4-7476-4808-b001-55dd497edd1b
  Command to run: ['unar', '-force-overwrite', '-o', '/src/tmp/tmp358g5qls', '/src/aips/DemoTransferCSV-automated-1.10-e3a11bf4-7476-4808-b001-55dd497edd1b.7z', 'DemoTransferCSV-automated-1.10-e3a11bf4-7476-4808-b001-55dd497edd1b/data/METS.e3a11bf4-7476-4808-b001-55dd497edd1b.xml']
  /src/aips/DemoTransferCSV-automated-1.10-e3a11bf4-7476-4808-b001-55dd497edd1b.7z: 7-Zip
  DemoTransferCSV-automated-1.10-e3a11bf4-7476-4808-b001-55dd497edd1b/data/METS.e3a11bf4-7476-4808-b001-55dd497edd1b.xml  (735736 B)... OK.
  Successfully extracted to "/src/tmp/tmp358g5qls/DemoTransferCSV-automated-1.10-e3a11bf4-7476-4808-b001-55dd497edd1b".
  ...
  ```
