### ISSUE TITLE
Problem: email field is inconsistently required in User forms

### ISSUE THREAD

**Issue by helrond** [archivematica/Issues#1067]
**Expected behaviour**
When submitting a form to create a user or update an existing user, I expect the same fields to be required.

**Current behaviour**
The email field is not required when creating a user, but is required when updating an existing user.

I'm happy to submit a PR to make this consistent (it's a one-line fix) but would like to know whether email should be required or not.

**Steps to reproduce**
1. Log into the dashboard and go to `Administration > Users`
2. Create a new user. Note email is not required.
3. Try to edit that same user. Email is now required.

**Your environment (version of Archivematica, operating system, other relevant details)**
AM 1.10, running in Docker.

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged (if applicable)
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by sromkey** [comment]
I don't see a reason why the user email should be required in either case. Thanks Hillel!

**Comment by sevein** [comment]
@helrond, let's make it a required field if you still have time to do so. It aligns better with what AtoM does, and we've also marked it as a mandatory field in our [install](https://github.com/artefactual/archivematica/blob/stable/1.10.x/src/dashboard/src/installer/management/commands/install.py) command used in some deployments.

**Comment by replaceafill** [comment]
@sevein Should we then consider making it required [in the Storage Service](https://github.com/artefactual/archivematica-storage-service/blob/70711272f5d07e3d39f05f0d0c4d75deec87a5b1/storage_service/administration/forms.py#L197) as well?

**Comment by helrond** [comment]
Should the change to the Storage Service be in this PR or in a different one?

**Comment by sromkey** [comment]
Fixed- if you try to make a new user without an email you are prompted to fill in the field, and you are also prompted to fill it in if you try to delete the email from an existing user.
