### ISSUE TITLE
Problem: getAMAgentsForFile adds additional organization and preservation system Agent links under certain circumstances

### ISSUE THREAD

**Issue by evelynPM** [archivematica/Issues#1072]
**Expected behaviour**
Premis Events generated by Archivematica are linked to 3 Agents.

**Current behaviour**
Under certain circumstances, Archivematica will add additional organization or preservation system Agent links to Events. This is because the the [`getAMAgentsForFile` helper](https://github.com/artefactual/archivematica/blob/baf565e4abc3bcf9480ee0784734ce9b0b223f63/src/archivematicaCommon/lib/databaseFunctions.py#L124) returns all the repository code and preservation system Agents for a file if an Agent can't be gathered first from the SIP or the transfer. Specifically [this part](https://github.com/artefactual/archivematica/blob/baf565e4abc3bcf9480ee0784734ce9b0b223f63/src/archivematicaCommon/lib/databaseFunctions.py#L150-L153) causes the issue.

**Steps to reproduce**
This problem can be reproduced in `qa` by using the the PREMIS Event importer or by adding a new agent with type `repository code` or `preservation system` directly through the database or the Django shell. Look for `repository code` in [this METS file](https://gist.github.com/replaceafill/409971b71dca9a2f77bed911dbbda711) of a `SampleTransfers/Images/pictures` transfer with this agent inserted through MySQL:

![Captura de pantalla de 2020-01-14 16-46-49](https://user-images.githubusercontent.com/560781/72389244-871a0580-36ed-11ea-9a61-b505a8f9fb15.png)

**Your environment (version of Archivematica, operating system, other relevant details)**

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged (if applicable)
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by sallain** [comment]
@evelynPM can you try reproducing this on one of the QA sites to see if it still occurs? Thanks!

**Comment by sromkey** [comment]
Tested on am qa/1.x , I'm no longer seeing the extra repository agent.
