### ISSUE TITLE
Problem: Dublin Core dmdSec not created if filename has diacritics

### ISSUE THREAD

**Issue by evelynPM** [archivematica/Issues#1073]
**Expected behaviour**
Processing a transfer with a metadata.csv file should result in a dmdSec for each row in the file.

**Current behaviour**
If the filename has diacritics, the dmdSec is not created.

**Steps to reproduce**
Start a transfer with a metadata.csv file and a file with a name like Montréal.txt. Open the resulting AIP mets file and look for the DC dmdSec.

**Your environment (version of Archivematica, operating system, other relevant details)**
AM 1.10.1, AM 1.11-qa (bionic)

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged (if applicable)
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by sallain** [comment]
This is working. Tested on qa/0.x on Bionic.
