### ISSUE TITLE
Problem: wording in filename cleanup scripts/logs does not match wording in UI

### ISSUE THREAD

**Issue by sallain** [archivematica/Issues#1079]
**Please describe the problem you'd like to be solved**
In #230 we changed the wording of the change filenames microservices, using "change filenames" (or similar) instead of "sanitize" or "clean up". However, the scripts themselves use the previous wording:

* `sanitizeObjectNames_v0.0` -- script for Transfer tab action
* `sanitizeSIPName_v0.0` -- script for Ingest tab action

The log names also use the previous wording:

* `data/logs/transfers/my-transfer-name/logs/filenameCleanup.log` -- log of changes made on Transfer tab
* `data/logs/filenameCleanup.log` -- log of changes made on Ingest tab

And the log contents do, as well:

```
Sanitized name: %transferDirectory%objects/Росси́я.png  -> %transferDirectory%objects/Rossiia.png
Sanitized name: %transferDirectory%objects/Éireann.png  ->  %transferDirectory%objects/Eireann.png
```

**Describe the solution you'd like to see implemented**
Over time, change the above areas (and any others I've missed) to be consistent with the changes that appear in the UI.

**Describe alternatives you've considered**
None.

**Additional context**

Related to #230 

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged
- [ ] Details about this issue have been added to the release notes

**Comment by sevein** [comment]
@sallain do you think it's safe to name filenameCleanup.log differently? I guess there is no much value in that file but it's part of the AIP.

Also, are we also looking into changing our PREMIS events? Our `eventType` is "name cleanup"; `eventDetail` and `eventDetailOutcome` use similar wording.

**Comment by replaceafill** [comment]
I've verified that:

* Most of the code and log messages have been adjusted accordingly
* The log file in the AIP is now called `filenameChanges.log`
* The PREMIS event type is now called `filename change` and its detail and note reflect the change:

  ```
            <premis:eventType>filename change</premis:eventType>
            <premis:eventDateTime>2021-07-07T13:57:41.267334+00:00</premis:eventDateTime>
            <premis:eventDetailInformation>
              <premis:eventDetail>prohibited characters removed: program="change_names"; version="1.10.7a907930df0a3033a2d12ad63c50b257c9cd8d71"</premis:eventDetail>
            </premis:eventDetailInformation>
            <premis:eventOutcomeInformation>
              <premis:eventOutcome></premis:eventOutcome>
              <premis:eventOutcomeDetail>
                <premis:eventOutcomeDetailNote>Original name="%transferDirectory%objects/artwork/Montréal.png"; new name="%transferDirectory%objects/artwork/Montreal.png"</premis:eventOutcomeDetailNote>
              </premis:eventOutcomeDetail>
            </premis:eventOutcomeInformation>
  ```
* The AMAUATs have been updated
