### ISSUE TITLE
Problem: `am services` command is out of date

### ISSUE THREAD

**Issue by ablwr** [archivematica/Issues#1080]
**Please describe the problem you'd like to be solved**
The Archivematica [admin-manual recommends](https://www.archivematica.org/en/docs/archivematica-1.10/admin-manual/maintenance/maintenance/#admin-faq) using the command `am services` for restarting Archivematica components. However, this command does not work.

This is how I restart services:

```
service gearmand restart
service archivematica-mcp-server restart
service archivematica-mcp-client restart
service archivematica-dashboard restart
service archivematica-storage-service restart
```

(except when `gearmand` is `gearman-job-server`)

**Describe the solution you'd like to see implemented**
1. Update the documentation when the standard way in which users should restart services within Archivematica.
2. Remove code for the `am services` scripts.

**Describe alternatives you've considered**
Update the `am services` script so that it works for all supported operating systems, and add a testing plan and plan for maintaining this script as these commands change.

**Additional context**

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged
- [ ] Details about this issue have been added to the release notes

**Comment by sromkey** [comment]
Looks like this was merged so closing!
