### ISSUE TITLE
Problem: GPG space and locations not created when using rpms and ansible

### ISSUE THREAD

**Issue by mamedin** [archivematica/Issues#1083]
**Expected behaviour**

The gpg space and locations should be created with ansible-archivematica-role when using rpms.

**Current behaviour**

The configure-gpg tasks are skipped.

**Steps to reproduce**

Deploy AM qa/1.x from rpms with ansible.

**Your environment (version of Archivematica, operating system, other relevant details)**

AM qa/1.x
CentoS 7

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged (if applicable)
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by sallain** [comment]
@mamedin This can be closed, right?
