### ISSUE TITLE
Problem: Cannot download or re-ingest an encrypted AIP (installed from rpm)

### ISSUE THREAD

**Issue by mamedin** [archivematica/Issues#1085]
**Expected behaviour**

The encrypted AIP should be downloaded or re-ingested with no errors.

**Current behaviour**

There's an error when trying to donwload or re-ingest the encrypted AIP. From SS log file:

```
locations.models.gpg:gpg:_gpg_decrypt:389:  Failed to decrypt /var/archivematica/storage_service/00f2/7deb/be24/4d24/9f6c/1767/fa86/8a88/mamedin-gpg-00f27deb-be24-4d24-9f6c-1767fa868a88.7z. Reason: decryption failed
```

**Steps to reproduce**

Install AM from rpms in CEntOS/RedHat, configure an encrypted AIP Storage and store and AIP on this AiP Storage. When you try to download or re-ingest that AIP you get the error.

**Your environment (version of Archivematica, operating system, other relevant details)**

CentOS and AM qa/1.x installed from rpms.

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged (if applicable)
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by mamedin** [comment]
Seems related to missing `libgpg-error-devel` package in rpm installation. This package is installed on CentOS when deploying from sources with the ansible role.

Installing the package and restarting the storage-service service fixes the issue on new AIPs.

The `libgpg-error-devel`package is a dependency of the `libxslt-devel` package:

```
[artefactual@am11centos archivematica]$ sudo rpm -q --whatrequires libgpg-error-devel
libgcrypt-devel-1.5.3-14.el7.x86_64
[artefactual@am11centos archivematica]$ sudo rpm -q --whatrequires libgcrypt-devel
libxslt-devel-1.1.28-5.el7.x86_64
```

**Comment by sallain** [comment]
@mamedin I thought I'd try testing this on bionic to start, but no dice - I get `{"message": "Storage service returned 500; check logs?", "success": false}`. It's possible that it might be the deployment though - can you check am111bionic? There is an AIP in the GPG space called "encrypted"

**Comment by sallain** [comment]
This works as expected. Tested on qa/1.x on CentOS.
