### ISSUE TITLE
Problem: Archivematica 1.11 is still using 1.10.x external packages repos

### ISSUE THREAD

**Issue by mamedin** [archivematica/Issues#1089]
**Expected behaviour**

When using AM1.11 the external packages repo should be:

https://packages.archivematica.org/1.11.x/centos-extras
http://packages.archivematica.org/1.11.x/ubuntu-externals

**Current behaviour**

AM1.11 still using:

https://packages.archivematica.org/1.10.x/centos-extras
http://packages.archivematica.org/1.10.x/ubuntu-externals

**Steps to reproduce**

Deploy AM and check apt or yum repositories

**Your environment (version of Archivematica, operating system, other relevant details)**

AM1.11 on Xenial, Bionic and CentOS

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged (if applicable)
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by mamedin** [comment]
The mcp-client base image should be updated once the https://github.com/artefactual/archivematica/pull/1555 is merged:

https://hub.docker.com/r/artefactual/archivematica-mcp-client-base/tags

**Comment by mamedin** [comment]
Created new archivematica-mcp-client-base image with new AM1.11 the external packages repo:

https://hub.docker.com/layers/artefactual/archivematica-mcp-client-base/20200210.01.0461aae/images/sha256-8886a09ab01b866ef29e83a8a68d4c4a0a04f1122e1ea06b3f73e20d426e867b

I deployed a test environment and it uses the new packages and external repo:

```
maml@cabesa:~/artefactual/am-git/am/compose$ docker-compose exec archivematica-mcp-client dpkg -l | grep -E '(fits|jhove|siegfried)'
ii  fits           1.1.0-6~18.0 amd64        File Information Tool Set (FITS)
ii  jhove          1.20.1-6~18. all          JSTOR/Harvard Object Validation E
ii  siegfried      1.8.0-1      amd64        PRONOM-based file identification
```

```
maml@cabesa:~/artefactual/am-git/am/compose$ docker-compose exec archivematica-mcp-client grep 1.11 /etc/apt/sources.list
deb [arch=amd64] http://packages.archivematica.org/1.11.x/ubuntu-externals bionic main
# deb-src [arch=amd64] http://packages.archivematica.org/1.11.x/ubuntu-externals bionic main
```

**Comment by ross-spencer** [comment]
Tested with the commands in the following snippets:

```
artefactual@am110xenial:~$ grep ^[^#] /etc/apt/sources.list /etc/apt/sources.list.d/* | grep archivematica
/etc/apt/sources.list.d/packages_archivematica_org_1_10_x_ubuntu_externals.list:deb [arch=amd64] http://packages.archivematica.org/1.10.x/ubuntu-externals xenial main
/etc/apt/sources.list.d/packages_archivematica_org_1_11_x_ubuntu_externals.list:deb [arch=amd64] http://packages.archivematica.org/1.11.x/ubuntu-externals xenial main
```	
	
```	
artefactual@am110bionic:~$ grep ^[^#] /etc/apt/sources.list /etc/apt/sources.list.d/* | grep archivematica
/etc/apt/sources.list.d/packages_archivematica_org_1_10_x_ubuntu_externals.list:deb [arch=amd64] http://packages.archivematica.org/1.10.x/ubuntu-externals bionic main
/etc/apt/sources.list.d/packages_archivematica_org_1_11_x_ubuntu_externals.list:deb [arch=amd64] http://packages.archivematica.org/1.11.x/ubuntu-externals bionic main
```

```
[artefactual@am11centos ~]$ yum repolist -v enabled | grep archivematica
Repo-id      : archivematica-extras
Repo-name    : archivematica extras
Repo-baseurl : https://packages.archivematica.org/1.11.x/centos-extras/
Repo-filename: /etc/yum.repos.d/archivematica-extras.repo
```
	
```
[artefactual@am110rpm ~]$ yum repolist -v enabled | grep archivematica
Repo-id      : archivematica
Repo-name    : archivematica
Repo-baseurl : https://jenkins-ci.archivematica.org/repos/am-packbuild/1.11.0-beta/centos7/
Repo-filename: /etc/yum.repos.d/archivematica.repo
Repo-id      : archivematica-extras
Repo-name    : archivematica-extras
Repo-baseurl : https://packages.archivematica.org/1.10.x/centos-extras/
Repo-filename: /etc/yum.repos.d/archivematica-extras.repo
Repo-id      : archivematica-ss
Repo-name    : archivematica-ss
Repo-baseurl : http://jenkins-ci.archivematica.org/repos/am-packbuild/0.15.0/centos7/
Repo-filename: /etc/yum.repos.d/archivematica-ss.repo
```

Moving to `in-progress` to verify whether on `RPM`, `Xenial` or `Bionic` the `1.10` sources should be deleted? i.e. added to the ansible scripts? Or is this simply overkill? cc. @mamedin <-- if it's overkill Miguel, please go ahead and close!! :slightly_smiling_face:

**Comment by mamedin** [comment]
@ross-spencer the am110 extra repo could be deleted to make the yum tasks faster, but it's harmless because we are not going to add packages with higher version in old repos.

So, closing!
