### ISSUE TITLE
Problem: Cannot add metadata files through UI

### ISSUE THREAD

**Issue by sromkey** [archivematica/Issues#1090]
**Expected behaviour**
During processing, users should be able to add metadata files through the UI, by clicking on the metadata entry page, and then on "add metadata files." This should work during initial ingest or during reingest, currently it works during neither.

**Current behaviour**
After the files are selected and the user attempts to add them, the browser hangs and the files are never added to the SIP.

**Steps to reproduce**
- create a SIP or reingest an AIP, ensuring that the processing configuration will pause for metadata entry
- click the metadata icon
- click on "Add metadata files" (last link in the list)
- Choose a file to add.
- Click add- it looks like it's initializing but nothing ever happens.

**Your environment (version of Archivematica, operating system, other relevant details)**
Tested on 1.10.1 and 1.11/qa (centos).

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged (if applicable)
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by sallain** [comment]
This is working as expected - I am able to select a metadata file, add it to the SIP, and it appears in the eventual AIP and in the METS properly.
