### ISSUE TITLE
Problem: tar.gz zipped bag transfers won't start on qa1.x -> 1.11

### ISSUE THREAD

**Issue by ross-spencer** [archivematica/Issues#1091]
**Expected behaviour**

The documented workflow for tar.gz transfers is [here](https://www.archivematica.org/en/docs/archivematica-1.10/user-manual/transfer/bags/#zipped-bags). It is expected that they will unpack and then be processed like any other workflow. 

**Current behaviour**

We receive a permissions error. When the transfer is approved. 
```
archivematica-mcp-server_1       | DEBUG    ThreadPoolExecutor-0_0 2020-02-08 02:07:13 packages:_copy_from_transfer_sources:249:  source: archivematica/archivematica-sampledata/SampleTransfers/ZippedTransfers/UnzippedBag.tar.gz, destination: /var/archivematica/sharedDirectory/tmp/tmpK02I6i/UnzippedBag.tar.gz
archivematica-mcp-server_1       | DEBUG    ThreadPoolExecutor-0_0 2020-02-08 02:07:13 packages:_start_package_transfer_with_auto_approval:460:  Package 6d250bf0-7f18-41ee-9326-fa3ee5a08110: moving package to processing directory
archivematica-mcp-server_1       | ERROR    ThreadPoolExecutor-0_0 2020-02-08 02:07:13 packages:wrap:402:  Exception occurred during transfer processing
archivematica-mcp-server_1       | Traceback (most recent call last):
archivematica-mcp-server_1       |   File "/src/MCPServer/lib/server/packages.py", line 395, in wrap
archivematica-mcp-server_1       |     return fn(*args, **kwargs)
archivematica-mcp-server_1       |   File "/src/MCPServer/lib/server/packages.py", line 462, in _start_package_transfer_with_auto_approval
archivematica-mcp-server_1       |     filepath, _get_setting("PROCESSING_DIRECTORY"), transfer
archivematica-mcp-server_1       |   File "/usr/local/lib/python2.7/site-packages/contextdecorator.py", line 102, in inner
archivematica-mcp-server_1       |     _reraise(*exc)
archivematica-mcp-server_1       |   File "/usr/local/lib/python2.7/site-packages/contextdecorator.py", line 95, in inner
archivematica-mcp-server_1       |     result = f(*args, **kw)
archivematica-mcp-server_1       |   File "/src/MCPServer/lib/server/packages.py", line 305, in _move_to_internal_shared_dir
archivematica-mcp-server_1       |     raise Exception("Error creating extraction dir %s (%s)", extract_dir, e)
archivematica-mcp-server_1       | Exception: (u'Error creating extraction dir %s (%s)', PosixPath('UnzippedBag'), OSError(13, 'Permission denied'))
```

**Steps to reproduce**

We have a `tar.gz` here that will work in `1.10.1` but not in `qa/1.x`. 

[UnzippedBag.tar.gz](https://github.com/archivematica/Issues/files/4173641/UnzippedBag.tar.gz)

**NB.** It would be good to add this, or a more complete example to the sampledata and AMAUAT.

**Your environment (version of Archivematica, operating system, other relevant details)**

Docker compose, running the latest `qa/1.x` branch. 

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged (if applicable)
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by sallain** [comment]
@ross-spencer just want to confirm, was this for `Zipped bag` transfers or `Zipped directory` transfers? This is just me getting confused between this issue and #682 so want to clarify to be extra sure I'm testing the right thing!

**Comment by sallain** [comment]
@ross-spencer Assuming I'm testing the right thing, I'm getting a failure at `Job: Verify bag, and restructure for compliance`. But maybe it is the sample bag provided above that's the issue? The error is:

```
Error validating BagIt package: Expected bagit.txt does not exist: /var/archivematica/sharedDirectory/currentlyProcessing/UnzippedBag_1-37af625d-5957-42b0-b931-bc6c3941f2d3/bagit.txt
Failed bagit compliance. Not restructuring.
```

**Comment by ross-spencer** [comment]
I've just seen this @sallain. I can recreate this if I select `Unzipped Bag` transfer type, and select the folder the `tar.gz` is contained in as an example, but providing the `tar.gz` file specifically is selected, it would fail previously as documented. I should note, my naming conventions require some work. 

As of this merge https://github.com/artefactual/archivematica/pull/1560 I can confirm this works now, as should zipped directory transfers if you'd like to verify with those?

**Comment by sallain** [comment]
This seems to be working now. I've tested doing a `Zipped bag` transfer with a bag serialized as tar.gz. The bag is extracted and bag verification succeeds. Tested on qa/1.x on Bionic.
