### ISSUE TITLE
Problem: Dashboard install fails due to missing dependency

### ISSUE THREAD

**Issue by Rayzilt** [archivematica/Issues#1093]
When installing the Dashboard on a seperate VM by setting "archivematica_src_install_am" the installation fails when compiling requirements through pip.

At task: [archivematica-src : virtualenv | Install requirements] the error ```gcc: error trying to exec 'cc1plus': execvp: No such file or directory\n  error: command 'gcc' failed with exit status 1``` is reported.

**Your environment (version of Archivematica, operating system, other relevant details)**
OS: CentOS 7
Archivematica: 1.10.1

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged (if applicable)
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by mamedin** [comment]
Thanks @Rayzilt 

The gcc dependency is included in SS osdeps:

https://github.com/artefactual/archivematica-storage-service/blob/stable/0.15.x/osdeps/CentOS-7.json#L25-L26

So, it is needed to include the gcc dependency in dashboard's osdeps.

**Comment by sromkey** [comment]
Installations are now working as expected.
