### ISSUE TITLE
Problem: Archivematica uses PRONOM v.92

### ISSUE THREAD

**Issue by sromkey** [archivematica/Issues#110]
**Please describe the problem you'd like to be solved.**

Archivematica is currently using v.92 of PRONOM. It would be good to update to v.93, or whatever is newest, with the next major release.

**Comment by ablwr** [comment]
I don't currently have access to FIDO, but I did file this issue requesting a new release: https://github.com/openpreserve/fido/issues/134

Either someone else will come along and do it (@jrwdunham? :smile: ) or when I'm granted access, I can do it.

**Comment by ablwr** [comment]
Cheating by moving the FIDO and Siegfried updates out of the scope of this issue. We should update those, but that should happen closer to the release, as both of those tools may have new releases. And if PRONOM94 is indeed coming soon, we can hopefully get that in as well, which would trigger yet-another FIDO update, at least.

**Comment by peterVG** [comment]
updated as per https://github.com/artefactual/archivematica/pull/1269
