### ISSUE TITLE
Problem: Ansible role doesn't configure the pipeline URL on SS

### ISSUE THREAD

**Issue by mamedin** [archivematica/Issues#1100]
**Expected behaviour**

The ansible role should allow to configure the pipeline URL on Archivematica Store Service.
**Current behaviour**

The "--site-url" option is missing in ansible-archivematica-role when registering the pipeline on SS. 

But this option is available on install command:

https://github.com/artefactual/archivematica/blob/stable/1.10.x/src/dashboard/src/installer/management/commands/install.py#L42

When not using the "--site-url" option registering the pipeline, SS sets the pipeline site-url as "127.0.0.1". Using "127.0.0.1" is a problem when re-ingesting and other dashboard actions.

**Steps to reproduce**

Deploy AM with ansible

**Your environment (version of Archivematica, operating system, other relevant details)**

Any ansible deployment.

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged (if applicable)
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by ross-spencer** [comment]
Moving to in-progress for additional verification from @mamedin as I see the following for Remote Name in the Storage Service:

Xenial: `127.0.0.1`
CentOS: `http://54.39.184.221`
Bionic: `http://54.39.190.16`
RPM: `http://am111rpm.qa.archivematica.net` 

I think per this issue only RPM is correct? But the other three are wrong? Or vice versa... ?

**Comment by ross-spencer** [comment]
Miguel has been walking me through the results of various deployments and we're seeing the IP address updated correctly, (not always the FQ domain name), but the correct IP to prevent the issues described in future. 

E.g. Xenial (just deployed) 

![image](https://user-images.githubusercontent.com/1880412/77569787-22bfb300-6ea1-11ea-8506-5c88e960edcd.png)

This looks great! 

![image](https://media0.giphy.com/media/26gsdPYZqqYKmcG0o/giphy.webp?cid=790b7611d4c30bda666c8502381a6a31ad12f478cff1685c&rid=giphy.webp)
