### ISSUE TITLE
Problem: in assign_file_uuids.py, find_mets_file() doesn't warn if it can't find a matching METS file

### ISSUE THREAD

**Issue by alexwlchan** [archivematica/Issues#1102]
**Expected behaviour**
If `find_mets_file()` doesn't find a matching METS file, it should throw immediately and print an explanatory error to the logs.

**Current behaviour**
It returns `None`, which can lead to the error occurring later on in the calling code with a non-obvious exception.

**Steps to reproduce**
Between Archivematica and our AIP storage, we had a tool that was removing the UUID from the name of the METS file. When Archivematica pulls the AIP back out for the Appraisal tab (I think; I’m not entirely sure of the details), it gets confused and throws an exception … but it’s further down, when it tries to parse the METS file.

I’m going to tweak the tool so it doesn't change the METS file name, and also improve the error reporting in this function.

**Your environment (version of Archivematica, operating system, other relevant details)**
Our custom fork, but a code read shows the possibility of this bug is present in stable/1.10.x.

I have a patch available, which I’ll open as a pull request shortly.

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged (if applicable)
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by sromkey** [comment]
@alexwlchan moving this to done also, just let us know if you ever reproduce again. Thank you!
