### ISSUE TITLE
Problem: when calling get_location(…)[0], you get an IndexError rather than a more helpful error

### ISSUE THREAD

**Issue by alexwlchan** [archivematica/Issues#1103]
Here’s a common-ish pattern in the Archivematica codebase:

```python
import storageService

processing_location = storageService.get_location(purpose="CP")[0]
```

What happens if you don't have any CP locations configured in the storage service?

**Expected behaviour**
An error that explains "No CP location found! Please check your storage service config."

**Current behaviour**
"IndexError: list index out of range", which is less than helpful.

**Your environment (version of Archivematica, operating system, other relevant details)**
I saw this in the Wellcome fork when I had a config error, with the following traceback in the "Move transfer to backlog" task:

```
list index out of rangeTraceback (most recent call last):
  File "/src/MCPClient/lib/job.py", line 111, in JobContext
    yield
  File "/src/MCPClient/lib/clientScripts/move_to_backlog.py", line 236, in call
    job.set_status(main(job, transfer_id, transfer_path, created_at))
  File "/src/MCPClient/lib/clientScripts/move_to_backlog.py", line 182, in main
    backlog = storage_service.get_location(purpose="BL")[0]
IndexError: list index out of range
```

But a code read suggests this would be present in the core codebase as well.

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged (if applicable)
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by sromkey** [comment]
@alexwlchan I'm going to move this to Done but if you experience it again let us know! Thanks for your help!
