### ISSUE TITLE
Problem: Can't add a processing configuration if the name has diacritics

### ISSUE THREAD

**Issue by replaceafill** [archivematica/Issues#1104]
**Expected behaviour**

Processing configurations created through the dashboard can have names with diacritics.

**Current behaviour**

You get the message `Failed to save processing configuration.` in the dashboard and this in the logs:

```
archivematica-dashboard_1        | ERROR     2020-02-18 16:55:01  archivematica.dashboard:views_processing:_report_error:55:  Failed to save processing configuration. 'ascii' codec can't encode character u'\xf3' in position 10: ordinal not in range(128)
archivematica-dashboard_1        | Traceback (most recent call last):
archivematica-dashboard_1        |   File "/src/dashboard/src/components/administration/views_processing.py", line 73, in edit
archivematica-dashboard_1        |     form.save_config()
archivematica-dashboard_1        |   File "/src/dashboard/src/components/administration/forms.py", line 382, in save_config
archivematica-dashboard_1        |     helpers.processing_config_path(), "{}ProcessingMCP.xml".format(name)
archivematica-dashboard_1        | UnicodeEncodeError: 'ascii' codec can't encode character u'\xf3' in position 10: ordinal not in range(128)
```

**Steps to reproduce**

1. Add a processing configuration with a name such as Dvořák or Montréal.
2. You'll get the error message `Failed to save processing configuration.`.

**Your environment (version of Archivematica, operating system, other relevant details)**

qa/1.x (https://github.com/artefactual/archivematica/commit/44eca798ff408ca727d239ac7515bafc28908662) on docker

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged (if applicable)
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by sromkey** [comment]
It would be nice to handle to error more elegantly at a minimum!

**Comment by sromkey** [comment]
We got this one as a bonus fix! Works fine now.
