### ISSUE TITLE
Problem: Currently Processing/Transfer Backlog Locations settings changes when editing the pipeline settings in SS

### ISSUE THREAD

**Issue by mamedin** [archivematica/Issues#1107]
**Expected behaviour**

Editing the pipeline settings in SS should not change the CP locations settings.

**Current behaviour**

When editing (you don't need to change anything, just click on "Edit" button) the pipeline settings in SS, the SS adds the pipeline to the default LocalFilesystem CP. When using multiple pipelines or one pipeline with Pipeline Local Filesystem it is a problem.

**Steps to reproduce**

Edit pipeline settings in SS and check the locations settings. If the pipeline was not using the default CP location, it adds the pipeline to that CP location.

**Your environment (version of Archivematica, operating system, other relevant details)**

Ubuntu Bionic, I tested with AM qa/1.x and AM v1.10.1 and it happened in both versions.

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged (if applicable)
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by mamedin** [comment]
It changes the Transfer Backlog settings too.

**Comment by sromkey** [comment]
@mamedin reports that the locations have the same settings after changing the pipeline description.
