### ISSUE TITLE
Problem: Getting "RuntimeError: Unexpectedly received another job on package completion."

### ISSUE THREAD

**Issue by jorikvankemenade** [archivematica/Issues#1108]
**Expected behaviour**
Not receiving `RuntimeErrors` while processing transfers in the qa environment.

**Current behaviour**

When I check the logs of the MCP Server I get the following:

```
ERROR     2020-02-20 15:36:25  concurrent.futures:_base:_invoke_callbacks:333:  exception calling callback for <Future at 0x7f75812aefd0 state=finished returned GetUnitVarLinkJob>
Traceback (most recent call last):
  File "/usr/share/archivematica/virtualenvs/archivematica-mcp-server/lib/python2.7/site-packages/concurrent/futures/_base.py", line 331, in _invoke_callbacks
    callback(self)
  File "/usr/lib/archivematica/MCPServer/server/queues.py", line 231, in _package_completed_callback
    "Unexpectedly received another job on package completion. "
RuntimeError: Unexpectedly received another job on package completion. If the workflow has been modified, please update PACKAGE_COMPLETED_LINK_IDS.
```

The problem is that "Check transfer directory for objects" is marked as a package completed link ([source](https://github.com/artefactual/archivematica/blob/44eca798ff408ca727d239ac7515bafc28908662/src/MCPServer/lib/server/queues.py#L76)). The workflow for this link has two exit codes:

```
"exit_codes": {
    "0": {
        "job_status": "Completed successfully",
        "link_id": null
    },
    "179": {
        "job_status": "Completed successfully",
        "link_id": "b04e9232-2aea-49fc-9560-27349c8eba4e"
    }
}
```

In my test transfer, I get the `179` exit code. According to the [client script](https://github.com/artefactual/archivematica/blob/qa/1.x/src/MCPClient/lib/clientScripts/check_transfer_directory_for_objects.py) this means that the transfer directory is not empty. As a result the next step is to continue to "Load options to create SIPs". This means that if you have a correctly functioning transfer, you will get runtime errors in your logs.

I think the problem, in this case, is that this link can be both ending, and not ending at the same link. One option is to remove this link from the `PACKAGE_COMPLETED_LINK_IDS`. But this would mean that the package is never deactivated in case of an empty transfer directory. Which brings me to a related question: do we want to do nothing in case of an empty transfer directory? I would think this should result in a cleanup, i.e. reject the transfer. 

Pinging @cole to see what he thinks about this. 

**Steps to reproduce**
1, Start a transfer that will finish correctly.
2. Check the MCP server logs around the time that "Check transfer directory for objects" runs. 

**Your environment (version of Archivematica, operating system, other relevant details)**
Archivematica qa/1.x

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged (if applicable)
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by sevein** [comment]
> I think the problem, in this case, is that this link can be both ending, and not ending at the same link. One option is to remove this link from the PACKAGE_COMPLETED_LINK_IDS.

Sounds like "Check transfer directory for objects" shouldn't be a terminal link but `exit_codes.0.link_id` should point to one?

> Which brings me to a related question: do we want to do nothing in case of an empty transfer directory? I would think this should result in a cleanup, i.e. reject the transfer.

Perhaps this is a question for @sromkey.

**Comment by jorikvankemenade** [comment]
My personal preference would be to change the return code of `check_transfer_directory_for_objects.py` to 0 in case there are files. This would be more in line with what you expect. If checking was successful, the exit code is 0, which is coincidentally green in the frontend.

The rest would depend on the answer of @sromkey, I am not completely sure what the desired behaviour here is. But I would guess some sort of `fallback` to a reject path. In the end, we don't really care if the transfer directory is empty or if there is some other problem. Or do we want to distinguish there as well?

**Comment by sromkey** [comment]
> > Which brings me to a related question: do we want to do nothing in case of an empty transfer directory? I would think this should result in a cleanup, i.e. reject the transfer.
> 
> Perhaps this is a question for @sromkey.

I agree that an empty transfer should be rejected.

**Comment by cole** [comment]
@jorikvankemenade it looks like you're on the right track here.

If I'm remembering correctly, I made some changes changes in [this PR](https://github.com/artefactual/archivematica/pull/1482) to try to avoid the non-terminal path — after SIP creation, there shouldn't be any obects left. But, that path remains in the workflow, and kind of highlights the weakness of using `PACKAGE_COMPLETED_LINK_IDS` 😞 .

**Comment by sevein** [comment]
We've put some significant effort (particularly @jorikvankemenade!) to identify terminal links in our workflow since that's now critical with the existence of queues in MCPServer. amflow has received some updates to help identify these cases easier.

* https://github.com/artefactual/archivematica/pull/1577
  Better way to identify terminal links as part of the workflow language.
  Update the set of terminal links to ensure good behavior of queues.
* https://github.com/artefactual/archivematica/pull/1584
  Relax logging level in case of false positives as we're accepting that a few links in AM 1.11's workflow will be tagged as terminal while they also reference to other links since we've confirmed the safety of it.

**Comment by ross-spencer** [comment]
Discussed locally and confirmed that we were seeing this when trying to process on a multi-pipeline environment, but also with large numbers of AIPS going through the system. We're now able to process 1000 in reasonable time and the logs continue to be clean post-fix.
