### ISSUE TITLE
Problem: Ingest Policy and Conformance Check fails in AMAUAT

### ISSUE THREAD

**Issue by ross-spencer** [archivematica/Issues#1115]
**Expected behaviour**

* AMAUAT continues to pass.
* We maintain a minimal suite of automated testing to explore the widest range of Archivematica features possible. Especially features for which testing is especially onerous. 

**Current behaviour**

* #912 removes defaults required by the [ingest-policy-check feature](https://github.com/artefactual-labs/archivematica-acceptance-tests/blob/qa/1.x/features/core/ingest-policy-check.feature#L34-L57) in AMAUAT. This test generally doesn't run in our QA matrix as it is unreliable across the multiple platforms, i.e. tends to require a developer's slightly better performing environment than our generic virtual machines. 

Image 1 shows the rule needed in the `qa/1.x` -> `1.11-RC`:

![image](https://user-images.githubusercontent.com/1880412/75267258-035f3880-57c4-11ea-9247-659460f7be65.png)

Image 2 shows the rule needed in `stable/1.10.x`:

![image](https://user-images.githubusercontent.com/1880412/75267594-736dbe80-57c4-11ea-98ce-083933af75b4.png)

Sara confirms some of the new behaviors in the comment to #912: https://github.com/archivematica/Issues/issues/912#issuecomment-586009575

It also removes the required rule for the [mkv-conformance feature](https://github.com/artefactual-labs/archivematica-acceptance-tests/blob/14bcaef70793668d43071083ee00521077b9b862/features/core/ingest-mkv-conformance.feature#L8-L28) for preservation:

![image](https://user-images.githubusercontent.com/1880412/75271737-b03cb400-57ca-11ea-8518-d43e992b497a.png)

**Steps to reproduce**

From your development environment run `sudo make test-at-behave TAGS=ipc BROWSER=Firefox`.

**Your environment (version of Archivematica, operating system, other relevant details)**

Docker Compose: `qa.1.x`->`1.11-rc`. 

**Workaround notes**

I would like to propose we keep the tests running, but comment out or disable the `preservation` specific tests, keeping the access checks in place. 

In the future, Selenium tests could have a feature added which gives them the ability to enable any existing test if it is disabled in the format policy register. Joel D [noted the need to have a click](https://github.com/artefactual-labs/archivematica-acceptance-tests/blob/9aaa74886530a03e9d39e3b4f131eef2169a8ce5/amuser/am_browser_preservation_planning_ability.py#L223-L231), and a lot of that work might already be done, I haven't a clear idea how much effort this is, the enabling of a rule needs to navigate two screens, not just a single click (~hours?).

Alternatively a feature may appear in future where this can all be tested via API :crossed_fingers:  

**Developer environment**

From the developer environment devs can access a helper:
```
developer@artefactual:~/git/artefactual-labs/am/compose$ sudo make test-at-help

   Archivematica acceptance tests (Listing).

   The most effective way to run these tests is to run them by tag. For
   example:

      make test-at-behave TAGS=aip-encrypt BROWSER=Firefox
      make test-at-behave TAGS=black-box

   Commonly used acceptance tests in the Archivematica suite:

      * aip-encrypt        :Tests the encryption of AIPs.
      * aip-encrypt-mirror :Tests the replication of encrypted AIPs.
      * black-box          :Test Archivematica without Selenium web-driver.
      * icc                :Conformance check feature on ingest.
      * ipc                :Policy check feature on ingest.
      * picc               :Policy check feature for preservation derivatives.
      * mo-aip-reingest    :Metadata-only reingest.
      * tpc                :Policy check feature on transfer.
      * uuids-dirs         :Tests whether UUIDs are assigned to AIP sub-DIRs.
```
For any of these tests which fail, (icc, ipc, others?) it makes the environment harder to work with. Disabling those tests that currently don't work might promote greater usage of these tests by only narrowing the impact slightly. 

Obviously if there is time to fix these, then I'd prefer that option. 

Related to https://github.com/archivematica/Issues/issues/780

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged (if applicable)
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by tw4l** [comment]
@replaceafill I seem to be hitting this issue again when trying to run AMAUATs via the "AMAUAT" tag in GH PRs. For example: https://github.com/artefactual/archivematica/pull/1725/checks?check_run_id=2335075302

Detailed traceback/test results available here: https://gist.github.com/tw4l/d23fd95837a15e8e4694a9f83f32646e

**Comment by replaceafill** [comment]
>@replaceafill I seem to be hitting this issue again when trying to run AMAUATs via the "AMAUAT" tag in GH PRs

This seems to be an intermittent issue with the `ipc` tag and `Firefox` when it's run in the GitHub workflow. [I just tried the `AMAUAT` tag in Tessa's PR](https://github.com/artefactual/archivematica/actions/runs/749916059) and the `acceptance-tests` workflow passed this time:

![Screenshot_2021-04-14 artefactual archivematica](https://user-images.githubusercontent.com/560781/114793206-1a097b80-9d47-11eb-9fde-8a9ab93a8300.png)

Since the `Firefox` problem is very tricky to reproduce [we've decided to exclude the `ipc` tag from running in `Firefox`](https://github.com/artefactual/archivematica/pull/1727) until we have time to investigate.
