### ISSUE TITLE
Problem: A Unicode error somewhere in "Remove unneeded files" causes the whole transfer to hang

### ISSUE THREAD

**Issue by alexwlchan** [archivematica/Issues#1117]
**Expected behaviour**
After Archivematica has finished removing any unneeded files, it proceeds to the next step of the workflow.

**Current behaviour**
It hangs … sometimes. Specifically, the transfer stops making any progress through the dashboard, and I see a stack trace in the MCP server logs:

```
ERROR ThreadPoolExecutor-0_0 2020-02-26 17:12:09 _base:_invoke_callbacks:333: exception calling callback for <Future at 0x7f996047a210 state=finished raised UnicodeDecodeError>
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/concurrent/futures/_base.py", line 331, in _invoke_callbacks
    callback(self)
  File "/src/MCPServer/lib/server/queues.py", line 233, in _job_completed_callback
    next_job = future.result()
  File "/usr/local/lib/python2.7/site-packages/concurrent/futures/_base.py", line 455, in result
    return self.__get_result()
  File "/usr/local/lib/python2.7/site-packages/concurrent/futures/thread.py", line 63, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python2.7/site-packages/contextdecorator.py", line 102, in inner
    _reraise(*exc)
  File "/usr/local/lib/python2.7/site-packages/contextdecorator.py", line 95, in inner
    result = f(*args, **kw)
  File "/src/MCPServer/lib/server/jobs/client.py", line 126, in run
    self.submit_tasks()
  File "/src/MCPServer/lib/server/jobs/client.py", line 238, in submit_tasks
    arguments = self.replace_values(self.arguments, command_replacements)
  File "/src/MCPServer/lib/server/jobs/client.py", line 104, in replace_values
    escaped_replacement = _escape_for_command_line(replacement)
  File "/src/MCPServer/lib/server/jobs/client.py", line 28, in _escape_for_command_line
    value = value.replace("\\", "\\\\")
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 85: ordinal not in range(128)
```

I don’t know if I can reproduce this reliably – it’s happened on ~20% of my transfer packages, but then I resent one of them and it worked fine. I just resent another package and it's failed again

The only reliable fix I’ve found it to restart the MCP client and MCP server, at which point the broken transfers get stopped and I have to send them again.

**Your environment (version of Archivematica, operating system, other relevant details)**
This is happening in the custom Wellcome fork of Archivematica.

Possibly significant: we've just rebased to a newer version – the newest commit we have common is feb139f (Jan 2020); prior to that we had a fork taken at 0f229b7a (Jun 2019), so we picked up six months of changes in one go. The `client.py` file where this exception is being thrown was added in this time – is it possible there's an uncaught bug lurking here?

I can put in some more debugging tomorrow and try to work out what's going on here; opening this ticket tonight in the hope that somebody else might have an idea what's going on here.

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged (if applicable)
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by replaceafill** [comment]
From the traceback it might be this same situation: https://github.com/wellcomecollection/platform/issues/4175#issuecomment-578136053 which has been fixed by https://github.com/artefactual/archivematica/pull/1553

**Comment by alexwlchan** [comment]
Aha! I’ll give that a look tomorrow, thanks.

**Comment by alexwlchan** [comment]
Hmm. I pulled https://github.com/artefactual/archivematica/commit/46273947514507d7c51bba581fe0ff6e1966af4d into our fork (the squash commit from https://github.com/artefactual/archivematica/pull/1553) and deployed it, kicked off a new transfer, and I’m seeing the same issue again.

I added some tracing code to get the `repr()` of objects that are being passed into `replace_values()`. Here's a sample just before it all goes wrong:

```
@@AWLC u'/var/archivematica/sharedDirectory/currentlyProcessing/PPHEP_2399'
@@AWLC u'%sharedPath%rejected/'
@@AWLC u'None'
@@AWLC u''
@@AWLC u'/var/archivematica/sharedDirectory/currentlyProcessing/PPHEP_2399'
@@AWLC u'PPHEP_2399'
@@AWLC u'/var/archivematica/sharedDirectory/watchedDirectories/'
@@AWLC u'Transfer'
@@AWLC u'adf7d178-1a8a-4b66-9425-e7d858b3c9ba'
@@AWLC '/var/archivematica/sharedDirectory/currentlyProcessing/PPHEP_2399/surveys October  2014/Chinese vs Western food additives 2007/Citric Acid - 2007 USA.ppt'
@@AWLC u'/var/archivematica/sharedDirectory/currentlyProcessing/'
@@AWLC u'/var/archivematica/sharedDirectory/currentlyProcessing/PPHEP_2399/objects/'
@@AWLC u'/var/archivematica/sharedDirectory/currentlyProcessing/PPHEP_2399/logs/'
@@AWLC u'/var/archivematica/sharedDirectory/tmp/'
@@AWLC u'PPHEP_2399'
@@AWLC u'/var/archivematica/sharedDirectory/currentlyProcessing/PPHEP_2399'
@@AWLC u'%sharedPath%rejected/'
@@AWLC u'None'
@@AWLC u''
@@AWLC u'/var/archivematica/sharedDirectory/currentlyProcessing/PPHEP_2399'
@@AWLC u'PPHEP_2399'
@@AWLC u'/var/archivematica/sharedDirectory/watchedDirectories/'
@@AWLC u'Transfer'
@@AWLC u'adf7d178-1a8a-4b66-9425-e7d858b3c9ba'
@@AWLC '/var/archivematica/sharedDirectory/currentlyProcessing/PPHEP_2399/surveys October  2014/Chinese vs Western food additives 2007/Monosodium Glutamate \xc3\xa2\xc2\x80\xc2\x93 MSG 2007 USA.ppt'
```

**Comment by alexwlchan** [comment]
Woohoo! That wasn't quite it, but https://github.com/artefactual/archivematica/commit/7ac6501fde87eae13e18dc877962a8bf3a4fb347 was the final piece I needed. Transfers seem to be moving again, thanks @replaceafill!
