### ISSUE TITLE
Problem: RPM packages install wrong settings for the dashboard

### ISSUE THREAD

**Issue by replaceafill** [archivematica/Issues#1118]
**Expected behaviour**

All the settings written at installation in `/etc/sysconfig/archivematica-dashboard` are used by the application.

**Current behaviour**

[These two settings](https://github.com/artefactual-labs/am-packbuild/blob/2cdb2f92138f64816640cf17047d91c6b2b6c856/rpm/archivematica/etc/archivematica-dashboard.env#L13-L14) are spelled wrongly:

* `ARCHIVEMATICA_DASHBOARD_GEARMAN=localhost:4730`
* `ARCHIVEMATICA_DASHBOARD_ELASTICSEARCH=localhost:9200`

They should be:

* `ARCHIVEMATICA_DASHBOARD_DASHBOARD_GEARMAN_SERVER=localhost:4730`
* `ARCHIVEMATICA_DASHBOARD_DASHBOARD_ELASTICSEARCH_SERVER=localhost:9200`

This was [reported in the user forum](https://groups.google.com/d/msg/archivematica/7BQSK-UEPWs/hqcjfdVWHAAJ), and it seems more notable when ElasticSearch is installed in a separate server.

**Steps to reproduce**

As explained in the user forum post (separate ElasticSearch server and dashboard on CentOs).

**Your environment (version of Archivematica, operating system, other relevant details)**

From the user forum post: `1.10.1`

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged (if applicable)
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by mamedin** [comment]
Package created and tested in am111rpm. It works fine.

**Comment by ross-spencer** [comment]
Testing per the issue, I look at: `less /etc/sysconfig/archivematica-dashboard`

But i see:
```
# Ansible managed

PYTHONPATH=/usr/lib/archivematica/archivematicaCommon:/usr/share/archivematica/dashboard
LANG="en_US.UTF-8"
LC_ALL="en_US.UTF-8"
LC_LANG="en_US.UTF-8"

REQUESTS_CA_BUNDLE=/etc/pki/tls/certs/ca-bundle.crt
ARCHIVEMATICA_DASHBOARD_DASHBOARD_ELASTICSEARCH_TIMEOUT=30
ARCHIVEMATICA_DASHBOARD_DASHBOARD_DJANGO_ALLOWED_HOSTS=*
ARCHIVEMATICA_DASHBOARD_SEARCH_ENABLED=yes
ARCHIVEMATICA_DASHBOARD_CLIENT_DATABASE=MCP
ARCHIVEMATICA_DASHBOARD_DASHBOARD_ELASTICSEARCH_SERVER=127.0.0.1:9200
DJANGO_SETTINGS_MODULE=settings.production
ARCHIVEMATICA_DASHBOARD_DASHBOARD_STORAGE_SERVICE_CLIENT_QUICK_TIMEOUT=30
ARCHIVEMATICA_DASHBOARD_CLIENT_HOST=localhost
AM_GUNICORN_BIND=127.0.0.1:8002
ARCHIVEMATICA_DASHBOARD_DASHBOARD_DJANGO_SECRET_KEY=CHANGE_ME_WITH_A_SECRET_KEY
ARCHIVEMATICA_DASHBOARD_CLIENT_PASSWORD=am110x
ARCHIVEMATICA_DASHBOARD_CLIENT_USER=archivematica
ARCHIVEMATICA_DASHBOARD_DASHBOARD_SEARCH_ENABLED=true
```
And am expecting to see per the commit [here](https://github.com/artefactual-labs/am-packbuild/blob/46584ed26897f5256b5ab70efaa3694f45046980/rpm/archivematica/etc/archivematica-dashboard.env): 

```
ARCHIVEMATICA_DASHBOARD_DASHBOARD_GEARMAN_SERVER=localhost:4730
ARCHIVEMATICA_DASHBOARD_DASHBOARD_ELASTICSEARCH_SERVER=localhost:9200
```
But they are not there.

**Comment by mamedin** [comment]
@ross-spencer the am111rpm.qa server is configured with ansible, so it is overriding the /etc/sysconfig/archivematica* files. To review this issue you need to make a new deploy from packages, faster way is: https://github.com/archivematica/Issues/issues/1124#issuecomment-599989073

Other option is to delete the /etc/sysconfig/archivematica* files and reinstall AM packages on am111rpm.qa test server:

```
sudo rm /etc/sysconfig/archivematica-*
sudo yum reinstall archivematica*
```

**Comment by mamedin** [comment]
Reviewed on am111rpm again.
