### ISSUE TITLE
Problem: MCPClient 1.10.1 installation fails due to lack of clamav-server in Red Hat 7.7

### ISSUE THREAD

**Issue by arthytrip** [archivematica/Issues#1119]
Problem: MCPClient 1.10.1 installation fails due to lack of clamav-server in Red Hat 7.7

**Expected behaviour**

The installation of MCPClient requires the presence of the ClamAV software.
In case of installation of MCPClient on a dedicated server, in Ubuntu and in CentOS 7 it is normally possible to install ClamAV and therefore the MCPClient, for example with the following sequence of commands (CentOS 7):

```
# sudo -u root yum install -y epel-release
# sudo -u root yum update -y
# sudo -u root yum clean all
# sudo -u root yum install -y clamav-server clamav-data clamav-update clamav-filesystem clamav clamav-scanner-systemd clamav-devel clamav-lib clamav-server-systemd

# sudo -u root bash -c 'cat << EOF > /etc/yum.repos.d/archivematica.repo
[archivematica]
name=archivematica
baseurl=https://packages.archivematica.org/1.10.x/centos
gpgcheck=1
gpgkey=https://packages.archivematica.org/1.10.x/key.asc
enabled=1
EOF'

# sudo -u root bash -c 'cat << EOF > /etc/yum.repos.d/archivematica-extras.repo
[archivematica-extras]
name=archivematica-extras
baseurl=https://packages.archivematica.org/1.10.x/centos-extras
gpgcheck=1
gpgkey=https://packages.archivematica.org/1.10.x/key.asc
enabled=1
EOF'

# sudo -u root yum install -y archivematica-mcp-client
```

**Current behaviour**

In Red Hat 7.x the procedure fails cause the lack of the package "clamav-server" and the numerous dependencies between this and the "archivematica-mcp-client".

**Steps to reproduce**

In Red Hat 7.x...

Install epel-release:
`# sudo -u root yum install https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm`

Extra packages for openjpeg:
`# sudo -u root subscription-manager repos --enable "rhel-*-optional-rpms" --enable "rhel-*-extras-rpms"`

Update and clean repos:
```
# sudo -u root yum update -y
# sudo -u root yum clean all
```

Install ClamAV:
`# sudo -u root yum install -y clamav-server clamav-data clamav-update clamav-filesystem clamav clamav-scanner-systemd clamav-devel clamav-lib clamav-server-systemd`

At this point you can already see the lack of the package "clamav-server")

Add Archivematica repos:
```
# sudo -u root bash -c 'cat << EOF > /etc/yum.repos.d/archivematica.repo
[archivematica]
name=archivematica
baseurl=https://packages.archivematica.org/1.10.x/centos
gpgcheck=1
gpgkey=https://packages.archivematica.org/1.10.x/key.asc
enabled=1
EOF'

# sudo -u root bash -c 'cat << EOF > /etc/yum.repos.d/archivematica-extras.repo
[archivematica-extras]
name=archivematica-extras
baseurl=https://packages.archivematica.org/1.10.x/centos-extras
gpgcheck=1
gpgkey=https://packages.archivematica.org/1.10.x/key.asc
enabled=1
EOF'
```

Install Archivematica MCPClient
`# sudo -u root yum install -y archivematica-mcp-client`

Now the installation fails with...
```
...
--> Finished Dependency Resolution
Error: Package: archivematica-mcp-client-1.10.1-1.x86_64 (archivematica)
           Requires: clamav-server
**********************************************************************
yum can be configured to try to resolve such errors by temporarily enabling
disabled repos and searching for missing dependencies.
To enable this functionality please set 'notify_only=0' in /etc/yum/pluginconf.d/search-disabled-repos.conf
**********************************************************************

Error: Package: archivematica-mcp-client-1.10.1-1.x86_64 (archivematica)
           Requires: clamav-server
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest
```

**Your environment (version of Archivematica, operating system, other relevant details)**

Archivematica 1.10.1
OS Red Hat Enterprise Linux Server release 7.7 (Maipo)

We are adding a new MCPClient, on a dedicated host, to an Archivematica 1.10.1 system.

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged (if applicable)
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by arthytrip** [comment]
I am realizing that in my MCPClient installations on CentOS 7 I have not installed clamav-server, yet they work!
Is it possible that the clamav-server dependence impacts the MCPClient installation only on Red Hat distributions?

Here an example in a CentOS 7 that hosts a well working MCPClient:
```
# yum list clam*
Loaded plugins: fastestmirror
Determining fastest mirrors
 * base: mirrors.prometeus.net
 * epel: mirror.infonline.de
 * extras: mirrors.prometeus.net
 * updates: mirrors.prometeus.net
Installed Packages
clamav.x86_64                     0.101.5-1.el7     @epel
clamav-data.noarch                0.101.5-1.el7     @epel
clamav-devel.x86_64               0.101.5-1.el7     @epel
clamav-filesystem.noarch          0.101.5-1.el7     @epel
clamav-lib.x86_64                 0.101.5-1.el7     @epel
clamav-update.x86_64              0.101.5-1.el7     @epel
clamd.x86_64                      0.101.5-1.el7     @epel
Available Packages
clamav-milter.x86_64              0.101.5-1.el7     epel
clamav-unofficial-sigs.noarch     7.0.1-1.el7       epel
clamsmtp.x86_64                   1.10-12.el7       epel
```

Best regards

Arthy

**Comment by jorikvankemenade** [comment]
When did you perform the CentOS 7 installation? My Puppet installation scripts only started to bother me about the missing `clamav-server` yesterday. So if you have the possibility of making a fresh install on another CentOS box that would be a good test I suppose.

**Comment by arthytrip** [comment]
No sooner said than done!
I just tried to install a brand new MCPClient on CentOS 7 and it fails exactly the same way as on Red Hat 7.
Again, the...
`# sudo -u root yum install -y clamav-server clamav-data clamav-update clamav-filesystem clamav clamav-scanner-systemd clamav-devel clamav-lib clamav-server-systemd`
immediately produces a "No package clamav-server available.".
So maybe there are two hypotheses:
1. the clamav-server package never existed (although many technological sites mention it) and the Archivematica MCPClient dependencies are incorrect
2. the clamav-server package ... you don't know where to get it

**Comment by scollazo** [comment]
The clamav-server and clamav-scanner disappeared. I found an old changelog entry in the clamav package that might be related:

> * dom jun 30 2019 Sérgio Basto <sergio@serjux.com> - 0.101.2-2
>- One year later we may remove pakages workaround of clamav-milter-systemd,
  clamav-scanner-systemd and clamav-server-systemd, before I forget it was one
  workaround to allow migration of service without stop it and disable it
  (#1583599).

**Comment by jorikvankemenade** [comment]
@scollazo thank you for linking this and the PRs. Changing the server packages to `clamd` fixed the problems for my CentOS based development and QA instances.

**Comment by arthytrip** [comment]
Hi,
thank Santiago.
If possible, I would like to solicit revisions and merge to master of this change, so as to make it immediately available for legacy installations.
This is a trivial change that does not affect any functionality and solves a current blocking installation problem.
Thank you.
Arthy

**Comment by scollazo** [comment]
@arthytrip while this is reviewed/tested,  I created a test package available at https://jenkins-ci.archivematica.org/repos/am-packbuild/clamav-update/centos7/archivematica-mcp-client-1.10.1-clamav1.x86_64.rpm , so if you test it tell us how it goes...


Jenkins build log: https://jenkins-ci.archivematica.org/job/am-packbuild/job/rpm-jenkinsci/340/

**Comment by arthytrip** [comment]
@scollazo
Thanks a lot Santiago for the package. I tried on the fly in CentOS a little while ago and the installation works. Tomorrow morning I will also try in Red Hat and I will let you know.

**Comment by mamedin** [comment]
New `archivematica-mcp-client-1.10.1-2.x86_64` package has been published in AM 1.10 rpm repository.

**Comment by arthytrip** [comment]
Thank so much.
Have a nice we!

**Comment by arthytrip** [comment]
Thank so much.
Have a nice we!

**Comment by ross-spencer** [comment]
Tested on CentOS and RPM by running `virusTests` sample-data:

![image](https://user-images.githubusercontent.com/1880412/77370959-782c8080-6d38-11ea-8243-99a48bd06134.png)

![image](https://user-images.githubusercontent.com/1880412/77370965-7c589e00-6d38-11ea-994d-72c340f9adb8.png)

Given ClamAV is triggered, and the deployments worked, then ClamAV must exist as anticipated.
