### ISSUE TITLE
Problem: zipfile is an inaccurate API descriptor of Zipped directory transfers

### ISSUE THREAD

**Issue by ross-spencer** [archivematica/Issues#1126]
**Please describe the problem you'd like to be solved**

From @sallain's wonderfully concise definition of the problem in Slack: 

Currently, the type parameter in the API for a `Zipped directory` transfer is `zipfile`. For the sake of clarity, we'd like to change it to `zipped package` and make the equivalent change in the user interface to `Zipped package` as well. This would require a some work, so there are three options:

1. Change to `zipped package` for 1.11. This would take ~5-10 hours of work that would be done next week. This work does touch the dashboard so there's a small threat that it could interfere with regression testing.
2. Leave it as `zipfile` but note in the API documentation that it will change in the future. For 1.12, change it to `zipped package`. Same amount of hours required.
3. Don't change it and leave it as `zipfile` forever!

**Describe the solution you'd like to see implemented**

After much rumination internally, we will go for 1. while we have the opportunity. We have a PR incoming.

cc. @alexwlchan this is likely to impact Wellcome most when `1.11` is released or you rebase to `qa/1.x`. 

**Describe alternatives you've considered**

As above.

**Additional context**

As above, and a desire to make sure the design of a feature is good before release to the wider public.

The original feature: https://github.com/archivematica/Issues/issues/682

cc. @sromkey will add the `1.11` label per discussion Friday. 

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged
- [ ] Details about this issue have been added to the release notes

**Comment by alexwlchan** [comment]
Thanks for the heads-up. We're already using the "zipped directory" code in our deployment, and I’ll make a note that it’ll change at some point.

**Comment by sromkey** [comment]
Because we released 1.11 with "zipfile" , we would actually be introducing a backwards incompatible change in the API to change it for 1.12. For this reason I'm going to close the issue for now.
@ross-spencer contributed some really valuable ideas and discussion in his PR, which I hope we can revisit in the future.. I think the general concept of transfer types could use some discussion more holistically anyway.
