### ISSUE TITLE
Problem: Large Dataverse Datasets fail to transfer into Archivematica

### ISSUE THREAD

**Issue by joel-simpson** [archivematica/Issues#113]
**Expected behaviour**
When I select the dataset "1059 AV & Large File Sizes" in the Transfer Browser, I expect the dataset to be retrieved from Dataverse and a transfer created and started from it. 

**Current behaviour**
The dataset does not appear in the dashboard of Archivematica. 
The following errors appear in the Storage Service logs: https://gist.github.com/joel-simpson/1e8e50018b62f676812154a1465455ab
It's probably worth noting that the file where the errors occurs is id 1118, which is a 2Gb file. 
See https://demodv.scholarsportal.info/file.xhtml?fileId=1118&version=RELEASED&version=.1

**Steps to reproduce**
Need to test from an instance of Archivematica that has a Dataverse Storage Space connected. Select a dataset with very large files. 

**Your environment (version of Archivematica, OS version, etc)**
Testing the latest changes for Dataverse which are up to date with qa/1.x (Dev branch for [SS PR 398] (https://github.com/artefactual/archivematica-storage-service/pull/398)and AM [PR 1242](https://github.com/artefactual/archivematica/pull/1242)). Tested on my local docker dev environment and in our QA environment http://ocul-am-dv.dev.archivematica.org:62080

**Comment by joel-simpson** [comment]
I have retested this on my local machine as well as our QA server and that large dataset (AV & Large Files) transfers in successfully in both cases. 
thanks @marktriggs !

**Comment by sevein** [comment]
If this is a blocker, should we add the 1.8.0 milestone?

**Comment by ross-spencer** [comment]
@sromkey @joel-simpson I think there was an agreement this would be okay to add to `1.8.0` on the call we had before my leave. is that correct? If so, we just need to add the milestone. cc. @sevein

**Comment by sromkey** [comment]
Yes, sorry that's my recollection too. Adding the milestone now.
