### ISSUE TITLE
Problem: Directory metadata is not imported during metadata re-ingests

### ISSUE THREAD

**Issue by replaceafill** [archivematica/Issues#1136]
**Expected behaviour**

During metadata re-ingests, file and directory metadata can be updated with [a CSV file uploaded through the user interface](https://www.archivematica.org/en/docs/archivematica-1.10/user-manual/ingest/ingest/#uploading-metadata-csv-files-through-the-user-interface).

**Current behaviour**

[Only file metadata is updated](https://github.com/artefactual/archivematica/blob/e804cc1cc3130c276390b6a0ed63c115c8191576/src/MCPClient/lib/clientScripts/archivematicaCreateMETSReingest.py#L541-L557).

**Steps to reproduce**

1. Set **Reminder: add metadata if desired:** to **None** in your processing configuration.
2. Run a `SampleTransfers/DemoTransferCSV` transfer
3. Run a metadata re-ingest on the transfer
4. When the metadata remainder is shown, [upload a CSV file](https://www.archivematica.org/en/docs/archivematica-1.10/user-manual/ingest/ingest/#uploading-metadata-csv-files-through-the-user-interface) that contains metadata for a file (e.g. `objects/bird.mp3`) and the `objects/artwork` directory. You can try [metadata.txt](https://github.com/archivematica/Issues/files/4296659/metadata.txt). Make sure to rename it to `.csv`. Also, be aware that because https://github.com/archivematica/Issues/issues/1139 only Dublin Core metadata will work.
5. Finish the re-ingest and check that only the file's metadata was updated. Additionally you can check the final part of the output of the `Generate AIP METS -> Generate METS.xml document` job of the re-ingest. It'll look similar to this:

   ```
   Parse new metadata.csv
   Looking for objects/artwork from metadata.csv in SIP
   objects/artwork not found in database
   Looking for objects/bird.mp3 from metadata.csv in SIP
   objects/bird.mp3 found in database
   objects/bird.mp3 was associated with ['dmdSec_8']
   objects/bird.mp3 now associated with ['dmdSec_8', u'dmdSec_11']
   ```

   Notice the `objects/artwork not found in database` part.

**Your environment (version of Archivematica, operating system, other relevant details)**

https://github.com/artefactual/archivematica/commit/e804cc1cc3130c276390b6a0ed63c115c8191576 on Docker. Confirmed on March 4th, 2020 on am111centos

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged (if applicable)
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by sallain** [comment]
This looks to be fixed:

1. I created an AIP using `SampleTransfers/DemoTransferCSV` and confirmed that the METS contains descriptive metadata for each object.
2. I did a metadata reingest and uploaded a metadata.csv file to the SIP (I used the one provided by @replaceafill above, which only has metadata for two objects)
3. I confirmed that the METS for the reingest AIP only has metadata for the two objects.

Tested on qa/1.x on RPM.
