### ISSUE TITLE
Problem: Non Dublin Core columns cause metadata re-ingest to fail

### ISSUE THREAD

**Issue by replaceafill** [archivematica/Issues#1139]
**Expected behaviour**

Metadata updated with [a CSV file uploaded through the user interface](https://www.archivematica.org/en/docs/archivematica-1.10/user-manual/ingest/ingest/#uploading-metadata-csv-files-through-the-user-interface) works with Dublin Core and custom columns.

**Current behaviour**

Only Dublin Core columns are updated and if the uploaded file has [non Dublin Core columns](https://www.archivematica.org/en/docs/archivematica-1.10/user-manual/transfer/import-metadata/#adding-non-dublin-core-descriptive-metadata) the re-ingest will fail like this:

![Captura de pantalla de 2020-03-05 15-17-20](https://user-images.githubusercontent.com/560781/76028781-e380f080-5ef8-11ea-9ed4-b34da3a35dd0.png)

**Steps to reproduce**

1. Set **Reminder: add metadata if desired:** to **None** in your processing configuration.
2. Run a `SampleTransfers/DemoTransferCSV` transfer
3. Run a metadata re-ingest on the transfer
4. When the metadata remainder is shown, [upload a CSV file](https://www.archivematica.org/en/docs/archivematica-1.10/user-manual/ingest/ingest/#uploading-metadata-csv-files-through-the-user-interface) that contains metadata for a file (e.g. `objects/bird.mp3`) with [non Dublin Core columns](https://www.archivematica.org/en/docs/archivematica-1.10/user-manual/transfer/import-metadata/#adding-non-dublin-core-descriptive-metadata). You can try with [metadata.txt](https://github.com/archivematica/Issues/files/4295325/metadata.txt). Make sure to rename it to `.csv`.
5. Try to finish the re-ingest and you will see the `Failed SIP` microservice. An error like the screenshot above will be in the `Generate AIP METS -> Generate METS.xml document ` job output.

**Your environment (version of Archivematica, operating system, other relevant details)**

https://github.com/artefactual/archivematica/commit/e804cc1cc3130c276390b6a0ed63c115c8191576 on Docker. Confirmed on March 4th, 2020 on am111centos

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged (if applicable)
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by sallain** [comment]
This is now fixed.

1. I created an AIP using SampleTransfers/DemoTransferCSV and confirmed that the METS contains descriptive metadata for each object.
2. I did a metadata reingest and uploaded a metadata.csv file to the SIP (I used the one provided by @replaceafill above, which contains non-DC metadata fields.)
3. I confirmed that the METS for the reingested AIP contains the non-DC metadata fields.

Tested on qa/1.x on RPM.
