### ISSUE TITLE
Problem: Test runs use different strategies across environments

### ISSUE THREAD

**Issue by replaceafill** [archivematica/Issues#1140]
**Expected behaviour**

All the test environments (Travis, docker-compose, etc) use the same settings for all the components.

**Current behaviour**

Travis CI runs tests through `tox` while the `docker-compose` environment calls `pytest` directly using different command line arguments and environment variables.

Let's take the MCPClient tests run as an example:

**docker-compose**

[In the docker-compose environment we use](https://github.com/artefactual-labs/am/blob/28b27909a19d44e5ad073c4a7e33478333b3be79/compose/Makefile#L147-L148):

```bash
$ docker-compose run --workdir /src/MCPClient --rm --entrypoint=py.test archivematica-mcp-client -p no:cacheprovider --reuse-db -v
```

This tells `pytest` to:

1. Only discover tests in the MCPClient directory (through the `--workdir` flag to `docker-compose`)
2. [Ignore previous test run results](https://docs.pytest.org/en/latest/cache.html)
3. [Not remove the test database and reuse it](https://pytest-django.readthedocs.io/en/latest/database.html#reuse-db-reuse-the-testing-database-between-test-runs)
4. Show verbose output.

Since we're using an `archivematica-mcp-client` container all of its environment variables from the [`MCPClient.Dockerfile`](https://github.com/artefactual/archivematica/blob/e804cc1cc3130c276390b6a0ed63c115c8191576/src/MCPClient.Dockerfile#L3-L7) and [`docker-compose.yml`](https://github.com/artefactual-labs/am/blob/28b27909a19d44e5ad073c4a7e33478333b3be79/compose/docker-compose.yml#L130-L148) files are used implicitly by the `pytest` call. Two of the most important ones are:

```
ENV DJANGO_SETTINGS_MODULE settings.common
ENV PYTHONPATH /src/MCPClient/lib/:/src/archivematicaCommon/lib/:/src/dashboard/src/
```

This combination makes the test run to use the `settings.common` module **from the MCPClient.lib directory** which in turn creates the `test_MCP` MySQL test database.

**tox**

`tox` on the other hand runs the MCPClient tests by starting in the `archivematica` top level directory and calling `pytest` like this:

```
py.test --ignore=src/MCPServer {posargs}
```

This only tells `pytest` to:

1. Discover tests for the dashboard, MCPClient and archivematicaCommon, but not the MCPServer
2. Use any positional arguments passed through the test run command line

The [combination of environment variables](https://github.com/artefactual/archivematica/blob/e804cc1cc3130c276390b6a0ed63c115c8191576/tox.ini#L9-L10) is also different and much simpler:

```
DJANGO_SETTINGS_MODULE = settings.test
PYTHONPATH = src/archivematicaCommon/lib:src/dashboard/src
```

This results in the `settings.test` module **from the dashboard** being used and produces an `archivematica-test.db` sqlite test database.

**Side effects**

These are a few side effects I've noticed from the two different set ups:

1. Different tests are discovered and they're executed in different order. This sometimes generates discrepancies in test runs like [this one found for the S3 tests](https://github.com/archivematica/Issues/issues/1048#issuecomment-572785442) of the Storage Service.

2. For the `tox` set up the `dashboard/src/settings/tests.py` module needs to include [MCPClient specific settings](https://github.com/artefactual/archivematica/blob/e804cc1cc3130c276390b6a0ed63c115c8191576/src/dashboard/src/settings/test.py#L76-L79) for some tests to work.

3. Since the docker-compose environment tries to reuse the test database sometimes the following situation arises:

    a. The test database is deleted with `make flush-test-dbs`
    b. The MCPClient tests are run and they fail
    c. The MCPClient tests are run again immediately and they pass the second time because the tables already contain the data that makes the test pass

    You can see the [output of such situation here](https://github.com/archivematica/Issues/files/4303961/docker-mcp-client.txt) (I added the `-p no:warnings` flag to make the output a bit more clear). You can look for the 4 `replaceafill@eluk:~/dev/archivematica/am/compose$` prompts to identify where the test runs begin and end. 

**Steps to reproduce**

Tests can be run in docker-compose as instructed above and `tox` can be run from the `archivematica` top level directory in the source code installed in a virtual environment.

**Your environment (version of Archivematica, operating system, other relevant details)**

https://github.com/artefactual/archivematica/commit/e804cc1cc3130c276390b6a0ed63c115c8191576 in docker-compose

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged (if applicable)
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by sevein** [comment]
This is useful, @replaceafill. Would you say that this conflates with https://github.com/archivematica/Issues/issues/392? We could stop working around these virtual packages that we created and standardize the layout of the project. Things would be much simpler if we followed standard packaging practices with a few entry points. We would probably not need to package multiple Docker images with different environment strings other than application config.

**Comment by tw4l** [comment]
FWIW, this is currently effectively blocking us from running the Makefile test commands in our Docker Compose development environment. https://github.com/artefactual/archivematica/pull/1610 was closed in favor of a better solution, but in the meantime anyone using Docker Compose has to use a workaround (like what was suggested in that PR, or running tox in a local virtualenv like @replaceafill mentioned in his comment on that PR).

**Comment by sevein** [comment]
Another annoyance discussed here: https://github.com/artefactual/archivematica/pull/1630#discussion_r457904748 - test_cas, test_ldap, test_shibboleth are ignored unless their corresponding toggles are enabled. We probably need to orchestrate different runs from the runner since Django doesn't seem to be very flexible to mutate certain settings.

**Comment by tw4l** [comment]
FYI, `make test-dashboard` is still failing following the recent inclusion of the Docker-Compose dev environment in the main Archivematica repo, due to the same Whitenoise issue identified last July. It would be great to get a fix in place, either by having Docker-Compose use the test environment or by disabling Whitenoise in the local environment. I've been doing the latter for my local dev environment but it's a pain to have to continually `git stash` and `git stash apply`.

**Comment by tw4l** [comment]
Just saw [this comment](https://github.com/artefactual-labs/am/issues/24#issuecomment-762718499) from last week so @replaceafill may already be on it! Just wanted to flag that it's been an ongoing issue for some of us.
