### ISSUE TITLE
Problem: processing config choices are ignored at times 

### ISSUE THREAD

**Issue by sevein** [archivematica/Issues#1141]
**Expected behaviour**
MCPServer should honour processing config choices when available.

**Current behaviour**
We've seen situations in which MCPServer seems to ignore user-defined processing config choices which results in user prompts. This is for example a problem in automated environments where users are not expected to interact with Archivematica during processing.

MCPServer's `server.jobs.decisions.DecisionJob` sets the thread event flag `awaiting_decision` to true when the preconfigured choice was not found. `server.processing_config.load_preconfigured_choice` seems to fail finding the processing config file or extracting the choice. The processing config seems to be in place when checking manually so this might be a case of transfers not being moved around atomically during processing? We'll have to investigate further.

**Update!** ⸻ We've identified other cases where MCPClient communicates task errors because the files are not reachable. This is happening in ~1% of the packages that we've been processing in our tests environments. See https://github.com/archivematica/Issues/issues/1111 for more details.

**Steps to reproduce**
I haven't been able to reproduce locally but I'll ask @scollazo to share details.

**Your environment (version of Archivematica, operating system, other relevant details)**
qa/1.x

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged (if applicable)
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by jorikvankemenade** [comment]
It might be interesting to add that I had this particular problem in Archivematica v9, v10, as well as qa/1.x. I have tried to find a root cause before opening an issue, or at least a reliable way of reproducing it, but so far I had no luck. IIRC the issue appears more often with certain config choices than others. For example, I have only encountered it during the transfer stage and not in the ingest phase.

**Comment by sevein** [comment]
Thanks @jorikvankemenade. We've had some success with https://github.com/artefactual/archivematica/pull/1587 (brings zero error rates) but I haven't had the time to fully understand what is that I'm fixing, not yet! It's a code path that only seems to be needed very rarely.

**Comment by sevein** [comment]
I'm wondering whether this is a case where clients scripts such `move_transfer` making changes such `Transfer.objects.filter(uuid=transferUUID).update(currentlocation=dst)` should use `SELECT FOR UPATE` to make sure that other queries (e.g. `get_or_create_from_db_by_path`) should wait until the row is updated.

**Comment by jorikvankemenade** [comment]
> I'm wondering whether this is a case where clients scripts such `move_transfer` making updates like the following:
> 
> ```python
> Transfer.objects.filter(uuid=transferUUID).update(currentlocation=dst)
> ```
> 
> should try instead to use `SELECT FOR UPATE`, to make sure that other queries wait until the row is updated

You mean that maybe this issue and #1111 are related? This could be the case, I am not sure. I looked into the `update` [documentation of Django](https://docs.djangoproject.com/en/1.8/ref/models/querysets/#update) for #1111. It says:

> Using update() also prevents a race condition wherein something might change in your database in the short period of time between loading the object and calling save().
>
> Finally, realize that update() does an update at the SQL level and, thus, does not call any save() methods on your models, nor does it emit the pre_save or post_save signals (which are a consequence of calling Model.save()). If you want to update a bunch of records for a model that has a custom save() method, loop over them and call save()

But this is only one particular kind of race. I don't think this will protect fore the case where the update changes a location and another query overwrites it to the old value for example.

**Comment by joel-simpson** [comment]
This was originally noticed in an environment running several transfers in parallel, automated by Enduro so that hundreds of transfers were running consecutively. We have since run the same volumes with this fix and been unable to reproduce the original issue.
