### ISSUE TITLE
Problem: TIME_ZONE setting is not configurable

### ISSUE THREAD

**Issue by sevein** [archivematica/Issues#1143]
**Please describe the problem you'd like to be solved**
The web framework that Archivematica uses provides a `TIME_ZONE` setting (https://docs.djangoproject.com/en/1.8/topics/i18n/timezones/) that determines the application timezone. It is meant to be configurable but Archivematica does not provide that configurability to its users (via envs or config).

This is true in both Archivematica and Storage service.

**Describe the solution you'd like to see implemented**
Look up the desired value of `TIME_ZONE` using our configuration mechanisms. Use envs following the pattern `ARCHIVEMATICA_DASHBOARD_TIME_ZONE`.

**Describe alternatives you've considered**
In older versions of Archivematica not providing the level of configurability that we need, users could still patch the settings module but that's not a process that we've documented.

**Additional context**
This issue relates or is a subset of https://github.com/archivematica/Issues/issues/291.

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [x] All pull requests related to this issue are properly linked
- [x] All pull requests related to this issue have been merged
- [x] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [x] Documentation regarding this issue has been written and merged
- [ ] Details about this issue have been added to the release notes

**Comment by sevein** [comment]
Envs used:
- `ARCHIVEMATICA_DASHBOARD_TIME_ZONE`
- `ARCHIVEMATICA_MCPCLIENT_TIME_ZONE`
- `ARCHIVEMATICA_MCPSERVER_TIME_ZONE`
- `TIME_ZONE` (in Storage Service)

**Comment by tw4l** [comment]
Tested in Docker and in a QA VM (Ubuntu Bionic). After setting time zone to "Europe/Oslo" in environment variables, all logs are confirmed writing dates correctly in UTC+01:00.
