### ISSUE TITLE
Question: File format detection as an application?

### ISSUE THREAD

**Issue by DonaldTsang** [archivematica/Issues#1147]
I would like to use Archivematica and Siegfred's file detection algorithm for another project.
What can I do, assuming that the project is in either Python or Golang?

**Comment by sallain** [comment]
Hi @DonaldTsang - I'd recommend posting this question on the [Archivematica user forum](https://groups.google.com/forum/#!forum/archivematica) instead.

**Comment by DonaldTsang** [comment]
@sallain I would like to avoid the use of Google Group at all costs, are there other ways of contact (excluding mailing list)?

**Comment by sallain** [comment]
@DonaldTsang Unfortunately that is the home of the public mailing list for the Archivematica project. You may wish to try some general mailing lists where library technologists and digital preservationists talk, such as the [ALA Digital Preservation list](https://lists.ala.org/sympa/subscribe/digipres?previous_action=info), the [Code4Lib mailing list](https://lists.clir.org/cgi-bin/wa?A0=CODE4LIB), or similar lists in your area.
