### ISSUE TITLE
Problem: Compressed AIPs break replication

### ISSUE THREAD

**Issue by replaceafill** [archivematica/Issues#1149]
**Expected behaviour**

Replication works with compressed and uncompressed AIPs.

**Current behaviour**

Due to a path change introduced in https://github.com/artefactual/archivematica-storage-service/pull/521 when a compressed AIP is stored in a replicated location the `Store AIP` job fails like this:

![Captura de pantalla de 2020-03-13 20-47-33](https://user-images.githubusercontent.com/560781/76673560-f8e6c200-656b-11ea-80c7-9a973bf90836.png)

and the logs show:

```
archivematica-storage-service_1  | INFO      2020-03-13 19:47:16  locations.models.package:package:replicate:580:  Replicating package f6d8b1b3-0d5b-449a-a599-91a5cdefd5cd to replicator location 8d6938e4-ca55-48fe-8ec0-0a92198f5b4f
archivematica-storage-service_1  | DEBUG     2020-03-13 19:47:16  common.utils:utils:uuid_to_path:579:  path bf30/92df/2dcc/4449/bcb1/3196/09e0/cad4
archivematica-storage-service_1  | DEBUG     2020-03-13 19:47:16  locations.models.space:space:move_to_storage_service:344:  TO: src: var/archivematica/sharedDirectory/www/AIPsStore/f6d8/b1b3/0d5b/449a/a599/91a5/cdef/d5cd/demo-f6d8b1b3-0d5b-449a-a599-91a5cdefd5cd.7z/
archivematica-storage-service_1  | DEBUG     2020-03-13 19:47:16  locations.models.space:space:move_to_storage_service:345:  TO: dst: bf30/92df/2dcc/4449/bcb1/3196/09e0/cad4/demo-bf3092df-2dcc-4449-bcb1-319609e0cad4.7z
archivematica-storage-service_1  | DEBUG     2020-03-13 19:47:16  locations.models.space:space:move_to_storage_service:346:  TO: staging: /var/archivematica/storage_service
archivematica-storage-service_1  | INFO      2020-03-13 19:47:16  locations.models.space:space:move_rsync:550:  Moving from /var/archivematica/sharedDirectory/www/AIPsStore/f6d8/b1b3/0d5b/449a/a599/91a5/cdef/d5cd/demo-f6d8b1b3-0d5b-449a-a599-91a5cdefd5cd.7z/ to /var/archivematica/storage_service/bf30/92df/2dcc/4449/bcb1/3196/09e0/cad4/demo-bf3092df-2dcc-4449-bcb1-319609e0cad4.7z
archivematica-storage-service_1  | INFO      2020-03-13 19:47:16  locations.models.space:space:move_rsync:592:  rsync command: ['rsync', '-t', '-O', '--protect-args', '-vv', '--chmod=Fug+rw,o-rwx,Dug+rwx,o-rwx', '-r', '/var/archivematica/sharedDirectory/www/AIPsStore/f6d8/b1b3/0d5b/449a/a599/91a5/cdef/d5cd/demo-f6d8b1b3-0d5b-449a-a599-91a5cdefd5cd.7z/', '/var/archivematica/storage_service/bf30/92df/2dcc/4449/bcb1/3196/09e0/cad4/demo-bf3092df-2dcc-4449-bcb1-319609e0cad4.7z']
archivematica-storage-service_1  | WARNING   2020-03-13 19:47:17  locations.models.space:space:move_rsync:600:  Rsync failed with status 23: sending incremental file list
archivematica-storage-service_1  | rsync: change_dir "/var/archivematica/sharedDirectory/www/AIPsStore/f6d8/b1b3/0d5b/449a/a599/91a5/cdef/d5cd/demo-f6d8b1b3-0d5b-449a-a599-91a5cdefd5cd.7z" failed: Not a directory (20)
archivematica-storage-service_1  | delta-transmission disabled for local transfer or --whole-file
archivematica-storage-service_1  | total: matches=0  hash_hits=0  false_alarms=0 data=0
archivematica-storage-service_1  | 
archivematica-storage-service_1  | sent 20 bytes  received 79 bytes  198.00 bytes/sec
archivematica-storage-service_1  | total size is 0  speedup is 0.00
archivematica-storage-service_1  | rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1196) [sender=3.1.2]
archivematica-storage-service_1  | 
archivematica-storage-service_1  | DEBUG     2020-03-13 19:47:17  locations.api.resources:resources:hydrate_current_location:945:  `current_location` was not matched by `default_location_regex`
archivematica-storage-service_1  | DEBUG     2020-03-13 19:47:18  locations.models.async_manager:async_manager:_watchdog_loop:123:  Watchdog sees 0 tasks running
```

with the relevant line being:

```
archivematica-storage-service_1  | DEBUG     2020-03-13 19:47:16  locations.models.space:space:move_to_storage_service:344:  TO: src: var/archivematica/sharedDirectory/www/AIPsStore/f6d8/b1b3/0d5b/449a/a599/91a5/cdef/d5cd/demo-f6d8b1b3-0d5b-449a-a599-91a5cdefd5cd.7z/
```

Notice the trailing slash after the `.7z` extension.

If I store the AIP uncompressed the transfer succeeds.

This was discovered through the [aip-encryption-mirror.feature](https://github.com/artefactual-labs/archivematica-acceptance-tests/blob/8339c51ed0dd0c27c2c3bd5752c9651c2604cb1d/features/core/aip-encryption-mirror.feature) AMAUAT.

**Steps to reproduce**

1. Set a Replicator location for the default AIP Storage location
2. Set the processing configuration to store the AIP compressed in the default AIP  Storage location
3. Run a `SampleTransfers/DemoTransferCSV`
4. The `Store AIP` job will fail as explained
5. Change the processing configuration to store the AIP uncompressed in the default AIP  Storage location
6. Run a new `SampleTransfers/DemoTransferCSV`
7. The transfer will succeed

**Your environment (version of Archivematica, operating system, other relevant details)**

https://github.com/artefactual/archivematica/commit/a1322a9162e3c43ded3c83f09b8c2568d5cb66d1 and https://github.com/artefactual/archivematica-storage-service/commit/ed10c120632ba6330660acb713c197175b3c58c5 on docker. Jenkins have been failing the `aip-encryption-mirror.feature` in all the platforms combinations since Feb 28th (a couple of days after the mentioned change was merged.

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged (if applicable)
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by ablwr** [comment]
This is true for AIPs that are 7z without compression too, right?

**Comment by sallain** [comment]
@ablwr yes I believe so - anything other than "Uncompressed"

**Comment by sallain** [comment]
This is working now! I've got a stored AIP and a replica. The AIP was created with the default compression settings. Tested on 1.11.2 on Centos

![image](https://user-images.githubusercontent.com/4612276/84205758-a762ac00-aa62-11ea-95ee-1dff37f6ec03.png)

![image](https://user-images.githubusercontent.com/4612276/84205814-c5301100-aa62-11ea-80b9-83815a8d007e.png)
