### ISSUE TITLE
Problem: no clear description of the effect of not installing ElasticSearch

### ISSUE THREAD

**Issue by npoppeli** [archivematica/Issues#1158]
**Version of the documentation**
1.11

**Page (and section, if applicable) where the issue occurs**
Administrator manual, Manual install on Ubuntu

**Description of the issue**
There is no clear description of the effect of not installing ElasticSearch

**Suggested fix**
Add which functionalities will be absent when you skip the installation of ElasticSearch, e.g. certain tabs in the dashboard

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by sromkey** [comment]
That's a fair assessment- this section describes that the search is disabled but not that the tabs actually disappear! https://www.archivematica.org/en/docs/archivematica-1.11/admin-manual/installation-setup/installation/installation/#elasticsearch

**Comment by sallain** [comment]
Thanks for filing this @npoppeli! I had time today so I made some fixes that will hopefully make it clearer.
