### ISSUE TITLE
Problem: There are a few more places we need to modify a microservice name to "change ... names"

### ISSUE THREAD

**Issue by ross-spencer** [archivematica/Issues#1163]
**Expected behaviour**

Per https://github.com/archivematica/Issues/issues/230 we're transitioning away from using `sanitize` in microservice names, but we've captured a few more instances today. 

**Current behaviour**

Talking to Sara, it looks like the final names it looks like we need to change are:

* `"en": "Sanitize file and directory names in metadata",`
* `"en": "Sanitize extracted objects' file and directory names",`
* `"en": "Sanitize file and directory names in submission documentation",`                                

And these would take the form along the lines of: `Change object and directory filenames`

**Your environment (version of Archivematica, operating system, other relevant details)**

Archivematica 1.11.0.

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged (if applicable)
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by sallain** [comment]
The changes listed above have been made.
