### ISSUE TITLE
Problem: lack of single entry point for developers is inconvenient

### ISSUE THREAD

**Issue by sevein** [archivematica/Issues#1165]
**Please describe the problem you'd like to be solved**
Developers can't set up their environment without the auxiliar ([am.git:/compose](https://github.com/artefactual-labs/am/tree/master/compose)) repo.

**Describe the solution you'd like to see implemented**
A smoother dev workflow would be to start off a single repository - for this to be possible, we should have all the artifacts of our development environment become part of our main repository. It's a common pattern in many projects to have a `docker-compose.yml` document in the root of the repo.

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged
- [ ] Details about this issue have been added to the release notes

**Comment by scollazo** [comment]
One issue I have with this approach, is that Archivematica development will be encouraged in  environments that are not related at all with the ones used in production, and that's a big risk from my point of view.

The divergences between development and production environments are a cause of headaches since the begining of times, so I would like to keep development and production deployment methods aligned as best as we could.

**Comment by RussellMcOrmond** [comment]
I'm curious if Artefactual has considered using the Docker images within production environments rather than using ansible  (or having Ansible only build the environment that Docker images run on).

In our production environment we intend to be using the Docker images.

**Comment by scollazo** [comment]
@RussellMcOrmond I don't know if that has been pitched to clients, but lately we have seen an increase of requests for installing archivematica from rpm packages on Centos/RHEL environments

**Comment by RussellMcOrmond** [comment]
@scollazo As a sysadmin I've become a huge fan of Docker as much of the complexity of application building is kept to the Docker file, and running the containers becomes agnostic to which distribution I'm using (and with Docker providing Linux for Windows and Mac, even what operating system is being run).

I know Artefactual creates packages for Ubuntu and CentOS/RHEL, but wouldn't have to if Docker became the standard way to deploy.   Unless there was a desire to create a meta-package that would set up Docker and pull the right images, making deployment in those environments trivial for those who don't currently know Docker.

I know Canonical  is using linux containers with their Snappy package management  system to avoid users even needing to know that containers are involved.

**Comment by scollazo** [comment]
@RussellMcOrmond while I don't disagree with you about how docker hides things, it's also a relatively new technology, and I don't want to push others to try and support in production the latest thing that came off the selves, but allow them to run archivematica using their preferred methods, not mine...

Also, using docker-compose in it's actual form doesn't allow you to run more than one pipeline on each host, and I'm not sure how to split our docker compose between different hosts, so in the end, there is no real difference to the end user between using docker,  rpm or source deployments, imho.

**Comment by RussellMcOrmond** [comment]
@scollazo Understood.  I'm always trying to separate build and distribution which is under the control of our development team from how things are run.  This allows flexibility for the sysadmins without needing to worry about app library/etc dependencies/etc which are all things handled by the developers (and encapsulated in containers).  This avoids the problem we had in the past where the environment that the developers were using (OS versions, packages, libraries, etc) was different than production, while allowing more complex running environment (networking, storage, number of containers, etc) in production than is used by developers.

While the developers have a docker-compose they use for testing, I use a different compose for production.  Enough of the app is encapsulated in the containers such that this isn't a major difference.

**Comment by sevein** [comment]
We will not fix, see comments [above](https://github.com/archivematica/Issues/issues/1165#issuecomment-609887418).
