### ISSUE TITLE
Problem: Changing a processing configuration is time consuming and not user-friendly

### ISSUE THREAD

**Issue by peterVG** [archivematica/Issues#1166]
**Please describe the problem you'd like to be solved**
When a user wants to switch to a different Archivematica pipeline processing configuration during her current Transfer she has to download a processingMCP.xml file from the Archivematica Administration dashboard tab and add it into her transfer directories. This process is not very user-friendly and it takes extra time to complete these manual steps repeatedly between different transfer types.

**Describe the solution you'd like to see implemented**

**Feature**:  Select processing configuration at the start of a Transfer
**Scenario**: 	The user is about to process a Transfer in Archivematica but she wants to change the decision point settings she has been using previously by selecting an alternate processing configuration file.
**Given**: That the “default”, “automated” and any additional, custom processing configuration files are saved in the Archivematica Administration tab.
**And:** The “default” processing configuration is set as the default option.
**When:** She selects an alternate processing configuration file from a drop-down select box in the Transfer tab (e.g. “my_custom_processing_config_1”)
**Then:** The Transfer and Ingest processing will follow the decisions set out in the newly selected processing configuration file, rather than the “default”  processing configuration.
**And** The user will receive a pop-up notification indicating that the Transfer has started with the selected processing configuration.
**And:** The “default” processing configuration will be reset as the default option the next time a Transfer is started.

![AM-wireframe-process-config-5b](https://user-images.githubusercontent.com/672121/78712040-d32fad00-78cc-11ea-9116-606808d4f9cf.png)

**Additional context**

See from https://github.com/artefactual/archivematica/issues/800

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged
- [ ] Details about this issue have been added to the release notes

**Comment by peterVG** [comment]
This feature has been successfully tested. 



Both **Then** statements are true: "The Transfer and Ingest processing will follow the decisions set out in the newly selected processing configuration file, rather than the “default” processing configuration."
**And:** "The “default” processing configuration will be reset as the default option the next time a Transfer is started."

**Comment by peterVG** [comment]
During the course of client review we added one other scenario to this feature.

**Feature**: Use custom processing configuration file in Transfer
**Scenario**: The user is about to process a Transfer in Archivematica but she wants to change the decision point settings she has been using previously by inserting an alternate processing configuration file she has created and downloaded using the Administration - Processing Configuration menu.
**Given**: That the user has downloaded the processing configuration file for called "custom3" from the Administration Dashboard menu.
**And:** She has renamed it to "processingMCP.xml" and inserted it at the top-level of the Transfer she is going to process.
**When**: She selects an alternate processing configuration file from a drop-down select box in the Transfer tab (e.g. “custom1")
**Then**: The options in the processingMCP.xml file will take precedence and the Transfer and Ingest processing will follow the decisions set out in the "custom3" processingMCP.xml configuration file, rather than the “custom1” processing configuration settings.

**Comment by sromkey** [comment]
:star2: My fav new feature! Working great.
