### ISSUE TITLE
Problem: the user is not seeing all relevant information on the Backlog tab

### ISSUE THREAD

**Issue by peterVG** [archivematica/Issues#1167]
**Please describe the problem you'd like to be solved**
The user is not seeing the complete set of information they need to efficiently process their Archivematica packages. They would like to add package sizes, accession number, and outstanding deletions to the columnar display of packages on the Backlog tab. 

**Describe the solution you'd like to see implemented**

**Feature:** Select which columns to display in the table list on the Backlog tab 
**Scenario:** The user has moved transfer packages to Backlog and is now ready to take further actions on them.
**Given:** That they can browse packages using the table list, column sorting, and list paging on the Backlog tab.
**And:** The default Name, Transfer UUID, File Count, Ingest Date, and Actions columns are currently displayed in the table list.
**When:** They click on the column selector icon, they can deselect one or more of the currently displayed default columns and can select one or more <column> options in their place.
**Then:** The columns displayed in the table list on the Backlog tab match the selected and deselected options.
**And:** These selections will also apply to the “Show files” display option (except “File Count”)
**And:** These selections will be applied to all users of the pipeline
**And:** The select and deselect choices will persist between user sessions 

**Examples:** 
|      column                      |
| Package Size                 |
| Accession Number       |
| Outstanding Deletions |

![AM-wireframe-column-picker-8-Page-2](https://user-images.githubusercontent.com/672121/78713596-60740100-78cf-11ea-818f-ad542790b733.png)

**Describe alternatives you've considered**
Replacing existing columns, e.g. eliminating the long UUID field and replacing it with two new columns, is problematic because which columns on the limited horizontal screen real estate are most relevant is a user-specific criterion. That is, those columns that may be useful to one user may be less so to an Archivematica user at another institution. 

**Additional context**

Any new strings introduced as part of this feature enhancements (e.g. "Select columns, column headers) should be translatable. 

The Backlog table uses the https://datatables.net/ javascript library. For consistency, the same library & look-n-feel should be applied to the "Show files" option.

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged
- [ ] Details about this issue have been added to the release notes

**Comment by peterVG** [comment]
This feature has been successfully tested:
<img width="1307" alt="Screen Shot 2020-05-08 at 1 09 42 PM" src="https://user-images.githubusercontent.com/672121/81445595-02d10f80-912e-11ea-928d-38954a51fa78.png">

<img width="1306" alt="Screen Shot 2020-05-08 at 1 11 13 PM" src="https://user-images.githubusercontent.com/672121/81445598-05336980-912e-11ea-8205-664ac4ca23c3.png">

Column selection applies to "Show files" and persists between different users and different user sessions.

**Comment by peterVG** [comment]
Draft docs done. Need to be added to am-docs repo.

**Comment by sromkey** [comment]
Working great in QA.
