### ISSUE TITLE
Problem: SS tests break with pytest 3.7 or newer

### ISSUE THREAD

**Issue by sevein** [archivematica/Issues#118]
In https://github.com/archivematica/Issues/issues/58 (https://github.com/artefactual/archivematica-storage-service/pull/399) we pinned pytest to its 3.6 release because 3.7 seemed incompatible. This was done in preparation for the 0.12 release of SS.

This new issue is filed to track the work needed so SS is upgraded to be compatible with pytest 3.7 or newer.

**Comment by sevein** [comment]
@sromkey I think the milestone should be 0.13 (SS).

**Comment by sromkey** [comment]
ya, I know it's kind of confusing, but we're using the 1.8 milestone to track both 1.8 and 0.13 since they'll be released together.

**Comment by sevein** [comment]
ok that makes sense thx
