### ISSUE TITLE
Problem: Commit message style links have moved on Archivematica's CONTRIBUTING.md

### ISSUE THREAD

**Issue by ross-spencer** [archivematica/Issues#1181]
**Version of the documentation**

See: [here](https://github.com/artefactual/archivematica/blob/4f2abe13a40ae330462a01d38e1ab5b3ce46d950/CONTRIBUTING.md#commit-messages)

And, the link in 4. [here](https://github.com/artefactual/archivematica-docs/wiki/Contributing-guide-for-community-members#create-a-pull-request) seems to have been pointing to the same place.

**Page (and section, if applicable) where the issue occurs**

As above.

**Description of the issue**

In general we've adopted the [50/72](https://chris.beams.io/posts/git-commit/) rule as a style and this was more explicit in our documents previously. We link to it [here](https://github.com/artefactual/archivematica-docs/wiki/Contributing-guide-for-community-members#create-a-pull-request). It's important to be able to point to information like this during code review to allow us to recognize that there is a process and a style we adopt here. _"The change I am asking for, is not subjective, it's based on something well documented and considered."_

**Suggested fix**

I'm not sure. Personally I do believe it belongs in a central style guide and linked out to from other contributing documents to avoid redundancy. There may be other options.

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by sromkey** [comment]
Looking at the history I can't find the move? Can you help me see it @ross-spencer ?

**Comment by ross-spencer** [comment]
The link hasn't changed @sromkey the page behind the link has.

**Comment by sallain** [comment]
So... I think what this issue means is that there is a broken link? Linking to the [AM contributing.md section on commit messages](https://github.com/artefactual/archivematica/blob/stable/1.11.x/CONTRIBUTING.md#commit-messages) would probably be a sufficient fix.

**Comment by sallain** [comment]
Oh wait it's sort of a circular problem. I'll fix it up.
