### ISSUE TITLE
Problem: documentation on reviewing DIPs from dashboard is incorrect

### ISSUE THREAD

**Issue by sallain** [archivematica/Issues#1186]
**Version of the documentation**
1.11 and earlier

**Page (and section, if applicable) where the issue occurs**
User Manual > Access > [Review and Download DIPs](https://www.archivematica.org/en/docs/archivematica-1.11/user-manual/access/access/#review-dip)

**Description of the issue**
The docs say "Regardless of the access path chosen (an integrated access system, or storing the DIP) the dashboard will present the operator with the option of reviewing and downloading the DIP objects."

This isn't accurate - you can only download the DIP via the Review button if you've uploaded it, because then the DIP ends up in the `uploadedDIPs` directory.

This is the behaviour if you upload a DIP to AtoM - the Review button appears.

![image](https://user-images.githubusercontent.com/4612276/80150024-7be83880-856c-11ea-904c-71c0a6371ccd.png)

And this is the behaviour if you do not upload the DIP - no Review button.

![image](https://user-images.githubusercontent.com/4612276/80150144-b0f48b00-856c-11ea-9f27-1a95e75709b7.png)

**Suggested fix**
I believe this is an error in documentation, rather than a bug in Archivematica, but not 100% sure. Should all DIPs end up in the `uploadedDIPs` directory so that they are available for review? This would require a change in the microservice chainlinks.

For now I'd like to change the documentation so that it reflects current behaviour.

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by sallain** [comment]
@sromkey can you confirm that I've got the right read on this issue?

**Comment by sromkey** [comment]
Yes, you've got it right. The functionality changed but the docs didn't follow- basically our thinking was if you're storing your DIP rather than uploading it, you really don't need another copy sent to `uploadedDIPs`. The diagram at the bottom of this wiki page is accurate: https://wiki.archivematica.org/DIP_storage_to_designated_location
