### ISSUE TITLE
Problem: Transfer/AIP status is not kept in sync between Storage Service and Elasticsearch when package deletions are made directly via Storage Service

### ISSUE THREAD

**Issue by tw4l** [archivematica/Issues#1189]
**Expected behaviour**

When I make a deletion request for a package (transfer or AIP), the related document is updated in the appropriate Elasticsearch index.

When I complete a package (transfer or AIP) deletion, the related document is removed from the appropriate Elasticsearch index.

At all times the status in the Storage Service and the `pending_deletion` field in Elasticsearch should be in sync and up-to-date.

**Current behaviour**

When I request deletions from the Archivematica GUI ("Backlog" or "Archival Storage" tabs), package status in Elasticsearch (ES) and the Storage Service stays in-sync.

When I request and confirm deletions exclusively from the Storage Service, bypassing the Archivematica GUI, the `pending_deletion` field in appropriate ES indices (`transfers`, `aips`, `transferfiles` and `aipfiles`)  is never updated.

The Archival Storage component has [some logic to try to detect changes and update the ES index appropriately](https://github.com/artefactual/archivematica/blob/stable/1.11.x/src/dashboard/src/components/archival_storage/views.py#L472-L532), but this only works in the case that the deletion request was initially made via the Archivematica GUI or manually updated in Elasticsearch.

**Steps to reproduce**

* Create a package and store in transfer backlog or AIP store
* Request deletion from Storage Service, via Storage Service GUI or the API
* Confirm that package status is not updated in Elasticsearch by looking at data in "Backlog" and/or "Archival Storage" tables.

**Your environment (version of Archivematica, operating system, other relevant details)**

Archivematica 1.11

**Related issues and PRs**

* https://github.com/artefactual/archivematica/pull/1597
* https://github.com/artefactual/archivematica-storage-service/issues/344
* https://github.com/artefactual/archivematica/issues/941

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged (if applicable)
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by tw4l** [comment]
One possible solution is to manage this in our views in Archivematica, by polling the Storage Service for each package returned in search results, checking if there are differences between the reported status in Storage Service vs. ES, and updating ES as necessary. This is the approach we have taken up to this point but comes at the expense of performance when this checking and updating happens synchronously, as it does currently. For a handful of transfers in a backlog this performance hit might not be much of an issue; for instances of Archivematica with many thousands of stored AIPs, it could be quite noticeable. So if we are taking this approach, we might want to look into making as much of this as possible happen asynchronously.

Another solution might be to have the Storage Service issue a call to update ES after every change in package status directly, perhaps hooking into the existing signals used to send administrator notification emails.

**Comment by tw4l** [comment]
Existing function [check_and_remove_deleted_transfers](https://github.com/artefactual/archivematica/blob/4f2abe13a40ae330462a01d38e1ab5b3ce46d950/src/dashboard/src/components/backlog/views.py#L41-L71) in the backlog component does something similar to what we want, but only when a document is already marked as `pending_deletion` in ES.

**Comment by ross-spencer** [comment]
Related to https://github.com/artefactual/archivematica-storage-service/issues/344 (I believe it should be closed by this one (1189).

**Comment by ross-spencer** [comment]
oh, this one can be moved to done right @tw4l?

**Comment by tw4l** [comment]
@ross-spencer yes, good catch!

**Comment by ross-spencer** [comment]
I was trying to delete a package and I'm not sure that this issue is quite solved yet. 

From Archivematica deletion seems to work. 

From the storage service, I believe there are two different scenarios, one of which works, the other doesn't:

**Scenario 1 (Works):**

1. Request deletion via the storage service. 
2. Refresh Archival Storage tab in Archivematica (status is set to deletion requested).
3. Confirm deletion from the storage service. 
4. Refresh Archival Storage (package is gone).

**Scenario 2 (Doesn't work):**

1. Request deletion via the storage service. 
2. DO NOT refresh Archival Storage tab in Archivematica.
3. Confirm deletion from the storage service. 
4. Refresh Archival Storage (Package is still there and set to stored).

**Comment by tw4l** [comment]
Good eye @ross-spencer !  In the long run I think it would be better to update the indices from the source of the change (the Storage Service) but given current limitations with that, I've I made an attempt to improve the existing behaviour in https://github.com/artefactual/archivematica/pull/1642 (put together in bits and pieces as I was waiting for some long-running processes to complete this week). Might be a bit late in the game to get this fix into 1.12, but it would be nice to close this issue properly when we're able.

**Comment by tw4l** [comment]
@ross-spencer @sevein In my testing, this appears to be fixed by the just-merged https://github.com/artefactual/archivematica/pull/1642. Would one of you want to verify so that we can move this to done?

**Comment by sallain** [comment]
I tested both of the scenarios in Ross' comment above and both worked as expected:

Scenario 1: Package is removed from Archival Storage tab
Scenario 2: Package is removed from Archival Storage tab
