### ISSUE TITLE
Problem: Ubuntu 18.04 is not supported

### ISSUE THREAD

**Issue by scollazo** [archivematica/Issues#119]
**Please describe the problem you'd like to be solved.**
Archivematica should be supported in the latest LTS Ubuntu release

**Describe the solution you'd like to see implemented.**
Support Archivematica on Ubuntu 18.04

**Describe alternatives you've considered.**

**Additional context**

**Comment by sevein** [comment]
Assigned 1.7.2 milestone to it as agreed that we're adding experimental support for Ubuntu 18.04.
This is also planned to happen in the upcoming Archivematica 1.8.0.
