### ISSUE TITLE
Problem: Storage Service unreachable when Re-Ingest in progress

### ISSUE THREAD

**Issue by Rayzilt** [archivematica/Issues#1193]
**Expected behaviour**
Storage Service always available for request from Dashboards Services or it's own webinterface

**Current behaviour**
This set-up contains two seperate VMs for the Dashboard Service [DS] and one Storage Service [SS].

When a DS is requesting a Re-Ingest, the Storage Service SS needs to copy the AIP to the DS for processing. In this timeperiod the SS is not responding to other requests, like the 'Browse' button in the transfer tab (From another DS), nor does it respond to webinterface requests.

This will generate timeouts everywhere until the copy process is done.

**Steps to reproduce**
Start a re-ingest and try to access the storage service webinterface.

**Your environment (version of Archivematica, operating system, other relevant details)**
AM: v1.11
Storage: 0.16
Ubuntu 18.04
2x Dahsboard VM's
1x Storage VM

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged (if applicable)
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by ross-spencer** [comment]
Thanks @Rayzilt. I've been picking at this periodically over the last few days. I have an 8 core VM available to me, and that seemed to work okay. So I used my 2 core VM and again, 10,000 1MB files transfer over for reingest without blocking the storage service. 

Archivematica and the Storage Service are running within the same VM so I wonder if that has a part to play here? 

I wonder though, can you share more information about your setup?

* How the VMs are provisioned and what disks they are running on maybe? 
* Perhaps a content breakdown of the SIP? A rough approximation of the size of the AIP, and maybe some idea about the largest and smallest files? 

Regarding the rsync command, then I don't know what an optimization might look like off the top of my head, but I do notice two slight differences between the start of a transfer, and then the commencement of a partial reingest. Start transfer uses a single rsync command to move the transfer directory:

```
INFO      2020-05-04 11:20:26  locations.models.space:space:move_rsync:592:  rsync command: ['rsync', '-t', '-O', '--protect-args', '-vv', '--chmod=Fug+rw,o-rwx,Dug+rwx,o-rwx', '-r', '/var/archivematica/storage_service/var/archivematica/sharedDirectory/tmp/tmpIIl_KA/10-000-5mb-objects/./', '/var/archivematica/sharedDirectory/tmp/tmpIIl_KA/10-000-5mb-objects/.']
```

And then on partial reingest, a manifest is built by the storage adapter than then sent one by one:

```
INFO      2020-05-05 06:45:10  locations.models.package:package:extract_file:1559:  Extracting file with: ['7z', 'x', '-bd', '-y', '-o/var/archivematica/storage_service/tmpSKdtm1', u'/var/archivematica/sharedDirectory/www/AIPsStore/88f4/d629/e062/4c13/8725/8c72/f19d/92ff/10-000-5mb-objects-88f4d629-e062-4c13-8725-8c72f19d92ff.7z'] to /var/archivematica/storage_service/tmpSKdtm1/10-000-5mb-objects-88f4d629-e062-4c13-8725-8c72f19d92ff

INFO      2020-05-05 06:47:35  locations.models.space:space:move_rsync:592:  rsync command: ['rsync', '-t', '-O', '--protect-args', '-vv', '--chmod=Fug+rw,o-rwx,Dug+rwx,o-rwx', '-r', '/home/centos/skeletons/objects/.', '/var/archivematica/storage_service/var/archivematica/sharedDirectory/tmp/tmpd8WibF/skeletons/.']

...
...

INFO      2020-05-05 06:50:10  locations.models.space:space:move_rsync:550:  Moving from /var/archivematica/storage_service/var/archivematica/sharedDirectory/tmp/tmpd8WibF/skeletons/./ to /var/archivematica/sharedDirectory/tmp/tmpd8WibF/skeletons/.

```

Both take a while! One partial-reingest took me 40 mins yesterday to initiate. But neither of my tests have blocked so far. So we will have to try other configurations I feel.

**Comment by ross-spencer** [comment]
Related: https://github.com/archivematica/Issues/issues/756

**Comment by ross-spencer** [comment]
I'm going to come back to this tomorrow and see if I can setup a `Pipeline Local Filesystem` type storage space between two of my instances.

**Comment by Rayzilt** [comment]
So after some more testing we noticed that the Storage Serivce is configured with "SS_GUNICORN_WORKER_CLASS=sync". Changing this option to the default "gevent" solved the issue.
