### ISSUE TITLE
Problem: SS GUI: Fixity Status tab sorts alphabetically, should sort by date

### ISSUE THREAD

**Issue by amayita** [archivematica/Issues#1196]
**Current behaviour**
Go to: https://storage.service.host:8000/packages/
Search the uuid of a package:
![image](https://user-images.githubusercontent.com/958745/81098247-675f5500-8f09-11ea-9e35-8d048db6dad2.png)
Click on Succes (Fixity Status column).
You get to: https://storage.service.host:8000//fixity/aip-uid/
![image](https://user-images.githubusercontent.com/958745/81098358-8f4eb880-8f09-11ea-831e-450ac67e3715.png)
The dates are sorted alphabetically. This makes no sense. They should be displayed by date.

**Your environment (version of Archivematica, operating system, other relevant details)**

Version: | 0.15.1

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged (if applicable)
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by replaceafill** [comment]
>They should be displayed by date.

@amayita @sromkey How should we sort the `Date` column by default? Oldest first or newest first?

**Comment by amayita** [comment]
I tend to think it's newest first all across the GUI, but I could be wrong
I'd be more interested , of course, in seeing the latest fixity runs, right?
/me gets excited that this will get fixed!

**Comment by jhsimpson** [comment]
I tested this, I see fixity checks listed in date order, newest first by default, and I can resort to oldest first if I want.  👍
