### ISSUE TITLE
Problem: Changes to Archival Storage tab will break AMAUAT tests

### ISSUE THREAD

**Issue by tw4l** [archivematica/Issues#1197]
**Expected behaviour**

AMAUAT tests should pass regardless of changes made to the Archival Storage tab user interface.

**Current behaviour**

Following changes made to the Archival Storage tab in PR https://github.com/artefactual/archivematica/pull/1602 (most notably, moving search results into a DataTable), the `mo-aip-reingest` AMAUAT tests fail with the following error message:

```
And the user waits for the AIP to appear in archival storage                                                                                                                    # features/steps/steps.py:256 24.616s
      Traceback (most recent call last):
        File "/usr/local/lib/python3.6/dist-packages/behave/model.py", line 1329, in run
          match.run(runner.context)
        File "/usr/local/lib/python3.6/dist-packages/behave/matchers.py", line 98, in run
          self.func(context, *args, **kwargs)
        File "features/steps/steps.py", line 258, in step_impl
          _appear_in_storage(context)
        File "features/steps/steps.py", line 252, in _appear_in_storage
          context.am_user.browser.wait_for_aip_in_archival_storage(uuid_val)
        File "/home/artefactual/acceptance-tests/amuser/am_browser_ability.py", line 101, in wait_for_aip_in_archival_storage
          summary_el = self.driver.find_element_by_css_selector("div.search-summary")
        File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 597, in find_element_by_css_selector
          return self.find_element(by=By.CSS_SELECTOR, value=css_selector)
        File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 966, in find_element
          'value': value})['value']
        File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 320, in execute
          self.error_handler.check_response(response)
        File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
          raise exception_class(message, screen, stacktrace)
      selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: div.search-summary
```
This failure is due to the fact that the div with class "search-summary" (formerly used for the Archival Storage search result table pager) no longer exists.

**Steps to reproduce**

In local Docker Compose dev environment:

* Checkout archivematica branch `dev/issue-1168-archival-storage-table` branch
* Checkout archivematica-acceptance-tests branch `stable/1.11.x`
* Run AMAUAT tests in Docker: `make test-at-behave TAGS=mo-aip-reingest BROWSER=Firefox`
* Check test results

**Your environment (version of Archivematica, operating system, other relevant details)**

Docker development environment. See details under "Steps to reproduce" immediately above to reproduce.

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged (if applicable)
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by tw4l** [comment]
The fix for this has been merged in commit https://github.com/artefactual-labs/archivematica-acceptance-tests/commit/d2a0b8d30d327ce692e22f86129d980dc44f26fc

**Comment by ross-spencer** [comment]
@tw4l you've reopend this but haven't left a note, is it failing again?

**Comment by tw4l** [comment]
Hi @ross-spencer , I re-opened it as I thought I noticed this was the only issue with the 1.12.0 milestone that was closed, and I thought I might have jumped a few steps by moving it from "Status: refining" directly to closed. Happy to keep it closed if that's not the case!

**Comment by ross-spencer** [comment]
oh @tw4l I didn't see it was tagged. That makes sense! I believe that's the right process. I was worried it might have cropped up again! 

Standing down! 
![](https://media2.giphy.com/media/4pMX5rJ4PYAEM/giphy.gif?cid=ecf05e476md4eonhf99zkjwd2wx392wb3wjz6api7r1dp19l&rid=giphy.gif)

**Comment by sromkey** [comment]
The AMAUATS ran on the 1.12 qa deploys so this must be working now!
