### ISSUE TITLE
Problem: Chrome browser and webdriver setup in Dockerfile no longer works correctly

### ISSUE THREAD

**Issue by tw4l** [archivematica/Issues#1199]
**Expected behaviour**

In my local Docker Compose Archivematica dev environment, I can successfully run AMAUAT tests in Chrome or Firefox.

**Current behaviour**

AMAUAT tests do not work with Chrome in newly setup Docker Compose development environments. Running `make test-at-build` then `make test-at-check` results in the following error message:

```
docker-compose -f docker-compose.yml -f docker-compose.acceptance-tests.yml  run --rm --no-deps archivematica-acceptance-tests /home/archivematica/acceptance-tests/simplebrowsertest.py
Starting tests...
Chrome... error! Message: session not created: This version of ChromeDriver only supports Chrome version 81
```

**Steps to reproduce**

In new Docker Compose dev environment (or after removing existing images/containers):

* Checkout branch `stable/1.11.x` of archivematica-acceptance-tests
* Run make commands:
    * `make test-at-build`
    * `make test-at-check`

**Your environment (version of Archivematica, operating system, other relevant details)**

Ubuntu 18.04, Docker Compose dev environment

**Related issues**

Relates to https://github.com/archivematica/Issues/issues/1198, which also currently causes `make test-at-check` to fail for a different reason. The Chrome issue persists even after fixing issue 1198.

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged (if applicable)
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by ross-spencer** [comment]
I built a newer version of the `amauat` container to test against and there's definitely a divergence at the moment:

_Very latest, which I suspect compares closely with yours Tim:_
```
user@artefactual:~/Artefactual/deploy-am$ sudo docker run -it test:amauat
To run a command as administrator (user "root"), use "sudo <command>".
See "man sudo_root" for details.

artefactual@9a0b49d74b22:~/acceptance-tests$ /usr/bin/chromedriver -v
ChromeDriver 81.0.4044.138 (8c6c7ba89cc9453625af54f11fd83179e23450fa-refs/branch-heads/4044@{#999})

artefactual@337ab4edf8b6:~/acceptance-tests$ google-chrome -version
Google Chrome 83.0.4103.44 beta
```

_The last container built which I run the tests successfully in_
```
user@artefactual:~/Artefactual/deploy-am$ sudo docker run -it compose_archivematica-acceptance-tests:latest
To run a command as administrator (user "root"), use "sudo <command>".
See "man sudo_root" for details.

artefactual@eb6170493a4b:~/acceptance-tests$ /usr/bin/chromedriver -v
ChromeDriver 80.0.3987.106 (f68069574609230cf9b635cd784cfb1bf81bb53a-refs/branch-heads/3987@{#882})

artefactual@eb6170493a4b:~/acceptance-tests$ google-chrome -version
Google Chrome 81.0.4044.83 beta
```

A solution might be, I guess, grabbing specific versions when the image is built? Or at least a better way to supply a version? If the discussion is about reducing barriers for other's running these, and experimenting with them, anyway...

**Comment by replaceafill** [comment]
The mismatch seems to be that [we're installing the **beta** version of the browser](https://github.com/artefactual-labs/archivematica-acceptance-tests/blob/8339c51ed0dd0c27c2c3bd5752c9651c2604cb1d/Dockerfile#L46) and then asking for `https://chromedriver.storage.googleapis.com/LATEST_RELEASE` which is supposed to give you the driver for the latest **stable** release. See the last paragraph of [Version selection page](https://sites.google.com/a/chromium.org/chromedriver/downloads/version-selection):

>In addition, the version of ChromeDriver for the current stable release of Chrome can be found at https://chromedriver.storage.googleapis.com/LATEST_RELEASE.

I think it's fine to keep relying on the `LATEST_RELEASE` url if we change `CHROME_VERSION` to `google-chrome-stable`.

> A solution might be, I guess, grabbing specific versions when the image is built? Or at least a better way to supply a version?

It's a bit cumbersome but since those values are `ARG` instructions in the `Dockerfile` you can override them at build time:

```
docker-compose -f docker-compose.yml -f docker-compose.acceptance-tests.yml build \
    --build-arg CHROME_DRIVER_VERSION="83.0.4103.39" \
    archivematica-acceptance-tests 
```

**Comment by tw4l** [comment]
Good catch @replaceafill ! I've submitted a PR which makes this change and updates Firefox/Geckodriver to pin them to the latest stable versions.

**Comment by replaceafill** [comment]
I've verified that the browser and driver versions are now pinned.
