### ISSUE TITLE
Problem: AMAUAT Dockerfile specifies old versions of Firefox and geckodriver

### ISSUE THREAD

**Issue by tw4l** [archivematica/Issues#1206]
**Expected behaviour**

The versions of Firefox and geckodriver are recent.

**Current behaviour**

The Dockerfile specifies `FIREFOX_VERSION=62.0.3` and `GECKODRIVER_VERSION=0.23.0` (as of time of writing, the most current stable releases are Firefox 75.0 and Geckodriver 0.26.0, respectively).

**Your environment (version of Archivematica, operating system, other relevant details)**

archivematica-acceptance-tests branch `qa/1.x`

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged (if applicable)
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by replaceafill** [comment]
Just verified the Firefox and Geckodriver versions have been updated.
