### ISSUE TITLE
Problem: storage service version has not been updated

### ISSUE THREAD

**Issue by scollazo** [archivematica/Issues#121]
**Expected behaviour**
Version (in Administration -> Version) should be 0.12.0

**Current behaviour**
Version shows 0.11.1

**Steps to reproduce**
Go to Administration -> Version in v0.12.0-rc1

**Your environment (version of Archivematica, OS version, etc)**
Archivematica v1.7.2-rc.3  and service storage v0.12.0-rc.1

**Comment by sevein** [comment]
We've confirmed that the version attribute is up to date in `v0.12.0-rc.1`:
https://github.com/artefactual/archivematica-storage-service/blob/v0.12.0-rc.1/storage_service/storage_service/__init__.py

@scollazo to revisit his test configs.

**Comment by kellyannewithane** [comment]
checked and it's up-to-date.  closing this issue
