### ISSUE TITLE
Problem: A user cannot see an AIP's storage location on the Archival Storage tab.

### ISSUE THREAD

**Issue by peterVG** [archivematica/Issues#1214]
**Please describe the problem you'd like to be solved**

A user viewing AIP information on the Archival Storage dashboard tab is not able to determine in which Storage Service location the AIP is being held.

**Describe the solution you'd like to see implemented**

**Feature**: A storage location column is made visible to an Archivematica user.

**Scenario**: An Archivematica user can select or deselect a storage location column on the Archival Storage dashboard tab.
**Given**: Archivematica has indexing turned on. 
**And**: A user has navigated to the Archival Storage tab. 
**When**: The user clicks on the column selector.
**Then**: A storage location column can be toggled either on or off.
**And**: The column visibility will be changed to on or off in the Archival Storage table. 
**And**: The value of the storage location will match the description or path as configured in the Storage Service.

![AM-wireframe-column-picker-Page-1](https://user-images.githubusercontent.com/672121/82847208-b01f8380-9ea1-11ea-8d6d-30acf9d4f9f5.png)
![AM-wireframe-column-picker-Page-2](https://user-images.githubusercontent.com/672121/82847220-c4fc1700-9ea1-11ea-80d3-a7000358874e.png)

**Additional context**

**Feature**: A storage service location is used in the archival storage column display 

**Scenario**: A user configures a storage service location without adding a description
**Given**: A space is available in the storage service.
**When**:  A user creates a storage service location.
**And**:   The user does not give the location a description.
**Then**:  The storage service API will return an absolute path to use as the value in the storage location column on the archival storage tab.

**Scenario**: A user configures a storage service location with a description
**Given**: A space is available in the storage service.
**When**:  A user creates a storage service location.
**And**:   The user gives the location a description.
**Then**:  The storage service API will return the storage service description to use as the value in the storage location column on the archival storage tab.

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged
- [ ] Details about this issue have been added to the release notes

**Comment by peterVG** [comment]
The new "Location" column can be successfully toggled on and off. 

However, one issue I am having on my QA server is that the Storage Service has a "var/archivematica/sharedDirectory/www/GPG_AIPsStore" storage space **enabled** but it is not showing up as an option under "Administration -> Available storage locations" or as an option on "Administration -> Processing configuration -> Edit -> Store AIP location". Therefore, I cannot change my AIP storage location ATM and test that the "Location" column does in fact display more than one storage location value correctly (e.g. where there happens to be a mix of storage locations used).

Secondly, a style issue. I noticed that the "Location" value used Archivematica Storage Service's default description for the default AIP storage, which is "Store AIP in standard Archivematica Directory". This is an action phrase, e.g. started with a verb, whereas the label "Location" insinuates that a noun should be used. Fortunately, this Location value can be edited by a user who sees this as a problem. I went to the Storage Service and changed the description value to "Standard Archivematica AIP storage directory". Any new transfers now use this label for their "Location" value. **However**, any previous transfers are still using the "Store AIP in standard Archivematica Directory" value in the "Location" column. Therefore, we have AIPs that are being stored in the same location but to the end-user this may not appear to be so after a Storage Service description label change. So the question is, should we be updating the Location value in the Elastic Search index after a Storage Service Location description value has been updated?

**Comment by sallain** [comment]
Toggling the location column on and off works like a charm, which closes this issue IMO.

@peterVG I'm certainly in favour of a more user friendly default storage location name, rather than "Store AIP in standard Archivematica Directory". That would presumably be a small change.

I can confirm the bug that you're seeing, where the Location value for existing AIPs is not updated if the name is changed.

![download.jpeg](https://codetreeusercontent.s3.amazonaws.com/uploads/89f01c84-05ca-410e-bc6a-b2f93b2a486a/download.jpeg)

I would file that as a separate bug or enhancement for this feature - it's not ideal, but the feature is technically working as expected. @sromkey thoughts?

**Comment by ross-spencer** [comment]
> I can confirm the bug that you're seeing, where the Location value for existing AIPs is not updated if the name is changed.

This would require updating the Elasticsearch index. We do have a management command for this which can be run separately. In the docs we might note that 1. on upgrade for all storage locations to be shown here, the Elasticsearch index needs to be refreshed. 2. Subsequently, if the location is updated, it would require the same script to be run as a workaround. A more dynamic solution would be lovely in the long-term.
