### ISSUE TITLE
Problem: Since Django 1.11 upgrade, many Dashboard tests fail in Docker Compose environment due to issue with staticfiles

### ISSUE THREAD

**Issue by tw4l** [archivematica/Issues#1218]
**Expected behaviour**

All Dashboard tests pass when run from Docker Compose development environment.

**Current behaviour**

Many Dashboard tests are failing with the following error message since the upgrade to Django 1.11:

`ValueError: Missing staticfiles manifest entry for 'images/favicon.ico'`

**Steps to reproduce**

* Checkout `qa/1.x` branch of Archivematica
* Run Dashboard tests (assuming Docker Compose dev environment): `make test-dashboard`

**Your environment (version of Archivematica, operating system, other relevant details)**

Docker Compose, `qa/1.x`

**Other notes**

This appears to be a known issue: https://docs.djangoproject.com/en/1.11/ref/contrib/staticfiles/#django.contrib.staticfiles.storage.ManifestStaticFilesStorage.manifest_strict

Note particularly: "Due to the requirement of running collectstatic, this storage typically shouldn’t be used when running tests as collectstatic isn’t run as part of the normal test setup. During testing, ensure that the STATICFILES_STORAGE setting is set to something else like 'django.contrib.staticfiles.storage.StaticFilesStorage' (the default)."

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged (if applicable)
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by replaceafill** [comment]
I'd consider this a variation of https://github.com/archivematica/Issues/issues/1140

[The `test` settings already disable Whitenoise](https://github.com/artefactual/archivematica/blob/6bcbf949405d64863197bf3c258a91d00dbbdbd3/src/dashboard/src/settings/test.py#L61-L64) but they're not used in the `make test-dashboard` call. Unfortunately, if you try to adapt the `make` command to use those settings then you get a different problem because they use a SQLite database which is not compatible with the docker environment :disappointed:

**Comment by tw4l** [comment]
Thanks @replaceafill. You're right, this is definitely related to https://github.com/archivematica/Issues/issues/1140. It makes sense to me to hold off on provisional solutions like this one (you're right that ideally this setting should be in `test`, not `local`, but the former didn't work for the reasons you poit out) in favor of fixing the larger issue.
