### ISSUE TITLE
Problem: GPG key import failure messages are different in Ubuntu and CentOS

### ISSUE THREAD

**Issue by replaceafill** [archivematica/Issues#1219]
**Expected behaviour**

When a passphrase protected GPG key is imported in the Storage Service the error message should always be:

```
Import failed. The GPG key provided requires a passphrase. GPG keys with passphrases cannot be imported
```

**Current behaviour**

In Ubuntu you get the expected message, but in CentOS you get:

```
Import failed. Sorry, we were unable to create a key with the supplied ASCII armor
```

The problem seems to be [we're relying on console output](https://github.com/artefactual/archivematica-storage-service/blob/605b6a7104ea640b80a92dc194d751ce415070f1/storage_service/common/gpgutils.py#L190) to determine if the key has a passphrase and that output is different between both systems.

Notice the `decrypt status` part of the output in Ubuntu includes the expected `need passphrase` string:

```
INFO      2020-05-27 17:57:46  common.gpgutils:gpgutils:encryption_works:183:  Checking decryption with key A1839A09DC72AA9D9127454DFA1B1E66E5DEDE22
INFO      2020-05-27 17:57:46  common.gpgutils:gpgutils:encryption_works:184:  decrypt ok: False
INFO      2020-05-27 17:57:46  common.gpgutils:gpgutils:encryption_works:185:  decrypt status: need passphrase
```

but it doesn't in CentOS (`decryption failed`):

```
INFO      2020-05-27 08:57:18  common.gpgutils:gpgutils:encryption_works:183:  Checking decryption with key A1839A09DC72AA9D9127454DFA1B1E66E5DEDE22
INFO      2020-05-27 08:57:18  common.gpgutils:gpgutils:encryption_works:184:  decrypt ok: False
INFO      2020-05-27 08:57:18  common.gpgutils:gpgutils:encryption_works:185:  decrypt status: decryption failed
```

**Steps to reproduce**

1. Import this [passphrase protected key](https://raw.githubusercontent.com/artefactual-labs/archivematica-acceptance-tests/8339c51ed0dd0c27c2c3bd5752c9651c2604cb1d/etc/gpgkeys/bbingo-passphrased.key) from the AMAUATs
2. Ubuntu will display the expected error and CentOS will not

**Your environment (version of Archivematica, operating system, other relevant details)**

This is currently breaking the Jenkins `matrix-qa` where [the `aip-encryption.feature` passes on Ubuntu but fails consistently on CentOs](https://github.com/artefactual-labs/archivematica-acceptance-tests/blob/d2a0b8d30d327ce692e22f86129d980dc44f26fc/features/steps/aip_encryption_steps.py#L466-L469). It was also confirmed in `am111centos` and `am111bionic`.

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged (if applicable)
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by mamedin** [comment]
We are using GnuPG version 1 in Ubuntu and version 2 on CentOS:

Ubuntu:

```
artefactual@am111bionic:~$ gpg1 --version
gpg (GnuPG) 1.4.22
``` 

CentOS/RH:

```
[root@am111centos ~]# gpg --version
gpg (GnuPG) 2.0.22
libgcrypt 1.5.3
```

**Comment by sevein** [comment]
Thanks @mamedin, you were right. @replaceafill pointed out that https://github.com/artefactual/archivematica-storage-service/commit/75fb6a378e77b15a98364f99467941d4649bedb1 could be also a fix for this issue and I've just confirmed that both aip-encrypt and aip-encrypt-mirror acceptance tests are passing.

**Comment by replaceafill** [comment]
I confirmed the message is the same across both versions now: `Import failed. The GPG key provided requires a passphrase. GPG keys with passphrases cannot be imported`.
