### ISSUE TITLE
Problem: name used to refer to API allowlist could be offensive

### ISSUE THREAD

**Issue by sevein** [archivematica/Issues#1226]
**Expected behaviour**
Archivematica should move away from terminology that could be considered offensive or non-inclusive. Particularly, we should replace the use of "whitelist" in our API settings with "allowlist" or "clearlist". Other projects have done this before, see https://git.io/JfPFs.

**Current behaviour**
Use of term "whitelist".

**Your environment (version of Archivematica, operating system, other relevant details)**
qa/1.x, 1.11 and older

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged (if applicable)
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by ablwr** [comment]
+1 to this

**Comment by sromkey** [comment]
[Another link](https://www.zdnet.com/article/uk-ncsc-to-stop-using-whitelist-and-blacklist-due-to-racial-stereotyping/) to show consistency with other industries (cyber security in this case).

Allow/deny seems to be a clear set of terminology.
