### ISSUE TITLE
Problem: cannot clear ingests/transfers in stable/1.11.x

### ISSUE THREAD

**Issue by sromkey** [archivematica/Issues#1227]
**Expected behaviour**
Clicking the red "remove" icon should remove a single transfer or ingest, and clicking 
the top remove icon should remove all that are no longer in progress

**Current behaviour**
Nothing happens.

**Your environment (version of Archivematica, operating system, other relevant details)**
stable/1.11.x commit db6de7ee868f20c6e2c7ce3ffa3a00d70116d571

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged (if applicable)
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by sromkey** [comment]
Possibly connect to #1221 ?

Note I tested on 1.11.1 and it works as expected there.

**Comment by ross-spencer** [comment]
@sromkey good call on the CSRF warning. We do in fact see it when trying to perform that action. From the `archivematica-dashboard` log:

```
archivematica-dashboard_1        | WARNING   2020-06-04 11:28:19  django.security.csrf:csrf:_reject:160:  Forbidden (CSRF token missing or incorrect.): /transfer/aa672c12-55d6-4ed7-b11a-b928c3091883/delete/
```

**Comment by sallain** [comment]
Tested on 1.11.2 on Centos and this is now resolved.
