### ISSUE TITLE
Problem: Sorting on new Backlog and Archival Storage columns doesn't work in upgraded Archivematica 1.12 instances unless ES mappings are updated or indices rebuilt during upgrade

### ISSUE THREAD

**Issue by tw4l** [archivematica/Issues#1228]
**Expected behaviour**

After upgrading an Archivematica 1.11 instance to Archivematica 1.12 (or, currently, the `qa/1.x` branch), I am able to sort correctly on all values in the Archival Storage and Backlog tables.

**Current behaviour**

Unless the mappings for the Elasticsearch indices are updated via [Put Mapping](https://www.elastic.co/guide/en/elasticsearch/reference/6.8/indices-put-mapping.html) or deleting and rebuilding the indices, sorting won't work in upgraded Archivematica 1.12 instances on the following columns that are introduced in Archivematica 1.12:

*Backlog* (see issue https://github.com/archivematica/Issues/issues/1167)

* Transfer view ("show files" not checked): Size, Accession number
* File view ("show files" checked): Status

*Archival Storage* (see issue https://github.com/archivematica/Issues/issues/1168)

* AIP view ("show files" not checked): Accession numbers, Status, File count
* File view ("show files" checked): File, Accession number, Status

In upgraded instances, sorting may also be affected by the fact that packages indexed prior to Archivematica 1.12 will not have data populated for the new fields.

In new Archivematica 1.12 instances, there are no sorting issues, as the ES mappings will already be up-to-date.

**In order to avoid these issues in Archivematica instances that were upgraded from versions prior to 1.12, it is necessary to update the ES mappings.**

There are two potential paths for doing so:

1) Update the ES mappings using Put Mapping using the management task introduced in PR https://github.com/artefactual/archivematica/pull/1617. This will upgrade the mappings so that sorting will work in the new columns for packages that have those fields populated (i.e. all new packages moving forward).

If taking the this approach, two details are important:

* The Put Mapping updates must take place *before* any new transfers or AIPs are ingested. This is because Put Mapping cannot be used to change the type of a string field from "text" to "keyword", and if mappings are not explicitly set, Elasticsearch will use the "text" type for new string fields.
* Put Mapping will create the appropriate keyword fields in the Elasticsearch index that enable sorting on column headers in the Archival Storage field. It will not, however, populate those fields for packages indexed prior to Archivematica 1.12. For this reason, if one wants to have the Backlog and/or Archival Storage tables fully populated and for sorting to work as one would naively expect, deleting and recreating the indices as detailed in option 2 is the better approach.

2) Delete and rebuild the ES indices for transfers and AIPs.

Use the `rebuild_transfer_backlog` and one of the tasks for rebuilding the AIP index (either from files or from the Storage Service) with the `--delete-all` flag to delete the current indices and rebuild them. This will use the new Archivematica 1.12 ES mappings and fully populate all of the fields in the tables for all packages.

There may be cases where this is not feasible, due to current limitations with the ES rebuilding tasks (e.g. https://github.com/archivematica/Issues/issues/701). In such cases, it's advised to use the Put Mapping technique instead of trying to rebuild the indices.

If transfers and/or AIPs are stored in encrypted storage locations, they can be reindexed using the ability to reindex packages from the Storage Service introduced in PR https://github.com/artefactual/archivematica/pull/1624.

**Steps to reproduce**

* Set up an Archivematica 1.11 instance
* Ingest some AIPs
* Upgrade codebase to current `qa/1.x` and ingest some AIPs
* Try to sort on the fields mentioned above.

**Your environment (version of Archivematica, operating system, other relevant details)**

`qa/1.x` / Archivematica 1.12

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged (if applicable)
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by ross-spencer** [comment]
Related to https://github.com/archivematica/Issues/issues/701

**Comment by tw4l** [comment]
Related to https://github.com/archivematica/Issues/issues/1214, which adds `location` as an additional field in the `aips` index and as a column in the Archival Storage tab

**Comment by tw4l** [comment]
@ross-spencer Do you want to look at this and see if we should add `location` to the ES mapping upgrade command for the AM 1.12 release? IIRC, I think you set the location mapping explicitly as a keyword field, in which case it may not be necessary, but it'll be good to make sure.

**Comment by ross-spencer** [comment]
@tw4l I had a brief look before the meeting earlier but it looks like I will need to put this in my backlog until next week. If you can share any specifics about your tests/recreating this in Docker if there is anything more than the above in how to recreate this then that will be a big help. Otherwise right now, I haven't an instinct about whether there is an impact here with the location change or not. Thx.

**Comment by tw4l** [comment]
@ross-spencer No worries, it can wait, and I can help verify next week.

My instinct is that there won't be an impact. The issue arose for some other fields because they had existed as string fields in the ES indices already and were populated with data, but because their mappings weren't set explicitly in `elasticSearchFunctions.py`, ES was using a `text` type rather than `keyword` and thus they couldn't be used for sorting. Since this is a new field with an explicit mapping, I think we should be in the clear.

The testing process to make sure is basically:
- Spin up an AM 1.11 instance
- Ingest some AIPs
- Upgrade to 1.12 (at this point the Location field should be visible in Archival Storage but not populated and not sortable)
- Ingest some more AIPs
- Check to make sure that sorting on Location is working as expected for the AIPs that have that field populated

**Comment by ross-spencer** [comment]
Thanks @tw4l I'll revisit in the new week as well. Refreshed hopefully a bit better placed to test this.

**Comment by tw4l** [comment]
@ross I had a moment to test while waiting on something else, and it looks like on the upgrade path where deleting and rebuilding the indices isn't an option, new data added in Location doesn't sort in AM 1.12, even after running the `update_elasticsearch_mappings` task during the upgrade process and then ingesting a new AIP in AM 1.12. Looking at my ES index, it looks like Location was set to a "text" type in the `aips` index, which is ES 6's default for text fields when an explicit mapping isn't provided:

![image](https://user-images.githubusercontent.com/6758804/89575441-c4fe8880-d7fb-11ea-8bce-39fccaa02710.png)

After running `rebuild_aip_index_from_storage_service --delete-all`, the mappings are set correctly:

![image](https://user-images.githubusercontent.com/6758804/89575952-861d0280-d7fc-11ea-97fb-3be49411fef1.png)

To fix this on the reindex-less upgrade path, I think we just need to add a line in [update_elasticsearch_mappings](https://github.com/artefactual/archivematica/blob/qa/1.x/src/dashboard/src/main/management/commands/update_elasticsearch_mappings.py#L47-L57) explicitly adding the keyword mapping for `location` in the `aips` index, as we have for the other new fields.

**Comment by ross** [comment]
> @ross 

I believe you want @ross-spencer :wave:

**Comment by tw4l** [comment]
@ross-spencer tagging the right person this time :sweat_smile:

**Comment by ross-spencer** [comment]
@tw4l thnks so much for looking at this. I'll need to get an update in. I'll see what I can do. I might need to touch base about testing Monday.

**Comment by ross-spencer** [comment]
This work should now be completed and ready for testing via https://github.com/artefactual/archivematica/commit/07ac5e754bd30b760bea3a33558ff8d02c7d264b
