### ISSUE TITLE
Problem: Cannot view callbacks in storage service post Django upgrade (qa/0.x)

### ISSUE THREAD

**Issue by ross-spencer** [archivematica/Issues#1232]
**Expected behaviour**

Storage service pages render as expected. 

**Current behaviour**

We're seeing an error when trying to view the storage service callbacks page. 
```
archivematica-storage-service_1  | WARNING   2020-06-08 06:56:44  django.template:loader_tags:render:232:  Exception raised while rendering {% include %} for template 'locations/callback_list.html'. Empty string rendered instead.
archivematica-storage-service_1  | Traceback (most recent call last):
archivematica-storage-service_1  |   File "/usr/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 216, in render
archivematica-storage-service_1  |     return template.render(context)
archivematica-storage-service_1  |   File "/usr/local/lib/python2.7/site-packages/django/template/base.py", line 209, in render
archivematica-storage-service_1  |     return self._render(context)
archivematica-storage-service_1  |   File "/usr/local/lib/python2.7/site-packages/django/template/base.py", line 199, in _render
archivematica-storage-service_1  |     return self.nodelist.render(context)
archivematica-storage-service_1  |   File "/usr/local/lib/python2.7/site-packages/django/template/base.py", line 990, in render
archivematica-storage-service_1  |     bit = node.render_annotated(context)
archivematica-storage-service_1  |   File "/usr/local/lib/python2.7/site-packages/django/template/base.py", line 957, in render_annotated
archivematica-storage-service_1  |     return self.render(context)
archivematica-storage-service_1  |   File "/usr/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 216, in render
archivematica-storage-service_1  |     nodelist.append(node.render_annotated(context))
archivematica-storage-service_1  |   File "/usr/local/lib/python2.7/site-packages/django/template/base.py", line 957, in render_annotated
archivematica-storage-service_1  |     return self.render(context)
archivematica-storage-service_1  |   File "/usr/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 458, in render
archivematica-storage-service_1  |     url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
archivematica-storage-service_1  |   File "/usr/local/lib/python2.7/site-packages/django/urls/base.py", line 91, in reverse
archivematica-storage-service_1  |     return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
archivematica-storage-service_1  |   File "/usr/local/lib/python2.7/site-packages/django/urls/resolvers.py", line 497, in _reverse_with_prefix
archivematica-storage-service_1  |     raise NoReverseMatch(msg)
archivematica-storage-service_1  | NoReverseMatch: Reverse for 'callback_edit' not found. 'callback_edit' is not a valid view function or pattern name.
```

**Steps to reproduce**

Monitor the logs while clicking on the service callbacks link in the storage service Administration tab.

Alternatively try creating a callback, then navigating back to this table and ask yourself _"where is my callback"_ when it doesn't appear. 

![Talking heads - Once in a lifetime](https://media3.giphy.com/media/iGlJoFMz4A4Mg/giphy.gif?cid=ecf05e4753474f5277b3e2153083b90f2483f6a0381929ef&rid=giphy.gif)

**Your environment (version of Archivematica, operating system, other relevant details)**

Currrent `qa/0.x` branch, so commit `605b6a7104ea640b80a92dc194d751ce415070f1`. 

**Fix**

Various URLs inthe [callback table](https://github.com/artefactual/archivematica-storage-service/blob/605b6a7104ea640b80a92dc194d751ce415070f1/storage_service/templates/snippets/callbacks_table.html#L23) need to be prefixed with the location namespace. So:

```
        <td>
          <a href="{% url 'locations:callback_edit' callback.uuid %}">
            {% trans "Edit" %}
          </a> |
          <a href="{% url 'locations:callback_switch_enabled' callback.uuid %}?next={{ request.path }}">
            {{ callback.enabled|yesno:_("Disable,Enable") }}</a> |
          <a href="{% url 'locations:callback_delete' callback.uuid %}?next={{ request.path }}">
            {% trans "Delete" %}
          </a>
        </td>
```

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged (if applicable)
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by replaceafill** [comment]
Sorry for the inconvenience @ross-spencer :facepalm: While we're at it, I just found the [`profile.html`](https://github.com/artefactual/archivematica/blob/8adc2bdabcd244710c005dfe96e6293526e49966/src/dashboard/src/templates/accounts/profile.html) template has a similar problem.

**Comment by ross-spencer** [comment]
This was looking good to me recently @replaceafill does it need the `review` label?

**Comment by replaceafill** [comment]
@ross-spencer Into review? Not sure if I'm missing something but I still:

1. don't see the `locations` namespace in the [`url` calls in the template in `qa/0.x`](https://github.com/artefactual/archivematica-storage-service/blob/2ae1a672ee39141581df058848a9cf14015684ca/storage_service/templates/snippets/callbacks_table.html#L23)
2. don't see the callbacks table after adding one
3. see the error you originally reported in the description

Did I miss a PR or commit?

**Comment by ross-spencer** [comment]
@replaceafill my mistake? Was a fix only added to `1.10`? Was it fixed at all anywhere?

**Comment by ross-spencer** [comment]
@replaceafill nvm. I must have been using my workaround.

**Comment by mamedin** [comment]
The PR have been tested successfully in  customer.
