### ISSUE TITLE
Problem: Cannot delete the JISC "automated" processing configuration

### ISSUE THREAD

**Issue by peterVG** [archivematica/Issues#1234]
**Version of the documentation**
1.11

**Page (and section, if applicable) where the issue occurs**
https://www.archivematica.org/en/docs/archivematica-1.11/user-manual/administer/dashboard-admin/#dashboard-processing

**Description of the issue**
It currently reads "Automated, which is used for transfers automatically started from Jisc RDSS environments (if you are not a Jisc user, **feel free to delete this configuration**)."

However, in AM 1.11 you only have the option to Edit, Download, or Reset the default and automated processing configurations. You can't delete the automated configuration.

**Suggested fix**
Change the documentation to read "Automated, which is used for transfers automatically started from Jisc RDSS environments (if you are not a Jisc user, feel free to **ignore** this configuration).

Alternatively, we introduce the ability to actually delete the automated processing configuration.

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by sromkey** [comment]
Closed with https://github.com/artefactual/archivematica-docs/pull/437
