### ISSUE TITLE
Problem: amflow outputs &nbsp; in SVG

### ISSUE THREAD

**Issue by ross-spencer** [archivematica/Issues#1237]
**Expected behaviour**

`amflow` escapes XML correctly. 

**Current behaviour**

A minor issue I think is just appearing in Chrome now, is that some XML is being escaped using HTML entities. I believe [&nbsp;](https://github.com/artefactual-labs/amflow/blob/76a687a0e648121ec1c7eb9fbf8ef04db1741a9a/internal/graph/dotviz.go#L109) here, I believe should be `"&#160;"`.

**Steps to reproduce**

This only happens when you follow the less than canonical approach of exporting the SVG via the embedded element in the browser and then re-open in Chrome standalone. 

![image](https://user-images.githubusercontent.com/1880412/84909318-882bd600-b083-11ea-95cb-9c292016876d.png)

E.g. 
```xml
<g id="a_node7"><a xlink:title="Args: &quot;%SIPDirectory%&quot; &quot;%sharedPath%watchedDirectories/workFlowDecisions/examineContentsChoice/.&quot; &nbsp;&quot;%SIPUUID%&quot; &quot;%sharedPath%&quot;">
```

The workaround is to follow the [documented approach](https://github.com/artefactual-labs/amflow#export-capabilities): 

`amflow export --full --format=dot | dot -v -Tsvg 2>/dev/null > ~/graph.svg` 

Which is just a little slower. 

**Your environment (version of Archivematica, operating system, other relevant details)**

`amflow` current commit https://github.com/artefactual-labs/amflow/commit/76a687a0e648121ec1c7eb9fbf8ef04db1741a9a 

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged (if applicable)
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by sromkey** [comment]
@ross-spencer assigning you just in case there are some more details you can include to reproduce this.
