### ISSUE TITLE
Unable to edit DSpace REST Space settings in SS

### ISSUE THREAD

**Issue by J4bbi** [archivematica/Issues#124]
**Expected behaviour**
Having created a DSpace REST location and successfully supplied necessary parameters it should be possible to change them/review later.

**Current behaviour**
The HTML isn't displayed correctly, after the "Staging path:" it's just HTML. This is identical to the issue in https://github.com/artefactual/archivematica-storage-service/issues/352

**Steps to reproduce**
Create a DSpace REST space and try to edit.

**Your environment (version of Archivematica, OS version, etc)**
SS qa 0.x 0.12.0 rc

**Comment by jrwdunham** [comment]
This should be fixed by the merger of https://github.com/artefactual/archivematica-storage-service/pull/406.

**Comment by jrwdunham** [comment]
To QA: First create a DSpace REST space. Then attempt to edit it. If the "Edit Space" form looks normal (i.e., has no literal HTML strings in it), then the issue should be considered resolved.

**Comment by currmie** [comment]
Verified - edit space form looks normal
