### ISSUE TITLE
Problem: The hash for the base image for the MCP client docker file is incorrect

### ISSUE THREAD

**Issue by ross-spencer** [archivematica/Issues#1242]
**Expected behaviour**

With a clear local docker registry I should be able to install Archivematica 1.10 or 1.9 using Docker.

**Current behaviour**

We currently see this failure:
```
Step 1/19 : FROM artefactual/archivematica-mcp-client-base:20190227.01.9a3872e0
ERROR: Service 'archivematica-mcp-client' failed to build: manifest for artefactual/archivematica-mcp-client-base:20190227.01.9a3872e0 not found: manifest unknown: manifest unknown
```

**Steps to reproduce**

Starting with a clean slate. As an example I believe this happened to me after running a clean up script which I do every so often.
```bash
#!/usr/bin/env bash
set -eux

sudo docker rm $(sudo docker ps -a -f status=exited -q)
sudo docker rmi $(sudo docker images -f dangling=true -q)
sudo docker volume rm $(sudo docker volume ls -f dangling=true -q)
sudo docker system prune -a
```
Try to follow the docker [installation instructions](https://github.com/artefactual-labs/am/tree/master/compose) for Archivematica. You should get the same error. 

**Your environment (version of Archivematica, operating system, other relevant details)**

AM 1.10 and 1.9 from the am.git environment. 

**More information**

The base image listed in the docker file is: `FROM artefactual/archivematica-mcp-client-base:20190227.01.9a3872e0`

Consulting [docker-hub](https://hub.docker.com/layers/artefactual/archivematica-mcp-client-base/20190227.01.aa8ec61a/images/sha256-3b11537cb3c2b818401ebf76335631442c83c98bf96491be70a225b3defbee7c?context=explore
) we need: `FROM artefactual/archivematica-mcp-client-base:20190227.01.aa8ec61a`

The line reference for AM 1.10 is [here](https://github.com/artefactual/archivematica/blob/603abeed18d28c6d3516e2808e35e8d8199993f3/src/MCPClient.Dockerfile#L1). If anyone needs to run an older version of Archivematica via docker then they may need to replace that line with `FROM artefactual/archivematica-mcp-client-base:20190227.01.aa8ec61a` as per above. 

_**NB.** I raised the question internally and it is believed that this just wasn't spotted previously during development as we may all have been using cached images. It's not clear why external developers wouldn't have noticed it. It was noted that we don't believe there to be an issue in docker-hub._

**Further notes**

There are no references in Git for the current hash. There are two references for `9a3872e0`. The image prior seems to have been `0461aae`.

```
ross-spencer@artefactual:~/git/artefactual-labs/am/src/archivematica/src$ git log -S aa8ec61a
ross-spencer@artefactual:~/git/artefactual-labs/am/src/archivematica/src$ git log -S 9a3872e0
commit fe01b9d2db880cff0a4418ef1f5f9338aaedfe12
Author: Miguel Angel Medinilla <mamedin@gmail.com>
Date:   Mon Feb 24 21:58:23 2020 +0100

    MCPClient: use new base Docker image (#1559)

commit cfc8aab94884b341917ee653885a05b1f31f47ae
Author: Jesús García Crespo <jesus@sevein.com>
Date:   Wed Feb 27 11:45:27 2019 -0800

    MCPClient: use new base Docker image
```

```diff
ross-spencer@artefactual:~/git/artefactual-labs/am/src/archivematica/src$ git diff cfc8aa MCPClient.Dockerfile
diff --git a/src/MCPClient.Dockerfile b/src/MCPClient.Dockerfile
index 4e833e7e..decbb2ad 100644
--- a/src/MCPClient.Dockerfile
+++ b/src/MCPClient.Dockerfile
@@ -1,4 +1,4 @@
-FROM artefactual/archivematica-mcp-client-base:20190227.01.9a3872e0
+FROM artefactual/archivematica-mcp-client-base:20200210.01.0461aae
 
 ENV DJANGO_SETTINGS_MODULE settings.common
 ENV PYTHONPATH /src/MCPClient/lib/:/src/archivematicaCommon/lib/:/src/dashboard/src/
```

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged (if applicable)
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by replaceafill** [comment]
Closing this since the [old Compose development environment](https://github.com/artefactual-labs/am) where this image was used is not maintained anymore.
