### ISSUE TITLE
Problem: "Rebuild the index" section of docs needs updating following changes to reindexing scripts

### ISSUE THREAD

**Issue by tw4l** [archivematica/Issues#1254]
**Version of the documentation**

Archivematica 1.12

**Page (and section, if applicable) where the issue occurs**

https://www.archivematica.org/en/docs/archivematica-1.11/admin-manual/maintenance/maintenance/#rebuild-the-indexes

**Description of the issue**

PR https://github.com/artefactual/archivematica/pull/1624 introduces several changes to the Django management tasks for rebuilding the Elasticsearch indices:

- `rebuild_transfer_backlog` has a new flag `--from-storage-service`, which uses the Storage Service API to determine which stored transfers need to be reindexed, and then reindexes by temporarily downloading those transfers from from the Storage Service.
- A new task `rebuild_aip_index_from_storage_service` has been added, which also uses the Storage Service API to determine which stored AIPs and AICs need to be reindexed (based on status and origin pipeline), and then reindexes those AIPs and AICs from temporarily downloaded copies of the AIP (and, as appropriate, AIC) METS files.

Collectively, these changes enable reindexing of transfers and AIPs/AICs stored in encrypted and (some) remote storage locations.

**Suggested fix**

Update the documentation to reflect that indices can be rebuilt by walking a local unencrypted location, or by interaction with the Storage Service. Document the new and modified tasks, including their arguments.

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by peterVG** [comment]
See https://github.com/artefactual/archivematica/commit/443fc2e66a101a0160951f06fa2f3a01717c9ce0

**Comment by peterVG** [comment]
<img width="902" alt="Screen Shot 2020-07-17 at 11 41 19 AM" src="https://user-images.githubusercontent.com/672121/87820173-75dbbe00-c822-11ea-8016-97db1ecb4509.png">

sudo -u archivematica bash -c " \
    set -a -e -x
    source /etc/default/archivematica-dashboard || \
        source /etc/sysconfig/archivematica-dashboard \
            || (echo 'Environment file not found'; exit 1)
    cd /usr/share/archivematica/dashboard
    /usr/share/archivematica/virtualenvs/archivematica-dashboard/bin/python \
        manage.py rebuild_transfer_backlog --from-storage-service --no-prompt
";

sudo -u archivematica bash -c " \
    set -a -e -x
    source /etc/default/archivematica-dashboard || \
        source /etc/sysconfig/archivematica-dashboard \
            || (echo 'Environment file not found'; exit 1)
    cd /usr/share/archivematica/dashboard
    /usr/share/archivematica/virtualenvs/archivematica-dashboard/bin/python \
        manage.py rebuild_aip_index_from_storage_service --delete-all
";

**Comment by sallain** [comment]
@peterVG @tw4l are the two docs PRs linked above sufficient to close this issue?

**Comment by tw4l** [comment]
@sallain I think so, yes!
