### ISSUE TITLE
Problem: Archivematica 1.12 Upgrading documentation needs to include section on how to update Elasticsearch indices

### ISSUE THREAD

**Issue by tw4l** [archivematica/Issues#1257]
**Version of the documentation**

1.12

**Page (and section, if applicable) where the issue occurs**

https://www.archivematica.org/en/docs/archivematica-1.12/admin-manual/installation-setup/upgrading/upgrading/

**Description of the issue**

As described in https://github.com/archivematica/Issues/issues/1228, upgrading from Archivematica 1.11 or earlier to Archivematica 1.12 requires updating the Elasticsearch mappings or deleting and rebuilding the Elasticsearch indices for the Backlog and Archival Storage tabs to work perfectly.

Otherwise, if one performs the upgrade to Archivematica 1.12 but doesn't do anything to the Elasticsearch indices, sorting on some columns in the Backlog and Archival Storage page tables won't work, and some data will appear "missing" for packages ingested prior to Archivematica 1.12.

**Suggested fix**

Add a language to the upgrading documentation that explains why this is necessary, how to choose between the two available options (just updating the ES mappings, or deleting and rebuilding the indices), and how to implement them.

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by tw4l** [comment]
The issue description in https://github.com/archivematica/Issues/issues/1228 might be useful in part here, but the documentation should likely be more succinct and include specific commands to run.

**Comment by sallain** [comment]
@sevein @tw4l I looked around a bit, but I'm not sure - did this result in a docs PR?

**Comment by tw4l** [comment]
@sallain No, I don't believe there has been a docs PR yet for the upgrading instructions. Depending on the outcome of https://github.com/archivematica/Issues/issues/1282 (i.e., if that results in an additional command to be run during the upgrade), we may want to address this all at once.

**Comment by sallain** [comment]
@tw4l it looks like artefactual/archivematica-docs#387 resolves this; is there anything else left to do here?

**Comment by tw4l** [comment]
@sallain With that PR merged, this issue can be closed.
