### ISSUE TITLE
Problem: DSpace_REST AIP store should be beta

### ISSUE THREAD

**Issue by sromkey** [archivematica/Issues#126]
**Expected behaviour**

The DSpace_REST space won't be supported until the 0.13 release but is currently merged into qa/0.x . It should be commented out until it's release-ready.

**Current behaviour**

DSpace_REST is available as a Space option in the SS.

**Comment by jrwdunham** [comment]
The merger of 403 should resolve this issue. DSpace REST is now hidden in the GUI in qa/0.x. A user could create a DSpace REST space via the API but I think it's ok to ignore that possibility for now.
