### ISSUE TITLE
Problem: Reindexing a single AIP with reindex_aips_from_storage_service task doesn't work

### ISSUE THREAD

**Issue by tw4l** [archivematica/Issues#1263]
**Expected behaviour**

Running `manage.py index_aips_from_storage_service` with the `-u/--uuid` option to specify a particular package will reindex that one package.

**Current behaviour**

Indexing fails due to two bugs:
* An `AttributeError` is thrown on line  because it was trying to get a property from a list on line https://github.com/artefactual/archivematica/blob/b2b7f3b623336ade66f9669ea399ffdbdfd15118/src/dashboard/src/main/management/commands/rebuild_aip_index_from_storage_service.py#L137, rather than from the first item in that list.
* Line https://github.com/artefactual/archivematica/blob/b2b7f3b623336ade66f9669ea399ffdbdfd15118/src/dashboard/src/main/management/commands/rebuild_aip_index_from_storage_service.py#L141 incrrectly expects `process_package` to return a tuple rather than a boolean.

**Steps to reproduce**

* Process some AIPs.
* Try to reindex one with `manage.py index_aips_from_storage_service --uuid UUID`
* Watch it fail

**Your environment (version of Archivematica, operating system, other relevant details)**

`qa/1.x`

**Additional context**

Related to https://github.com/archivematica/Issues/issues/734

Bug introduced in PR https://github.com/artefactual/archivematica/pull/1624

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [x] All pull requests related to this issue are properly linked
- [x] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged (if applicable)
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by tw4l** [comment]
Fixed in https://github.com/artefactual/archivematica/pull/1628

**Comment by ross-spencer** [comment]
This looks good. I have a handful of AIPs all stored in my default storage location.

![image](https://user-images.githubusercontent.com/1880412/91586818-ebf43a00-e923-11ea-95ca-4cee2cf8863d.png)

I want to change the name of my storage location, but only update the search index for one AIP.

If I run the command but only one UUID:
```
~/git/artefactual-labs/am/compose$ sudo make manage-dashboard ARG='rebuild_aip_index_from_storage_service --uuid=57f346f4-cdec-49ea-be0c-583f79588c87'
docker-compose run \
	--rm \
	--entrypoint /src/dashboard/src/manage.py \
		archivematica-dashboard \
			rebuild_aip_index_from_storage_service --uuid=57f346f4-cdec-49ea-be0c-583f79588c87
Starting compose_elasticsearch_1 ... done
Starting compose_mysql_1         ... done
Starting compose_redis_1         ... done
Starting compose_gearmand_1      ... done
Starting compose_archivematica-storage-service_1 ... done
/usr/local/lib/python2.7/site-packages/cryptography/__init__.py:39: CryptographyDeprecationWarning: Python 2 is no longer supported by the Python core team. Support for it is now deprecated in cryptography, and will be removed in a future release.
  CryptographyDeprecationWarning,
Rebuilding 'aips' and 'aipfiles' indices
Removed FITS output from METS.
AIP UUID: 57f346f4-cdec-49ea-be0c-583f79588c87
Indexing AIP files ...
Files indexed: 10
Indexing AIP ...
Done.
Successfully indexed package 57f346f4-cdec-49ea-be0c-583f79588c87
Cleaning up
Indexing complete. Successfully indexed 1 AIP/AIC.
```
I now have one AIP in my index, and it's the one I requested. You can tell it has been updated by the change in storage location retrieved from the search index. 

![image](https://user-images.githubusercontent.com/1880412/91586951-1a721500-e924-11ea-8c2c-92b7b0956959.png)

I notice the command name has changed from `index_aips_from_storage_service` to `rebuild_aip_index_from_storage_service`

So before moving this to complete, let's just check the docs, which I'll do right now...

**Comment by ross-spencer** [comment]
References to rebuild_aip_index... all seem fine [here](https://github.com/artefactual/archivematica-docs/blob/04fcf364cfe309a2e68ea8ab5ed729168261e7cb/admin-manual/maintenance/maintenance.rst).

**Comment by ross-spencer** [comment]
Same test as above for Bionic. And also without the duplication seen in the screenshot above. 

**Command and output**
```
root@am112bionic:~# sudo -u archivematica bash -c " \
    set -a -e -x
    source /etc/default/archivematica-dashboard || \
        source /etc/sysconfig/archivematica-dashboard \
            || (echo 'Environment file not found'; exit 1)
    cd /opt/archivematica/archivematica/src/dashboard/src/
    /usr/share/archivematica/virtualenvs/archivematica-dashboard/bin/python manage.py rebuild_aip_index_from_storage_service --delete --uuid=7c2c7234-3049-4110-8cce-aad48fa769fb";
+ source /etc/default/archivematica-dashboard
++ PYTHONPATH=/usr/lib/archivematica/archivematicaCommon:/usr/share/archivematica/dashboard
++ LANG=en_US.UTF-8
++ LC_ALL=en_US.UTF-8
++ LC_LANG=en_US.UTF-8
++ DJANGO_SETTINGS_MODULE=settings.production
++ ARCHIVEMATICA_DASHBOARD_DASHBOARD_DJANGO_ALLOWED_HOSTS='*'
++ ARCHIVEMATICA_DASHBOARD_DASHBOARD_DJANGO_SECRET_KEY=CHANGE_ME_WITH_A_SECRET_KEY
++ AM_GUNICORN_BIND=127.0.0.1:8002
++ ARCHIVEMATICA_DASHBOARD_DASHBOARD_ELASTICSEARCH_SERVER=127.0.0.1:9200
++ ARCHIVEMATICA_DASHBOARD_DASHBOARD_STORAGE_SERVICE_CLIENT_QUICK_TIMEOUT=20
++ ARCHIVEMATICA_DASHBOARD_DASHBOARD_ELASTICSEARCH_TIMEOUT=30
++ ARCHIVEMATICA_DASHBOARD_DASHBOARD_TIME_ZONE=America/Toronto
++ ARCHIVEMATICA_DASHBOARD_SEARCH_ENABLED=yes
++ ARCHIVEMATICA_DASHBOARD_CLIENT_HOST=localhost
++ ARCHIVEMATICA_DASHBOARD_CLIENT_DATABASE=MCP
++ ARCHIVEMATICA_DASHBOARD_CLIENT_USER=archivematica
++ ARCHIVEMATICA_DASHBOARD_CLIENT_PASSWORD=am110x
++ REQUESTS_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt
+ cd /opt/archivematica/archivematica/src/dashboard/src/
+ /usr/share/archivematica/virtualenvs/archivematica-dashboard/bin/python manage.py rebuild_aip_index_from_storage_service --delete --uuid=7c2c7234-3049-4110-8cce-aad48fa769fb
/usr/share/archivematica/virtualenvs/archivematica-dashboard/lib/python2.7/site-packages/cryptography/__init__.py:39: CryptographyDeprecationWarning: Python 2 is no longer supported by the Python core team. Support for it is now deprecated in cryptography, and will be removed in a future release.
  CryptographyDeprecationWarning,
Rebuilding 'aips' and 'aipfiles' indices
Deleting package 7c2c7234-3049-4110-8cce-aad48fa769fb from 'aips' and 'aipfiles' indices.
Removed FITS output from METS.
AIP UUID: 7c2c7234-3049-4110-8cce-aad48fa769fb
Indexing AIP files ...
Files indexed: 11
Indexing AIP ...
Done.
Successfully indexed package 7c2c7234-3049-4110-8cce-aad48fa769fb
Cleaning up
Indexing complete. Successfully indexed 1 AIP/AIC.
```

**Before**

_Initially: Standard Archivematica Directory_

![image](https://user-images.githubusercontent.com/1880412/91592444-93756a80-e92c-11ea-8bee-0d9bde8da22b.png)

**After**

_Now: Standard Archivematica Directory (Reindex test)_

![image](https://user-images.githubusercontent.com/1880412/91592482-a25c1d00-e92c-11ea-954b-8da5f423763b.png)

Looking good!
