### ISSUE TITLE
Creating an AIC fails at "Job: Store this AIP" if replication is enabled in Storage Service

### ISSUE THREAD

**Issue by tw4l** [archivematica/Issues#1264]
**Expected behaviour**

Creating an AIC succeeds.

**Current behaviour**

If a Replicator location is enabled in the Storage Service for the AIP Store location, creating an AIC fails at the "Store this AIP" job. Here's the stderr as presented in the Archivematica dashboard:

```
500 Server Error: INTERNAL SERVER ERROR for url: http://archivematica-storage-service:8000/api/v2/file/Traceback (most recent call last):
  File "/src/MCPClient/lib/job.py", line 111, in JobContext
    yield
  File "/src/MCPClient/lib/clientScripts/store_aip.py", line 365, in call
    args.sip_type,
  File "/src/MCPClient/lib/clientScripts/store_aip.py", line 244, in store_aip
    related_package_uuid,
  File "/src/MCPClient/lib/clientScripts/store_aip.py", line 80, in _create_file
    agents=get_agents_from_db(uuid),
  File "/src/archivematicaCommon/lib/storageService.py", line 359, in create_file
    response.raise_for_status()
  File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
HTTPError: 500 Server Error: INTERNAL SERVER ERROR for url: http://archivematica-storage-service:8000/api/v2/file/
```

And the traceback from the Storage Service logs:

```
archivematica-storage-service_1  | ERROR     2020-07-13 13:46:33  django.request.tastypie:resources:_handle_500:321:  Internal Server Error: /api/v2/file/
archivematica-storage-service_1  | Traceback (most recent call last):
archivematica-storage-service_1  |   File "/usr/local/lib/python2.7/site-packages/tastypie/resources.py", line 227, in wrapper
archivematica-storage-service_1  |     response = callback(request, *args, **kwargs)
archivematica-storage-service_1  |   File "/usr/local/lib/python2.7/site-packages/tastypie/resources.py", line 467, in dispatch_list
archivematica-storage-service_1  |     return self.dispatch('list', request, **kwargs)
archivematica-storage-service_1  |   File "/usr/local/lib/python2.7/site-packages/tastypie/resources.py", line 499, in dispatch
archivematica-storage-service_1  |     response = method(request, **kwargs)
archivematica-storage-service_1  |   File "/usr/local/lib/python2.7/site-packages/tastypie/resources.py", line 1408, in post_list
archivematica-storage-service_1  |     updated_bundle = self.obj_create(bundle, **self.remove_api_resource_names(kwargs))
archivematica-storage-service_1  |   File "/src/storage_service/locations/api/resources.py", line 1062, in obj_create
archivematica-storage-service_1  |     self._store_bundle(bundle)
archivematica-storage-service_1  |   File "/src/storage_service/locations/api/resources.py", line 997, in _store_bundle
archivematica-storage-service_1  |     aip_subtype=aip_subtype,
archivematica-storage-service_1  |   File "/src/storage_service/locations/models/package.py", line 825, in store_aip
archivematica-storage-service_1  |     self.create_replicas()
archivematica-storage-service_1  |   File "/src/storage_service/locations/models/package.py", line 1475, in create_replicas
archivematica-storage-service_1  |     self.replicate(replicator_loc)
archivematica-storage-service_1  |   File "/src/storage_service/locations/models/package.py", line 647, in replicate
archivematica-storage-service_1  |     master_premis_object = master_ptr_aip_fsentry.get_premis_objects()[0]
archivematica-storage-service_1  | AttributeError: 'NoneType' object has no attribute 'get_premis_objects'
```

An AIC is created and can be downloaded (and re-indexed) from the Storage Storage, but it is the Ingest is marked as failed in Archivematica and is not indexed/present in the Archival Storage tab.

**Steps to reproduce**

* Set up an instance of Archivematica
* Set up a Replication location for the default AIPs Store location
* Ingest some AIPs
* Create an AIC from the Archival Storage tab and, when prompted, store it in the default AIPs Store location
* Watch it fail

**Your environment (version of Archivematica, operating system, other relevant details)**

I first noticed this behaviour in `qa/1.x`. I've confirmed the bug also exists in Archivematica 1.11.2. I haven't looked at older versions than 1.11 or tried to determine when the bug was introduced.

**Additional context**

Related to https://github.com/archivematica/Issues/issues/685

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged (if applicable)
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by tw4l** [comment]
On investigation, this appears to be a bug with how `metsrw` parses file UUIDs from FILEID attributes. For AIPs, [metsrw knows to strip the AIP name, with an optional `"file-"` prefix, from the FILEID to get the file UUID](https://github.com/artefactual-labs/mets-reader-writer/blob/master/metsrw/mets.py#L450). However, it's currently not doing the same for AICs, which have a different `entry_type` ("Archival Information Collection", as opposed to "Archival Information Package").

This in turn prevents [retrieving the AIC FSEntry based on UUID](https://github.com/artefactual/archivematica-storage-service/blob/63f74d3314e29bd34d2844567047ecd248a5471c/storage_service/locations/models/package.py#L646), which prevents the replication of the AIC and results in the error in the issue description.

In my local environment, patching the `metsrw` line noted above to something like `if entry_type.lower() in ("archival information package", "archival information collection"):` resolves the issue and allows for successful storage and replication of AICs.

As far as I can tell, this bug has existed since 2017, when the [AIP handling code noted above](8f76174950fe95f1d4ad0425387c63c6e4f0a0e1) was added.

A user on the Google group forum seems to have run into this same issue, or at least a very similar one: https://groups.google.com/g/archivematica/c/v47PwUyK_PQ. It might be a good idea to follow up on that to confirm whether or not that issue is also related to AICs specifically.

**Comment by sromkey** [comment]
I created a replicator space and stored an AIC without error, closing this.
