### ISSUE TITLE
Problem: METS schema validation fails after new redirect in loc.gov URL

### ISSUE THREAD

**Issue by replaceafill** [archivematica/Issues#1266]
**Expected behaviour**

METS schema validation works independently of network conditions of the AM server.

**Current behaviour**

Since July 9, 2020 our [Travis CI has been failing three METS validation related tests](https://travis-ci.org/github/artefactual/archivematica/jobs/706640560) in the `MCPClient/tests/test_create_aip_mets.py` module with the message:

```
XMLSchemaParseError: Element '{http://www.w3.org/2001/XMLSchema}attributeGroup', attribute 'ref': The QName value '{http://www.w3.org/1999/xlink}simpleLink' does not resolve to a(n) attribute group definition., line 760
```

This can also be reproduced locally by running `tox` and [it seems to be related to recent changes in the `loc.gov` infrastructure](https://github.com/mets/METS-schema/issues/3#issuecomment-658864361), specifically the redirect of the `http://www.loc.gov/standards/xlink/xlink.xsd` URL to https.

We've found similar errors being reported in:

* https://github.com/sul-dlss/argo/issues/2180
* https://github.com/mets/METS-schema/issues/3

Parts of AM where this problem has shown are:

* [Importing structural metadata with mets_structmap.xml](https://www.archivematica.org/en/docs/archivematica-1.11/user-manual/transfer/import-metadata/#structmap-xml)

We've faced a similar situation in https://github.com/artefactual/archivematica/issues/1050 which adjusted the pointer file creation logic in the Storage Service:

```
                # It has been observed that this function can fail validating,
                # for example against the Library of Congress' (LoC) XSD for
                # METS if the LoC server is down it will fail. We don't want
                # this to happen so if the pointer file xml is not valid at
                # this point in time we need to rely on a different mechanism
                # to manage that.
```

**Steps to reproduce**

As of July 16, 2020 the problem can be reproduced with `tox` in the AM repository and `Travis CI` or by starting a `SampleTransfers/StructMapTransferSamples/MinimalStructMapExample` transfer which will fail in the `Verify transfer compliance -> Verify mets_structmap.xml compliance` job with:

```
Element '{http://www.w3.org/2001/XMLSchema}attributeGroup', attribute 'ref': The QName value '{http://www.w3.org/1999/xlink}simpleLink' does not resolve to a(n) attribute group definition., line 760Traceback (most recent call last):
  File "/opt/archivematica/archivematica/src/MCPClient/lib/job.py", line 111, in JobContext
    yield
  File "/opt/archivematica/archivematica/src/MCPClient/lib/clientScripts/verify_mets.py", line 34, in call
    xmlschema = etree.XMLSchema(etree.parse(mets_xsd))
  File "src/lxml/xmlschema.pxi", line 87, in lxml.etree.XMLSchema.__init__ (src/lxml/lxml.etree.c:204467)
XMLSchemaParseError: Element '{http://www.w3.org/2001/XMLSchema}attributeGroup', attribute 'ref': The QName value '{http://www.w3.org/1999/xlink}simpleLink' does not resolve to a(n) attribute group definition., line 760
```

**Your environment (version of Archivematica, operating system, other relevant details)**

docker compose https://github.com/artefactual-labs/am/commit/6031e67f8ffad3fc353198bb2ec527a13277426c and verified in `am111bionic`.

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged (if applicable)
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by ross-spencer** [comment]
A little more to compliment the LoC/METS-schema issue above: 

* :beetle:  [From twitter](https://twitter.com/gmcharlt/status/1283783678708113409)
* :bug:  [Links to GNOME's XMLlint Bugzilla](https://bugzilla.gnome.org/show_bug.cgi?id=791220)

**Comment by ross-spencer** [comment]
LoC have temporarily eased our woes, you can try this again with a custom structmap @replaceafill and I think it will work for you: https://github.com/mets/METS-schema/issues/3#issuecomment-659569020

**Comment by replaceafill** [comment]
Thanks @ross-spencer. Confirmed, the `Verify transfer compliance -> Verify mets_structmap.xml compliance` job succeeds now on `am111bionic`:

```
Custom structmap validated correctly
```

`tox` and Travis CI build also pass now.

**Comment by ross-spencer** [comment]
Update from the METS folk and my response: https://github.com/mets/METS-schema/issues/3#issuecomment-769910476
