### ISSUE TITLE
Problem: Cannot create a SIP from a Bag Transfer in the Appraisal tab

### ISSUE THREAD

**Issue by dcraze** [archivematica/Issues#1267]
**Expected behaviour**
Start an UnzippedBag transfer and send it to backlog. Add the transfer to the Arrangement pane in the Appraisal tab.  Select the folder in the Arrangement pane and click Create SIP; a SIP is created on the Ingest tab.

**Current behaviour**
When clicking Create SIP you get an error message "SIP could not be started! Check dashboard logs." and no SIP is created on the Ingest tab.

**Your environment (version of Archivematica, operating system, other relevant details)**
Ubuntu 18.04, 1.11.2

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged (if applicable)
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by sallain** [comment]
Just a note that this issue occurs for unzipped and zipped bag transfers, but not zipped directory transfers.

**Comment by sromkey** [comment]
I've tested during 1.12 release testing and this seems to work fine now.
