### ISSUE TITLE
Status doesn't revert appropriately to "Stored" for packages and their files in AM after deletion requests are rejected in Storage Service

### ISSUE THREAD

**Issue by tw4l** [archivematica/Issues#1273]
**Expected behaviour**

If I submit a deletion request for a package and that deletion request is subsequently rejected by an administrator in the Storage Service, the status for the transfer and its files should revert back to "Stored" (with the appropriate changes made in the Elasticsearch indices).

**Current behaviour**

If I submit a deletion request for a transfer in the Backlog tab and that deletion request is subsequently rejected by an administrator in the Storage Service, the status for the package and files in the Backlog remains "Deletion requested".

If I submit a deletion request for an AIP in the Archival Storage tab and that deletion request is subsequently rejected by an administrator in the Storage Service, the status for the package is reverted to "Stored" as expected, but the status of the related files remains "Deletion requested".

**Steps to reproduce**

* Create some packages
* Request deletions
* Reject those deletion requests from the Storage Service
* Look at package and file status in the Backlog and Archival Storage tabs

**Your environment (version of Archivematica, operating system, other relevant details)**

`qa/1.x`

**Additional context**

Relates to https://github.com/archivematica/Issues/issues/1189, about keeping package status in sync between Elasticsearch and the Storage Service. The case described in this issue was previously missed in the implementation, which was merged into `qa/1.x` via https://github.com/artefactual/archivematica/pull/1611.

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged (if applicable)
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by ross-spencer** [comment]
Tangentially related to: https://github.com/archivematica/Issues/issues/716
