### ISSUE TITLE
Problem: The Archivematica generated transfer directory fileMeta isn't documented

### ISSUE THREAD

**Issue by ross-spencer** [archivematica/Issues#1275]
**Version of the documentation**

* [1.11](https://www.archivematica.org/en/docs/archivematica-1.11/search/?q=filemeta)

**Description of the issue**

Trying to find information about the `fileMeta` folder yield's no results. It is created in the transfer logs folder before it is added to the backlog. You can see it in the directory structure in this issue: https://github.com/archivematica/Issues/issues/1113

And in the transfer METS it gets its own PREMIS object because it is there (along with a PREMIS object for submission docs):
```xml
  <mets:dmdSec ID="dmdSec_22" CREATED="2020-08-04T18:20:53" STATUS="original">
    <mets:mdWrap MDTYPE="PREMIS:OBJECT">
      <mets:xmlData>
        <premis:object xmlns:premis="http://www.loc.gov/premis/v3" xsi:schemaLocation="http://www.loc.gov/premis/v3 http://www.loc.gov/standards/premis/v3/premis.xsd" xsi:type="premis:intellectualEntity" version="3.0">
          <premis:objectIdentifier>
            <premis:objectIdentifierType>UUID</premis:objectIdentifierType>
            <premis:objectIdentifierValue>3e5b2ab7-eea2-4e50-ab31-8c10e542a8c9</premis:objectIdentifierValue>
          </premis:objectIdentifier>
          <premis:originalName>%transferDirectory%metadata/submissionDocumentation/</premis:originalName>
        </premis:object>
      </mets:xmlData>
    </mets:mdWrap>
  </mets:dmdSec>
  <mets:dmdSec ID="dmdSec_23" CREATED="2020-08-04T18:20:53" STATUS="original">
    <mets:mdWrap MDTYPE="PREMIS:OBJECT">
      <mets:xmlData>
        <premis:object xmlns:premis="http://www.loc.gov/premis/v3" xsi:schemaLocation="http://www.loc.gov/premis/v3 http://www.loc.gov/standards/premis/v3/premis.xsd" xsi:type="premis:intellectualEntity" version="3.0">
          <premis:objectIdentifier>
            <premis:objectIdentifierType>UUID</premis:objectIdentifierType>
            <premis:objectIdentifierValue>d45889ec-0242-4f97-8386-cee6a56783db</premis:objectIdentifierValue>
          </premis:objectIdentifier>
          <premis:originalName>%transferDirectory%logs/fileMeta/</premis:originalName>
        </premis:object>
      </mets:xmlData>
    </mets:mdWrap>
  </mets:dmdSec>
```

**Suggested fix**

1. Related to https://github.com/archivematica/Issues/issues/251 verify its purpose and use and make sure it isn't old Archivematica structure that can now be removed. (It doesn't persist into the AIP). 
2. If it's needed, we can document it. If not, we will need to fix-up the code to remove it. 

**Related**

* FITS has previously been one of the Microservices using this directory: https://github.com/archivematica/Issues/issues/77 (I believe there's a normalization microservice recorded using it in workflow.json as well) 

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by sromkey** [comment]
This is the first I've ever been aware of the fileMeta directory, I don't think it's supposed to be there! @evelynPM @sallain , just pinging you for extra eyes in case I'm mistaken.

**Comment by sromkey** [comment]
This mysterious directory doesn't seem to be around anymore? Closing this issue!

**Comment by sallain** [comment]
@sromkey I got a notification about this because I was mentioned in 2020 :joy: - and out of curiosity, I went looking. And I do see the fileMeta directory, but ONLY in the transfer METS (located at `my-transfer/data/objects/transfer-my-transfer/METS.xml`). Searching in the file, I get two hits for fileMeta. One is a dmdSec:

```
  <mets:dmdSec ID="dmdSec_39" CREATED="2024-05-22T17:44:32" STATUS="original">
    <mets:mdWrap MDTYPE="PREMIS:OBJECT">
      <mets:xmlData>
        <premis:object xmlns:premis="http://www.loc.gov/premis/v3" xmlns:fits="http://hul.harvard.edu/ois/xml/ns/fits/fits_output" xmlns:MediaInfo="https://mediaarea.net/mediainfo" xsi:schemaLocation="http://www.loc.gov/premis/v3 http://www.loc.gov/standards/premis/v3/premis.xsd" version="3.0" xsi:type="premis:intellectualEntity">
          <premis:objectIdentifier>
            <premis:objectIdentifierType>UUID</premis:objectIdentifierType>
            <premis:objectIdentifierValue>9a20a896-6116-4168-b3dc-fc65c8aa22b1</premis:objectIdentifierValue>
          </premis:objectIdentifier>
          <premis:originalName>%transferDirectory%logs/fileMeta/</premis:originalName>
        </premis:object>
      </mets:xmlData>
    </mets:mdWrap>
  </mets:dmdSec>
```

The other is in the structmap, as you'd expect anything with a dmdSec to be (some extraneous stuff removed for clarity:

```
  <mets:structMap TYPE="logical" ID="structMap_2" LABEL="Normative Directory Structure">
    <mets:div TYPE="Directory" LABEL="my-transfer-a0bd54bf-2a53-427c-b17a-467f9a07cc00">
      <mets:div TYPE="Directory" LABEL="logs" ADMID="amdSec_534">
        ...
        <mets:div TYPE="Directory" LABEL="fileMeta" DMDID="dmdSec_39"/>
      </mets:div>
      ...
      </mets:div>
    </mets:div>
  </mets:structMap>
```

However, it's no longer present in the final AIP METS. Presumably it's some sort of transitory directory, located within the logs directory, that is then removed. Honestly doesn't seem like too big of a deal, but interesting nonetheless!
