### ISSUE TITLE
Problem: Django migrations for 1.12 release haven't been created yet

### ISSUE THREAD

**Issue by tw4l** [archivematica/Issues#1278]
**Expected behaviour**

Migrations have been created as needed for the Archivematica 1.12 release.

**Current behaviour**

A few changes have been made to the models in `qa/1.x` / `qa/0.x` that require migrations which haven't been created yet.

Running `manage.py makemigrations --dry-run --verbosity 3` for the Dashboard in my Docker development environment on branch `qa/1.x`, I see:

```
➜ docker-compose run \
                --rm \
                --entrypoint /src/dashboard/src/manage.py archivematica-dashboard makemigrations --dry-run  --verbosity 3
Starting compose_mysql_1         ... done
Starting compose_elasticsearch_1 ... done
Starting compose_redis_1         ... done
Starting compose_gearmand_1                      ... done
Starting compose_archivematica-storage-service_1 ... done
/usr/local/lib/python2.7/site-packages/cryptography/__init__.py:39: CryptographyDeprecationWarning: Python 2 is no longer supported by the Python core team. Support for it is now deprecated in cryptography, and will be removed in a future release.
  CryptographyDeprecationWarning,
Migrations for 'main':
  src/dashboard/src/main/migrations/0077_auto_20200810_2149.py
    - Alter field event_id on event
    - Alter field microservicechainlink on job
    - Alter field file_uuid on siparrange
    - Alter field transfer_uuid on siparrange
    - Alter field microservicechainlink on unitvariable
```

_Full migrations file '0077_auto_20200810_2149.py':_

```python
# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-10 21:49
from __future__ import unicode_literals
from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):
    dependencies = [("main", "0076_version_number")]
    operations = [
        migrations.AlterField(
            model_name="event",
            name="event_id",
            field=django_extensions.db.fields.UUIDField(
                auto=False, db_column=b"eventIdentifierUUID", null=True, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="microservicechainlink",
            field=django_extensions.db.fields.UUIDField(
                auto=False, blank=True, db_column=b"MicroServiceChainLinksPK", null=True
            ),
        ),
        migrations.AlterField(
            model_name="siparrange",
            name="file_uuid",
            field=django_extensions.db.fields.UUIDField(
                auto=False, blank=True, default=None, null=True, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="siparrange",
            name="transfer_uuid",
            field=django_extensions.db.fields.UUIDField(
                auto=False, blank=True, default=None, null=True
            ),
        ),
        migrations.AlterField(
            model_name="unitvariable",
            name="microservicechainlink",
            field=django_extensions.db.fields.UUIDField(
                auto=False, blank=True, db_column=b"microServiceChainLink", null=True
            ),
        ),
    ]
```

```
Migrations for 'auth':
  usr/local/lib/python2.7/site-packages/django/contrib/auth/migrations/0009_auto_20200810_2149.py
    - Alter field username on user
```

_Full migrations file '0009_auto_20200810_2149.py':_

```python
# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-10 21:49
from __future__ import unicode_literals
import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("auth", "0008_alter_user_username_max_length")]
    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                error_messages={"unique": "A user with that username already exists."},
                help_text="Required, 255 characters or fewer. Only letters, numbers, and @, ., +, -, or _ characters.",
                max_length=255,
                unique=True,
                validators=[django.contrib.auth.validators.ASCIIUsernameValidator()],
                verbose_name="username",
            ),
        )
    ]
```

The migrations for `main` seem to be a result of changes to `workflow.json` made in commit https://github.com/artefactual/archivematica/commit/c75092435aa742f89926f281386bfda86de2f6f5.

The migration for `auth` seems like it could stem from the upgrade from Django 1.8 to Django 1.11. I see [mention of the `ASCIIUsernameValidator` in the Django 1.10 release notes](https://docs.djangoproject.com/en/1.11/releases/1.10/#official-support-for-unicode-usernames)

The latter migration is also required for the Storage Service:

```
➜ docker-compose run \
                --rm \
                --entrypoint /src/storage_service/manage.py \
                        archivematica-storage-service makemigrations --dry-run --verbosity 3
Starting compose_mysql_1 ... done
/usr/local/lib/python2.7/site-packages/cryptography/__init__.py:39: CryptographyDeprecationWarning: Python 2 is no longer supported by the Python core team. Support for it is now deprecated in cryptography, and will be removed in a future release.
  CryptographyDeprecationWarning,
DEBUG     2020-08-10 17:40:55  locations.models.async_manager:async_manager:_watchdog_loop:123:  Watchdog sees 0 tasks running
Migrations for 'auth':
  /usr/local/lib/python2.7/site-packages/django/contrib/auth/migrations/0009_auto_20200810_1740.py
    - Alter field username on user
```

_Full migrations file '0009_auto_20200810_1740.py':_

```python
# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-11 00:40
from __future__ import unicode_literals

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("auth", "0008_alter_user_username_max_length")]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                error_messages={"unique": "A user with that username already exists."},
                help_text="Required, 255 characters or fewer. Only letters, numbers, and @, ., +, -, or _ characters.",
                max_length=255,
                unique=True,
                validators=[django.contrib.auth.validators.ASCIIUsernameValidator()],
                verbose_name="username",
            ),
        )
    ]
```

**Steps to reproduce**

* Build containers from latest `qa/1.x` (Archivematica) and `qa/0.x` (Storage Service)
* Run `manage.py makemigrations --dry-run --verbosity 3` in Dashboard and Storage Service respectively (see examples above for examples of how to run these in Docker Compose dev environment) to see changes that require migrations

**Your environment (version of Archivematica, operating system, other relevant details)**

* `qa/1.x` (Archivematica) as of commit https://github.com/artefactual/archivematica/commit/f5f6a2d02a4ed730d553b27aff55e03e2ec24cad
* `qa/0.x` (Storage Service) as of commit https://github.com/artefactual/archivematica-storage-service/commit/9349b7cb83260bfeafe139f7e16a7413e54c61ba

**Additional context**

Related to issue https://github.com/archivematica/Issues/issues/1243, which is causing a warning to display when attempting to migrate the database after running `manage.py makemigrations`.

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged (if applicable)
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by sevein** [comment]
I'm planning to commit the migration on `UUIDField` fields, we missed that!

The migrations touching `user.username` in both AM and SS are trickier. I don't know enough about Django to tell what's exactly happening but I think the problem is in that we extended the length of the field to 255 characters via the [`longerusername`](https://github.com/seatme/django-longer-username) app. But whenn we upgraded from 1.8 to 1.11, Django touched the length again here: [0008_alter_user_username_max_length](https://github.com/django/django/blob/stable/1.11.x/django/contrib/auth/migrations/0008_alter_user_username_max_length.py), increasing it to 150 characters. I suspect we have a few solutions here:
1. Remove longerusername, which prevents the migration issue and it result in length of 150 characters for new Archivematica users and 255 for existing users,
2. Transition to a custom user model (big overhaul)
3. Fork longerusername? I'm not entirely sure how we would achieve it, but there must be a way from that extension to re-conciliate with Django's contrib.auth 0008 migration.

You may be wondering how we could prevent this from happening again. SS has a `checkmigrations` CI task but it isn't perfect. It detects unstaged changes in the git working tree, but it did not see changes in site-packages (django.contrib.auth). It'd be nice to find a better way to do this, but also Django 3.1 just made this functionality part of the framework, see https://docs.djangoproject.com/en/3.1/ref/django-admin/#cmdoption-migrate-check.
AM does not have a `checkmigrations`, I can try to add it if I have time.

**Comment by sevein** [comment]
@replaceafill :ping_pong: ^ what are your thoughts about the longerusername issue?

**Comment by jraddaoui** [comment]
@sevein, maybe we can add a custom migration before the one that changes the user names to report possible issues. I'm not sure if we want user interaction in the migration process, but maybe we could add a check that stops the process if it will need to change usernames, requiring the user to do it manually and re-run the upgrade. I'm not sure how this migrations are executed when installing from packages, for example, so I'm not sure if something along this lines could be an option.

**Comment by sevein** [comment]
That's a good idea. I'll give it a try!

**Comment by sevein** [comment]
@jraddaoui, here's my attempt finally: https://github.com/artefactual/archivematica/pull/1646. The goal of the migration is to throw an error, forcing the user to deal with the situation. The migration module has a docstring with more details, I was thinking that could be linked from the release notes.

For QA:
1. Change max. length with `ALTER TABLE auth_user MODIFY COLUMN `username` varchar(250);` (this brings you to the schema that we expect to see in Archivematica users coming from Archivematica v1.11 where we used to have `longerusername` installed), and
2. Set an username with more than 150 characters, e.g.: `UPDATE auth_user SET username = "..."`, and
3. Run migrations with `make manage-dashboard ARG="migrate"`, it should fail!

Now you can either fake the migration (`make manage-dashboard ARG="migrate main 0078 --fake"`) or trim the fields affected.

**Comment by sevein** [comment]
Added a new section to our release notes mentioning this new migration: https://wiki.archivematica.org/index.php?title=Archivematica_1.12.0_and_Storage_Service_0.17.0_release_notes&action=historysubmit&diff=13519&oldid=13518.
