### ISSUE TITLE
Problem: Setting Administrator entitlements from CAS user attributes doesn't work for the Storage Service

### ISSUE THREAD

**Issue by tw4l** [archivematica/Issues#1289]
**Expected behaviour**

When Storage Service settings `SS_CAS_AUTHENTICATION`, `AUTH_CAS_CHECK_ADMIN_ATTRIBUTES`, `AUTH_CAS_ADMIN_ATTRIBUTE`, and `AUTH_CAS_ADMIN_ATTRIBUTE_VALUE` are set properly, a user's Administrator status should be set automatically from the value of a particular CAS user attribute (e.g. membership in a particular group on the CAS server).

**Current behaviour**

This entitlement check-and-set routine isn't working, so users are never set as Administrators. This appears to be due to a regression introduced during code review for https://github.com/artefactual/archivematica-storage-service/pull/538, which moved the `cas_user_authenticated` Django signal receiver from the `locations` app to the `storage_service` app (see the PR description for more detail), where it no longer appears to be getting called.

I'm afraid the blame for not catching this earlier sits with me, as it looks like I did not re-deploy the QA VM with the updated code between submitting the pull request and post-code review internal QA.

**Steps to reproduce**

* Configure the Storage Service against a CAS server that releases user attributes when used with the CAS 3.0 protocol.
* Sign in as a user that should have administrator entitlements.
* Verify that user is not an admin.

**Your environment (version of Archivematica, operating system, other relevant details)**

`qa/0.x` as of commit https://github.com/artefactual/archivematica-storage-service/commit/aa1a7c7c79897b232fa1cec36f9a9222e621347d

**Additional context**

Connected to #1211 

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged (if applicable)
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by tw4l** [comment]
@sevein We could move the signal receiver back to the `locations` app but I'm wondering if you have insight into why the receiver isn't working from `storage_service`.

**Comment by sevein** [comment]
Hi @tw4l! Maybe because `storage_service` isn't an actual app that we list in INSTALLED_APPS.

**Comment by tw4l** [comment]
Hm, thanks @sevein ! It previously also wasn't working from the `administration` app, which is in `INSTALLED_APPS`. I'll take a closer look this evening or tomorrow AM after getting a bit of closure on the other release-related issue I'm working on.

**Comment by sromkey** [comment]
QA'd in client environment.
