### ISSUE TITLE
Problem: Attempting to edit an FPR command results in an Internal Server Error

### ISSUE THREAD

**Issue by tw4l** [archivematica/Issues#1295]
**Expected behaviour**

Editing an FPR command succeeds.

**Current behaviour**

Attempting to edit an FPR command results in an Internal Server Error message and the following error in the Dashboard logs:

```
/var/log/archivematica/dashboard/dashboard.debug.log:6674:ERROR     2020-08-27 18:07:46  django.request:exception:handle_uncaught_exception:135:  Internal Server Error: /fpr/fpcommand/41112047-7ddf-4bf0-9156-39fe96b32d53/edit/
/var/log/archivematica/dashboard/dashboard.debug.log-6675-Traceback (most recent call last):
/var/log/archivematica/dashboard/dashboard.debug.log-6676-  File "/usr/share/archivematica/virtualenvs/archivematica-dashboard/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
/var/log/archivematica/dashboard/dashboard.debug.log-6677-    response = get_response(request)
/var/log/archivematica/dashboard/dashboard.debug.log-6678-  File "/usr/share/archivematica/virtualenvs/archivematica-dashboard/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
/var/log/archivematica/dashboard/dashboard.debug.log-6679-    response = self.process_exception_by_middleware(e, request)
/var/log/archivematica/dashboard/dashboard.debug.log-6680-  File "/usr/share/archivematica/virtualenvs/archivematica-dashboard/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
/var/log/archivematica/dashboard/dashboard.debug.log-6681-    response = wrapped_callback(request, *callback_args, **callback_kwargs)
/var/log/archivematica/dashboard/dashboard.debug.log-6682-  File "/usr/share/archivematica/virtualenvs/archivematica-dashboard/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
/var/log/archivematica/dashboard/dashboard.debug.log-6683-    return view_func(request, *args, **kwargs)
/var/log/archivematica/dashboard/dashboard.debug.log-6684-  File "/opt/archivematica/archivematica/src/dashboard/src/fpr/views.py", line 654, in fpcommand_edit
/var/log/archivematica/dashboard/dashboard.debug.log-6685-    fprmodels.FPCommand, "uuid", replaces, new_fpcommand
/var/log/archivematica/dashboard/dashboard.debug.log-6686-  File "/opt/archivematica/archivematica/src/dashboard/src/fpr/utils.py", line 38, in update_references_to_object
/var/log/archivematica/dashboard/dashboard.debug.log-6687-    for model in models.get_models():
/var/log/archivematica/dashboard/dashboard.debug.log-6688-AttributeError: 'module' object has no attribute 'get_models'
```

When I go back to the same command from the Preservation Planning tab it appears to have changed, but the changes don't seem to take effect.

I attempted to edit both a normalization command and an identification command and received the same error each time.

**Steps to reproduce**

* Attempt to edit an FPR command
* Observe Internal Server Error in GUI
* Look in the logs
* Ingest a new SIP and see if the command takes effect

**Your environment (version of Archivematica, operating system, other relevant details)**

`qa/1.x` pre-1.12 release

Verified on a QA server and in local Docker dev environment

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged (if applicable)
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by tw4l** [comment]
Seems similar in nature to https://github.com/archivematica/Issues/issues/1276

**Comment by sallain** [comment]
Tested this on qa/1.x (commit 132d49a) and confirmed that it now works as expected.
