### ISSUE TITLE
Problem: not all Django email settings are configurable

### ISSUE THREAD

**Issue by mamedin** [archivematica/Issues#1298]
**Please describe the problem you'd like to be solved**

The following django variables could be usefull in Archivematica and Archivematica Storage Service:

EMAIL_SUBJECT_PREFIX
EMAIL_BACKEND

@uofmsean have suggested it on https://github.com/archivematica/Issues/issues/921

**Describe the solution you'd like to see implemented**

Make these variables configurable.

**Describe alternatives you've considered**

**Additional context**

See:

https://github.com/archivematica/Issues/issues/921
https://github.com/artefactual/archivematica-storage-service/pull/482

**Reminder**: include Hector's fix in the Arkivum model too - https://github.com/artefactual/archivematica-storage-service/pull/485.

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged
- [ ] Details about this issue have been added to the release notes

**Comment by replaceafill** [comment]
I tested that the listed settings can be customized in the Dashboard and the Storage Service through environment variables.
