### ISSUE TITLE
Problem: libgfortran-ed201abd.so.3.0.0 dependency for rpms packages (AM1.12)

### ISSUE THREAD

**Issue by mamedin** [archivematica/Issues#1299]
**Expected behaviour**

The dashboard and mcp-server packages shouldn't include the `libgfortran-ed201abd.so.3.0.0` because this library is included in the virtualenvs.

**Current behaviour**

The dashboard and mcp-server packages include `libgfortran-ed201abd.so.3.0.0` as dependency.

**Steps to reproduce**

Installing AM1.12 rpm packages.

**Your environment (version of Archivematica, operating system, other relevant details)**

AM1.12 and rpm packages

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged (if applicable)
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by scollazo** [comment]
This was caused by the addition of pandas in https://github.com/artefactual/archivematica/pull/1626

**Comment by mamedin** [comment]
Same issue when building Ubuntu packages:

```
12:45:54  dpkg-shlibdeps: error: cannot find library libgfortran-ed201abd.so.3.0.0 needed by debian/archivematica-mcp-client/usr/share/archivematica/virtualenvs/archivematica-mcp-client/lib/python2.7/site-packages/numpy/.libs/libopenblasp-r0-34a18dc3.3.7.so (ELF format: 'elf64-x86-64' abi: '0201003e00000000'; RPATH: '')
12:45:56  dpkg-shlibdeps: error: cannot continue due to the error above
12:45:56  Note: libraries are not searched in other binary packages that do not have any shlibs or symbols file.
12:45:56  To help dpkg-shlibdeps find private libraries, you might need to use -l.
```
