### ISSUE TITLE
Problem: Transfer METS validates but agent linking objects have no corresponding PREMIS agent objects (AM 1.11 / 1.12)

### ISSUE THREAD

**Issue by ross-spencer** [archivematica/Issues#1301]
**Expected behaviour**

PREMIS object relationships are described completely. 

**Current behaviour**

We're missing a set of agent objects in the transfer METS that one might expect to see. 

The AIP METS doesn't have the same issue so there we see an event say, with:

```xml
    <premis:linkingAgentIdentifier>
      <premis:linkingAgentIdentifierType>preservation system</premis:linkingAgentIdentifierType>
      <premis:linkingAgentIdentifierValue>Archivematica-1.11</premis:linkingAgentIdentifierValue>
    </premis:linkingAgentIdentifier>
    <premis:linkingAgentIdentifier>
      <premis:linkingAgentIdentifierType>repository code</premis:linkingAgentIdentifierType>
      <premis:linkingAgentIdentifierValue>artefactual</premis:linkingAgentIdentifierValue>
    </premis:linkingAgentIdentifier>
    <premis:linkingAgentIdentifier>
      <premis:linkingAgentIdentifierType>Archivematica user pk</premis:linkingAgentIdentifierType>
      <premis:linkingAgentIdentifierValue>2</premis:linkingAgentIdentifierValue>
    </premis:linkingAgentIdentifier>
```

And the agent objects (missing in the transfer METS looks like):
```xml
      <mets:mdWrap MDTYPE="PREMIS:AGENT">
        <mets:xmlData>
          <premis:agent xmlns:premis="http://www.loc.gov/premis/v3" xsi:schemaLocation="http://www.loc.gov/premis/v3 http://www.loc.gov/standards/premis/v3/premis.xsd" version="3.0">
            <premis:agentIdentifier>
              <premis:agentIdentifierType>repository code</premis:agentIdentifierType>
              <premis:agentIdentifierValue>artefactual</premis:agentIdentifierValue>
            </premis:agentIdentifier>
            <premis:agentName>artefactual</premis:agentName>
            <premis:agentType>organization</premis:agentType>
          </premis:agent>
        </mets:xmlData>
      </mets:mdWrap>
    </mets:digiprovMD>
    <mets:digiprovMD ID="digiprovMD_70">
      <mets:mdWrap MDTYPE="PREMIS:AGENT">
        <mets:xmlData>
          <premis:agent xmlns:premis="http://www.loc.gov/premis/v3" xsi:schemaLocation="http://www.loc.gov/premis/v3 http://www.loc.gov/standards/premis/v3/premis.xsd" version="3.0">
            <premis:agentIdentifier>
              <premis:agentIdentifierType>Archivematica user pk</premis:agentIdentifierType>
              <premis:agentIdentifierValue>2</premis:agentIdentifierValue>
            </premis:agentIdentifier>
            <premis:agentName>username="demo@example.com", first_name="", last_name=""</premis:agentName>
            <premis:agentType>Archivematica user</premis:agentType>
          </premis:agent>
        </mets:xmlData>
      </mets:mdWrap>
    </mets:digiprovMD>
```

**Steps to reproduce**

Create a SIP or AIP and inspect the output of the transfer METS in the submission documentation folder. 

**Your environment (version of Archivematica, operating system, other relevant details)**

Sandbox `1.11`, Bionic, `1.12`. 

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged (if applicable)
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by ross-spencer** [comment]
A snipped that might be usedul:

given something like:
```python
    agents = Agent.objects.filter(event__file_uuid_id=fileUUID).distinct()
    for agent_record in agents:
```
You can construct the agent snippets with:
```python
    PREMIS_META = metsrw.plugins.premisrw.PREMIS_3_0_META
    IE_PREMIS_META = PREMIS_META.copy()

    agent_data = (
        (
            "agent_identifier",
            ("agent_identifier_type", agent_record.identifiertype),
            ("agent_identifier_value", agent_record.identifiervalue),
        ),
        ("agent_name", agent_record.name),
        ("agent_type", agent_record.agenttype),
    )

    premis_data = (
        ("agent", IE_PREMIS_META) + agent_data
    )

    md = metsrw.plugins.premisrw.data_to_premis(
        premis_data, premis_version=IE_PREMIS_META["version"]
    )
```
NB. They need to be wrapped in:
```xml
    <mets:digiprovMD ID="digiprovMD_❓❓">
      <mets:mdWrap MDTYPE="PREMIS:AGENT">
        <mets:xmlData>
   ...
   ...
```
For reference this updated syntax is used in [create_transfer_mets](https://github.com/artefactual/archivematica/blob/396015a44723e6b2dd2f4d7bed1443514a429c12/src/MCPClient/lib/clientScripts/create_transfer_mets.py) already. However, anyone addressing this might want to consider introducing a separate METS helper module as this code has potential to be applicable to AIP METS in the fullness of time. A lot of object generation code in transfer METS too.

**Comment by corinnemrogers** [comment]
Tested with 1.13, reviewed transfer METS and AIP METS: premis:linkingAgentIdentifier and premis:agent now consistent in transfer METS to match AIP METS.
