### ISSUE TITLE
Problem: Date Range search in Archival Storage tab returns "Error accessing index" 

### ISSUE THREAD

**Issue by sarah-mason** [archivematica/Issues#1302]
**Expected behaviour**
When you search by date range option in the Archival Storage tab all results that fall in that date range should be returned as the documentation: https://www.archivematica.org/en/docs/archivematica-1.11/user-manual/archival-storage/archival-storage/#searching-the-aip-store

**Current behaviour**
A search by date range returns "Error accessing index" instead of a list of AIPs in that date range.
![Screenshot 2020-09-02 at 16 24 47](https://user-images.githubusercontent.com/24920834/92004325-01110480-ed3a-11ea-9e28-d0477c1bfbd1.png)

**Steps to reproduce**
- Go to Archivematica Archival Storage tab
- enter a date range, e.g. 2020-08-25:2020-08-27
- select "date range" search (not "keyword" or "phrase") and hit enter
![Screenshot 2020-09-02 at 16 25 14](https://user-images.githubusercontent.com/24920834/92004267-eccd0780-ed39-11ea-9d9e-929a3505a886.png)

**Your environment (version of Archivematica, operating system, other relevant details)**
1.11.2 -- also tested in: 1.12 (qa), 1.10.x, 1.9.x

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged (if applicable)
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by Bolkun** [comment]
@sarah-mason I got the same problem in archivematica 1.11 version. Did you find a solution for this issue?

**Comment by sarah-mason** [comment]
@Bolkun -- thanks for confirming the issue! It's still in refining and not yet triaged to any release, so no work is being done on it at present. The above PR is actually related to another issue, not this one. But if any work is done on this by us or a community member,  you'll see it linked here. Also, if we do start working on it, we'll change the `Status` label so keep an eye on that.

**Comment by tw4l** [comment]
Date range searches are not returning results because an Elasticsearch exception is being thrown. Stacktrace:

```
archivematica-dashboard_1        | Traceback (most recent call last):
archivematica-dashboard_1        |   File "/src/src/dashboard/src/components/archival_storage/views.py", line 339, in search
archivematica-dashboard_1        |     results = es_client.search(body=query, index=es.AIP_FILES_INDEX)
archivematica-dashboard_1        |   File "/usr/local/lib/python3.6/dist-packages/elasticsearch/client/utils.py", line 101, in _wrapped
archivematica-dashboard_1        |     return func(*args, params=params, **kwargs)
archivematica-dashboard_1        |   File "/usr/local/lib/python3.6/dist-packages/elasticsearch/client/__init__.py", line 872, in search
archivematica-dashboard_1        |     "GET", _make_path(index, doc_type, "_search"), params=params, body=body
archivematica-dashboard_1        |   File "/usr/local/lib/python3.6/dist-packages/elasticsearch/transport.py", line 409, in perform_request
archivematica-dashboard_1        |     timeout=timeout,
archivematica-dashboard_1        |   File "/usr/local/lib/python3.6/dist-packages/elasticsearch/connection/http_urllib3.py", line 252, in perform_request
archivematica-dashboard_1        |     self._raise_error(response.status, raw_data)
archivematica-dashboard_1        |   File "/usr/local/lib/python3.6/dist-packages/elasticsearch/connection/base.py", line 254, in _raise_error
archivematica-dashboard_1        |     status_code, error_message, additional_info
archivematica-dashboard_1        | elasticsearch.exceptions.RequestError: RequestError(400, 'illegal_argument_exception', 'field name is null or empty')
```

This exception is being thrown because Elasticsearch requires than a field is specified for range searches. This is [implied in the Elasticsearch 6.8 docs](https://www.elastic.co/guide/en/elasticsearch/reference/6.8/query-dsl-range-query.html) and made clearer in the docs for more recent versions such as [7.15](https://www.elastic.co/guide/en/elasticsearch/reference/7.15/query-dsl-range-query.html).

**Comment by sromkey** [comment]
I tested using the range 2021-01-01:2021-12-31 on a QA server and it worked as expected with no error.
