### ISSUE TITLE
Problem: METS from a dataverse transfer is invalid

### ISSUE THREAD

**Issue by joel-simpson** [archivematica/Issues#131]
**Expected behaviour**
When we preserve a dataset from Dataverse, we expect the Dataverse METS and the AIP METS to be well formed and valid (as per http://pim.fcla.edu/validate#input-file) 

**Current behaviour**
The METS from the dataset [Canadian Relocations](https://demodv.scholarsportal.info/dataset.xhtml?persistentId=doi:10.5072/FK2/QYH45Z) is not valid. 
For the [Dataverse METS](https://drive.google.com/open?id=1kiYInAT0TnDffbqvXdiwSUGNnF8vdnhy), we see the following error: 
```
line 92, column 106: cvc-datatype-valid.1.2.1: 
    '30_CFLQ_271_13-3-13_1524[1].pdf' is not a valid value for 'anyURI'.
line 92, column 106: cvc-attribute.3: The value 
    '30_CFLQ_271_13-3-13_1524[1].pdf' of attribute 'xlink:href' on element 
    'mets:FLocat' is not valid with respect to its type, 'anyURI'.
``` 
For the [AIP METS](https://drive.google.com/file/d/1kiYInAT0TnDffbqvXdiwSUGNnF8vdnhy/view?usp=sharing), we see: 
```
line 7464, column 68: cvc-minLength-valid: Value '' with length = '0' 
    is not facet-valid with respect to minLength '1' for type 'IDREFS'.
line 7464, column 68: cvc-attribute.3: The value ' ' of attribute 'DMDID' 
    on element 'mets:div' is not valid with respect to its type, 'IDREFS'.
```
**Steps to reproduce**
Use the dataverse transfer type, select the Canadian Relocations dataset, and create an AIP. 

**Your environment (version of Archivematica, OS version, etc)**
Using http://ocul-am-dv.dev.archivematica.org:62080/ which is currently based off of qa/1.x but includes the dataverse feature branches for both AM and SS.

**Comment by joel-simpson** [comment]
The [Images dataset](https://demodv.scholarsportal.info/dataset.xhtml?persistentId=doi:10.5072/FK2/EOGUHP) also has a validation error in the [AIP METS](https://drive.google.com/open?id=1CmKr3o1MSww-LzWhUixi3FHpy5m_FPun) (the dataverse METS is fine):

```
line 35, column 39: cos-nonambig: "https://mediaarea.net/mediainfo":Matrix_Channels and "https://mediaarea.net/mediainfo":Matrix_Channels (or elements from their substitution group) violate "Unique Particle Attribution". During validation against this schema, ambiguity would be created for those two particles.
```

**Comment by sromkey** [comment]
@joel-simpson the validation error you see in the Images dataset is from a known-issue which we'll also be addressing for 1.8: https://github.com/artefactual/archivematica/issues/1027

Transfer METS from non-Dataverse transfers appear to be valid in qa as far as I can tell... still digging into the details here but just capturing the investigation so far!

**Comment by sromkey** [comment]
Transfer METS issues:
- in the fileSec, xlink:href is not allowing square brackets to be used in the file name (e.g. 30_CFLQ_271_13-3-13_1524[1].pdf is not allowed but 30_CFLQ_271_13-3-13_1524_1.pdf is.
- line two is missing a PREMIS element. For example this line:
`<mets:mets xmlns:mets="http://www.loc.gov/METS/" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.loc.gov/METS/ http://www.loc.gov/standards/mets/version111/mets.xsd">` 
I believe what is missing is the OBJID which should be the UUID of the transfer.

The Transfer METS from the Dataverse transfer appears to be missing the UUID throughout actually.
as compared to this valid line:
`<mets:mets xmlns:mets="http://www.loc.gov/METS/" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" OBJID="7e71bf7b-a3bf-4cbd-b4e4-193b74f1b634" xsi:schemaLocation="http://www.loc.gov/METS/ http://www.loc.gov/standards/mets/mets.xsd">`

**Comment by sromkey** [comment]
AIP METS issue:

This one appears to be a little easier (I hope!) One of the items in the structMap is looking for a DMDID but there is no corresponding ID given. If you just remove the `DMDID=" "` from line 7564 (using the CadRelocation example) then it will validate.

**Comment by sromkey** [comment]
I just updated my comment above to reflect the fact that we're not actually talking about the Transfer METS, we're talking about a new METS file which only will appear in Dataverse AIPs.

**Comment by evelynPM** [comment]
Another validation issue in the dataverse mets file is "SchemaLocation: schemaLocation value = 'http://www.ddialliance.org/Specification/DDI-Codebook/2.5/XMLSchema/codebook.xsd' must have even number of URI's." This can be fixed as follows:
Change namespace from <ddi:codebook xmlns:ddi="http://www.icpsr.umich.edu/DDI" version="2.5" xsi:schemaLocation="http://www.ddialliance.org/Specification/DDI-Codebook/2.5/XMLSchema/codebook.xsd"> to <ddi:codebook xmlns:ddi="http://www.icpsr.umich.edu/DDI" version="2.5" xsi:schemaLocation="http://www.ddi:codebook:2_5 http://www.ddialliance.org/Specification/DDI-Codebook/2.5/XMLSchema/codebook.xsd">

**Comment by ross-spencer** [comment]
Transfer METS:
```
<mets:file ID="file-4e2842be-925f-46b2-bf74-aedbfff1e270" ADMID="digiprov-4e2842be-925f-46b2-bf74-aedbfff1e270">
        <mets:FLocat xlink:href="objects/30_CFLQ_271_13-3-13_1524[1].pdf" LOCTYPE="OTHER" OTHERLOCTYPE="SYSTEM"/>
      </mets:file>
```
If that snippet becomes:
```
      <mets:file ID="file-4e2842be-925f-46b2-bf74-aedbfff1e270" ADMID="digiprov-4e2842be-925f-46b2-bf74-aedbfff1e270">
        <mets:FLocat xlink:href="objects%2F30_CFLQ_271_13-3-13_1524%5B1%5D.pdf" LOCTYPE="OTHER" OTHERLOCTYPE="SYSTEM"/>
      </mets:file>
```
Then the validation works as expected. 

So we need to figure out where and when we can urlencode the path string, and what impact that may have in the workflow later on if any.

**Comment by ross-spencer** [comment]
For the blank `DMDID` the issue seems to be in this part of the code:

https://github.com/artefactual/archivematica/blob/37364dea64639b19e4d78f897ec0db5f4577b5d1/src/MCPClient/lib/clientScripts/create_mets_v2.py#L922-L931

Whereby, if a `DMDID` cannot be found, it is given a blank string as a value, and added to the METS anyway.

**Comment by ross-spencer** [comment]
RE: https://github.com/archivematica/Issues/issues/131#issuecomment-418852712
>>> line two is missing a PREMIS element. For example this line:
<mets:mets xmlns:mets="http://www.loc.gov/METS/" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.loc.gov/METS/ http://www.loc.gov/standards/mets/version111/mets.xsd">
I believe what is missing is the OBJID which should be the UUID of the transfer.
as compared to this valid line:
<mets:mets xmlns:mets="http://www.loc.gov/METS/" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" OBJID="7e71bf7b-a3bf-4cbd-b4e4-193b74f1b634" xsi:schemaLocation="http://www.loc.gov/METS/ http://www.loc.gov/standards/mets/mets.xsd">

Discussed with Sarah, and it is now confirmed this is not an issue for the METS that we are working with as it is a separate entity to the Transfer METS file.

**Comment by ross-spencer** [comment]
**Note to self:** The Bundle for Canadian Relocation data can be accessed via: https://demodv.scholarsportal.info/api/access/datafile/bundle/1010

**Comment by ross-spencer** [comment]
Hi @evelynPM, this looks like an easy fix for: https://github.com/archivematica/Issues/issues/131#issuecomment-419249318 but when I replace the values and validate the METS I get a new error where in the first instance I can't recreate the original issue you saw:
``
09/23/2018 23:25:49 ERROR: Element '{http://www.w3.org/2001/XMLSchema}import', 
attribute 'namespace': 'http://www.ddi:codebook:2_5' is not a valid value of 
the atomic type 'xs:anyURI'.
``` 
I have two questions about the issue:

1. What validation tool do I need to recreate the issue? It's not showing up via http://pim.fcla.edu/validate#input-direct for me.
2. Have you seen other ways of encoding the values you recommend in the METS before?

**Comment by joel-simpson** [comment]
Hi @ross-spencer - for question 1 - I believe that the validator @evelynPM was using when she looked at this was: https://www.xmlvalidation.com
(I just tried it with the original Dataverse METS and it highlights that issue).
