### ISSUE TITLE
Problem: Upgrade to 1.12 - update_elasticsearch_mappings failing with 'mapper [status] of different type, current_type [text], merged_type [keyword]'

### ISSUE THREAD

**Issue by uofmsean** [archivematica/Issues#1313]
**Expected behaviour**
[Update the Elasticsearch Mappings](https://www.archivematica.org/en/docs/archivematica-1.12/admin-manual/installation-setup/upgrading/upgrading/#update-the-elasticsearch-mappings) for an upgrade to 1.12 from 1.11.2 should not fail with an error.

**Current behaviour**
Running the "manage.py update_elasticsearch_mappings" step as described in [Update the Elasticsearch Mappings](https://www.archivematica.org/en/docs/archivematica-1.12/admin-manual/installation-setup/upgrading/upgrading/#update-the-elasticsearch-mappings) results in an Elasticsearch "RequestError(400, u'illegal_argument_exception', u'mapper [status] of different type, current_type [text], merged_type [keyword]')". Full log is in 
[update_elasticsearch_mappings.log](https://github.com/archivematica/Issues/files/5357608/update_elasticsearch_mappings.log)

**Steps to reproduce**
Upgrade to 1.12 from 1.11.2 and follow the instructions at [Update the Elasticsearch Mappings](https://www.archivematica.org/en/docs/archivematica-1.12/admin-manual/installation-setup/upgrading/upgrading/#update-the-elasticsearch-mappings)

**Your environment (version of Archivematica, operating system, other relevant details)**
Archivematica 1.12 and Storage Service 0.17 (upgraded from 1.11.2 and 0.16.1)
Python 2.7.5
Red Hat Enterprise Linux Server release 7.8 (Maipo)
Linux 3.10.0-1127.18.2.el7.x86_64 #1 SMP Mon Jul 20 22:32:16 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged (if applicable)
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by uofmsean** [comment]
This upgrade was for our development system and no AIPs were ingested during the process (the last one being Aug 19, long before the upgrade). When I first ran the command, I did get similar errors but unfortunately do not have the output. By running the command again, maybe I'm seeing a different error now that there is a status field? It is definitely there with the type 'text' now. I checked our production system, and that field is clearly not present yet since I haven't done the upgrade there. I'll follow your suggestions and roll back the indicies to see if the status field was present from before.

**Comment by uofmsean** [comment]
I restored the snapshot, but still the same problem. I even deleted the aips index before the restore on a second attempt since I thought the first restore must have failed. I verified that the recovery status was complete, but the aips index status field was still present with type 'text'. I took the snapshot two hours before I even attempted to upgrade the mappings so now I'm really puzzled as to what happened. At this point I'm just going to rebuild the indexes.

**Comment by uofmsean** [comment]
Indexes have been rebuilt, and the aips status field is now of type 'keyword'. Might as well close this issue and chalk it up to cabin fever. Thanks for your help @tw4l !

**Comment by tw4l** [comment]
No problem @uofmsean, I'm glad to hear that you were able to get the indices rebuilt! I'm sorry you had a hard time of it but thank you for the bug reports!

**Comment by sromkey** [comment]
I'm going to leave this issue open for now in case anyone else runs into it during the upgrade (easier to find when open).

**Comment by sevein** [comment]
In case this comes up again, @mamedin has documented a new process for upgrading the indices that has been giving us good results. See https://www.archivematica.org/en/docs/archivematica-1.12/admin-manual/installation-setup/upgrading/upgrading/#update-search-indices for more.
