### ISSUE TITLE
Problem: Hard to know which formats are related to which PRONOM IDs in FPR

### ISSUE THREAD

**Issue by ablwr** [archivematica/Issues#132]
@sallain and I talked about this before she left for AtoM Camp, so I am filing an issue on our behalf. When talking about issues with the Preservation Planning tab, she said it was difficult to know which formats related to which format IDs. Also, which group the format belonged to was not always clear, either.

As part of my onboarding process with understanding how the FPR connects to Archivematica, I made these improvements, and soon a link to a PR will appear below this issue.

@sromkey This isn't attached to any specific milestone, nor does it need to be.

**Comment by sevein** [comment]
This is ready for QA. However for this enhancement to be available in AM we need to make a new release of fpr-admin, which is going to be done as part of #110. So don't QA this one until #110 is also ready for QA. CC @sallain

**Comment by ablwr** [comment]
This is ready now!
