### ISSUE TITLE
Problem: clicking on metadata icon in transfer tab results in internal server error

### ISSUE THREAD

**Issue by evelynPM** [archivematica/Issues#1324]
**Expected behaviour**
Clicking on the metadata icon for a transfer in the transfer tab should open up a page that allows the user to add rights and descriptive metadata

**Current behaviour**
Clicking on the icon results in an internal server error page

**Steps to reproduce**
Click on a metadata icon in the transfer tab, either at a decision point or after the transfer has been processed

**Your environment (version of Archivematica, operating system, other relevant details)**
This error is happening in 1.12 but not 1.11

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged (if applicable)
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by replaceafill** [comment]
I just checked and this was caused by the Django 1.11 upgrade (sorry! :disappointed:). [This `namespace` variable](https://github.com/artefactual/archivematica/blob/462d91c0b65682ffe32f0a5dac5ae9f4b9afe07a/src/dashboard/src/components/rights/transfer_urls.py#L23) should be called `app_name`.

**Comment by sromkey** [comment]
This is resolved now! Thanks for the quick fix @replaceafill !
