### ISSUE TITLE
Feature: report SSL connection failure for post-store AIP callback

### ISSUE THREAD

**Issue by photomedia** [archivematica/Issues#1326]
**Please describe the problem you'd like to be solved**

If/when the post-store AIP callback fails in certain ways, it fails silently, without any feedback on any of the web interfaces (storage controller or the dashboard).  There is only a record of the failure in the log of the storage service.  It would be best to signal the failure/error on the dashboard and/or storage controller interface.

Specifically, when the following error occurs, it is only reported in the log at:

/var/log/archivematica/storage-service 

Here is the log of the error (replaced name of our domain with [domain] in the output below):

> INFO      2020-11-13 07:11:30  locations.models.package:package:run_post_store_callbacks:1498:  Executing post_store_aip callback: https://[domain]/id/archivematica/6
> ERROR     2020-11-13 07:11:30  locations.models.package:package:run_post_store_callbacks:1501:  Error in post_store_aip callback: HTTPSConnectionPool(host='[domain], port=443): Max retries exceeded with url: /id/archivematica/6 (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",),))
> 

The servers were unable to make a proper SSL connection.We were able to resolve the issue by adding the certificate to the server using the 2nd method described here: https://ep.gnt.md/index.php/curl-60-peers-certificate-issuer-is-not-recognized/. 
 
This SSL connection error that prevents the callback should be reported on the interface. 

**Describe the solution you'd like to see implemented**

SSL connection error should be reported, ideally on the Archivematica Dashboard, but also could work on the Storage Controller UI.

**Describe alternatives you've considered**

We solved the issue by using SSH to examine the log at: /var/log/archivematica/storage-service
However, the failure and error should reported somehow on the dashboard or storage controller.

**Additional context**

In our case, is important that the connection is through SSL, because our EPrints servers (what receives the callback) are configured to only accept SSL connections with redirects from non-secure protocols to SSL. 

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged
- [ ] Details about this issue have been added to the release notes

**Comment by mamedin** [comment]
Hi @photomedia,

You can add the CA certificate following this document:

https://www.archivematica.org/en/docs/archivematica-1.12/admin-manual/security/security/#ca-certificates

**Comment by tw4l** [comment]
Hi @photomedia, thanks for logging this! I agree it would be great to get more visibility of the Storage Service callbacks, and this has been on the radar for a little while - see also issue #881.

**Comment by ross-spencer** [comment]
Ha! That's me forgoetting about #881 Tessa and pointing Tomasz here! - Tomasz thanks for following up on these. If you feel #881 covers your needs, would you mind raising your interest there and then closing this as a duplicate? (And sorry about that!)

**Comment by photomedia** [comment]
Thanks @tw4l and @ross-spencer .  Yes, this issue I am describing is that of an error that is not reported on the UI in any way.  The HTTPS request isn't made at all in this case, the process stops before the call is made due to SSL issue.  The solution is to report errors, as described in https://github.com/archivematica/Issues/issues/881 so I am OK with closing this call as a duplicate.
