### ISSUE TITLE
Problem: Enable legacy persistent identifiers (PIDs) to be associated with transferred content

### ISSUE THREAD

**Issue by ross-spencer** [archivematica/Issues#133]
**Please describe the problem you'd like to be solved.**

When moving content from a legacy system into Archivematica, I want to be able to take advantage of the Archivematica PID capability to add legacy PIDs instead of minting new ones. 

**Describe the solution you'd like to see implemented.**

I would like to pass a document that can be read by Archivematica in such a way as to be able to pair PIDs with specific objects. This might make more sense in a transfer workflow, but it might also be something we consider doing at the current PID decision point during ingest. It is likely that complexity will vary choosing one over the other.

**Describe alternatives you've considered.**

Folks may be considering PIDs in Dublin Core and so as that work progresses one might consider extending Archivematica's capability to map DC, e.g. https://github.com/dcmi/pids_in_dc

**Comment by ross-spencer** [comment]
**NB.** Other transfer types (DSpace/Dataverse) may either be projects to look at that might already do something similar, or indeed benefit from this work where their extracts/AIPs also have PIDs.

**Comment by ross-spencer** [comment]
Okay, so the `dc:` initiative is more about enabling literals, and PID URIs for the same `dc:` element, so creator could be something like:

`<dc:creator id="https://orcid.org/0000-0003-1541-5631">Walk, Paul</dc:creator>`

Which could be quite nice, see: https://github.com/dcmi/pids_in_dc/blob/master/proposal/The_Association_of_Persistent_Identifiers_with_Literals_in_XML-formatted_Metadata_using_Dublin.md

This ticket discusses legacy identifiers however, and Dublin Core already allows us to do this: http://dublincore.org/documents/dcmi-terms/#elements-identifier 

It seems we just need to understand the drawbacks of using this field for legacy PIDs if any...

**Comment by ross-spencer** [comment]
More on `dc:identifier`:

![image](https://user-images.githubusercontent.com/1880412/46765942-1b551b80-cca6-11e8-8e45-6becdafbaa7f.png)

Turtle:

````
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix owl: <http://www.w3.org/2002/07/owl#> .
@prefix skos: <http://www.w3.org/2004/02/skos/core#> .
@prefix dcam: <http://purl.org/dc/dcam/> .
@prefix dcterms: <http://purl.org/dc/terms/> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .

<http://purl.org/dc/elements/1.1/identifier>
    dcterms:description "Recommended best practice is to identify the resource by means of a string conforming to a formal identification system. "@en ;
    dcterms:hasVersion <http://dublincore.org/usage/terms/history/#identifier-006> ;
    dcterms:issued "1999-07-02"^^<http://www.w3.org/2001/XMLSchema#date> ;
    dcterms:modified "2008-01-14"^^<http://www.w3.org/2001/XMLSchema#date> ;
    a rdf:Property ;
    rdfs:comment "An unambiguous reference to the resource within a given context."@en ;
    rdfs:isDefinedBy <http://purl.org/dc/elements/1.1/> ;
    rdfs:label "Identifier"@en ;
    skos:note "A second property with the same name as this property has been declared in the dcterms: namespace (http://purl.org/dc/terms/).  See the Introduction to the document \"DCMI Metadata Terms\" (http://dublincore.org/documents/dcmi-terms/) for an explanation."@en .
```

**Comment by ross-spencer** [comment]
Regarding repeatability of this field, if that were a concern:

```
1.2. What is the Dublin Core?

The Dublin Core metadata standard is a simple yet effective element set for describing a wide range of networked resources. The Dublin Core standard comprises fifteen elements, the semantics of which have been established through consensus by an international, cross-disciplinary group of professionals from librarianship, computer science, text encoding, the museum community, and other related fields of scholarship.

The Dublin Core element set is outlined in Section 4. Each element is optional and may be repeated. Each element also has a limited set of qualifiers, attributes that may be used to further refine (not extend) the meaning of the element. The Dublin Core Metadata Initiative (DCMI) has defined standard ways to "qualify" elements with various types of qualifiers. A registry of qualifiers conforming to DCMI "best practice" is in progress.
```

Via: http://www.dublincore.org/documents/2000/07/16/usageguide/

**Comment by sallain** [comment]
@ross-spencer Trying to test this, but getting errors - I assume because I don't know how to config the handle server page on the VM. Is it even possible to test without a handle server to test against?

**Comment by ross-spencer** [comment]
Hi @sallain, those are anticipated. We only made one small change to the original bind PIDs functions with this, and so between `1.9` and `1.10` you'll still need to configure the handle server, but you'll get a nicer, slightly more managed error/message from bind pids, so:
```
bindpids_v0.0: INFO      2019-07-12 23:18:51,299  archivematica.mcp.client.bind_pids.call:265  bind_pids called with args: {'shared_path': '/var/archivematica/sharedDirectory/', 'bind_pids_switch': True, 'sip_uuid': 'b6b58265-7a51-4904-8b05-bd39b1314c85'}
bindpids_v0.0: INFO      2019-07-12 23:18:51,301  archivematica.mcp.client.bind_pids.main:229  A value for parameter entity_type is required
```
vs.
```
bindpids_v0.0: INFO      2019-07-13 19:19:13,486  archivematica.mcp.client.bind_pids.call:237  bind_pids called with args: {'shared_path': '/var/archivematica/sharedDirectory/', 'bind_pids_switch': True, 'sip_uuid': '70d2255b-a5f3-4a2e-9cb0-3cd92d5a179f'}
'handle_archive_pid_source'Traceback (most recent call last):
  File "/opt/archivematica/archivematica/src/MCPClient/lib/job.py", line 102, in JobContext
    yield
  File "/opt/archivematica/archivematica/src/MCPClient/lib/clientScripts/bind_pids.py", line 238, in call
    job.set_status(main(job, **vars(args)))
  File "/opt/archivematica/archivematica/src/MCPClient/lib/clientScripts/bind_pids.py", line 82, in wrapped
    func(*_args, **kwargs)
  File "/opt/archivematica/archivematica/src/MCPClient/lib/clientScripts/bind_pids.py", line 215, in main
    _bind_pid_to_model(job, mdl, shared_path, handle_config)
  File "/opt/archivematica/archivematica/src/MCPClient/lib/clientScripts/bind_pids.py", line 188, in _bind_pid_to_model
    mdl, is_sip, shared_path, config['handle_archive_pid_source'])
KeyError: 'handle_archive_pid_source'
```
Which should (I hope?) be less intimidating for users start to configure the handle server form if it isn't already set up. (In practice, I don't think it will work like that, but I guess it's worth a try). 

That being said, the new feature will run before the Bind PIDs decision point as `Job: Persistent identifier (PID) declaration` so the user can set the bind pid decision point to `No` to reduce the noise and the ingest will complete and 🤞 the feature will have attached the new identifiers to the METS anyway! :) 

But let me know of course.

**Comment by sallain** [comment]
Okay! That's fine. I just wanted to make sure I wasn't doing something wrong. I definitely see the new style error message and that's nicer. As this was tested for the client I will move it to Done.

**Comment by sallain** [comment]
Documentation added via artefactual/archivematica-docs#293
