### ISSUE TITLE
Problem: Previewing or downloading files from pipeline local filesystem in Appraisal tab returns 404

### ISSUE THREAD

**Issue by tw4l** [archivematica/Issues#1333]
**Expected behaviour**

Downloading and previewing files in the Appraisal tab works regardless of which server the transfer backlog is on when the dashboard and Storage Service are on different machines.

**Current behaviour**

When the dashboard and Storage Service are on different machines and the transfer backlog is on the Pipeline Local Filesystem (i.e. the same machine as the Archivematica dashboard), attempting to preview or download files from the Appraisal tab fails and returns `404 Not Found`.

The immediate issue seems to be the result of doubled-up package name directories in the temporary directories created in the Storage Service's internal location, e.g.:

```
├── tmpwQQedY
│   └── originals
│       └── backlog-PLF-bd07828f-a7d0-4eee-a6fd-f38244b16a5c
│           └── backlog-PLF-bd07828f-a7d0-4eee-a6fd-f38244b16a5c
│               ├── bag-info.txt
│               ├── bagit.txt
│               ├── data
```

To understand why this is happening, it's useful to take a step back and consider the overall flow of what's happening when a file is requested from the Appraisal tab in the case where the Storage Service is on a different machine than the pipeline and the transfer backlog location is on the Pipeline Local Filesystem:

1. Pipeline dashboard's Appraisal tab requests file from Storage Service
2. Transfer package (uncompressed bag) is tarred so that entire package can be sent from pipeline local filesystem to the Storage Service server
3. Entire transfer package (as tarball) is sent to Storage Service server via rsync
3. Storage Service unpacks tarball to temporary directory in its internal storage location (resulting in doubled transfer name directories as shown above)
4. Storage Service attempts to find file to stream by its relative path within the unpacked package (and fails because of the doubled directory name)
5. Storage Service streams file (or, in our case, sends error message back to Pipeline)

An immediate fix might be a small tweak to the Storage Service to either account for or, preferably, avoid creating the doubled directories for packages of type `Package.TRANSFER`.

But this flow is also a lot of slow I/O over the network in order to (ultimately) stream a single file which is already in a transfer backlog directory on the local pipeline server, so I think it's likely that there's a better potential solution.

This issue can also be avoided by setting up the transfer backlog location(s) on the Storage Service's local filesystem rather than the pipeline local filesystem.

**Steps to reproduce**

* Set up an Archivematica dashboard and Archivematica Storage Service on different machines, with a transfer backlog location on the Pipeline Local Filesystem.
* Store a transfer in the transfer backlog.
* Attempt to download a file from the transfer backlog in the Appraisal tab.

**Your environment (version of Archivematica, operating system, other relevant details)**

We've seen this issue in Archivematica 1.11.2/Storage Service 0.16 and Archivematica 1.12.0/0.17. It's possible that older versions are also affected

**Other context**

It looks like this or a similar issue was intended to be fixed in https://github.com/artefactual/archivematica/commit/39c0e13 but the fix doesn't work for the particular configuration noted in this issue.

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged (if applicable)
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by sromkey** [comment]
This works now on a machine deployed with the SS on a separate server.
