### ISSUE TITLE
Problem: metadata-only DIP upload doesn't pass relative file path info to AtoM

### ISSUE THREAD

**Issue by peterVG** [archivematica/Issues#1334]
**Expected behaviour**
If Archivematica is being used in conjunction with an AtoM access system, the Download (Archivematica) File link will request and download a file from an Archivematica AIP via the Storage Service API for an authorized AtoM users. See https://www.accesstomemory.org/en/docs/2.7/user-manual/import-export/upload-digital-object/#digital-object-preservation

**Current behaviour**
This works for standard DIP uploads. However, if the Archivematica user has performed a metadata-only DIP upload to AtoM, then the Archivematica file metadata will be displayed in AtoM, along with a "Download File" link for authorized users. But clicking on the link will result in a `400 Missing parameter: relativepath.` error. 

This is due to the fact that metadata-only DIP upload does not send a METS file to AtoM which it can then parse for the file's relative path to use in the Storage Service request.

Instead, metadata-only DIP upload uses a script that imports the agentarchives module to pass metadata values to AtoM. https://github.com/artefactual/archivematica/blob/289f32f5ac9c205c954e569a8875ca2cb5fcfa06/src/dashboard/src/components/archival_storage/atom.py 

This agentarchives metadata hand-off needs to include the file's relative path so that AtoM can correctly construct the "Download File" request.

**Steps to reproduce**
Perform a metadata-only DIP upload from Archivematica to AtoM.
Ensure your AtoM user has permission to download files from Arhivematica.
Click on the "Download File" link.

**Your environment (version of Archivematica, operating system, other relevant details)**
Archivematica 1.12.x
AtoM 2.6.x

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged (if applicable)
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by peterVG** [comment]
related https://projects.artefactual.com/issues/13454

**Comment by sromkey** [comment]
@peterVG have you tested this locally by chance? We're not yet testing with AtoM 2.7 for the 1.13 release, but if you have had success locally I think we can close this.

**Comment by replaceafill** [comment]
I've confirmed this integration works. I created an AIP with the `DemoTransferCSV` and then did a `Metadata-only DIP upload to AtoM` and the `Download file` and `Download AIP` links work in the AtoM digital objects created.

![Screenshot 2021-07-06 at 10-52-36 View_from_lookout_over_Queenstown_towards_the_Remarkables_in_spring jpg - Demo site](https://user-images.githubusercontent.com/560781/124638791-9ee8ca80-de48-11eb-99f9-7e5bbdd64a87.png)
