### ISSUE TITLE
Storage service API regression between 1.11 and 1.12 for non-admin users

### ISSUE THREAD

**Issue by ross-spencer** [archivematica/Issues#1336]
**Expected behaviour**

In lieu of a more granular access model users have consistent access to the storage service REST API across versions.

**Current behaviour**

We are seeing a regression between 1.11 and 1.12 in behavior, e.g. for the locations endpoint. 1.12 does not return location information as expected as previously in 1.11. 

_1.12 - Non-admin:_

```
ross-spencer:~/git/artefactual-labs/AIPscan$ http --pretty=format \
   GET "http://127.0.0.1:62081/api/v2/location/" \
   Authorization:"ApiKey rosco:ab9184954d608664f4237910c1379148c011256f"
HTTP/1.1 200 OK
Cache-Control: no-cache
Connection: keep-alive
Content-Language: en
Content-Length: 101
Content-Type: application/json
Date: Thu, 03 Dec 2020 00:24:08 GMT
Server: nginx/1.18.0
Vary: Accept, Accept-Language, Cookie
X-Frame-Options: SAMEORIGIN

{
    "meta": {
        "limit": 20,
        "next": null,
        "offset": 0,
        "previous": null,
        "total_count": 0
    },
    "objects": []
}
```

_1.12 - Admin:_

```
ross-spencer:~/git/artefactual-labs/AIPscan$ http --pretty=format \
   GET "http://127.0.0.1:62081/api/v2/location/" \
   Authorization:"ApiKey rosco:ab9184954d608664f4237910c1379148c011256f"
HTTP/1.1 200 OK
Cache-Control: no-cache
Connection: keep-alive
Content-Language: en
Content-Length: 3367
Content-Type: application/json
Date: Thu, 03 Dec 2020 00:24:40 GMT
Server: nginx/1.18.0
Vary: Accept, Accept-Language, Cookie
X-Frame-Options: SAMEORIGIN

{
    "meta": {
        "limit": 20,
        "next": null,
        "offset": 0,
        "previous": null,
        "total_count": 7
    },
    "objects": [
        {
            "description": "",
            "enabled": true,
            "path": "/home",
            "pipeline": [
                "/api/v2/pipeline/573a7b2b-bb6e-43ea-b441-8f1e7bdfe67b/"
            ],
            "purpose": "TS",
            "quota": null,
            "relative_path": "home",
            "resource_uri": "/api/v2/location/71494313-51b8-4084-99cf-d97230cf3e3f/",
            "space": "/api/v2/space/2856a834-cee2-43f1-93d1-b9b392435ee4/",
            "used": 0,
            "uuid": "71494313-51b8-4084-99cf-d97230cf3e3f"
        },
        {
            "description": "Store AIP in standard Archivematica Directory",
            "enabled": true,
            "path": "/var/archivematica/sharedDirectory/www/AIPsStore",
            "pipeline": [
                "/api/v2/pipeline/573a7b2b-bb6e-43ea-b441-8f1e7bdfe67b/"
            ],
            "purpose": "AS",
            "quota": null,
            "relative_path": "var/archivematica/sharedDirectory/www/AIPsStore",
            "resource_uri": "/api/v2/location/50103c6f-02cc-43ac-9a93-7a318ee02092/",
            "space": "/api/v2/space/2856a834-cee2-43f1-93d1-b9b392435ee4/",
            "used": 157104,
            "uuid": "50103c6f-02cc-43ac-9a93-7a318ee02092"
        },
       ...
       ...
    ]
}
```

_1.11 - Non-admin_

```
ross-spencer:~/git/artefactual-labs/AIPscan$ http --pretty=format \
   GET "http://127.0.0.1:62081/api/v2/location/"     \
   Authorization:"ApiKey rosco:3bcda10745b186447b46d0aaf7ddea4152053993"
HTTP/1.1 200 OK
Cache-Control: no-cache
Connection: keep-alive
Content-Language: en
Content-Type: application/json
Date: Thu, 03 Dec 2020 00:50:50 GMT
Server: nginx/1.18.0
Transfer-Encoding: chunked
Vary: Accept, Accept-Language, Cookie
X-Frame-Options: SAMEORIGIN

{
    "meta": {
        "limit": 20,
        "next": null,
        "offset": 0,
        "previous": null,
        "total_count": 7
    },
    "objects": [
        {
            "description": "",
            "enabled": true,
            "path": "/home",
            "pipeline": [
                "/api/v2/pipeline/35202a03-147d-4a86-a238-6ef6ff090d20/"
            ],
            "purpose": "TS",
            "quota": null,
            "relative_path": "home",
            "resource_uri": "/api/v2/location/c9feb3a3-6b79-4646-a4a2-03d05fa98f09/",
            "space": "/api/v2/space/406e87e5-e8e9-49fe-b36a-2eaa8bc03401/",
            "used": "0",
            "uuid": "c9feb3a3-6b79-4646-a4a2-03d05fa98f09"
        },
        {
            "description": "Store AIP in standard Archivematica Directory",
            "enabled": true,
            "path": "/var/archivematica/sharedDirectory/www/AIPsStore",
            "pipeline": [
                "/api/v2/pipeline/35202a03-147d-4a86-a238-6ef6ff090d20/"
            ],
            "purpose": "AS",
            "quota": null,
            "relative_path": "var/archivematica/sharedDirectory/www/AIPsStore",
            "resource_uri": "/api/v2/location/66742782-9acf-41fc-9ce6-1d5e47be3e80/",
            "space": "/api/v2/space/406e87e5-e8e9-49fe-b36a-2eaa8bc03401/",
            "used": "11637623",
            "uuid": "66742782-9acf-41fc-9ce6-1d5e47be3e80"
        },
       ...
       ...
    ]
}
```

_1.11 - Admin:_ works as does non-admin below...

**Steps to reproduce**

As per above.

**Your environment (version of Archivematica, operating system, other relevant details)**

Archivematica 1.12 on Docker, also reported by the client. 

**Additional context**

I haven't spent time testing other endpoints. 

An idea about testing in future is that one way to improve our coverage here is to also ask AMAUAT to authenticate as a non-admin user and see what tests pass successfully or not. I have not tried this, but IIRC this issue may well have been spotted that way.

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged (if applicable)
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by tw4l** [comment]
This regression appears to be due to [a change in `django-tastypie` 0.13.2](https://django-tastypie.readthedocs.io/en/latest/release_notes/v0.13.2.html), which "updated DjangoAuthorization to disallow read unless a user has change permission," which non-administrative users in the Storage Service do not.

We upgraded to django-tastypie 0.14.3 in commit https://github.com/artefactual/archivematica-storage-service/commit/89f607c as part of the upgrade to Django 1.11.

**Comment by tw4l** [comment]
I think we have a couple options for how to proceed on this issue and I'd like to get your feedback on it @sevein @replaceafill @sromkey:

1. Revert to an older version of `django-tastypie` (would need to test to make sure it works with Django 1.11, which doesn't appear to be officially supported until `django-tastypie` 0.14.0)
2. Create a `CustomDjangoAurthorization` class to revert to the old behaviour, e.g. (draft PR): https://github.com/artefactual/archivematica-storage-service/pull/579
3. Consider this to be a security issue ([as the `django-tastypie` developers do](https://github.com/django-tastypie/django-tastypie/issues/1407)), and accept non-administrative users losing access to reading resources via the API as a "feature not a bug" :beetle: I see their rationale but currently non-administrative users are already able to see all the same information the API exposes via the Storage Service GUI, so I'm not sure that this would actually be a gain for us

**Comment by sevein** [comment]
Thanks for the analysis! I agree, with our current permission model, (3) doesn't make sense in Storage Service. I prefer your second option, it's very simple.

**Comment by replaceafill** [comment]
I confirmed that I can list resources as a non admin user through the API.
