### ISSUE TITLE
Problem: Enhance the PID documentation in the Archivematica docs

### ISSUE THREAD

**Issue by ross-spencer** [archivematica/Issues#134]
**Version of the documentation**

1.7.1

**Page (and section, if applicable) where the issue occurs**

Currently, the onld documentation on PIDs I can find in the public documentation is here: https://www.archivematica.org/en/docs/archivematica-1.7/user-manual/administer/dashboard-admin/#bind-pids

**Description of the issue**

There is very little detail around making PID binding work in Archivematica. If we can find an appropriate location, some examples for one or two handle servers might be a good improvement for users. A demonstration of the expected output in the AIP mets may also be useful. 

There are various other small changes we can make to the documentation too, e.g. to introduce the PID acronym before using it in certain pages.

**Comment by sallain** [comment]
@ross-spencer I don't know how public docs got skipped for this feature :neutral_face: Is there a feature file/developer docs somewhere that I can use to construct some proper documentation?

**Comment by sallain** [comment]
Note that there is also a sentence on configuring the Handle Server settings, here: https://www.archivematica.org/en/docs/archivematica-1.7/user-manual/administer/dashboard-admin/#handle-server

Throughout the docs and the UI, Handle Server and PID binding (or some form of the latter) are used interchangeably to mean the same thing. This should be consistent.

**Comment by sallain** [comment]
PID binding steps file https://github.com/artefactual-labs/archivematica-acceptance-tests/blob/master/features/steps/pid_binding_steps.py

**Comment by ross-spencer** [comment]
We may potentially need to document some of the behavior from #154 as well: https://github.com/archivematica/Issues/issues/154

**Comment by ross-spencer** [comment]
Related documentation/notes: https://docs.google.com/document/d/1gy2efR6UQ60LhDXhUAC3BW7a1we48u1woXjiirQUmqc/edit#heading=h.u15xx5u3xjwa
