### ISSUE TITLE
Problem: Fixity fails to clean up temporay files, disk fills up

### ISSUE THREAD

**Issue by amayita** [archivematica/Issues#1345]
**Expected behaviour**

~~I'd love to see `Fixity` clean up the temporary files it creates as it uncompresses AIPS for inspection.~~
When checking compressed AIPS, fixity fails to delete the temporary directories where AIPs are uncompressed to, filling up the disk.

**Current behaviour**
`Fixity` fills up the disk with temporary files because it fails to clean up after uncompressing AIPS for inspection. 

**Steps to reproduce**
Run fixity and, on a default installation, check the directory `/var/archivematica/storage_service/`  and you will find it creates as many `tmp*` directories as AIPs it's checking, that end up filling the disk up if the AIPS are big enough (and there's not enough free space). It leaves those dirs there forever.

**Your environment (version of Archivematica, operating system, other relevant details)**
AM v: 1.11.2
SS v: 0.16.1
Fixity v: Apr 17, 2020

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged (if applicable)
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by ross-spencer** [comment]
@amayita if possible can issues be phrased as problems and not solutions?

I suspect we'll find the problem is still the same as https://github.com/archivematica/Issues/issues/431 which has previously been noted. Fixity largely just wraps the API call which one can call standalone: https://www.archivematica.org/en/docs/archivematica-1.13/dev-manual/api/api-reference-storage-service/#check-fixity - that call might look like:

```

**Comment by ross-spencer** [comment]
Noting this might reasonably be considered a duplicate of https://github.com/archivematica/Issues/issues/431 and related issues which has previously been logged. 

Fixity largely just wraps the API call which one can call standalone: https://www.archivematica.org/en/docs/archivematica-1.13/dev-manual/api/api-reference-storage-service/#check-fixity - that call might look like:

```
http -v --pretty=format \
    GET "http://127.0.0.1:62081/api/v2/file/<uuid>/check_fixity/" \
    Authorization:"ApiKey test:test" 
```

So it's a high-level application designed to record progress and store some of the output of that but which doesn't rely on/might be better off not needing low-level access to the file-system. The solution may still therefore be to ask the storage service to do its job properly and to not leave behind excess data.

i'd be interested to know too if using the Dashboard can at least clear some space here to move processing forward:

![image](https://user-images.githubusercontent.com/1880412/105853386-a2cc1300-5fb3-11eb-9cd0-6ca7370dd7d0.png)

This has already been noted as related: https://github.com/archivematica/Issues/issues/1343 I wonder if too, other Fixity related issues such as https://github.com/archivematica/Issues/issues/29 might be incorporated into a solution for the app proper to ease the issues here.

**Comment by amayita** [comment]
I rephrased my report, as you were right, @ross-spencer it failed to describe the issue appropriately. 
Sorry and thx for pointing it out. I want my reports to be useful :)

**Comment by amayita** [comment]
As #431 is now fixed, pending merge, I am closing this issue.
