### ISSUE TITLE
Problem: Identification tools need to be updated

### ISSUE THREAD

**Issue by ablwr** [archivematica/Issues#135]
FIDO and Siegfried, two tools we use for identification of file formats, need to be updated to take advantage of new PRONOM updates (#110).

**Comment by sevein** [comment]
This is going to need changes in a couple of places:
- fpr-admin, to make sure that the tools reflect the versions used.
- packages.archivematica.org, where we usually ask Santi to publish the packaes for us.

**Comment by scollazo** [comment]
Once we agreed witch versions should be used, pull request updating siegfried and fido should be created at artefactual-labs/am-packbuild , in order to build the packages and upload them to the repositories

**Comment by peterVG** [comment]
see https://github.com/artefactual/archivematica/pull/1269
