### ISSUE TITLE
Problem: Cannot create a replicator location in Duracloud Space

### ISSUE THREAD

**Issue by mamedin** [archivematica/Issues#1350]
**Expected behaviour**

The replicator location can be created in a Duracloud Space

**Current behaviour**

When trying to create the replicator location in a Duracloud, the replicator cannot be selected (gray) in SS GUI.

**Steps to reproduce**

Creating a Duracloud Spaceand trying to add a replicator location.

**Your environment (version of Archivematica, operating system, other relevant details)**

AM 1.11.2, SS 0.16.1 on CentOS (rpm packages)

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged (if applicable)
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by mamedin** [comment]
I was doubting to create this issue as feature. Please, let me know if I need to change it.

**Comment by sromkey** [comment]
As @ross-spencer says- a good rule of thumb is if a space can be an AIP-store it should be able to be a replicator too!

**Comment by scollazo** [comment]
For reference, spaces have a ``` ALLOWED_LOCATION_PURPOSE``` var that tell what they can used for, and while there migth be historic reasons, there are some external services that work as aipstore, but not as other locations (ts/backlog/replicas).

NFS Space can't be a replicator: https://github.com/artefactual/archivematica-storage-service/blob/f02b9149863efe3e883806b7d470ab3c55273d03/storage_service/locations/models/nfs.py#L52
Dspace is only an aip store: https://github.com/artefactual/archivematica-storage-service/blob/stable/0.17.x/storage_service/locations/models/dspace.py#L90

**Comment by ross-spencer** [comment]
@scollazo so maybe not as straightforward as I hoped :cry:. Question: Do we have historic documentation why either shouldn't be a replicator? (DSpace kind of makes sense to me why it wouldn't be (I think))

**Comment by scollazo** [comment]
I would say that when replication spaces where added to the SS, they weren't added/tested on all the spaces already being supported as AIPstores.

**Comment by replaceafill** [comment]
> As @ross-spencer says- a good rule of thumb is if a space can be an AIP-store it should be able to be a replicator too!

This makes sense to me, but I'd wish the interfaces of spaces and locations were easier to follow or more clearly documented since I always have trouble when I just add a value to the `ALLOWED_LOCATION_PURPOSE` list of the space, test it (with a Duracloud test instance in this case) and it "seems" to work. Sorry for the rant...

That being said, I just tested adding the `REPLICATOR` purpose to the `Duracloud` space and was able to replicate an AIP from a `Local Filesystem` AIP Store to a Duracloud replicator :+1: .

**Comment by replaceafill** [comment]
The `Replicator` option is now enabled for Duracloud locations.

![Captura de pantalla de 2021-07-02 14-50-27](https://user-images.githubusercontent.com/560781/124327188-eddee900-db44-11eb-829e-9d558fa0c16b.png)
