### ISSUE TITLE
Service name required by `docker-compose` logs is different from the `docker-compose ps` one

### ISSUE THREAD

**Issue by avivace** [archivematica/Issues#1351]
**Archivematica develoment on Docker Compose documentation**

**[README](https://github.com/artefactual/archivematica/tree/qa/1.x/hack)**

In the troubleshooting guide section, it is said/implied to run `docker-compose logs -f SERVICE_NAME`, where SERVICE_NAME is the service Name from `docker-compose ps`. However, in the new recommended qa/1.x/hack branch the service names from `docker-compose ps` have these kind of names:

```
hack_archivematica-dashboard_1
hack_archivematica-storage-service_1
```

While the `docker-compose logs -f` command still needs, e.g. `archivematica-dashboard` and `archivematica-storage-service`, and not the full name as reported by `docker-compose ps`.

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by sevein** [comment]
Thanks @avivace, we should definitely fix that. If you want to update the docs or name the containers manually with `container_name` or similar please go ahead!
