### ISSUE TITLE
Problem: Metadata added before 'Approve transfer' microservice does not show up in the METS (and it used to)

### ISSUE THREAD

**Issue by kellyannewithane** [archivematica/Issues#140]
**Expected behaviour**
In 1.6 metadata added to DC fields before 'Approve transfer' used to show up in the dmdSec.

**Current behaviour**
It does not do that anymore.

**Steps to reproduce**
1 add information to DC fields BEFORE approving a transfer (on the transfer tab)
2 process the transfer, create an AIP
3 look at the METS, see nothing in dmdSec that you added in step 1

**Your environment (version of Archivematica, OS version, etc)**
1.7.x

**More information**
This workflow isn't documented but we have at least 1 client who uses it and has reported it.  Workaround would be for them to add it at normalization but this is late in the workflow - it's more convenient to do it earlier.

**Comment by peterVG** [comment]
Tested successfully in AM 1.8 Bionic. Metadata added before the Approve Transfer step is once again being included in the AIP dmdSec.

**Comment by peterVG** [comment]
NOTE: a dc.json consisting of metadata entered via the Dashboard before the "approve transfer" option is still being included in the AIP's /metadata/transfers/ directory, so related issue https://projects.artefactual.com/issues/11013 is not closed
