### ISSUE TITLE
MCP client job does not receive a correct SIP uuid argument

### ISSUE THREAD

**Issue by lwo** [archivematica/Issues#141]
**Expected behaviour**
A valid SIP uuid format is passed\processed so the MCP client can execute shell command with correct parameters.

**Current behaviour**
For example, this sip_uuid argument :
https://github.com/IISH/archivematica/blob/qa/1.x/src/MCPClient/lib/clientScripts/verify_aip.py#L210

has this runtime the value
/api/v2/location/a7480377-15fb-457e-a040-347289e66dfb//api/v2/location/a7480377-15fb-457e-a040-347289e66dfb/%/api/v2/location/a7480377-15fb-457e-a040-347289e66dfb/**S**/api/v2/location/a7480377-15fb-457e-a040-347289e66dfb/**I**/api/v2/location/a7480377-15fb-457e-a040-347289e66dfb/**P**/api/v2/location/a7480377-15fb-457e-a040-347289e66dfb/**U**/api/v2/location/a7480377-15fb-457e-a040-347289e66dfb/**U**/api/v2/location/a7480377-15fb-457e-a040-347289e66dfb/**I**/api/v2/location/a7480377-15fb-457e-a040-347289e66dfb/**D**/api/v2/location/a7480377-15fb-457e-a040-347289e66dfb/%/api/v2/location/a7480377-15fb-457e-a040-347289e66dfb//api/v2/location/a7480377-15fb-457e-a040-347289e66dfb/

Note the capitals "S-I-P-U-U-I-D" are separators the above string.

The mcp-client log show it like this (where we added tenp_dir and sip_uuid ourselves in the printout):

*** Completed job: #<verifyaip_v1.0; exit=1; code=success uuid=62dd58a7-8583-42c5-8d34-5551dc4f1eca
=============== STDOUT ===============
temp_dir:  /data/work/sharedDirectory/02/tmp
sip_uuid:  /api/v2/location/a7480377-15fb-457e-a040-347289e66dfb//api/v2/location/a7480377-15fb-457e-a040-347289e66dfb/%/api/v2/location/a7480377-15fb-457e-a040-347289e66dfb/S/api/v2/location/a7480377-15fb-457e-a040-347289e66dfb/I/api/v2/location/a7480377-15fb-457e-a040-347289e66dfb/P/api/v2/location/a7480377-15fb-457e-a040-347289e66dfb/U/api/v2/location/a7480377-15fb-457e-a040-347289e66dfb/U/api/v2/location/a7480377-15fb-457e-a040-347289e66dfb/I/api/v2/location/a7480377-15fb-457e-a040-347289e66dfb/D/api/v2/location/a7480377-15fb-457e-a040-347289e66dfb/%/api/v2/location/a7480377-15fb-457e-a040-347289e66dfb//api/v2/location/a7480377-15fb-457e-a040-347289e66dfb/
extract_dir:  /api/v2/location/a7480377-15fb-457e-a040-347289e66dfb//api/v2/location/a7480377-15fb-457e-a040-347289e66dfb/%/api/v2/location/a7480377-15fb-457e-a040-347289e66dfb/S/api/v2/location/a7480377-15fb-457e-a040-347289e66dfb/I/api/v2/location/a7480377-15fb-457e-a040-347289e66dfb/P/api/v2/location/a7480377-15fb-457e-a040-347289e66dfb/U/api/v2/location/a7480377-15fb-457e-a040-347289e66dfb/U/api/v2/location/a7480377-15fb-457e-a040-347289e66dfb/I/api/v2/location/a7480377-15fb-457e-a040-347289e66dfb/D/api/v2/location/a7480377-15fb-457e-a040-347289e66dfb/%/api/v2/location/a7480377-15fb-457e-a040-347289e66dfb//api/v2/location/a7480377-15fb-457e-a040-347289e66dfb/

=============== END STDOUT ===============
=============== STDERR ===============
OSError(13, 'Permission denied')
Error extracting AIP at "/api/v2/location/a7480377-15fb-457e-a040-347289e66dfb//api/v2/location/a7480377-15fb-457e-a040-347289e66dfb/%/api/v2/location/a7480377-15fb-457e-a040-347289e66dfb/S/api/v2/location/a7480377-15fb-457e-a040-347289e66dfb/I/api/v2/location/a7480377-15fb-457e-a040-347289e66dfb/P/api/v2/location/a7480377-15fb-457e-a040-347289e66dfb/D/api/v2/location/a7480377-15fb-457e-a040-347289e66dfb/i/api/v2/location/a7480377-15fb-457e-a040-347289e66dfb/r/api/v2/location/a7480377-15fb-457e-a040-347289e66dfb/e/api/v2/location/a7480377-15fb-457e-a040-347289e66dfb/c/api/v2/location/a7480377-15fb-457e-a040-347289e66dfb/t/api/v2/location/a7480377-15fb-457e-a040-347289e66dfb/o/api/v2/location/a7480377-15fb-457e-a040-347289e66dfb/r/api/v2/location/a7480377-15fb-457e-a040-347289e66dfb/y/api/v2/location/a7480377-15fb-457e-a040-347289e66dfb/%/api/v2/location/a7480377-15fb-457e-a040-347289e66dfb/%/api/v2/location/a7480377-15fb-457e-a040-347289e66dfb/A/api/v2/location/a7480377-15fb-457e-a040-347289e66dfb/I/api/v2/location/a7480377-15fb-457e-a040-347289e66dfb/P/api/v2/location/a7480377-15fb-457e-a040-347289e66dfb/F/api/v2/location/a7480377-15fb-457e-a040-347289e66dfb/i/api/v2/location/a7480377-15fb-457e-a040-347289e66dfb/l/api/v2/location/a7480377-15fb-457e-a040-347289e66dfb/e/api/v2/location/a7480377-15fb-457e-a040-347289e66dfb/n/api/v2/location/a7480377-15fb-457e-a040-347289e66dfb/a/api/v2/location/a7480377-15fb-457e-a040-347289e66dfb/m/api/v2/location/a7480377-15fb-457e-a040-347289e66dfb/e/api/v2/location/a7480377-15fb-457e-a040-347289e66dfb/%/api/v2/location/a7480377-15fb-457e-a040-347289e66dfb//api/v2/location/a7480377-15fb-457e-a040-347289e66dfb/"

=============== END STDERR ===============

**Steps to reproduce**
Start a transfer and approve.

**Your environment (version of Archivematica, OS version, etc)**
Ubuntu 16.04 lts 64-bit
Fork: https://github.com/IISH/archivematica
Branch qa/1.x

**Comment by jrwdunham** [comment]
@lwo I'm wondering if you can give me more details about the type of transfer created in that 141 issue. Here are some specific questions:

1. What was the name of the transfer? Were there strange/special characters in it?
2. What was the name of the directory used to create the transfer? Were there strange/special characters in it?
3. The processing config indicates to me that you were creating uncompressed AIPs. Is that true?
4. Did the transfer contain a package that had to be extracted?
5. Was the transfer a standard type transfer?

**Comment by lwo** [comment]
1. It was: ARCH00000.test00010
2. Identical: ARCH00000.test00010
So alphanumeric and a dot.
3. Yes: a 7z copy: packaged but not compressed
4. No. The problem occurs even with single file transfers ( a folder with one file ).
5. Yes: standard transfer

**Comment by lwo** [comment]
I am not able to replicate this on Ubuntu 16...

**Comment by sevein** [comment]
Thanks for the update, @lwo. I'm hoping this was only reproducible in the context described under #182 which was addressed by https://github.com/artefactual/archivematica/pull/1268. I'm going to close, feel free to re-open if it appears again.
