### ISSUE TITLE
Problem: orphan chain link in workflow data

### ISSUE THREAD

**Issue by sevein** [archivematica/Issues#142]
**Steps to reproduce**
1. Deploy environment with Compose
2. Run `make manage-dashboard ARG="json_links"`
3. The following error is seen:

        root:json_links:process_chain_link_task_details:113:  Link eb52299b-9ae6-4a1f-831e-c7eee0de829f points to a StandardTaskConfig tuple that is missing!

Meaning that we have a MSCL that it's unused and not referenced by others: `eb52299b-9ae6-4a1f-831e-c7eee0de829f`. It should be removed.

Does this issue impact the user? Probably not, but bad data in the workflow dataset makes it hard to work with the tooling and practices that we've developed to manipulate it.

**Your environment (version of Archivematica, OS version, etc)**
qa/1.x d343fef0a908b4e08c42e616a716bb3f2ebe6c86

**Comment by ablwr** [comment]
I tested this
