### ISSUE TITLE
Problem: After a SIP fails creation in the Appraisal tab, a successful creation of the same SIP name will create a clash in the database that halts SIP creation in the Ingest tab

### ISSUE THREAD

**Issue by sarah-mason** [archivematica/Issues#1423]
**Expected behaviour**
A SIP in the Appraisal tab should fail to start if the SIP has no contents. Content should then be able to be added and started successfully. When that SIP is created successfully, it should appear in the Ingest tab with the "Approve SIP Creation" job.

**Current behaviour**
When a SIP is accidentally started in the Appraisal tab, it will fail creation. A 500 will appear in the dashboard log. An entry will also appear in the database in the `SIPs` table.

If backlog objects are then added to the SIP and the name is unchanged, a new SIP can be created. However it will not appear in the Ingest tab. A second entry will appear in the `SIPs` table that causes a clash for the MCP Server

> mysql> SELECT      currentPath,      COUNT(currentPath) FROM     SIPs GROUP BY currentPath HAVING COUNT(currentPath) > 1;
> +-------------------------------------------------------------------------------+--------------------+
> | currentPath                                                                   | COUNT(currentPath) |
> +-------------------------------------------------------------------------------+--------------------+
> | %sharedPath%watchedDirectories/SIPCreation/SIPsUnderConstruction/sm-test-sip/ |                  2 |
> +-------------------------------------------------------------------------------+--------------------+
> 1 row in set (0.01 sec)

The MCP Server log will show this error:
`Feb 11 10:47:30 am1.centos-rpm-1112.camps.archivematica.org python[30537]: MultipleObjectsReturned: get() returned more than one SIP -- it returned 2!`

One of the SIP entries must be deleted from the database 'SIPs' table and then the MCP Server restarted for the SIP to appear in the Ingest tab.

**Steps to reproduce**

1. In the Appraisal tab, create a directory in the Arrangement window. Do not add any backlog objects to it. It should be empty so it fails.
2. Hit the Start SIP button. This should create a failure and a SIP should not be created. The dashboard log should show a 500 entry like this: 
`82.28.144.104 - - [11/Feb/2021:10:41:28 +0000] "GET /access/archivesspace/levels/ HTTP/1.1" 500 130 "http://am1.centos-rpm-1112.camps.archivematica.org/appraisal/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36"`
3. Add backlog objects to the same directory (do not change the name) in the Arrangement window.
4. Hit the Start SIP button. It should say the SIP has been created successfully but it will not appear in the Ingest tab. The MCP Server log will show an error like this: 
`Feb 11 10:47:30 am1.centos-rpm-1112.camps.archivematica.org python[30537]: MultipleObjectsReturned: get() returned more than one SIP -- it returned 2!
Hint: Some lines were ellipsized, use -l to show in full.` 
This error will cause the SIP to remain stuck and the instance to stop processing.

**Note:** We had a similar failure when a SIP created from arrangement in the Appraisal tab failed at a point during Ingest. However, this was a two part issue where first the arrangement entries in the database `main_siparrange` table needed to be deleted first. They had not been cleared after the failure and the objects were still appearing as unavailable even though the failed SIP had been deleted from the `/failed` directory. When the objects were available again, they were arranged in the Appraisal tab under the same SIP name as the previous failure. When the SIP was successfully started, the same database clash happened again as the original entry was still in the 'SIPs' table in the database. This requires more testing  though.

**Your environment (version of Archivematica, operating system, other relevant details)**
1.12.1

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged (if applicable)
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by mamedin** [comment]
The workaround is:

* Find the transfer without records in `main_siparrange` table
* Delete this transfers from `SIPs` table
* Restart mcp-server, mcp-client and dashboard services

For instance, to fix the description issue:

```
mysql> select sipUUID from SIPs where currentPath='%sharedPath%watchedDirectories/SIPCreation/SIPsUnderConstruction/sm-test-sip/';
+--------------------------------------+
| sipUUID                              |
+--------------------------------------+
| 088bc318-9b1a-4db7-bff4-3b86441e86ae |
| 2f75a0eb-28c5-40b5-8661-b8979632f287 |
+--------------------------------------+
2 rows in set (0.00 sec)

mysql> select * from main_siparrange where sip_id='088bc318-9b1a-4db7-bff4-3b86441e86ae';
+----+---------------------------------------------------------------------------------------------------------+----------------------------------+--------------------------------------+--------------------------------------+-------------+-------------+----------------------+--------------------------------------+
| id | original_path                                                                                           | arrange_path                     | file_uuid                            | transfer_uuid                        | sip_created | aip_created | level_of_description | sip_id                               |
+----+---------------------------------------------------------------------------------------------------------+----------------------------------+--------------------------------------+--------------------------------------+-------------+-------------+----------------------+--------------------------------------+
| 26 | NULL                                                                                                    | .                                | NULL                                 | NULL                                 |           1 |           0 |                      | 088bc318-9b1a-4db7-bff4-3b86441e86ae |
| 28 | originals/officedocs-cfe9307b-4381-4c7a-94b0-ea513b7f8f67/data/objects/_datavibe-l__FW__job_vacancy.rtf | _datavibe-l__FW__job_vacancy.rtf | b7d238d9-aea9-49fb-a886-3fdb5449fed8 | cfe9307b-4381-4c7a-94b0-ea513b7f8f67 |           1 |           0 |                      | 088bc318-9b1a-4db7-bff4-3b86441e86ae |
+----+---------------------------------------------------------------------------------------------------------+----------------------------------+--------------------------------------+--------------------------------------+-------------+-------------+----------------------+--------------------------------------+
2 rows in set (0.00 sec)

mysql> select * from main_siparrange where sip_id='2f75a0eb-28c5-40b5-8661-b8979632f287';
Empty set (0.00 sec)
```

So the empty one is: sip_id='2f75a0eb-28c5-40b5-8661-b8979632f287'

To delete it:

```
mysql> delete from SIPs where sipUUID='2f75a0eb-28c5-40b5-8661-b8979632f287';
Query OK, 1 row affected (0.00 sec)
```

Restart AM services:

```
sudo service archivematica-mcp-server restart
sudo service archivematica-mcp-client restart
sudo service archivematica-dashboard restart
```

**Comment by ross-spencer** [comment]
Nice sleuthing both!

**Comment by mamedin** [comment]
The bug seems more serious.

It happens when creating a new transfer from appraisal tab with the same directory name (with or without files).

It creates a new transfer with "_1" suffix:

```
[root@am1 sharedDirectory]# find | grep SIPsUnderConstruction/2app3
./watchedDirectories/SIPCreation/SIPsUnderConstruction/2app3
./watchedDirectories/SIPCreation/SIPsUnderConstruction/2app3/MS-OfficeOpenXML-samples.zip
./watchedDirectories/SIPCreation/SIPsUnderConstruction/2app3/logs
./watchedDirectories/SIPCreation/SIPsUnderConstruction/2app3/logs/arrange.log
./watchedDirectories/SIPCreation/SIPsUnderConstruction/2app3/metadata
./watchedDirectories/SIPCreation/SIPsUnderConstruction/2app3/metadata/submissionDocumentation
./watchedDirectories/SIPCreation/SIPsUnderConstruction/2app3_1
./watchedDirectories/SIPCreation/SIPsUnderConstruction/2app3_1/samplepptx.pptx
./watchedDirectories/SIPCreation/SIPsUnderConstruction/2app3_1/logs
./watchedDirectories/SIPCreation/SIPsUnderConstruction/2app3_1/logs/arrange.log
./watchedDirectories/SIPCreation/SIPsUnderConstruction/2app3_1/metadata
./watchedDirectories/SIPCreation/SIPsUnderConstruction/2app3_1/metadata/submissionDocumentation
``` 
But it adds a new record to database (focus on createdTime field):

```
mysql> select * from SIPs where currentPath like '%sharedPath%watchedDirectories/SIPCreation/SIPsUnderConstruction/2ap%';
+--------------------------------------+----------------------------+---------------------------------------------------------------------------+--------+-------------+---------+----------+
| sipUUID                              | createdTime                | currentPath                                                               | hidden | aipFilename | sipType | dirUUIDs |
+--------------------------------------+----------------------------+---------------------------------------------------------------------------+--------+-------------+---------+----------+
| 09078057-53c5-4bd1-b513-058e2e3d5a57 | 2021-02-11 10:04:52.170110 | %sharedPath%watchedDirectories/SIPCreation/SIPsUnderConstruction/2app3/   |      0 | NULL        | SIP     |        0 |
| 0e854180-b62b-414c-b98b-eedbdc241150 | 2021-02-11 09:37:32.988397 | %sharedPath%watchedDirectories/SIPCreation/SIPsUnderConstruction/2app3/   |      0 | NULL        | SIP     |        0 |
| 388e2eef-07d2-4984-bd7b-4ae723b02b12 | 2021-02-11 10:04:52.743284 | %sharedPath%watchedDirectories/SIPCreation/SIPsUnderConstruction/2app3_1/ |      0 | NULL        | SIP     |        0 |
+--------------------------------------+----------------------------+---------------------------------------------------------------------------+--------+-------------+---------+----------+
```

**Comment by sromkey** [comment]
Tested by attempting to create an empty SIP which failed; after adding content it was successful.
