### ISSUE TITLE
Problem: Purpose field of Location forms does not disable invalid options

### ISSUE THREAD

**Issue by replaceafill** [archivematica/Issues#1424]
**Expected behaviour**

The Purpose field allows to select only options listed in the `ALLOWED_LOCATION_PURPOSE ` attribute of the location's space.

**Current behaviour**

All the Purpose options are enabled no matter what type of space you're using. However, options are validated on submission and you get an `Invalid purpose` error message when you submit an invalid one.

See this example of a `GPG encryption on Local Filesystem` space which is only supposed to have [AIP Storage, Backlog and Replicator locations](https://github.com/artefactual/archivematica-storage-service/blob/ff51028190b5389f54038ac544d1e4d5600491de/storage_service/locations/models/gpg.py#L84-L87):

![Captura de pantalla de 2021-02-12 12-22-43](https://user-images.githubusercontent.com/560781/107807369-a2f73d00-6d2d-11eb-9bb0-746639835866.png)

![Screenshot_2021-02-12 Archivematica Storage Service](https://user-images.githubusercontent.com/560781/107808673-9378f380-6d2f-11eb-8233-7c67d75f336e.png)

I think this is a regression in the [DisableableSelectWidget](https://github.com/artefactual/archivematica-storage-service/blob/ff51028190b5389f54038ac544d1e4d5600491de/storage_service/locations/forms.py#L24) class caused by the [Django 1.11 upgrade where the undocumented `Select.render_option` method was removed](https://docs.djangoproject.com/en/1.11/releases/1.11/#changes-due-to-the-introduction-of-template-based-widget-rendering).

**Steps to reproduce**

1. Create a  `GPG encryption on Local Filesystem` space
2. Add a location in the new space
3. Check that you can select any option in the Purpose field dropdown

**Your environment (version of Archivematica, operating system, other relevant details)**

SS on https://github.com/artefactual/archivematica-storage-service/commit/ff51028190b5389f54038ac544d1e4d5600491de
Also confirmed the regression between `am111bionic` (SS 0.16.1) and `am112bionic` (SS 0.17.0).

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged (if applicable)
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by ross-spencer** [comment]
I wondered about this recently but I couldn't recall the previous behavior so didn't go down that rabbit hole. Good sleuthing! It feels particularly unintuitive to use the interface like this right now. Especially if you use it as a guide about what should be possible for a location.

**Comment by replaceafill** [comment]
I agree. I got to it because I'm investigating https://github.com/archivematica/Issues/issues/1350 and thought "wait! I can select Replicator! Is this fixed already?!?" :facepalm:

**Comment by jhsimpson** [comment]
I tested this, and the problem is resolved.  I don't see the message 'invalid purpose', but instead the invalid options are greyed out in the dropdown list.  

I tried creating a new loacation in a regular filesystem space, and another one in a gpg encrypted space, and the dropdown list only lets me pick the choices that are valid for that space.

👍
