### ISSUE TITLE
Problem: 7z and fits fail on CentOS/RedHat when mounting /tmp with `noexec` option

### ISSUE THREAD

**Issue by mamedin** [archivematica/Issues#1425]
**Version of the documentation**

Any Archivematica version, this is a system related issue.

**Page (and section, if applicable) where the issue occurs**

Probably it should be added as prerequisite, for example here: /admin-manual/installation-setup/installation/install-centos/

**Description of the issue**

When mounting /tmp directory with  the `noexec` flag in  the `/etc/fstab` file, it doesn't allow to run 7z or fits from Archivematica. You get a permission denied error issue with 7z (when compressing AIP) and FITS (characterize and extract metadata).

```
[Errno 13] Permission denied[Errno 13] Permission denied
```

![image](https://user-images.githubusercontent.com/10259133/108249347-42189c00-7155-11eb-99db-a01ff0f6363c.png)

**Suggested fix**

Explain in documentation that it needs to be changed in order to run Archivematica at least when using compression or FITS.

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by ross-spencer** [comment]
Interesting reasons why folks might adopt different values for the temporary directory: https://www.cyberciti.biz/faq/linux-add-nodev-nosuid-noexec-options-to-temporary-storage-partitions/

**Comment by ross-spencer** [comment]
Miguel has been doing some great investigation and testing in this space successfully changing the temporary directory used by Python and seeing it used by Archivematica. A user might change the temporary directory to work around other `/tmp` dir restrictions.

The directory for Python can be changed [per the docs](https://docs.python.org/3/library/tempfile.html#tempfile.mkstemp).

> If dir is not None, the file will be created in that directory; otherwise, a default directory is used. The default directory is chosen from a platform-dependent list, but the user of the application can control the directory location by setting the TMPDIR, TEMP or TMP environment variables. There is thus no guarantee that the generated filename will have any nice properties, such as not requiring quoting when passed to external commands via os.popen().

Miguel has noticed that there is still some default /tmp usage. 

I wanted to see what Docker might show us. We can make a change to Archivematica using docker to use `/tmp2`. Rhe Dockerfiles look as follows.

```diff
diff --git a/Dockerfile b/Dockerfile
index c33cea6..0dcb01e 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -50,6 +50,9 @@ RUN set -ex \
        && mkdir -p $internalDirs \
        && chown -R archivematica:archivematica $internalDirs
 
+RUN mkdir /tmp2
+RUN chmod 1777 /tmp2
+
 WORKDIR /src/storage_service
 
 USER archivematica
diff --git a/src/MCPClient-base.Dockerfile b/src/MCPClient-base.Dockerfile
index 8f94d5649..2548f1c2f 100644
--- a/src/MCPClient-base.Dockerfile
+++ b/src/MCPClient-base.Dockerfile
@@ -83,3 +83,6 @@ RUN set -ex \
 RUN set -ex \
        && groupadd --gid 333 --system archivematica \
        && useradd -m --uid 333 --gid 333 --system archivematica
+
+RUN mkdir /tmp2
+RUN chmod 1777 /tmp2
diff --git a/src/MCPClient.Dockerfile b/src/MCPClient.Dockerfile
index decbb2ad5..71ce1981c 100644
--- a/src/MCPClient.Dockerfile
+++ b/src/MCPClient.Dockerfile
@@ -22,6 +22,8 @@ COPY MCPClient/ /src/MCPClient/
 COPY archivematicaCommon/lib/externals/fido/ /usr/lib/archivematica/archivematicaCommon/externals/fido/
 COPY archivematicaCommon/lib/externals/fiwalk_plugins/ /usr/lib/archivematica/archivematicaCommon/externals/fiwalk_plugins/
 
+RUN mkdir /tmp2
+RUN chmod 1777 /tmp2
 
 USER archivematica
 
diff --git a/src/MCPServer.Dockerfile b/src/MCPServer.Dockerfile
index 07788f604..d77484fa8 100644
--- a/src/MCPServer.Dockerfile
+++ b/src/MCPServer.Dockerfile
@@ -40,6 +40,9 @@ RUN set -ex \
        && mkdir -p /var/archivematica/sharedDirectory \
        && chown -R archivematica:archivematica /var/archivematica
 
+RUN mkdir /tmp2
+RUN chmod 1777 /tmp2
+
 USER archivematica
 
 ENTRYPOINT ["/src/MCPServer/lib/archivematicaMCP.py"]
diff --git a/src/dashboard.Dockerfile b/src/dashboard.Dockerfile
index 883d4a684..74369974a 100644
--- a/src/dashboard.Dockerfile
+++ b/src/dashboard.Dockerfile
@@ -66,6 +66,9 @@ RUN set -ex \
        && mkdir -p $internalDirs \
        && chown -R archivematica:archivematica $internalDirs
 
+RUN mkdir /tmp2
+RUN chmod 1777 /tmp2
+
 COPY dashboard/frontend/ /src/dashboard/frontend/
 RUN chown -R archivematica:archivematica /src/dashboard/frontend \
        && su -l archivematica -c "cd /src/dashboard/frontend && npm install"
```

And `docker-compose.yml`:

```diff
diff --git a/compose/docker-compose.yml b/compose/docker-compose.yml
index 80c59c4..b4bf093 100644
--- a/compose/docker-compose.yml
+++ b/compose/docker-compose.yml
@@ -113,6 +113,7 @@ services:
       ARCHIVEMATICA_MCPSERVER_SEARCH_ENABLED: "${AM_SEARCH_ENABLED:-true}"
       ARCHIVEMATICA_MCPSERVER_MCPSERVER_PROMETHEUS_BIND_PORT: "7999"
       ARCHIVEMATICA_MCPSERVER_MCPSERVER_PROMETHEUS_BIND_ADDRESS: "0.0.0.0"
+      TMPDIR: "/tmp2"
     volumes:
       - "../src/archivematica/src/archivematicaCommon/:/src/archivematicaCommon/"
       - "../src/archivematica/src/dashboard/:/src/dashboard/"
@@ -146,6 +147,7 @@ services:
       ARCHIVEMATICA_MCPCLIENT_MCPCLIENT_CLAMAV_CLIENT_BACKEND: "clamdscanner" # Option: clamdscanner or clamscan;
       ARCHIVEMATICA_MCPCLIENT_MCPCLIENT_PROMETHEUS_BIND_PORT: "7999"
       ARCHIVEMATICA_MCPCLIENT_MCPCLIENT_PROMETHEUS_BIND_ADDRESS: "0.0.0.0"
+      TMPDIR: "/tmp2"
 
     volumes:
       - "../src/archivematica/src/archivematicaCommon/:/src/archivematicaCommon/"
@@ -178,6 +180,8 @@ services:
       ARCHIVEMATICA_DASHBOARD_CLIENT_HOST: "mysql"
       ARCHIVEMATICA_DASHBOARD_CLIENT_DATABASE: "MCP"
       ARCHIVEMATICA_DASHBOARD_SEARCH_ENABLED: "${AM_SEARCH_ENABLED:-true}"
+      TMPDIR: "/tmp2"
     volumes:
       - "../src/archivematica/src/archivematicaCommon/:/src/archivematicaCommon/"
       - "../src/archivematica/src/dashboard/:/src/dashboard/"
@@ -200,6 +204,10 @@ services:
       SS_DB_URL: "mysql://archivematica:demo@mysql/SS"
       SS_GNUPG_HOME_PATH: "/var/archivematica/storage_service/.gnupg"
       SS_PROMETHEUS_ENABLED: "true"
+      TMPDIR: "/tmp2"
     volumes:
       - "../src/archivematica-storage-service/:/src/"
       - "../src/archivematica-sampledata/:/home/archivematica/archivematica-sampledata/:ro"
```

When we run a decently complex transfer we can look at the container directories and see results as follows: 

* archivematica-storage-service - no tmp directory content during transfer.
* archivematica-mcp-client - tmp2 used for data. 
* archivematica-dashboard - prometheus and other data in tmp2. 
* archivematica-mcp-server - tmp2 used for data.

We don't see a lot of default usage of `/tmp` but that doesn't mean different transfer types and setups won't cause more, e.g. do tools for transcription or identifying PPI require tmp directory access? What we do see with the Docker configuration I am using which seems like it would have an impact (the directories created each time if they don't exist) are (in `/tmp`):

* MCP Client container: `hsperfdata_archivematica`
* FITS container: `hsperfdata_fits`
* Elasticsearch container: `hsperfdata_elasticsearch`

hsperfdata directories seem to be associated with Java. For FITS and Elasticsearch these make sense. I'm not clear on the directory in the MCP client (`hsperfdata_archivematica`). Either way, if modifying Java output like we have Python is needed to be able to use a different TEMPDIR then [changing the way Java apps are called](https://stackoverflow.com/a/1924159 ) might be one approach? 

**Hypothesis: why Docker might help figuring out a longer term solution**

From this quick test it seems Docker can provide some helpful isolation and granularity when trying to identify today where Archivematica components are using the default temporary directory as well as identify which component. We knew it was using it for Python. If it looks like we can also exclude Java output from this default directory we might then be a step closer to enabling the configuration of a new default across the system. If other components show up traces in `/tmp` like this, then it could certainly be helpful. (It might also be just as easy to do this on a standalone AM VM :shrug: - but it will be interesting to learn).

**Comment by replaceafill** [comment]
The `TMPDIR`, `TEMP` and `TMP` environment variables can be used now to set custom paths for the temporary directory.
