### ISSUE TITLE
Problem: Archivematica doesn't record granular timestamps for original files

### ISSUE THREAD

**Issue by tw4l** [archivematica/Issues#1427]
**Please describe the problem you'd like to be solved**

I would like for Archivematica to record timestamps for files granular enough to be able to reconstruct last modified dates in a DIP to what they were in a transfer.

This is currently only possible if FITS is enabled (see #703 - much of this issue comes from a comment in that one). The `dateCreatedByApplication` value Archivematica is storing is an ISO 8601-formatted date stamp without any time information - i.e. YYYY-MM-DD ([here's the relevant bit of code](https://github.com/artefactual/archivematica/blob/3e52494735ebfeb0cabc477d95d692034f4b3142/src/MCPClient/lib/clientScripts/create_mets_v2.py#L541-L545)).

So if FITS is disabled, Archivematica does not record date information below the day. Personally, that seems like a big deal to me because in my experience and [digital archives user research](https://www.bitarchivist.net/blog/2017-05-04-usersurvey/), modified dates are often one of the first bits of information that end users look for to orient themselves with digital objects in a research setting. Some workflows like the [CCA DIP creation script in the Automation-Tools repo](https://github.com/artefactual/automation-tools/blob/master/aips/create_dip.py) even rely on having access to more granular timestamps to restore modified dates in DIPs, so that users can browse files in a local filesystem similar to how they are used to with their own files.

**Describe the solution you'd like to see implemented**

The PREMIS 3 Data Dictionary shows examples of more granular timestamps used with `dateCreatedByApplication` ([see page 79](http://www.loc.gov/standards/premis/v3/premis-3-0-final.pdf)) - e.g. "20030223T151047".

I think we should consider making the time recorded by `dateCreatedByApplication` more granular.

**Describe alternatives you've considered**

We could keep `dateCreatedByApplication` as-is and store a Unix timestamp somewhere else in the PREMIS object metadata for original files. Or rely on another service like FITS for this information.

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged
- [ ] Details about this issue have been added to the release notes

**Comment by tw4l** [comment]
Connected to #703

**Comment by sromkey** [comment]
I can see the timestamps in the METS now! e.g.
`<premis:dateCreatedByApplication>2021-06-29T19:54:50Z</premis:dateCreatedByApplication>`
