### ISSUE TITLE
Problem: Assign UUIDs to objects works on a per file basis and during reingest that means it reads the METS file (n*files) times

### ISSUE THREAD

**Issue by ross-spencer** [archivematica/Issues#1429]
**Expected behaviour**

Archivematica scripts should be optimal. 

**Current behaviour**

Reading a METS file and parsing it into memory to find a UUID and repeating it for each file in a reingest is slow. Assign UUIDs to files does this during reingest so that UUIDs are taken from the AIP correctly but it is an inefficient process. It is also possible that identifying UUIDs in the DOM are not optimized either, and so you also have the potential for lexicographically aligned UUIDs to be distributed somewhat randomly across the DOM for retrieval. Ideally they'd be collected into a hashmap like data-structure to improve how quickly they can be found. 

Drastic reductions in speed start to be noticed after a few hundred files and anecdotally I have left the process overnight on Bigserver™️ for just ~4000 files (115MB XML before parsing) before cancelling the transfer entirely to continue with other investigations. 

**Steps to reproduce**

Reingest a decent sized transfer, ~1000 objects. Potentially time it against a standard transfer. Observe how long this microservice takes. 

**Your environment (version of Archivematica, operating system, other relevant details)**

AM 1.12 and previous versions using this script. 

**Additional context**

Related to https://github.com/archivematica/Issues/issues/867 (see [first reference](https://github.com/archivematica/Issues/issues/867#issuecomment-648460483) EM and myself discovered on client site).

**Demonstration of per-file-bases during reingest**

![image](https://user-images.githubusercontent.com/1880412/109186882-5e24ca80-775f-11eb-957e-f16dd902eeea.png)

* [METS loop](https://github.com/artefactual/archivematica/blob/a31f218ceabc5bbe996775b82b9c9861b2f406d9/src/MCPClient/lib/clientScripts/assign_file_uuids.py#L158-L180).
* [Per-file entry in Workflow.json](https://github.com/artefactual/archivematica/blob/a31f218ceabc5bbe996775b82b9c9861b2f406d9/src/MCPServer/lib/assets/workflow.json#L2968-L3004).

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged (if applicable)
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by ross-spencer** [comment]
Some statistics generated over the last few days on Bigserver: 

* Skeleton TZW files (TWZ header, random content)
* 3000 files, 100MB each.
* 300GB total.
* Reingest started: 2021-02-26 11:20
* Reingest finished: 2021-03-01 22:09
* Assign UUIDs job (per batch): ~1126 seconds increasing to ~2512 seconds at the end of the process (18.7 minutes up to 41 minutes) 
* First task start: 2021-03-01 09:28:50.834023
* Last task end: 2021-03-02 01:50:26.527175 
* Total: 16 hours, 21 minutes and 36 seconds (58896 seconds) **avg. _19 seconds per file._** 

**First batch**

![image](https://user-images.githubusercontent.com/1880412/109668048-c1877180-7b3e-11eb-8969-a1b1f60c4242.png)

**Last batch**

![image](https://user-images.githubusercontent.com/1880412/109667964-ae74a180-7b3e-11eb-919c-258f619d0a86.png)

**Comment by replaceafill** [comment]
I've confirmed that the METS file is now read only once on reingest.

![Screenshot 2021-07-06 at 09-07-50 Archivematica Dashboard -](https://user-images.githubusercontent.com/560781/124624162-e1ef7180-de39-11eb-8784-b0cd872692e9.png)
