### ISSUE TITLE
Problem: AIP Encryption doesn't work on am.git (Docker Compose) deploys

### ISSUE THREAD

**Issue by jrwdunham** [archivematica/Issues#143]
**Expected behaviour**

You should be able to create a GPG encrypted space in the Storage Service on a local dev Docker Compose deploy.

**Current behaviour**

You can't. The space create request times out. This is because rng-tools is not installed so the GPG key generation takes way too long.

**Steps to reproduce**

Deploy AM/SS with am.git and attempt to create a GPG encrypted space in the SS.

**Your environment (version of Archivematica, OS version, etc)**

[am.git](https://github.com/artefactual-labs/am/tree/stable/1.7.x)

**Suggested solution**

From @sevein: "we could run rng inside a separate service and then have the device shared". See https://github.com/ewindisch/docker-rngd for a start.

**Comment by sevein** [comment]
Fixed in https://github.com/artefactual-labs/am/commit/6443fc44fb4c63f196f296d8ef6ab6a9e4f2b9a8#diff-13b3f3e76ed018a105bdeac77aa8967e.
