### ISSUE TITLE
Problem: CI builds do not provide test coverage metrics

### ISSUE THREAD

**Issue by replaceafill** [archivematica/Issues#1434]
**Expected behaviour**

The CI builds of all Archivematica related repositories provide test coverage metrics that help developers understand the impact of their code changes.

**Current behaviour**

Currently, only the [`mets-reader-writer`](https://coveralls.io/github/artefactual-labs/mets-reader-writer) repository stores and displays test coverage metrics through https://coveralls.io and [shows a coverage badge in its README file in GitHub](https://github.com/artefactual-labs/mets-reader-writer/#readme).

Alternatively, [`a3m`, `enduro`](https://codecov.io/gh/artefactual-labs/) and [`scope`](https://codecov.io/gh/CCA-Public/) use https://codecov.io and also display coverage badges in their README files.

**Steps to reproduce**

See the CI build history of all the repositories we updated to use GitHub Actions in https://github.com/archivematica/Issues/issues/1329 or check that their README files don't display test coverage badges in GitHub.

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged (if applicable)
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by sevein** [comment]
+1 from @jraddaoui and me!
