### ISSUE TITLE
archivematica-dashboard fails during compose up - repeatable 

### ISSUE THREAD

**Issue by kfiresmith** [archivematica/Issues#1444]
**Expected behaviour**
archivematica-dashboard container successfully starts

**Current behaviour**
dashboard service dies with tracebacks from urllib

**Steps to reproduce**
Pull repo+submodules that are present on the date of this submission, run through the full bootstrapping doc to build and run.

**Your environment (version of Archivematica, operating system, other relevant details)**
Latest docker-compose for ArchiveMatica as of today's date.  Running on Ubuntu 20.04 w/ current Docker, Compose, Gnu make.

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged (if applicable)
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by sevein** [comment]
@kfiresmith, could you please share the traceback? Thank you!

**Comment by sevein** [comment]
That makes sense, thank you for the clarification. We've seen a couple of community-based deployments based on containers that are publicly available in case you're interested. https://github.com/wellcomecollection/archivematica-infrastructure from Wellcome Collection using AWS, ECS and Terraform. Recently, https://github.com/piql/PiqlConnect-AM from Piql AS based on Azure and Kubernetes.
