### ISSUE TITLE
Problem: red notification badge includes active hidden packages

### ISSUE THREAD

**Issue by sevein** [archivematica/Issues#1446]
**Expected behaviour**

The notification badge (top bar red bubble) should not count pending packages that have been hidden.

**Current behaviour**

Archivematica offers the possibility to hide completed packages from the web interface to work around some performance issues generating processing status. Active packages that are awaiting user decision (e.g. Store AIP) can be hidden but the MCPServer status endpoint includes the in the total count of pending packages which is shown in the top bar red bubble badge.

**Steps to reproduce**

1. Submit a transfer using a processing configuration with some undefined processing choices,
2. Wait until the server requests a decision to be made,
3. Observe the red bubble badge, and
4. Hide the package.

The total count of pending packages remains the same, for example:

![image](https://user-images.githubusercontent.com/606459/117713359-dbe06a00-b1d5-11eb-860e-e570db4eaab3.png)

**Your environment (version of Archivematica, operating system, other relevant details)**
qa/1.x, v1.12.x and older

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged (if applicable)
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by sromkey** [comment]
Fix confirmed- I get the dialog when I try to hide an active SIP.
