### ISSUE TITLE
Problem: When I type a word with a diacritic (ex: Québec) in the copyright jurisdiction field of the rights section of the SIP info page, my SIP fails

### ISSUE THREAD

**Issue by kellyannewithane** [archivematica/Issues#1447]
**Expected behaviour**
When I type words with diacritics in the copyright jurisdiction field of the rights section of the SIP information page in the AM dashboard I expect that the METS file will be generated.

**Current behaviour**
Currently, typing the word Québec with the accent in this field means that the Job: Generate METS.xml document will fail. 
 The SIP will also then fail. 

**Steps to reproduce**
Create a transfer.  At 'reminder: add metadata if desired' job on the Ingest tab, click on the piece of paper and pen, which brings up the SIP information page.  Click on 'add' under 'rights'.  Add the word Québec (or other word with diacritics) in the Copyright Jurisdiction field.  Click on Save.  Continue processing.

**Your environment (version of Archivematica, operating system, other relevant details)**
1.12.1

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged (if applicable)
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by sromkey** [comment]
This is fixed, looks good in the METS too.
