### ISSUE TITLE
Problem: Optimize AIP download speeds from the dashboard

### ISSUE THREAD

**Issue by elizondom** [archivematica/Issues#1448]
**Please describe the problem you'd like to be solved**

Downloading AIPs from the Archival Storage tab in the dashboard interface is substantially slower than downloading them directly from the storage service API or interface. We have some fairly large AIPs that preserve AV material where the download speed issue becomes increasingly noticeable. Downloading from the storage service is roughly 30x faster.

**Describe the solution you'd like to see implemented**

Achieve better download speeds from the dashboard interface for users that typically don't require access to the storage service. I was able to achieve the same speeds as the storage service, but from the dashboard, by altering the following line of code:

https://github.com/artefactual/archivematica/blob/7ebfb2b716b7ba3bfd49528f73b7fffa2d677207/src/dashboard/src/components/helpers.py#L316

As such:

```
chunk_size = 1024 * 1024
response = StreamingHttpResponse(payload.iter_content(chunk_size))
```

**Describe alternatives you've considered**

Provide users access to the storage service interface.

**Additional context**

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged
- [ ] Details about this issue have been added to the release notes

**Comment by sromkey** [comment]
This is a little hard to QA without a direct comparison of speeds from a previous version but downloading from the dashboard seems to be working well and relatively quickly so I'll close this.
