### ISSUE TITLE
Problem: Archival Storage CSV file is not sortable by size column

### ISSUE THREAD

**Issue by tw4l** [archivematica/Issues#1450]
**Expected behaviour**

The CSV users download from the Archival Storage Service can be sorted on the size column.

**Current behaviour**

Because we're using Django's `filesizeformat` to format file sizes in the search view, the units of measure in the Archival Storage CSV are inconsistent. One row could be "312 bytes", another "2.3 GB" and another "1.7KB". This makes it impossible to sort the CSV by AIP size.

**Steps to reproduce**

- Create some AIPs
- Download a CSV from the Archival Storage tab

**Your environment (version of Archivematica, operating system, other relevant details)**

Archivematica 1.12 / `qa/1.x`

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged (if applicable)
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by tw4l** [comment]
Related to https://github.com/archivematica/Issues/issues/1213

**Comment by sromkey** [comment]
The csv now has a bytes column, enabling sorting by size.
