### ISSUE TITLE
Problem: In Python 3, replicator locations are listed as "Location object" rather than UUID in the Edit location screen

### ISSUE THREAD

**Issue by tw4l** [archivematica/Issues#1454]
**Expected behaviour**

Replicator locations continue to be listed as UUIDs in the Edit screen of an AIP Storage location.

**Current behaviour**

Enabled replicator locations are showing as "Location object" when running in Python 3.6:

![image](https://user-images.githubusercontent.com/6758804/120229384-05ac1000-c21b-11eb-8d5d-f9b60a822a34.png)

I think what's happening is that the `Location` model has a `__unicode__` method, but not a `__str__`. If I put the code in the current `__unicode__` method into a new `__str__` method, it displays as expected:

![image](https://user-images.githubusercontent.com/6758804/120229612-80752b00-c21b-11eb-9399-0a38ec7e32a5.png)

**Steps to reproduce**

1. Spin up Storage Service using Python 3.6
2. Create a Replicator location
3. Go to the Edit page for an AIP Storage location and look at listed replicators

**Your environment (version of Archivematica, operating system, other relevant details)**

Storage Service `qa/0.x`, Python 3.6

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged (if applicable)
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by replaceafill** [comment]
I confirmed that the `Replicators` list shows their UUIDs again.
