### ISSUE TITLE
Rendering of dahsboard

### ISSUE THREAD

**Issue by luisenriqueramos1977** [archivematica/Issues#1459]
Hi I did a manual installation of archivematica following the published instructions

**Expected behavi
the dashboard should looks like this:
https://www.archivematica.org/en/docs/archivematica-1.7/_images/ProcessingConfigOptions.jpg

**Current behaviour**

But it is shown with no css or js

![image](https://user-images.githubusercontent.com/48624384/122023811-2b631880-cdc8-11eb-8c17-0af21e820342.png)

**Steps to reproduce**

well, the steps I followed was the standard installation process.

**Your environment (version of Archivematica, operating system, other relevant details)**
version 1.8.1

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged (if applicable)
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by sromkey** [comment]
Hi Luis- could you please post requests for help in the User Forum: https://groups.google.com/g/archivematica rather than filing an issue? Archivematica has an active user community and you'll likely find help there. Thanks!
