### ISSUE TITLE
Elasticsearch error Exception type: <class 'elasticsearch.exceptions.TransportError'> when click in backlog

### ISSUE THREAD

**Issue by luisenriqueramos1977** [archivematica/Issues#1460]
**Expected behaviour**
When I click in "backlog" from archivematica dashboard, I should see the transfers history if any.

**Current behaviour**
however I received the following message:

**Elasticsearch error
Exception type: <class 'elasticsearch.exceptions.TransportError'>
Sorry! The page that you are trying to view is not available.
Please contact an administrator.**

**Steps to reproduce**

**Your environment (version of Archivematica, operating system, other relevant details)**
archvematica 1.8.1

I checked elasticsearch was up and running, moreover I tried to rebuild the indexes of elasticsearch, trying to find the source of the issue, and received this new error as well:

elasticsearch.exceptions.TransportError: TransportError(406, u'Content-Type header [] is not supported'

So, I wonder what could be happening here.

Luis Ramos
---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged (if applicable)
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by mamedin** [comment]
Please, can you tell us:

* Archivematica version
* Elasticsearch version
* Archivematica install method (ansible, packages)
* OS (CentOS7, Ubuntu18, Ubuntu16)
* And the output of the following command (from ES server):

curl -X GET "localhost:9200/_cat/indices?v"

**Comment by luisenriqueramos1977** [comment]
Sure:

    Archivematica version: 1.8.1
    Elasticsearch version: "number" : "6.8.16",
    Archivematica install method (ansible, packages): packages
    OS (CentOS7, Ubuntu18, Ubuntu16): ubuntu 18
    And the output of the following command (from ES server):

**curl -X GET "localhost:9200/_cat/indices?v"**

health status index         uuid                   pri rep docs.count docs.deleted store.size pri.store.size
yellow open   transfers     MCOtu9DiT2WOMMOmdHm6KQ   5   1          0            0      1.2kb          1.2kb
yellow open   transferfiles NUbj4cpSSJ2SNG2A55cUSg   5   1          0            0      1.2kb          1.2kb
yellow open   aips          IX42QI_1TD6pI5unPkfoXw   5   1          0            0      1.2kb          1.2kb
yellow open   aipfiles      5RVkniPmSaKJZ2WC3SA0zQ   5   1          0            0      1.2kb          1.2kb


Thanks in advanced


Luis Ramos

**Comment by mamedin** [comment]
Hi again,

The problem is the Elasticsearch version, you need to use Elasticsearch 1.x for AM1.8.1

**Comment by luisenriqueramos1977** [comment]
Thanks for your quick answer, this installation should be done in the virtual environment?, if so, in which one?

**Comment by mamedin** [comment]
@luisenriqueramos1977 did you try another AM version?

For AM1.8.1 (iirc) the elasticsearch indices should be:

* transfers
* aips

`transferfiles` and `aipsfiles` indices were added in 1.9.x (iirc). 

To install AM from packages (AM1.12.1) in a clean system, the easiest method is running the following script (Ubuntu 18):

https://raw.githubusercontent.com/artefactual/archivematica-docs/1.12/admin-manual/installation-setup/installation/scripts/am-bionic-deb.sh

The above script is used in the doc for the installation steps, but there's no script for AM1.8.x.

**Comment by luisenriqueramos1977** [comment]
Hi Miguel, 

As I understand I have to discard the current installation, and I must d a fresh reinstall, installing archivematica 1.12, however I still have to install AM1.12.1?, 
Could you tell me what is AM1.12.1?, because I do not know such software.

Luis

**Comment by mamedin** [comment]
Sorry, I mean Archivematica version 1.12.1 that is the last stable release.

Archivematica 1.8 is outdated (and probably you are going to have some issues with python2.7), and there are a lot of improvements on AM v1.12.1. So if you are going to install a new Archivematica server, it is better to use the last release.

Thanks.
