### ISSUE TITLE
Problem: Storage Service installation process may fail in some environments

### ISSUE THREAD

**Issue by sevein** [archivematica/Issues#1463]
**Expected behaviour**
Storage Service should not exit abruptly during the installation. It is expected to be up and running in automated deployments where Archivematica registers a pipeline.

**Current behaviour**
In Ansible, task "Create Dashboard user and register pipeline on SS" which uses the `install` command fails because Storage Service is unavailable because it exited with the following error:

```
 File "/usr/lib/archivematica/storage-service/storage_service/wsgi.py", line 38, in <module>
 startup()
 File "/usr/lib/archivematica/storage-service/common/startup.py", line 118, in startup
 and utils.get_setting(loc_info["default_setting"]) is None
 File "/usr/lib/archivematica/storage-service/common/utils.py", line 113, in get_setting
 return_value = ast.literal_eval(setting.value)
 File "/usr/lib64/python3.6/ast.py", line 85, in literal_eval
 return _convert(node_or_string)
 File "/usr/lib64/python3.6/ast.py", line 84, in _convert
 raise ValueError('malformed node or string: ' + repr(node))
 ValueError: malformed node or string: None
 [2021-06-23 07:34:49 -0700] [15002] [INFO] Worker exiting (pid: 15002)
 [2021-06-23 07:34:49 -0700] [14996] [INFO] Worker exiting (pid: 14996)
 [2021-06-23 15:34:50 +0100] [14971] [INFO] Shutting down: Master
 ```

Starting the service again is possible, and Storage Service doesn't seem to fail again. The reasons are still being investigated.

Having set up the service to restart automatically (see related issue https://github.com/artefactual-labs/ansible-archivematica-src/issues/339) should have mitigated the problem as well.

**Steps to reproduce**
1. Using Ansible, install 1.13 (QA) on RHEL, and
2. See task "Create Dashboard user and register pipeline on SS" fail.

**Your environment (version of Archivematica, operating system, other relevant details)**
Archivematica qa/1.x and Storage Service qa/0.x

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged (if applicable)
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by mamedin** [comment]
Same issue on 0.17.x and MySQL. The following branch has been created with the fix: 

https://github.com/artefactual/archivematica-storage-service/tree/dev/issue-1463-debug-startup-locations-0.17.x
