### ISSUE TITLE
Enhancement: AIP and DIP Store notifications for external systems

### ISSUE THREAD

**Issue by helrond** [archivematica/Issues#147]
**Please describe the problem you'd like to be solved.**
I would like Archivematica to send a notification whenever an AIP or a DIP are successfully stored in order to trigger actions in an external system.

**Describe the solution you'd like to see implemented.**
Preferably, Archivematica would deliver a POST request to a configurable URL which would include a payload. At minimum, that payload would include either an identifier or a URL I could use to GET a fuller representation of the package or download its content via existing endpoints. 

**Describe alternatives you've considered.**
I'm aware of the existing `post_store` callback, but as currently implemented that does not meet my needs because it sends a request for each file in an AIP, rather than once per package for either an AIP or DIP.

Polling the `/files/` endpoint works in the short term, but that approach will not scale as the number of packages stored increases. If it were possible to pass a URL parameter to this endpoint which would return only packages stored after a particular time, that might work as well.

**Additional context**
This proposed work is is part of a larger project project to build out infrastructure to support the transfer of digital records for active organizations to archival custody. More information about this project is available at https://projectelectron.rockarch.org/

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- [ ] All PRs related to this issue are properly linked 👍
- [ ] All PRs related to this issue have been merged 👍
- [ ] Test plan for this issue has been implemented and passed 👍
- [ ] Release documentation (e.g. release notes, wiki documentation, etc) regarding this issue has been written 👍

**Comment by sallain** [comment]
Added the triage-release-1.10 label as artefactual/archivematica-storage-service#449 addresses @helrond's request for a post-store callback for DIPs. This work is being done for the Canadian Centre for Architecture's SCOPE project but is widely applicable. That work is in code review right now and should be merged within the next couple of weeks, so it will be complete by the time the 1.10 release work starts.

**Comment by jraddaoui** [comment]
[The related PR](https://github.com/artefactual/archivematica-storage-service/pull/449) has been merged and this is ready for review in the qa/0.x branch from the SS.

The changes include a description of the functionality in the create/edit service callback page, but maybe we can add more information or an example for the SCOPE integration in [the current documentation](https://www.archivematica.org/en/docs/storage-service-0.14/administrators/#service-callbacks).
