### ISSUE TITLE
Problem: DIP upload fails 

### ISSUE THREAD

**Issue by corinnemrogers** [archivematica/Issues#1470]
**Expected behaviour**
DIP upload successful 

**Current behaviour**
DIP upload fails during processing and also as metadata-only upload

**Steps to reproduce**
normalize for access; select 'yes' at Upload DIP; enter slug from AtoM record

**Your environment (version of Archivematica, operating system, other relevant details)**
1.13 release candidate and AtoM 2.6.4

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged (if applicable)
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by sromkey** [comment]
Fixed!
