### ISSUE TITLE
Problem: documentation for Migrating data from SQLite to MySQL doesn't work for centos/rhel

### ISSUE THREAD

**Issue by fitnycdigitalinitiatives** [archivematica/Issues#1478]
**Version of the documentation**
Archivematica Storage Service 0.18.0

**Page (and section, if applicable) where the issue occurs**
Migrating data from SQLite to MySQL

**Description of the issue**
In the upgrading for redhat/centos to v 1.13 it links to this page to switch from SQLite to MySQL before upgrading. However, the instructions, as is, do not work and probably written for ubuntu installations. Each step list the wrong source for redhat/centos installations, `source /etc/default/archivematica-storage-service` should be, `source /etc/sysconfig/archivematica-storage-service`

Also the step 
```
su - archivematica -s /bin/bash -c "set -a -e -x; source /etc/default/archivematica-storage-service; cd /usr/lib/archivematica/storage-service/; /usr/share/archivematica/virtualenvs/archivematica-storage-service/bin/python manage.py --exclude auth.permission --exclude contenttypes --exclude=sessions.session --natural-foreign --natural-primary --indent 4 dumpdata > /tmp/datadump.json"
```
does not work. Should be something like:
```
sudo -u archivematica bash -c " \
    set -a -e -x
    source /etc/default/archivematica-storage-service || \
        source /etc/sysconfig/archivematica-storage-service \
            || (echo 'Environment file not found'; exit 1)
    cd /usr/lib/archivematica/storage-service
    /usr/share/archivematica/virtualenvs/archivematica-storage-service/bin/python manage.py dumpdata --exclude=auth.permission --exclude=contenttypes --exclude=sessions.session --natural-foreign --natural-primary --indent 4  -o /tmp/datadump.json
";
```

**Suggested fix**
Separate instructions might be needed for redhat/centos installations.

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by sevein** [comment]
Fixed! See https://www.archivematica.org/en/docs/storage-service-0.18/migration-sqlite-mysql/.

@fitnycdigitalinitiatives, thank you so much for testing the Ubuntu packages. It's been really useful.
