### ISSUE TITLE
Problem: Jhove characterization is failing due to missing FITS schema

### ISSUE THREAD

**Issue by tw4l** [archivematica/Issues#1483]
**Expected behaviour**

Jhove characterisation completes successfully.

**Current behaviour**

Characterization currently fails due to an issue with the FITS schema:

![image](https://user-images.githubusercontent.com/6758804/127045985-1b970d73-8d4f-4795-bbfd-ea72c072d8df.png)

An issue has been filed in the FITS GitHub repository: https://github.com/harvard-lts/fits/issues/220

**Steps to reproduce**

- Attempt to characterize a file with Jhove

**Your environment (version of Archivematica, operating system, other relevant details)**

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged (if applicable)
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by sromkey** [comment]
Fixed upstream.
