### ISSUE TITLE
Problem: Endpoint documentation for "create space"

### ISSUE THREAD

**Issue by jens-st** [archivematica/Issues#1485]
**Version of the documentation**
Archivematica 1.13.0 / Storage Service API

**Page (and section, if applicable) where the issue occurs**
https://www.archivematica.org/en/docs/archivematica-1.13/dev-manual/api/api-reference-storage-service/#create-space

**Description of the issue**
1. wrong endpoint path and missing "/"
2. linked [issue 36](https://github.com/archivematica/Issues/issues/36) is closed / solved
3. outdated link to Storage Service and Space documentation
4. missing basic field `staging_path`
5. required fields specific to certain space types and their spelling can only be guessed from [Access Protocols](https://www.archivematica.org/en/docs/storage-service-0.18/administrators/#access-protocols) or studied in source code

**Suggested fix**
1. change `/api/v2/pipeline/space` to `/api/v2/space/`
2. remove note regarding issue
3. update Storage Service and Space link to https://www.archivematica.org/en/docs/storage-service-0.18/administrators/#access-protocols
4. add field `staging_path` (common to all types of spaces) to table
5. add fields defined in https://github.com/artefactual/archivematica-storage-service/blob/stable/0.18.x/storage_service/locations/constants.py to endpoint description

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by fozboz** [comment]
The example for creating an S3 endpoint is missing `bucket` key in the JSON.

**Comment by sallain** [comment]
I've addressed the first three issues listed in the description.

Thanks for the report, @jens-st!

**Comment by Dhwaniartefact** [comment]
This has been fixed in https://github.com/artefactual/archivematica-docs/commit/25baad7490eca574ee3b48b62d7a372dd62c9b68
