### ISSUE TITLE
Problem: Python 2.7 compatibility layer is still present

### ISSUE THREAD

**Issue by sevein** [archivematica/Issues#1506]
**Expected behaviour**
Archivematica should stop supporting Python 2.7 since all distributions are now using Python 3.6 successfully.  All code or dependencies that exist for the purpose of being compatible with that specific version should be removed, removing unnecessary complexity and speed up continous integration builds.

**Current behaviour**
We still have a lot of code that targets Python 2.7, including some pinned dependencies, CI configurations, requirements, programming idioms, specialized imports, encoding workarounds, etc...

**Your environment (version of Archivematica, operating system, other relevant details)**
Archivematica 1.13.x

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged (if applicable)
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by replaceafill** [comment]
Verified the Python `requirement` files of the [`archivematica`](https://github.com/artefactual/archivematica/blob/179247f9e5508defd563e4eae3c73ea8e8b674f3/requirements.txt) and [`archivematica-storage-service`](https://github.com/artefactual/archivematica-storage-service/tree/f04eb8b24a8b03e541b8c8fda00a7b7237e92f95/requirements) repositories. They don't contain Python 2.7 specific dependencies anymore. Also `pyupgrade` has been added to the `pre-commit` configuration of both repositories to upgrade the syntax to Python 3.6.
