### ISSUE TITLE
Problem: API endpoint for approving reingests broke during the JSON-encoded workflow refactoring

### ISSUE THREAD

**Issue by replaceafill** [archivematica/Issues#1510]
**Expected behaviour**

The `api/ingest/reingest/approve` API endpoint can be used to approve metadata-only and partial reingests.

**Current behaviour**

Two issues were introduced during https://github.com/artefactual/archivematica/pull/1251:

1. The dashboard MCP client was refactored to accept the Django user during initialization so it's not passed in each RPC method call. However [the extra parameter is still present in the `reingest_approve` view](https://github.com/artefactual/archivematica/blob/bf635157bb829124104b7d0d9278a579c61c261d/src/dashboard/src/components/api/views.py#L564) which produces:

   ```
   archivematica-dashboard_1        | ERROR     2021-11-13 01:07:55  archivematica.dashboard:views:reingest_approve:510:  Unable to approve the partial reingest. approve_partial_reingest() takes exactly 2 arguments (3 given) (sip_uuid=6c2d4191-6fff-4413-bc12-de2ad71b83cd)
   ```

2. Even if  the previous issue is addressed, the `RPCServer.APPROVE_AIP_REINGEST_CHAIN_ID` attribute introduced for looking the right workflow chain has a link UUID when the workflow expects a chain UUID which produces:

   ```
   archivematica-dashboard_1        | ERROR     2021-11-13 01:09:28  archivematica.dashboard:views:reingest_approve:510:  Unable to approve the partial reingest. Could not find choice for approve AIP reingest (sip_uuid=6c2d4191-6fff-4413-bc12-de2ad71b83cd)
   ```

**Steps to reproduce**

1. Start a metadata only reingest.
2. Once the `Job: Approve AIP reingest` prompts for approval call the `api/ingest/reingest/approve` API endpoint passing the SIP UUID as the `uuid` parameter. Also note that the endpoint expects an `application/x-www-form-urlencoded` request. Here's a sample call using [httpie](https://httpie.io/):

   ```
   http --pretty=format --form \
       POST 127.0.0.1:62080/api/ingest/reingest/approve/ \
       "Authorization: ApiKey test:test" \
       "uuid"="6c2d4191-6fff-4413-bc12-de2ad71b83cd"
   ```
3. The reingest will not be approved and you will have a `approve_partial_reingest() takes exactly 2 arguments` error in the dashboard logs.

**Your environment (version of Archivematica, operating system, other relevant details)**

https://github.com/artefactual/archivematica/commit/bf635157bb829124104b7d0d9278a579c61c261d and https://github.com/artefactual/archivematica-storage-service/commit/85f77d18391cdd89b228b6b90e38ab91e41b170c

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged (if applicable)
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by Dhwaniartefact** [comment]
Verified this in development by calling api/ingest/reingest/approve API endpoint during "job: Approve AIP reingest" to approve metadata-only and partial reingests.
