### ISSUE TITLE
Problem: symlinked storage locations no longer work

### ISSUE THREAD

**Issue by fozboz** [archivematica/Issues#1512]
**Expected behaviour**

When I "Browse" a filesystem-based storage location, I should see a list of all the files in that directory.

**Current behaviour**

If the directory is a symlink, no file listing is displayed and there does not appear to be any error in the logs. If I change the path to the "real" path, it works fine.

**Steps to reproduce**

- Symlink a directory in the OS
- Create a storage location using the symlink path
- Attempt to browse the location in the UI

**Your environment (version of Archivematica, operating system, other relevant details)**

CentOS 7, v1.13.1
This was not an issue with v1.12

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged (if applicable)
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by mamedin** [comment]
@fozboz it seems a permission issue. Please, can you try in AM server?

```
sudo su - archivematica -s /bin/bash
ls SYMLINKED_DIRECTORY
```

This way we ensure that the `archivematica` user can access the files in the directory.

**Comment by fozboz** [comment]
Archivematica user is able to access the symlinked paths.

**Comment by replaceafill** [comment]
This will be tracked in https://github.com/archivematica/Issues/issues/1515
