### ISSUE TITLE
Problem: metadata import results in null values in METS for files where metadata field is not used

### ISSUE THREAD

**Issue by jfcarrano** [archivematica/Issues#1517]
**Expected behaviour**
Metadata imported via an external file (CSV, JSON) with metadata fields only used for specific files will create metadata in the resulting METS for those specific files and not other files in the AIP where a metadata field was not used.

**Current behaviour**
Metadata imported via an external file (CSV, JSON) with metadata fields only used for specific files will create metadata in the resulting METS for all files, including files in the AIP where a field was not used. The resulting metadata field is blank for the files where the metadata field was not used. For example `<dc.creator></dc.creator>`

**Steps to reproduce**
For CSV:

1. Create a `metadata.csv` file for the files in a transfer, list at least 2 files under the "filename" column. 
2. Add an arbitrary field such as dc.creator. Put a value in dc.creator field for the first file but leave the field blank for the second file.
3. Run the SIP through Archivematica with the CSV included in the proper location or upload it via the dashboard. 
4. Once processed, look at the METS in the resulting AIP. `dc.creator` will be present in the dmd_sec for both files, the first file with the value provided in the CSV, the second file will be null, `<dc.creator></dc.creator>`

For JSON:

1. Create a `metadata.json` file for the files in a transfer, list at least 2 files as objects in the JSON. 
2. Add an arbitrary field such as `dc.creator` to the JSON object for the first file. 
3. Run the SIP through Archivematica and upload the JSON via the dashboard. 
4. Once processed, look at the METS in the resulting AIP. `dc.creator` will be present in the dmd_sec for both files, the first file with the value provided in the JSON, the second file will be null, `<dc.creator></dc.creator>`

**Your environment (version of Archivematica, operating system, other relevant details)**
Archivematica 1.13.2

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged (if applicable)
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by sromkey** [comment]
Another way that we see this behaviour is during reingest- if you replace a metadata file with another the empty elements can appear where they didn't on initial ingest.

**Comment by sromkey** [comment]
Tested using DemoTransferCSV which does not have all values filled out for every object and this appears to be fixed.
