### ISSUE TITLE
Problem: BIB files are missing

### ISSUE THREAD

**Issue by joel-simpson** [archivematica/Issues#152]
**Expected behaviour**
When Archivematica is configured to connect to a dataverse repository and the Transfer type is set to Dataverse, a Dataverse METS is created (by Archivematica) that describes that dataset as it was initially retrieved. This is particularly useful when a dataset includes tabular data, because the dataverse application creates metadata and derivative files, and we want to describe these as such in the final AIP. The Dataverse METS helps to do this by describing the files received and their relationshiops (which are originals, derivatives, metadata etc.). 

The Dataverse METS should describe ALL files provided by Dataverse and should NOT describe any files NOT provided by dataverse.

**Current behaviour**
The Dataverse METS describes two files (.rdata files) that were not actually provided by Dataverse. These files are included in the dataset.json file that dataverse provides (so essentially the problem is that dataverse is describing two files that it isn't actually providing). 

The Dataverse METS is missing any description of two other files that were provided (.bib files). 

Details of all files and their respective METS entries are [tracked in this spreadsheet](https://docs.google.com/spreadsheets/d/1te_JIVyJ_P0MwSQ-2Ao9bSsUgQz3HiuLzHqAf7LIYEc/edit#gid=1537460364). 

Again, the overall issue is that the dataverse manifest (dataset.json) is not accurate based on what is actually retreived. We should confirm that we are in fact retrieving the dataset correctly, and whether there are known issues logged in dataverse for this. 

However, this highlights the challenge of our current approach - which is to create a Dataverse METS based purely on the dataset.json file, not by interrogating the actual files provided. Assuming the dataverse issue can be fixed by that team, one option might be to create a new microservice that validates the dataset.json file against actual files returned (say, in "Verify Transfer Compliance"), and throw an error if the two do not match. 

(Note also this issue only appears to occur for datasets with 'bundles' - where tabular data has resulted in dataverse creating derivatives and metadata files. For simple datasets like the images dataset we don't see any issues)

**Steps to reproduce**
configure AM to talk to dataverse and select the dataset "Canadian Relocations"... 

**Your environment (version of Archivematica, OS version, etc)**
Testing on http://ocul-am-dv.dev.archivematica.org:62080 
(currently running the dataverse dev branches) 

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Release documentation (e.g. release notes, wiki documentation, etc) regarding this issue has been written 👍

**Comment by joel-simpson** [comment]
Discussed this issue with Grant at Scholar's Portal. Grant pointed out that the Rdata files are NOT described in the dataset.json file provided by Dataverse. In fact none of the metadata / citatation files are. 

My assertion (or assumption) that we are creating the Dataverse METs purely from the dataset.json seems to be incorrect. 
so it doesn't appear to be a Dataverse issue... 
the RData files are not provided by Dataverse, and yet somehow they get described in the Dataverse METS. 
the .bib files are provided by Dataverse, and while not in the dataverse.json, neither are any of the other metadata / citation files. So this appears to be a gap in what we are entering into Dataverse METS.

**Comment by joel-simpson** [comment]
My hunch here is that we are creating METS entries for files that we EXPECT to be in the bundle, not based on what is actually provided in the bundle. https://github.com/artefactual/archivematica/blob/dev/issue-1147-minimal-dataverse-transfer-type/src/MCPClient/lib/clientScripts/convert_dataverse_structure.py#L158

Possibly what dataverse returns for a bundle has changed? I've looked through the issues / release notes and couldn't find anything. I think a more robust solution would be to ensure that we are cataloguing based on the actual files provided.

**Comment by jrwdunham** [comment]
@joel-simpson I think I've discovered part of the problem. I've created a Dataverse-type transfer from the dataset "880 (Canadian Relocation Cases: ...)" and I see that in the Transfer METS (which is located within the AIP at a path like `data/objects/metadata/transfers/<TRANSFER-NAME>-<TRANSFER-UUID>/METS.xml`) there is a structure like the following:

    <mets:structMap ID="structMap_1" LABEL="Archivematica default" TYPE="physical">
      <mets:div TYPE="Directory" LABEL="Canadian Relocation Cases: Heading Towards Guidelines, 2011 [test]" DMDID="dmdSec_274934 dmdSec_172175">
        <mets:div TYPE="Directory" LABEL="relocation2011">
          <mets:div TYPE="Item" LABEL="relocation2011.RData">

Yet there is no `relocation2011.RData` file in the AIP.

The problem seems to be coming from this line: https://github.com/artefactual/archivematica/pull/1242/files#diff-cd921d566b4b0c45fc437feb8dea55f9R196. In the `dataset.json` file there are objects whose `label` attribute has a value that has a file extension `.tab`. This causes the `convert_dataverse_structure.py::create_bundle` function to be called and when the value of `originalFormatLabel` is *not* `'R Data'`, then we are asserting (via the METS) that there is a file `relocation2011/relocation2011.RData` that is a derivative of the original `.tab` file.

I do not know what motivated this logic originally. Maybe you or @ross-spencer does. At this point, without understanding the motivation, I am hesitant to propose a fix.

**Comment by jrwdunham** [comment]
As for the .bib citation files, you can see from https://github.com/artefactual/archivematica/blob/7fcdd55a4653dde692634b77e0edf87a3fec8322/src/MCPClient/lib/clientScripts/convert_dataverse_structure.py#L232 that we are just assuming (for the `.tab` files) the presence of `citation-endnote.xml` and `citation-ris.ris` citation files, but not `citation-bib.bib` files.

**Comment by joel-simpson** [comment]
Grant noted that the rdata files should be returned by dataverse. I just tested and it currently isn't, so will confirm. But given this, I think the focus of this issue for now should simply be to fix the missing .bib entries; and assume that with the dataverse fix we will get the rdata files. 
We can discuss a longer term solution separately for making the process more robust to errors.

**Comment by ross-spencer** [comment]
I downloaded the dataset `2014 National Survey of Canadian Community Pharmacists: Use of Digital Health Technologies in Practice` and have the tree:

**NB.** The bundle is https://demodv.scholarsportal.info/api/access/datafile/bundle/1234
```
root@artefactual:/tmp/am-pipeline-data/watchedDirectories/activeTransfers/dataverseTransfer/pharma# tree
.
├── CHI Infoway Pharmacists 2014(DataVerse)citation-bib.bib
├── CHI Infoway Pharmacists 2014(DataVerse)citation-endnote.xml
├── CHI Infoway Pharmacists 2014(DataVerse)citation-ris.ris
├── CHI Infoway Pharmacists 2014(DataVerse)-ddi.xml
├── CHI Infoway Pharmacists 2014(DataVerse).RData
├── CHI Infoway Pharmacists 2014(DataVerse).sav
├── CHI Infoway Pharmacists 2014(DataVerse).tab
└── metadata
    ├── agents.json
    └── dataset.json
```

The original should be: `CHI Infoway Pharmacists 2014(DataVerse).sav`, `md5:6a0b47cd70bf8140348a33bce9e2e6f3`

The checksums are:
```
dafeb916739864014f6e868c61d32160  CHI_Infoway_Pharmacists_2014(DataVerse)citation-bib.bib
fb132736a7bd6504a168d77249a3649a  CHI_Infoway_Pharmacists_2014(DataVerse)citation-endnote.xml
f8902b77289d0792bd67139b4e61d6bf  CHI_Infoway_Pharmacists_2014(DataVerse)citation-ris.ris
66b77c16231deee5f88d14de8b7b8398  CHI_Infoway_Pharmacists_2014(DataVerse)-ddi.xml
c7c989a1ba359df9b121b47ae9665a9e  CHI_Infoway_Pharmacists_2014(DataVerse).RData
6a0b47cd70bf8140348a33bce9e2e6f3  CHI_Infoway_Pharmacists_2014(DataVerse).sav
026a3d29420fa3f3aedef2451e561201  CHI_Infoway_Pharmacists_2014(DataVerse).tab
```
On top of the original `.sav`file, we are seeing six other files, when the Dataverse docs describe only five that should be associated with the Bundle. I have logged this here https://github.com/IQSS/dataverse/issues/5081 and we should update the Dataverse docs when there is confirmation and an opportunity to do so.

**Comment by ross-spencer** [comment]
For reference, before we fix this, the metadata currently shows the original okay, and doesn't show the bibtext file:
```
    <mets:fileGrp USE="original">
      <mets:file ID="file-d446840f-ecf8-440a-8dc4-b636fdc5ad7c" GROUPID="Group-d446840f-ecf8-440a-8dc4-b636fdc5ad7c" CHECKSUM="6a0b47cd70bf8140348a33bce9e2e6f3" CHECKSUMTYPE="MD5">
        <mets:FLocat xlink:href="CHI Infoway Pharmacists 2014(DataVerse)/CHI Infoway Pharmacists 2014(DataVerse).sav" LOCTYPE="OTHER" OTHERLOCTYPE="SYSTEM"/>
      </mets:file>
    </mets:fileGrp>
  </mets:fileSec>
  <mets:structMap ID="structMap_1" LABEL="Archivematica default" TYPE="physical">
    <mets:div TYPE="Directory" LABEL="2014 National Survey of Canadian Community Pharmacists: Use of Digital Health Technologies in Practice" DMDID="dmdSec_834995 dmdSec_465726">
      <mets:div TYPE="Directory" LABEL="CHI Infoway Pharmacists 2014(DataVerse)">
        <mets:div TYPE="Item" LABEL="CHI Infoway Pharmacists 2014(DataVerse).sav">
          <mets:fptr FILEID="file-d446840f-ecf8-440a-8dc4-b636fdc5ad7c"/>
        </mets:div>
        <mets:div TYPE="Item" LABEL="CHI Infoway Pharmacists 2014(DataVerse).RData">
          <mets:fptr FILEID="file-a27ba781-2e29-44c5-bcbf-4013f5ca0c98"/>
        </mets:div>
        <mets:div TYPE="Item" LABEL="CHI Infoway Pharmacists 2014(DataVerse).tab" DMDID="dmdSec_277452">
          <mets:fptr FILEID="file-f8bcae7f-419a-48e1-b3c2-47f5c77afea7"/>
        </mets:div>
        <mets:div TYPE="Item" LABEL="CHI Infoway Pharmacists 2014(DataVerse)-ddi.xml">
          <mets:fptr FILEID="file-06b05cea-93ad-483b-8af8-9767abe5ff30"/>
        </mets:div>
        <mets:div TYPE="Item" LABEL="CHI Infoway Pharmacists 2014(DataVerse)citation-endnote.xml">
          <mets:fptr FILEID="file-f4e5c1ea-91e5-4ee4-8378-9e62a5817bb1"/>
        </mets:div>
        <mets:div TYPE="Item" LABEL="CHI Infoway Pharmacists 2014(DataVerse)citation-ris.ris">
          <mets:fptr FILEID="file-468be438-fa02-4a16-bc53-2a080bb64a2e"/>
        </mets:div>
      </mets:div>
      <mets:div TYPE="Directory" LABEL="metadata">
        <mets:div TYPE="Item" LABEL="dataset.json">
          <mets:fptr FILEID="file-e5ba308c-0bdc-4c1f-847d-b471f2640633"/>
        </mets:div>
      </mets:div>
    </mets:div>
  </mets:structMap>
```

**Comment by ross-spencer** [comment]
Example, post-fix with the bibtext added:
```
    <mets:fileGrp USE="original">
      <mets:file ID="file-4505b164-dc8a-4a4d-a7db-f8fca2cbf205" GROUPID="Group-4505b164-dc8a-4a4d-a7db-f8fca2cbf205" CHECKSUM="6a0b47cd70bf8140348a33bce9e2e6f3" CHECKSUMTYPE="MD5">
        <mets:FLocat xlink:href="CHI Infoway Pharmacists 2014(DataVerse)/CHI Infoway Pharmacists 2014(DataVerse).sav" LOCTYPE="OTHER" OTHERLOCTYPE="SYSTEM"/>
      </mets:file>
    </mets:fileGrp>
  </mets:fileSec>
  <mets:structMap ID="structMap_1" LABEL="Archivematica default" TYPE="physical">
    <mets:div TYPE="Directory" LABEL="2014 National Survey of Canadian Community Pharmacists: Use of Digital Health Technologies in Practice" DMDID="dmdSec_459529 dmdSec_885031">
      <mets:div TYPE="Directory" LABEL="CHI Infoway Pharmacists 2014(DataVerse)">
        <mets:div TYPE="Item" LABEL="CHI Infoway Pharmacists 2014(DataVerse).sav">
          <mets:fptr FILEID="file-4505b164-dc8a-4a4d-a7db-f8fca2cbf205"/>
        </mets:div>
        <mets:div TYPE="Item" LABEL="CHI Infoway Pharmacists 2014(DataVerse).RData">
          <mets:fptr FILEID="file-5513efb4-54c4-42b2-873c-6f42e22d7fa4"/>
        </mets:div>
        <mets:div TYPE="Item" LABEL="CHI Infoway Pharmacists 2014(DataVerse).tab" DMDID="dmdSec_152417">
          <mets:fptr FILEID="file-fda97e77-867e-4917-8b6d-7601931bf702"/>
        </mets:div>
        <mets:div TYPE="Item" LABEL="CHI Infoway Pharmacists 2014(DataVerse)-ddi.xml">
          <mets:fptr FILEID="file-19c09acc-d013-48ee-9d4f-4160a376ff9a"/>
        </mets:div>
        <mets:div TYPE="Item" LABEL="CHI Infoway Pharmacists 2014(DataVerse)citation-endnote.xml">
          <mets:fptr FILEID="file-0d2e912f-6d53-4165-9681-30693afde3b6"/>
        </mets:div>
        <mets:div TYPE="Item" LABEL="CHI Infoway Pharmacists 2014(DataVerse)citation-ris.ris">
          <mets:fptr FILEID="file-1c1a70ba-32a1-4a8d-b5b6-70aeebb8a1e2"/>
        </mets:div>
        <mets:div TYPE="Item" LABEL="CHI Infoway Pharmacists 2014(DataVerse)citation-bib.bib">
          <mets:fptr FILEID="file-e7296bb3-3b4b-4abf-989e-a20e4dbce38a"/>
        </mets:div>
      </mets:div>
      <mets:div TYPE="Directory" LABEL="metadata">
        <mets:div TYPE="Item" LABEL="dataset.json">
          <mets:fptr FILEID="file-6bb01966-0d5b-4660-9aea-1761bed8c818"/>
        </mets:div>
      </mets:div>
    </mets:div>
  </mets:structMap>
```

**Comment by peterVG** [comment]
Tested on AM.18.x.qa Centos with successful generation of BIB Metadata:

![screen shot 2018-10-17 at 14 52 35](https://user-images.githubusercontent.com/672121/47118627-b60ca780-d21c-11e8-8cc2-86366fcdcc51.png)

as well as *.bib files generated during ingest:

![screen shot 2018-10-17 at 13 11 26](https://user-images.githubusercontent.com/672121/47118703-0126ba80-d21d-11e8-8e3f-8f966b9729b3.png)


NB. to avoid a Parse Dataverse XML error, "Delete packages after extraction" in "Processing configuration" > default > edit: must be set to "No" in order to avoid Parse Dataverse XML errors during transfer and ingest of Dataverse packages.
