### ISSUE TITLE
Problem: some parts of the Elasticsearch indexes are hard to navigate

### ISSUE THREAD

**Issue by jraddaoui** [archivematica/Issues#1524]
**Please describe the problem you'd like to be solved**
In order to index XML contents in Elasticsearch (AMD and DMD sections from the METS file), Archivematica transforms the XML tags to avoid mismatches in the mapping when indexing the same tag as a string field (when the XML contains only text) or as a dict/multi-field (when the XML contains other tags). Additionally, the process also makes differentiation between lists (multiple XML sub-elements with the same tag) and single string values (a single tag), something that is not necessary in Elasticsearch and that complicates targeting those string fields.

Currently, from [this XML](https://gist.github.com/jraddaoui/49c697d92a3a304f567ef29b1bc9d817#file-1_example-xml) Archivematica generates [this Elasticsearch document part](https://gist.github.com/jraddaoui/49c697d92a3a304f567ef29b1bc9d817#file-2_previous_index-json).

The existing normalization names dict fields always as "tag_dict_list" even if there was only one value and it names string fields as "tag" (for a single value) or "tag_str_list" (for multiple values).

**Describe the solution you'd like to see implemented**
Elasticsearch fields accept a single value or a list of values, so there is no need to make a distinction for lists, only between strings and dictionaries. From [the same XML content](https://gist.github.com/jraddaoui/49c697d92a3a304f567ef29b1bc9d817#file-1_example-xml), Archivematica could generate [this Elasticsearch document part](https://gist.github.com/jraddaoui/49c697d92a3a304f567ef29b1bc9d817#file-3_new_index-json), which is enough to avoid the mapping mismatch, it's easier to navigate and also simplifies the transformation process.

Due to the existing normalization these changes won't introduce conflicts in existing indexes, but it will modify the expected mapping for the indexed AMD and DMD sections (if someone is expecting something from an undocumented dynamic mapping).

**Describe alternatives you've considered**
Keep it as it is.

**Additional context**
AM qa/1.x (8e379f9), Docker env. But it has been like this since we index the AMD sections.

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged
- [ ] Details about this issue have been added to the release notes

**Comment by jraddaoui** [comment]
While this won't produce mismatches in existing indexes, @replaceafill noticed that it may create two different mapping structures for the same XML contents where the previous transformation already took place. That will be only the `METS.dmdSec` field (which will be removed after https://github.com/artefactual/archivematica/pull/1787 in favor of the existing `transferMetadata` to avoid duplication) and the `METS.amdSec`, both from the `aipfiles` index.

For advanced users targeting those fields directly in Elasticsearch this could be an issue. As possible solutions:
- Re-indexing will use the new mapping structure for all documents, but that's not always possible.
- Update the Elasticsearch interactions to target both structures.
- Update existing indexes with a Painless script (to be executed as part of the AM upgrade process).

All of them will require actions from those advanced users to use the new mapping (or both) and, given that it is an undocumented dynamic mapping for now, I think we can skip the Painless script in this case.

**Comment by replaceafill** [comment]
Related to https://github.com/archivematica/Issues/issues/1531
