### ISSUE TITLE
Problem: staging_path is not returned when using the space API

### ISSUE THREAD

**Issue by fozboz** [archivematica/Issues#1528]
**Expected behaviour**

Run a GET on the space API should return the space's `staging_path`.

**Current behaviour**

`staging_path` is not presented in the returned JSON string.

**Steps to reproduce**

Run e.g. `curl -H "Authorization: ApiKey user:yourkey" "localhost:8000/api/v2/space/"` and observe that `staging_path` is not in the returned JSON string.

**Your environment (version of Archivematica, operating system, other relevant details)**

Storage Service version 0.18.1
Ubuntu 18.04
Installed using the Ansible playbook.

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged (if applicable)
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by replaceafill** [comment]
Verified this by using `curl` to fetch the spaces of the Storage Service and confirming the `staging_path` is in the response:

```bash
curl -H "Authorization: ApiKey test:test" "http://localhost:62081/api/v2/space/" | jq
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   437  100   437    0     0    933      0 --:--:-- --:--:-- --:--:--   935
{
  "meta": {
    "limit": 20,
    "next": null,
    "offset": 0,
    "previous": null,
    "total_count": 1
  },
  "objects": [
    {
      "access_protocol": "FS",
      "id": 1,
      "last_verified": null,
      "path": "/",
      "resource_uri": "/api/v2/space/205d1144-29f6-4d2f-9366-edc83748e568/",
      "size": null,
      "space": "205d1144-29f6-4d2f-9366-edc83748e568",
      "staging_path": "/var/archivematica/storage_service",
      "used": 0,
      "uuid": "205d1144-29f6-4d2f-9366-edc83748e568",
      "verified": false
    }
  ]
}
```
