### ISSUE TITLE
Problem: aip ingest date is not easy to find when using indexless mode

### ISSUE THREAD

**Issue by scollazo** [archivematica/Issues#1529]
**Please describe the problem you'd like to be solved**
I want to be able to know the size of an AIP, or the aggregate size of a list of AIPs (let's say, the ones ingested between two dates)

**Describe the solution you'd like to see implemented**

Add a new field to storage service locations_package that stores the AIP ingest date

**Describe alternatives you've considered**

- Retrieve such info from elasticsearch (not an option if not using the index)
- Parse archivematica logs to identify the date of transfers

**Additional context**
This feature would be useful for creating reports showing how many aips/gigabytes have been ingested in a period of time

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged
- [ ] Details about this issue have been added to the release notes

**Comment by tw4l** [comment]
Related to https://github.com/archivematica/Issues/issues/731 - if we add accurate stored dates the Storage Service, we could use those in the Archival Storage tab instead of the current potentially inaccurate one

**Comment by tw4l** [comment]
Milestoned for 1.14 after discussing with @sromkey

**Comment by replaceafill** [comment]
Verified this by creating a compressed AIP and an uncompressed AIP and checking their `stored_date` column in the Storage Service database being populated correctly.
