### ISSUE TITLE
Problem: Unclear sentence in admin documentation - section "Archivematica configuration"

### ISSUE THREAD

**Issue by BPeuch** [archivematica/Issues#1534]
**Version of the documentation**
0.18

**Page (and section, if applicable) where the issue occurs**
[Administering the Storage Service](https://github.com/artefactual/archivematica-storage-service-docs/blob/0.18/administrators.rst)

**Description of the issue**
There is an unclear sentence in the [Archivematica configuration](https://github.com/artefactual/archivematica-storage-service-docs/blob/0.18/administrators.rst#archivematica-configuration) section:

> The **Register this pipeline & set up transfer source and AIP storage locations** option will only attempt to register a new Pipeline with the Storage Service, and _will not error if not Storage Service_ can be found.

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by sallain** [comment]
Thank you @BPeuch! I'll get that fixed.

**Comment by sallain** [comment]
Resolved by artefactual/archivematica-storage-service-docs#51
