### ISSUE TITLE
Problem: metadata updates of DMD sections are not easy to understand

### ISSUE THREAD

**Issue by jraddaoui** [archivematica/Issues#1537]
**Expected behaviour**
With the addition of more DMD sections coming from XML metadata files on ingest and re-ingest (see https://github.com/archivematica/Issues/issues/1531) we need a better way to relate the DMD sections of the same metadata type between them and indicate the current status of all the sections.

Proposed solutions:
- Add `GROUPID` attribute to relate the DMD sections of the same metadata type.
- Include `CREATED` attribute in all cases.
- Modify existing `STATUS` attribute to use the following values:
  - `original`: added on initial ingest.
  - `original-superseded`: added on initial ingest and updated on a re-ingest.
  - `update`: added on re-ingest.
  - `update-superseded`: added on re-ingest and updated on another re-ingest.
  - `deleted`: metadata removed on re-ingest.
  - `deleted-superseded`: metadata removed on re-ingest and re-added on another re-ingest.

**Current behaviour**
- We don't add `STATUS` nor `CREATED` attribute to DMD sections on initial ingests.
- On re-ingest, if there are updates to the DMD section a new one is created with status `updated` and the previous one gets an `original` status.
- Following re-ingest with updates keep adding new DMD sections with status `updated`.
- When the metadata is deleted, a new empty DMD section is added with `deleted` status.
- It's not clear what could be the behavior when CUSTOM and DC metadata are mixed together, and when metadata comes from the GUI and the metadata CSV file at the same time, but those cases should also be considered by this changes.

**Steps to reproduce**
- Add metadata through the GUI to a normal ingest.
- Update or delete that metadata on a following metadata only partial re-ingest.
- Check DMD sections attributes on the AIP's METS file.

**Your environment (version of Archivematica, operating system, other relevant details)**
Docker, qa/1,x. 

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged (if applicable)
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by replaceafill** [comment]
Related to https://github.com/archivematica/Issues/issues/1531
