### ISSUE TITLE
Problem: typo in the "Administration" section

### ISSUE THREAD

**Issue by BPeuch** [archivematica/Issues#1539]
**Version of the documentation**
0.18

**Page (and section, if applicable) where the issue occurs**
[Administering the Storage Service](https://github.com/artefactual/archivematica-storage-service-docs/blob/0.18/administrators.rst) > [Users](https://www.archivematica.org/en/docs/storage-service-0.18/administrators/#users) 

**Description of the issue**
Typo:
The Storage Service has two types of users: administrative users, and regular users. The only distinction between the two types is for email notifications; administrators will be notified by email when special events occur, while regular users will not. Only registered users can **long** into the Storage Service.

**Suggested fix**
The Storage Service has two types of users: administrative users, and regular users. The only distinction between the two types is for email notifications; administrators will be notified by email when special events occur, while regular users will not. Only registered users can *log* into the Storage Service.

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by replaceafill** [comment]
This has been fixed in https://github.com/artefactual/archivematica-storage-service-docs/commit/05a35cd0963e4d716eeb148e6db2060eb94a8545
