### ISSUE TITLE
PROBLEM: Typo in "recover AIP" request API documentation

### ISSUE THREAD

**Issue by sarah-mason** [archivematica/Issues#1543]
**Version of the documentation**
1.13

**Page (and section, if applicable) where the issue occurs**
https://www.archivematica.org/en/docs/archivematica-1.13/dev-manual/api/api-reference-storage-service/#recover-aip-request

**Description of the issue**
There is a small typo in the API curl request for _Recover AIP request_ where a `\` is missing after `--request POST`:
```
curl \
    --location \
    --request POST
...
        'http://test.archivematica.net:8000/api/v2/file/2cd0575f-5e0b-4d2f-bd00-7e0b254e0802/recover_aip/'
```
Without it, the request will not work properly.

**Suggested fix**
Add the `\` to the call so it looks like this:
```
curl \
    --location \
    --request POST \
...
        'http://test.archivematica.net:8000/api/v2/file/2cd0575f-5e0b-4d2f-bd00-7e0b254e0802/recover_aip/'
```

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by sallain** [comment]
Fixed! Thanks @sarah-mason!
