### ISSUE TITLE
Problem: Missing word in the Quick-Start Guide

### ISSUE THREAD

**Issue by BPeuch** [archivematica/Issues#1544]
**Version of the documentation**
1.13.2

**Page (and section, if applicable) where the issue occurs**
[Archivematica Quick-Start Guide](https://www.archivematica.org/en/docs/archivematica-1.13/getting-started/quick-start/quick-start) > [Review AIPs and DIPs](https://www.archivematica.org/en/docs/archivematica-1.13/getting-started/quick-start/quick-start/#task-4-review-aips-and-dips)

**Description of the issue**
Missing word:
"You will _need to a program_ capable of opening 7zip files installed on your computer."

**Suggested fix**
"You will need to **use** a program capable of opening 7zip files installed on your computer."

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by sallain** [comment]
Fixed! Thanks so much for catching this, @BPeuch!
