### ISSUE TITLE
Problem: Move AIP call does not work

### ISSUE THREAD

**Issue by fozboz** [archivematica/Issues#1545]
**Expected behaviour**

Making a Move AIP call to the API moves the AIP.

**Current behaviour**

The AIP does not move. It gets stuck in "MOVING" state.

**Steps to reproduce**

Make a call to the Move API.

```
$ curl -H "Authorization: ApiKey test:test" -d "location_uuid=c5cbd502-d4bc-4f45-a588-5dddcd387c70" "http://127.0.0.1:62081/api/v2/file/1009ce6e-3c46-477d-909d-c94f83af5152/move/"
```

Check the status of the AIP and observe that it is in MOVING state and never gets moved.

```
$ curl -H "Authorization: ApiKey test:test" "http://127.0.0.1:62081/api/v2/file/1d892fb2-bb00-44bc-9ad6-563d09eb6b2f/"                                         
{"current_full_path": "/var/archivematica/sharedDirectory/www/AIPsStore/1d89/2fb2/bb00/44bc/9ad6/563d/09eb/6b2f/ZippedBag-1d892fb2-bb00-44bc-9ad6-563d09eb6b2f.7z", "current_location": "/api/v2/location/14d2715b-7db5-4587-a611-9588ea1a1874/", "current_path": "1d89/2fb2/bb00/44bc/9ad6/563d/09eb/6b2f/ZippedBag-1d892fb2-bb00-44bc-9ad6-563d09eb6b2f.7z", "encrypted": false, "misc_attributes": {}, "origin_pipeline": "/api/v2/pipeline/2a63a4ff-881b-4507-872c-1e630cecc105/", "package_type": "AIP", "related_packages": [], "replicas": [], "replicated_package": null, "resource_uri": "/api/v2/file/1d892fb2-bb00-44bc-9ad6-563d09eb6b2f/", "size": 5124842, "status": "MOVING", "uuid": "1d892fb2-bb00-44bc-9ad6-563d09eb6b2f"}
```

Also observe the following error in the logs.

```
Traceback (most recent call last):
  File "/usr/lib/archivematica/storage-service/locations/models/async_manager.py", line 139, in wrapper
    value = task_fn(*args, **kwargs)
  File "/usr/lib/archivematica/storage-service/locations/api/resources.py", line 1722, in task
    package.move(location)
  File "/usr/lib/archivematica/storage-service/locations/models/package.py", line 525, in move
    self._update_existing_ptr_loc_info()
  File "/usr/lib/archivematica/storage-service/locations/models/package.py", line 1142, in _update_existing_ptr_loc_info
    root, pretty_print=True, xml_declaration=True, encoding="utf-8"
TypeError: write() argument must be str, not bytes 
```

**Your environment (version of Archivematica, operating system, other relevant details)**

Archivematica 1.13/storage service 0.19 running on CentOS 7
Also reproducible on the archivematica/hack docker-compose stack.

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged (if applicable)
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by gehurley** [comment]
Thank you @fozboz ! Just adding here that the AIP does physically get moved to the new storage location, but the pointer file fails to get updated and gets replaced by a 0-byte file, which presumably causes the stall in the move operation. As a result functions like METS download and re-ingest also fail.
