### ISSUE TITLE
PROBLEM: AIP recovery documentation is unclear how to copy uncompressed replicated AIPs and requires API request updates

### ISSUE THREAD

**Issue by sarah-mason** [archivematica/Issues#1546]
**Version of the documentation**
1.13 

**Page (and section, if applicable) where the issue occurs**
https://www.archivematica.org/en/docs/storage-service-0.19/recovery/#example-recovery-request 

**Description of the issue**
There are some changes required to the documentation to make AIP recovery clear, especially when using a replicator location. They are:
* How to copy uncompressed replicated AIPs is not stated
* The recovered AIP permissions for the Storage Service to perform AIP recovery is not stated
* The API request needs to be updated to reflect the API documentation

**Suggested fix**
Documentation updates should include:
* uncompressed AIP replicas must be copied to the recovery location with the original AIP uuid in the package name, not the replica uuid
* permissions for AIPs and all files must be set to `archivematica` as owner to work properly 
* API request should be updated based on API documentation  in dev manual and a link to API documentation added

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by JBosse-Artefactual** [comment]
The issue has been resolved in 0.22 documentation of the [recovery process](https://www.archivematica.org/fr/docs/storage-service-0.22/recovery/) can now replace both compressed and uncompressed AIPs as described in the documentation. To be added to the documentation "Ensure the AIP recovery directory is empty before starting the recovery process, and if a recover directory exists inside the internal processing location (e.g. /var/archivematica/storage_service/var/archivematica/storage_service/recover), make sure it is empty as well."
