### ISSUE TITLE
Problem: S3 upload does not specify content type / mime type in header 

### ISSUE THREAD

**Issue by gehurley** [archivematica/Issues#1550]
**Expected behaviour**

When making use of an S3 storage location, especially for DIPs (thanks to https://github.com/archivematica/Issues/issues/1442), files uploaded should have a mime type assigned in the metadata. 

If users wish to make use of any kind of public access for files in a DIP in S3, such as sharing a URL for upload to AtoM or for sending to researchers, the ideal behaviour would be for the file display in browser. For this to happen, a mimetype needs to be passed with the object. Otherwise, all files default to download which is not useful or expected behaviour for streaming audiovisual content, viewing images and PDFs, etc. 

**Current behaviour**

All objects uploaded to an S3 storage location using the boto3 library have the mimetype `binary/octet-stream` assigned.

This issue is also documented in reference to the boto3 library here: https://github.com/boto/boto3/issues/548

**Steps to reproduce**

- Store a DIP in an S3 location with public access turned on
- View the metadata in relation to that file, or attempt to access the file using a public URL

**Your environment (version of Archivematica, operating system, other relevant details)**
Archivematica 1.13, tested in CentOS and Ubuntu

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged (if applicable)
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by fozboz** [comment]
Proposed fix: https://github.com/artefactual/archivematica-storage-service/pull/633/files

**Comment by sromkey** [comment]
Thanks for the suggestion and the fix! I've earmarked it for consideration for the next release.

**Comment by fitnycdigitalinitiatives** [comment]
This is great!

**Comment by sromkey** [comment]
@fozboz Hi there! If we could get a contributor's agreement from you we can get this into the next release (check your email :) ) Thank you!

**Comment by replaceafill** [comment]
Verified this by:
* Creating an uncompressed AIP in a Duracloud AIP Storage location and checking each file displays the appropriate `Mime Type` information and not `application/octet-stream` anymore.
* Creating a DIP in an S3 DIP Storage location and checking each file displays the appropriate `Content-Type` information in the Metadata section and not `binary/octet-stream` anymore.
