### ISSUE TITLE
Problem: pointer file error (not compliant to Mets xsd Version 1121 ?)

### ISSUE THREAD

**Issue by rguedj18** [archivematica/Issues#1555]
**Expected behaviour**
File pointer created should be validated

**Current behaviour**
An error comes up during the validation of the structure of file pointer

ERROR 2022-05-10 05:12:49 locations.models.package:package:create_pointer_file:1493: Pointer file constructed for dce4b6b7-f524-4d1f-bcab-cab730c1d58c is not valid.
Schematron Error(s):
1. A techMD mdWrap element must contain a PREMIS object element.
test: m:xmlData/p:object
location: /*[local-name()='mets' and namespace-uri()='[http://www.loc.gov/METS/']/*[local-name()='amdSec'](http://www.loc.gov/METS/%27%5D/*%5Blocal-name()=%27amdSec%27) and namespace-uri()='[http://www.loc.gov/METS/']/*[local-name()='techMD'](http://www.loc.gov/METS/%27%5D/*%5Blocal-name()=%27techMD%27) and namespace-uri()='[http://www.loc.gov/METS/']/*[local-name()='mdWrap'](http://www.loc.gov/METS/%27%5D/*%5Blocal-name()=%27mdWrap%27) and namespace-uri()='[http://www.loc.gov/METS/']](http://www.loc.gov/METS/%27%5D)

We have noticed that Pointer file structure is related to a different xsd schema of mets:

Version 1121 (in Archivematica  1.13.2)

<mets:mets xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:mets="http://www.loc.gov/METS/" xsi:schemaLocation="http://www.loc.gov/METS/ http://www.loc.gov/standards/mets/version1121/mets.xsd">
  <mets:metsHdr CREATEDATE="2022-05-10T12:12:49"/>

and in our current Archivematica instance (1.10.1), 

<mets:mets xmlns:mets="http://www.loc.gov/METS/" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.loc.gov/METS/ http://www.loc.gov/standards/mets/version111/mets.xsd">
  <mets:metsHdr CREATEDATE="2022-05-10T13:08:02"/>

**Steps to reproduce**
Nothing special, 
a packet with automatic normalization is ingested and DIP sent to AtoM

**Your environment (version of Archivematica, operating system, other relevant details)**
4.15.0-175-generic
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.6 LTS
Release:        18.04
Codename:       bionic

Archivematica  1.13.2 deployed by Ansible on a single node

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged (if applicable)
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by replaceafill** [comment]
Using https://github.com/archivematica/Issues/issues/1292 to track this.
