### ISSUE TITLE
Problem: Docker build fails on copy steps due to dockerignore whitelist errors 

### ISSUE THREAD

**Issue by mInnes-archives** [archivematica/Issues#1557]
**Expected behaviour**
`make build` successfully completes

**Current behaviour**
`make build` fails on COPY steps resulting in the following errors types:

```
Step 10/60 : COPY hack/osdeps.py /src/hack/osdeps.py
ERROR: Service 'archivematica-mcp-server' failed to build: COPY failed: file not found in build context or excluded by .dockerignore: stat hack/osdeps.py: file does not exist
Makefile:81: recipe for target 'build' failed
make: *** [build] Error 1
```

**Steps to reproduce**
run `make build` as per standard Archivematica Docker Compose install instructions, ensuring that the relevant files aren't already in the target location.

**Your environment (version of Archivematica, operating system, other relevant details)**
qa/1.x, Ubuntu 18.04.6, etc.

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged (if applicable)
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by replaceafill** [comment]
From the `Step 10/60` part of your output I presume you're not running the latest version of `docker-compose`.

I'm able to reproduce your error message in a fresh Ubuntu 18.04.6 VM by installing the `docker-compose` package which brings the following versions:

```
replaceafill@vm1:~/archivematica/hack$ docker --version
Docker version 20.10.7, build 20.10.7-0ubuntu5~18.04.3
replaceafill@vm1:~/archivematica/hack$ docker-compose --version
docker-compose version 1.17.1, build unknown
```

Looking at the Docker Compose release notes I noticed this issue was addressed in version [1.20.0](https://docs.docker.com/compose/release-notes/#1200):

> Bug Fixes
>
> * Fixed .dockerignore handling, notably with regard to absolute paths and last-line precedence rules

It was reported as https://github.com/docker/compose/issues/5672 and fixed in https://github.com/docker/docker-py/pull/1904

If I uninstall the `docker-compose` deb package and install release 1.20.0 from Github:

```
sudo curl -SL https://github.com/docker/compose/releases/download/1.20.0/docker-compose-Linux-x86_64 -o /usr/local/bin/docker-compose
sudo chmod +x /usr/local/bin/docker-compose
```

the `COPY failed` error goes away.

**Comment by mInnes-archives** [comment]
>From the `Step 10/60` part of your output I presume you're not running the latest version of `docker-compose`.

Yes, looks that way. In that case my characterization that this problem is the result of a syntax error is wrong. Sorry about that.

> If I uninstall the docker-compose deb package and install release v1.20.0 from Github...the `COPY failed` error goes away.

Given that Universe for Ubuntu 18.04.6 keeps `docker-compose` at 1.17.1, I suppose there are a two options until Archivematica is officially support on Ubuntu 20.04.4:

1. Update the Archivematica docker documentation to include a step to grab `docker-compose` 1.20.0.
2. Don't use absolute paths in the dockerignore file to maintain compatibility with 1.17.1 (ie. merge this PR).

Option 2 seems easier in my opinion, but if you are aware of any issues it might introduce, then option 1 would be the way to go.

**Comment by replaceafill** [comment]
In https://github.com/artefactual/archivematica/pull/1826 we updated the `README` file to indicate the Docker Engine and Compose versions that the development environment needs.
