### ISSUE TITLE
Feature: Support more cloud storage services

### ISSUE THREAD

**Issue by tw4l** [archivematica/Issues#1567]
**Please describe the problem you'd like to be solved**

Currently the Archivematica Storage Service can only communicate to cloud storage providers over the S3 or Swift protocols, using the Spaces dedicated to those protocols. We would like to be able to use a wider range of cloud storage providers without needing to write an adapter Space for each provider/protocol.

**Describe the solution you'd like to see implemented**

We (PDT) would like to implement an [rclone](https://rclone.org) Space in the Storage Service, which would allow using nearly any cloud provider or service for AIP storage, replication, DIP storage, and transfer sources.

**Describe alternatives you've considered**

Writing Space adapters for each protocol independently (too much maintenance overhead), sticking to only S3 and Swift-compatible vendors (limiting)

**Additional context**

This is part of a solution for a client project around preservation storage.

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged
- [ ] Details about this issue have been added to the release notes

**Comment by Dhwaniartefact** [comment]
Verified this in our dev environment for s3 bucket using this new rcone changes.
