### ISSUE TITLE
Problem: Storage Service documentation doesn't build with Sphinx 5

### ISSUE THREAD

**Issue by tw4l** [archivematica/Issues#1568]
**Version of the documentation**

All branches, first noticed with `0.20`.

**Page (and section, if applicable) where the issue occurs**

This is a more general issue, not related to a specific page.

**Description of the issue**

`make html` fails when using Sphinx 5, e.g.: https://github.com/artefactual/archivematica-storage-service-docs/runs/8075260528?check_suite_focus=true.

Pinning the Sphinx version to `Sphinx<5.0.0` solves the issue for now, but we'll probably want to address the problem rather than continue using an older version of `Sphinx`.

I haven't checked to see if the Archivematica documentation is affected as well, but it seems likely.

**Suggested fix**

Look into and fix issues preventing docs from building on Sphinx 5.

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by replaceafill** [comment]
This has been fixed in https://github.com/artefactual/archivematica-storage-service-docs/commit/476af16e52441b346f9efe815423b35d040e13ce where the `extlinks` configuration was updated to be compatible with Sphinx 6.0 and higher.
