### ISSUE TITLE
Feature: Add package checksums in Storage Service database to add additional level of verification that an AIP hasn't been replaced in storage

### ISSUE THREAD

**Issue by tw4l** [archivematica/Issues#1570]
**Please describe the problem you'd like to be solved**

The Storage Service does not currently store checksums for AIPs, which has two consequences:
1. The Storage Service could potentially be fooled if an AIP was replaced on-disk by another BagIt bag with the same name
2. Fixity checks for compressed AIPs require extracting the compressed package, rather than calculating a checksum for the compressed package

**Describe the solution you'd like to see implemented**

I'd like to store a checksum in the Storage Service database for all AIPs. For compressed AIPs, this would be the checksum of the package. For uncompressed AIPs, we could store the checksum of the Bag's tagmanifest file, which itself contains checksums for the Bag files and hash manifest.

**Describe alternatives you've considered**

I considered extending pointer files for uncompressed AIPs, but decided the scope would be too large to get the direct benefit described here.

**Additional context**

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged
- [ ] Details about this issue have been added to the release notes

**Comment by replaceafill** [comment]
Verified this by storing a compressed AIP and an uncompressed AIP and checking their `checksum` and `checksum_algorithm` columns of the Storage Service database were populated correctly. Also ran a metadata only reingest on the compressed AIP and saw the `checksum` value being updated correctly. Finally ran fixity successfully on both AIPs.
