### ISSUE TITLE
Feature: Make Elasticsearch MAX_QUERY_SIZE and TOTAL_FIELDS_LIMIT configurable

### ISSUE THREAD

**Issue by mamedin** [archivematica/Issues#1571]
**Please describe the problem you'd like to be solved**

The total AIPs limit on the "Archival Storage" tab are limited to 10000 items. It is hardcoded so right now we need change directly the code to print more than 10000 items.

**Describe the solution you'd like to see implemented**

I'd like to have some variables in the dashboard config file to set this limit.

Right now we are changing the following 2 files to increase that limit to 100000:

* `src/archivematicaCommon/lib/elasticSearchFunctions.py`
* `src/dashboard/src/components/archival_storage/views.py`

With the following diffs:

```
[root@am02 archivematica]# git diff src/archivematicaCommon/lib/elasticSearchFunctions.py
diff --git a/src/archivematicaCommon/lib/elasticSearchFunctions.py b/src/archivematicaCommon/lib/elasticSearchFunctions.py
index 2cdd6c0..e163046 100644
--- a/src/archivematicaCommon/lib/elasticSearchFunctions.py
+++ b/src/archivematicaCommon/lib/elasticSearchFunctions.py
@@ -99,9 +99,9 @@ INDEXES = [AIPS_INDEX, AIP_FILES_INDEX, TRANSFERS_INDEX, TRANSFER_FILES_INDEX]
 DOC_TYPE = "_doc"
 # Maximun ES result window. Use the scroll API for a better way to get all
 # results or change `index.max_result_window` on each index settings.
-MAX_QUERY_SIZE = 10000
+MAX_QUERY_SIZE = 100000
 # Maximun amount of fields per index (increased from the ES default of 1000).
-TOTAL_FIELDS_LIMIT = 10000
+TOTAL_FIELDS_LIMIT = 100000
 # Maximum index depth (increased from the ES default of 20). The way the
 # `structMap` element from the METS file is parsed may create a big depth
 # in documents for AIPs with a big directories hierarchy.
**Describe alternatives you've considered**
```

```
[root@vpl-dpasarc02 archivematica]# git diff src/dashboard/src/components/archival_storage/views.py
diff --git a/src/dashboard/src/components/archival_storage/views.py b/src/dashboard/src/components/archival_storage/views.py
index ec5dd2e..612542f 100644
--- a/src/dashboard/src/components/archival_storage/views.py
+++ b/src/dashboard/src/components/archival_storage/views.py
@@ -328,7 +328,7 @@ def search(request):
             # add size parameter in terms to override.
             # TODO: Use composite aggregation when it gets out of beta.
             query["aggs"] = {
-                "aip_uuids": {"terms": {"field": "AIPUUID", "size": "10000"}}
+                "aip_uuids": {"terms": {"field": "AIPUUID", "size": "100000"}}
             }
             # Don't return results, just the aggregation.
             query["size"] = 0
```

And to avoid the ES reindex, we are applying on the ES server:

```
curl -XPUT 'http://localhost:9200/aips,aipfiles,transfers,transferfiles/_settings' -H "Content-Type: application/json"  -d '{"index.mapping.total_fields.limit": 100000, "index.max_result_window": 100000}'
```

**Additional context**

It must be added to the Archivematica documentation, specially the ES server changed to avoid the reindex.

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged
- [ ] Details about this issue have been added to the release notes

**Comment by replaceafill** [comment]
Verified this by setting `ARCHIVEMATICA_DASHBOARD_DASHBOARD_ELASTICSEARCH_MAX_QUERY_SIZE=3` in `/etc/default/archivematica-dashboard` in a Ubuntu 18.04 QA server with 7 AIPs listed in the `Archival storage` tab. After restarting the service the table only listed 3 AIPs, and after removing the setting and restarting the server again I was able to see them all listed again.
