### ISSUE TITLE
 Job Identify file format: Failed 

### ISSUE THREAD

**Issue by taschenlampe** [archivematica/Issues#1573]
Hi!

Please bear in mind that I am an absolute beginner to archivematica, so it is most likely that this issue is rather my issue than a problem with the software

While "Examining contents Job: Identidy the file format" I got a failed message

```
Standard output (stdout)

IDCommand: Identify by File Extension
IDCommand UUID: 8546b624-7894-4201-8df6-f239d5e0d5ba
IDTool: File Extension
IDTool UUID: 115bc526-c75b-4d2a-9fb9-090c5b49620f
File: (3ca2ed3a-dae6-451e-8570-5d16a950cdd8) /var/archivematica/sharedDirectory/watchedDirectories/workFlowDecisions/selectFormatIDToolTransfer/888-9850fb63-6a88-4a1b-b346-317b307074b6/objects/ubant2o3_-_Kopie.jpg


Errors and diagnostics (stderr)

Error: IDCommand with UUID 8546b624-7894-4201-8df6-f239d5e0d5ba exited non-zero.
Error: [Errno 13] Permission denied: '/tmp/664ab50d-d6f9-480a-bacb-dc615187dffd'
```

I found some errors and infos that might lead to the core of the problem, but I haven´t found any real info that could help me analyse the issue.

In storage_service_debug.log I see following:

```
INFO      2022-10-04 05:52:42  locations.models.space:space:move_rsync:552:  Moving from /var/archivematica/storage_service/var/archivematica/sharedDirectory/tmp/tmplqd7ht1e/777/./ to /var/archivematica/sharedDirectory/tmp/tmplqd7ht1e/777/.
DEBUG     2022-10-04 05:52:42  locations.models.space:space:move_rsync:566:  os.rename failed, trying with normalized paths
DEBUG     2022-10-04 06:00:37  locations.api.resources:resources:_move_files_between_locations:554:  Moving files from this location is not allowed
DEBUG     2022-10-04 06:00:37  locations.models.space:space:move_to_storage_service:346:  TO: src: home/Test/import/.
DEBUG     2022-10-04 06:00:37  locations.models.space:space:move_to_storage_service:347:  TO: dst: /var/archivematica/sharedDirectory/tmp/tmpeftj8h9q/888/.
DEBUG     2022-10-04 06:00:37  locations.models.space:space:move_to_storage_service:348:  TO: staging: /var/archivematica/storage_service
```

/var/log/messages shows:

```
Oct  4 13:00:15 dlzaatom1c002 python: archivematicaClient.py: INFO      2022-10-04 11:00:15,641  archivematica.mcp.client:write_task_results_callback:218:
Oct  4 13:00:15 dlzaatom1c002 python: *** Completed job: #<characterizefile_v0.0; exit=255; code=success uuid=872f39c8-c8a2-4bd5-859a-1d611c1104a5
Oct  4 13:00:15 dlzaatom1c002 python: =============== STDOUT ===============
Oct  4 13:00:15 dlzaatom1c002 python: Config Error!
Oct  4 13:00:15 dlzaatom1c002 python: =============== END STDOUT ===============
Oct  4 13:00:15 dlzaatom1c002 python: =============== STDERR ===============
Oct  4 13:00:15 dlzaatom1c002 python: [Errno 13] Permission denied: '/tmp/c0aefd7f-5702-4c85-a9c3-623741868e1a'Command FITS failed with exit status -1; stderr:
Oct  4 13:00:15 dlzaatom1c002 python: =============== END STDERR ===============
```

**Expected behaviour**
Files get analysed and filetype gets detected

**Current behaviour**
Files do not get identified -> transfer continues but no normalisation is triggered

**Your environment (version of Archivematica, operating system, other relevant details)**
RHEL7:x86_64
archivematica: 1.13.2

-> Is there a way to manually trigger the failing command  so I could debug that issue a little more? 
-> It is not impossible that my company has some automated restrictions.

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged (if applicable)
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by mamedin** [comment]
Hi @taschenlampe, probably it can sounds weird but I suspect your issue is related to the /tmp directory permissions.

Are you using a separate partition and with the `noexec` option enabled?

**Comment by taschenlampe** [comment]
@mamedin Thanks for you hint, that was it. File detection works now
