### ISSUE TITLE
Problem: DSpace transfer fails at verifying checksums in the METS if another METS exists inside an extracted package

### ISSUE THREAD

**Issue by johngostick** [archivematica/Issues#1579]
**Expected behaviour**
When processing a submission exported from DSpace using the transfer type 'DSpace', Archivematica appears to verify the checksums included in the `<fileSec>` of the DSpace-supplied METS file. Specifically, it looks at the CHECKSUM and CHECKSUMTYPE attributes in the file elements within the `<fileSec>`, e.g.
`<file ID="bitstream_1" MIMETYPE="application/pdf" SEQ="1" SIZE="9123323" CHECKSUM="0fca4ba7ce27efe0007dda9621450e51" CHECKSUMTYPE="MD5" ADMID="amd_22" GROUPID="GROUP_bitstream_1">`

As far as I can tell, these don't appear to be part of the core METS specification so are possibly DSpace-specific? Archivematica clearly expects and uses these values for a DSpace transfer though.

**Current behaviour**
We've noticed that if a DSpace transfer includes additional content in a container that includes an additional (non-DSpace) METS file from another system, and our processing configuration is also set to extract packages, the Archivematica transfer will fail.

Specifically, it fails at Microservice: 'Identify DSpace files', Job: 'Verify checksums in fileSec of DSpace METS files' with error message 'Unsupported checksum type: '

This appears to be because Archivematica is picking up the additional METS file from the extracted package and then attempting to verify the checksums, but values for these are not present in the additional METS, hence the blank checksum type in the error message above.

I believe this is undesired behaviour and could potentially be avoided if the microservice only verified the fileSec checksums for a METS in the root of the DSpace package, ignoring any additional METS that may exist in subfolders or extracted packages.

**Steps to reproduce**
Processing Configuration: Extract packages (Transfer)

Transfer type: DSpace

Transfer source: A native AIP export from DSpace in ZIP format that includes an additional (non-DSpace) METS in a child container/package

**Your environment (version of Archivematica, operating system, other relevant details)**
Archivematica: 1.13.2
Storage Service: 0.15.0 

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged (if applicable)
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by johngostick** [comment]
Hi @eviau-artefactual - unfortunately we've since moved away from using Archivematica from this part of our workflow so I'm not able to verify if this is still an issue or supply any examples. I'm not aware of anyone else experiencing the same problem though so it might be best just to close and archive this one.

**Comment by eviau-artefactual** [comment]
Thank you for following on this!

Given your answer, we will be closing this for now.

If you or someone else encounters the same behaviour, feel welcome to re-open as needed.
