### ISSUE TITLE
Problem: Big transfers fail during 'Compress Aip' microservice when compression time exceeds MySQL wait_timeout and/or interactive_timeout values

### ISSUE THREAD

**Issue by currmie** [archivematica/Issues#1580]
**At the start of the 'Compress AIP' microservice, a new MySQL connection is opened. In theory, the time it takes for AIP compression should not exceed other timeout settings.**

**Current behaviour**
When running big transfers through a pipeline, they tend to fail during 'Compress AIP.'

**Steps to reproduce**
Increasing the MySQL wait_time and interactive_timeout can provide a temporary fix, but perhaps  a better option (from a deployment perspective) might be to alter the 'Compress AIP' microservice in the AM code to open a MySQL connection or add a re-attempt to reconnect to MySQL after compression .

**Your environment (version of Archivematica, operating system, other relevant details)**
AM 1.13.1

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged (if applicable)
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by Dhwaniartefact** [comment]
I verified this in my development environment by creating large file source directory and it does not fail during "Compress AIP" micro service. Also, the time it takes for AIP compression did not exceed other timeout settings.
