### ISSUE TITLE
Problem: change filenames microservice can create filenames which exceed the OS limit

### ISSUE THREAD

**Issue by helrond** [archivematica/Issues#1586]
**Expected behaviour**
Transfers which contain filenames with non-Latin characters should be processed successfully.

**Current behaviour**
The change filenames microservice attempts to change a filename such as `关于取消《基本医疗保险门诊治疗部分重症（慢性）疾病申报》中参保人员需要向所在参保单位（大学生向所在学校）提出申请并保护个人隐私信息的建议信.doc` (73 characters) to `Guan_Yu_Qu_Xiao___Ji_Ben_Yi_Liao_Bao_Xian_Men_Zhen_Zhi_Liao_Bu_Fen_Zhong_Zheng_(Man_Xing_)Ji_Bing_Shen_Bao____Zhong_Can_Bao_Ren_Yuan_Xu_Yao_Xiang_Suo_Zai_Can_Bao_Dan_Wei_(Da_Xue_Sheng_Xiang_Suo_Zai_Xue_Xiao_)Ti_Chu_Shen_Qing_Bing_Bao_Hu_Ge_Ren_Yin_Si_Xin_Xi_De_Jian_Yi_Xin_.doc` (277 characters). This results in an `OSError: [Errno 36] File name too long`.

**Steps to reproduce**
Attempt to ingest a transfer with the filename specified above.

**Your environment (version of Archivematica, operating system, other relevant details)**
Archivematica version 1.13.2
Running on Centos 7

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged (if applicable)
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by helrond** [comment]
I should note that this is a blocking issue for us, so I'd like to get it resolved ASAP. Happy to put together a PR if we can align on an approach to this problem.

**Comment by helrond** [comment]
It's true it's an OS-specific thing but the error is introduced when single characters are romanized into multiple characters by the Change Filenames microservice.

The easiest way to solve this would be to add a check on the filename length and truncate it if it exceeds the OS limit, with a secondary check to make sure the path in question doesn't already exist. As long as the changed filename gets written to a PREMIS event (and this behavior is documented in user-facing docs) it may be the best that we can do if we're presuming that filenames do in fact need to have all non-Latin characters removed, which feels like a harder assumption to test.

**Comment by replaceafill** [comment]
Verified this by running a `Standard` transfer on a directory containing these two files:

```bash
replaceafill@vm1:~/archivematica/hack/submodules/archivematica-sampledata/test-long-names$ tree .
.
├── 关于取消《基本医疗保险门诊治疗部分重症（慢性）疾病申报》中参保人员需要向所在参保单位（大学生向所在学校）提出申请并保护个人隐私信息的建议信_2.txt
└── 关于取消《基本医疗保险门诊治疗部分重症（慢性）疾病申报》中参保人员需要向所在参保单位（大学生向所在学校）提出申请并保护个人隐私信息的建议信.txt
```

The transfer succeeds and the output of the `Change object and directory filenames` job shows the collision generated by the new names is handled correctly:

```
Changed name: /var/archivematica/sharedDirectory/currentlyProcessing/test-long-names-97243e03-2826-488e-b590-900a7c00e8ca/objects/关于取消《基本医疗保险门诊治疗部分重症（慢性）疾病申报》中参保人员需要向所在参保单位（大学生向所在学校）提出申请并保护个人隐私信息的建议信_2.txt  ->  /var/archivematica/sharedDirectory/currentlyProcessing/test-long-names-97243e03-2826-488e-b590-900a7c00e8ca/objects/Guan_Yu_Qu_Xiao___Ji_Ben_Yi_Liao_Bao_Xian_Men_Zhen_Zhi_Liao_Bu_Fen_Zhong_Zheng_(Man_Xing_)Ji_Bing_Shen_Bao____Zhong_Can_Bao_Ren_Yuan_Xu_Yao_Xiang_Suo_Zai_Can_Bao_Dan_Wei_(Da_Xue_Sheng_Xiang_Suo_Zai_Xue_Xiao_)Ti_Chu_Shen_Qing_Bing_Bao_Hu_Ge_Ren_Yin_Si_.txt
Changed name: /var/archivematica/sharedDirectory/currentlyProcessing/test-long-names-97243e03-2826-488e-b590-900a7c00e8ca/objects/关于取消《基本医疗保险门诊治疗部分重症（慢性）疾病申报》中参保人员需要向所在参保单位（大学生向所在学校）提出申请并保护个人隐私信息的建议信.txt  ->  /var/archivematica/sharedDirectory/currentlyProcessing/test-long-names-97243e03-2826-488e-b590-900a7c00e8ca/objects/Guan_Yu_Qu_Xiao___Ji_Ben_Yi_Liao_Bao_Xian_Men_Zhen_Zhi_Liao_Bu_Fen_Zhong_Zheng_(Man_Xing_)Ji_Bing_Shen_Bao____Zhong_Can_Bao_Ren_Yuan_Xu_Yao_Xiang_Suo_Zai_Can_Bao_Dan_Wei_(Da_Xue_Sheng_Xiang_Suo_Zai_Xue_Xiao_)Ti_Chu_Shen_Qing_Bing_Bao_Hu_Ge_Ren_Yin_S_1.txt
```

The original and modified names are also correct in the METS.
