### ISSUE TITLE
Problem: lxml element serialization does not specify encoding

### ISSUE THREAD

**Issue by replaceafill** [archivematica/Issues#1589]
**Expected behaviour**

Calls to `etree.tostring` always work with non-ASCII text.

**Current behaviour**

Some MCP client scripts and shared `archivematicaCommon` modules call `etree.tostring` to serialize `lxml` elements. Some of these calls don't specify an encoding so [they default to `ascii`](https://lxml.de/tutorial.html#serialisation) encoding.

We found a scenario in a client environment where the `Index AIP` job truncates `amdSec` elements if they contain children with very long non-ASCII strings which makes a subsequent call to `xmltodict` to fail. The closing tag for the `<premis:eventOutcomeDetailNote>` element of the `filename change` PREMIS event containing Chinese characters looked like this:

```
&#20250;\x05/premis:eventOutcomeDetailNote>
```

An lxml [issue](https://bugs.launchpad.net/lxml/+bug/1945048) describes a similar symptom and a way to address it.

We should probably add the encoding explicitly to all our `etree.tostring` calls.

**Steps to reproduce**

So far I've reproduced the issue using a modified version of the [test_index_metadata-METS.xml](https://github.com/artefactual/archivematica/blob/4db46a3faa360040348883d43fb146eccf073284/src/archivematicaCommon/tests/fixtures/test_index_metadata-METS.xml) fixture and running the [`test_index_mets_file_metadata`](https://github.com/artefactual/archivematica/blob/4db46a3faa360040348883d43fb146eccf073284/src/archivematicaCommon/tests/test_elasticsearch_functions.py#L96) test.

I have not tested the remaining cases yet.

**Your environment (version of Archivematica, operating system, other relevant details)**

https://github.com/artefactual/archivematica/commit/4db46a3faa360040348883d43fb146eccf073284
https://github.com/artefactual/archivematica-storage-service/commit/9216cad19519411f5d60e8e932501f24ea0be6d0

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged (if applicable)
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by Dhwaniartefact** [comment]
This was tested successfully in the test environment of the client with new changes.
