### ISSUE TITLE
Problem: GitHub is dropping Python 2.7 support from CI workflows

### ISSUE THREAD

**Issue by replaceafill** [archivematica/Issues#1602]
**Expected behaviour**

GitHub CI workflows pass in the Archivematica related repositories written in Python.

**Current behaviour**

The `setup-python` action used in many CI workflows will [drop Python 2.7 support](https://github.com/actions/setup-python/issues/672) on June 19. And GitHub also plans to [remove the `python:2.7` Docker image](https://github.com/actions/runner-images/issues/7401) from their CI runners.

This will affect the following repositories:

* https://github.com/artefactual/automation-tools
* https://github.com/artefactual/fixity
* https://github.com/artefactual-labs/agentarchives/
* https://github.com/artefactual-labs/amclient
* https://github.com/artefactual-labs/ammcpc/
* https://github.com/artefactual-labs/mets-reader-writer

**Steps to reproduce**

This is not happening yet, but at some point the CI workflows of these repositories will start failing in the jobs that test Python 2.7.

**Your environment (version of Archivematica, operating system, other relevant details)**

GitHub CI workflows of the mentioned repositories.

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged (if applicable)
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by Dhwaniartefact** [comment]
Verified and working successfully.
