### ISSUE TITLE
Problem: Large downloads (15GB+) from Duracloud fail if a single chunk fails once

### ISSUE THREAD

**Issue by carlosmcgregor** [archivematica/Issues#1607]
**Please describe the problem you'd like to be solved**

Whenever large files (15GB+) are retrieved from Duracloud, one failure from a single chunk will cause the whole operation to fail. This often means longer waiting times for users as they have to do multiple re-attempts when doing operations on such files, with every single operation already taking a long time.

**Describe the solution you'd like to see implemented**

Implementing a recursive retry in the function [Duracloud._download_file()](https://github.com/artefactual/archivematica-storage-service/blob/ab64d17f8220428091699870f6a14ac8dc45136b/storage_service/locations/models/duracloud.py#L227) that allows Archivematica to attempt downloading a chunk again. We have already extensively tested this approach successfully in our dev instance of Archivematica.

**Describe alternatives you've considered**

Streaming the chunks instead of doing a single download of them, but Duracloud does not allow for that.

**Additional context**

I am a member of [Scholars Portal](https://scholarsportal.info). I will be forking the repo and making a pull request with our change for you to review.

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged
- [ ] Details about this issue have been added to the release notes

**Comment by replaceafill** [comment]
We test this new logic in the automated tests of the Storage Service now.
