### ISSUE TITLE
Problem: Endpoint /api/transfer/uuid/delete/ example incorrect

### ISSUE THREAD

**Issue by jens-st** [archivematica/Issues#1609]
**Version of the documentation**
Archivematica 1.13.2 / Archivematica API

**Page (and section, if applicable) where the issue occurs**
https://www.archivematica.org/en/docs/archivematica-1.13/dev-manual/api/api-reference-archivematica/#hide

**Description of the issue**
* example request incorrect / outdated
```
curl -X DELETE \
    http://my_archivematica_instance.archivematica.org/api/transfer/status/
    89fd478d-c896-461a-baec-5d1faf661020/ \
    -H 'Authorization: ApiKey [_your_username_]:[_your_ApiKey_]' \
    -H 'Host: my_archivematica_instance.archivematica.org'
```

**Suggested fix**
```
curl -X DELETE \
    http://my_archivematica_instance.archivematica.org/api/transfer/
    89fd478d-c896-461a-baec-5d1faf661020/delete/ \
    -H 'Authorization: ApiKey [_your_username_]:[_your_ApiKey_]' \
    -H 'Host: my_archivematica_instance.archivematica.org'
```
---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by sromkey** [comment]
Thanks for bringing this to our attention!

**Comment by Dhwaniartefact** [comment]
Fixed in https://github.com/artefactual/archivematica-docs/pull/454
