### ISSUE TITLE
Problem: Temporary directories (and the files inside) are not deleted when a file is requested from an AIP from a remote server, e.g. S3

### ISSUE THREAD

**Issue by joel-simpson** [archivematica/Issues#1614]
**Expected behaviour**
When a METs file is downloaded (using the API) from a remote service, e.g. Amazon S3, all temporary artifacts are deleted afterwards. 

**Current behaviour**
When a METS file is requested via the API, a copy of the AIP is stored on the Storage Service. 

**Steps to reproduce**
We are seeing this when we run AIPScan, which requests METs files for indexing. It means that indexing an AIPStore requires as much storage on the Storage Service as there is in the actual AIPStore. 

**Your environment (version of Archivematica, operating system, other relevant details)**
Ubuntu 18.02 running Archivematica 1.13.2 and storage service 0.19; connected to an S3 AIPStore. 

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged (if applicable)
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by replaceafill** [comment]
The temporary directory for the AIP is now removed after downloading the METS file from the Archival storage tab.
