### ISSUE TITLE
Problem: DSpace exports resulting in incorrect METS if started as a package

### ISSUE THREAD

**Issue by sromkey** [archivematica/Issues#1617]
**Expected behaviour**

As per the [documentation](https://archivematica.org/en/docs/archivematica-1.14/user-manual/transfer/dspace/#dspace) there are three expected elements in the resulting AIP METS and they should be present whether the transfer was started as an individual DSpace export or if started from a directory higher than the export(s). There are two dmdSecs specific to the DSpace transfer workflow and in the fileSec there should be the expected fileGrps present as per the documentation. 

**Current behaviour**

It is working as expected if a directory containing DSpace exports is started as a transfer but if an individual export is started the METS elements are not there. It appears to be treated like a zipped directory transfer.

**Steps to reproduce**

1. Choose DSpace as the transfer type
2. Choose an individual DSpace export as the transfer material
3. Process and inspect the METS.

**Your environment (version of Archivematica, operating system, other relevant details)**

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged (if applicable)
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by replaceafill** [comment]
This regression was introduced during https://github.com/artefactual/archivematica/pull/1787 where the `create_mets_v2` client script was changed to rely more on the `mets-reader-writer` library in the generation of the AIP METS.

Using the `SampleTransfers/DSpaceExport/ITEM@2429-2700.zip` transfer this is how the [METS](https://github.com/archivematica/Issues/files/11986838/mets-before.xml.txt) looks like up to the point where it is passed and parsed by the `mets-reader-writer` which loses the Dspace dmdSecs.

**Comment by JBosse-Artefactual** [comment]
All three expected elements are present in the resulting AIP METS. Confirmed issue is fixed.
