### ISSUE TITLE
Problem: checksums not visible in Packages table

### ISSUE THREAD

**Issue by shij13** [archivematica/Issues#1625]
**Expected behaviour**
Columns recording checksums, checksum algorithms, and stored date for packages are recorded in the Packages table after upgrading to Storage Service 0.20.1

**Current behaviour**
Only the stored date column has been added to the Packages table in the Storage Service.
![image](https://github.com/archivematica/Issues/assets/97206007/5e513cb1-5e52-4f41-b3ec-836fb4f5d0d7)

It looks like package_row.html and packages_table.html were updated in #[636](https://github.com/artefactual/archivematica-storage-service/pull/636/files#diff-f29524185d7a564ec1374800643392cfd185a2989c770edb236997ac2dee22c4) for the stored_date but not in #[639](https://github.com/artefactual/archivematica-storage-service/pull/639/files) for the checksum and checksum_algorithm

**Steps to reproduce**
Install/upgrade to Storage Service 0.20.1
Open the Packages tab and look at the columns present

**Your environment (version of Archivematica, operating system, other relevant details)**
SS 0.20.1

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged (if applicable)
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by eviau-artefactual** [comment]
Please note that I was able to reproduce the issue - I only see the Stored column and no checkums ones.

![image](https://github.com/archivematica/Issues/assets/146032034/596b6860-0578-4c24-aebb-65188c6c6b29)

**Comment by sromkey** [comment]
Hi @shij13 , thanks for the suggestion- having given this some thought we're concerned about the UI getting too crowded- this table is already quite over extended. I think if we add any further data to the table it will have to be done in the larger scope of a re-design. Thanks again!

**Comment by shij13** [comment]
Thanks for the explanation @sromkey . I just wanted to note that I was looking for this information in the Storage Service dashboard because of issue #1570 , which is associated with the the AM1.14/SS 0.20.x milestone. To clarify, was #1570 a change to the database but not the user interface? Apologies for not referencing this when I first created the issue.

**Comment by sromkey** [comment]
@shij13 no worries at all, and you've got that correct- it was intended to be stored in the database but not necessarily the user interface.
