### ISSUE TITLE
Problem: Archivematica - manual install instructions for Ubuntu are out of date

### ISSUE THREAD

**Issue by marceloalencar** [archivematica/Issues#1626]
**Version of the documentation**
1.14.1

**Page (and section, if applicable) where the issue occurs**
Manually Installing Archivematica on Ubuntu (/admin-manual/installation-setup/installation/install-ubuntu)

**Description of the issue**
As is, the install fails due to the missing MySQL Server.
It is necessary to install MySQL Server, create the 'archivematica' user and 'SS' database before installing archivematica-storage-service.
All next steps remains the same.

**Suggested fix**
Update steps according to the actual behavior during install.
https://github.com/artefactual/archivematica-docs/pull/426

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by replaceafill** [comment]
@marceloalencar's fix has been merged to the `1.14` branch of the docs in https://github.com/artefactual/archivematica-docs/commit/9ba99dec2082a408e177799a4955c3d1c4339d2b
