### ISSUE TITLE
Problem: Archivematica related repositories use unsupported Python versions

### ISSUE THREAD

**Issue by replaceafill** [archivematica/Issues#1632]
**Expected behaviour**

In https://github.com/archivematica/Issues/issues/1612 we dropped [unsupported Python versions](https://devguide.python.org/versions/#unsupported-versions) in Archivematica and Storage Service. We should also drop them from other Archivematica related repositories like [agentarchives](https://github.com/artefactual-labs/agentarchives), [amclient](https://github.com/artefactual-labs/amclient), etc.

**Current behaviour**

The following Python related repositories still support Python 3.6 and 3.7 which have reached "end-of-life" already:

* https://github.com/artefactual/automation-tools
* https://github.com/artefactual/fixity
* https://github.com/artefactual-labs/agentarchives/
* https://github.com/artefactual-labs/amclient
* https://github.com/artefactual-labs/ammcpc/
* https://github.com/artefactual-labs/mets-reader-writer

Among other problems this prevents security related upgrades on some of these.

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged (if applicable)
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by mcantelon** [comment]
https://github.com/artefactual-labs/AIPscan is another to add to the list. I'm currently working on upgrading its CI and dependencies to remove vulnerabilities.

**Comment by replaceafill** [comment]
These are the git tags of each project that still support Python 3.6:

* https://github.com/artefactual/automation-tools/releases/tag/v0.1.0
* https://github.com/artefactual/fixity/releases/tag/v0.5.0
* https://github.com/artefactual-labs/agentarchives/releases/tag/v0.8.0
* https://github.com/artefactual-labs/amclient/releases/tag/v1.2.3
* https://github.com/artefactual-labs/ammcpc/releases/tag/v0.1.3
* https://github.com/artefactual-labs/mets-reader-writer/releases/tag/v0.4.0

**Comment by replaceafill** [comment]
All these projects are now being tested in CI workflows with Python 3.8 - 3.12. Once Django supports Python 3.13 we will need a similar update on these projects.
