### ISSUE TITLE
Problem: JHOVE failure event outcome has result "Well-formed and valid"

### ISSUE THREAD

**Issue by sallain** [archivematica/Issues#164]
**Expected behaviour**
If JHOVE encounters a failure during validation, there are two visible results in the UI:

1. _Job: Validate formats_ should turn pink with the output message "Failed".
2. Clicking on the gear icon to view the task output, the file that failed should have a STDERR output with the following:

```
Command Validate using JHOVE indicated failure with this output:

'{"eventOutcomeInformation": "fail", "eventOutcomeDetailNote": "format=\\"bytestream\\"; result=\\"Some error message here, i.e. Well-formed and not valid\\""}\n'
```

**Current behaviour**
JHOVE validation is failing for the file SampleTransfers/Multimedia/sample.aif. The validation job bar is turning pink, as expected, but the STDERR output reads:

```
Command Validate using JHOVE indicated failure with this output:

'{"eventOutcomeInformation": "fail", "eventOutcomeDetailNote": "format=\\"bytestream\\"; result=\\"Well-Formed and valid\\""}\n'
```
The event outcome result "Well-Formed and valid" is concerning - it would be ideal to see more information about why this validation failed. @sevein has suggested that it's possible that JHOVE is not signalling completion with the right exit code.

I tested the same file using JHOVE 1.20.1 on my local machine and the file validated correctly. Note that Archivematica is currently using JHOVE 1.6.

**Steps to reproduce**
Run the SampleTransfers/Multimedia directory following usual steps. JHOVE will automatically run.

**Your environment (version of Archivematica, OS version, etc)**
Tested on QA, 1.7.1, and 1.7.2.

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Release documentation (e.g. release notes, wiki documentation, etc) regarding this issue has been written 👍

**Comment by sallain** [comment]
Still happens on 1.8 (confirmed on Ubuntu 18.04 and RPM) for .aif and .wav files.

**Comment by sallain** [comment]
Same error occurs with SampleTransfers/OfficeDocs/article.pdf

**Comment by ross-spencer** [comment]
For reference, the JHOVE bytestream module just makes sure that what it's looking at is a file and that it can be read: https://github.com/openpreserve/jhove/blob/a79dc0bdcdaed69b182f4dd89b8e4517ac40ddc2/jhove-core/src/main/java/edu/harvard/hul/ois/jhove/module/BytestreamModule.java#L75-L115 and http://jhove.openpreservation.org/modules/bytestream/ 

The code notes that any arbitrary stream is valid, but that means everything including a zero-byte file:
```
JhoveView (Rel. 1.20.1, 2018-03-29)
 Date: 2018-12-18 08:53:14 CET
 RepresentationInformation: /home/ross-spencer/git/artefactual-labs/am/src/archivematica-sampledata/custom-transfers/pg/Empty File
  ReportingModule: BYTESTREAM, Rel. 1.3 (2007-04-10)
  LastModified: 2018-08-14 18:09:29 CEST
  Size: 0
  Format: bytestream
  Status: Well-Formed and valid
  InfoMessage: Zero-length file
  MIMEtype: application/octet-stream
```
Avoiding a false positive (the suggestion that any particular JHOVE-like validation has been done) would be good, so a `partial-pass` or ignoring bytestreams somehow entirely, seem like good options. But documenting the meaning of bytestream validation and its impact to the user could be beneficial if you choose for the module not to fail.

**Comment by ablwr** [comment]
As discussed in Slack, @sallain will decide how to best deal with this! Then I am happy to make the change.

@ross-spencer thanks for this extra insight!!

**Comment by sallain** [comment]
I also like the partial-pass option! I think it provides the context that the bitstream itself looked okay to JHOVE, but it wasn't able to carry out full validation of the format for whatever reason. I think reporting this result in the Transfer tab as a success is okay as well, rather than a failure - JHOVE is doing what it's supposed to do.

**Comment by sallain** [comment]
I ran the same test as in the initial report and this was the result:

1. Job is reported as completed successfully

![Screenshot of Archivematica Dashboard - Transfer (1).jpg](https://codetreeusercontent.s3.amazonaws.com/uploads/c5c45f98-278c-4b94-b075-6641d0b1a33e/Screenshot+of+Archivematica+Dashboard+-+Transfer+%281%29.jpg)

2. Task output for sample.aif shows that validation resulted in a partial pass for this file.

![Screenshot of Archivematica Dashboard -.jpg](https://codetreeusercontent.s3.amazonaws.com/uploads/c5c45f98-278c-4b94-b075-6641d0b1a33e/Screenshot+of+Archivematica+Dashboard+-.jpg)

Therefore, I think that this is working as per the decisions made in this thread, but before I move it to Done I want to make sure that other analysts have a chance to look at this and provide feedback, since this wasn't done as a client project - @ablwr @sromkey @evelynPM @corinnemrogers @currmie @sarah-mason @peterVG 

This is a pretty significant change to the validation microservice. In the past, the partial pass for the AIFF file would have resulted in a failure status in the dashboard, like this:

![Screenshot of Archivematica Dashboard - Transfer (2).jpg](https://codetreeusercontent.s3.amazonaws.com/uploads/c5c45f98-278c-4b94-b075-6641d0b1a33e/Screenshot+of+Archivematica+Dashboard+-+Transfer+%282%29.jpg)

And the task output for that error used to look like this:

![Screenshot of Archivematica Dashboard - (1).jpg](https://codetreeusercontent.s3.amazonaws.com/uploads/c5c45f98-278c-4b94-b075-6641d0b1a33e/Screenshot+of+Archivematica+Dashboard+-+%281%29.jpg)

What we are saying, with this change, is that if JHOVE encounters a file that it can only read as a bytestream, that is fine. Bytestream is used as the fallback option in JHOVE, if JHOVE can't figure out what format a file is supposed to be. I apparently did some analysis on this a few years ago, but it doesn't look like it went anywhere: https://projects.artefactual.com/issues/11117

**Comment by ablwr** [comment]
Yeah, for file formats like that .aif and .wav files -- a bytestream is a valid file and should pass. A preservation master LPCM audio in a .wav container is going to give that same result -- Well-formed and valid bytestream.

Updating JHOVE was sponsored via tickets by University of Washington and UCLA, and both registered a complaint about how their resulting "Well-formed and valid" bitstreams were coming up as failed when JHOVE considers them valid, so I guess I do consider this a client project in some ways? Although I agree it would take more than a change like this to really build out more robust validation in Archivematica, like you recommend in your previous analysis.

I support this because it brings us more in line with JHOVE's results.

**Comment by sallain** [comment]
Documentation has been added.
