### ISSUE TITLE
Feature: add  start time/end time to /api/v2beta/jobs/<unit UUID>/ API endpoint

### ISSUE THREAD

**Issue by scollazo** [archivematica/Issues#1641]
**Please describe the problem you'd like to be solved**

We want to consume the /api/v2beta/jobs/\<unit UUID\>/ API in enduro-sdps project, but it lacks information about microservices start time/end time.

**Describe the solution you'd like to see implemented**

Add start time/end time information to the /api/v2beta/jobs/\<unit UUID\>/ API endpoint

**Describe alternatives you've considered**

Run mysql queries and gather the information from the database

**Additional context**

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged
- [ ] Details about this issue have been added to the release notes

**Comment by scollazo** [comment]
It would be nice if it could also be available in the microservices list in the dashboard, something like

![image](https://github.com/archivematica/Issues/assets/2728070/27dcbf24-dfa6-4145-bd68-e2161226f4ea)

**Comment by replaceafill** [comment]
A `detailed` parameter was added to the `api/v2beta/jobs` API endpoint. When the parameter is sent in the request the endpoint will return all the task properties returned by the `api/v2beta/task` endpoint.
