### ISSUE TITLE
Problem: Create new format in preservation planning is not working (cannot save)

### ISSUE THREAD

**Issue by vdecorges** [archivematica/Issues#1643]
**Expected behaviour**
In preservation planning tab under Formats when using "Create new format" a dialog is open where you have to give a Group and a description. After filling this information a new format should be created by clicking on the save button.

**Current behaviour**
Clicking on the Save button does nothing no call is made.

**Steps to reproduce**
Go to the Preservation planning -> Formats -> Create new format, select a group and put a description then click on save.
Note that by modifying the html code of the form, it is possible to save.

**Your environment (version of Archivematica, operating system, other relevant details)**
Archivematica 1.12.1 on Ubuntu 18.04.3 LTS

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged (if applicable)
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by sromkey** [comment]
Hello @vdecorges - thanks for this report, I actually found the same behaviour in the current version (1.15.1). We'll look at this bug in a future release.

**Comment by sromkey** [comment]
In 1.16 I am able to create a new format as well as format versions.
