### ISSUE TITLE
Problem: not sure how to cite the software

### ISSUE THREAD

**Issue by eviau-artefactual** [archivematica/Issues#1654]
There is no hint at how to cite Archivematica in research papers, books, articles, etc.

**Comment by replaceafill** [comment]
@eviau-artefactual Can this be closed now that https://github.com/artefactual/archivematica/pull/1884 has been merged?

**Comment by eviau-artefactual** [comment]
Yes we can close it. I will probably review this later on - should I re-open or create a new issue?

**Comment by replaceafill** [comment]
Whatever is more convenient for you, but if you still need to work on this then we can leave it open.
