### ISSUE TITLE
Problem: S3 spaces fail with the global endpoint URL

### ISSUE THREAD

**Issue by replaceafill** [archivematica/Issues#1655]
**Expected behaviour**

S3 spaces work as documented.

**Current behaviour**

S3 spaces don't work if their `S3 Endpoint URL` field is set to the global S3 endpoint URL (`https://s3.amazonaws.com`) which is used as an example in the [user documentation](https://www.archivematica.org/en/docs/storage-service-0.21/administrators/#s3-amazon) and in the Storage Service [user interface](https://github.com/artefactual/archivematica-storage-service/blob/d2907d6195c74e08b26ae8d832984e27ecb417d4/storage_service/locations/models/s3.py#L45).

Any operation on the space and bucket will result in an exception similar to:

```
botocore.exceptions.ClientError: An error occurred (PermanentRedirect) when calling the CreateMultipartUpload operation: The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint.
```

This problem was introduced in https://github.com/artefactual/archivematica-storage-service/commit/ea8d7718476ed762ad1899a6f9bdbb1f6ffbfee3 where the `botocore` library was upgraded from version `1.26.10` to version `1.31.35`. It seems version `1.28.0` introduced a [change](https://github.com/boto/botocore/blob/82f14992032cb3de26d804231b94da54ff8b275f/CHANGELOG.rst#L3407) where the endpoint URL is now derived from the service that is being used.

@mamedin found that a workaround to this problem is to use a [regional endpoint](https://docs.aws.amazon.com/general/latest/gr/rande.html#regional-endpoints) (e.g `https://s3.us-west-2.amazonaws.com`) in the `S3 Endpoint URL` field that matches the `Region` field where the bucket is created.

**Steps to reproduce**

1. Set up an S3 space using `https://s3.amazonaws.com` for the `S3 Endpoint URL` field and set up an AIP Storage location in it.
2. Run a transfer and send it to the S3 AIP Storage location.
3. Processing will fail at the `Store the AIP` job in the Dashboard and you'll see a `ClientError` error in your Storage Service logs.

**Your environment (version of Archivematica, operating system, other relevant details)**

https://github.com/artefactual/archivematica/commit/43328a1756ae1235b2e6c0610527141db272d6f9
https://github.com/artefactual/archivematica-storage-service/commit/d2907d6195c74e08b26ae8d832984e27ecb417d4

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged (if applicable)
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by scollazo** [comment]
As a workaround, an rclone space can be used

**Comment by replaceafill** [comment]
The global endpoint URL `https://s3.amazonaws.com` works now.
