### ISSUE TITLE
Problem: Endpoint /api/ingest/copy_metadata_files/ response definition incorrect

### ISSUE THREAD

**Issue by jens-st** [archivematica/Issues#1656]
**Version of the documentation**
Archivematica 1.15.* / Archivematica API

**Page (and section, if applicable) where the issue occurs**
https://www.archivematica.org/en/docs/archivematica-1.15/dev-manual/api/api-reference-archivematica/#copy-metadata

**Description of the issue**
Response definition wrong, maybe copy & paste error (identical to API endpoint above)

**Suggested fix**
The HTTP Response that we get looks like this (no _reingest_uuid_ but an error indicator):
```json
{"error": false, "message": "Metadata files added successfully."}
```

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by Dhwaniartefact** [comment]
This has been fixed in https://github.com/artefactual/archivematica-docs/commit/01693692e8c2fca02fc1d4ee69d363c9afa52c11
