### ISSUE TITLE
Support for DICOM?

### ISSUE THREAD

**Issue by sumeetchhetri** [archivematica/Issues#1660]
After going through the legacy source code on google code, support for DICOM was available (assumption) via exiftool (https://code.google.com/archive/p/archivematica/source/default/source?page=309) and/or fits library from harvard. But the current versions seem to be depending on fido, is there any plan to provide DICOM + (metadata) read/write access via archivematica? There is already a library doing this (https://github.com/pydicom/pydicom)

**Comment by sromkey** [comment]
Hi @sumeetchhetri , thanks for your question/suggestion. No, we do not have any current plans for adding DICOM to the Archivematica stack although theoretically a person could do it locally through altering the Preservation Planning rules/commands (see: https://archivematica.org/en/docs/archivematica-1.15/user-manual/preservation/preservation-planning/#altering-commands-rules). 
In the future, please feel free to ask via the Archivematica user forum on Google Groups: https://groups.google.com/g/archivematica
