### ISSUE TITLE
Problem: specify permissions required when using S3 as a storage space

### ISSUE THREAD

**Issue by helrond** [archivematica/Issues#1661]
**Version of the documentation**
Archivematica Storage Service 0.21.1

**Page (and section, if applicable) where the issue occurs**
https://www.archivematica.org/en/docs/storage-service-0.21/administrators/#s3-amazon

**Description of the issue**
Specific permissions are required when using AWS S3 as a storage service space, but these are not documented anywhere. As far as I know they are:
- `s3:PutObject`
- `s3:ListBucket`
- `s3:GetBucketLocation`
- `s3:GetObject`

**Suggested fix**
Add an additional section here which specifies which permissions need to be associated with the IAM user whose credentials are used to connect to S3.

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by helrond** [comment]
This is even better than I could have imagined, thank you @replaceafill!

**Comment by replaceafill** [comment]
This has been fixed in https://github.com/artefactual/archivematica-storage-service-docs/commit/35c4fc6151a333ec3ef02ee4a4448c113adeeb73.
