### ISSUE TITLE
Question: Web API Delete Request Creation and Approval Process

### ISSUE THREAD

**Issue by nakamura196** [archivematica/Issues#1662]
Thank you for developing such a wonderful system.

I was able to create a delete request using the web API of the storage service.

Can you approve them via API? I was able to do it through the GUI, but I couldn't figure out how to do it using a web API.

<img width="1396" alt="image" src="https://github.com/archivematica/Issues/assets/5351691/943d59d9-6b1b-4355-9729-bc7143647a72">

**Comment by replaceafill** [comment]
No, it's not possible to approve the deletion requests through the Storage Service API yet.

Hope these are helpful for reference:
* https://github.com/artefactual/archivematica-storage-service/issues/250
* https://github.com/archivematica/Issues/issues/1153
* https://github.com/artefactual-labs/ops-helpers/tree/2000a0d30865418b811cef73e71f71345c6af8ef/am-delete-aip
