### ISSUE TITLE
Problem: Archivematica 1.15.1 Ubuntu packages are not available yet

### ISSUE THREAD

**Issue by jens-st** [archivematica/Issues#1666]
**Expected behaviour**
* Archivematica 1.15.1 was released November 2023 (https://github.com/artefactual/archivematica/releases/tag/v1.15.1), includes security & bug fixes
* Archivematica Ubuntu 1.15.1 packages available for upgrade from older versions

**Current behaviour**
* Only Archivematica 1.15.0 can be found (https://packages.archivematica.org/1.15.x/)
* Q: Will Artefactual provide Ubuntu packages for current Archivematica releases going forward?

**Steps to reproduce**
* check https://packages.archivematica.org/1.15.x/ubuntu/pool/main/a/archivematica/ or
* add repos as described in https://www.archivematica.org/en/docs/archivematica-1.15/admin-manual/installation-setup/installation/install-ubuntu/#ubuntu-22-04-jammy-installation-instructions
* `sudo apt update`
* `sudo apt list --upgradable`

**Your environment (version of Archivematica, operating system, other relevant details)**
* Ubuntu 22.04 Server with package installation of Archivematica 1.15.0 & Storage Service 0.21.0

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged (if applicable)
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by replaceafill** [comment]
I just published Archivematica 1.15.1 and Storage Service 0.21.1 packages for Ubuntu 22.04 and Rocky 9.
