### ISSUE TITLE
Problem: populate_aip_stored_dates SS command python requirements are not installed

### ISSUE THREAD

**Issue by scollazo** [archivematica/Issues#1670]
**Expected behaviour**

The [populate_aip_stored_dates](https://github.com/artefactual/archivematica-storage-service/blob/qa/0.x/storage_service/common/management/commands/populate_aip_stored_dates.py) command works 

**Current behaviour**

The command fails with

```
 < Omitted output>

  File "/src/storage_service/common/management/commands/populate_aip_stored_dates.py", line 15, in <module>
    import pytz
ModuleNotFoundError: No module named 'pytz'
```

**Steps to reproduce**

Run the command with:

```
sudo -u archivematica bash -c " \
    set -a -e -x
    source /etc/default/archivematica-storage-service || \
        source /etc/sysconfig/archivematica-storage-service \
            || (echo 'Environment file not found'; exit 1)
    cd /usr/lib/archivematica/storage-service
    /usr/share/archivematica/virtualenvs/archivematica-storage-service/bin/python manage.py populate_aip_stored_dates
";

```
**Your environment (version of Archivematica, operating system, other relevant details)**

SS stable/0.21.x on Ubuntu 22.04

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged (if applicable)
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by replaceafill** [comment]
We dropped the `pytz` dependency and adjusted the command to use Django's timezone calculation.
