### ISSUE TITLE
Problem: Filename Changes documentation does not reflect accurate PREMIS information captured in METS file and logs

### ISSUE THREAD

**Issue by ravengermain** [archivematica/Issues#1672]
**Version of the documentation**
Archivematica 1.15.0

**Page (and section, if applicable) where the issue occurs**
https://www.archivematica.org/en/docs/archivematica-1.15/user-manual/transfer/change-filenames/

**Description of the issue**

The documentation says that the PREMIS event type for filename changes will be labeled as "name cleanup" in the METS file, when it is actually labeled as "filename change"

**Suggested fix**

Documentation changes needed:

1. In the METS output table, `cleaned up name=` should be changed to `new name=`
2. Under the PREMIS event fragment, after `<premis:eventType>`, `name cleanup` should be changed to `filename change`
3. Under the "log file for name changes" bullet points at the bottom of the page, the locations should be changed from `filenameCleanup.log` to `filenameChanges.log`

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by replaceafill** [comment]
Fixed in https://github.com/artefactual/archivematica-docs/pull/459
