### ISSUE TITLE
Problem: Cannot set CSRF_TRUSTED_ORIGINS and USE_X_FORWARDED_HOST DJANGO env variables

### ISSUE THREAD

**Issue by mamedin** [archivematica/Issues#1675]
**Expected behaviour**

Both variables should be configurable:

* `USE_X_FORWARDED_HOST DJANGO`: Allows to use X_FORWARDED_* headers, especially useful when having a second reverse proxy.

* `CSRF_TRUSTED_ORIGINS`: Useful to add exceptions.

**Current behaviour**

They are using the default values, they cannot be set as environment variables.

**Steps to reproduce**

Try to configure a second reverse proxy or OIDC auth.

**Your environment (version of Archivematica, operating system, other relevant details)**

Ubuntu 22, AM qa/1.x, SS qa/0.x

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged (if applicable)
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by replaceafill** [comment]
These variables are now set in the `/etc/default/archivematica-*` files.
