### ISSUE TITLE
Problem: Default thumbnails are not generated in normalization

### ISSUE THREAD

**Issue by replaceafill** [archivematica/Issues#1682]
**Expected behaviour**

All modes of thumbnail normalization work.

**Current behaviour**

According to the [`Generate thumbnails` section of the documentation](https://www.archivematica.org/en/docs/archivematica-1.15/user-manual/administer/dashboard-admin/#generate-thumbnails) when `Yes` is selected as the value of the `Choose thumbnail mode` processing configuration setting:

> thumbnails will be generated according to the format rules in the FPR. Formats which do not have a rule will have a default thumbnail generated (grey document icon).

However, in the `Ingest` tab the `Normalize -> Normalize for thumbnails` job is marked as successful but the tasks for those formats without rules show an error like this:

```console
  File "/tmp/547569e3-17e1-474b-a6ee-00bb1c55616c", line 8
    DEFAULT_THUMBNAIL = \"\"\"
                             ^
SyntaxError: unexpected character after line continuation character
Failed: Using default thumbnail
Standard out: 
Standard error:   File "/tmp/547569e3-17e1-474b-a6ee-00bb1c55616c", line 8
    DEFAULT_THUMBNAIL = \"\"\"
                             ^
SyntaxError: unexpected character after line continuation character

[Errno 2] No such file or directory: '/var/archivematica/sharedDirectory/currentlyProcessing/demo-03f22bcc-47a6-4e95-9dce-d4ba59902d8d/thumbnails/5745c15a-8ae4-4bdc-86ca-492d1331f426.jpg'
```

**Steps to reproduce**

1. Create a transfer using the `SampleTransfer/DemoTransferCSV` sample transfer.
2. Set the `Choose thumbnail mode` processing configuration setting as `Yes`.
3. See the output of the `Normalize -> Normalize for thumbnails` job in the Ingest tab and notice the failed tasks for the  `piiTestDataCreditCardNumbers.txt` and `bird.mp3` files.
4. Check the `thumbnails` folder of the AIP and notice the `piiTestDataCreditCardNumbers.txt` and `bird.mp3` files don't have thumbnail files.

**Your environment (version of Archivematica, operating system, other relevant details)**

https://github.com/artefactual/archivematica/commit/37ba46a6f90d64282f9f8f94acc635949c4c52a1 but also reproduced in the Archivematica sandbox which is currently running 1.13.2.

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged (if applicable)
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by sromkey** [comment]
Working as expected now
