### ISSUE TITLE
PROBLEM rocky9/rhel9 storage-service package install incorrect owner group of/usr/lib/archivematica/storage-service/assets

### ISSUE THREAD

**Issue by dmnyu** [archivematica/Issues#1700]
**Expected behaviour**
owner/group /usr/lib/archivematica/storage-service/assets should be **archivematica:archivematica** during package installation of archivematica-storage-service

**Current behaviour**
owner/group /usr/lib/archivematica/storage-service/assets is **root:root**

this causes the `/usr/share/archivematica/virtualenvs/archivematica/bin/python manage.py collectstatic` step of the package install to fail and the service to unable to start. currently using chown after install to correct

**Steps to reproduce**
install the archivematica-storage-service,  view ownership /usr/lib/archivematica/storage-service/assets

**Your environment (version of Archivematica, operating system, other relevant details)**
Tested on Rocky9.4

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged (if applicable)
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by replaceafill** [comment]
Thank you for reporting this. I'm able to see the problem **after** installing both DEB and RPM packages when I try to run the `collectstatic` command.

> this causes the /usr/share/archivematica/virtualenvs/archivematica/bin/python manage.py collectstatic step of the package install to fail and the service to unable to start. 

The installation process doesn't fail for me though. I tested with the [installation scripts](https://github.com/artefactual/archivematica-docs/tree/586fe79656cf09bda6630688d637f20d8d5d81f2/admin-manual/installation-setup/installation/scripts) of the `archivematica-docs` repository in new Rocky Linux 9.4 and Ubuntu 22.04 VMs.

Would you be able to share the trace of the error you get to see what I'm missing?

**Comment by dmnyu** [comment]
@replaceafill Sorry I could have described that better. The installation completes and the service starts, but I get a 502 in nginx. In nginx's error log, it's trying to load an asset. Let me reload my VM and I'll get you more thorough info.  I thought it manage.py was unable to run collectstatic.

**Comment by replaceafill** [comment]
I think to verify this issue we could use the [Archivematica RPM Packages Test](https://github.com/artefactual-labs/am-packbuild/actions/workflows/test-am-rpms.yml) workflow like this:

1. Click `Run workflow` and select the `dev/am-1.17.0` branch (associated with the PR that updates versions https://github.com/artefactual-labs/am-packbuild/pull/358)
2. Uncheck the `Build local packages` checkbox to download the packages instead of building them from scratch
3. Click the `Run workflow` button
4. Once the workflow run finishes:
    1. Inspect the `Install packages` step and confirm that:
        1. AM and SS were installed from the `packages.archivematica.org` repository
        2. Their versions are 1.17.0 and 0.23.0 (they're still RC1 packages)
        3. The `collectstatic` commands ran successfully after the packages were installed
    2. Inspect the `Test AM API - Get processing configurations` step worked
    3. Inspect the `Test SS API - Get pipeline count` step worked

**Comment by Dhwaniartefact** [comment]
We have verified this issue by running the [workflow](https://github.com/artefactual-labs/am-packbuild/actions/runs/11800301439) as described and it works as expected.
