### ISSUE TITLE
Problem: import_aip.py fails because it tries to set the GID the same as the UID for files in fix_ownership()

### ISSUE THREAD

**Issue by uofmsean** [archivematica/Issues#1703]
**Expected behaviour**
GID of files should be set correctly using am_gid and not am_uid.

**Current behaviour**
fix_ownership() tries to set the UID and GID to the same value since it uses am_uid twice.

**Steps to reproduce**
See the following source line with the bug:
[import_aip.py line 298](https://github.com/artefactual/archivematica-storage-service/blob/29b529095723f350027bd6990754b9ee4af3e101/storage_service/common/management/commands/import_aip.py#L298)

**Your environment (version of Archivematica, operating system, other relevant details)**
Archivematica 1.16
Storage Service 0.22.0
Red Hat Enterprise Linux release 9.4 (Plow)

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged (if applicable)
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by Dhwaniartefact** [comment]
Tested and verified this issue. LGTM !
