### ISSUE TITLE
Problem: ffmpeg not found on a clean install in rocky linux 9 

### ISSUE THREAD

**Issue by juanpablomora-logalty** [archivematica/Issues#1719]
**Expected behaviour**

Complete the installation steps in https://www.archivematica.org/es/docs/archivematica-1.16/admin-manual/installation-setup/installation/install-rocky/#install-pkg-rocky 

**Current behaviour**

Error when install mcp-cliente:

```
# sudo -u root yum install -y archivematica-mcp-client
Last metadata expiration check: 0:16:39 ago on Thu 21 Nov 2024 09:00:24 AM UTC.
Error:
 Problem: package archivematica-mcp-client-1.16.0-1.x86_64 from archivematica requires ffmpeg, but none of the providers can be installed
  - package ffmpeg-5.1.3-1.el9.x86_64 from archivematica-extras requires ffmpeg-libs(x86-64) = 5.1.3-1.el9, but none of the providers can be installed
  - conflicting requests
  - nothing provides libdav1d.so.6()(64bit) needed by ffmpeg-libs-5.1.3-1.el9.x86_64 from archivematica-extras
(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)
```

**Steps to reproduce**

In my case, follow the installation link. The instance is clean, with updates.

**Your environment (version of Archivematica, operating system, other relevant details)**

OS version:

# cat /etc/os-release
NAME="Rocky Linux"
VERSION="9.5 (Blue Onyx)"
ID="rocky"
ID_LIKE="rhel centos fedora"
VERSION_ID="9.5"
PLATFORM_ID="platform:el9"
PRETTY_NAME="Rocky Linux 9.5 (Blue Onyx)"
ANSI_COLOR="0;32"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:rocky:rocky:9::baseos"
HOME_URL="https://rockylinux.org/"
VENDOR_NAME="RESF"
VENDOR_URL="https://resf.org/"
BUG_REPORT_URL="https://bugs.rockylinux.org/"
SUPPORT_END="2032-05-31"
ROCKY_SUPPORT_PRODUCT="Rocky-Linux-9"
ROCKY_SUPPORT_PRODUCT_VERSION="9.5"
REDHAT_SUPPORT_PRODUCT="Rocky Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="9.5"

---

**Comment by replaceafill** [comment]
The [`Archivematica RPM Packages Test` workflow](https://github.com/artefactual-labs/am-packbuild/actions/workflows/test-am-rpms.yml) currently fails with:

```console
+ sudo -u root yum install -y archivematica-mcp-client
Last metadata expiration check: 0:00:55 ago on Tue Dec  3 03:07:35 2024.
Error: 
 Problem: package archivematica-mcp-client-1.16.0-1.x86_64 from archivematica requires ffmpeg, but none of the providers can be installed
  - package ffmpeg-5.1.3-1.el9.x86_64 from archivematica-extras requires ffmpeg-libs(x86-64) = 5.1.3-1.el9, but none of the providers can be installed
  - conflicting requests
  - nothing provides libdav1d.so.6()(64bit) needed by ffmpeg-libs-5.1.3-1.el9.x86_64 from archivematica-extras
(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)
Error: Process completed with exit code 1.
```

It seems like the `libdav1d` package has been updated in the Rocky Linux 9 repository:

```console
[root@0ef58ea14cbb /]# yum info libdav1d
Last metadata expiration check: 0:05:14 ago on Tue Dec  3 21:14:02 2024.
Available Packages
Name         : libdav1d
Version      : 1.5.0
Release      : 2.el9
Architecture : x86_64
Size         : 601 k
Source       : dav1d-1.5.0-2.el9.src.rpm
Repository   : epel
Summary      : Library files for dav1d
URL          : https://code.videolan.org/videolan/dav1d
License      : BSD-2-Clause AND ISC
Description  : Library files for dav1d, the AV1 cross-platform Decoder.
```

and it provides a higher version of the expected requirement:

```console
[root@0ef58ea14cbb /]# rpm -qp --provides libdav1d-1.5.0-2.el9.x86_64.rpm 
libdav1d = 1.5.0-2.el9
libdav1d(x86-64) = 1.5.0-2.el9
libdav1d.so.7()(64bit)
```

**Comment by replaceafill** [comment]
This has been addressed in the `1.17.x` package repository by setting [newer versions of `ffmpeg`](https://github.com/artefactual-labs/am-packbuild/pull/361/files). I'll leave this issue open until we address it in previous releases.

**Comment by juanpablomora-logalty** [comment]
Thanks @replaceafill ,  after a "yum update"  I could complete the installation of  the archivematica-mcp-client module.

**Comment by mamedin** [comment]
rocky9-extras repos updated in 1.16.x and 1.17.x.

When checking in test VMs, it needed a `yum clean all` before the upgrade because the repo changed.
