### ISSUE TITLE
Deprecate the Archivists' Toolkit DIP upload functionality

### ISSUE THREAD

**Issue by sallain** [archivematica/Issues#174]
**Please describe the problem you'd like to be solved.**
Archivists' Toolkit has been deprecated since 2013. At Artefactual we have been maintaining the Archivists' Toolkit DIP upload feature with no active development or testing since then. There are no plans to start testing or to fix any problems with the feature. As such, I'd like to propose that we come up with a way to deprecate the feature (which could then act as a template for deprecating other such features in the future)

**Describe the solution you'd like to see implemented.**
In the 1.8 release, mark the Archivists' Toolkit functionality as to-be-deprecated in the release notes and release communications.

In the 1.9 release, disable the functionality.

**Describe alternatives you've considered.**

**Additional context**

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Release documentation (e.g. release notes, wiki documentation, etc) regarding this issue has been written 👍

**Comment by helrond** [comment]
As an employee of the organization that funded this work (and one of the contributors to the development spec) I am strongly supportive of this change. In fact, I'm a little embarrassed that we didn't suggest it first. We haven't used Archivists' Toolkit in production for almost 5 years.

The suggested approach (mark as deprecated in 1.8, remove in 1.9) sounds eminently reasonable to me, and would allow plenty of time for community comment and for someone else to take responsibility for the code if necessary.

**Comment by sallain** [comment]
Thanks for the feedback, @helrond! And thank you so much for sponsoring the original feature!

**Comment by sevein** [comment]
This is an easy task and it would result in more than 1500 LoC removed!
I've put together a [branch](https://github.com/artefactual/archivematica/compare/qa/1.x...dev/issue-174-delete-at-support?expand=1) to see how much work it would be. It's mostly done, I'd need a couple of extra hours to complete the database migration and test the ArchivesSpace workflows to make sure I'm not breaking anything since there was some shared code - see the [TODO list](https://github.com/artefactual/archivematica/commit/39677916a98134566ae3e9ac55c9792eccad217a).

**Comment by sevein** [comment]
I've confirmed that AT's upload is broken. This is because the "upload-archivistsToolkit_v0.0" entry was removed from `archivematicaClientModules` in Archivematica v1.8.0.

**Comment by sevein** [comment]
For QA, make sure that AT's functionality is gone and test the integration with ArchivesSpace. They used to share a lot of code so it's good to confirm that it remains fully functional.

**Comment by corinnemrogers** [comment]
AT no longer given as an option

**Comment by corinnemrogers** [comment]
ASpace upload works.

**Comment by sallain** [comment]
Relevant documentation needs to be removed.
