### ISSUE TITLE
Problem: file formats allowed for "Zipped bag" are unclear

### ISSUE THREAD

**Issue by helrond** [archivematica/Issues#177]
**Version of the documentation**
1.7.2

**Page (and section, if applicable) where the issue occurs**
https://www.archivematica.org/en/docs/archivematica-1.7/user-manual/transfer/bags/#bags

**Description of the issue**
This section implies (through omission) that "Zipped bag" transfers must be `.zip` files, but other archive formats (for example `.tar.gz`) are allowed. I couldn't find documentation of which archive formats are or are not allowed.

**Suggested fix**
Specify explicitly which archive formats are allowed for "Zipped bag" transfers. Based on https://github.com/artefactual/archivematica/blob/stable/1.7.x/src/MCPClient/lib/clientScripts/extractBagTransfer.py#L38 it looks like tar with gzip and zip are allowed.

**Comment by sallain** [comment]
Thanks for this @helrond! I just added another bag-related documentation ticket, so I'll try to address this one, as well as #173 when I make that change.

**Comment by sallain** [comment]
Resolved via artefactual/archivematica-docs#238. Thanks again @helrond!
