### ISSUE TITLE
Problem: it's hard to maintain fpr-admin as a separate repo

### ISSUE THREAD

**Issue by sevein** [archivematica/Issues#181]
**Expected behaviour**
It should be easy to make changes to our `fpr` Django app.
Suggested solution: move `fpr` to dashboard.

**Current behaviour**
`fpr` lives in a separate [repo](https://github.com/artefactual/archivematica-fpr-admin) with its own releases. When we want to make a change, we usually submit a PR against fpr-admin, CR, merge, release, submit a PR against AM bumping the requirement, CR, merge... it's highly inconvenient!

**Your environment (version of Archivematica, OS version, etc)**
Any!

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Release documentation (e.g. release notes, wiki documentation, etc) regarding this issue has been written 👍

**Comment by sevein** [comment]
It'd be as easy as copying `fpr` into `src/dashboard/src` and adjusting the requirements. Once this is done, it'll also become easier to deal with some known issues like the problems with template inheritance and other issues like https://github.com/artefactual/archivematica-fpr-admin/issues/28, https://github.com/artefactual/archivematica-fpr-admin/issues/34...

**Comment by sevein** [comment]
Things that we need to consider during the migration:
- `south_migrations` can potentially be removed
- `load_data` should not be used in migrations (deprecated in Django 1.9!)
- `setup.py`, `testproject`, etc... would not be needed anymore
- Template inheritance should be reviewed (`_fpr_update_button.html`? `fpr/templates/app_layout.html:layout_fluid.html`?)
- Shared assets like datatables should be reviewed

**Comment by sevein** [comment]
I've done this as part of the work that I was doing in https://github.com/archivematica/Issues/issues/213.

**Comment by peterVG** [comment]
The Preservation Planning tab works as usual. Policy changes were successfully tested for Characterization, Event Details, Normalization, Transcription and Validation. 

There is a separate known issue (#485) for File Identification.
