### ISSUE TITLE
Problem: ARCHIVEMATICA_VERSION has not been updated yet to 1.8.0

### ISSUE THREAD

**Issue by sevein** [archivematica/Issues#183]
[It reads the following:](https://github.com/artefactual/archivematica/blob/f05e4bcf1b3f1336532822e80a30a04e768ba9ba/src/archivematicaCommon/lib/version.py#L1)

```
ARCHIVEMATICA_VERSION = (1, 7, 0)
```

It should be:

```
ARCHIVEMATICA_VERSION = (1, 8, 0)
```

A similar change is needed in SS to reflect the bump to `0.13.0`.

**Your environment (version of Archivematica, OS version, etc)**
f05e4bcf1b3f1336532822e80a30a04e768ba9ba

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Release documentation (e.g. release notes, wiki documentation, etc) regarding this issue has been written 👍

**Comment by sromkey** [comment]
Both the Dashboard and SS have been updated with their version numbers.
