### ISSUE TITLE
Problem: Ubuntu 14.04-specific configs are still present in dev branch

### ISSUE THREAD

**Issue by sevein** [archivematica/Issues#198]
We announced that [v1.7.2](https://wiki.archivematica.org/Archivematica_1.7.2_release_notes) would be the last release supported on Ubuntu 14.04. There's been already some work done to clean up trusty-specific configuration files, e.g. see the following commits:

- https://github.com/artefactual/archivematica/commit/a6bfc099daebf5c36ab7202a71f7f79bfd8d7583
- https://github.com/artefactual/archivematica/commit/066d958b98e10d84e00c80983c580af40e694ef4
- https://github.com/artefactual/archivematica-storage-service/commit/ee0fed54dda4880085bcc168bd642d884e1502b9
- https://github.com/artefactual/archivematica-storage-service/commit/4f3bc5cf43066633367e10851941087a94036f55

However, I've identified some remaining bits and I think it's worth to have an issue to track them properly. So far, this is what I've found:

- [x] SS: [requirements tweak](https://github.com/artefactual/archivematica-storage-service/blob/07ae87501b93f4c917f1c0a49dc76ba5c369039d/requirements/base.txt#L3-L6) for Ubuntu 14.04 that installs pip and setuptools
- [x] SS: trusty-specific instructions on [install's README](https://github.com/artefactual/archivematica-storage-service/tree/qa/0.x/install)
- [x] SS: old [debian](https://github.com/artefactual/archivematica-storage-service/tree/4f3bc5cf43066633367e10851941087a94036f55/debian) directory
- [x] AM: trusty-specific instructions on install's README files under [MCPServer](https://github.com/artefactual/archivematica/tree/540acf453d64a19bc7f2ca0513a79a82156f49a4/src/MCPServer/install), [MCPClient](https://github.com/artefactual/archivematica/tree/540acf453d64a19bc7f2ca0513a79a82156f49a4/src/MCPClient/install) and [Dashboard](https://github.com/artefactual/archivematica/tree/540acf453d64a19bc7f2ca0513a79a82156f49a4/src/dashboard/install) directories

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Release documentation (e.g. release notes, wiki documentation, etc) regarding this issue has been written 👍

**Comment by ablwr** [comment]
I noted in this issue that we need to heed the docs as well!: https://github.com/archivematica/Issues/issues/238
