### ISSUE TITLE
Problem: Metsrw version needs to be bumped to 0.2.2 prior to release

### ISSUE THREAD

**Issue by ross-spencer** [archivematica/Issues#200]
Prior to release, make sure that the `metsrw` library version is bumped. To clarify, `0.2.2` or `0.3.0` (which specific point number is not clear to me at present)

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Release documentation (e.g. release notes, wiki documentation, etc) regarding this issue has been written 👍

**Comment by ross-spencer** [comment]
Resolved by: https://github.com/artefactual-labs/mets-reader-writer/commit/40d8ad0acf5aeada3973b2ca93e4b5e02ec0bbb2

**Comment by ross-spencer** [comment]
Connected to: https://github.com/artefactual/archivematica/issues/1147

**Comment by sromkey** [comment]
is this superseded by #208 ?

**Comment by ablwr** [comment]
I'm going to assume this is superceded by #208
