### ISSUE TITLE
Problem: Installation & upgrade docs need 1.8 package details

### ISSUE THREAD

**Issue by joel-simpson** [archivematica/Issues#203]
**Version of the documentation**
1.8

**Page (and section, if applicable) where the issue occurs**
Installation page for each type of supported deployment: 
1) for Centos packages: 
https://www.archivematica.org/en/docs/archivematica-1.8/admin-manual/installation-setup/installation/install-centos/#install-pkg-centos (section starting at line 73) 

2) for Ubuntu packages: 
https://www.archivematica.org/en/docs/archivematica-1.8/admin-manual/installation-setup/installation/install-ubuntu/#install-pkg-ubuntu

3) Upgrade instructions
https://www.archivematica.org/en/docs/archivematica-1.8/admin-manual/installation-setup/upgrading/upgrading/#upgrade (update each section by type of deployment)

(I reviewed the installation instructions using Ansible but there doesn't appear to be any need to update that. Those changes need to be made in the deploy-pub repo)

**Description of the issue**
The 1.8 documentation for installation and upgrades links to packages for 1.7. 

**Suggested fix**
replace with urls and references to 1.8 as needed.

**Comment by sallain** [comment]
Note: make sure to remove Ubuntu 14.04 references as per #238

**Comment by mamedin** [comment]
Santi found a small problem enabling the ElasticSearch service on boot for Bionic. We need to change this command line in documentation to use systemd instead of old system5 command:

https://github.com/artefactual/archivematica-docs/blame/1.8/admin-manual/installation-setup/installation/install-ubuntu.rst#L191
