### ISSUE TITLE
Problem: new fpr identification commands haven't been made available in the workflow

### ISSUE THREAD

**Issue by sevein** [archivematica/Issues#204]
**Expected behaviour**
AM should be able to use the new identification commands made available via https://github.com/artefactual/archivematica/commit/29a33f0cdfe0fdabaabe23833d62916de7118810#diff-c4ac691399b972d58c904647ed225436 (new releases of siegfried and fido).

**Current behaviour**
`Identify file format` fails with the following error:

    IDCommand with UUID df074736-e2f7-4102-b25d-569c099d410c does not exist.

@mamedin reported this issue. `df074736-e2f7-4102-b25d-569c099d410c` is now disabled and replaced by `75290b14-2931-455f-bdde-3b4b3f8b7f15` but the workflow is still pointing to the former.

This is likely also true for in `fido`.

**Your environment (version of Archivematica, OS version, etc)**
qa/1.x: [dc0ffc7bcf1a3290bc528e18cd32c04c0814e923](https://github.com/artefactual/archivematica/commit/dc0ffc7bcf1a3290bc528e18cd32c04c0814e923)

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Release documentation (e.g. release notes, wiki documentation, etc) regarding this issue has been written 👍

**Comment by sevein** [comment]
For reference, we've done this before here: https://github.com/artefactual/archivematica/blob/stable/1.7.x/src/dashboard/src/main/migrations/0044_update_idtools.py.

The process of updating tools is convoluted, we need to improve it but for this release I'd just suggest to address it as we've done before.

**Comment by ablwr** [comment]
Would be nice to merge in the already-required updates to FIDO and FPR before I send a PR for this, although I can get started still https://github.com/artefactual/archivematica/pull/1269

**Comment by peterVG** [comment]
is resolved by artefactual/archivematica#1269 on Xenial, Bionic, and CentOS (but not RPM).
