### ISSUE TITLE
Problem: Metsrw version needs to be bumped to 0.2.3 prior to release

### ISSUE THREAD

**Issue by jrwdunham** [archivematica/Issues#208]
---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Release documentation (e.g. release notes, wiki documentation, etc) regarding this issue has been written 👍

**Comment by ablwr** [comment]
This needs to be bumped in Archivematica dependencies as well. So should this be moved back to "in progress"? I don't see a separate issue for doing that.

**Comment by ross-spencer** [comment]
Hi @ablwr it was completed as part of the Dataverse work: https://github.com/artefactual/archivematica/blob/78d6ed7b2a33d781396515e3f9d37279d438a4dd/src/MCPClient/requirements/base.txt#L9

**Comment by ablwr** [comment]
Oh it's a dependency is the dashboard too, should it change there? https://github.com/artefactual/archivematica/blob/stable/1.7.x/src/dashboard/src/requirements/base.txt#L20

**Comment by ross-spencer** [comment]
@ablwr In short, it could be, but I'm not sure it needs to be bumped at present. Entirely a preference based decision I think. 

The update was for a Microservice in the MCP Client so testing can remain focused on that. The Dashboard could be bumped if there were a perceived benefit.
