### ISSUE TITLE
Problem: make db no longer just works in am.git

### ISSUE THREAD

**Issue by jrwdunham** [archivematica/Issues#210]
**Expected behaviour**

When I run `make db` in a Docker Compose am.git deploy of Archivematica, I should be able to connect to the MySQL shell.

**Current behaviour**

It fails. `ERROR 2003 (HY000): Can't connect to MySQL server on '127.0.0.1' (61)`

**Steps to reproduce**

Try it. Run `make db`. Workaround is to execute `mysql -h127.0.0.1 --port=61701 -uroot -p12345`.

**Your environment (version of Archivematica, OS version, etc)**

Branch stable/1.7.x of am.git.

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Release documentation (e.g. release notes, wiki documentation, etc) regarding this issue has been written 👍

**Comment by sevein** [comment]
I've updated `make db` so it uses the MySQL client inside the container,
- `stable/1.7.x`: https://github.com/artefactual-labs/am/commit/5984aee49a53d127ec8628747352395d1c6a247f
- `master`: https://github.com/artefactual-labs/am/commit/3b0def6b8854a9e6143589ec56e106afe2e7e996
