### ISSUE TITLE
Problem: FPR is displaying duplicate commands

### ISSUE THREAD

**Issue by sallain** [archivematica/Issues#212]
**Expected behaviour**
On the Identification > Commands page, I expect to see one command for each tool - Identify by File Extension, Identify using Fido, Identify using Siegfried.

**Current behaviour**
There are duplicate commands for Fido and Siegfried. One of the commands for each is disabled. @sevein has identified this as old code that wasn't properly removed when the tool was updated for 1.7.2.

**Steps to reproduce**
Open the Preservation Planning tab and navigate to Identification > Commands.

**Your environment (version of Archivematica, OS version, etc)**
Archivematica 1.7.2

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Release documentation (e.g. release notes, wiki documentation, etc) regarding this issue has been written 👍

**Comment by sevein** [comment]
Not sure if we can make this happen in a timely manner. I made a first attempt in https://github.com/artefactual/archivematica-fpr-admin/pull/92 but it has revealed some other issues os I suggest to revisit this later.

**Comment by sevein** [comment]
Fixed in https://github.com/artefactual/archivematica/pull/1342.
