### ISSUE TITLE
Problem: fpr app import and writes to main.models

### ISSUE THREAD

**Issue by sevein** [archivematica/Issues#213]
This happens as a result of saving a `fpr.IDCommand`. I believe the goal was to update the identification microservice so its list of choices is updated according to changes made in the `fpr` app.

This needs to be revisited for a couple of reasons:
- Workflows as encoded in the database are supposed to be inmutable
- `main.models.MicroServiceChoiceReplacementDic` is being deprecated, potentially in AM19 - see https://github.com/artefactual/archivematica/pull/1251

This is related to #181 which suggests to move `fpr` to the Dashboard project.

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Release documentation (e.g. release notes, wiki documentation, etc) regarding this issue has been written 👍

**Comment by sevein** [comment]
For QA, we have to make sure that identification commands can still be updated, i.e. the form submits successfully and the changes are saved. However, the workflow isn't going to be updated - the list of choices presented to the user during identification is going to remain the same. This is a limitation that could be improved in future work.

**Comment by peterVG** [comment]
Identification commands can be edited from the Preservation Planning tab using the "Replace" option. Changes are saved.

**Comment by peterVG** [comment]
see issue #485 for follow-up
