### ISSUE TITLE
Problem: most categories are missing from Preservation Planning

### ISSUE THREAD

**Issue by sromkey** [archivematica/Issues#218]
**Expected behaviour**

When I click on Preservation Planning I should see all the normal categories of preservation actions (normalization, validation, characterization, etc etc)

**Current behaviour**

I only see Formats/Groups, Identification and Format Policy Registry

**Your environment (version of Archivematica, OS version, etc)**
 
qa/1.x deployed on centos 

---

**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by sevein** [comment]
The fix is simple, see https://github.com/artefactual/archivematica-fpr-admin/pull/93.

However, for this to be QA'ed the following needs to happen:
1. https://github.com/artefactual/archivematica-fpr-admin/pull/93 is merged
2. fpr-admin is released
3. new release of fpr-admin is incorporated in AM

**Comment by ablwr** [comment]
This will be resolved when #204 is merged.

**Comment by peterVG** [comment]
is resolved by https://github.com/artefactual/archivematica/pull/1269
