### ISSUE TITLE
Problem: in bionic, ng binary (nailgun) cannot be found

### ISSUE THREAD

**Issue by sevein** [archivematica/Issues#223]
**Current behaviour**

When AM's `fpr-admin` calls FITS, it does it via [Nailgun](https://github.com/facebook/nailgun).

This is how the FPR script looks like as in its database:

```
new_cmd = (
    'set -euo pipefail\n'
    'IFS=$\'\\n\\t\'\n'
    'tempdir=$(mktemp -d %tmpDirectory%fits.XXXXXX)\n'
 ➡️ 'ng edu.harvard.hul.ois.fits.Fits' 
    ' -i "%relativeLocation%"'
    ' -o "$tempdir/fits.xml" >/dev/null\n'
    'cat "$tempdir/fits.xml"\n'
    'rm -r "$tempdir"')
```

It expects that the binary is called `ng`. Ubuntu doest not provision `ng` - only `ng-nailgun`. In Bionic, we're aiming to use the distro package. This is also true in Xenial. We didn't realize I believe because we were using the package provided by `ubuntu-externals` which provided the `ng` binary, as in `centos-extra`.

**This could break file characterization.** I think that this bug hadn't been revealed during QA yet because somehow it's been shadowed by https://github.com/archivematica/Issues/issues/222. @jrwdunham however experienced this issue in the Docker image that it's only using the `nailgun` package, `nailgun-client` is not being installed.

**Steps to reproduce**

```
$ docker run --rm -it ubuntu:bionic bash
$ apt update
$ apt install nailgun
$ dpkg -L nailgun | grep bin
/usr/bin
/usr/bin/ng-nailgun
$ ng
bash: ng: command not found
```

Relates to https://github.com/archivematica/Issues/issues/222.

**Your environment (version of Archivematica, OS version, etc)**

qa/1.x

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by sevein** [comment]
I'm not sure what's the best way to solve this. I think this is something that we need to discuss with @mamedin. Providing a `ng` alias could work but is that the right thing to do? `fpr-admin` could also learn how to use `ng-nailgun` if `ng` is unavailable. Two very different solutions, solving the issue at different layers. What would you do?

**Comment by scollazo** [comment]
In ubuntu packages, we could use `update-alternatives` to provide the `ng` command as an alias to `ng-nailgun`, and the same situation happens in other mcp-client scripts with `7za` (Centos)/`7z` (Ubuntu). We solved it in the docs, by adding a [symbolic link](https://github.com/artefactual/archivematica-docs/blame/1.7/admin-manual/installation-setup/installation/install-centos.rst#L227) from one to other.

I would prefer your approach, choosing the correct program name as part of the mcp-c script, instead of customizing the OS for the script to work.

**Comment by ablwr** [comment]
Inadvertently tested this yesterday while testing FITS on all platforms. Ran into this, rebuild with latest, and now is fine.

**Comment by ablwr** [comment]
This upgrade seems to run fine, and FITS runs successfully sometimes when performing Characterize & Extract on the contents of SIPs, but sometimes it breaks. It also breaks when running Characterize & Extract on on metadata files, during the Process Metadata Directory service. 

The error messages are different between Ubuntu and CentOS.

CentOS and Ubuntu 16.04: 
`Command FITS failed with exit status -11; stderr:`

Ubuntu 18.04 is more verbose, but ends with:
`Command FITS failed with exit status 131; stderr:`

I'm not sure if this is necessarily related to this issue, though, as `ng` is installed and running. However, `ng-nailgun` is not a command I can call from the terminal. I could make a new issue about this, and consider this one resolved. Whatever you think is best!

**Comment by ablwr** [comment]
To follow up on this a little bit...

Bionic: accepts ng and ng-nailgun
Xenial: accepts ng, doesn't think ng-nailgun is installed
CentOS: accepts ng, has never heard of ng-nailgun

**Comment by sevein** [comment]
> However, ng-nailgun is not a command I can call from the terminal. I could make a new issue about this, and consider this one resolved. Whatever you think is best!

I agree, making a new issue seems like a good idea! Thanks.

**Comment by ablwr** [comment]
I did, as you can see.

Now, is the expectation that all envs should understand both `ng` and `ng-nailgun`? If so, this should still be open. If all of them accepting `ng`, then we can move on.

**Comment by mamedin** [comment]
Hi, I think we can create a new bionic package called, for example, `nailgun-archivematica` that runs the `update-alternatives` command to create the `ng-nailgun` symlink.

Then we can remove the `nailgun-client` dependency from bionic osdeps and add this new package.

**Comment by ablwr** [comment]
Should this go back to Ready or In Progress instead of Review?

**Comment by sevein** [comment]
The characterization script now uses ng or ng-nailgun depending which is available. I think this is done, as we've confirmed the new script is doing its work. Related issues #222 and #247 are still open though.
