### ISSUE TITLE
Problem: errors building frontend apps in Compose dev environment in Docker for Mac

### ISSUE THREAD

**Issue by sevein** [archivematica/Issues#226]
**Expected behaviour**
Archivematica's development environment (Compose) should be able to build the front-end apps inside the Dashboard container.

**Current behaviour**
Mac users running our [Compose dev environment](https://github.com/artefactual-labs/am) have experienced issues at the build stage (`make bootstrap` and `bootstrap-dashboard-frontend` in particular).

[npm](https://www.npmjs.com/) seems unable to build successfully (`npm install`) when `/src/dashboard` is a volume shared by the host machine. This could be a limitation in the way that npm operates with its `node_modules` directory.

This issue replaces:
- https://github.com/artefactual-labs/am/issues/69
- https://github.com/artefactual-labs/am/issues/49
- https://github.com/artefactual-labs/am/issues/4

@jrwdunham has had some success using yarn instead of npm: https://github.com/artefactual-labs/am/pull/70.

Also, both yarn (plug'n'play) and npm (tink) seem to be working on similar projects where they stop using `node_modules`. Not sure if that's a solution to our problem but it's worth investigating.

**Your environment (version of Archivematica, OS version, etc)**
Compose dev environment.

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by replaceafill** [comment]
Closing this since the [old Compose development environment](https://github.com/artefactual-labs/am) is not maintained anymore.
