### ISSUE TITLE
Problem: Archivematica cannot upload DIPs to Binder

### ISSUE THREAD

**Issue by jrwdunham** [archivematica/Issues#23]
**Please describe the problem you'd like to be solved.**

Archivematica has no mechanism built in for uploading DIPs to Binder. This feature was introduced in the MoMA-sponsored branches of Archivematica and is not available in public releases.

**Describe the solution you'd like to see implemented.**

We need to create a PR that brings the relevant changes (commits) from the appropriate branches into qa/1.x so that these commits will be present in a future Archivematica release.

**Additional context**

Because there are four MoMA-related branches, it is not obvious which branch contains the changes that we need.  **`dev/1.6.x-moma`** appears to be the correct branch to target: it is the same as `dev/issue-9250-moma-rebase` but with four additional commits. The following commits from that branch appear to be the most relevant for bringing in the "Upload to Binder" functionality:

- "Transfer: Store access system ID": 3a7e56cb8d57a828233ac7c1c486e1f9300e3b06
- "Cleanup": 15cb8d1eacdf821850517d18959e380b1075e290
- "Upload to AtoM: Use access_system_id instead of accession no": 0fa2fb4392f8e8ac54a8939a83d875db96bfbbe9
- "JS: automatically fill in AtoM upload form": fa54b3014cb63f0a656d37624f31d93137a8a43f

Here is a brief analysis of the relevant branches.

- branches:
    - dev branch [dev/1.6.x-moma](https://github.com/artefactual/archivematica/commits/dev/1.6.x-moma)
    - dev branch [dev/issue-9250-moma-rebase](https://github.com/artefactual/archivematica/commits/dev/issue-9250-moma-rebase) and accompanying [PR 366](https://github.com/artefactual/archivematica/pull/366)
    - qa branch [qa/1.5.x-moma](https://github.com/artefactual/archivematica/commits/qa/1.5.x-moma)
    - qa branch [qa/1.5.x-moma-updates](https://github.com/artefactual/archivematica/commits/qa/1.5.x-moma-updates)

- `dev/1.6.x-moma` is the same as `dev/issue-9250-moma-rebase` but with four additional commits:

          $ git log --left-right --graph --cherry-pick --oneline dev/1.6.x-moma...dev/issue-9250-moma-rebase 
          < 312c382 Fix ldap import
          < 49917bc Settings: rename LDAP file
          < 2ee4748 Move custom LDAPBackend to contrib.auth
          < ad18d92 django-mysqlpool: unlimited max_overflow #10622

- `qa/1.5.x-moma` and `qa/1.5.x-moma-updates` are very similar:
    - `qa/1.5.x-moma-updates` has one commit that `qa/1.5.x-moma` does not: `c85f6b7`
    - `qa/1.5.x-moma` has four commits that `qa/1.5.x-moma-updates` does not:

          $ git log --left-right --graph --cherry-pick --oneline qa/1.5.x-moma...qa/1.5.x-moma-updates
          < 685ad01 MoMA: exclude hidden files in bag checks
          < 78e2c05 Unzipped Bag: Restructure doesn't move processingMCP
          < 2f558fa MCPClient: add ._.DS_Store to removableFiles
          < 2dafcdb moved removeUnneededFiles config to clientConfig.conf and added .DS_Store
          < aedc221 clientScripts: use valid sender e-mail address

**Comment by sevein** [comment]
Hopefully we can remove all these branches once they're not needed?

**Comment by jrwdunham** [comment]
@sevein yes, but unfortunately I think they're still needed until the MoMA work gets brought into mainline. 

Pending QA, merged PR 1212 should resolve this issue.

**Comment by sallain** [comment]
Testing uploads to artwork records worked like a dream :slightly_smiling_face: 

**Test 1 - automated upload to an artwork record**
1. Create a transfer and enter `ar:2` into the Access system ID box.
2. Processed transfer with normalize set to "normalize for access" and DIP upload set to "Upload DIP to AtoM/Binder".
3. Once complete, check Binder - AIP has been uploaded and connected to artwork record 2.

**Test 2 - unautomated upload to an artwork record**
1. Create a transfer but leave Access system ID box blank.
2. Processed transfer with normalize set to "normalize for access" and DIP upload set to "None".
3. At the DIP upload microservice, choose "DIP upload to AtoM/Binder" and enter `ar:2` in the popup.
4. Once complete, check Binder - AIP has been uploaded and connected to artwork record 2.

**Test 3 - hybrid upload to an artwork record**
1. Create a transfer and enter `ar:2` into the Access system ID box.
2. Processed transfer with normalize set to "normalize for access" and DIP upload set to "None".
3. At the DIP upload microservice, choose "DIP upload to AtoM/Binder". The popup should not appear; it should use the access system ID entered in step 1.
4. Once complete, check Binder - AIP has been uploaded and connected to artwork record 2.

However, I wasn't able to upload to a technology record :disappointed: 

**Test 4 - uploading to a technology record**
1. Create a transfer and enter "tr:100" into the Access system ID box.
2. Processed transfer with normalize set to "normalize for access" and DIP upload set to "Upload DIP to AtoM/Binder".
3. Archivematica will display a success for DIP upload. However, the AIP has not been uploaded to Binder - it's not in the list of AIPs and not linked to the technology record.

**Comment by ablwr** [comment]
I also tried to upload a technology record through the Access system ID box (tr:638) and was not able to get it to succeed.

**Comment by sallain** [comment]
@ablwr I woke up in the middle of the night and realized that this may be because we only created artwork records in Mockable.io, not technology records.

**Comment by sallain** [comment]
@ablwr But wait, technology records wouldn't come from TMS, right? They'll always be created in Binder. So that doesn't make sense... I think... :thinking:

**Comment by sevein** [comment]
I've added @jraddaoui, hopefully he can help us QA this one?

**Comment by jraddaoui** [comment]
I could not find anything obvious in the related code from Binder or Archivematica. I'll give it a try locally tomorrow.

**Comment by jraddaoui** [comment]
Hi @sallain, @ablwr,

As you mention, Technology Records don't come from the TMS, they need to be created in Binder first and use the ID that's generated in there as the access system ID.

If you made your tests over http://binder-atom.archivematica.org/drmc, the ID of the only Tech. Record in that site is `2044`:

http://binder-atom.archivematica.org/drmc/technology-records/2044

I tested locally and it worked for me but, please, if you could test it again to verify that it's not just me, that would be great.

Thanks!

**Comment by ablwr** [comment]
Ahhhh! Thanks for this. I’ll work on making that clear when I document this process!

**Comment by sallain** [comment]
Okay, this works! I was using the wrong identifier.

@ablwr I've written some docs already, and I think I'm going to clarify this TR process today just to get it done! But any additions later are, of course, welcome.

**Comment by sallain** [comment]
Documented and added to release notes.
