### ISSUE TITLE
Problem: Archivematica v1.8.0 translations not updated yet

### ISSUE THREAD

**Issue by sevein** [archivematica/Issues#231]
Action items:

- [x] Extract messages and push to Transifex:
- [x] **Call for translators!**
- [x] Pull translations, include new languages in application if needed.
  - [x] https://github.com/artefactual/archivematica/pull/1299
  - [x] https://github.com/artefactual/archivematica/pull/1298
  - [x] https://github.com/artefactual/archivematica-fpr-admin/pull/100
  - [x] https://github.com/artefactual/archivematica-storage-service/pull/421
  - [x] Docs and website too!

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by sevein** [comment]
This is ready for QA!

Thinks you can test:
- Changing languages in Dashboard.
  - Make sure that the appraisal tab, transfer browser and fpr-admin are also being translated because those are managed separately.
- Changing languages in Storage Service.
- Changing languages in https://www.archivematica.org.
  - Translated contents under docs is still very limited, also https://github.com/artefactual/archivematica-docs/pull/216 still not merged but that should not block the release IMO.

**Comment by sallain** [comment]
Everything looks so good, @sevein!

- [x] Changing languages in Dashboard.
- [x] Make sure that the appraisal tab, transfer browser and fpr-admin are also being translated because those are managed separately.
- [x] Changing languages in Storage Service.
- [x] Changing languages in https://www.archivematica.org.
