### ISSUE TITLE
Problem: Code of Conduct not exclusive to Issues

### ISSUE THREAD

**Issue by sromkey** [archivematica/Issues#233]
**Please describe the problem you'd like to be solved.**

This repo contains a [Code of Conduct](https://github.com/archivematica/Issues/blob/master/CODE_OF_CONDUCT.md) . I believe the spirit of this was to be a Code of Conduct for participating in the Archivematica community generally and it would be helpful to link it from other places (the user forum, the code repos, etc). However it seems a little misplaced in the Issues repo.

**Describe the solution you'd like to see implemented.**

@sallain had a good suggestion to make a Code of Conduct repo in the Archivematica organization so that it can stand on its own and be linked to from any context.

**Describe alternatives you've considered.**

None but open to other suggestions!

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by ablwr** [comment]
A benefit to having the language in a root-level CODE_OF_CONDUCT.md file is that you get notified and reminded of it when opening issues or PRs. It's in the Helpful Resources category on the bottom right. And I think if you are new to a repo, it'll elevate that announcement to be a little higher.

**Comment by sevein** [comment]
Now also part of the project website, under Community, https://www.archivematica.org/en/community/code-of-conduct/.
