### ISSUE TITLE
Problem: Help text for site URL is unclear

### ISSUE THREAD

**Issue by sromkey** [archivematica/Issues#234]
Related to https://github.com/artefactual/archivematica/issues/1140 

**Current behaviour**

Current text: "It defines the public address of this service. This is needed so the service (which is part of the pipeline) can be accessede by the Storage Service" is a little unclear (and contains a typo ;) ).

Suggested text: "This is the URL of your Archivematica dashboard. It is required if the Storage Service is running on a different machine from the Archivematica pipeline. Use the public URL, not the IP address."

**Your environment (version of Archivematica, OS version, etc)**

qa/1.x

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by sromkey** [comment]
@sevein and I were just discussing and maybe just "This is the URL of your Archivematica dashboard" is sufficient!

**Comment by sevein** [comment]
PR #1276 replaces the message with:

    This is the public URL of your Archivematica dashboard.
