### ISSUE TITLE
Docs: Validate METS feature is undocumented

### ISSUE THREAD

**Issue by ablwr** [archivematica/Issues#244]
**Version of the documentation**
1.8+

**Page (and section, if applicable) where the issue occurs**

**Description of the issue**

We can validate METS when reviewing AIPs, before storing them, by clicking on the validatorTester.html -- this isn't documented.

**Suggested fix**

We should document everything!!!

**Comment by ross-spencer** [comment]
Additional temporary information for users wanting to do this here: https://github.com/archivematica/Issues/issues/153#issuecomment-422974896
