### ISSUE TITLE
Problem: Archivematica core contains old METS.xsd

### ISSUE THREAD

**Issue by ablwr** [archivematica/Issues#245]
Likely related to https://github.com/artefactual/archivematica/pull/773 and may be resolved through that initiative.

Archivematica contains a METS.xsd version 0.9, but the docs and Mets Reader & Writer both use 0.11. Also 0.12 is the latest. Unsure if there is some legacy code that needs clearing out or if it's still being used.

**Your environment (version of Archivematica, OS version, etc)**

qa/1.x (1.8)

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by ross-spencer** [comment]
@ablwr I happen to be looking at a few things around this today. It is used here in the code https://github.com/artefactual/archivematica/blob/f6be2ab032aa3b5622a3111c26b04555d719339f/src/MCPClient/lib/clientScripts/archivematicaVerifyMets.sh#L32 which is a shell script called at the various points `verify mets_structmap.xml` is triggered. I'm mot entirely sure on `xmllint`'s effectiveness but that aside, perhaps we can either close this issue, or rename it to suggest updating the `mets.xml` document we are referencing?

**Comment by ross-spencer** [comment]
Hi @sromkey I added the `1.10` milestone as this will be resolved by https://github.com/artefactual/archivematica/pull/1404

**Comment by ablwr** [comment]
yayayayayay, bye old code!
