### ISSUE TITLE
Problem: Ansible fails with: TASK [artefactual.archivematica-src : Checkout out archivematica-sampledata repository]

### ISSUE THREAD

**Issue by rsandrade** [archivematica/Issues#25]
**Expected behaviour**
A successful Installation following the steps at website

**Current behaviour**
```
TASK [artefactual.archivematica-src : Checkout out archivematica-sampledata repository] ***
fatal: [am-local]: FAILED! => {"before": "31903fbb37fb85c78e6a66447974b6e5323f2097", "changed": false, "msg": "Local modifications exist in repository (force=no)."}
        to retry, use: --limit @/home/archivematica/deploy-pub/playbooks/archivematica/singlenode.retry

PLAY RECAP *********************************************************************
am-local                   : ok=177  changed=27   unreachable=0    failed=1

Ansible failed to complete successfully. Any error output should be visible above. Please fix these errors and try again.
```

Trying to install at Ubuntu 14.04 and Vagrant 2.x

**Comment by rsandrade** [comment]
Hi @sevein. I had to change ~/deploy-pub/playbooks/archivematica/roles/artefactual.percona/tasks/install.yml keyserver parameter to "hkp://keys.gnupg.net:80" in order to make it works. I can't use the exactly clone of the repo since the vagrant do not find the percona server keys in original url.

**Comment by sevein** [comment]
Oh I see, the original error that you shared seemed to be pointing to a different issue.
Glad that it's working now!

**Comment by rsandrade** [comment]
@sevein The first error was resolved changing the keyserver parameter but seems it created a new error (this issue) and I still trying to fix it. :)

I am not sure what to do to Ansible accept that change I made.

**Comment by sevein** [comment]
Does it get fixed if you go inside the archivematica-sampledata directory from the shell and run `git checkout -- .`?

**Comment by rsandrade** [comment]
Not sure if I did correctly. I used the git checkout -- . at ~/deploy-pub/ (I tried in another random dir and the command return an error) and it not fix the problem.

**Comment by sevein** [comment]
I actually meant in the archivematica-sampledata directory which you can find inside the virtual machine in the home directory.

**Comment by rsandrade** [comment]
@sevein after user `vagrant ssh` I could run `git checkout -- .` at archivematica-sampledata directory, exit and try `vagrant provision` but did not work too...

**Comment by sevein** [comment]
Try removing the sampledata directory then, hopefully that'll work.

**Comment by rsandrade** [comment]
I removed that dir, appear it worked. Now I need to deal with another error but is another issue. Thanks! :)

**Comment by sevein** [comment]
That's one problem I see with Ansible, it's brittle. Maybe we should do better at error handling.
