### ISSUE TITLE
Problem: we use external repositories for CentOS

### ISSUE THREAD

**Issue by scollazo** [archivematica/Issues#254]
**Expected behaviour**
All packages needed by archivematica should be available through the operating system, or available in artefactual managed repositories.

**Current behaviour**
Currently, we use packages from lin.ux.ro and forensics.cert.org repositories
 

**Steps to reproduce**

**Your environment (version of Archivematica, OS version, etc)**
Archivematica on Centos/RHEL

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by scollazo** [comment]
We should add all packages from the external repos into our own centos-extras repository

**Comment by mamedin** [comment]
This way we can reduce the risk or at least not depend on the actions of others, for example during the last 2 days it has not been possible to use the multimedia repository of li.nux.ro because the certificate was expired.

**Comment by scollazo** [comment]
TODO: document the process for downloading packages from nux-desktop and forensics repo in https://github.com/artefactual-labs/am-packbuild

**Comment by sallain** [comment]
@scollazo is this PR supposed to be open still?
