### ISSUE TITLE
Problem: default processing configuration is out of date

### ISSUE THREAD

**Issue by sallain** [archivematica/Issues#255]
**Please describe the problem you'd like to be solved.**
Since we set up the default processing configuration pre-sets for Archivematica 1.7 in artefactual/archivematica#993, several changes have been made that add extra decision points to the config (Bind PIDs, policy checks, etc.). These changes are set to _None_ in the current default config pre-sets. It would be good to review these changes for the 1.8 or 1.9 release.

**Describe the solution you'd like to see implemented.**
Review pre-sets for the default config, keeping in mind that the users using the pre-sets are usually testing out or new to Archivematica (the assumption is that a user who is more familiar with Archivematica will start to change the default config to suit their workflow).

**Describe alternatives you've considered.**
None

**Additional context**
None

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by sallain** [comment]
@sromkey @ablwr Here's a default processing config that I think strikes a nice balance between showing new users what Archivematica can do without showing too much:

![image](https://user-images.githubusercontent.com/4612276/51197613-e826b780-18a6-11e9-8f40-ba05c20d8abc.png)

@replaceafill, I'll place the XML in a gist once Sarah and Ashley sign off.

**Comment by ablwr** [comment]
This has been on my mind a lot so I didn't have to do a lot of thinking in this moment, hahaha. 

If anything, I'd consider turning off extracting packages by default. I guess it doesn't get triggered that often, but someone testing around with disk images or other surprise-compressed items might not have that intention. In this way, I think it should be an active decision of intent to extract packages. It can bog down a system and possibly for no reason, if it's just the user leaving things as-is.

**Comment by sromkey** [comment]
Perfecto :ok_hand: I think this looks great! Extract packages is set to none @ablwr so it's off by default!

**Comment by sallain** [comment]
@ablwr "Extract packages" is set to *None* - my thinking was that it's useful for new users to see that package extraction is possible and giving them the power to make the choice. Do you think setting it to *No* would be better?

**Comment by sromkey** [comment]
Oh I see what she's saying now. I think None is probably best to give new users the visibility into what's going on.

**Comment by ablwr** [comment]
Ahh yeah I meant considering `No` instead of `None`, but I don't have strong opinions about that. So I stand by my original point... LGTM!!!! :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1:

**Comment by sallain** [comment]
Okay, let's leave it as is! Thank you!!!

@replaceafill here is a gist for you! https://gist.github.com/sallain/ea79bd794454a09cdb123a818e795c99

**Comment by sallain** [comment]
@replaceafill Because of #485, this has changed! The three commands below should be set as follows:

* Perform file format identification (Transfer): None
* Perform file format identification (Ingest): No, use existing data
* Perform file format identification (Submission documentation & metadata):	Yes

@ablwr If you have an opinion on this, let me know!

**Comment by scollazo** [comment]
The changes to the processing configuration are breaking the automated tests:

<pre>
FAILED SUB-STEP: Given a base processing configuration for MediaConch tests
Substep info: Assertion Failed: FAILED SUB-STEP: Given that the user has ensured that the default processing config is in its default state
Substep info: Traceback (most recent call last):
  File "/home/jenkins/jenkins-home/workspace/deploy-pub/QA/Ubuntu-18.04-QA/env/lib/python3.5/site-packages/behave/model.py", line 1329, in run
    match.run(runner.context)
  File "/home/jenkins/jenkins-home/workspace/deploy-pub/QA/Ubuntu-18.04-QA/env/lib/python3.5/site-packages/behave/matchers.py", line 98, in run
    self.func(context, *args, **kwargs)
  File "features/steps/steps.py", line 46, in step_impl
    context.am_user.browser.ensure_default_processing_config_in_default_state()
  File "/home/jenkins/jenkins-home/workspace/deploy-pub/QA/Ubuntu-18.04-QA/amuser/am_browser_ability.py", line 431, in ensure_default_processing_config_in_default_state
    choice_value='Use existing data')
  File "/home/jenkins/jenkins-home/workspace/deploy-pub/QA/Ubuntu-18.04-QA/amuser/am_browser_ability.py", line 377, in set_processing_config_decision
    decision_select.select_by_visible_text(choice_value)
  File "/home/jenkins/jenkins-home/workspace/deploy-pub/QA/Ubuntu-18.04-QA/env/lib/python3.5/site-packages/selenium/webdriver/support/select.py", line 140, in select_by_visible_text
    raise NoSuchElementException("Could not locate element with visible text: %s" % text)
selenium.common.exceptions.NoSuchElementException: Message: Could not locate element with visible text: Use existing data
</pre>

**Comment by sallain** [comment]
This is resolved! Thanks @ablwr!
