### ISSUE TITLE
Problem: Cannot create user with accented characters/diacritics

### ISSUE THREAD

**Issue by sromkey** [archivematica/Issues#261]
**Expected behaviour**
Users should be able to have accents or other special characters in their First Name and/or Last Name fields.

**Current behaviour**
When trying to create a user with an accent in the First Name or Last Name, an Internal Server error comes up.

**Steps to reproduce**
- Create a new user with an accent in the first and/or last name
- Hit save- you'll get the error.

**Your environment (version of Archivematica, OS version, etc)**
qa/1.x (pre-1.8) on centos.

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by ross-spencer** [comment]
This has been noted in the user-forum by Rodrigo too, and it impacts the user's ability to login if accented characters are used. See the link [here](https://groups.google.com/d/msg/archivematica/0DFF0RhleVc/rDBQxYqIBAAJ).

**Comment by sromkey** [comment]
@replaceafill can you give us a sense of size for this?

**Comment by replaceafill** [comment]
@sromkey I'd say 1-2 hours.

**Comment by ablwr** [comment]
Tested in qa/1.x (last commit: https://github.com/artefactual/archivematica/commit/6d84db86d7d8fa21cea6f79f4b2ef1ec4c9666ef)
