### ISSUE TITLE
Problem: Dashboard status API can return status 'PROCESSING' for completed SIPs

### ISSUE THREAD

**Issue by hakamine** [archivematica/Issues#262]
**Expected behaviour**
The status API should return 'COMPLETED' for all completed SIPs

**Current behaviour**
The status API returns 'PROCESSING' for completed SIPs, when there is a job with later(bigger) values of createdtime and createdtimedec than the "Remove the processing directory" job

The dashboard API call that returns the status of a SIP/Transfer, assumes that the current or last job for a SIP/Transfer is the one with the latest created time (createdtime and createdtimedec object variables), hence returning the status for a SIP/Transfer based on the state of this job. In stable/1.6.x this is done [here](https://github.com/artefactual/archivematica/blob/stable/1.6.x/src/dashboard/src/components/api/views.py#L68-L107) (code is essentially unchanged in stable/1.7.x and current qa/1.x)

In some completed ingests, the last job in the microservices chain("Job: Remove the processing directory") is not the job with the latest createdtime and createdtimedec values, for these cases the call to the status API returns 'PROCESSING' instead of 'COMPLETE'

This incorrect status affects automation tools, which relies on the status API call to determine if a SIP is still processing or completed, in order to start a new transfer/ingest. 

**Steps to reproduce**
1) Find a completed ingest in which there is a job with later(bigger) values of createdtime and createdtimedec than the "Remove the processing directory" job. In the dashboard, these ingests are recognizable when the topmost job in the Store AIP microservice is not "Job: Remove the processing directory"

![screen shot 2018-10-10 at 2 00 13 pm](https://user-images.githubusercontent.com/10160634/46765813-e5f40200-cc94-11e8-9e9c-62f26c08203e.png)

2) Issue the API call:
```
$ curl "http://127.0.0.1/api/ingest/status/75856912-e620-4bb4-8ca5-c276278837cb/?username=your_user&api_key=your_key"
{"status": "PROCESSING", "name": "ITEM_2429-49364.zip", "microservice": "Clean up after storing AIP", "directory": "ITEM_2429-49364.zip-75856912-e620-4bb4-8ca5-c276278837cb", "path": "/var/archivematica/sharedDirectory/currentlyProcessing/ITEM_2429-49364.zip-75856912-e620-4bb4-8ca5-c276278837cb/", "message": "Fetched status for 75856912-e620-4bb4-8ca5-c276278837cb successfully.", "type": "SIP", "uuid": "75856912-e620-4bb4-8ca5-c276278837cb"}
```

**Your environment (version of Archivematica, OS version, etc)**
AM: stable/1.6.x, SS: stable/0.10.x However get_unit_status() is essentially unchanged in stable/1.7.x and the current qa/1.x, so the problem should be reproducible there.

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by sevein** [comment]
For QA, please follow Héctor's detailed description on how to reproduce!

**Comment by ablwr** [comment]
Hmm, any advice on triggering a transfer in which "Remove the processing directory" is not last?

**Comment by hakamine** [comment]
@ablwr  Unfortunately I don't know of a reliable way to reproduce this, but it's occurring consistently on some client's servers running AM 1.6.x, I suspect it's somehow related with server load, those servers have relatively big MCP databases (so queries take some time to complete). BTW I tested https://github.com/artefactual/archivematica/pull/1326 (which work arounds this problem on 1.6.x) and it's working fine.

**Comment by sromkey** [comment]
@evelynPM may have experienced this in testing- can you ping @hakamine please?
