### ISSUE TITLE
Problem: Can't answer 'yes' to "Delete Packages After Extraction?"

### ISSUE THREAD

**Issue by joel-simpson** [archivematica/Issues#269]
**Expected behaviour**
When I select a Dataverse dataset as a Transfer, I should be able to choose any of the standard options in the processing configuration. In this example, I should be able to answer yes to the question "Extract Packages?"  

**Current behaviour**
When "Extract Packages" is set to yes, the transfer fails at the "Parse Dataverse METS" job. 
Output from that job is here: https://gist.github.com/joel-simpson/bb231efa4040f6f44c8fe5f6308f73a4
(UPDATE following comment below... you can "Extract Packages", it's actually the following question, "Delete Packages After Extraction" that causes the transfer to fail).

**Steps to reproduce**
Select a dataverse dataset with a .zip package in it; process as a Dataverse Transfer Type, select yes at Extract Packages. ( I used the dataset "A Study of My Afternoon Drinks") 

**Your environment (version of Archivematica, OS version, etc)**
Testing in http://ocul-am-dv.dev.archivematica.org:62080 which I believe is current with qa/1.x as of this morning. 
I am sure this was working when originally merged to QA so feel this is a recent regression. 

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by ablwr** [comment]
Funny, I was running a test extracting packages last night and it was totally fine... (local qa/1.x)

**Comment by joel-simpson** [comment]
Some further details: using the same dataset (A Study of My Afternoon drinks), selecting "yes" to extract packages (as before)... but then selecting "No" to "Delete Packages After Extraction?", the transfer completes just fine. 
In that example, if we look at the task output from `Job Determine if transfer contains packages` we see `%transferDirectory%objects/Drinks.RData is extractable and has not yet been extracted.`
Could be coincidence, since there doesn't appear to be any FPR extraction rule for .Rdata files (this rdata file was correctly ID'd as an Rdata binary file).

**Comment by ablwr** [comment]
Ohhh I got that too when testing and @ross-spencer pointed me to this issue https://github.com/archivematica/Issues/issues/211

**Comment by ross-spencer** [comment]
@joel-simpson just to confirm the file causing the problem here. I stuck in some additional logging:

```
parsedataverse_v0.0: INFO      2018-10-11 23:20:18,994  archivematica.mcp.client.parse_dataverse_mets.get_db_objects:79  Looking for file type: 'Item' using base name: %transferDirectory%objects/Drone -US(revised).sav
parsedataverse_v0.0: INFO      2018-10-11 23:20:18,996  archivematica.mcp.client.parse_dataverse_mets.get_db_objects:61  Looking for file type: 'Item' using relative path: %transferDirectory%objects/Drone -US(revised)/Drone -US(revised)citation-ris.ris
parsedataverse_v0.0: INFO      2018-10-11 23:20:18,997  archivematica.mcp.client.parse_dataverse_mets.get_db_objects:67  Could not find file type: 'Item' in the database: Drone -US(revised)/Drone -US(revised)citation-ris.ris
parsedataverse_v0.0: INFO      2018-10-11 23:20:18,997  archivematica.mcp.client.parse_dataverse_mets.get_db_objects:79  Looking for file type: 'Item' using base name: %transferDirectory%objects/Drone -US(revised)citation-ris.ris
('Database integrity error, entry: %s for file %s', None, u'%transferDirectory%objects/Drone -US(revised).RData')Traceback (most recent call last):
  File "/src/MCPClient/lib/job.py", line 102, in JobContext
    yield
  File "/src/MCPClient/lib/clientScripts/parse_dataverse_mets.py", line 283, in call
    job.set_status(init_parse_dataverse_mets(job))
  File "/src/MCPClient/lib/clientScripts/parse_dataverse_mets.py", line 270, in init_parse_dataverse_mets
    return parse_dataverse_mets(job, transfer_dir, transfer_uuid)
  File "/src/MCPClient/lib/clientScripts/parse_dataverse_mets.py", line 257, in parse_dataverse_mets
    create_db_entries(job, mapping, agent)
  File "/src/MCPClient/lib/clientScripts/parse_dataverse_mets.py", line 174, in create_db_entries
    file_entry.currentlocation, file_entry.originallocation)
ParseDataverseError: ('Database integrity error, entry: %s for file %s', None, u'%transferDirectory%objects/Drone -US(revised).RData')
```

Note: `ParseDataverseError: ('Database integrity error, entry: %s for file %s', None, u'%transferDirectory%objects/Drone -US(revised).RData'`

So it does look like it is because we're deleting the `rdata` file because it is considered a `gzip` package, that we're seeing this issue.

e.g.

```
file Drinks.RData 
Drinks.RData: gzip compressed data, from Unix
```

I think it's the FPR gzip rule kicking in, in lieu of another ID. Because of that, there may be one or two ways we can consider fixing this. 

I've spend a couple of minutes adding some notes to this tomorrow.

**Comment by jhsimpson** [comment]
@ross-spencer I think the root cause of this issue is coming from here:
https://github.com/artefactual/archivematica/blob/qa/1.x/src/MCPClient/lib/clientScripts/parse_dataverse_mets.py#L62-L63

That code is fetching the set of all files for a given transfer from the MCP database.  It is not filtering out deleted files.

In the scenario described in this issue, there is a file whose originalLocation is %transferDirectory%objects/Drinks.RData

That file is being identified as a GZip file (x-fmt/266 is recorded during file format identification).  During extract packages, it is successfully extracted, and the original .RData file is deleted (all good, that is what the user selected in this case). 

In the database after extract packages has run, the original .RData file has the currentLocation set to null and the removedTime is not null:

```
originalLocation                        | fileGrpUse | currentLocation                    | removedTime
----------------------------------------+------------+------------------------------------+-----------------
%transferDirectory%objects/Drinks.RData | original   | NULL                               | 2018-10-12 01:25:44.464697 
```

If you modify the line of code linked above, so it filters the list of files fetched from the db, so it only gtse files where the removedTime is null and the currentLocation is not null, I think that will resolve the issue.

**Comment by sallain** [comment]
Note: when this is fixed for 1.9, remove the known bug admonition that was added to the documentation for 1.8 as per #327

**Comment by ross-spencer** [comment]
**To test:**

1. Setup a Dataverse transfer source with the Archivematica Subtree:

![image](https://user-images.githubusercontent.com/1880412/51285904-f97bdb00-19f0-11e9-90f3-8e6a224ae2bc.png)

2. Look for a dataset which would cause extract packages to run, and would previously cause the parse Dataverse METS microservice to fail:

![image](https://user-images.githubusercontent.com/1880412/51285882-e23ced80-19f0-11e9-8d37-c7717e50b011.png)

![image](https://user-images.githubusercontent.com/1880412/51286036-90489780-19f1-11e9-8e19-d33ea86d87c5.png)

(`.tab` datasets like this are downloaded as bundles and extracted in the Storage Service. In the 'bundle' is a file with an `RData` extension. You can see this by creating an AIP without extracting packages. If you do extract packages, the `.RData` file is identified as a `gzip` and the contents placed in the transfer folder. If the package is to be deleted its removal needs to be managed by Archivematica which is where the `Parse Dataverse METS` job previously failed, i.e. it wrongly assumed this file would always be there.) 

3. Ensure that the transfer is converted to a SIP and review the AIP and ensure that:

* It validates.
* That the METS validates.
* That other markers for fthe `.RData` file are as expected and there are no remnants in the METS which suggests that it should still be there.

![image](https://user-images.githubusercontent.com/1880412/51285965-347e0e80-19f1-11e9-9eed-e277442c17dd.png)

**Comment by replaceafill** [comment]
@ross-spencer I'm testing your branch and it's working great. I've got to this point of your testing instructions (the METS validates):

> ensure that:
> * It validates.
> * That the METS validates.

But I don't understand the last bullet and how to verify it:

> * That other markers for fthe .RData file are as expected and there are no remnants in the METS which suggests that it should still be there.

Could you please clarify that? I'm not very familiar with Dataverse yet or this type of file.

**Comment by ross-spencer** [comment]
Hi @replaceafill I don't know how to describe it concisely, but we're checking that the AIP METS doesn't suggest that the deleted object should still exist in the AIP. PREMIS IIRC doesn't record a deletion event for extracted packages (I don't think PREMIS has a deletion event!). I think we need to make sure it's no longer in the physical struct map primarily. There may still be references to the original object in places. I'm keen on getting @sallain or @sromkey's opinion on what to look for in the METS to validate the efficacy of this fix.

**Comment by pdurbin** [comment]
Hello! I just arrived at this issue by clicking "known bug" at https://www.archivematica.org/en/docs/archivematica-1.10/user-manual/transfer/dataverse/#processing-dataverse-datasets

Here's a screenshot:

![Screen Shot 2019-09-23 at 9 47 32 AM](https://user-images.githubusercontent.com/21006/65431313-45381d00-dde7-11e9-8290-4874fd85e396.png)

Does this mean the docs should be updated? Thanks!

**Comment by sromkey** [comment]
you are correct @pdurbin , thanks for the reminder!

**Comment by pdurbin** [comment]
@sromkey you're welcome. I just created https://github.com/artefactual/archivematica-docs/pull/328 to removed the link to this (fixed) bug from the docs. 😄
