### ISSUE TITLE
Problem: Dataverse datasets not displayed in any order

### ISSUE THREAD

**Issue by joel-simpson** [archivematica/Issues#276]
**Expected behaviour**
When you have configured a Dataverse repository as a Transfer Source Location, you can browse through the available datasets in the Transfer tab. Ideally the list of datasets would be presented in alphabetical order using the dataset name field. 

**Current behaviour**
Currently datasets are not displayed in any discernable order. In a long list of datasets this makes finding a dataset difficult. 
![screenshot from 2018-10-16 10-16-35](https://user-images.githubusercontent.com/17187309/47043676-315a5480-d15c-11e8-9390-6f72e8fb8afe.png)

**Steps to reproduce**
Configure a Transfer Source Location for dataverse and select "browse" from the Transfer tab. 

**Your environment (version of Archivematica, OS version, etc)**
Using qa/1.x (this will be an issue in v1.8.x when released)

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by jraddaoui** [comment]
Fixed the sort order for both, directories and files. However, the `entity_id` is displayed in front of the directory names, which makes the order a little rare. This id is required to move the Transfer later on and displayed like that to fit in the global workflow for transfer locations (the directory name is displayed as part of the extra properties inside parenthesis, like the size or file count in other sources). A more complicated fix will be required to not show that id, but it could be done.

**Comment by peterVG** [comment]
Confirmed working on 18.x.qa Xenial.

Before:
![screen shot 2018-10-18 at 12 18 53](https://user-images.githubusercontent.com/672121/47181043-d6993800-d2d6-11e8-9b15-359462dab6f5.png)


After:

![screen shot 2018-10-18 at 12 55 10](https://user-images.githubusercontent.com/672121/47181047-dac55580-d2d6-11e8-96b6-de0e4a09aa9e.png)
