### ISSUE TITLE
Problem: Perform policy checks on originals job is missing

### ISSUE THREAD

**Issue by sromkey** [archivematica/Issues#277]
**Expected behaviour**
In Transfer, the Perform policy checks job should be in the Validation micro-service, after Validate formats.  

**Current behaviour**
The job isn't there, however you set the processing configuration.

Of note is that Validation is now followed by Parse External Files, with the job Determine Parse Dataverse METS XML.

**Steps to reproduce**
Should happen with any transfer with any processing configuration.

**Your environment (version of Archivematica, OS version, etc)**
qa/1.x (pre-1.8) on centos.

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by kellyannewithane** [comment]
Just ran a standard transfer through am18bionic.qa and I do not see a Perform policy check microservice. Back to the drawing board?

**Comment by kellyannewithane** [comment]
Update:  perform policy check is BACK where it should be. All is well.
