### ISSUE TITLE
Problem: Multiple authors not captured in Dataverse METS

### ISSUE THREAD

**Issue by joel-simpson** [archivematica/Issues#278]
**Expected behaviour**
When a dataset from Dataverse is selected as a transfer, a Dataverse METS gets created during the transfer process. This METS includes metadata provided by dataverse in a dataset.json file, which includes the authors of the dataset. As documented in the data mapping on the wiki, we map `json: citation/typeName: "authorName"` to the METS element `ddi:AuthEntity`
When there are multiple authors of a dataset in the dataset.json, we should see multiple authors in the METS file.  

**Current behaviour**
Only the first author is included in the METS file. 

**Steps to reproduce**
In an environment configured to connect to dataverse, select the "3D Lasers" dataset (or any other that has multiple authors) and process it as a Dataverse Transfer type. Check the Dataverse METS (and final AIP METS, which includes the same content) and you'll see only the first author is listed. 

**Your environment (version of Archivematica, OS version, etc)**
currently testing in qa/1.x

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by ross-spencer** [comment]
When we look at a multiple author dataset we can see the affiliation attribute is also used in the DDI:

```
<AuthEnty affiliation="Channel 4">Noel Fielding</AuthEnty>
<AuthEnty affiliation="BBC">Mary Berry</AuthEnty>
<AuthEnty affiliation="Freelance">Hollywood, Paul</AuthEnty>
```

Example: https://demodv.scholarsportal.info/dataset.xhtml?persistentId=doi:10.5072/FK2/QAWS8O

**Comment by ross-spencer** [comment]
**Datasets to contrast when testing:** 
* Single-author dataset: https://demodv.scholarsportal.info/dataset.xhtml?persistentId=doi:10.5072/FK2/6PPJ6Y
* Multiple-author dataset: https://demodv.scholarsportal.info/dataset.xhtml?persistentId=doi:10.5072/FK2/QAWS8O

**Comment by ross-spencer** [comment]
**To test:**

1. Setup a Dataverse transfer source with the Archivematica Subtree:

![image](https://user-images.githubusercontent.com/1880412/51285904-f97bdb00-19f0-11e9-90f3-8e6a224ae2bc.png)

2. Look for a dataset with multiple authors, e.g. this one set up for development testing:

![image](https://user-images.githubusercontent.com/1880412/51285882-e23ced80-19f0-11e9-8d37-c7717e50b011.png)

3. Review the AIP and ensure that:

* It validates
* You can see the multiple authors in the METS

![image](https://user-images.githubusercontent.com/1880412/51285965-347e0e80-19f1-11e9-9eed-e277442c17dd.png)

**Comment by currmie** [comment]
Verified after reviewing the AIP and ensuring:
* It validates
* Can see the multiple authors in the METS
