### ISSUE TITLE
Problem: The purpose of 'Verify mets_structmap.xml' during ingest is not clear.

### ISSUE THREAD

**Issue by ross-spencer** [archivematica/Issues#286]
**Expected behaviour**

The purpose of `verify mets_structmap.xml compliance` on Ingest isn't clear. 

**Current behaviour**

From the screenshot below it is possible to see the verify compliance microservice is triggered, but then files such as `mets_structmap.xml` are not added to the AIP until much later as can be seen in `Process Metadata Directory`.

![image](https://user-images.githubusercontent.com/1880412/47151416-fc740c00-d2d9-11e8-8e4e-13893a711154.png)

If you add logging to the script, e.g. `find` you will see the directory list as follows: 

```
Attempting to validate /var/archivematica/sharedDirectory/currentlyProcessing/structmap/metadata/mets_structmap.xml using /src/MCPClient/lib/assets/mets/mets.xsd

/var/archivematica/sharedDirectory/currentlyProcessing/structmap/ 
/var/archivematica/sharedDirectory/currentlyProcessing/structmap/logs 
/var/archivematica/sharedDirectory/currentlyProcessing/structmap/logs/fileMeta 
/var/archivematica/sharedDirectory/currentlyProcessing/structmap/processingMCP.xml 
/var/archivematica/sharedDirectory/currentlyProcessing/structmap/metadata 
/var/archivematica/sharedDirectory/currentlyProcessing/structmap/metadata/submissionDocumentation 
/var/archivematica/sharedDirectory/currentlyProcessing/structmap/objects 
/var/archivematica/sharedDirectory/currentlyProcessing/structmap/objects/manualNormalization 
/var/archivematica/sharedDirectory/currentlyProcessing/structmap/objects/manualNormalization/access 
/var/archivematica/sharedDirectory/currentlyProcessing/structmap/objects/manualNormalization/preservation 
/var/archivematica/sharedDirectory/currentlyProcessing/structmap/objects/one_file.txt 
/var/archivematica/sharedDirectory/currentlyProcessing/structmap/objects/sample_dir 
/var/archivematica/sharedDirectory/currentlyProcessing/structmap/objects/sample_dir/one_file_two.txt

No metadata/mets_structmap.xml file to verify.
```

`Verify SIP compliance` which has already run at this stage checks the physical layout of the directory, so for example, it checks that the `metadata` directory is in the SIP, but it doesn't check what files are or are not there. 

From the directory listing, `metadata` can be confirmed to be there, but no other metadata objects. 

If it is decided that this microservice is required still, we should also consider changing the task group under which it is being triggered so that it becomes part of `Verify SIP compliance`. 

**Your environment (version of Archivematica, OS version, etc)**

`qa/1.x`

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by sallain** [comment]
@ross-spencer, I'm curious what happens if you start a transfer that includes a structmap (which is a valid option, though not documented; the structmap gets checked on the Transfer tab) and then rearrange the materials in the backlog (i.e. move things around, add items from another transfer, remove items) before reaching this step in Ingest. Is it looking at the user-generated structmap for this job? Would the rearrangement cause this job to fail?

I wish I had an idea of what the original purpose of this feature was, whether this is a legacy job from when Archivematica worked differently or if it was supposed to carry out some specific function. Maybe @jhsimpson would know.

**Comment by ross-spencer** [comment]
Trying to document this better today, Thanks for your advice Sara. I will attempt that example below. I try two scenarios to understand Archivematica's behavior. 

### Scenario 1

First, I tried the arrangement tab on its own, and combined two transfers: I ended up with this structure and a SIP was initialized:

```
watchedDirectories/SIPCreation/SIPsUnderConstruction# tree
.
└── appraisal_tab_adding_structure
    ├── add_a_new_folder
    │   └── one_file
    │       └── one_file.txt
    ├── add_a_second_folder
    │   └── one_zip
    │       └── one_file.zip
    ├── logs
    │   └── arrange.log
    ├── metadata
    │   └── submissionDocumentation
    └── put_a_second_transfer_here
        ├── IMG_5799.jpg
        └── Kazimir_Malevich_-_Supremus_58.jpg

9 directories, 5 files
```

I wasn't sure what to expect, but as you probably anticipated, working in the arrangement tab alone doesn't create a custom structmap, instead structmap information is preserved in the transfer METS and the AIP METS. 

The verify structmap job during ingest looks like this: `No metadata/mets_structmap.xml file to verify.`: 

![image](https://user-images.githubusercontent.com/1880412/51674644-7f8bb900-1fd1-11e9-92c3-4927e8a53d95.png)

Users can derive what has happened in arrangement, using the AIP METS and a combination of the output of the two transfer METS fils stored with the AIP:

![image](https://user-images.githubusercontent.com/1880412/51674864-3ab45200-1fd2-11e9-93da-d8a9656e8604.png)

And I will attempt to see what happens if we use a custom structmap.

**Comment by ross-spencer** [comment]
### Scenario 2

We have a custom structmap example in the [sample-data repository](https://github.com/artefactual/archivematica-sampledata/blob/f665bd1850831811436aafe743386329b4f7ccd2/SampleTransfers/structMapSample/metadata/mets_structmap.xml).

I combined two transfers to end up with a structure like this:

```
SIPCreation/SIPsUnderConstruction# tree
.
└── transfer_arrangement_existing_structmap
    ├── logs
    │   └── arrange.log
    ├── metadata
    │   └── submissionDocumentation
    ├── original_transfer
    │   └── objects
    │       ├── cover.jpg
    │       ├── index_02.jpg
    │       ├── inside_cover.jpg
    │       ├── modify_layout_add_levels
    │       │   ├── back_cover.jpg
    │       │   ├── index_01.jpg
    │       │   ├── page_02.jpg
    │       │   └── page_03.jpg
    │       ├── page_01.jpg
    │       ├── page_04.jpg
    │       ├── page_05.jpg
    │       ├── page_06.jpg
    │       ├── page_07.jpg
    │       └── page_20.jpg
    └── second_transfer
        └── second_transfer-35b02eb6-4604-4160-890c-bbcb9a67a735
            └── objects
                ├── Cv7a7v7WAAADJTO.jpg
                ├── DU5yMrQWsAEZrZn.jpg
                ├── DUI7YauXcAAqQ0c.jpg
                ├── Empty_File
                ├── IMG_5799.jpg
                ├── Kazimir_Malevich_-_Supremus_58.jpg
                ├── sample.aif
                └── somedata.aif

10 directories, 22 files
```

**NB.** I think consistent with original observations, the structmap and much of the transfer documentation is missing at this point - after arrangement, and just before `Approve SIP Creation`. 

**Transfer tab verify structmap job:**

![image](https://user-images.githubusercontent.com/1880412/51676052-bfed3600-1fd5-11e9-8042-d31231cb6056.png)

**Ingest tab verify structmap job:**

![image](https://user-images.githubusercontent.com/1880412/51676072-d1ced900-1fd5-11e9-8aa9-00c7ad0e2405.png)

Aside from generating a rather verbose 11000 line METS, the transfer completes, and no additional validation is done on the original structmap. We see it transplanted in the AIP as we'd expect for a transfer. 

```
	<mets:structMap TYPE="logical" ID="structMap_2">
		<mets:div TYPE="book" LABEL="How to create a hierarchical book">
			<mets:div TYPE="page" LABEL="Cover">
				<mets:fptr FILEID="file-16dee643-0a7a-4b1d-9230-3dcc0d280c8b"/>
			</mets:div>
			<mets:div TYPE="page" LABEL="Inside cover">
				<mets:fptr FILEID="file-18959b8f-14c7-46ec-b97f-504a4a06e27d"/>
			</mets:div>
			<mets:div TYPE="chapter" LABEL="Chapter 1">
				<mets:div TYPE="page" LABEL="Page 1">
					<mets:fptr FILEID="file-e45ca83b-e4ae-4072-bd81-57b15a065391"/>
				</mets:div>
				<mets:div TYPE="subchapter" LABEL="Subchapter 1.1">
					<mets:div TYPE="page" LABEL="Page 2">
						<mets:fptr FILEID="file-001421bc-a199-42c8-b3d7-9061679eb865"/>
					</mets:div>
					<mets:div TYPE="page" LABEL="Page 3">
						<mets:fptr FILEID="file-d9906949-885a-4acc-adf7-75c842748710"/>
					</mets:div>
					<mets:div TYPE="page" LABEL="Page 4">
						<mets:fptr FILEID="file-6b01b629-180d-42d0-9a1a-559d3396b0df"/>
					</mets:div>
					<mets:div TYPE="subchapter" LABEL="Subchapter 1.2">
						<mets:div TYPE="page" LABEL="Page 5">
							<mets:fptr FILEID="file-4ff55f7f-7b07-4d95-a0d9-c1fae1061a86"/>
						</mets:div>
						<mets:div TYPE="page" LABEL="Page 6">
							<mets:fptr FILEID="file-43bd2651-c63b-4f90-a792-2d689f5e856f"/>
						</mets:div>
						<mets:div TYPE="page" LABEL="Page 7">
							<mets:fptr FILEID="file-b6cc6536-c204-483b-8505-ab8a755189c3"/>
						</mets:div>
					</mets:div>
					<!-- Subchapter 1.2 -->
				</mets:div>
				<!-- Subchapter 1.1 -->
			</mets:div>
			<!-- Chapter 1 -->
			<!-- Chapters 2 and 3, each with their own subchapters as in Chapter 1, omitted from this example. -->
			<mets:div TYPE="afterword" LABEL="Afterword">
				<mets:div TYPE="page" LABEL="Page 20">
					<mets:fptr FILEID="file-d8dfef04-ec8b-49bc-bbfc-b0950c1f6e5a"/>
				</mets:div>
			</mets:div>
			<!-- afterword -->
			<mets:div TYPE="index" LABEL="Index">
				<mets:div TYPE="page" LABEL="Index, page 1">
					<mets:fptr FILEID="file-93ac4476-984e-43b6-ab27-7336f160c8cd"/>
				</mets:div>
				<mets:div TYPE="page" LABEL="Index, page 2">
					<mets:fptr FILEID="file-fffdd151-fe2d-4c9b-9f64-c50dad4c845d"/>
				</mets:div>
			</mets:div>
			<!-- index -->
		</mets:div>
		<!-- book -->
	</mets:structMap>
```

This gives me an idea though...

**Comment by ross-spencer** [comment]
### Scenario three

I removed the structmap on transfer, and then added it manually on ingest (as I thought it might validate the structmap if supplied manually like this), so before and after I had this structure:

```
SIPCreation/SIPsUnderConstruction# tree
.
└── structmap_on_ingest
    ├── logs
    │   └── arrange.log
    ├── metadata
    │   └── submissionDocumentation
    └── objects
        ├── back_cover.jpg
        ├── cover.jpg
        ├── index_01.jpg
        ├── index_02.jpg
        ├── inside_cover.jpg
        ├── page_01.jpg
        ├── page_02.jpg
        ├── page_03.jpg
        ├── page_04.jpg
        ├── page_05.jpg
        ├── page_06.jpg
        ├── page_07.jpg
        └── page_20.jpg

5 directories, 14 files
```

```
SIPCreation/SIPsUnderConstruction# tree
.
└── structmap_on_ingest
    ├── logs
    │   └── arrange.log
    ├── metadata
    │   ├── mets_structmap.xml
    │   └── submissionDocumentation
    └── objects
        ├── back_cover.jpg
        ├── cover.jpg
        ├── index_01.jpg
        ├── index_02.jpg
        ├── inside_cover.jpg
        ├── page_01.jpg
        ├── page_02.jpg
        ├── page_03.jpg
        ├── page_04.jpg
        ├── page_05.jpg
        ├── page_06.jpg
        ├── page_07.jpg
        └── page_20.jpg

5 directories, 15 files
```

But from the verify structmap compliance job on the ingest tab we see the following:

![image](https://user-images.githubusercontent.com/1880412/51677527-3ab85000-1fda-11e9-8f1d-aefa728fa1c3.png)

So it's not clear yet how to invoke this job.

**Comment by peterVG** [comment]
After further discussion we've concluded that adding a custom structMap during Ingest is not a feature that is supported by the current user interface. It would require a sys admin granting access to the `.am/am-pipeline-data/watchedDirectories/SIPCreation` directory to upload the custom structMap. While this is possible, there are no known use cases where this is a requirement. There is a gap in historical knowledge on why this microservice is present in the Ingest workflow. The more recent work on adding custom structMaps focusses on adding these during the Transfer workflow and this is now working and understood quite well (See issue #451). The conclusion of the discussion is to eliminate the `Verify mets_structmap.xml compliance` Job from the Ingest workflow as it appears to be a deprecated feature.

**Comment by sallain** [comment]
@peterVG @ross-spencer I'm sure you've already discussed it but there's no chance that this verification job exists because of backlog arrangement, is there? I.e. AM making sure that the structmap is accurate post-arrangement.

**Comment by sallain** [comment]
I just realized that the above comment is basically the exact same question that I posed in December, which was thoroughly investigated by @ross-spencer  :woman_facepalming:

**Comment by ross-spencer** [comment]
Working on this today, there are three examples of `verify_custom_structmap.xml` in `amflow`: 

**Standard transfer**
![image](https://user-images.githubusercontent.com/1880412/58071990-8fda2c00-7b9e-11e9-8027-e77775539b56.png)

**DSpace transfer**
![image](https://user-images.githubusercontent.com/1880412/58072004-9ff20b80-7b9e-11e9-9dbd-b27a397a4b1c.png)

And finally, the one we will focus on removing, `Ingest` (no specific transfer type):

![image](https://user-images.githubusercontent.com/1880412/58072030-b1d3ae80-7b9e-11e9-9c47-f986df23c5e5.png)

**Work that needs to be done**

* [ ] Unlink: Verify mets_structmap.xml compliance (`d1018160-aaab-4d92-adce-d518880d7c7d`) from workflow.
* [ ] Link: Verify SIP compliance: (`208d441b-6938-44f9-b54a-bd73f05bc764`) -> Check if SIP is from Maildir Transfer (`b3d11842-0090-420a-8919-52d7039d50e6`)
* [ ] Link: Attempt restructure for compliance: (`7d0616b2-afed-41a6-819a-495032e86291`) -> Check if SIP is from Maildir Transfer (`b3d11842-0090-420a-8919-52d7039d50e6`)

Aside from that no further work is needed, i.e. no scripts need removing or other code updating.

**Comment by sallain** [comment]
`Verify mets_structmap.xml compliance` triggered in Transfer tab and completed successfully. Duplicate job did not occur in the Ingest tab. Structmap is properly recorded in METS.
