### ISSUE TITLE
Problem: "Add Next" button for disk image transfers is redundant

### ISSUE THREAD

**Issue by sallain** [archivematica/Issues#290]
**Please describe the problem you'd like to be solved.**
When you create a disk image transfer, it's possible to add specific disk image-related metadata to the object prior to starting the transfer.

![screenshot of archivematica dashboard - transfer](https://user-images.githubusercontent.com/4612276/47176843-7f419a80-d2cb-11e8-91b1-9e856426ac02.jpg)

If you want to add multiple disk images, the [documentation](https://www.archivematica.org/en/docs/archivematica-1.8/user-manual/transfer/forensic/#upload-image-to-dashboard) says to click on "Add Next" in order to add metadata to the next item that you add to the transfer. However, if you add a second item to the transfer, there is also a metadata icon. Adding metadata using the metadata icon serves the same purpose as using the "Add Next" button. The "Add Next" button is redundant.

![image](https://user-images.githubusercontent.com/4612276/47177461-51f5ec00-d2cd-11e8-8baa-b7674a19c0fc.png)

**Describe the solution you'd like to see implemented.**
Remove the "Add Next" button and change the documentation so that users have a clear workflow for adding metadata to a disk image.

**Describe alternatives you've considered.**
None.

**Additional context**

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by ablwr** [comment]
Yes, tested, tested. Tested on qa/1.x (https://github.com/artefactual/archivematica/commit/baf565e4abc3bcf9480ee0784734ce9b0b223f63, proto-1.11 RC candidate)

**Comment by sallain** [comment]
NTS update screenshots on `user-manual/transfer/forensic.rst`
