### ISSUE TITLE
Problem: html lang attribute always reads "en" (English)

### ISSUE THREAD

**Issue by sevein** [archivematica/Issues#297]
**Expected behaviour**
The `html` element should reflect the language of the contents sent to the browser.

**Current behaviour**
The `html` element is always rendered as follows regardless the language of the contents:

    <html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">

**Steps to reproduce**
1. Open Dashboard
2. Go to Administration > Language
3. Choose a lang other than English, e.g. Brazilian Portuguese
4. Open the source of the page and inspect the `html` element and its attributes

**Your environment (version of Archivematica, OS version, etc)**
AM18 qa/1.x [a90faa9](https://github.com/artefactual/archivematica/commit/a90faa92d37e91efe234614ede11231885717cc5).

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by sevein** [comment]
Looking at mozilla/bedrock, they have some logic behind their `LANG` that it's worth checking. See https://github.com/mozilla/bedrock/blob/master/bedrock/base/templates/base-resp.html.

**Comment by sallain** [comment]
It would be nice to fix this alongside the final i18n things!

**Comment by sallain** [comment]
@sevein is there a PR for this???

**Comment by ablwr** [comment]
Sorry @sevein we are experiencing some Waffle weirdness here
