### ISSUE TITLE
Problem: There isn't a lot of information around reingest.py in the automation tools

### ISSUE THREAD

**Issue by ross-spencer** [archivematica/Issues#300]
**Please describe the problem you'd like to be solved.**

It would be good to have more information about logging, database output, and how to debug. 

**Describe the solution you'd like to see implemented.**

Update the automation tools `README.md` to satisfy this gap. 

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by sallain** [comment]
@ross-spencer looks like the PR has been merged - going to close, but feel free to re-open if I'm being too hasty!
