### ISSUE TITLE
Problem: There is no Dataverse sampledata

### ISSUE THREAD

**Issue by ross-spencer** [archivematica/Issues#301]
**Please describe the problem you'd like to be solved.**

It would be nice to be able to test Dataverse workflows without having to necessarily connect the Storage Service to a Dataverse endpoint. Currently, not all Dataverses can be easily hooked up: https://github.com/archivematica/Issues/issues/264

**Describe the solution you'd like to see implemented.**

Add some sample Dataverse transfers to the sampledata repository. 

**Describe alternatives you've considered.**

We can leave this as is, but it would be good to be able test and demonstrate Dataverse functionality in alternative ways.

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by sevein** [comment]
@ross-spencer can you push #45 again using the gitolite remote?

**Comment by sevein** [comment]
I fixed it!
