### ISSUE TITLE
Problem: Cannot change a format ID rule in AM 1.8

### ISSUE THREAD

**Issue by ross-spencer** [archivematica/Issues#304]
**Expected behaviour**

When I try to replace a format identification command, and submit a valid Python script the FPR doesn't result in an internal server error.

**Current behaviour**

This was discovered by trying to add a new function to the Siegfried script. My version is as follows:

```
from __future__ import print_function

import json
import subprocess
import sys


class IdToolError(Exception):
    pass


class ParseError(IdToolError):
    PREFIX = 'The output produced by siegfried could not be parsed'
    def __init__(self, message=None):
        message = self.PREFIX if message is None else '{}: {}'.format(self.PREFIX, message)
        Exception.__init__(self, message)


def sf_tool(path):
    return subprocess.check_output(['sf', '-json', path])


def sf_version():
    return subprocess.check_output(['sf', '-version'])
    

def find_puid(sf_output):
    result = json.loads(sf_output)
    try:
        matches = result['files'][0]['matches']
    except KeyError as e:
        raise ParseError('error matching key {}'.format(e))

    if len(matches) == 0:
        raise ParseError('no matches found')

    match = matches[0]
    puid = None

    if 'puid' in match:
        puid = match['puid']
    elif 'id' in match:
        puid = match['id']
    else:
        raise ParseError

    if puid == 'UNKNOWN':
        raise IdToolError('siegfried determined that the file format is UNKNOWN')

    return puid


def main(path):
    try:
        print(sf_version())
        print(find_puid(sf_tool(path)))
    except IdToolError as e:
        print(e, file=sys.stderr)
        return 1
    return 0


if __name__ == '__main__':
    sys.exit(main(sys.argv[1]))
```
And I can confirm it works standalone:

```
ross-spencer@artefactual:~/Desktop/temp$ python standalone.py Drinks.RData 
siegfried 1.7.10
/home/ross-spencer/siegfried/default.sig (2018-09-19T11:32:11+10:00)
identifiers: 
  - pronom: DROID_SignatureFile_V94.xml; container-signature-20180917.xml
  - tika: tika-mimetypes.xml (1.18, 2018-04-20)
  - freedesktop.org: freedesktop.org.xml (1.10, 2018-28-06)
  - loc: fddXML.zip (2018-06-14, DROID_SignatureFile_V94.xml, container-signature-20180917.xml)

x-fmt/266
```

But the easiest way to recreate the issues is as follows:

1. Look in the FPR for identification commands, and replace the entirety of the current Siegfried rule with:

      `print("this is a simple script")`

This is valid Python, and while it is expected to have other consequences when triggered in the workflow, it isn't expected to cause an FPR error. 

This is what we see in AM 18 Bionic:

![image](https://user-images.githubusercontent.com/1880412/47624495-a7c46280-db1d-11e8-8942-48e1fc8951d8.png)

And in my `qa/1.x` test server:

![image](https://user-images.githubusercontent.com/1880412/47624502-be6ab980-db1d-11e8-933d-a9f38ec45fe2.png)
 
**Your environment (version of Archivematica, OS version, etc)**

`qa/1.x` in docker-compose on Ubuntu.

**Additional context**

It seems that whatever the issue submitting this script change (or any change I have been able to confirm as valid Python), the write to the database happens regardless. This means that when the user tries to access FPR -> Identification -> Commands again, then the same 'internal server error' appears. This makes the FPR unstable for users. We may need to consider a way to recover from this losslessly, e.g. by writing a new working script from the original migration as a new version and letting users access the previous one still.  

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by sevein** [comment]
@sallain, I've moved this to 1.8 and refining to make sure it does not fall of the radar.

**Comment by sevein** [comment]
I've submitted a fix! I don't think this is a regression?

Also, changed priority to High since you can just work around it by giving the field a value.

**Comment by kellyannewithane** [comment]
Tested on bionic successfully.  No internal server error.  Good job @ross-spencer!

**Comment by ross-spencer** [comment]
Wish I could take the credit @kellyannewithane but I'm just the problem finder :wink: @sevein squished this :bug:
