### ISSUE TITLE
Problem: Rights.csv metadata is not imported to METS file

### ISSUE THREAD

**Issue by peterVG** [archivematica/Issues#305]
**Expected behaviour**
When including a rights.csv file in a transfer's  `/metadata` directory using the correct CSV field mappings, the rights metadata will be included in the AIP METS file as RightsMD sections. 

**Current behaviour**

The corresponding microservice ("Characterize and extract metadata/load rights") completes without an error but does report "Skipping duplicate basis/act combination at row 1, (row 2), (row 3), etc." 

![screen shot 2018-10-29 at 11 59 49](https://user-images.githubusercontent.com/672121/47673765-cdc82200-db72-11e8-9764-37d82de0730b.png)

The AIP that is produced thereafter does not include any RightsMD sections.

NOTE: The rights import seems to work at least once on a fresh server/installation (without the "Skipping duplicate basis/acts combination" errors) but then the exact same sample data in a separate Transfer fails each time thereafter as described above. 

**Steps to reproduce**

`archivematica-sampledata-SampleTransfers-DemoTransfer` is the one set of sample data that includes a rights.csv file which has been used for all Archivematica rights import testing to date. Conduct a transfer using this set of sample data and then search the corresponding METS file for a RightsMD section. The first time on a fresh installation completes successfully. e.g. see this screencap:

![screen shot 2018-10-29 at 12 59 52](https://user-images.githubusercontent.com/672121/47676754-aa08da00-db7a-11e8-80c7-4fd5f61d2b11.png)

but any subsequent transfers will fail as described further above.

FYI: I rebuilt the AM18bionic.qa server specifically to test this. I ran two transfers seconds apart. The second one failed as reported.

**Your environment (version of Archivematica, OS version, etc)**

AM18bionic.qa, AM18xenial.qa, AM18Centos.qa

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by ross-spencer** [comment]
This sounds a little related, it will be interesting to read more about the logic about why it is skipping: https://github.com/archivematica/Issues/issues/130

**Comment by sallain** [comment]
This looks to be fixed! I ran a few transfers and the rights were properly applied each time.
