### ISSUE TITLE
Problem: GPG key generation doesn't work in Ubuntu 18.04

### ISSUE THREAD

**Issue by jraddaoui** [archivematica/Issues#306]
**Expected behaviour**
Entering a proper name and email in the "Create key" form and submitting it should generate a new GPG key.

**Current behaviour**
The form submission fails to create a new key:
![gpg_key_error](https://user-images.githubusercontent.com/637040/47716907-5bc00d80-dc44-11e8-9ea1-62ee4e3b0d8e.png)

**Steps to reproduce**
- In an instance working in Ubuntu 18.04
- Go to `.../administration/keys/create/`.
- Enter a name and email.
- Click the "Create key" button.

**Your environment (version of Archivematica, OS version, etc)**
- Local AM-Bionic Vagrant box with qa branches.
- http://am18bionic.qa.archivematica.org/

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by mamedin** [comment]
Bionic uses gnupg2 for the gpg command, and CentOS and Xenial use gnupg v1.

I found a fast workaround for Bionic installing the `gnupg1` package and creating a symbolic link for the `gpg`command on `/usr/local/bin`:

```
sudo apt-get install -y gnupg1
sudo ln -s /usr/bin/gpg1 /usr/local/bin/gpg
```

**Comment by sevein** [comment]
@mamedin, we may have to do that. We could introduce a tweak in SS so we try to run gpg1 first, if that helps, so we don't have to think about symlinks.

The problem seems to be discussed here: https://git.io/fxdcH. It looks like github.com/isislovecruft/python-gnupg may already have a fix? But we're using bitbucket.org/vinay.sajip/python-gnupg I believe.

There's more detail about the error in the logs when you change the level of the root logger to `DEBUG` (e.g. in `storageService.logging.json`), e.g.:

```
gnupg:gnupg:_open_subprocess:833:  14742: gpg --status-fd 2 --no-tty --debug ipc --homedir /var/archivematica/storage_service --gen-key --batch
gnupg:gnupg:_threaded_copy_data:173:  data copier: <Thread(Thread-9, initial daemon)>, <_io.BytesIO object at 0x7f42bc6a8a70>, <FileObjectPosix _fobj=<FlushingBufferedWriter>>
gnupg:gnupg:_copy_data:168:  closed output, 85 bytes sent
gnupg:gnupg:_collect_output:889:  stderr reader: <Thread(Thread-10, initial daemon)>
gnupg:gnupg:_collect_output:895:  stdout reader: <Thread(Thread-11, initial daemon)>
gnupg:gnupg:_read_response:851:  gpg: WARNING: unsafe permissions on homedir '/var/archivematica/storage_service'
gnupg:gnupg:_read_response:851:  gpg: Note: no default option file '/var/archivematica/storage_service/gpg.conf'
gnupg:gnupg:_read_response:851:  gpg: enabled debug flags: ipc
gnupg:gnupg:_read_response:851:  gpg: DBG: chan_3 <- OK Pleased to meet you, process 14742
gnupg:gnupg:_read_response:851:  gpg: DBG: connection to agent established
gnupg:gnupg:_read_response:851:  gpg: DBG: chan_3 -> RESET
gnupg:gnupg:_read_response:851:  gpg: DBG: chan_3 <- OK
gnupg:gnupg:_read_response:851:  gpg: DBG: chan_3 -> GETINFO version
gnupg:gnupg:_read_response:851:  gpg: DBG: chan_3 <- D 2.2.4
gnupg:gnupg:_read_response:851:  gpg: DBG: chan_3 <- OK
gnupg:gnupg:_read_response:851:  gpg: DBG: chan_3 -> OPTION allow-pinentry-notify
gnupg:gnupg:_read_response:851:  gpg: DBG: chan_3 <- OK
gnupg:gnupg:_read_response:851:  gpg: DBG: chan_3 -> OPTION agent-awareness=2.1.0
gnupg:gnupg:_read_response:851:  gpg: DBG: chan_3 <- OK
gnupg:gnupg:_read_response:851:  gpg: DBG: chan_3 -> RESET
gnupg:gnupg:_read_response:851:  gpg: DBG: chan_3 <- OK
gnupg:gnupg:_read_response:851:  gpg: DBG: chan_3 -> GENKEY
gnupg:gnupg:_read_response:851:  gpg: DBG: chan_3 <- S INQUIRE_MAXLEN 1024
gnupg:gnupg:_read_response:851:  gpg: DBG: chan_3 <- INQUIRE KEYPARAM
gnupg:gnupg:_read_response:851:  gpg: DBG: chan_3 -> D (genkey(rsa(nbits 4:4096)))
gnupg:gnupg:_read_response:851:  gpg: DBG: chan_3 -> END
gnupg:gnupg:_read_response:851:  gpg: DBG: chan_3 <- INQUIRE PINENTRY_LAUNCHED 14744 curses 1.1.0 - - -
gnupg:gnupg:_read_response:851:  [GNUPG:] PINENTRY_LAUNCHED 14744 curses 1.1.0 - - -
gnupg:gnupg:_read_response:851:  gpg: DBG: chan_3 -> END
gnupg:gnupg:_read_response:851:  gpg: DBG: chan_3 <- ERR 83918950 Inappropriate ioctl for device <Pinentry>
gnupg:gnupg:_read_response:851:  gpg: agent_genkey failed: Inappropriate ioctl for device
gnupg:gnupg:_read_response:851:  gpg: key generation failed: Inappropriate ioctl for device
gnupg:gnupg:_read_response:851:  [GNUPG:] ERROR key_generate 83918950
gnupg:gnupg:_read_response:851:  [GNUPG:] KEY_NOT_CREATED
gnupg:gnupg:_read_response:851:  gpg: secmem usage: 0/65536 bytes in 0 blocks
```

**Comment by sallain** [comment]
Added to release notes, no docs needed.

**Comment by sevein** [comment]
I've submitted #426 that covers a different part of the application that was also interacting with the GnuPG binary directly. With #426, `aip-encryption.feature` passes in development.
