### ISSUE TITLE
Problem: Cannot save settings on general settings form in 1.8

### ISSUE THREAD

**Issue by ross-spencer** [archivematica/Issues#307]
**Expected behaviour**

Changing a setting on General Settings should take effect when the form has been submitted.

**Current behaviour**

The lambda in this line of code `map(lambda form: form.save(), forms)` does not seem to do the actual `save`, despite the lambda above seemingly performing the validation function. 

https://github.com/artefactual/archivematica/blob/d6b004ece75cc359df6a224c477a9f2a49fe74ec/src/dashboard/src/components/administration/views.py#L462-L465

I can't see why this wouldn't work. 

An alternative to the two lambdas is a simple for loop:
```
    forms = (general_form, storage_form, checksum_form)
    for form_ in forms:
        if form_.is_valid():
            form_.save()
    messages.info(request, _('Saved.'))
```

**Steps to reproduce**

Try to change the checksum algorithm on this page, navigate away, and then monitor the result. It won't have changed.

**Your environment (version of Archivematica, OS version, etc)**

Verified on: `am18bionic`, and locally running `qa/1.x`.

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by sallain** [comment]
Added to release notes, no docs needed.
