### ISSUE TITLE
Problem: No default description for a transfer source in the Storage Service/Archivematica

### ISSUE THREAD

**Issue by ross-spencer** [archivematica/Issues#31]
**Please describe the problem you'd like to be solved.**

When the default locations are created in the Storage Service the default transfer source sometimes displays as a blank field inside Archivematica. Previously, this has shown up as `/home` or other folder on the configured machine. 

**Describe the solution you'd like to see implemented.**

A default location name might be a good idea as currently the prompt for the user looks to be 'click this drop-down on an unlabelled field'. 

**Describe alternatives you've considered.**

This could of course be left as-is. 

**Additional context**

The defaults are set [here](https://github.com/artefactual/archivematica-storage-service/blob/31bad497be0ce1c94f3bf3413a93b75bae9815e3/storage_service/locations/models/pipeline.py#L91-L159) in the code for the storage service.

**Comment by sromkey** [comment]
Bumpity bump, I'm guessing this wouldn't be a hard fix for 1.12.

**Comment by sromkey** [comment]
This has been fixed for 1.13, verified during release testing.
