### ISSUE TITLE
Problem: size and usage on "Processing storage usage" screen are misleading/incorrect

### ISSUE THREAD

**Issue by sallain** [archivematica/Issues#312]
**Please describe the problem you'd like to be solved.**

Under the Administration tab, there is a page called _Processing storage usage_.

![image](https://user-images.githubusercontent.com/4612276/47882189-f015a600-dde5-11e8-8d41-904db169f8e2.png)

The intention of this page is to show users how much space is available in their Currently Processing location (here represented by the path `/var/archivematica/sharedDirectory/`) . Users can also clear out a few subdirectories (i.e. folders that store rejected and failed transfer artifacts) by clicking on the **Clear** button. On the right, the size of the folder and the usage are displayed, but these values are not accurate for their stated purpose and are unhelpful to users.

The first line of this table states that the Currently Processing location has 193.8 GB of total space available - but I believe this is actually the total space available for the root directory (`/`), not just the sharedDirectory partition. Even if you apply a quota to the Currently Processing directory through the storage service (i.e. 5GB) the value listed on the processing storage usage page doesn't change. Therefore, the usage and percentage (in the above example, `245.6 KB (0%)`) is both incorrect and misleading. Users can't rely on this to see how much processing space they actually have available.

The way that the table is read, it looks like each of the subdirectories also has 193.8 GB of space available. This is inaccurate and could cause confusion.

**Describe the solution you'd like to see implemented.**

I'd like the processing storage usage page to display a correct value for the Currently Processing directory, so that users can see how much directory space is available. This will allow users to make more educated decisions about transfer size and, hopefully, mitigate failures caused by running out of processing space, which is a common problem.

This may require sysadmins to declare a quota for this storage location through the Storage Service, but I think that's an acceptable compromise.

For each subdirectory (rejected, failed, etc.) it's helpful to know how much data is contained within them, but it needs to be clearer that they take up space within their parent directory. That relationship needs to be clear to users if this page is going to be helpful for avoiding disk full failures.

It could also be helpful to see the total space available for the root directory. This would take into account the size of Archivematica itself, and could be quite helpful to sysadmins and users alike.

**Additional context**

Based on a quick and dirty test, it seems that the paths shown in the dashboard are hard-coded. I changed the sharedDirectory path in the Storage Service and this change was not reflected in the dashboard. More investigation will be required.

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by ross-spencer** [comment]
RE: the hard-coding of this information, this is related https://github.com/artefactual/archivematica/issues/885

**Comment by jraddaoui** [comment]
As noted by @ross-spencer in the related issue, these processing locations paths are created based on the `shared_directory` config setting:

https://github.com/artefactual/archivematica/blob/qa/1.x/src/dashboard/src/components/administration/views.py#L184-L208

The size and usage are obtained by parsing the output of the `df` and `du` commands:

https://github.com/artefactual/archivematica/blob/qa/1.x/src/dashboard/src/components/administration/views.py#L232-L273

However, looking at the MCPServer code, the watched directories are also being created based on the `shared_directory` config setting:

https://github.com/artefactual/archivematica/blob/qa/1.x/src/MCPServer/lib/archivematicaMCP.py#L253-L316

Moreover, when defaults locations are created in the SS for a pipeline, they use a hard-coded path that matches the default value of the `shared_directory` config setting:

https://github.com/artefactual/archivematica-storage-service/blob/qa/0.x/storage_service/locations/models/pipeline.py#L86
https://github.com/artefactual/archivematica/blob/qa/1.x/src/dashboard/src/settings/base.py#L63

So, the first thing I wonder is what is the correlation between the shared and watched directories in a pipeline and the related currently processing location in the SS. Why do they share the same path? What would happen if a custom currently processing in a different path is used? Would it affect the MCPServer workflow by not being in the same path than the watched directories?

To answer part of my questions, looking at the MCPServer and MCPClient code, it seems like the rely in the `shared_directory` config setting in some cases too, so I'd guess that having the SS currently processing location in a different path should not affect the watched directories workflow actions in the MCPServer. But then I wonder, why do they share the same path in a default installation?

**If that's the case, then this information could not be retrieved from the SS and the current behavior is not that bad.** We could definitely add the root of the file system (it could be `/` or a different path if the shared directory is in a mounted partition) and improve the current display to make it clear that the available space belongs to the root and not to each directory. We could also add a few more of those hard-coded directories (from the watched directories declaration in the MCPServer) to allow the clean-up action in more paths.

**If that's the case, we should be using different paths for the shared directories and the default currently processing location for the pipeline**, to avoid the confusion. And maybe rename a few things like this page to make it clear that they are not related locations/paths.

---

The other two pages (Transfer sources locations and AIP Storage locations) actually make requests to the SS:

https://github.com/artefactual/archivematica/blob/qa/1.x/src/dashboard/src/components/administration/views.py#L343-L350
https://github.com/artefactual/archivematica/blob/qa/1.x/src/dashboard/src/components/administration/views.py#L148-L155

The response from the SS service also includes the quota and usage from each location:
```
[{u'uuid': u'fc1e44c6-c107-44f7-b850-17b5d089e846', u'pipeline': [u'/api/v2/pipeline/d3c7fbbe-4024-4b3e-9a42-c2abd7d93287/'], u'used': u'21214945', u'description': u'Store AIP in standard Archivematica Directory', u'space': u'/api/v2/space/1269aa8e-cd71-4b08-b264-bff2ec792675/', u'enabled': True, u'quota': None, u'relative_path': u'var/archivematica/sharedDirectory/www/AIPsStore', u'purpose': u'AS', u'path': u'/var/archivematica/sharedDirectory/www/AIPsStore', u'resource_uri': u'/api/v2/location/fc1e44c6-c107-44f7-b850-17b5d089e846/'}]
```

This pages could also be improved to include the currently processing and other locations related to the pipeline and show the quota and usage for each of them. However, the `used` value is only being updated in a few location types and only in a few cases, so this will require additional work in the SS to keep those values properly updated on each location.

**Comment by sallain** [comment]
@jraddaoui Okay, so I think I understand... about half of the technical details here :slightly_smiling_face: I've tried to summarize this as a problem statement. Please feel free to correct any inaccuracies!

**Problem**
The Currently Processing directory and the MCPServer watched directories share the same path, which makes it difficult to get accurate usage information because the two locations serve different purposes.

**Outstanding questions**
* Why do the Currently Processing directory and watched directories share the same path? Is there a compelling architectural reason that this decision was made?
* What would happen if a custom Currently Processing path was used?
* Would it affect the MCPServer workflow if the Currently Processing directory did not share a path with the watched directories?

**Benefits to changing the path**

If we can change the paths so that the Currently Processing directory is not sharing a path with the MCPServer watched directories, we could do the following:

* Add the root path of the file system (it could be / or a different path if the shared directory is in a mounted partition) and improve the current display to make it clear that the available space belongs to the root and not to each directory.
* Add a few more of those hard-coded directories (from the watched directories declaration in the MCPServer) to allow the clean-up action in more paths.

**Other things we can do**

Even without the above path changes, we can tackle the following:

* Rework the layout of the _Processing storage usage_ page to make the distinction between the locations and paths clear
* Improve the _Transfer source locations_ reporting page to include the Currently Processing and other locations related to the pipeline and show the quota and usage for each of them. This will require additional work in the SS to keep those values properly updated on each location.
* Improve the _AIP storage locations_ reporting page to include the currently processing and other locations related to the pipeline and show the quota and usage for each of them. This will require additional work in the SS to keep those values properly updated on each location.

---

Is that an accurate summary?

**Comment by jraddaoui** [comment]
Thanks for the follow-up @sallain,

Took a deeper look to the outstanding questions and it seems like the relation between the shared directory setting in the pipeline and the currently processing location in the SS is intentional and needed at this point. When a pipeline is registered in the SS with the default configuration, the shared directory setting is passed in the request and used to create the currently processing location in the default space:

https://github.com/artefactual/archivematica/blob/qa/1.x/src/dashboard/src/installer/steps.py#L109-L115
https://github.com/artefactual/archivematica-storage-service/blob/qa/0.x/storage_service/locations/models/pipeline.py#L97-L102

Also, the default locations created in the SS on the start-up process use harcoded paths inside the default shared directory:
https://github.com/artefactual/archivematica-storage-service/blob/qa/0.x/storage_service/storage_service/urls.py#L70-L109

So, changing the paths will require further analysis. However, I think the benefits are not completely tied to changing the path and that we can also do the other things, I'll send estimates for that via email.

**Comment by jraddaoui** [comment]
Sent estimates for the following tasks:

_Dashboard: Processing storage usage page:_

1. Rename the page to make it clear the paths are created from the shared directory setting.
2. Add the root path of the file system and improve the current display to make it clear that the available space belongs to the root and not to each directory.
3. Add more directories from the watched directories declaration in the MCPServer to allow the clean-up action in more paths.
4. Improve error handling (issues with `du` and `df` commands, non existing paths, problems deleting files).

_Dashboard: Transfer source and AIP storage locations pages:_

5. Unify this pages and include other locations related to the pipeline.
6. Show `quota` and `used` values for each location (`used` value may not be properly updated, see 8 bellow).

_Storage Service:_

7. Move default locations created on startup (AIP and DIP storage and Backlog) outside the default shared directory.
8. Monitor quota usage for selected spaces/locations (periodic background task to update `used` value).

**Comment by sallain** [comment]
Related to #323, #325, #312

**Comment by sallain** [comment]
If it's not too much extra time, I've proposed another enhancement that we could do as part of this project: [Change storage location reporting unit from bytes to GB (or something else)](#350). Bytes are not a very helpful unit of measurement for the average user looking at storage space - GBs are much more widely-used and the values presented are easier to understand.

For example, 398413571 B / 429496729600 B takes a few seconds (and maybe an online unit converter) to parse, whereas 0.37105 GB / 400 GB is very clear.

**Comment by jraddaoui** [comment]
Merged in qa/1.x. Final changes included in this work:

Unify SS locations administration pages:

    - Remove transfer source locations URL, link and view.
    - Rename 'AIP storage locations' link to 'Storage locations'.
    - Change 'Storage locations' page title and add page description.
    - Show all related SS locations for this pipeline in this page, except
      currently processing, AIP recovery, SS internal purposes and
      disabled locations.
    - Sort locations by purpose and show it in human readable form.
    - Show formatted used and quota values for AIP and DIP storage locations.

Improve processing storage usage page:

    To avoid timeouts on the first load of this page, the usage data is only
    calculated when the `calculate` get parameter is evaluated as `True`.
    When the usage data is not calculated, the page shows a description and
    a button to reload the page calculating the usage. When the usage is
    calculated, the page will display a general information section and a
    table of clearable directories from within the shared path.

    - Show the root of the filesystem where the shared directory is located.
    - Only show the size of the root path.
    - Simplify directory list generation and only include clearable dirs.

**Comment by sallain** [comment]
Testing note: check #495 and #757 as well, fixes here might solve those issues.

**Comment by ablwr** [comment]
Wooooooowwww this is very exciting, y'all!!!

**Comment by ablwr** [comment]
Here's a screenshot for @sallain :)

![Screenshot from 2020-01-07 12-20-07](https://user-images.githubusercontent.com/3260492/71914920-a098db80-3148-11ea-80af-55dc1059e11c.png)

**Comment by sallain** [comment]
@jraddaoui I've tested this and it looks great! The `Processing storage` page functions as expected. It'll be interesting to see how it performs with larger instances and different storage arrangements, but on local filesystem setups like our test VMs it works well.

The only issue I've found is that deleting a package from storage doesn't result in the count going down (either on the `Storage locations` page in the dashboard or in the Locations tab of the SS), for AIPs or DIPs. It seems to be addition-only:

1. I have one AIP in storage. The `Storage locations` screen reports 33.2 MB.
2. I delete the AIP, which should bring the storage location back down to 0 MB.
3. The `Storage locations` screen still reads 33.2 MB.
4. I create a new AIP that is 0.8 MB.
5. The `Storage locations` screen now reads 34 MB.

**Comment by jraddaoui** [comment]
Thanks @sara,

I've addressed that issue in the PR above. However, the situation is far from being perfect, a few things to consider:

- As noted in this issue, the used value is only being updated in a few location types and only in a few cases, so this will require additional work in the SS to keep those values properly updated on each location. We came up with an estimate to create a task to monitor those values but decided not to include it in this work and, depending on the direction of the project, we may want to consider better options when we get to that point.

- The current implementation doesn't consider race conditions. This will be hard to reproduce though the GUI but it could become a problem in an automated workflow with multiple pipelines. They're not considered in the update nor the check, so the used value could be misleading or even pass the quota.

- This change will only fix the issue for new deletions, instances where it already happened will remain with the wrong used value.

I hope we have some time to improve this soon.

**Comment by jraddaoui** [comment]
> If it's not too much extra time, I've proposed another enhancement that we could do as part of this project: [Change storage location reporting unit from bytes to GB (or something else)](https://github.com/archivematica/Issues/issues/350). Bytes are not a very helpful unit of measurement for the average user looking at storage space - GBs are much more widely-used and the values presented are easier to understand.
> 
> For example, 398413571 B / 429496729600 B takes a few seconds (and maybe an online unit converter) to parse, whereas 0.37105 GB / 400 GB is very clear.

I've looked at this too and the only place that I found that remains using Bytes only in the Storage Service are the locations tables. However, in this case it's not a easy fix, as it will require to change how the entire table is loaded to not break the sorting over that column.

If we're okay with the sorting issue, I have a quick fix that we could include in this release, but I think it's better to do it properly in the next one.

**Comment by sallain** [comment]
@jraddaoui The number now goes down when something is deleted, so that bit is solved!

Thanks for laying out these other issues.

> The current implementation doesn't consider race conditions. This will be hard to reproduce though the GUI but it could become a problem in an automated workflow with multiple pipelines.

I think we have generally assumed that folks running AM in a highly automated fashion will be monitoring space usage in a much more sophisticated way, but this is an implicit assumption and is not stated anywhere. At this point, if this works for front-end users, I think that's an okay threshold. 

> This change will only fix the issue for new deletions, instances where it already happened will remain with the wrong used value.

I can include a note about that in the docs. This is a step-change towards having accurate reporting and maybe we will be able to retroactively fix it in a more holistic way in the future.

> If we're okay with the sorting issue, I have a quick fix that we could include in this release, but I think it's better to do it properly in the next one.

Agreed.

**Comment by sallain** [comment]
@jraddaoui @sromkey I think that we have done enough here to close this issue - but am hesitant to actually do it :sweat_smile: Thoughts? Is there anything we need to do to wrap this up, or reflect the next steps somewhere?

**Comment by sromkey** [comment]
It seems like we've addressed the main gist of this issue and further issues could be opened in the future if we decide to tackle further work on this.

**Comment by ablwr** [comment]
:+1: and happy to see this addition in the upcoming release!
