### ISSUE TITLE
Problem: Fixity version needs to be bumped to 0.4

### ISSUE THREAD

**Issue by ross-spencer** [archivematica/Issues#320]
Following a couple of additions to the code since 2016, we should bump the fixity release to 0.4. We might want to wait for the docs changes associated with #317 first if those are made in the next few days.

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by sevein** [comment]
https://github.com/artefactual/fixity/releases/tag/v0.4.0
