### ISSUE TITLE
Problem: The rebuild AIP command duplicates existing AIPS

### ISSUE THREAD

**Issue by mamedin** [archivematica/Issues#329]
**Version of the documentation**
1.8

**Page (and section, if applicable) where the issue occurs**
`Page`: https://github.com/artefactual/archivematica-docs/blob/1.8/admin-manual/installation-setup/upgrading/upgrading.rst
`Section`: "Rebuild the AIP index:"

**Description of the issue**
The command in section "Rebuild the AIP index" duplicates the existing AIPs at "Archival Storage" tab.

**Suggested fix**
Adding the ``--delete`` or ``--delete-all`` option does not duplicate the existing AIPs at "Archival Storage" tab.
See https://github.com/artefactual/archivematica/blob/qa/1.x/src/dashboard/src/main/management/commands/rebuild_elasticsearch_aip_index_from_files.py

**Comment by ablwr** [comment]
This section doesn't exist in the current documentation anymore, so I think it's fair enough if we consider this "resolved."

This section of the docs covers the above, including documentation of flags: https://www.archivematica.org/en/docs/archivematica-1.10/admin-manual/maintenance/maintenance/#rebuild-the-indexes
