### ISSUE TITLE
Problem: Cannot store AIPS when there is an AIP Storage Location with no description  

### ISSUE THREAD

**Issue by jhsimpson** [archivematica/Issues#340]
**Expected behaviour**
The Storage Service gui allows AIP Storage Locations to be defined where the description is an empty string. It is not possible to store an aip in an aip storage location that has no description.  Either the description should be made a required field, or the getAipStorageLocations client script should be able to handle aip storage locations with no description.

**Current behaviour**
When getAipStorageLocations is called, and the storage service returns an AIP Storage Location with the description missing, getAipStorageLocations does not set the aip storage location properly.  
This causes the next job (move to processing directory) to fail.

https://github.com/artefactual/archivematica/blob/stable/1.7.x/src/MCPClient/lib/clientScripts/getAipStorageLocations.py

**Steps to reproduce**
1. In the Storage Service gui, edit the description of the default aip storage location. Set the description to be empty (delete all text in the text box).
2. Create a transfer and attempt to process it through to the store aip microservice.  It will fail in the 'move to processing directory' job of the 'store aip' microservice.  The stdout of the job will show something like 
`/api/v2/location/5759c85f-7ff0-4143-b1cf-bc6bb85682ed/"/api/v2/location/5759c85f-7ff0-4143-b1cf-bc6bb85682ed/%/api/v2/location/5759c85f-7ff0-4143-b1cf-bc6bb85682ed/S/api/v2/location/5759c85f-7ff0-4143-b1cf-bc6bb85682ed/I/api/v2/location/5759c85f-7ff0-4143-b1cf-bc6bb85682ed/P/api/v2/location/5759c85f-7ff0-4143-b1cf-bc6bb85682ed/D/api/v2/location/5759c85f-7ff0-4143-b1cf-bc6bb85682ed/i/api/v2/location/5759c85f-7ff0-4143-b1cf-bc6bb85682ed/r/api/v2/location/5759c85f-7ff0-4143-b1cf-bc6bb85682ed/e/api/v2/location/5759c85f-7ff0-4143-b1cf-bc6bb85682ed/c/api/v2/location/5759c85f-7ff0-4143-b1cf-bc6bb85682ed/t/api/v2/location/5759c85f-7ff0-4143-b1cf-bc6bb85682ed/o/api/v2/location/5759c85f-7ff0-4143-b1cf-bc6bb85682ed/r/api/v2/location/5759c85f-7ff0-4143-b1cf-bc6bb85682ed/y/api/v2/location/5759c85f-7ff0-4143-b1cf-bc6bb85682ed/%/api/v2/location/5759c85f-7ff0-4143-b1cf-bc6bb85682ed/"/api/v2/location/5759c85f-7ff0-4143-b1cf-bc6bb85682ed/ /api/v2/location/5759c85f-7ff0-4143-b1cf-bc6bb85682ed/"/api/v2/lo`

**Your environment (version of Archivematica, OS version, etc)**
Archivematica 1.7.2 on ubuntu or centos.  Not tested on 1.8.0 yet

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by sallain** [comment]
Just throwing in my two cents: I think description should be made a required field. Through the Red Team disk full project, I'm hoping to have more information about locations represented in the Archivematica UI. An important component of this is the description field - it's used as the main name field for the location, as opposed to the use field (many locations can have the same use) or the path (paths can be very similar and aren't always descriptive).

**Comment by ross-spencer** [comment]
The primary issue described here should be solved by: https://github.com/archivematica/Issues/issues/456

Though there are still limitations noted by @sallain here: https://github.com/archivematica/Issues/issues/456#issuecomment-462929366

@sevein notes a small inconvenience to making descriptions required here: https://github.com/archivematica/Issues/issues/456#issuecomment-460695446

Perhaps though, we can close this, and open a feature ticket?

**Comment by ross-spencer** [comment]
Demonstration of this working, the description doesn't exist for the storage location selected here an so it defaults to the path the user can expect to find the AIP on the storage service. Fixed in `1.9.0`.

![Peek 2020-12-07 20-31](https://user-images.githubusercontent.com/1880412/101426648-5f1a2e80-38cb-11eb-9d9e-53551216ca44.gif)
