### ISSUE TITLE
Problem: MediaConch "validation against policy" error logs are reporting the wrong info in the UI

### ISSUE THREAD

**Issue by sallain** [archivematica/Issues#345]
**Expected behaviour**
If there's an error in a MediaConch validation against a policy, the stdout/stderr in the task output should contain some informative information about the error to help us diagnose the problem.

**Current behaviour**
When an error occurs (i.e. the policy is malformed) at _Job: Policy checks for originals_, the error output in the stderr contains this text:

```
policycheck_v0.0: ERROR     2018-11-20 19:35:35,412  archivematica.mcp.client.policyCheck._execute_rule_command:234  Unable to load an object from the malformed JSON in
Traceback (most recent call last):
  File "/usr/lib/archivematica/MCPClient/clientScripts/policy_check.py", line 230, in _execute_rule_command
    output = json.loads(stdout)
  File "/usr/lib64/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

The actual error is related to a malformed policy - it should contain some information along the lines of what we see in MediaConchOnline when there's a policy error:

```
Validation generated an internal error:    Invalid expression
    compilation error: element when
    xsl:when : could not compile test expression 'mi:MediaInfo/mi:track[@type='General'][*]/mi:FormatIs equal (=)'MPEG-4''
```

(The error that creates the malformed policy happens in MediaConchOnline and is logged here: https://github.com/MediaArea/MediaConchOnline/issues/95. We don't need to fix this error, just the reporting of it.)

@jhsimpson did some investigation and proved that the error is actually being reported in the logs, but it's not being output into the stderr.

**Steps to reproduce**
1. Create a policy with a deliberate error, set up the appropriate rule, etc.
2. Run a transfer containing an appropriate file.
3. The transfer should fail at "Job: Policy checks for originals". Check the task output.

**Your environment (version of Archivematica, OS version, etc)**
1.8

Note: I didn't check to see if this happens with regular MediaConch validation (i.e. validation for Matroska files). I also didn't try validating preservation or access copies against a policy to see if this error occurs there as well.

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by ross-spencer** [comment]
Hi @sallain, @ablwr, seeing the PR logged against this issue triggered a memory of this PR: https://github.com/artefactual/archivematica/pull/995 it might be something to keep in mind (or not, I haven't done much with this workflow yet). Could maybe provide a test-vector when we come to review.

**Comment by ablwr** [comment]
@ross-spencer Thank you! Yeah there's a lot of modifications done to get this work integrated and I'm afraid I don't have all the history w/r/t the decisionmaking... nor am I very familiar yet with the codebase as a whole! Many questions.

**Comment by ablwr** [comment]
I guess my rationale for the above change is "Keep things as they are, but if something goes wrong, give the user absolutely everything!" The `stdout` refuses to be parsed when there is an invalid XML in the middle, even if the XML is invalid for reasons that wouldn't normally break JSON (like a value in double-quotes being the wrong value, not an error like missing a doublequote).
