### ISSUE TITLE
Problem: md5deep checksum validation for multiple files with same checksum

### ISSUE THREAD

**Issue by mjaddis** [archivematica/Issues#346]
**Expected behaviour**
If I have a transfer with multiple files that happen to have the same checksum and these are listed correctly in checksum.md5 in the metadata directory, then I expect checksum validation to pass at the Transfer stage of the workflow.

**Current behaviour**
Checkum validation fails with error code 110.  However, logs from the script show that the md5deep tests actually passed, for example:

```
PASSED
/var/archivematica/sharedDirectory/currentlyProcessing/md5deep1-93325aa1-1a22-46f6-a815-1adec5b47fbe/objects/earth1.jpg
/var/archivematica/sharedDirectory/currentlyProcessing/md5deep1-93325aa1-1a22-46f6-a815-1adec5b47fbe/objects/earth2.jpg
 
2 items passed integrity checking
 
 
FAILED
 
0 items failed integrity checking
```

**Steps to reproduce**
create a transfer containing two files that have different filenames but the same checksum.  Use md5deep to generate a manifest and put this in checksum.md5.  For example:

``` 
6b72dc8ff4cd45df12e971a466fabc09  objects/earth1.jpg
6b72dc8ff4cd45df12e971a466fabc09  objects/earth2.jpg
```

It looks like md5deep is exiting with a 1 when there is more than one entry in the manifest that matches a given file in the objects directory.   If there aren't duplicates then it exits 0.  However, ignoring the exit code, actual the test still passes.   The Archivematica script concatenates the return codes of `md5deep -r -m`, `md5deep -r -x` and the count of failed files.  Hence the 110 code.  

Better perhaps to use `md5sum -c` instead of `md5deep` as this would involve the correct entry in the manifest being used agains the correct payload file in the objects dir? 

Run this as a standard Transfer.

**Your environment (version of Archivematica, OS version, etc)**
AM1.7.2 on 16.04 LTS 

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by sallain** [comment]
Just a note to say that a user came across this issue independent of this conversation (funny how that always happens!) and one concerning factor is that Archivematica provides absolutely no indication in the UI that this is what's causing the issue. Not sure if there's something in the client scripts that could be passed to the stderr/stdout to improve this so that users have a hope of diagnosing the issue.

**Comment by mjaddis** [comment]
Great discussion of the issues.  In terms of checking a manifest against the payload of a transfer, 'md5sum -c' does the job very well and could replace md5deep in my view.  I think the question is what to do about files that aren't in the manifest.   Should the transfer fail if there are files not in the manifest, should the extra files be ignored, or should the extra files be physically deleted?   

I would be happy with the following:  

1. If I provide a checksum.md5 in a Transfer then I want each and every entry in the manifest to be checked against the payload of the Transfer so I know that my specified list of files are all present and correct (name, path, checksum).  If any entries in the manifest fail to be verified then I want the whole Transfer to fail.

2. If there are files in the Transfer that are not listed in the checksum.md5 then I either want them to be ignored or to be deleted.  They are not relevant to my Transfer.  However, I don't want the Transfer to fail.

The behaviour above is a slightly different to the way it is designed currently.  If there are files in a Transfer that don't match the manifest then the Transfer is failed.  Personally, I'd be happy if this was relaxed a little.  It's all to easy for users to pollute a Transfer with .DS_Store, Thumbs.db and other junk files, e.g. simply by using Finder or Explorer to 'look inside' a Transfer before copying it to Archivematica.   I can't remember what Archivematica's policy is for handling junk files, e.g. removing them, but if there are files like this in a Transfer and they are not listed in a checksum.md5 (or maybe they are listed but have changed), then I'd prefer them to be ignored rather than cause a Transfer to fail.

**Comment by ross-spencer** [comment]
Such a great analysis @andrewjbtw, thank you! 

Speaking as independently as possible, I think more in response to @mjaddis I'd like to understand how best to handle the files not on the manifest we're checking aginst use-case. I'd love to know both what was and wasn't there, and have control over deletion or not, and possibly, failure or not too, because at some point in the workflow everything gets taken over by Bagit's conventions. Of course, it starts to make the solution more complex, i.e. from a tool/script change, to database-workflow migrations... so there's that!

**Comment by ross-spencer** [comment]
I need to incorporate this with the AM codebase, but here is a gist beginning to approximate the way this might work as a shell script: https://gist.github.com/ross-spencer/4bd776a221a26c71ed0d9ee96bc12a34

**Comment by ross-spencer** [comment]
Related to https://github.com/archivematica/Issues/issues/346
