### ISSUE TITLE
Feature: Streamlining decision points on the transfer workflow

### ISSUE THREAD

**Issue by carlwilson** [archivematica/Issues#347]
**Please describe the problem you'd like to be solved.**
The Archivematica workflow has various descision points where the user selects a choice from a dropdown. This happens even when there's only a single choice, which seems unnecessary.

**Describe the solution you'd like to see implemented.**
Detect if there's only a single option to offer and make the decision for the user.

**Describe alternatives you've considered.**
None really.

**Additional context**
Using version 1.6.1 as set up by Arkivum.

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by sromkey** [comment]
Hi @carlwilson - thanks for this- can you give some examples? I'm struggling to think of any that have only one choice, other than the metadata reminder, the purpose of which is to pause the workflow for the user. You can also preconfigure as many of them as you'd like in the processing configuration: https://www.archivematica.org/en/docs/archivematica-1.8/user-manual/administer/dashboard-admin/#dashboard-processing

**Comment by ross-spencer** [comment]
I just had a quick look, and it seems three which have one choice are:

* Approve normalization (None/Yes)
* Reminder: add metadata (None/Continue)
* Store AIP (None/Yes) 

For documentation's sake, outside of the processing configuration (as noted above, can all be resolved prior to transfer), if any of these values are set to `None` then two of these have specific actions the user can perform, other than yes/no like decisions, e.g. enter a metadata form and add Dublin Core metadata, or look at the outcome of various normalization processes. Store AIP on the outside looks like a strange one, but this will also offer the user the ability to review the AIP for the last time before storing. In a sense these decision points make our workflow a little more 3D than 2D than it might seem at first :nerd_face:.

**Comment by sallain** [comment]
With work in Archivematica [1.7](https://wiki.archivematica.org/Archivematica_1.7_and_Storage_Service_0.11_release_notes) and [1.8](https://wiki.archivematica.org/Archivematica_1.8_and_Storage_Service_0.13_release_notes), we have improved the workflow so that every choice can be pre-set in the processing configuration. While there are still dropdowns where there is only one choice, users can now easily automate them. Closing this issue as I believe that is a sufficient resolution.
