### ISSUE TITLE
Problem: create_aic_mets.py client script fails due to broken import

### ISSUE THREAD

**Issue by payten** [archivematica/Issues#35]
**Expected behaviour**
`create_aic_mets.py` client script doesn't throw error due to broken import.

**Current behaviour**
`create_aic_mets.py` client script throws an unknown import error due to file name change of the `archivematicaCreateMETS2.py` client script (is now `create_mets_v2.py`).

**Steps to reproduce**
Run `python create_aic_mets.py` from the command line.

**Your environment (version of Archivematica, OS version, etc)**
qa/1.x running under docker.

**Comment by joel-simpson** [comment]
I tried testing this by creating an AIC according to the documentation here: https://www.archivematica.org/en/docs/archivematica-1.7/user-manual/archival-storage/aic/

The Create AIC job failed. 
![screenshot from 2018-07-26 21-38-51](https://user-images.githubusercontent.com/17187309/43296954-6207c4bc-911c-11e8-8bb4-192c2aaab69e.png)

The task output was: 
![screenshot from 2018-07-26 21-41-58](https://user-images.githubusercontent.com/17187309/43297045-e9f1a1c2-911c-11e8-879a-0cea6aaacf10.png)



I've no idea if that is related to the original problem @payten but clearly it's the same script failing... mabye you can have a look? 
This was tested in a local docker environment (built with qa/1.x today)

**Comment by ross-spencer** [comment]
Hi @joel-simpson I suspect this is a typo: https://github.com/artefactual/archivematica/blob/qa/1.x/src/MCPClient/lib/clientScripts/create_aic_mets.py#L163 and should be `job.args[1:]`. I'd need to just try this locally to confirm.

**Comment by ross-spencer** [comment]
@peterVG this should be good to go now. Before and after:

![image](https://user-images.githubusercontent.com/1880412/46373384-86be3e00-c653-11e8-8312-649980cb20e5.png)

**Comment by peterVG** [comment]
I've seemed to run into a new problem where the Prepare AIC microservice is never actually run. I've tried adding an AIC number at several metadata entry points but I'm not having any luck.
