### ISSUE TITLE
Problem: Archivematica version number isn't updated when upgrading from 1.7 to 1.8

### ISSUE THREAD

**Issue by sromkey** [archivematica/Issues#353]
**Expected behaviour**
In version 1.8, the METS file should have the premis:linkingAgentIdentifierValue of Archivematica-1.8

**Current behaviour**
It has Archivematica-1.7

**Steps to reproduce**
- Make an AIP
- Search the METS file for "Archivematica" and you'll see the incorrect value in premis:linkingAgentIdentifierValue

This is also visible in the UI under Administration- Version

**Your environment (version of Archivematica, OS version, etc)**

Tested on our amdemo site which is version 1.8 I think on Ubuntu deployed with Ansible.

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by ross-spencer** [comment]
The provenance of the Dashboard command is: https://github.com/artefactual/archivematica/issues/1192 

But this seems to speak to developer needs, not necessarily an Archivematica user. Is this right approach for an install or upgrade by a non-dev, non-Artefactual user?

**Comment by sromkey** [comment]
Miguel's PR seems to have fixed it but I think this is all good to discuss for a future release so we don't run into this problem again. Moving to verified though!
