### ISSUE TITLE
Problem: deleting AIPs does not delete associated directories from AIP store

### ISSUE THREAD

**Issue by sromkey** [archivematica/Issues#359]
**Expected behaviour**
When you delete an AIP (by making a request through the dashboard and approving it in the Storage Service), the quad directories that it was stored in would also be deleted.

One factor to consider is that it's possible for more than one AIP to reside in a quad directory if there are enough AIPs in storage that the directory tree has branched.

**Current behaviour**
The AIP is deleted but the directories remain.

**Steps to reproduce**
- request and approve the deletion of an AIP
- navigate to AIP storage on the file system and you'll see the quad directories.

**Your environment (version of Archivematica, OS version, etc)**
qa/1.x on Docker (@sevein tested for me)

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by Bolkun** [comment]
I have the same problem in archivematica version 1.11.2. When an AIP is deleted, the quad directories are not removed, only the contents of the last directory in the chain. Do you have already a solutions ti this problem?

**Comment by ross-spencer** [comment]
NB. This  is the same for packages such as those which are replicated and stored elsewhere on the file-system.

**Comment by ross-spencer** [comment]
The `why?` for a quad-tree is documented in the archivematica docs, e.g for `1.12`: [here](https://www.archivematica.org/en/docs/archivematica-1.12/user-manual/archival-storage/archival-storage/#aip-storage-structure). 

As Sarah notes, as the tree starts to branch, deletion isn't as simple as removing all quad-dirs, a significantly complicated structure asks us to complete a reverse-tree-traversal deleting from the leaf, backwards, until a directory is reached which contains no other directory. On a legacy storage system, we already recognize that empty directories may well exist in that structure. 

I have created a test which starts to mock a relatively complex structure that could be used to develop a solution: [here](https://github.com/artefactual/archivematica-storage-service/blob/91bbfbb6b2362908b27462e7f8b0abae0d8f61b9/storage_service/locations/tests/test_space.py#L166-L220).

That structure looks as follows:
```
@pytest.fixture
def aipstore_compressed(tmpdir):
    """Create a structure simulating an AIPstore with an appropriate
    level of complexity.

    i.e.

        └── 1111
            ├── 2222
            │   ├── 3333
            │   │   ├── 4444
            │   │   │   ├── 5555
            │   │   │   │   ├── 6666
            │   │   │   │   │   ├── 7777
            │   │   │   │   │   │   └── 8888
            │   │   │   │   │   │       └── 0a-11112222-3333-4444-5555-666677778888.7z
            │   │   │   │   │   └── 8888
            │   │   │   │   │       └── 9999
            │   │   │   │   │   │       └── etc.
            │   │   │   │   └── 8888
            │   │   │   │       └── 9999
            │   │   │   │           └── aaaa
            │   │   │   └── 8888
            │   │   │       └── 9999
            │   │   │           └── aaaa
            │   │   │               └── bbbb
            │   │   └── 8888
            │   │       └── 9999
            │   │           └── aaaa
            │   │               └── bbbb
            │   │                   └── cccc
            │   └── 8888
            │       └── 9999
            │           └── aaaa
            │               └── bbbb
            │                   └── cccc
            │                       └── dddd
            └── 8888
                └── 9999
                    └── aaaa
                        └── bbbb
                            └── cccc
                                └── eeee
                                    └── eeee

    which is created using the following paths which we list to help
    manual verification of this effort outside of pytest:

        1111/2222/3333/4444/5555/6666/7777/8888/0a-11112222-3333-4444-5555-666677778888.7z
        1111/2222/3333/4444/5555/6666/8888/9999/0b-11112222-3333-4444-5555-666688889999.7z
        1111/2222/3333/4444/5555/8888/9999/aaaa/0c-11112222-3333-4444-5555-88889999aaaa.7z
        1111/2222/3333/4444/8888/9999/aaaa/bbbb/0d-11112222-3333-4444-8888-9999aaaabbbb.7z
        1111/2222/3333/8888/9999/aaaa/bbbb/cccc/0e-11112222-3333-8888-9999-aaaabbbbcccc.7z
        1111/2222/8888/9999/aaaa/bbbb/cccc/dddd/0f-11112222-8888-9999-aaaa-bbbbccccdddd.tar.bz
        1111/8888/9999/aaaa/bbbb/cccc/eeee/eeee/1a-11118888-9999-aaaa-bbbb-cccceeeeeeee.zip
```

Implementing a function via the storage services which manages the backwards deletion of directories is not in and of itself a big problem for a local file-system. Something could be written which manages directory deletion and potentially checks the remaining integrity of the service. We can write good tests here too. 

What does seem to be more difficult, however, which is a larger problem of the storage service, is writing something consistent and tested across storage service types, e.g. pipeline local file-system (rsync), or some of the cloud-based adapters for which we have some compatibility with. 

S3 incidentally does seem to provide native management of this complexity. Our local file-system deletion doesn't. and our rsync managed storage locations neither. Auditing the other mechanisms, SWORD, Duracloud, seems to be a potentially arduous task. So to be clear:

For the different adapters we support it is not clear what a measurement off success is (rationally that seems like it would be 100% consistency, but pragmatically...) so _(just some immediate questions, no particular opinion meant to be implied)_:

1. Do we focus on this an adapter at a time, e.g. local file-system first?
2. Is the quad-directory concept fleshed out enough, was deletion considered in its design?
3. Do we need to start by completing/fleshing out a design document for this feature?
4. What does clean-up of a legacy storage service look like? Should probably be managed by the storage service? Will be important to get right and not delete other packages. Has anyone implemented a clean-up script?  
5. Other strategies/what else is on the horizon? E.g. anyone still looking at [protocols like OCFL](https://www.slideshare.net/simeonwarner/ocfl-samcon-2018#16). Do they impact this?

**Comment by ross-spencer** [comment]
Further to the above. while finalizing https://github.com/artefactual/archivematica-storage-service/pull/554 I read into some of the deletion code in more depth and I noticed that the functionality does exist for a local file system if we are deleting a pointer file: [removedirs which is called on pointer deletion](https://github.com/artefactual/archivematica-storage-service/blob/f02b9149863efe3e883806b7d470ab3c55273d03/storage_service/common/utils.py#L583-L602).

This code looks to work well, and so I have implemented it as I hoped for the replica PR for NHA here: https://github.com/artefactual/archivematica-storage-service/pull/554/commits/adf752de6e1dd880a7fa1f0d92eec2082715a83d

Tests have been put in place that should provide some confidence. This will also help avoid the structure in the AIPstore spiraling out of control if many more replicas are recreated through reingest like processes. 

Trying the new code in docker, you can see the AIPstore as follows. First we can see two sets of structures for the AIP and the pointer. After deletion, we can now see both structures are cleaned up:

```
root@49cc258f5883:/var/archivematica# find * | grep aa9a

sharedDirectory/www/AIPsStore/aa9a
sharedDirectory/www/AIPsStore/aa9a/f3b1
sharedDirectory/www/AIPsStore/aa9a/f3b1/32ae
sharedDirectory/www/AIPsStore/aa9a/f3b1/32ae/4f3e
sharedDirectory/www/AIPsStore/aa9a/f3b1/32ae/4f3e/8841
sharedDirectory/www/AIPsStore/aa9a/f3b1/32ae/4f3e/8841/0539
sharedDirectory/www/AIPsStore/aa9a/f3b1/32ae/4f3e/8841/0539/568c
sharedDirectory/www/AIPsStore/aa9a/f3b1/32ae/4f3e/8841/0539/568c/43f2
sharedDirectory/www/AIPsStore/aa9a/f3b1/32ae/4f3e/8841/0539/568c/43f2/0E-aa9af3b1-32ae-4f3e-8841-0539568c43f2.7z
storage_service/aa9a
storage_service/aa9a/f3b1
storage_service/aa9a/f3b1/32ae
storage_service/aa9a/f3b1/32ae/4f3e
storage_service/aa9a/f3b1/32ae/4f3e/8841
storage_service/aa9a/f3b1/32ae/4f3e/8841/0539
storage_service/aa9a/f3b1/32ae/4f3e/8841/0539/568c
storage_service/aa9a/f3b1/32ae/4f3e/8841/0539/568c/43f2
storage_service/aa9a/f3b1/32ae/4f3e/8841/0539/568c/43f2/pointer.aa9af3b1-32ae-4f3e-8841-0539568c43f2.xml

root@49cc258f5883:/var/archivematica# find * | grep aa9a
   <nothing to show>
```

**User-acceptance testing**

For user-acceptance-testing I would recommend accessing an AIPstore via the command line and creating arbitrary folders and directories, somewhere within the depth of a quad-directory structure before asking Archivematica to delete an AIP. If everything works as anticipated this arbitrary content and some of the quad-structure will still remain safe-and-sound.

**Comment by replaceafill** [comment]
As Ross [recommended](https://github.com/archivematica/Issues/issues/359#issuecomment-756267047) I created content inside some of the quad directories in the `AIPsStore` location before removing the AIP and I see the content is preserved and the unnecessary quad directories have been removed.
