### ISSUE TITLE
Problem: can't create space via API

### ISSUE THREAD

**Issue by sevein** [archivematica/Issues#36]
At the moment, it's not possible to create spaces via the API.

E.g. I want to send a request like the following (using cURL):

```
curl \
    -X POST \
    -d @payload.json \
    -H "Authorization: ApiKey test:test" \
    -H "Content-Type: application/json" \
        http://127.0.0.1:8000/api/v2/space/
```

Where `payload.json` is:

```json
{
    "access_protocol": "S3",
    "path": "",
    "staging_path": "/",
    "endpoint_url": "http://127.0.0.1:12345",
    "access_key_id": "_Cah4cae1_",
    "secret_access_key": "_Thu6Ahqu_",
    "region": "us-west-2"
}
```

The last four properties are specific to the S3 protocol.

**Comment by joel-simpson** [comment]
Tested by creating an S3 space as shown in the example. 
Working as expected!

I also updated documentation on the wiki here: https://wiki.archivematica.org/Storage_Service_API#Create_space
