### ISSUE TITLE
Problem: transfers can't be started in AM18 RPM upgrades

### ISSUE THREAD

**Issue by rodyoukai** [archivematica/Issues#360]
**Expected behaviour**

Start a Transfer...

**Current behaviour**

In console chrome I get :

![captura de pantalla de 2018-12-05 14-11-11](https://user-images.githubusercontent.com/15165226/49541888-a531f700-f899-11e8-851d-d2b197a8a259.png)

**Steps to reproduce**

Enter to dashboard, tab transfer, select standar, type transfer name, click in browse, select folder to transfer, click add, and click start Transfer

**Your environment (version of Archivematica, OS version, etc)**

CENTOS 7, I upgrade archivematica from 1.7 to 1.8 with this guide:

https://www.archivematica.org/es/docs/archivematica-1.8/admin-manual/installation-setup/upgrading/upgrading/#upgrade

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by sromkey** [comment]
Hi @rodyoukai - thanks for your report. It sounds like more of a deployment issue than a code issue. Would you mind posting to the Archivematica User Forum Google Group? https://github.com/archivematica/Issues/issues/360 That would be a better place to troubleshoot this issue.

**Comment by sevein** [comment]
@mamedin was able to reproduce the issue.

I suspect he problem is on how we're running `collectstatic`. In our RPM, we're running [the following](https://github.com/artefactual-labs/am-packbuild/blob/e9acc7c162cd6595d12553d21bccb3c9867dffe5/rpm/archivematica/archivematica.spec#L270-L273) under `%post`:

```
/usr/share/archivematica/virtualenvs/archivematica-dashboard/bin/python manage.py collectstatic --noinput
```

I'm not sure why that's failing to propagate the latest changes - it could be a problem with timestamps? Should we use `--clear`?

> On subsequent collectstatic runs (if STATIC_ROOT isn’t empty), files are copied only if they have a modified timestamp greater than the timestamp of the file in STATIC_ROOT. Therefore if you remove an application from INSTALLED_APPS, it’s a good idea to use the collectstatic --clear option in order to remove stale static files.

CC @rodyoukai @sromkey @mamedin

**Comment by sromkey** [comment]
I apologize for assuming it was a deployment issue @rodyoukai! Thank you for bringing this to our attention.

**Comment by rodyoukai** [comment]
@sromkey Do not worry, I'm glad to help, I love Archivematica :+1:

**Comment by mamedin** [comment]
As @sevein suspected, running collecstatic with the --clear option fixes the issue:

```
sudo su -
export $(cat /etc/sysconfig/archivematica-dashboard)
cd /usr/share/archivematica/dashboard
/usr/share/archivematica/virtualenvs/archivematica-dashboard/bin/python manage.py collectstatic --noinput --clear

sudo service archivematica-dashboard restart
```

The collectstatic output when running with `--clear` option:

```
50 static files copied to '/usr/share/archivematica/dashboard/static', 150 post-processed.
```

And the same output when running without `--clear` option:

```
0 static files copied to '/usr/share/archivematica/dashboard/static', 150 unmodified, 37 post-processed.
```

**Comment by mamedin** [comment]
I could reproduce same issue on xenial package upgrade from archivematica v1.7.2.

archivematica-dashboard package upgrade output:

```
41 static files copied to '/usr/share/archivematica/dashboard/static', 109 unmodified, 46 post-processed.
```

The output when running with --clear option:

```
150 static files copied to '/usr/share/archivematica/dashboard/static', 150 post-processed.
```

**Comment by rodyoukai** [comment]
> @mamedin was able to reproduce the issue.
> 
> I suspect the problem is in how we're running `collectstatic`. In our RPM, we're running [the following](https://github.com/artefactual-labs/am-packbuild/blob/e9acc7c162cd6595d12553d21bccb3c9867dffe5/rpm/archivematica/archivematica.spec#L270-L273) under the `%post` section:
> 
> ```
> /usr/share/archivematica/virtualenvs/archivematica-dashboard/bin/python \
>     manage.py collectstatic --noinput
> ```
> I'm not sure why that's failing to propagate the latest changes - it could be a problem with timestamps? Should we use `--clear` in addition to `--noinput`?
> 
> > On subsequent collectstatic runs (if STATIC_ROOT isn’t empty), files are copied only if they have a modified timestamp greater than the timestamp of the file in STATIC_ROOT. Therefore if you remove an application from INSTALLED_APPS, it’s a good idea to use the collectstatic --clear option in order to remove stale static files.
> 
> CC @rodyoukai @sromkey @mamedin

Hi @sevein, Your command work well, now I have the frontend of archivematica 1.8 working, but I have a new issue, I will open a new post for describe it.

**Comment by mamedin** [comment]
Hi @rodyoukai, the Storage Service should need the same command:

```
sudo -u archivematica bash -c " \
    set -a -e -x
    source /etc/default/archivematica-storage-service || \
        source /etc/sysconfig/archivematica-storage-service \
            || (echo 'Environment file not found'; exit 1)
    cd /usr/lib/archivematica/storage-service
    /usr/share/archivematica/virtualenvs/archivematica-storage-service/bin/python manage.py collectstatic --noinput --clear
";
```

**Comment by mamedin** [comment]
I think you need to start mcp-client, try running: 

```
sudo service archivematica-mcp-client restart
```

**Comment by rodyoukai** [comment]
@mamedin 

> I think you need to start mcp-client, try running:
> 
> ```
> sudo service archivematica-mcp-client restart
> ```

You right, but I aware mpc-client is not installed, I dont know what happend, in 1.7 I have it and working, well...

For now my Instance of Archivematica is working...

Thanks

**Comment by sromkey** [comment]
Tested the fix, working great now. Thanks all!
