### ISSUE TITLE
Problem: When ingesting DSpace files sometimes transfers fail to approve ("Unable to find unapproved transfer directory.")

### ISSUE THREAD

**Issue by ross-spencer** [archivematica/Issues#361]
Migrated from Automation Tools repository, original ticket (and extensive notes) is here (via @hakamine): https://github.com/artefactual/automation-tools/issues/34

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by sallain** [comment]
Triaged for 1.9.1. as this issue is blocking upgrades for customers who use DSpace + automation tools.

**Comment by hakamine** [comment]
https://github.com/artefactual/automation-tools/pull/37 (which removes the problem-causing pre-transfer script) has been merged. [Helper scripts](https://github.com/artefactual-labs/transfer-source-helpers) can be used to arrange the DSpace transfer source zips into directories for the automation tools to process them without having the problem described in this issue (the helper scripts' repo is mentioned in the [automation tools README](https://github.com/artefactual/automation-tools#tips-for-ingesting-dspace-exports)

**Comment by sromkey** [comment]
Because the fix is in the automation tools and not Archivematica I'm going to remove the milestone, for release notes purposes only.

**Comment by ross-spencer** [comment]
Resolved per the comments made above https://github.com/archivematica/Issues/issues/361#issuecomment-475793976
