### ISSUE TITLE
AIP METS file has 2 different versions of premis

### ISSUE THREAD

**Issue by evelynPM** [archivematica/Issues#370]
**Please describe the problem you'd like to be solved.**
In the AIP METS file, premis 3.0 is used for intellectual entity but premis 2.2 is used everywhere else

**Describe the solution you'd like to see implemented.**
There was only one backward-incompatible change in premis 3.0 vs premis 2.2. In premis 3.0 eventDetail was changed to eventDetailInformation and made a repeatable & extensible container instead of a single semantic unit, as follows:

eventDetailInformation (O, R)
--eventDetail (O, NR)
--eventDetailExtension (O, R)

Sample eventDetail from premis 2.2:

``
<premis:eventDetail>program="python"; module="hashlib.sha256()"</premis:eventDetail>
``

Same sample in premis 3.0:

``
<premis:eventDetailInformation>
``
``   
<premis:eventDetail>program="python"; module="hashlib.sha256()"</premis:eventDetail>
``
``
</premis:eventDetailInformation>
``

**Describe alternatives you've considered.**

**Additional context**

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by evelynPM** [comment]
I've marked this as severity:high because PREMIS 3.0 came out in November 2015 - i.e. more than three years ago. The quality of Archivematica's metadata is a key to widespread adoption, and this is a relatively minor change that will bring the system up-to-date with this important standard.

**Comment by ablwr** [comment]
It looks like there's a little more than just adjusting the eventDetailInformation to get valid PREMIS. Other than updating the namespace and versions everywhere, a couple of other things:

- premis:objectCharacteristicsExtension should not exist if it is going to be blank. It should only exist if it has content, right now we make a self-closing tag.
- an update for  `<relatedObjectIdentification>` and `<relatedEventIdentification>` which are now `<relatedObjectIdentifier>` and `<relatedEventIdentifier>`

I also get this:
-  Updated needed here: "There must be PREMIS elements inside the METS container." 
But I get that with allegedly valid PREMIS in METS from the loc.gov website and there are PREMIS elements inside the METS container, so... :woman_shrugging: ?

Looks like we'll have to update our tests and their five .xml fixtures too.

**Comment by ablwr** [comment]
Another: `premis:copyrightApplicableDates` expects `premis:startDate` as its content, even if empty.

**Comment by ablwr** [comment]
mets-reader-writer will also have to be updated pretty significantly. It's writing our pointer files, which are currently coming out wrong, and I believe this also affects the ability to re-ingest.

**Comment by sevein** [comment]
The PREMIS3 update is now part of [AM dev/issue-24-handle-old-aips](https://github.com/artefactual/archivematica/tree/dev/issue-24-handle-old-aips) (https://github.com/archivematica/Issues/issues/24) where we're doing some additional changes to reingest old METS documents, being PREMIS3 only one of the changes needed. It's still work in progress. We've been successfully generating METS with PREMIS3 and reingest too, but old METS are causing some issues.

**Comment by evelynPM** [comment]
Regarding the comment "premis:objectCharacteristicsExtension should not exist if it is going to be blank. It should only exist if it has content, right now we make a self-closing tag." @ablwr would you mind filing that as a separate issue & describe the circumstances under which an empty premis:ObjectCharacteristicsExtension semantic unit would be created?

**Comment by ablwr** [comment]
@evelynPM I tried to recreate this issue but I think it was resolved in the update. I can see empty self-closing `<premis:objectCharacteristicsExtension/>` in 1.9x (viewing a processed SampleTransfers/Images) but in 1.10x, it is either present and full, or not present at all, as expected.
