### ISSUE TITLE
Problem: checksums don't verify if there is a space in the filepath and no error message is provided

### ISSUE THREAD

**Issue by sallain** [archivematica/Issues#371]
**Expected behaviour**
During the transfer, existing checksums that are included in a transfer are verified during _Job: Verify metadata directory checksums_. Given a directory of material that includes a checksum file with accurate checksums, the job should succeed. If it fails, some information should appear in the standard output/standard error, accessed by clicking on the gear icon to the right of the job name.

**Current behaviour**
If the filepaths for the digital objects in the transfer contain a space, either in the directory name or the file name, _Job: Verify metadata directory checksums_ fails. Entries in the checksum file look like this:

`f7256b095b0e4a9b7647b5b9131ddf9b sub2\sub2 1\98elect hq_disc03.E01` (space in directory name)
`b9a8c4c8212d12330efa93f26fd9e045 sub1\sub1-1\98el ect_hq_disc02.E01` (space in filename)

I'm assuming that Archivematica is interpreting the space as the end of the filepath.

The task output contains no further information about why the job failed.

![screen shot 2018-12-07 at 4 41 00 pm](https://user-images.githubusercontent.com/4612276/49679258-ed3e4e80-fa3e-11e8-867a-ef96a4cc7c97.png)

Note that in cases where this job fails because of an error, like an incorrect checksum, the task output indicates which files had an issue:

![unnamed](https://user-images.githubusercontent.com/4612276/49679427-0e536f00-fa40-11e8-9e7a-2e9f4f695e65.png)

**Steps to reproduce**
1. Create a transfer containing a checksum file where a filepath has a space in it. In the transfer I used, the directory structure looked like this:

```
test
├── metadata
│   ├── checksum.md5
└── objects
    ├── sub1
    │   └── sub1-1
    │       ├── 98el ect_hq_disc02.E01
    │       └── sub1-1-1
    │           └── sub-1-1 -1
    │               └── 98elect_hq_disc01.E01
    └── sub2
        ├── 98elect_hq_disc05.E01
        └── sub2 1
            ├── 98elect hq_disc03.E01
            └── 98elect_hq_disc04.E01
```

2. Process the transfer as a Standard transfer in Archivematica. It will fail at _Job: Verify metadata directory checksums_. Check the task output.
3. Edit the transfer to remove any spaces in directories or filenames, and update the checksum file accordingly. My edited transfer directory looked like this:

```
test-no-spaces/
├── metadata
│   ├── checksum.md5
└── objects
    ├── sub1
    │   └── sub1-1
    │       ├── 98elect_hq_disc02.E01
    │       └── sub1-1-1
    │           └── sub-1-1-1
    │               └── 98elect_hq_disc01.E01
    └── sub2
        ├── 98elect_hq_disc05.E01
        └── sub2-1
            ├── 98elect_hq_disc03.E01
            └── 98elect_hq_disc04.E01
```

4. Run the edited transfer as above. This time, the job will succeed.

**Your environment (version of Archivematica, OS version, etc)**
1.8 (Ubuntu hosted environment)

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by ross-spencer** [comment]
Curious one! There may be some logging that can be used to verify the specific behavior in this comment: https://github.com/archivematica/Issues/issues/346#issuecomment-444184763

**Comment by sallain** [comment]
Turns out I got my files mixed up and this isn't an actual problem :disappointed_relieved:
