### ISSUE TITLE
Travis fails to build in Archivematica-docs

### ISSUE THREAD

**Issue by ablwr** [archivematica/Issues#373]
**Expected behaviour**

In archivematica-docs, Travis build should pass when there are no problems with the code.

**Current behaviour**

Travis does not pass! See [this PR](https://github.com/artefactual/archivematica-docs/pull/233#issuecomment-445949537) as an example.

@sallain and I believe this has to do with some translation hooks, because it's getting caught on something that no longer exists in the primary docs.

The error says "/home/travis/build/artefactual/archivematica-docs/admin-manual/installation-setup/installation/installation.rst:31:undefined label: multiple-machines (if the link has no caption the label must precede a section header)"

I get this error locally but it does not prevent things from building. Here it is, a little fuller:

```
/home/ashley/Development/archivematica-docs/admin-manual/installation-setup/installation/installation.rst:31: WARNING: undefined label: multiple-machines (if the link has no caption the label must precede a section header)
/home/ashley/Development/archivematica-docs/index.rst:207: WARNING: undefined label: fpr (if the link has no caption the label must precede a section header)
/home/ashley/Development/archivematica-docs/index.rst:209: WARNING: undefined label: fpr-instruct (if the link has no caption the label must precede a section header)
/home/ashley/Development/archivematica-docs/user-manual/administer/dashboard-admin.rst:289: WARNING: undefined label: digitized (if the link has no caption the label must precede a section header)
/home/ashley/Development/archivematica-docs/user-manual/ingest/ingest.rst:395: WARNING: undefined label: digitized (if the link has no caption the label must precede a section header)
```

**Steps to reproduce**

Make a pull request to https://github.com/artefactual/archivematica-docs and wait for Travis to build and subsequently, probably, fail.

**Your environment (version of Archivematica, OS version, etc)**

Travis @ https://github.com/artefactual/archivematica-docs

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by sallain** [comment]
I think this is fixed per artefactual/archivematica-docs#235!
