### ISSUE TITLE
Installation instructions point to an Elasticsearch GPG key that 404s

### ISSUE THREAD

**Issue by alexwlchan** [archivematica/Issues#376]
I'm reading the Installation page of the Archivematica docs, version 1.8.

URL: <https://www.archivematica.org/en/docs/archivematica-1.8/admin-manual/installation/installation/>.  
Retrieved 11 December 2018.

In the section "New Installation", step 2 is:

> Add Elasticsearch package source (optional)
> Skip this step if you are planning to run Archivematica in headless mode (without Elasticsearch).
>
> Elasticsearch comes from its own package repository.
>
> ```
> sudo wget -O - http://jenkins-ci.archivematica.org/GPG-KEY-elasticsearch | sudo apt-key add -
> sudo sh -c 'echo "deb http://packages.elasticsearch.org/elasticsearch/1.7/debian stable main" >> /etc/apt/sources.list'
> ```

But if I try to run this code in Ubuntu 16.04, I get an error:

```
--2018-12-11 10:39:27--  http://jenkins-ci.archivematica.org/GPG-KEY-elasticsearch
Resolving jenkins-ci.archivematica.org (jenkins-ci.archivematica.org)... 158.69.84.7
Connecting to jenkins-ci.archivematica.org (jenkins-ci.archivematica.org)|158.69.84.7|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2018-12-11 10:39:27 ERROR 404: Not Found.

gpg: no valid OpenPGP data found.
```

And if I open http://jenkins-ci.archivematica.org/GPG-KEY-elasticsearch in a browser, I get a 404 error.

The key should be put back, or the instructions should be updated with a link to a new key.

**Comment by sallain** [comment]
Hi there - thanks for this report. That page is actually outdated and should have been deleted - I'm not sure why it's hanging around! I think that the page you are looking for is here: https://www.archivematica.org/en/docs/archivematica-1.8/admin-manual/installation-setup/installation/install-ubuntu/

The table in the overview section on [this page](https://www.archivematica.org/en/docs/archivematica-1.8/admin-manual/installation-setup/installation/installation/#overview) will link you to the correct installation instructions for all of the various deployment methods/environments.

**Comment by sevein** [comment]
@alexwlchan, the page that you reported returns now a 404. There is something going on with the cache eviction system, I'll try to take a look!
