### ISSUE TITLE
Problem: There isn't a singular approach to setting the Archivematica version number

### ISSUE THREAD

**Issue by ross-spencer** [archivematica/Issues#383]
**Please describe the problem you'd like to be solved.**

Moving here, from https://github.com/artefactual/archivematica/issues/658

From @sevein:

> When we make releases we need to change:
> 
> * The version number constant (e.g. #656 and #657)
> * The agent version number (e.g. https://github.com/artefactual/archivematica/issues/793) (uses Agents model) - we should stop doing this!
> * Possibly more places.
>  
> The impact has been observed, for example, where the migration hasn't been written to upgrade agent-version moving from `1.7` to `1.8`. 
> 

There is additional discussion in this comment here: https://github.com/archivematica/Issues/issues/353#issuecomment-446587449

**Describe the solution you'd like to see implemented.**

It is unclear what the best approach is.

There is a way to do this which might satisfy developer needs, but not necessarily release/user needs: https://github.com/artefactual/archivematica/issues/1192 

archivematica#1192 would have the impact of introducing another line of instruction to the user [upgrade instructions](https://www.archivematica.org/en/docs/archivematica-1.8/admin-manual/installation/installation/#upgrade). If it is missed, it is not something we can verify easily, or use to determine precisely which version of Archivematica a user will be on. This does potentially undermine what we require from the AIP when we look at this information as well. This also has a real-world impact when migrating AIPs.

A migration however, e.g. [`1.7` to `1.8`](https://github.com/artefactual/archivematica/commit/3177e181a9a8354026242ba31434badeba9613f4) is guaranteed to run on upgrade, or on install, which means it is the most reliable way to make sure an Archivematica instance reports its version number correctly, but of course, can be missed, as shown above as well. 

The version number for the Storage Service is updated in one place: [storage_service/storage_service/__init__.py](https://github.com/artefactual/archivematica-storage-service/commit/8d38fbe71da9757270333966f3a830aa632cffe5) but to use this approach in Archivematica would then require some additional logic to be developed to access this value and output it correctly. 

What other approaches are out there for an application like Archivematica? 

**Related issues**

* https://github.com/artefactual/archivematica/issues/658
* https://github.com/artefactual/archivematica/issues/1183
* https://github.com/artefactual/archivematica/issues/1192
* https://github.com/archivematica/Issues/issues/353

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by cole** [comment]
To me, the best way to handle this is to use a constant. I don't think there's any reason to store it in the database, as that just makes less reliable and harder to update. The agent version should also be pulled from the constant (if it's not already).

We may want to change the constant to a string, and have the qa branch use something like `1.10-alpha` or `1.10-qa`, which would be changed to `1.10` when cutting the release. With scripts and plugins it's possible to get way more complicated than that, with formats like `1.10-qa-r<number of commits>-<git commit hash>` so you get something like `1.10-qa-r6-ad42cd30` but I'm not sure that's necessary here.

**Comment by ross-spencer** [comment]
NB. via the storage service, we have a single version constant [there](https://github.com/artefactual/archivematica-storage-service/blob/946a513da208f96c87b00f0ae86ad011d7e9baac/storage_service/storage_service/__init__.py).

**Comment by sromkey** [comment]
@sevein could you size this and give your opinion on relative priority?

**Comment by sevein** [comment]
This can probably get done in a day or two. Low priority, but having to create a migration on every release is definitely cumbersome. Releases would be a little easier and faster to prepare if we fixed this. The tricky part I find is to update the code that generates the METS document and find other places other than create_mets where we may be looking up agents. Perhaps the Django way to solve this would be to have a custom Agent manager that knows how to include the "preservation system" agent when we look it up.

**Comment by sevein** [comment]
> To me, the best way to handle this is to use a constant. I don't think there's any reason to store it in the database, as that just makes less reliable and harder to update. The agent version should also be pulled from the constant (if it's not already).

Additionally, I think it would be interesting to consider populating that constant from the build system. I've seem some projects doing this, e.g. pytest. They use [setuptools_scm](https://github.com/pypa/setuptools_scm) but assumes that our starting point is a wheel and that's far from where we are right now. Perhaps something to consider as part of https://github.com/archivematica/Issues/issues/392.
