### ISSUE TITLE
Problem: Archivematica version has not been updated to 1.9.0 yet

### ISSUE THREAD

**Issue by sevein** [archivematica/Issues#385]
SS's version also needs to be updated.

**Comment by sevein** [comment]
For QA, confirm version displayed in the version page of the admin area, e.g.:

![image](https://user-images.githubusercontent.com/606459/50314962-ba944d00-0465-11e9-9396-741e3b246f2f.png)

**Comment by kellyannewithane** [comment]
easiest.test.ever.
