### ISSUE TITLE
Problem: Storage service Dataverse space is marked as Beta

### ISSUE THREAD

**Issue by ross-spencer** [archivematica/Issues#388]
**Expected behaviour**

When I configure a space in the storage service for Dataverse the feature should not be marked as a Beta.

**Current behaviour**

As per the screenshot below, the `qa/0.x` interface still marks it as a Beta. 

![image](https://user-images.githubusercontent.com/1880412/50091924-fc768680-020c-11e9-973f-d65c2f38f99e.png)

**Steps to reproduce**

Access  the storage service and attempt to configure a new Dataverse space.

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by ross-spencer** [comment]
Marking as `Severity: High` for consideration in Archivematica's `1.9` release as it is too late to consider a fix for the `1.8.1` release.

**Comment by kellyannewithane** [comment]
Interface no longer marked as beta!
