### ISSUE TITLE
Problem: Archivematica  Dashboard refers to previously removed StorageServiceError exception

### ISSUE THREAD

**Issue by ross-spencer** [archivematica/Issues#390]
**Expected behaviour**

When it is triggered, a StorageServiceException should be caught and handled by the Archivematica dashboard.

**Current behaviour**

The module returns `AttributeError: 'module' object has no attribute 'StorageServiceError'`:

```
archivematica-dashboard_1_a00bb1a4162c | ERROR     2018-12-17 17:53:11  django.request:base:handle_uncaught_exception:256:  Internal Server Error: /api/transfer/start_transfer/
archivematica-dashboard_1_a00bb1a4162c | Traceback (most recent call last):
archivematica-dashboard_1_a00bb1a4162c |   File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
archivematica-dashboard_1_a00bb1a4162c |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
archivematica-dashboard_1_a00bb1a4162c |   File "/src/dashboard/src/components/api/views.py", line 81, in wrapper
archivematica-dashboard_1_a00bb1a4162c |     result = func(request, *args, **kwargs)
archivematica-dashboard_1_a00bb1a4162c |   File "/src/dashboard/src/components/api/views.py", line 306, in start_transfer_api
archivematica-dashboard_1_a00bb1a4162c |     response = filesystem_ajax_views.start_transfer(transfer_name, transfer_type, accession, access_id, paths, row_ids)
archivematica-dashboard_1_a00bb1a4162c |   File "/src/dashboard/src/components/filesystem_ajax/views.py", line 260, in start_transfer
archivematica-dashboard_1_a00bb1a4162c |     raise storage_service.StorageServiceError('Error copying {} to start of transfer.'.format(filepath))
archivematica-dashboard_1_a00bb1a4162c | AttributeError: 'module' object has no attribute 'StorageServiceError'
```

It seems that the exception was removed in this commit: https://github.com/artefactual/archivematica/commit/6163c07cfc3f1f6f189c6d806ce0ee8673e882dc

**Steps to reproduce**

I cannot reproduce this reliably at the moment. I am currently seeing the issue when trying to start a standard transfer via the API. The exception is referenced here:

* https://github.com/artefactual/archivematica/blob/707e9332f0bebf4c32def012e30752314a207d48/src/dashboard/src/components/filesystem_ajax/views.py#L258-L260

And that was previously in the storage service module here:

* https://github.com/artefactual/archivematica/blob/56b3c2c46edaa7aea0b252e3da648f959a77af41/src/archivematicaCommon/lib/storageService.py

**Your environment (version of Archivematica, OS version, etc)**

Archivematica `stable/1.8.x` in the Docker-compose environment.  

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by sevein** [comment]
Fixed in https://github.com/artefactual/archivematica/commit/8484d58fe3d157d8f7a865d586dd641f5a1641ad.
