### ISSUE TITLE
Problem: backlog content doesn't persist beyond its current pipeline

### ISSUE THREAD

**Issue by peterVG** [archivematica/Issues#391]
**Expected behaviour**
Backlogs can be used for long-term storage of content and users can expect it to be as durable as AIP storage for maintaining accurate metadata over pipeline upgrades, migrations or re-indexes.

**Current behaviour**
Currently, transfers stored using Archivematica’s backlog functionality can only be accessed by using the same pipeline that the transfer was created in. If you decommission or lose your pipeline, you will be unable to reindex and repopulate the backlogged material in a new Archivematica pipeline. The reliance on maintaining this information in a transactional database and search index is a significant preservation risk if the files are kept in backlog for an indefinitely long period of time, as is the case for an increasing number of Archivematica users.

![screen shot 2019-01-18 at 11 51 05](https://user-images.githubusercontent.com/672121/51409961-1bbc4880-1b18-11e9-8bad-5e4c4cfebf23.png)

Instead, files sent to backlog are stored as self-describing Bagit packages just like Archivematica AIPs. The METS file in these packages will contain all the information required by Archivematica to restore from backlog and begin appraisal microservices, whether its using the same pipeline or a new one installed at a future date. This significantly improves the robustness and preservation of files sent to backlog for an indefinite period of time as they are no longer critically dependent on the database and search index of a specific pipeline.

![screen shot 2019-01-18 at 11 51 25](https://user-images.githubusercontent.com/672121/51409993-2e368200-1b18-11e9-9ec7-1f5fb1a271b6.png)

Development Tasks:

- Parent of #444 "Send to backlog" does not create Bagit packages
- Parent of #446 cannot restore transfer Bagit packages from Transfer Storage location
- Parent of #508 Pipeline cannot read transfer packages from new "Transfer Storage" location 
- Parent of  #442  it's unclear whether Transfer METS file has all the information required for a compliant AIP

**Your environment (version of Archivematica, OS version, etc)**

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by sallain** [comment]
Test plan:
- If #446 can be closed, then this issue can be closed.
