### ISSUE TITLE
Problem: ansible update is not described in docs

### ISSUE THREAD

**Issue by scollazo** [archivematica/Issues#396]
**Version of the documentation**
1.8

**Page (and section, if applicable) where the issue occurs**

admin-manual/installation-setup/upgrading/upgrading.rst

**Description of the issue**

The instructions only take into account the upgrade for debian/centos packages, upgrades using ansible are not described.

**Suggested fix**
Add procedure for upgrades using ansible

**Comment by sevein** [comment]
There is a new `Upgrade on Vagrant / Ansible` section in https://www.archivematica.org/en/docs/archivematica-1.9/admin-manual/installation-setup/upgrading/upgrading/.
