### ISSUE TITLE
Problem: can't connect to ArchivesSpace with non-standard connection details

### ISSUE THREAD

**Issue by sevein** [archivematica/Issues#409]
It's unclear how to (or impossible) set up the ArchiveSpace connection details in Archivematica when the former is not using a standard deployment configuration, e.g. deployed behind a https load balancer or served from a subpath in a shared domain.

Our ArchivesSpace configuration form asks the user for `host` and `port`, see:

![image](https://user-images.githubusercontent.com/606459/50709884-26f27d00-101e-11e9-8e67-002b54f78a16.png)

These values are used in two different forms:

#### In `post_store_aip_hook.py`

URL is built simply concatenating host and port:

    'http://' + config['host'] + ':' + str(config['port']) + '/<app_endpoint>'

#### Via agentarchives' `ArchivesSpaceClient`

See related PR: https://github.com/artefactual-labs/agentarchives/pull/42.

`host` and `port` are processed as follows (simplified constructor):

    def __init__(self, host, port=8089):
        parsed = urlparse(host)
        if not parsed.scheme:
            host = 'http://' + host
        self.host = host + ':' + str(port)

Given the above, in particular `post_store_aip_hook.py`, the final set of possible valid combinations is too restrictive.

This is true in AM v1.8.x and older.

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by sevein** [comment]
I think that we should just stop using `port` and reinterpret `host` as it was `base_url`, i.e. a qualified URL which could potentially hold all URL parts.

Existing Archivematica installations can be updated with a migration that makes the best effort to parse the previous `host` and `port` to build a new `base_url` from it.

**Comment by helrond** [comment]
FYI what @sevein describes above is how ArchiveSnake handles these configs: https://github.com/archivesspace-labs/ArchivesSnake

**Comment by ablwr** [comment]
I think testing this is blocked by https://github.com/archivematica/Issues/issues/483, but potentially blocked by our testing services not being whitelisted by our ASpace test server.

**Comment by sallain** [comment]
To do:
* @scollazo  to test  upgrading a 1.8 site that has ArchivesSpace credentials. The credentials should carry over to the new form (or we should provide instructions for fixing them)

**Comment by scollazo** [comment]
Tested upgrading from a 1.8 site with ArchivesSpace already configured, and everything worked as expected, I was able to search ASpace in the backlog, and also able to upload DIPs to it.
