### ISSUE TITLE
Problem: archivematica xenial vagrantfile is broken

### ISSUE THREAD

**Issue by scollazo** [archivematica/Issues#415]
**Expected behaviour**
Running "vagrant up" in deploy-pub/playbooks/archivematica-xenial/ gives you an usable system

This has an impact on our CI process: http://jenkins-ci.archivematica.org/job/deploy-pub/job/Stable/job/Ubuntu-16.04-Stable/

**Current behaviour**
Vagrant provision fails to complete, due to the repositories not being populated before python is installed

**Steps to reproduce**
Run "vagrant up" on deploy-pub/playbooks/archivematica-xenial/

**Your environment (version of Archivematica, OS version, etc)**
artefactual/deploy-pub@e3d0930e1484213bf4ea3ab9ded

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by mamedin** [comment]
Verified, I deployed sucessfully AM1.8 and AM1.9 on xenial (vagrant ).
