### ISSUE TITLE
Problem: DSpace workflow differs from Standard when automating 'send to quarantine'

### ISSUE THREAD

**Issue by ross-spencer** [archivematica/Issues#426]
**Expected behaviour**

When the processing configuration is automated for standard transfer, it should still be automated when running a DSpace transfer. 

**Current behaviour**

When using an automated processing configuration the decision point `Job Workflow decision - send transfer to quarantine [?]` still comes up. 

**Steps to reproduce**

Setup an automated processing configuration, and perform a standard transfer, a good one to choose in sample-data is `Demo Transfer`. The transfer will complete with full automation.

Select a DSpace transfer and select the sample DSpace transfer from the sample-data. The transfer will pause at the aforementioned decision point. 

In the following screenshot you can see the different transfer types being set, and the decision point either appearing or not appearing. 

![image](https://user-images.githubusercontent.com/1880412/51031186-0dac7c00-159c-11e9-849b-aaf7b0485405.png)

**Your environment (version of Archivematica, OS version, etc)**

Archivematica 1.8.0.

**Related issues**

Related to https://github.com/archivematica/Issues/issues/45 

**Workaround**

I didn't realize this, but I think it is possible to modify this section of the processing configuration to skip the decision point in a dspace transfer as we do in a standard transfer. The user could then use a custom processing configuration. I need to double check the right uuids for this. Perhaps @luisilara can confirm this workaround for current clients? 

```
    <!-- Send transfer to quarantine -->
    <preconfiguredChoice>
      <appliesTo>755b4177-c587-41a7-8c52-015277568302</appliesTo>
      <goToChain>d4404ab1-dc7f-4e9e-b1f8-aa861e766b8e</goToChain>
    </preconfiguredChoice>
```

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by sromkey** [comment]
An oldie and not such a goodie! https://projects.artefactual.com/issues/6599 
I think it's never been prioritized because most users have DSpace transfers running through automation tools and they avoid this problem.

**Comment by ross-spencer** [comment]
Nice @sromkey! Thank you! So with the work-around documented there, and this ticket too, following @sevein's line of thinking yesterday, Can we close the Redmine ticket? One down, a few more to go :)

**Comment by sromkey** [comment]
Ya I'll do it!

**Comment by sevein** [comment]
Related: https://github.com/artefactual/archivematica/issues/598.

**Comment by ablwr** [comment]
Just noting this is still an issue in 1.10x RC. But I believe there are plans for quarantine and it'll be resolved in due time.

**Comment by sromkey** [comment]
Since we plan to remove quarantine in 1.11, I am moving this to review and adding the milestone. In QA, we should ensure that DSpace workflow works as expected when automated, e.g. does not stop anywhere.

**Comment by ablwr** [comment]
I tested this and noted it on https://github.com/artefactual/archivematica/issues/598 -- not closing that one quite yet but I think this one is fine to close.
