### ISSUE TITLE
Problem: Temporary directories (and the files inside) are not deleted when AIPs are downloaded from a remote server, e.g. S3

### ISSUE THREAD

**Issue by ross-spencer** [archivematica/Issues#431]
**Expected behaviour**

When a package is downloaded from a remote service, e.g. Amazon S3, all temporary artifacts are deleted afterwards.

**Current behaviour**

Temporary directories created during move_to_storage_service(...) are not deleted. The behavior is described here: https://groups.google.com/d/msg/archivematica/GLZmbhs5XRk/rX3N7Ti9DwAJ 

**Your environment (version of Archivematica, OS version, etc)**

Docker-compose, running Archivematica `1.8` and storage service `0.13`. 

**Additional context**

Santi posted a workaround in a related issue:

This line can be addedd to the crontab to delete folders older than 30 minutes: 
```
*/5 * * * *       archivematica   find /var/archivematica/storage_service/ -maxdepth 1 -iname 'tmp*' -mmin +30 -type d -exec rm -rf {} \;
```

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by sromkey** [comment]
Related to #359 ?

**Comment by ross-spencer** [comment]
Tangentially related: https://github.com/archivematica/Issues/issues/1343

**Comment by tw4l** [comment]
To test:

1. Ingest some packages
2. Check number of files in Storage Service internal tempdir: `find /var/archivematica/storage_service -type f | wc -l`
3. Download, reingest, and check fixity of packages via Storage Service GUI and/or API
4. Verify that number of files in Storage Service internal tempdir hasn't changed

**Comment by replaceafill** [comment]
I just confirmed [Tessa's fix](https://github.com/artefactual/archivematica-storage-service/commit/d1dcd47f27a30794a4d482e77f247bb49c11dba1) removes the temporary directory created when the AIP is downloaded in the Storage Service UI or when the `check_fixity` endpoint is called.

Using [the commit previous to Tessa's fix](https://github.com/artefactual/archivematica-storage-service/commit/fc2eabf62192e501e7a18531ceef408869ece925) I was able to reproduce the issue and see the temporary directory left behind (`tmpJ4HGIk` here):

```
root@255ba98aefbb:/src/storage_service# tree /var/archivematica/storage_service/
/var/archivematica/storage_service/
├── c31c
│   └── 6ea5
│       └── bf1c
│           └── 4aa0
│               └── bfe8
│                   └── 717a
│                       └── ce0d
│                           └── 4e7f
│                               └── pointer.c31c6ea5-bf1c-4aa0-bfe8-717ace0d4e7f.xml
├── recover
│   └── backup
├── tmpJ4HGIk
│   └── c31c
│       └── 6ea5
│           └── bf1c
│               └── 4aa0
│                   └── bfe8
│                       └── 717a
│                           └── ce0d
│                               └── 4e7f
│                                   └── somename-c31c6ea5-bf1c-4aa0-bfe8-717ace0d4e7f.7z
└── var
    └── archivematica
        └── sharedDirectory
            └── tmp
                └── tmpZGlSW1
```

And after checking out Tessa's fix, the temporary directory is still created but deleted after each operation.

**Comment by replaceafill** [comment]
I just confirmed this again when I downloaded a package in the Storage Service stored in Duracloud. The Storage Service logs show:

```
DEBUG     2021-06-30 07:58:47  locations.models.package:package:clear_local_tempdirs:384:  Deleted Storage Service internal tempdir: /var/archivematica/storage_service/tmpyx8hqmxz
```
