### ISSUE TITLE
REQUESTS_CA_BUNDLE setting is incorrect in Red Hat/CentOS packages and also in the documentation.

### ISSUE THREAD

**Issue by R-Khera** [archivematica/Issues#432]
**Expected behaviour**
When using internally signed certificates for the Storage Service, Archivematica should be able to connect via HTTPS after I follow the steps on https://www.archivematica.org/en/docs/archivematica-1.8/admin-manual/security/security/.

**Current behaviour**
I get "certificate verify" error after setting the Storage Service options to use HTTPS.

**Steps to reproduce**
1. Create a internally (or self-) signed cert for your Storage Service.
1. Follow the instructions here: https://www.archivematica.org/en/docs/archivematica-1.8/admin-manual/security/security/#use-the-environment-string-request-ca-bundle
1. Go to admin > general on the Archivematica instance and config the Storage Service options to use HTTPS.

**Your environment (version of Archivematica, OS version, etc)**
Red Hat 7.6
Archivematica 1.8.1
Storage Server 0.13.0

**Fix**
The setting in the /etc/sysconfig/archivematica* config files is incorrect. It should be REQUESTS_CA_BUNDLE not REQUEST_CA_BUNDLE.

This typo is also in the documentation: https://www.archivematica.org/en/docs/archivematica-1.8/admin-manual/security/security/.

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by mamedin** [comment]
Thanks @XincUK.

You're right, it should be `REQUESTS_CA_BUNDLE`  instead of `REQUEST_CA_BUNDLE`

The typo is present in:

* [packages](https://github.com/artefactual-labs/am-packbuild) 
* [archivematica-docs](https://github.com/artefactual/archivematica-docs) 
* [ansible-archivematica-src](https://github.com/artefactual-labs/ansible-archivematica-src) role.
