### ISSUE TITLE
Not possible to designate destination ArchivesSpace repository using DSpace REST location

### ISSUE THREAD

**Issue by J4bbi** [archivematica/Issues#435]
**Please describe the problem you'd like to be solved.**
The DSpace REST location optionally allows creating a link to the deposited DIP in ArchivesSpace.

The id of the parent archival object in ArchivesSpace can be passed in the submitted metadata. 

However the ArchivesSpace repository currently has to be defined in the location config in SS and depositing to more than one repository would require a corresponding number of locations set up in SS with identical parameters aside from the repository id.

**Describe the solution you'd like to see implemented.**
Enable repository id to be passed in the metadata in the same way as DSpace collection ids and ArchivesSpace archival object is.

**Describe alternatives you've considered.**

**Additional context**
As I developed the DSpace REST functionality with the good help of an Artefactual developer I can submit a PR with this simple feature added.

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by sromkey** [comment]
HI @J4bbi , sounds great, thanks for the suggestion and the offer of a PR. We're close to code freeze for 1. but we could definitely consider something for 1.10- I'll label this appropriately. Thanks again!

**Comment by sallain** [comment]
@j4bbi this is now available in the 1.10 release candidate if you would like to test!
