### ISSUE TITLE
Problem: cannot restore transfer Bagit packages to start appraisal

### ISSUE THREAD

**Issue by peterVG** [archivematica/Issues#446]
As per issue #391, backlog transfers will be stored in a Transfer Storage location in the Storage Service. 

There is an existing CLI command to make backlog packages available to the pipeline from the backlog location: https://github.com/artefactual/archivematica/blob/stable/1.8.x/src/dashboard/src/main/management/commands/rebuild_transfer_backlog.py

With the new "transfer storage" implementation we need a new or upgraded command to restore transfer packages so that they are available to Backlog, Appraisal, and Ingest SIP creation features in the pipeline.

- [ ] Open Bagit package and move files to Appraisal working directory (/originals folder)
- [ ] Update ES index (for packages being restored from Transfer Storage)
- [ ] Insert data into MCP database

**Your environment (version of Archivematica, OS version, etc)**

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by sromkey** [comment]
Would this be a reasonable test plan for this issue:

- populate a backlog with packages
- delete the pipeline (maybe not necessary?)
- install a new pipeline and index the backlog from previously created transfers
- ensure transfers can be arranged into SIPs.

pinging @peterVG and @scollazo to give feedback on that

**Comment by sallain** [comment]
Above testing plan is correct - @scollazo, assigning to you!
