### ISSUE TITLE
Problem: Automation tools is now saving the absolute path to its database not the transfer name

### ISSUE THREAD

**Issue by ross-spencer** [archivematica/Issues#447]
**Expected behaviour**

Automation tools are able to understand the transfers that they have processed using transfer names. 

**Current behaviour**

The previous commit to the automation-tools: 

Writes the absolute path to the database once a transfer has been initiated but the automation tools doesn't have the absolute path to work with when it is looking for new transfers. The API signature for browsing a location looks as follows: 

![image](https://user-images.githubusercontent.com/1880412/51441637-cf1d6c80-1cd3-11e9-8fcc-e97f3c0ad3b4.png)

The paths described here are relative to a location:

e.g.

```
HTTP/1.1 200 OK
Cache-Control: no-cache
Connection: keep-alive
Content-Language: en
Content-Type: application/json
Date: Sun, 20 Jan 2019 15:56:53 GMT
Server: nginx/1.14.2
Transfer-Encoding: chunked
Vary: Accept, Accept-Language, Cookie
X-Frame-Options: SAMEORIGIN

{
    "directories": [
        "auto_1"
    ],
    "entries": [
        "auto_1"
    ],
    "properties": {
        "auto_1": {
            "object count": 3,
            "size": 4096
        }
    }
}
```

Where the full path for the one directory here would be: `/home/archivematica/archivematica-sampledata/automation/auto_1`

Further, once the transfer has begun processing the absolute path is relative to the processing directory, not the storage space. 

The automation tools would not find a previous matching transfer if it compared `auto_1` to `/var/archivematica/sharedDirectory/watchedDirectories/activeTransfers/standardTransfer/auto_1/` which might be returned from the start transfer endpoint (the automation tools calls endpoints in order (abbreviated) `ss:location/browser` -> `am:transfer/unapproved` -> `am:transfer/start_transfer` -> `am:transfer/approve_transfer`). 

**Your environment (version of Archivematica, OS version, etc)**

AM Tools: https://github.com/artefactual/automation-tools/tree/6d76af2ff2ada9585c00a7aef9fd58345b034e35

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by ross-spencer** [comment]
@luisilara rather than me verifying this, would you say this is working okay for Unimelb? If so, can you add the `Status: Verified` tag?

**Comment by luisilara** [comment]
@ross-spencer I see that the automation tools writes the transfer name to the database once a transfer has been initiated, great work!
