### ISSUE TITLE
Problem: bagit created by Storage Service after reingest may have outdated tag manifest files

### ISSUE THREAD

**Issue by sevein** [archivematica/Issues#449]
**Expected behaviour**
SS shouldn't create invalid bags.

**Current behaviour**
After full reingest, Storage Service [executes a number of steps](https://github.com/artefactual/archivematica-storage-service/blob/8863492193a8f07e89fa6f1a27ad9889be4de822/storage_service/locations/models/package.py#L1977-L2020) in order to replace the original AIP with the new re-ingested AIP. In particular, as the payload of the bag has changed, SS uses [python-bag](http://libraryofcongress.github.io/bagit-python/) to regenerate the manifests. When the original package is a BagIt v0.96, the library does not update optional tag manifests.

This is a problem when the package is transferred to the pipeline again because during the validation process we're using the Java version which verifies optional tag manifests. `tagmanifest-md5.txt` wasn't updated so the verification process fails and the transfer is rejected.

A potential solution is to update the BagIt package to v0.97.

**Steps to reproduce**
1. Import really old Archivematica AIP (pre AM v1.x, see more in [#24](https://github.com/archivematica/Issues/issues/24))
2. Confirm that it uses BagIt v0.96
3. Full re-ingest
4. Download new re-ingested AIP and verify the tag manifest files.

**Your environment (version of Archivematica, OS version, etc)**
Tested using: bagit-python v1.5.4 and v1.7.0
AM qa/1.x 6de2fc11d11c2013a11b9a6864d9f23dc89f3681

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by sevein** [comment]
This has been fixed in #24.

**Comment by evelynPM** [comment]
Tested by re-ingesting an AIP from 2012, then downloaded the re-ingested AIP and used bagger to verify. I also visually inspected the manifest-sha256 file. All looks good.
