### ISSUE TITLE
Problem: Navigating away from 'Archival storage' tab after searching and then returning to tab results in ES error 

### ISSUE THREAD

**Issue by currmie** [archivematica/Issues#452]
**Expected behaviour**
After performing a search in the Archival storage tab, search results should display, and navigating away from the tab should NOT return an ES error.

**Current behaviour**
After navigating away from the Archival storage tab, an ES error is returned.

**Steps to reproduce**
1. In **Archival storage** tab, place cursor in Search field and either leave blank or enter something.
2. Then click **Search archival storage**.
3. Navigate away from the tab and then randomly click on Transfer tab.
4. Navigate back to **Archival Storage** tab .
    You should see an ES error, screenshot attached.

![screen shot 2019-01-24 at 3 02 59 pm](https://user-images.githubusercontent.com/35077919/51714630-b7ebc100-1fea-11e9-9c7a-9943a5548faf.png)

**Your environment (version of Archivematica, OS version, etc)**
ES test server: http://51.68.145.199
Version I think is an early 1.9 with some ES updates merged.

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by jraddaoui** [comment]
The fix has been merged in qa/1.x. Assigning to @scollazo for deploy.

**Comment by jraddaoui** [comment]
Hi @currmie and @sromkey, this should be fixed in the test server now.
