### ISSUE TITLE
Problem: Setting up the Elasticsearch 6.x.x docker image requires vm.max_map_count=262144 to be set by the user

### ISSUE THREAD

**Issue by ross-spencer** [archivematica/Issues#453]
**Expected behaviour**

Users should have available all the settings required to run Elasticsearch (ES) 6.x.x in the docker development environment from Archivematica `1.9` onwards. 

**Current behaviour**

Users attempting to run Archivematica `1.9` for the first time, or the `qa` branch at time of writing, containing the new ES feature may see logging in the docker environment along these lines:

```
ross-spencer@artefactual:~/git/artefactual-labs/am/compose$ sudo docker-compose logs -f elasticsearch | ack -A 4 -B 4 vm
elasticsearch_1                  | [2019-01-25T16:36:43,535][INFO ][o.e.n.Node               ] [am-node] starting ...
elasticsearch_1                  | [2019-01-25T16:36:43,671][INFO ][o.e.t.TransportService   ] [am-node] publish_address {172.18.0.7:9300}, bound_addresses {0.0.0.0:9300}
elasticsearch_1                  | [2019-01-25T16:36:43,681][INFO ][o.e.b.BootstrapChecks    ] [am-node] bound or publishing to a non-loopback address, enforcing bootstrap checks
elasticsearch_1                  | ERROR: [1] bootstrap checks failed
elasticsearch_1                  | [1]: max virtual memory areas vm.max_map_count [65530] is too low, increase to at least [262144]
elasticsearch_1                  | [2019-01-25T16:36:43,688][INFO ][o.e.n.Node               ] [am-node] stopping ...
elasticsearch_1                  | [2019-01-25T16:36:43,720][INFO ][o.e.n.Node               ] [am-node] stopped
elasticsearch_1                  | [2019-01-25T16:36:43,720][INFO ][o.e.n.Node               ] [am-node] closing ...
elasticsearch_1                  | [2019-01-25T16:36:43,730][INFO ][o.e.n.Node               ] [am-node] closed
```

This is related to a setting that must be set in your own environment (not Docker) and can be configured as follows via @jraddaoui:

* Temporarily: `sudo sysctl -w vm.max_map_count=262144`
* Permanently you can add it in: `/etc/sysctl.conf` by adding: `vm.max_map_count=262144` at the of the file

There is a similar ticket in the AtoM repository where this information can sit. We can adopt the same pattern for the `am.git` repository.

* Ref: https://github.com/artefactual/atom-docs/issues/54

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by ross-spencer** [comment]
Hi @sromkey this will be needed for devs to setup their environment from `1.9` on, so requesting a milestone if possible. Thanks.

**Comment by ablwr** [comment]
I inadvertently tested this one.
