### ISSUE TITLE
DSpace REST location does not fall back to default values

### ISSUE THREAD

**Issue by J4bbi** [archivematica/Issues#458]
**Expected behaviour**
When setting up a DSpace REST location it is mandatory to define two default variables:

Default DSpace DIP collection id
Default DSpace AIP collection id

these are the collection UUIDs in which the transfer record will get created if these variables are not defined in a supplied metadata file with the transfer.

In addition to the DSpace collection ids it is also possible to optionally create a digital object in ArchivesSpace. In order to do that two variables are required, the repository id and the archival object id.

When a transfer is processed the default values set up for the space should be used if they're not defined in the metadata file.

**Current behaviour**
It is not possible to pass the repository id in the metadata file (#435) and this PR artefactual/archivematica-storage-service#436 adds that functionality.

When testing that new functionality it became apparent that the original code does not work as intended:

When extracting the metadata from a file that does **not** contain any of the variables (see https://github.com/artefactual/archivematica-storage-service/blob/8863492193a8f07e89fa6f1a27ad9889be4de822/storage_service/locations/models/dspace_rest.py#L196-L202) a dict with the corresponding key would get created with the value `None`

When assigning the values extracted the `dict.get(key[, default])` method is used which checks if the provided key exists and if it does not assigns a default value (https://github.com/artefactual/archivematica-storage-service/blob/8863492193a8f07e89fa6f1a27ad9889be4de822/storage_service/locations/models/dspace_rest.py#L328-L338), however, as explained in the earlier paragraph a value with the key gets assigned regardless.

Therefore the default values are never used.

**NOTE**
The PR artefactual/archivematica-storage-service#436 to add the same functionality for the ArchivesSpace repository id artefactual/archivematica-storage-service#436 fixes this issue by explicitly making sure that the value is not `None` (see https://github.com/artefactual/archivematica-storage-service/blob/cdeaaa9bad8897c94546b3a9e75ef5f4d9978e0e/storage_service/locations/models/dspace_rest.py#L198)

**Steps to reproduce**
Try a transfer using the DSpace REST location without providing any of the required variables.

**Your environment (version of Archivematica, OS version, etc)**

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by sallain** [comment]
@J4bbi This is merged into the 1.10 release candidate if you would like to test!
