### ISSUE TITLE
Problem: Automation-tools - Invalid transfer path for the pre-transfer scripts

### ISSUE THREAD

**Issue by luisilara** [archivematica/Issues#461]
**Expected behaviour**

To process transfers from Dspace the parameter `--files` is used with the `transfers.py` script in order to start transfers from files as well as folders

**Current behaviour**

By running the `transfers.py` script I get the error `Invalid transfer path for the pre-transfer scripts`
```
/usr/share/archivematica/virtualenvs/automation-tools/bin/python -m transfers.transfer --files --transfer-type dspace ...

...
INFO      2019-01-30 05:39:33 transfer.py:419  Attempting to run pre-transfer scripts on: 37076.zip
ERROR     2019-01-30 05:39:33 transfer.py:197  Invalid transfer path for the pre-transfer scripts to work with
INFO      2019-01-30 05:39:33 transfer.py:430  Ready to approve transfer
...

```

The script is looking for this transfer path `/var/archivematica/sharedDirectory/watchedDirectories/activeTransfers/Dspace/37076.zip` 

The path exists at the time of the script execution 

**Your environment (version of Archivematica, OS version, etc)**

AM 1.7.1
SS 0.11.1
Red Hat Enterprise  7.6 (Maipo)

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by ross-spencer** [comment]
Resolved via [#96](https://github.com/artefactual/automation-tools/pull/96).
