### ISSUE TITLE
rights.csv example is incomplete

### ISSUE THREAD

**Issue by goetzk** [archivematica/Issues#462]
**Version of the documentation**

at least 1.7 and 1.8

**Page (and section, if applicable) where the issue occurs**
https://www.archivematica.org/en/docs/archivematica-1.8/user-manual/transfer/import-metadata/#rights-csv

**Description of the issue**
Examples given are plain file names, but like metadata.csv rights.csv requires filenames be prefixed with objects/.

**Suggested fix**
prefix examples with objects/

**Comment by sallain** [comment]
Thanks for raising this, @goetzk!
