### ISSUE TITLE
Problem: Dashboard can't connect to MCPServer after a period of inactivity

### ISSUE THREAD

**Issue by sevein** [archivematica/Issues#464]
**Expected behaviour**
MCPServer should be able to function properly after long periods of inactivity.
RPCServer should call `django.db.close_old_connections` so Django has an opportunity to close unusable/obsolote connections.

**Current behaviour**
MCPServer stops working after long periods of inactivity. This seems to be happening because the new RPCServer introduced in #1251 fails to call `django.db.close_old_connections` when RPC handlers complete. This is causing Django's ORM to recycle the previous database connection which may have already been closed by MCPServer if `wait_timeout` was exceeded.

In the future, we may additionally want to call `close_old_connections` before the handler is executed. That would allow us to recycle connections when `CONN_MAX_AGE>0`, i.e. we're currently not recycling connections in RPCserver but we could try. For context, RPCServer runs on its own system thread - Django's connection management doesn't share and it's not pool! An alternative is to move to SQLAlchemy.

**Steps to reproduce**
1. Set a low value for `wait_timeout` in MySQL.
2. Start Archivematica.
3. Open the Dashboard, let it connect, close it.
4. Wait until `wait_timeout` is exceeded.
5. Open the Dashboard again - connection with MCP will fail.

It's also useful to monitor connections with `SHOW PROCESSLIST` in MySQL, an easy way to tell if MCPServer is leaving connections open.

**Your environment (version of Archivematica, OS version, etc)**
AM's qa/1.x 7935c4814b11dae3d346109fb36a9173b6b7a97f.

Related PRs:
- https://github.com/artefactual/archivematica/pull/505
- https://github.com/artefactual/archivematica/pull/1227

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by sallain** [comment]
@sevein what counts as a long period of inactivity?

**Comment by sevein** [comment]
In MySQL, the default value for `wait_timeout` is eight hours.
So you may want to leave the machine running and give it a try tomorrow.
I tested it using `SHOW PROCESSLIST` and the connections were being closed again.

**Comment by currmie** [comment]
Verified on local deploy. Dashboard connects to MCPServer after 12+ hours of inactivity
