### ISSUE TITLE
Problem: version number of storage service in qa branch is incorrect

### ISSUE THREAD

**Issue by jhsimpson** [archivematica/Issues#47]
**Please describe the problem you'd like to be solved.**
The version number in https://github.com/artefactual/archivematica-storage-service/blob/qa/0.x/storage_service/storage_service/__init__.py
says '0.11.0', which is behind the '0.11.1' version number in the stable/0.11.x branch

**Describe the solution you'd like to see implemented.**
The version number in qa should either say '0.12.0' (the expected next release) 
or something else that indicates this is a qa version.

**Comment by joel-simpson** [comment]
Tested in my local environment (qa/1.x using docker / am.git) and works as expected
![screenshot from 2018-07-31 19-01-20](https://user-images.githubusercontent.com/17187309/43491886-5d78f73c-94f4-11e8-9543-5450fa47de9d.png)
