### ISSUE TITLE
Stuck on Postfix Configuration during manual installation

### ISSUE THREAD

**Issue by nvanderperren** [archivematica/Issues#470]
**Expected behaviour**
Installation of Archivematica was succesfull

**Current behaviour**
stuck on postifx configuration. After `sudo apt-get install -y archivematica-mcp-client` I got a screen in terminal to select mail server configuration. It's not possible to click 'ok'. If I do enter, notting happens. I can use escape (esc) to go to the next screen where I get a list of mail configuration types. When I select a configuration and push enter, I go back to the first screen of mail configuration (screenshots). I have no idea how to skip or terminate this step.

![screenshot from 2019-02-04 12-18-09](https://user-images.githubusercontent.com/17183054/52207691-868eb300-287e-11e9-8101-359560b8ad7c.png)
![screenshot from 2019-02-04 13-12-20](https://user-images.githubusercontent.com/17183054/52207699-8bebfd80-287e-11e9-8a7c-1db51ff2a2ef.png)

**Steps to reproduce**
follow the manual installation of Archivematica on Ubuntu 16.04: https://www.archivematica.org/en/docs/archivematica-1.8/admin-manual/installation/install-ubuntu

**Your environment (version of Archivematica, OS version, etc)**
- Ubuntu 16.04 Desktop 64 bit
- Archivematica 1.8

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by nvanderperren** [comment]
It seemed to be a problem with Ubuntu, which is solved now by using the Ubutnu Software application. Everything is working fine now. Sorry for the issue :)

**Comment by sromkey** [comment]
No problem at all, thanks for reporting back @nvanderperren !

**Comment by karzmei** [comment]
In case anyone gets the same error in Ubuntu 20.04, what suddenly worked for me:
- in the first screen - click "Tab" so that you see the "ok" highlighted, and then click "Enter".
- then you get the second screen - choose "no configuration" and click "Enter".
Then go back to installing whatever you planned.

**Comment by nhandq110** [comment]
Thank you so much!

**Comment by nhandq110** [comment]
> In case anyone gets the same behaviour in Ubuntu 20.04, what suddenly worked for me:
> 
> * in the first screen - click "Tab" so that you see the "ok" highlighted, and then click "Enter".
> * then you get the second screen - choose "no configuration" and click "Enter".
>   Then go back to installing whatever you planned.

Thank you it helped me a lot
