### ISSUE TITLE
Problem: File list pane of the Appraisal tab always removes the last tag of a file

### ISSUE THREAD

**Issue by replaceafill** [archivematica/Issues#472]
**Expected behaviour**

When a file has multiple tags clicking the `-` icon next to a tag removes that specific tag only.

**Current behaviour**

When a file has multiple tags clicking the `-` icon of a tag always removes the last tag of the file instead.

I think the problem is [this line](https://github.com/artefactual/archivematica/blob/e240825332b76f3cc50b66646921fd9b1ab84d4b/src/dashboard/frontend/appraisal-tab/app/services/transfer.service.js#L174) in the Transfer service popping the last element from the record's tags.

**Steps to reproduce**

1. Send a transfer containing a few files to the backlog so you access it in the Appraisal tab.
2. Assign a few files multiple tags in the Backlog pane of the Appraisal tab and select those files so they appear in the File list pane.
3. Make the File list pane visible and try to remove the first tag of a file with multiple tags. The last tag should have been removed instead. 

**Your environment (version of Archivematica, OS version, etc)**

https://github.com/artefactual-labs/am/commit/e860b311cbea2cce95c05620109a763b3929642b

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by sallain** [comment]
Docs may need to be updated.
