### ISSUE TITLE
Problem: Upload DIP locks on "Choose config for AtoM/Binder DIP upload" job

### ISSUE THREAD

**Issue by peterVG** [archivematica/Issues#474]
**Expected behaviour**
Upload DIP to AtoM/Binder completes with successful upload of DIP files to AtoM.

**Current behaviour**
The "Upload DIP" job displays as completing successfully but the files are not uploaded to AtoM. The next job that displays is "Choose config for AtoM/Binder DIP upload" with an "Awaiting decisions" option, but which does not have any options to select. The workflow is effectively locked from this point.

![screen shot 2019-02-04 at 14 53 06](https://user-images.githubusercontent.com/672121/52242840-9e6d3380-288c-11e9-8b79-650fad045620.png)

**Steps to reproduce**
Upload a DIP to AtoM/Binder.

Possibly related to issue #55 

**Your environment (version of Archivematica, OS version, etc)**

http://am19bionic.qa.archivematica.org

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by sallain** [comment]
I was just checking the sequence of events for this issue and it might be helpful to note that there are two `Upload DIP` jobs - the first one is for the decision prompt, which succeeds; qa/1.x is never able to get to the second Upload DIP job, which is the one where the actual DIP upload takes place.

This is what a successful upload DIP workflow looks like on a 1.8 site:
![image](https://user-images.githubusercontent.com/4612276/52244412-5224f200-2892-11e9-8d88-c712fd9fa0a9.png)

The connection with AtoM looks like it's configured properly on the pipeline in question.

**Comment by peterVG** [comment]
Upload DIP to AtoM/Binder is working successfully again and the "choose config" option is not appearing.
