### ISSUE TITLE
Problem: Need an AMAUAT that tests generating and retrieving an AIP

### ISSUE THREAD

**Issue by sromkey** [archivematica/Issues#479]
**Please describe the problem you'd like to be solved.**
In the Archivematica Automated User Acceptance Tests, we do not have a test to generate an AIP and retrieve it. Having this test would ease manual regression testing.

**Additional context**
A feature file for this test is contained in this document:
https://docs.google.com/document/d/1q_kHi9JePVN8Kvay61WZAyIssPoH2ZJZEWqB-wtqEDc/edit#heading=h.9p6xz0e1ruaq

Further tests could be written, or this test iterated on, to describe the criteria of what a "correct" AIP looks like.
This issue requires #478 to be completed.

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by joel-simpson** [comment]
This issue requires #478 to be completed.

**Comment by ross-spencer** [comment]
Completed as part of our work with @wellcometrust. [Epic here](https://github.com/archivematica/Issues/issues/467).
