### ISSUE TITLE
Problem: No AMAUAT tests the content/structure of AIP METS

### ISSUE THREAD

**Issue by sromkey** [archivematica/Issues#480]
**Please describe the problem you'd like to be solved.**
A time consuming part of manual regression testing is ensuring that the AIP METS contains expected content and structure. We could have an Archivematica Automated User Acceptance Test that defines and tests the criteria for what should be in the AIP METS.

**Describe the solution you'd like to see implemented.**
1. Describe what an AIP METS should look like/contain
2. Write a feature file and test for that criteria.

**Additional context**
Requirements are being gathered here: https://docs.google.com/spreadsheets/d/1EbCshlXUPWYb1bBFxz5ObA4FHxWCkcJf38nCYGgVhCI/edit#gid=1934959319 

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by ross-spencer** [comment]
Completed as part of our work with @wellcometrust. [Epic here](https://github.com/archivematica/Issues/issues/467).
