### ISSUE TITLE
Problem: No AMAUAT confirms the content/structure of an AIP

### ISSUE THREAD

**Issue by sromkey** [archivematica/Issues#481]
**Please describe the problem you'd like to be solved.**
In manual regression testing, we need to confirm that an AIP has an expected structure and contains expected content. This testing could be done instead with an Archivematica Automated User Acceptance Test.

**Describe the solution you'd like to see implemented.**
1. Describe the criteria that an AIP should have in structure/content
2. Write a feature file and test for that criteria

**Additional context**
Criteria is being gathered here: https://docs.google.com/spreadsheets/d/1EbCshlXUPWYb1bBFxz5ObA4FHxWCkcJf38nCYGgVhCI/edit#gid=1934959319

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by ross-spencer** [comment]
Completed as part of our work with @wellcometrust. [Epic here](https://github.com/archivematica/Issues/issues/467).
