### ISSUE TITLE
Problem: No AMAUAT tests the success of AIP reingest

### ISSUE THREAD

**Issue by sromkey** [archivematica/Issues#482]
**Please describe the problem you'd like to be solved.**
In regression testing we need to manually test AIP reingest. In particular, we look for specific PREMIS events indicating that reingestion has occurred and what has happened to the objects in the AIP. This could be tested automatically using an Archivematica Automated User Acceptance Test.

**Describe the solution you'd like to see implemented.**
1. Define the criteria of what should be an acceptable AIP re-ingest
2. Write a feature file and test for this criteria.

**Additional context**
Criteria being defined here: https://docs.google.com/spreadsheets/d/1EbCshlXUPWYb1bBFxz5ObA4FHxWCkcJf38nCYGgVhCI/edit#gid=2118272868 

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by replaceafill** [comment]
@sromkey I think this is a duplicate of https://github.com/archivematica/Issues/issues/561, correct?

**Comment by sromkey** [comment]
Whoops, yep! 

Duplicates #561
