### ISSUE TITLE
Problem: "Unable to access ArchivesSpace" error when attempting an AS search in the appraisal tab

### ISSUE THREAD

**Issue by hakamine** [archivematica/Issues#483]
**Expected behaviour**
No errors

**Current behaviour**
Error as reported

**Steps to reproduce**
- Configure ArchivesSpace DIP upload (Administration > DIP upload > ArchivesSpace)
<img width="594" alt="screen shot 2019-02-05 at 12 35 47 pm" src="https://user-images.githubusercontent.com/10160634/52302802-21e95c00-2943-11e9-9e08-0f49fac22392.png">

- In the appraisal tab, go to ArchivesSpace and try an AS search (enter anything in the "Title" box and then click Search ArchivesSpace

- An error banner is shown:
<img width="1056" alt="screen shot 2019-02-05 at 12 36 21 pm" src="https://user-images.githubusercontent.com/10160634/52302831-3a597680-2943-11e9-9da3-4f90a4991b7c.png">

Additional info:

- dashboard log:
<pre>
ERROR     2019-02-05 20:36:54  django.request:base:handle_uncaught_exception:256:  Internal Server Error: /access/archivesspace/levels/
Traceback (most recent call last):
  File "/usr/share/archivematica/virtualenvs/archivematica-dashboard/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/archivematica/archivematica/src/dashboard/src/components/access/views.py", line 48, in wrapper
    client = _get_client_by_type(system)
  File "/opt/archivematica/archivematica/src/dashboard/src/components/access/views.py", line 35, in _get_client_by_type
    return get_as_system_client()
  File "/opt/archivematica/archivematica/src/dashboard/src/components/ingest/views_as.py", line 25, in get_as_system_client
    if not config['host']:
KeyError: 'host'
</pre>

- This seems to be related with https://github.com/artefactual/archivematica/pull/1328

**Your environment (version of Archivematica, OS version, etc)**

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by sallain** [comment]
This is working in 1.9 QA sites.
