### ISSUE TITLE
Problem: FPR options are listed in a left-hand sidebar but docs say right-hand

### ISSUE THREAD

**Issue by peterVG** [archivematica/Issues#484]
**Version of the documentation**
current

**Page (and section, if applicable) where the issue occurs**
https://www.archivematica.org/en/docs/archivematica-1.8/user-manual/preservation/preservation-planning/

**Description of the issue**

**Suggested fix**
change "right-hand" to "left-hand"

**Comment by ablwr** [comment]
This was fixed somewhere along the way!
