### ISSUE TITLE
Problem: Add metadata files and Normalization Event Detail views fail in the Ingest tab

### ISSUE THREAD

**Issue by replaceafill** [archivematica/Issues#486]
**Expected behaviour**

All metadata views for SIPs work in the Ingest tab. 

**Current behaviour**

Two of the metadata views fail:
- `Manual normalization event detail`
- `Add metadata files`

**Steps to reproduce**

Go to the Ingest tab and click the metadata icon for a SIP. Check any of the two views above.

**Your environment (version of Archivematica, OS version, etc)**

https://github.com/artefactual-labs/am/commit/bd1012731b3e942f13ab0e217f00478419cf1a88

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by sallain** [comment]
This is now fixed! Thanks @replaceafill!
