### ISSUE TITLE
Problem: External Identifier isn't included in the final AIP bag-info.txt

### ISSUE THREAD

**Issue by helenst** [archivematica/Issues#492]
**Please describe the problem you'd like to be solved.**
We'd like to include the External-Identifier field (and potentially other fields from the BagIt spec) in the `bag-info.txt` in the AIP generated by Archivematica

**Describe the solution you'd like to see implemented.**
In terms of implementation, it looks as if the bag tool only writes a couple of fields itself (bag size, bagged date and payload oxum), and doesn't support specifying values for other fields. However, it does support passing in a pre-existing `bag-info.txt` (which would need to be written manually) containing those fields, and will append its own fields to that.

I propose using the SIP UUID for the External Identifier field.

**Describe alternatives you've considered.**
An alternative would be to switch to using [bagit-python](https://github.com/LibraryOfCongress/bagit-python) which does allow fields to be specified, although this would be riskier in terms of changing the bag generation method.

**Additional context**
I am working on a PR for this.

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by sromkey** [comment]
Thanks for filing this Helen! We're very close to code freeze for 1.9 so I've added a label for consideration for 1.10.
