### ISSUE TITLE
Problem: docker-compose doesn't complete deployment of older qa branch, and incompatible with 1.7

### ISSUE THREAD

**Issue by ross-spencer** [archivematica/Issues#50]
**Expected behaviour**

Our docker-compose [installation process](https://github.com/artefactual-labs/am/tree/master/compose) will pass without raising an exception on different versions of the Archivematica source within reason, e.g. for testing or development purposes on certain branches.

**Current behaviour**

The bootstrap process is using a site-url argument introduced here: https://github.com/artefactual-labs/am/commit/39d08ee43c0ae55b738b165aec2d7a251d9257c8 and here https://github.com/artefactual/archivematica/pull/1142

But it isn't compatible with all recent AM 

**Steps to reproduce**

Run the docker-compose install process with an older qa branch, and you will see the following towards the end:
```
Starting compose_archivematica-storage-service_1 ... done
usage: manage.py install [-h] [--version] [-v {0,1,2,3}] [--settings SETTINGS]
                         [--pythonpath PYTHONPATH] [--traceback] [--no-color]
                         --username USERNAME --email EMAIL --password PASSWORD
                         --api-key API_KEY --org-name ORG_NAME --org-id ORG_ID
                         --ss-url SS_URL --ss-user SS_USER --ss-api-key
                         SS_API_KEY [--whitelist WHITELIST]
manage.py install: error: unrecognized arguments: --site-url=http://archivematica-dashboard:8000
Makefile:71: recipe for target 'bootstrap-dashboard-db' failed
make: *** [bootstrap-dashboard-db] Error 2
```
**Workaround**

I haven't tried this yet, but will likely revert to an older [commit](https://github.com/artefactual-labs/am/commit/4373e76ec9ee547769b48df27a531182c11f5708) for now.

**Comment by ross-spencer** [comment]
I can confirm using an older commit for this deployment method makes it possible to deploy without an exception being raised.

**Comment by sevein** [comment]
Why don't you rebase your dev branch?

**Comment by sevein** [comment]
FWIW I think this is the commit your AM dev branch is missing: https://github.com/artefactual/archivematica/commit/d952ea224ce6503b49965c2626d4dde74d735a0b.

IMO it's a fair assumption that am.git/compose can only work properly off the most recent code, in particular the versions pointed by the submodules. The opposite would be really hard to manage - probably easier if you had your branches up to date.

For 1.7, am.git has a `stable/1.7.x` branch. I haven't used it mostly because I don't do much dev work for 1.7 so it may require fixes, but that's half of your problem solved.

**Comment by ross-spencer** [comment]
Hi @sevein for my particular dev branch I didn't have the opportunity to rebase, and I can see some reasons where folk might pick up a stale dev branch and try to use this deployment method. This ticket might just be useful for others in a similar situation, but yes, given the opportunity, keeping dev branches up-to-date is understandably desirable.

**Comment by sevein** [comment]
@ross-spencer, I've added a new section to the troubleshooting guide with some tips to deal with the situation described in this issue: https://github.com/artefactual-labs/am/tree/master/compose#my-environment-is-still-broken.

**Comment by ross-spencer** [comment]
Related: https://github.com/archivematica/Issues/issues/125

**Comment by ablwr** [comment]
Is this still an issue?

**Comment by ross-spencer** [comment]
Hey @ablwr I think it likely, but probably a `wontfix` if you want to close it.

**Comment by ross-spencer** [comment]
Contrary to my thoughts 20 days ago, I'd like to reopen this, and attach the `discussion` label. I have tried to revert back to a `1.9` environment today for a simple test, but it hasn't proven that simple. I have eventually found a commit in the right time-period to test what I wanted. The ability for others to do this (I feel) is crucial to good testing and support. A developer being able to revert back to a previous AM via Docker I believe is still the path of least resistance, vs. setting up a VM via ansible. Historically, we can maintain a record that development environment `w` was required to build version `x.y.z`.

## Proposed solution

I would like to propose adding Docker-compose instructions to the release-checklist as we did AMAUAT [here](https://github.com/archivematica/Issues/issues/778). My feeling is that creating a release tag, on or near release-day, for Docker-compose will resolve, or ease the problem described in the issue. 

Perhaps an indication via this issue that this isn't the worst idea, would be good. I can raise it as a discussion point internally as well. Without adding this detail to release procedures, devs can still perform this task at release-time without too much issue too, so it's something we can try moving forward. That is to say, this doesn't feel like a huge pressing issue to be resolved immediately.

**Comment by sevein** [comment]
Would it be simpler if we moved the dev env into the main Archivematica
repo? It'd be a one-time effort not adding steps to the release process.
The original goal of am.git was to have a single entry point in AM, and
archivematica.git seems to be the best place for that.

**Comment by ross-spencer** [comment]
+1 for that as an idea, it'd be good to bring these two parts together. I personally can't see many barriers unless we were planning on supporting a different development environment in the near-future?
