### ISSUE TITLE
Problem: Dataverse transfer fails at Verify transfer compliance if transfer name contains a space

### ISSUE THREAD

**Issue by evelynPM** [archivematica/Issues#503]
**Expected behaviour**
Transfer should pass Verify transfer compliance microservice

**Current behaviour**
Failing at Job: Convert Dataverse structure with the following error: `Error opening dataset metadata: [Errno 2] No such file or directory: '/var/archivematica/sharedDirectory/currentlyProcessing/Staffing/metadata/dataset.json'`

**Steps to reproduce**
Start a transfer from SampleTransfers/Dataverse/ with Transfer type set to Dataverse; include a space in the transfer name

**Your environment (version of Archivematica, OS version, etc)**
am19centos.qa, am19bionic.qa

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by sallain** [comment]
This is working now on xenial.

**Comment by peterVG** [comment]
confirmed on Bionic. "Job Convert Dataverse structure" now passes successfully.
