### ISSUE TITLE
Problem: can't download AIP files from Archival Storage tab link if the AIP file isn't listed in the MCP Files table

### ISSUE THREAD

**Issue by hakamine** [archivematica/Issues#504]
**Expected behaviour**
From the Archival Storage tab, it should be possible to download AIP files listed there, even though the corresponding AIP files are not in the MCP Files tables. We can think for example, two possible scenarios:
1. The corresponding AIP was ingested locally, but the MCP Files table was deleted afterwards in order to reduce the size of MCP database (due to performance issues)
2. An AIP was not ingested locally, but imported using the [import_aip SS management command](https://github.com/archivematica/Issues/issues/24) and reindexed using the 
[rebuild_elasticsearch_aip_index_from_files AM management command](https://github.com/artefactual/archivematica/blob/stable/1.8.x/src/dashboard/src/main/management/commands/rebuild_elasticsearch_aip_index_from_files.py)

**Current behaviour**
When trying to download AIP files listed in the Archival Storage tab, getting an internal server error screen if the corresponding AIP file is not in the MCP Files table.

**Steps to reproduce**
Reproduced for the scenario 2 described above:
1. Imported an AIP using the [import_aip SS management command](https://github.com/archivematica/Issues/issues/24) and reindexed using the 
[rebuild_elasticsearch_aip_index_from_files AM management command]
2. In the Archival Storage tab, show the AIP files by checking the "Show files?" box and doing a search
![screen shot 2019-02-15 at 2 35 25 pm](https://user-images.githubusercontent.com/10160634/52888053-13632780-312f-11e9-9752-66286af0bfc7.png)
3. Attempt to download one of the files by clicking on the file name or file uuid. An "Internal server error" screen will appear 
![screen shot 2019-02-15 at 2 37 54 pm](https://user-images.githubusercontent.com/10160634/52888138-6046fe00-312f-11e9-840c-01fbd3f64ba2.png)
4. Dashboard log:
```
ERROR     2019-02-15 22:37:10  django.request:base:handle_uncaught_exception:256:  Internal Server Error: /archival-storage/download/aip/file/fc0e52ca-a688-41c0-a10b-c1d36e21e804/
Traceback (most recent call last):
  File "/usr/share/archivematica/virtualenvs/archivematica-dashboard/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/archivematica/archivematica/src/dashboard/src/components/archival_storage/views.py", line 312, in aip_file_download
    file = models.File.objects.get(uuid=uuid)
  File "/usr/share/archivematica/virtualenvs/archivematica-dashboard/local/lib/python2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/share/archivematica/virtualenvs/archivematica-dashboard/local/lib/python2.7/site-packages/django/db/models/query.py", line 334, in get
    self.model._meta.object_name
DoesNotExist: File matching query does not exist.
```

**Your environment (version of Archivematica, OS version, etc)**
AM dev/ branch based off qa/1.x c6396b9 (post 1.8.x, pre 1.9.x). However scenario 1 should be reproducible as well in qa/1.x, stable 1.8.x (or previous)

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by sallain** [comment]
@hakamine can you test this against one of the 1.10 test sites?

**Comment by hakamine** [comment]
Tested on AM qa/1.x 50affa (1.10.0-rc.1) SS qa/0.x fbdf31 (0.15.0-rc.1). Was able to download files from AIPs imported to the server (not ingested there, so not present in the MCP Files table), so issue is solved.
