### ISSUE TITLE
Problem: debian packages create the MCP database with the wrong character set

### ISSUE THREAD

**Issue by scollazo** [archivematica/Issues#505]
**Expected behaviour**

Database should use UTF8 as we do in source deployments, to avoid charset problems.

**Current behaviour**
The AMAUAT test for premis events unpacking is failing due to unicode problems. The database is being created using ```latin1```

**Steps to reproduce**
- Install archivematica using debian packages
- Check the mysql db collation with
```
SELECT default_character_set_name FROM information_schema.SCHEMATA WHERE schema_name = "MCP";
```

**Your environment (version of Archivematica, OS version, etc)**
Ubuntu 16.04 or Ubuntu 18.04 , with debian packages (tested with 1.9.0~rc.1+2.g57e0ddc )
---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by mamedin** [comment]
Related issue https://github.com/archivematica/Issues/issues/403

**Comment by mamedin** [comment]
For CentOS/RedHat packages the database is created in the documentation as separate step:

https://github.com/artefactual/archivematica-docs/blob/1.8/admin-manual/installation-setup/installation/scripts/am18-centos-rpm.sh#L83
