### ISSUE TITLE
Problem: Pipeline cannot read transfer packages from new "Transfer Storage" location 

### ISSUE THREAD

**Issue by peterVG** [archivematica/Issues#508]
**Expected behaviour**
The Archivematica pipeline Backlog, Appraisal, Ingest SIP creation tabs can import transfer packages from either the old backlog storage location or the new Transfer Storage location.

**Current behaviour**
The Archivematica pipeline Backlog, Appraisal, Ingest SIP creation tabs can only operate on the old backlog transfers.

**Steps to reproduce**

**Your environment (version of Archivematica, OS version, etc)**

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

blocked by #445

**Comment by joel-simpson** [comment]
This is replaced by #446
