### ISSUE TITLE
Problem: File identification failing on files extracted from packages (centos & rpms)

### ISSUE THREAD

**Issue by evelynPM** [archivematica/Issues#512]
**Expected behaviour**
When files are extracted from packages during transfer, format identification should be run on extracted files

**Current behaviour**
Siegfried is skipping file identification on extracted files

```
Module identifyFileFormat_v0.0
"75290b14-2931-455f-bdde-3b4b3f8b7f15" "/var/archivematica/sharedDirectory/watchedDirectories/workFlowDecisions/extractPackagesChoice/Ev_testing_OfficeDocs-e01d48c2-fa58-455c-b152-8d24e0e14145/objects/Club-Report.doc" "bb66f294-9d04-44c2-a7b0-7acd88e5d48b" --disable-reidentify
Standard streams
Standard output (stdout)
Skipping file format identification
```

**Steps to reproduce**
1) Select OfficeDocs transfer
2) Select Extract Packages: Yes
3) Select File identification: Yes

**Your environment (version of Archivematica, OS version, etc)**
occuring on centos, rpms, xenial and bionic

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by currmie** [comment]
Failing on Xenial too :(
