### ISSUE TITLE
Problem: Fido is being reported as 1.3.12 from FPR Database where only 1.3.10 is on the system through PIP requirements

### ISSUE THREAD

**Issue by ross-spencer** [archivematica/Issues#520]
**Expected behaviour**

Archivematica reports accurately in the microservices and the PREMIS events when a particular version of a tool is used. 

**Current behaviour**

In attempting to debug https://github.com/openpreserve/fido/issues/152 it was identified that the Fido version is being reported incorrectly for Fido. This incorrect value persists in to the METS/PREMIS:
```xml
<mets:digiprovMD ID="digiprovMD_24">
<mdWrap MDTYPE="PREMIS:EVENT">
    <xmlData>
        <premis:event xmlns:premis="info:lc/xmlns/premis-v2" schemaLocation="info:lc/xmlns/premis-v2 http://www.loc.gov/standards/premis/v2/premis-v2-2.xsd" version="2.2">
        <premis:eventIdentifier>
            <premis:eventIdentifierType>UUID</premis:eventIdentifierType>
            <premis:eventIdentifierValue>26bfff13-f6e4-4fba-b585-cd80701c0cd1</premis:eventIdentifierValue>
        </premis:eventIdentifier>
        <premis:eventType>format identification</premis:eventType>
        <premis:eventDateTime>2019-02-24T03:27:18+00:00</premis:eventDateTime>
        <premis:eventDetail>program="Fido"; version="1.3.12"</premis:eventDetail>
        <premis:eventOutcomeInformation>
            <premis:eventOutcome>Positive</premis:eventOutcome>
            <premis:eventOutcomeDetail>
                <premis:eventOutcomeDetailNote>fido-fmt/189.word</premis:eventOutcomeDetailNote>
            </premis:eventOutcomeDetail>
        </premis:eventOutcomeInformation>
        <premis:linkingAgentIdentifier>
            <premis:linkingAgentIdentifierType>preservation system</premis:linkingAgentIdentifierType>
            <premis:linkingAgentIdentifierValue>Archivematica-1.9</premis:linkingAgentIdentifierValue>
        </premis:linkingAgentIdentifier>
        <premis:linkingAgentIdentifier>
            <premis:linkingAgentIdentifierType>repository code</premis:linkingAgentIdentifierType>
            <premis:linkingAgentIdentifierValue>test</premis:linkingAgentIdentifierValue>
        </premis:linkingAgentIdentifier>
    </premis:event>
</xmlData>
</mdWrap>
```

On either system, I can only find the one version:
```bash
[root@am19rpm /]# find * | grep 'fido$'
usr/lib/archivematica/archivematicaCommon/externals/fido
usr/share/archivematica/virtualenvs/archivematica-mcp-client/bin/fido
usr/share/archivematica/virtualenvs/archivematica-mcp-client/lib/python2.7/site-packages/fido

root@am19xenial:/# find * | grep 'fido$'
opt/archivematica/archivematica/src/archivematicaCommon/lib/externals/fido
usr/share/archivematica/virtualenvs/archivematica-mcp-client/bin/fido
usr/share/archivematica/virtualenvs/archivematica-mcp-client/lib/python2.7/site-packages/fido
```

And if I invoke the tool:
```bash
[artefactual@am19rpm objects]$ /usr/share/archivematica/virtualenvs/archivematica-mcp-client/bin/fido *
FIDO v1.3.10 (formats-v94.xml, container-signature-20180920.xml, format_extensions.xml)

artefactual@am19xenial:~/archivematica-sampledata/SampleTransfers/OfficeDocsExtracted/objects$ /usr/share/archivematica/virtualenvs/archivematica-mcp-client/bin/fido *
FIDO v1.3.10 (formats-v94.xml, container-signature-20180920.xml, format_extensions.xml)
```

I haven't delved into the mechanics, but it is likely that this is driven by how we store the tool information in the policy register,where Fido is listed as `1.3.12`:

![image](https://user-images.githubusercontent.com/1880412/53299551-fa97f780-383b-11e9-9a3d-b44eb6949282.png)

**Steps to reproduce**

Run a transfer and look at the METS at the Store AIP stage, or after it is stored. Check the PREMIS version for Fido vs. the version installed. 

It will also be listed in the `Identify file format` Microservice job: 
```bash
IDCommand: Identify using Fido 1.3.12
IDCommand UUID: 213d1589-c255-474f-81ac-f0a618181e40
IDTool: Fido
IDTool UUID: c33c9d4d-121f-4db1-aa31-3d248c705e44
File: (c65b5ffd-58b7-4291-bad0-845ab03ae28b) /var/archivematica/sharedDirectory/watchedDirectories/workFlowDecisions/selectFormatIDToolTransfer/rs-fido-086b4957-70b3-4851-9704-f7e90c15dc46/objects/MS-OfficeOpenXML-samples.zip
Command output: x-fmt/263
/var/archivematica/sharedDirectory/watchedDirectories/workFlowDecisions/selectFormatIDToolTransfer/rs-fido-086b4957-70b3-4851-9704-f7e90c15dc46/objects/MS-OfficeOpenXML-samples.zip identified as a ZIP file
```

**Your environment (version of Archivematica, OS version, etc)**

Verified on RPM and Xenial test installs of AM19

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by sevein** [comment]
fido is installed via pip requirements.

https://github.com/artefactual/archivematica/blob/bb3a9496d648d095e9fb8b6a96019c158b2807e0/src/MCPClient/requirements/base.txt#L12

I think that we forgot to update it when https://github.com/artefactual/archivematica-fpr-admin/pull/94 was merged.

**Comment by ross-spencer** [comment]
Ah! I looked there, but going alphabetically missed `opf-fido` over `fido`, thx @sevein easy-enough fix.

**Comment by ross-spencer** [comment]
NB. This is still pinned at [3.10](https://github.com/artefactual/archivematica/blob/f06c0e317d7187bd346f09828fd9b52d33952848/src/MCPClient/requirements/base.txt#L21) in `qa.1.x`.

And if you activate the `venv` you can check the version:
```
(archivematica-mcp-client) [centos@am110rpm ~]$ fido version
FIDO v1.3.10 (formats-v94.xml, container-signature-20180920.xml, format_extensions.xml)
FIDO: Processed      0 files in  50.00 msec,  0 files/sec
```

FPR versions were partially tackled in [this issue](https://github.com/archivematica/Issues/issues/191#issuecomment-510176085) but the comment notes we didn't resolve the FPR issues around versions of format identification tools. 

Related to https://github.com/archivematica/Issues/issues/791 (might be resolved as part of the PRONOM update)
Related to https://github.com/archivematica/Issues/issues/847 (requirements should be updated when we want to use the latest changes made in the Fido Py3 development branches)

That being said, it remains an [open question](https://github.com/archivematica/Issues/issues/522) how to enable the FPR to query version properly. Creating an interface for FPR rules that specifies how to ask tools for version information and return that seems a pretty standard approach but is by no means a small undertaking.

You can monitor the effect of the database in this situation by modifying the strings there, and observing the output in the PREMIS that is exported:

![image](https://user-images.githubusercontent.com/1880412/67751598-b051c080-fa31-11e9-8892-75d8c0fb9baa.png)

```xml
      <premis:eventDetailInformation>
        <premis:eventDetail>program="Fido"; version="1.x.x"</premis:eventDetail>
      </premis:eventDetailInformation>
```

**Comment by ablwr** [comment]
+1 for 1.11 triage, we will have to update FIDO to 1.4 anyway

**Comment by ablwr** [comment]
FIDO should be updated to [v1.4.1](https://github.com/openpreserve/fido/releases), which should be deployed as `opf-fido` [here](https://pypi.org/project/opf-fido/1.4.1/). This has to be done by someone with `pip-compile` functional on her computer, which is not me.

(See https://github.com/archivematica/Issues/issues/791 for context)

**Comment by sallain** [comment]
Preservation Planning > Identification > Tools shows Fido as version 1.4.1. Fido is also working just fine. Tested on qa/0.x on Bionic.
