### ISSUE TITLE
Problem: JHOVE on RPM and CentOS test servers are out of date

### ISSUE THREAD

**Issue by ross-spencer** [archivematica/Issues#521]
**Expected behaviour**

JHOVE should be consistent across Archivematica environments. 

**Current behaviour**

As documented in this issue, validation fails in CentOS and RPM installs because JHOVE is four versions behind (although I believe the failing module is only two versions behind). 

https://github.com/archivematica/Issues/issues/513#issuecomment-466707634

**Steps to reproduce**

As per this ticket, https://github.com/archivematica/Issues/issues/513#issue-413139158 except the results can be observed in `Job Validate formats`. 

**Your environment (version of Archivematica, OS version, etc)**

The most recent `qa/1.x` commit on each of these deployments should be: https://github.com/artefactual/archivematica/commit/57e0ddce108090483b24617ba82f8a731dfaa8d9 

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by ross-spencer** [comment]
I don't want to spam everyone with JHOVE issues, so I have opted to close this in favor of https://github.com/archivematica/Issues/issues/524 which I hope is okay.

**Comment by sromkey** [comment]
@ablwr could you please investigate?

**Comment by ablwr** [comment]
@ross-spencer opted to close this in favor of #524 and I am going to do the same.
