### ISSUE TITLE
Problem: There are JHOVE inconsistencies across deployments and in the FPR/PREMIS output

### ISSUE THREAD

**Issue by ross-spencer** [archivematica/Issues#524]
**Expected behaviour**

This is to collect a few issues surrounding JHOVE, so that there is one ticket to capture it. It is closely related to this ticket here too: https://github.com/archivematica/Issues/issues/394

1. PREMIS events written about JHOVE should be accurate to the JHOVE version and module version.
2. Deployments of Archivematica should be consistent where possible.
3. Optionally, JHOVE versions should be kept up-to-date where there are updates available. 

**Current behaviour**

Across test deployments, we currently see two versions of JHOVE:

Xenial:
```bash
Jhove (Rel. 1.16.0, 2017-12-06)
 Date: 2019-02-24 20:24:31 UTC
```

Bionic:
```bash
Jhove (Rel. 1.16.0, 2018-10-09)
 Date: 2019-02-24 20:25:18 UTC
```

RPM:
```bash
Jhove (Rel. 1.12.0-SNAPSHOT, 2016-07-28)
 Date: 2019-02-24 21:27:11 CET
```

CentOS:
```bash
Jhove (Rel. 1.12.0-SNAPSHOT, 2016-07-28)
 Date: 2019-02-24 21:26:33 CET
```

As well as that, neither version is reported correctly in the FPR. The impact of that, however, is that we don't accurately capture information that might be useful to users identifying issues with validation, including false-positives. In the extract below, we see PDF is validated using JHOVE version 1.6: 
```xml
<mdWrap MDTYPE="PREMIS:EVENT">
    <xmlData>
        <premis:event xmlns:premis="info:lc/xmlns/premis-v2" schemaLocation="info:lc/xmlns/premis-v2 http://www.loc.gov/standards/premis/v2/premis-v2-2.xsd" version="2.2">
        <premis:eventIdentifier>
            <premis:eventIdentifierType>UUID</premis:eventIdentifierType>
            <premis:eventIdentifierValue>177df159-942b-48d5-b8e1-62d87ab86cb9</premis:eventIdentifierValue>
        </premis:eventIdentifier>
        <premis:eventType>validation</premis:eventType>
        <premis:eventDateTime>2019-02-24T20:05:39.507697+00:00</premis:eventDateTime>
        <premis:eventDetail>program="JHOVE"; version="1.6"</premis:eventDetail>
        <premis:eventOutcomeInformation>
            <premis:eventOutcome>pass</premis:eventOutcome>
            <premis:eventOutcomeDetail>
                <premis:eventOutcomeDetailNote>
                    format="PDF"; version="1.6"; result="Well-Formed and valid"
                </premis:eventOutcomeDetailNote>
            </premis:eventOutcomeDetail>
        </premis:eventOutcomeInformation>
        <premis:linkingAgentIdentifier>
            <premis:linkingAgentIdentifierType>preservation system</premis:linkingAgentIdentifierType>
            <premis:linkingAgentIdentifierValue>Archivematica-1.9</premis:linkingAgentIdentifierValue>
        </premis:linkingAgentIdentifier>
        <premis:linkingAgentIdentifier>
            <premis:linkingAgentIdentifierType>repository code</premis:linkingAgentIdentifierType>
            <premis:linkingAgentIdentifierValue>test</premis:linkingAgentIdentifierValue>
        </premis:linkingAgentIdentifier>
    </premis:event>
</xmlData>
</mdWrap>
```

This seems to be driven by the FPR, if we look up the database table: 
```mysql
mysql> select * from fpr_fptool where description = "JHOVE";
+----+--------------------------------------+-------------+---------+---------+----------+
| id | uuid                                 | description | version | enabled | slug     |
+----+--------------------------------------+-------------+---------+---------+----------+
| 18 | 085d8690-93b7-4d31-84f7-2c5f4cbf6735 | JHOVE       | 1.6     |       1 | jhove-16 |
+----+--------------------------------------+-------------+---------+---------+----------+
1 row in set (0.00 sec)
```

This PREMIS output, taken from my docker-compose install, ideally, would report, both the overall JHOVE version, and the module used to mark the PDF `well formed and valid` as per the JHOVE output below where the overall version of JHOVE is 1.16, and the PDF module is 1.9: 
```bash
Jhove (Rel. 1.16.0, 2018-09-20)
 Date: 2019-02-24 20:29:35 GMT
 App:
  API: 1.16.0, 2018-09-20
  Configuration: /etc/jhove/jhove.conf
  JhoveHome: $INSTALL_PATH
  Encoding: utf-8
  TempDirectory: /tmp
  BufferSize: 131072
  Module: AIFF-hul 1.3
  Module: ASCII-hul 1.3
  Module: BYTESTREAM 1.3
  Module: GIF-hul 1.3
  Module: GZIP-kb 0.1
  Module: HTML-hul 1.3
  Module: JPEG-hul 1.2
  Module: JPEG2000-hul 1.3
  Module: PDF-hul 1.9
  Module: PNG-gdm 1.0
  Module: TIFF-hul 1.7
  Module: UTF8-hul 1.6
  Module: WARC-kb 1.0
  Module: WAVE-hul 1.4
  Module: XML-hul 1.4
  OutputHandler: Audit 1.1
  OutputHandler: TEXT 1.5
  OutputHandler: XML 1.7
```

**Additional context**

Replaces https://github.com/archivematica/Issues/issues/521
At time of writing, the most recent JHOVE is `v1.20 29-03-2018` via http://jhove.openpreservation.org/

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by sromkey** [comment]
Related to #513

**Comment by sromkey** [comment]
At this stage I'm going to suggest that this and #513 are put up for consideration in 1.10

**Comment by ross-spencer** [comment]
That sounds good @sromkey cc. @mamedin I was conscious writing this up that it feels too chunky for `1.9`, but it would be good to resolve soon-ish.

**Comment by ablwr** [comment]
UWashington would also like JHOVE to get updated soon! There's been some notable updates between this version and the latest version that would make identification of WAV files better (and less likely to fail).

**Comment by ablwr** [comment]
I did some testing with this. The latest JHOVE at time of writing is 1.22, but there's a [critical error](https://github.com/openpreserve/jhove/issues/459) that prevents us from being able to upgrade to that version. 1.22 also changes the namespaces of the exported XML.

I have been testing with version 1.20 (1.21 seems to have never existed) and it seems to be a winner. I think updating JHOVE to 1.20 across versions is the best thing to do at this stage!

**Comment by joel-simpson** [comment]
As discussed in today's scrum, this still needs an ampack-build PR and build packages. Assigned to @mamedin . moving this back to "in progress"
