### ISSUE TITLE
Problem: Incorrect text on button in Rights metadata entry template

### ISSUE THREAD

**Issue by evelynPM** [archivematica/Issues#526]
**Expected behaviour**
Button should read "Create new grant/restriction?"

**Current behaviour**
Button currently reads "Create new %(type)?"

**Steps to reproduce**
1) Open rights metadata entry template
2) Create a rights basis and click Next
3) Create a permission/restriction and click Save
4) Button with the incorrect text appears in the lower right-hand corner

**Your environment (version of Archivematica, OS version, etc)**
am19centos.qa, but also appears in 1.8.1 sandbox
---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by sallain** [comment]
This looks to be fixed on xenial!

**Comment by peterVG** [comment]
fixed on Bionic.
