### ISSUE TITLE
Problem: Access System ID field is not passing values for DIP upload

### ISSUE THREAD

**Issue by sallain** [archivematica/Issues#528]
**Expected behaviour**
The `Access system ID` box was added to the transfer area in Archivematica 1.8 (see documentation [here](https://www.archivematica.org/en/docs/archivematica-1.8/user-manual/access/access/#upload-atom)).

If I add a valid AtoM slug to the access system ID box before starting my transfer, Archivematica should automatically use the provided slug to upload the DIP to AtoM when "Upload DIP to AtoM/Binder" is selected at the Upload DIP microservice.

**Current behaviour**
When "Upload DIP to AtoM/Binder" is selected at the Upload DIP microservice, Archivematica prompts the user to enter the AtoM slug. The DIP upload works, but the prompt should not appear.

**Steps to reproduce**
1. Make sure the processing configuration is set to `Normalize for access` and `Upload DIP to AtoM/Binder`.
2. Make sure the AtoM credentials are properly set in the Admin tab.
3. Create a transfer and enter a valid AtoM slug in the `Access system ID` box.
4. Start transfer and process until DIP upload prompts.

**Your environment (version of Archivematica, OS version, etc)**
Tested on Archivematica 1.9 on Ubuntu 18.04 Bionic and Ubuntu 16.04 Xenial.
---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by peterVG** [comment]
Archivematica once again automatically uses slug provided as Access System ID to upload the DIP to AtoM when "Upload DIP to AtoM/Binder" is selected at the Upload DIP microservice.

**Comment by sallain** [comment]
Works on xenial too! :clap: :clap: :clap:
