### ISSUE TITLE
Problem: can't arrange a SIP from backlog with long names

### ISSUE THREAD

**Issue by sevein** [archivematica/Issues#53]
My transfer looks as the one below. To reproduce, re-create a similar structure. Start the transfer, move it to backlog and then try to arrange a new SIP from it.

```
University_Suspendisse_and_Legal_Interdum_-_Board_and_Senate_records__2010-2017
└── University_Suspendisse_and_Legal_Interdum
    └── Board_of_Foobars_-_XYZ_Material
        └── Board_of_Foobars_XYZ_-_11_Jun_1999_-_Agenda_-_Pdf.txt
```

The SIP never appears in the user interface. SS returns a 500 error but the Dashboard doesn't let the user know about the situation. SS throws an error (rsync can't locate files).

The problem seems to be in that the values that we're storing in `main_siparrange` during the arrangement are stripped by MySQL due to the type used in `original_path` and `arrange_path`.

This is the schema of `main_siparrange` (`models.SIPArrange`).

```sql
 CREATE TABLE `main_siparrange` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `original_path` varchar(255) DEFAULT NULL,
  `arrange_path` varchar(255) NOT NULL,
  `file_uuid` varchar(36) DEFAULT NULL,
  `transfer_uuid` varchar(36) DEFAULT NULL,
  `sip_created` tinyint(1) NOT NULL,
  `aip_created` tinyint(1) NOT NULL,
  `level_of_description` varchar(2014) NOT NULL,
  `sip_id` varchar(36) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `original_path` (`original_path`),
  KEY `main_siparrange_2664b5aa` (`sip_id`),
  CONSTRAINT `main_siparrange_sip_id_601574f35f1ea7ec_fk_SIPs_sipUUID` FOREIGN KEY (`sip_id`) REFERENCES `SIPs` (`sipUUID`)
) ENGINE=InnoDB AUTO_INCREMENT=8 DEFAULT CHARSET=latin1
```

Version: 1.8-dev

**Comment by peterVG** [comment]
I recreated the same directory structure and placed it in a transfer called "long-dir-test-1":

![screen shot 2018-10-03 at 11 23 57](https://user-images.githubusercontent.com/672121/46432323-e32c6680-c702-11e8-89e2-d04c76ad24bf.png)

I moved the transfer to backlog but when I try to arrange a SIP from it, the directory doesn't open (stays uncollapsed when clicking the arrow icon) like it does for other backlog directories.

![screen shot 2018-10-03 at 11 52 06](https://user-images.githubusercontent.com/672121/46432466-30a8d380-c703-11e8-86a7-f98741816308.png)

**Comment by sevein** [comment]
Back to you, Peter! The problem you found was a CSS glitch, the button was being hidden by the directory name when it was too long. Fixed in https://github.com/artefactual/archivematica/pull/1288.
