### ISSUE TITLE
Problem: We cannot automatically configure automation-tools or amclient.py to re-record vcrpy cassettes

### ISSUE THREAD

**Issue by ross-spencer** [archivematica/Issues#530]
**Please describe the problem you'd like to be solved.**

Being able to re-record [vcr_cassette](https://github.com/kevin1024/vcrpy) fixtures for the automation-tools and `amclient.py` provides some level of integration testing with the Archivematica and Storage Service API endpoints. This could be beneficial where that integration doesn't currently exist. 

Additionally, because functionality tends to be added to the two utilities at different intervals, it can reduce the burden of having to record a cassette against one endpoint when global variables set in tests are logically pointing at different endpoints on different servers. The process currently looks like this:

1. Record against an available endpoint.
2. Access the cassette in an IDE and replace the api keys and endpoint IP addresses.
3. Test again with the new values to ensure that they pass.

Steps 2 and 3 are less than ideal, and are time-consuming for the developer. For external contributors it might not be the most intuitive of phases either, because functionality could technically be added (to `amclient.py` as an example), in fewer than 10 lines of code, and 20-30 lines of test function. 

**Describe the solution you'd like to see implemented.**

I would like to see the re-recording of these fixtures made easier. At present, if a developer changes the global variables, then first the tests stop working. Second, to re-record all the tests, they will see 17 failures (at time of writing):
```python
Ran 41 tests in 0.318s

FAILED (failures=17, errors=6)
```

The failures are often caused because the way tests need to be configured. As an example, listing unapproved transfers via the API requires that the Archivematica service has unapproved transfers to report. 

The failures could also be in what the API is returning, and how the code is working with that result. That is more difficult to pull-apart when the fixtures are stale, i.e. recorded against `1.6`, `1.7`, `1.8` endpoints where depending on the quality of unit tests against those there could conceivably be some drift in what consumers are anticipating. 

Making the re-recording process easier, might involve: 

* Creating scripts to automatically populate Archivematica.
* Clearing the existing fixtures.
* Running the new tests against the desired endpoint. 

**Describe alternatives you've considered.**

Alternatives:

(For completeness, rather than any particular belief in one solution over the above)

1. Record tests against default Archivematica outputs only, e..g if there are no unapproved transfers, only test for that, don't try and test for handling against a configuration with unapproved values. 
2. Change the paradigm to not use fixtures such as these. 
3. Always record on a specific virtual machine running Archivematica and the Storage Service. 
4. Reduce the reliance on global variables in the test scripts and let each test function configure itself independently so that developers only need to re-record a single test at a time with their desired ip addresses. 

**Additional context**

As we continue to develop the `amclient.py` work to make it more complete in what it offers the user, the overhead becomes clearer with each new addition. For the developer this might diminish their interest in testing for undesirable results, i.e. they may only test for the output they desire and not try to write tests to disprove cases where their additions may or may not work. 

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by replaceafill** [comment]
Closing this as we've started to move away from `vcrpy`.
