### ISSUE TITLE
Problem: Disabled FPR "Event Detail" is still outputting premis:eventDetail to METS

### ISSUE THREAD

**Issue by peterVG** [archivematica/Issues#531]
**Expected behaviour**
With the Event Detail command set to "disabled" the Event Detail data should be excluded from the premis:event section.

**Current behaviour**
The premis:eventDetail data is written to the METS file when Event Detail is disabled for a given Command.

**Steps to reproduce**
Disable 'inkscape event detail' in "Preservation Planning > Event Detail" tab.
Run the SampleTransfers/OfficeDocs transfer.
Normalize for preservation.
Check the METS file and note that "inkscape" information is output to the premis:eventDetail for the normalization premis:event.

Disable 'convert event detail' in "Preservation Planning > Event Detail" tab.
Run the SampleTransfers/Image transfer.
Normalize for preservation.
Check the METS file and note that "convert" information is output to the premis:eventDetail for the normalization premis:event.

**Your environment (version of Archivematica, OS version, etc)**

am19bionic.qa

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by peterVG** [comment]
The way to disable is actually to leave a blank "event detail command" on the source command definition (e.g. normalization, characterization).

**Comment by peterVG** [comment]
![screen shot 2019-03-04 at 11 12 49](https://user-images.githubusercontent.com/672121/53756647-85957500-3e6e-11e9-8521-730747cfa516.png)

**Comment by ross-spencer** [comment]
Hi @peterVG this still feels like a bug - what does the event detail say when it is disabled?
