### ISSUE TITLE
Problem: vagrantfile has a typo

### ISSUE THREAD

**Issue by sallain** [archivematica/Issues#535]
**Expected behaviour**
The vagrantfile should work.

**Current behaviour**
The vagrantfile does not work! Richard Pearce-Moses reports:

I went to install an instance of Archivematica in a VirtualBox using Vagrant, following the instructions on https://www.archivematica.org/en/docs/archivematica-1.8/getting-started/quick-start/quick-start/#installing-on-vm

Vagrant reported a 404 for https://vagrantcloud.com/artefactal/archivematica

With a bit of squinting, I saw that the URL in the Vagrant file in the home directory has a typo - the u in artefactual is missing.  I edited the file, and now it seems to be working. 

**Steps to reproduce**

**Your environment (version of Archivematica, OS version, etc)**

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by sallain** [comment]
@scollazo this can be closed?

**Comment by scollazo** [comment]
@sallain , as the Vagrant box and docs had been updated, I think we can close this.
