### ISSUE TITLE
Problem: SIP arrange functionality in Ingest could be moved to Appraisal tab

### ISSUE THREAD

**Issue by sromkey** [archivematica/Issues#536]
**Please describe the problem you'd like to be solved.**
It would be functionally cleaner if all of the SIP arrangement options were present in one tab. Since the Appraisal tab is more feature-rich, it makes sense to move the functionality that currently exists at the top of Ingest to the Appraisal tab.

**Describe the solution you'd like to see implemented.**
If we wanted to do-away with the SIP arrange area in the Ingest tab, this is the functionality that we would want to add to the Appraisal tab:

- Edit metadata button needs to access AtoM levels of description (Arrangement pane)
- Need to be able to drag and drop folders and objects within the Arrangement pane
- Need to be able to see logs and metadata folders in Backlog pane, to be turned on/off with a toggle

**Describe alternatives you've considered.**
We could leave it as is and it wouldn't be the end of the world, but this is a cleaner solution IMO.

**Additional context**
Originally logged as an issue here: https://projects.artefactual.com/issues/10836

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by sevein** [comment]
Adding the SFU for consideration - if updating SIP arrange so it works with baggited transfer is going to be a lot of work, maybe removing SIP arrange can be considered a better alternative.
