### ISSUE TITLE
Problem: normalization using inkscape failing on rpm

### ISSUE THREAD

**Issue by evelynPM** [archivematica/Issues#537]
**Expected behaviour**
In sampleData/Images the files Vector.NET-Free-Vector-Art-Pack-28-Freedom-Flight.eps and lion.svg should be normalized for preservation using Inkscape

**Current behaviour**
Normalization is unsuccessful and the error output gives a lecture on morality. Sample error output:

```
We trust you have received the usual lecture from the local System
Administrator. It usually boils down to these three things:
    #1) Respect the privacy of others.
    #2) Think before you type.
    #3) With great power comes great responsibility.
sudo: no tty present and no askpass program specified
Failed: Transcoding to plain svg with inkscape
```

**Steps to reproduce**
Ingest sampleData/Images and choose Normalize for preservation. View the normalization command output in  the normalization report.

**Your environment (version of Archivematica, OS version, etc)**
am19rpm.qa. Confirmed that this is not happening on centos, bionic or xenial

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by sevein** [comment]
@evelynPM can you try again with the `Transcoding to plain svg with inkscape` command updated as follows?

```
/usr/bin/inkscape "%fileFullName%" --export-plain-svg="%outputDirectory%%prefix%%fileName%%postfix%.svg"
chmod 777 "%outputDirectory%%prefix%%fileName%%postfix%.svg"
```

If that works for you, we can submit a new migration in `fpr` applying the same fix.

The original command was using `sudo` which is not expected to work.
I think that `sudo` was used in early prototypes of Archivematica.

**Comment by sromkey** [comment]
@sevein I can confirm that command works on rpm install.

**Comment by sevein** [comment]
https://github.com/artefactual/archivematica/pull/1359 is now merged. I'm hoping that the normalization command will now work in all environments.

**Comment by sromkey** [comment]
@sevein remember also to remove sudo from the ansible role
