### ISSUE TITLE
Index AIP fails when depositing to DSpace

### ISSUE THREAD

**Issue by J4bbi** [archivematica/Issues#540]
**Expected behaviour**
When depositing AIP to DSpace Archivematica should (probably?) not attempt to Index the AIP.

**Current behaviour**
This has only been tested with depositing to DSpace and not other external spaces. If AIP is stored in Standard Archivematica Directory the error is not raised. When depositing to DSpace however, after Store the AIP has finished, Index AIP fails with:

```
Standard output (stdout)
AIP info: [{u'status': u'UPLOADED', u'package_type': u'AIP', u'origin_pipeline': u'/api/v2/pipeline/47e2ebdb-e15a-4c5a-843c-8820043b1654/', u'uuid': u'1788b294-8016-4b77-8ec4-29ba80a6c52f', u'replicas': [], u'encrypted': False, u'current_path': u'1788/b294/8016/4b77/8ec4/29ba/80a6/c52f/image-test-1788b294-8016-4b77-8ec4-29ba80a6c52f.7z', u'replicated_package': None, u'misc_attributes': {}, u'current_full_path': u'/1788/b294/8016/4b77/8ec4/29ba/80a6/c52f/image-test-1788b294-8016-4b77-8ec4-29ba80a6c52f.7z', u'current_location': u'/api/v2/location/d0b819ce-c7d1-4582-80f7-6469a9bf6565/', u'related_packages': [u'/api/v2/file/53341703-2e69-4185-b635-1981164d1add/'], u'size': 2962775, u'resource_uri': u'/api/v2/file/1788b294-8016-4b77-8ec4-29ba80a6c52f/'}]
Indexing additional identifiers %s []
Indexing AIP and AIP files
Standard error (stderr)
AIP does not exist at: /1788/b294/8016/4b77/8ec4/29ba/80a6/c52f/image-test-1788b294-8016-4b77-8ec4-29ba80a6c52f.7z
Error indexing AIP and AIP files
```

**Steps to reproduce**
Run a transfer through with DSpace set up as receiving space.
Note that because of #458 a metadata.json file with destination AIP collection needs to be included in the transfer package.
It would be interesting to see if same behaviour is shown when depositing to other external locations.

**Your environment (version of Archivematica, OS version, etc)**

 - Vanilla [AM/Compose](https://github.com/artefactual-labs/am/tree/master/compose)
- AM - On branch stable/1.8.x
- SS - On branch stable/0.13.x
---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by evelynPM** [comment]
Is the AIP being successfully deposited into DSpace?

**Comment by mamedin** [comment]
Hi @evelynPM , I tested the same environment and the AIP was successfully deposited into DSpace. I have credentials to use the same DSpace server they used in the their tests.

**Comment by J4bbi** [comment]
@sromkey https://github.com/artefactual/archivematica/pull/1369 seems to have fixed this

**Comment by sromkey** [comment]
Awesome, thanks for the update @J4bbi !
