### ISSUE TITLE
Problem: amclient package isn't published as an Artefactual project

### ISSUE THREAD

**Issue by ross-spencer** [archivematica/Issues#543]
**Expected behaviour**

The new amclient package needs to be completed and published as an Artefactual project. I believe thatt there are a couple of tasks outstanding ((suggested steps) some are ideal, some are required):

* [x] Setup TravisCI integration in the repository: https://github.com/artefactual-labs/amclient
* [x] Add repository docs according to Artefactual principles on the amclient repo, e.g. `CONTRIBUTING.md` and pointers to the issues repository. 
* [x] Upload the package without the `rc` (release candidate) suffix as the Artefactual user on PyPi. 
* [x] Create an ADR.

The current PyPi repository is here: https://pypi.org/project/amclient/

**NB** A note on a target for the release is that Archivematica `1.10` contains two new endpoints, tha would be worth wrapping in a `1.0` release of AM Client. The end points are also used by the AMAUAT black box tests. 

* [x] Also done [here](https://github.com/artefactual-labs/amclient/commit/91e09f21fbcf303be3585f6a04c40308e70d7fd3) 

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by ross-spencer** [comment]
Related to https://github.com/archivematica/Issues/issues/644

**Comment by sromkey** [comment]
@ross-spencer This might be a candidate for an ADR if one does not already exist

**Comment by ross-spencer** [comment]
Released and ADR merged:

* [ADR](https://adr.archivematica.org/0009-unification-of-api-handling-in-am.html)
* [PyPi Release](https://pypi.org/project/amclient/)
* [Github Release](https://github.com/artefactual-labs/amclient/releases/tag/v1.0.0)

Suggested testing approach:

1. Find a clean working directory somewhere.
2. Create a virtual environment: ` python3 -m pip install amclient`
3. Access the virtual enviroment: `source venv/bin/activate`
4. Install `amclient` via pip: `pip install amclient`
5. Run the following in a Python interpreter by typing first: `python`
```python
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from amclient import AMClient
>>> print(AMClient.version())
1.0.0
```
As the client library is a CLI application as well, you can also try:
```bash
(venv) user-name@artefactual:~/Desktop/temp/amclient$ amclient --version
amclient 1.0.0
```
