### ISSUE TITLE
Problem: AtoM not creating Information Object for re-ingested AIPs with updated metadata

### ISSUE THREAD

**Issue by evelynPM** [archivematica/Issues#546]
**Expected behaviour**
AtoM should create an information object out of the Dublin Core metadata entered via the GUI

**Current behaviour**
No Information Object is created and none of the DC metadata appear in AtoM

**Steps to reproduce**
-Create and store an AIP with DC metadata entered via the GUI
-Perform a partial re-ingest
-Edit the DC metadata via the GUI
-Create a DIP and upload it to AtoM

**Your environment (version of Archivematica, OS version, etc)**
am19centos.qa, am19rpm.qa

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by sromkey** [comment]
My suspicion is that AtoM doesn’t know how to interpret the “updated” status of the dmdSec. Not sure if the issue can be solved on the Archivematica side though- I think this should be filed with the AtoM project.

**Comment by sromkey** [comment]
Closing this due to my comment above ^.

**Comment by evelynPM** [comment]
Filed issue in the AtoM project at https://projects.artefactual.com/issues/13068.
