### ISSUE TITLE
Problem: descriptive metadata added via GUI is not indexed for searching

### ISSUE THREAD

**Issue by sallain** [archivematica/Issues#547]
**Expected behaviour**
If I add descriptive metadata to a transfer or ingest, I should be able to use the descriptive metadata to search for the resulting AIP.

**Current behaviour**
I can search for the AIP using the descriptive metadata if the metadata was added using a CSV included with the transfer. However, if the metadata was added using the form in the GUI, I cannot search for the AIP using the descriptive metadata.

**Steps to reproduce**

First, create a transfer that is searchable:
1. Create a transfer using the package SampleTransfers/CSVmetadata.
2. Store the AIP.
3. Search for the term "Peters" or any other word that appears in the [metadata CSV](https://github.com/artefactual/archivematica-sampledata/blob/master/SampleTransfers/CSVmetadata/metadata/metadata.csv).

Then, create a transfer that is not searchable:
1. Create a new transfer using any package.
2. At any time before the metadata reminder microservice, click on the metadata icon and add descriptive metadata.
3. Complete processing until the AIP has been stored.
4. Try to search for the AIP using one of the metadata terms that you added.

**Your environment (version of Archivematica, OS version, etc)**
1.x

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by ablwr** [comment]
I followed the above reproduction guidelines but this still doesn't seem resolved to me. As @sallain brings up in the above issue #273, searching is notably finicky, but I can't find my top-level dc:title metadata, "<dc:title>carlyraejepsen</dc:title>" :(

**Comment by ablwr** [comment]
Actually we are all good here -- I had cleared out my test environment before testing this, and it accidentally sent me back to the non-qa branches. In qa/1.x (last commit: https://github.com/artefactual/archivematica/commit/6d84db86d7d8fa21cea6f79f4b2ef1ec4c9666ef), this is fine.
