### ISSUE TITLE
Problem: Choosing AtoM/Binder/AT/AS config is unnecessary (from user point of view)

### ISSUE THREAD

**Issue by sromkey** [archivematica/Issues#55]
**Expected behaviour**

When I choose DIP upload to AtoM/Binder, it should immediately give me the pop-up to enter the slug/object ID.

**Current behaviour**

There is a "Choose config for AtoM/Binder" job. This is an unnecessary click from a user's point of view, because there are not multiple configs to choose from.

**Your environment (version of Archivematica, OS version, etc)**

qa/1.x.

**Comment by sevein** [comment]
I think that this is also the case for AT/AS uploads, at least since https://github.com/artefactual/archivematica/pull/1233.

**Comment by sevein** [comment]
I've updated the title to reflect that this is true for all uploads.
Currently investigating a solution...

**Comment by peterVG** [comment]
pop-up to enter Atom/Binder slug appears as soon as Upload is selected so this issue is resolved in 1.8
