### ISSUE TITLE
Problem: MCP server doesn't report when the Gearman server is unavailable

### ISSUE THREAD

**Issue by alexwlchan** [archivematica/Issues#553]
**Expected behaviour**

When you run the MCP client, if you've misconfigured the Gearman server config, it prints an error log:

```
Gearman server is unavailable: <Error message>. Retrying in 3 seconds.
```

This is a useful debugging log. The MCP server should log in the same way.

**Current behaviour**

If you've misconfigured the Gearman server config in the MCP server, it hangs silently and doesn't explain why nothing is happening.

**Steps to reproduce**

Start the MCP server after doing any of:

- Disabling the Gearman server
- Changing the MCP server environment variables/config so it can't find Gearman
- Breaking networking between them

**Your environment (version of Archivematica, OS version, etc)**

This was originally observed with the release Debian package of AM 1.8.1, running on Ubuntu 18.04.

See https://github.com/artefactual/archivematica/pull/1361

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by sevein** [comment]
I've tested Alex' solution and it's working as expected.

**Comment by sallain** [comment]
@alexwlchan this is ready to test in the 1.10 release candidate if you would like to test!
