### ISSUE TITLE
Problem: s3 bucket name can't be configured

### ISSUE THREAD

**Issue by scollazo** [archivematica/Issues#558]
**Expected behaviour**
When configuring a S3 aipstore, there is no way to select wich S3 bucket to use

**Current behaviour**
The bucket is created by the storage-service, and the bucket id is used as space id.

This also means that the IAM user configured in SS needs to have permissions to create buckets (we are using S3Admin group )

**Steps to reproduce**
Create a S3 storage space

**Your environment (version of Archivematica, OS version, etc)**
Archivematica 1.9 in Ubuntu Bionic

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by sevein** [comment]
The behaviour described is by design. We could certainly make some of it configurable but that sounds like an enhancement to me, i.e. not something that we can include in AM v1.9.1?

**Comment by sromkey** [comment]
Good point @sevein , I had assumed this was something possible in 1.8.

**Comment by ablwr** [comment]
Working in qa/1.x -- docs will need to be updated to reflect this new field.
