### ISSUE TITLE
Problem: No AMAUAT for testing transfer micro-services

### ISSUE THREAD

**Issue by sromkey** [archivematica/Issues#562]
**Please describe the problem you'd like to be solved.**

We do not have an Archivematica Automated User Acceptance Test for testing the success of digital preservation actions which happen as transfer micro-services (virus scanning, metadata extraction, validation, message digest calculation, file format identification, ingestion).

**Describe the solution you'd like to see implemented.**

Write a test that ensures the outcomes are being written to the AIP METS file 

**Additional context**

Scenarios for testing are being captured here: https://docs.google.com/document/d/1KGTsuc9NV5yaq-lUY7CVK3XY33C21zS3Ykr-N-6gpEg/edit# 

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by ross-spencer** [comment]
Completed as part of our work with @wellcometrust. [Epic here](https://github.com/archivematica/Issues/issues/467).
