### ISSUE TITLE
Problem: when Extract Packages fails, there is no visual indicator of the failure in the dashboard

### ISSUE THREAD

**Issue by sallain** [archivematica/Issues#568]
**Expected behaviour**
When tasks fail in Archivematica, the general protocol in the dashboard is for the specific job to turn pink with the message "Failed".

![image](https://user-images.githubusercontent.com/4612276/54314591-5206c900-4599-11e9-8418-d8e434675566.png)

Any failure in Archivematica should result in the same behaviour.

**Current behaviour**
When Archivematica tries to extract a package but the package is corrupt, the job "Extract contents from compressed archives" fails but the user is not notified of the failure in the dashboard. The transfer then fails completely.

![image](https://user-images.githubusercontent.com/4612276/54314653-7a8ec300-4599-11e9-9e5d-2eebda4b8954.png)

This can make it difficult to troubleshoot the issue.

The failure is also not particularly well-reported in the task output page. An exit code 255 is reported, but the problem file doesn't "float to the top" as with other errors. The job "Extract contents from compressed archives" produces potentially a lot of output - at least one line for every file. The stdout ends with

```
Error:
Unexpected end of input stream
```

but the actual problem is buried in the long stderr:

```
extractcontents_v0.0: INFO      2019-03-12 20:05:25,417  archivematica.mcp.client.extractContents.main:173  Command to execute is: 7z x -bd -o"/var/archivematica/sharedDirectory/watchedDirectories/workFlowDecisions/extractPackagesChoice/700-2019-02TEST-fd0d6a76-a129-46e7-b94b-315d06ede8bc/objects/hts-cache/new.zip-2019-03-12T20:05:23.316833+00:00" "/var/archivematica/sharedDirectory/watchedDirectories/workFlowDecisions/extractPackagesChoice/700-2019-02TEST-fd0d6a76-a129-46e7-b94b-315d06ede8bc/objects/hts-cache/new.zip"
Command Extracting 7Zip compatible format. failed!
```

Getting to that failure message requires quite a lot of investigative effort by the user.

**Steps to reproduce**

1. Make sure that the processing config is set to extract packages
2. Start a transfer using any of the samples in `TestTransfers/broken_package_format_types` (in the case I was investigating it was a .zip)

**Your environment (version of Archivematica, OS version, etc)**
1.8+, possibly earlier versions as well

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by sevein** [comment]
In the workflow, I think that `1cb7e228-6e94-4c93-bf70-430af99b9264` needs `fallback_job_status` to be set to `Failed` instead of `Completed successfully`.

**Comment by ross-spencer** [comment]
Related to: https://github.com/archivematica/Issues/issues/97

**Comment by evelynPM** [comment]
Just experienced this error in 1.12.0, so it is still happening

**Comment by sevein** [comment]
Superseded by https://github.com/archivematica/Issues/issues/775.
