### ISSUE TITLE
Problem: there is no canonical list of which microservice/job failures cause a transfer to fail

### ISSUE THREAD

**Issue by sallain** [archivematica/Issues#569]
**Version of the documentation**
All

**Page (and section, if applicable) where the issue occurs**
N/A

**Description of the issue**
As users begin to experiment with Archivematica and experience various failures, they often ask which failures are "allowed" (i.e. Archivematica does not stop the transfer from being processed) and which failures kill the transfer altogether. There is no canonical list of the failure result for various jobs.

**Suggested fix**
Make a list! Arguably, it wouldn't even need to be a complete list, just a list of the results of the most common failures that we see in Archivematica.

**Comment by ross-spencer** [comment]
This is a really great addition! Nice work @sarah-mason.
