### ISSUE TITLE
Problem: Not enough logging in Dataverse scripts

### ISSUE THREAD

**Issue by ross-spencer** [archivematica/Issues#57]
**Please describe the problem you'd like to be solved.**

Where Dataverse transfers are still in progress, and some aren't making their way through to ingest, it is useful to have more logging to help users discover what is not working. 

**Describe the solution you'd like to see implemented.**

Additional logging added to the dataverse mets generation script on transfer and parse_dataverse mets further on in the transfer workflow. Additional logging in the Storage Service `locations/models/dataverse` might also make sense for users downloading datasets from the transfer browser.

**Describe alternatives you've considered.**

We could leave this as is, but it does not increase user efficacy. Debug would be reliant on a developer.

**Comment by joel-simpson** [comment]
This issue is not currently connected to a PR, but as you can see from github history, Ross made a commit for it in his dev branch, and I've done some testing and can confirm there are more details being logged in 'convert dataverse structure' as well as 'parse dataverse mets'.
