### ISSUE TITLE
Problem: Archivematica does not fully support Python 3 yet

### ISSUE THREAD

**Issue by sevein** [archivematica/Issues#572]
[ **[:snake:³ Codetree](https://codetree.com/projects/8SEL/board?labels=%3Asnake%3A%C2%B3+Python+3)** ]

**Please describe the problem you'd like to be solved.**
Archivematica's support for Python 3 is not complete.

**Describe the solution you'd like to see implemented.**
Our desire is to increase support in Archivematica v1.10 (mid-2019).
We're aiming to fully support Python 3 before the end of the year since Python 2 will not be maintained past 2020.

**Additional context**
* A decision record is also being written: see [ADR-0004](https://github.com/artefactual-labs/archivematica-architectural-decisions/pull/4).
* @alexwlchan (Wellcome Trust) has created a Python3-compatible fork of python-gearman for Archivematica (see [gearman3](https://github.com/wellcometrust/python-gearman)).
* TravisCI has been used to test against Python 3 since it was set up back in 2017.
* Old branches with some initial work
  * [dev/issue-6079-python3](https://github.com/artefactual/archivematica/tree/dev/issue-6079-python3)
  * [dev/issue-py23-compatibility](https://github.com/artefactual/archivematica/tree/dev/issue-py23-compatibility)
* A lot more has been done already, but there's more to do... [TBC]
* This issue replaces:
  * [Redmine #6079](https://projects.artefactual.com/issues/6079)
  * [Redmine #10564](https://projects.artefactual.com/issues/10564)
* Relationships:
  * Parent of https://github.com/archivematica/Issues/issues/573.
  * Parent of https://github.com/archivematica/Issues/issues/580.
---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by sallain** [comment]
Closed in favour of #805, which uses Codetree epic formatting
