### ISSUE TITLE
Problem: chunkids in manifest file do not match id in DuraCloud

### ISSUE THREAD

**Issue by dcraze** [archivematica/Issues#574]
**Expected behaviour**
The chunkid listed in the manifest and the contentId of that chunk in storage should match.  The DuraCloud Retrieval Tool can then be used to download the file and reassemble it.

**Current behaviour**
The chunkid in the manifest has a leading slash "/" that is not present in the stored chunk; this prevents the DuraCloud Retrieval Tool from being able to use the manifest to reassemble the file

**Steps to reproduce**
Store an AIP in DuraCloud from Archivematica that is larger than 1 GB
Attempt to download the file using the DuraCloud Retrieval Tool - it will fail to find the file chunks

**Your environment (version of Archivematica, OS version, etc)**
1.9 and earlier, Ubuntu 18.04 and earlier

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by sevein** [comment]
Here's a manifest using our development branch:

```xml
<?xml version='1.0' encoding='UTF-8'?>
<dur:chunksManifest xmlns:dur="duracloud.org">
  <header schemaVersion="0.2">
    <sourceContent contentId="/5366/cb16/f3c8/4c90/8ad9/71b6/d44a/af06/20190531104700-5366cb16-f3c8-4c90-8ad9-71b6d44aaf06.7z">
      <mimetype>application/octet-stream</mimetype>
      <byteSize>1316531087</byteSize>
      <md5>f0be6054eb1e076effa209aab2ec85cd</md5>
    </sourceContent>
  </header>
  <chunks>
    <chunk chunkId="/5366/cb16/f3c8/4c90/8ad9/71b6/d44a/af06/20190531104700-5366cb16-f3c8-4c90-8ad9-71b6d44aaf06.7z.dura-chunk-0000">
      <byteSize>1073741824</byteSize>
      <md5>a5b1e093c6b95f5c7478866a29de6be8</md5>
    </chunk>
    <chunk chunkId="/5366/cb16/f3c8/4c90/8ad9/71b6/d44a/af06/20190531104700-5366cb16-f3c8-4c90-8ad9-71b6d44aaf06.7z.dura-chunk-0001">
      <byteSize>242789263</byteSize>
      <md5>a6ddb460f17b6a4a5acef4957593a365</md5>
    </chunk>
  </chunks>
</dur:chunksManifest>
```

This is the error I see when I run the retrieval tool:

```
The Retrieval Tool will exit when processing is complete. Status will be printed every 10 minutes.

Failed to retrieve DuraCloud file 'test-issue-574/5366/cb16/f3c8/4c90/8ad9/71b6/d44a/af06/20190531104700-5366cb16-f3c8-4c90-8ad9-71b6d44aaf06.7z.dura-manifest' after 5 attempts. Last error message was: Calculated checksum value for retrieved file does not match properties checksum.
```

If the problem is a mismatch, shouldn't the error message be different?

I patched my local SS so the IDs do not include the leading slash:

```xml
<?xml version='1.0' encoding='UTF-8'?>
<dur:chunksManifest xmlns:dur="duracloud.org">
  <header schemaVersion="0.2">
    <sourceContent contentId="f09e/dd17/c769/4224/aa08/a28b/0f21/5bab/20190531170939-f09edd17-c769-4224-aa08-a28b0f215bab.7z">
      <mimetype>application/octet-stream</mimetype>
      <byteSize>1316531155</byteSize>
      <md5>0c59eb085aacb72888031945ddcaa374</md5>
    </sourceContent>
  </header>
  <chunks>
    <chunk chunkId="f09e/dd17/c769/4224/aa08/a28b/0f21/5bab/20190531170939-f09edd17-c769-4224-aa08-a28b0f215bab.7z.dura-chunk-0000">
      <byteSize>1073741824</byteSize>
      <md5>8880fae16377fa9a9940a13bc874a64e</md5>
    </chunk>
    <chunk chunkId="f09e/dd17/c769/4224/aa08/a28b/0f21/5bab/20190531170939-f09edd17-c769-4224-aa08-a28b0f215bab.7z.dura-chunk-0001">
      <byteSize>242789331</byteSize>
      <md5>73121e01300d28184c15ca90ae59f417</md5>
    </chunk>
  </chunks>
</dur:chunksManifest>
```

However, I'm seeing a similar error:

```
The Retrieval Tool will exit when processing is complete. Status will be printed every 10 minutes.

Failed to retrieve DuraCloud file 'test-issue-574/f09e/dd17/c769/4224/aa08/a28b/0f21/5bab/20190531170939-f09edd17-c769-4224-aa08-a28b0f215bab.7z.dura-manifest' after 5 attempts. Last error message was: Calculated checksum value for retrieved file does not match properties checksum.
```

So there is definitely a problem impeding the download but I can't see how that's because of a chunk ID mismatch. Our `duracloud.py` has not been altered for a very long time, i.e. the code responsible for doing the uploads has been the same for many releases - so I'm starting to think that the problem must be somewhere else.

**Comment by sevein** [comment]
Update: the retrieval tool works when I download non-chunked AIPs.

**Comment by sevein** [comment]
I've submitted [#462](https://github.com/artefactual/archivematica-storage-service/pull/462) with a few changes (follow the link for more). In my testing, I've observed that the problem seen in the Retrieval Tool disappeared when I added the missing `index` attribute (`<xs:attribute name="index" type="xs:int" use="required"/>`) to the manifest's chunk items.

**Comment by sallain** [comment]
@dcraze are you able to test this?
