### ISSUE TITLE
Problem: README includes a link to an archived repository

### ISSUE THREAD

**Issue by sevein** [archivematica/Issues#579]
In the README, FPR is listed as a related project and the link points to:

    https://github.com/artefactual/archivematica-fpr-admin

The repo is archived. The source code is now part of the Dashboad: https://github.com/artefactual/archivematica/tree/qa/1.x/src/dashboard/src/fpr.

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by ablwr** [comment]
Just noting the README referred to here is this one: https://github.com/artefactual/archivematica

**Comment by ablwr** [comment]
AND this one https://github.com/artefactual/archivematica-storage-service
