### ISSUE TITLE
Problem: Transfer METS does not include Dublin Core metadata

### ISSUE THREAD

**Issue by cole** [archivematica/Issues#586]
**Expected behaviour**

Any Dublin Core metadata associated with a transfer is present in the transfer METS file.

**Current behaviour**

No Dublin Core metadata is present in the transfer METS file.

**Steps to reproduce**

1. Create a new transfer containing Dublin Core metadata and send it to backlog.
2. Examine the transfer METS.xml file and observe the Dublin Core metadata is not present.

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by cole** [comment]
Broken out from #442.

**Comment by sevein** [comment]
I think that we can leave this out for now

The user-provided `metadata.{json,csv}` file is included in the transfer package. After SIP Arrangement, Archivematica imports the metadata of every file (see `copy_transfers_metadata_and_logs` in Ingest and `create_mets_v2`). In https://github.com/artefactual/archivematica/pull/1379, some fixes were made so this is still true when the transfer is a BagIt package.

Package-level metadata introduced via the web interface is now also incorporated in the transfer package when it's sent to backlog - that was also done as part of https://github.com/artefactual/archivematica/pull/1379. It's not clear how package-level metadata is consolidated into one SIP when it's sourced from many transfers, but that's a known limitation that we're not going to address now I believe.

**Comment by sromkey** [comment]
@sevein it's in review but I'm unclear from your last comment if it's been addressed in PR 1379?

**Comment by sromkey** [comment]
We ended up not implementing this in the way originally expected so I'm labelling as Won't Fix. It can always be reopened in the future if needed.
