### ISSUE TITLE
Problem: Transfer METS does not include rights metadata

### ISSUE THREAD

**Issue by cole** [archivematica/Issues#587]
**Expected behaviour**

Any rights metadata associated with a transfer is present in the transfer METS file.

**Current behaviour**

No rights metadata is present in the transfer METS file.

**Steps to reproduce**

1. Create a new transfer containing rights metadata (e.g. from CSV) and send it to backlog.
2. Examine the transfer METS.xml file and observe the rights metadata is not present.

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by cole** [comment]
Broken out from #442.

**Comment by sevein** [comment]
`PREMISRights` added to metsrw v0.3.4.
@cole is working on the writing (`create_transfer_mets`).
@sevein is working on the import (`rebuild_transfer_backlog`, https://github.com/artefactual/archivematica/pull/1379).
