### ISSUE TITLE
Problem: rights basis in Archivematica doesn't include "institutional policy"

### ISSUE THREAD

**Issue by sromkey** [archivematica/Issues#590]
**Please describe the problem you'd like to be solved.**
We generally keep vocabs used in Archivematica consistent with PREMIS vocabularies and the rights basis vocabulary (http://id.loc.gov/vocabulary/preservation/rightsBasis.html) now includes "institutional policy". We have long supported the idea of policy as a rights basis, but because it wasn't in the vocabulary we use "other" and add "policy" as <premis:otherRightsBasis>

**Describe the solution you'd like to see implemented.**
I think it's worth considering adding "institutional policy" to the list of rightsBasis- my only concern is about it being recorded inconsistently across AIPs made using different versions. I'd be interested in hearing from users about this (pinging @bonniegee in case she'd like to give input!)

**Describe alternatives you've considered.**
We could leave it as is and it's not technically wrong, but I'd say less than ideal.

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by bonniegee** [comment]
Thanks for pinging me, @sromkey!

I support Archivematica making this change (adding "institutional policy," removing "other: policy") in order to be in line with the updated vocabulary. In the past, we've always used "other: policy" in cases that match the new "institutional policy:" "A policy decision made by an organization."[1] While there would need to be a way of keeping track of when "policy" became "institutional policy" for AIPs, I think it's still worth the change. 

[1] http://id.loc.gov/ontologies/premis-3-0-0.html#c_InstitutionalPolicy

**Comment by evelynPM** [comment]
We could do this quite easily but it wouldn't have a major impact on the PREMIS output. The reason for this is that the PREMIS Data Dictionary hasn't caught up with the new LOC vocabulary yet - i.e. there are no new semantic units specific to the rightsBasis "Institutional Policy". Currently in Archivematica, the user can select "Policy" as a basis in the data entry template and the PREMIS output looks like this:

![Screenshot from 2019-03-21 13-45-18](https://user-images.githubusercontent.com/14101311/54783818-9fa9b400-4bdf-11e9-897d-f883bc077f83.png)

We could change the term in Archivematica from "Policy" to "Institutional Policy" but that would still result in the PREMIS output using "otherRights" for all the other metadata elements. The only thing that would change would be the value in <otherRightsBasis>.

**Comment by helrond** [comment]
Further to @bonniegee's comment, I think the question for us would be how this change would impact the `rights.csv` file. If there were changes to the structure or allowed values for particular columns we'd have to adjust some of our tooling. That's definitely not a big deal from a development perspective; it's really more of a change management process.

**Comment by sromkey** [comment]
I think I jumped the gun given @evelynPM 's comment that the vocabulary has not actually been adopted by PREMIS yet. I'm going to close this for now but if PREMIS updates its vocabularies we can always re-open.
