### ISSUE TITLE
Problem: documentation needed for Appraisal tab enhancements

### ISSUE THREAD

**Issue by peterVG** [archivematica/Issues#598]
**Version of the documentation**
1.10

**Page (and section, if applicable) where the issue occurs**
Appraisal

**Description of the issue**
Documentation to describe the enhancements introduced in https://github.com/archivematica/Issues/issues/369

**Suggested fix**

**Comment by peterVG** [comment]
updated docs sent to Sara for CR

**Comment by sallain** [comment]
@peterVG it doesn't look like the docs PR is connected here; you can connect them by adding `Connected to archivematica/Issues#598` to a comment in the docs PR.

**Comment by peterVG** [comment]
Connected to archivematica/Issues#598

**Comment by sallain** [comment]
I closed this! @peterVG I know there were screenshots you wanted to add, but judged that the PR was fine without them so I merged. You can always add them later!
