### ISSUE TITLE
Problem: Storage Service: pipeline form's help text for field remote_name is misleading

### ISSUE THREAD

**Issue by hakamine** [archivematica/Issues#604]
**Expected behaviour**
The help text for remote_name should explain that the field accepts a base url, not just the host or IP address

**Current behaviour**
Help text for remote_name says: "Host or IP address of the pipeline server for making API calls."

![Screen Shot 2019-03-25 at 11 08 18 AM](https://user-images.githubusercontent.com/10160634/54943391-64182e00-4eee-11e9-89e8-e20ce14bcccf.png)

This is a problem when Archivematica is configured with https. In this case, if remote_name only contains a host name or IP address in the remote_name field, reingest won't work: the reingest API call from the SS to the pipeline (using http) will receive a 301 (Moved Permanently) response, the SS then will use a GET instead of a POST in the https API call, which will get a 405 error response. The remote_name field actually accepts a base url (e.g. https://amserver.archivematica.org), so it is just matter of changing the help text to make it clear.

**Steps to reproduce**
In the Storage Service, edit a pipeline 

**Your environment (version of Archivematica, OS version, etc)**
AM/SS 1.9.x/0.14.x and qa

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by sromkey** [comment]
This is a small change, putting on the milestone for the 1.10 release.

**Comment by sallain** [comment]
This page of the SS docs should be updated: https://www.archivematica.org/en/docs/storage-service-0.14/administrators/#id2
