### ISSUE TITLE
Problem: 7z (copy) compression isn't represented in storage service

### ISSUE THREAD

**Issue by ross-spencer** [archivematica/Issues#605]
**Expected behaviour**

When the storage service reads a pointer file it can accurately determine the type of compression used by the package.

**Current behaviour**

As `7z with copy` isn't represented in the storage service, the default is to return `7z with bzip`. Though the impact is minimal as the code routes through a more generic 7z command at present.

**Steps to reproduce**

There isn't an easy way to reproduce this, but the code here shows that we never made the corresponding change to the Storage Service when we added `7z (copy)` to the allowed mechanisms. 

https://github.com/artefactual/archivematica-storage-service/blob/d83d383f44dd258f6ba4c1b5a879ca22270e2ae6/storage_service/common/utils.py#L251-L274

*Additional* related to #599 if the compression can't be determined as `copy` then packages will be extracted using `unar` and might fail reingest as a result. 

**Your environment (version of Archivematica, OS version, etc)**

Archivematica `stable/1.9.x`

**Additional context**

Related to https://github.com/archivematica/Issues/issues/493 where a similarly corresponding change would be good.

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by ross-spencer** [comment]
Related: https://github.com/archivematica/Issues/issues/707

**Comment by ross-spencer** [comment]
Hi @sromkey I have added 1.10 as this is resolved through Wellcome's work on 1.10 to add gzip compression to Archivematica. (So the PRs associated with this ticket). Have also placed it into status: review.

**Comment by sallain** [comment]
@ross-spencer can you add notes about how to test?

**Comment by ross-spencer** [comment]
Hi @sallain and @evelynPM in this instance there were no user-facing errors reported. The storage service was able to write the pointer file correctly, it just ran the risk of not being able to read that information back correctly. It could have manifested itself similar to this ticket [here](https://github.com/archivematica/Issues/issues/594#issuecomment-475394072) but we headed it off at the pass, so to speak. As for testing, the only thing I can think of doing is picking a handful of transfers to ingest with copy compression and seeing if reingest initiates correctly (so it will just get to the point where you can approve it in the transfer tab). At that point we know the Storage Service was able to read the original content and extract it correctly. 

The benefit may be minimal, so perhaps it can just be a regression test, transfer vs. transfer and reingest vs. reingest between `1.9` and `1.10`. 

I would suggest recreating the issue in #594 but we don't setup the test instances in the same way and the original server for that one has already been upgraded to a flavor of `1.10`. There's no guarantee copy compression would create the same failure.

**Comment by sallain** [comment]
Thanks @ross-spencer - we can definitely test out the copy compression + reingest, that's easy enough.

**Comment by evelynPM** [comment]
Re-ingest of AIPs created with 7z without compression is working. @ross-spencer is this enough to close the issue?

**Comment by ross-spencer** [comment]
I'd say so @evelynPM :+1:
