### ISSUE TITLE
Problem: Parallel bzip2 compression is failing in am19rpm

### ISSUE THREAD

**Issue by ross-spencer** [archivematica/Issues#606]
**Expected behaviour**

It should be possible to store packages using parallel bzip2 in Archivematica.

**Current behaviour**

Having chatted to @scollazo it seems that there maybe a problem trying to construct a version string when trying to save a pointer file for the package. See the screenshot below:

![image](https://user-images.githubusercontent.com/1880412/54999235-b9743e00-4fc7-11e9-8963-0eca03dd8087.png)

**Steps to reproduce**

Run `DemoTransfer` through am19rpm and try to save as `Parallel Bzip2` and the error should occur.

**Your environment (version of Archivematica, OS version, etc)**

AM 1.9.x.

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by ross-spencer** [comment]
We can this this problem still exists in AM `1.10` as of today:

![image](https://user-images.githubusercontent.com/1880412/67695415-50153d00-f9a5-11e9-81dc-d2c4b357b2ef.png)

**Comment by ross-spencer** [comment]
I have logged into the server today and can see there is no `pbzip2` for RPM to use:
```
[centos@am110rpm ~]$ which pbzip2
/usr/bin/which: no pbzip2 in (/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/centos/.local/bin:/home/centos/bin)
```
After: `[centos@am110rpm ~]$ yum install pbzip2`

We see:
```
[root@am110rpm ~]# which pbzip2
/bin/pbzip2
```
Which also creates the symlink `/usr/bin/pbzip2` 

This allows us to compress the AIP. 

But then we're bumping into a different error at validate:

![image](https://user-images.githubusercontent.com/1880412/67719493-32aa9800-f9d2-11e9-9ff2-5e0468f1ddfe.png)

The files are immediately moved to the Failed directory.

The error:
```
tar (child): bzip2: Cannot exec: Permission denied
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
atool: tar ...: non-zero return-code
Exception('Error extracting AIP',)
Error extracting AIP at "/var/archivematica/sharedDirectory/currentlyProcessing/pbzip2-3-5890e073-f273-4a37-87a5-32b60f606e87/pbzip2-3-5890e073-f273-4a37-87a5-32b60f606e87.tar.bz2"
```
Suggests bzip2 isn't installed on the distribution. And indeed:
```
[centos@am110rpm support]$ bzip2
-bash: bzip2: command not found
```
Once we `yum install bzip2` and attempt the transfer again, everything works as anticipated!

**Comment by ross-spencer** [comment]
Related to https://github.com/archivematica/Issues/issues/253

**Comment by sallain** [comment]
This works on AM 1.x on RPMs - the AIP stored properly and I can download and extract it. I can also access the pointer and METS files as expected.

**Comment by sallain** [comment]
This works on AM 1.x on RPM - the AIP stored properly and I can download and extract it. I can also access the pointer and METS files as expected.
