### ISSUE TITLE
Problem: METSRW component needs documentation

### ISSUE THREAD

**Issue by peterVG** [archivematica/Issues#609]
**Version of the documentation**
1.10

**Page (and section, if applicable) where the issue occurs**
https://github.com/artefactual-labs/mets-reader-writer/tree/master/docs
https://github.com/artefactual-labs/mets-reader-writer#basic-usage
https://github.com/artefactual-labs/mets-reader-writer/wiki

**Description of the issue**

**Suggested fix**

**Comment by sevein** [comment]
@cole has set up readthedocs and cleaned things up a bit.
https://mets-reader-writer.readthedocs.io

**Comment by ross-spencer** [comment]
This is a huge help. Thanks @cole!

**Comment by currmie** [comment]
Might be nice to include a section on how the sponsoring clients intend to use METSRW as part of their workflow; that would also be helpful for other institutions that might be interested once the component is generally available.

**Comment by cole** [comment]
@currmie I'm not sure if anyone outside of Artefactual is intending on using it directly yet. It's been worked on for SFU as part of some enhancements to Archivematica. But, good point, there would be value in adding something to explain what this potentially could be used for.

What's up right now on Read The Docs is mostly just the autogenerated API documentation. I would like to provide some more detail on how to do basic operations for sure before we close this out.

**Comment by currmie** [comment]
Makes sense, thanks @cole !

**Comment by ross-spencer** [comment]
Previous issue from @sevein mets-reader-writer repository: https://github.com/artefactual-labs/mets-reader-writer/issues/30
