### ISSUE TITLE
Problem: Tag and click arrangement breaks with too many tagged files

### ISSUE THREAD

**Issue by replaceafill** [archivematica/Issues#610]
**Expected behaviour**

Create SIP arrangement from tag works with any number of tagged files.

**Current behaviour**

The **tag and click** functionality reuses some of the drag and drop submission logic where each arrangement file is sent individually to the server.

Doing the load testing described in https://github.com/archivematica/Issues/issues/549 we found that attempting to send too many tagged files makes the database to throw `OperationalError: (1040, 'Too many connections') errors`.

The [`copy_to_arrange` view](https://github.com/artefactual/archivematica/blob/df2c90d8cfc5afd5d6ee9336ee33123dca202999/src/dashboard/src/components/filesystem_ajax/views.py#L848) already [accepts lists](https://github.com/artefactual/archivematica/blob/qa/1.x/src/dashboard/src/components/filesystem_ajax/views.py#L856-L857) as parameters so the JS code could gather the files first and submit them all at once.

We may need to change the [`create_directory_within_arrange` view](https://github.com/artefactual/archivematica/blob/df2c90d8cfc5afd5d6ee9336ee33123dca202999/src/dashboard/src/components/filesystem_ajax/views.py#L625) to also accept lists of directories.

**Steps to reproduce**

Explained in https://github.com/archivematica/Issues/issues/549

**Your environment (version of Archivematica, OS version, etc)**

https://github.com/artefactual-labs/am/commit/1ef43a43ddf21268ccbb223f7ad43025f485875b

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by ablwr** [comment]
How many is "too many"?

**Comment by replaceafill** [comment]
@ablwr Sorry I just noticed your question. I tested most of the Appraisal work with the [10,000 files 10,000 directories.tar.7z](https://github.com/artefactual/archivematica-sampledata/blob/master/TestTransfers/10%2C000%20files%2010%2C000%20directories.tar.7z) transfer, but the [1000.zip](https://github.com/artefactual/archivematica-sampledata/blob/master/TestTransfers/1000.zip) one is smaller (and faster) and could be used to test this.

**Comment by ablwr** [comment]
If 1000 is adequate, I tested that and it was okay! I think testing the larger files will need more horsepower than what we currently deploy for our release candidate VMs. I am testing another heavy thing on my local machine and it's taking all day to get it going through, so I'll try to test this bit as well.
