### ISSUE TITLE
Problem: Avalon manifest file should validate prior to processing

### ISSUE THREAD

**Issue by ablwr** [archivematica/Issues#618]
**Please describe the problem you'd like to be solved.**

Avalon Media System depends on a manifest file to reconstruct hierarchical and contextual information, and import metadata to association with a/v files. In a proposed workflow in which files are first processed through Archivematica and then sent to Avalon for access, it would be unfortunate to reach the end of the processing pipeline but have an error in the Manifest CSV. I propose that we create an API endpoint in Archivematica by which a user can validate her Avalon-flavored Manifest file against a validator, which I've conveniently already mapped out and written (https://github.com/artefactual/automation-tools/pull/98).

This is related to and should build a foundation by which it will make issues like https://github.com/archivematica/Issues/issues/563 easier to build out.

**Describe the solution you'd like to see implemented.**

Described in this ADR: https://github.com/artefactual-labs/archivematica-architectural-decisions/pull/6/files

**Describe alternatives you've considered.**

See ADR above.

**Additional context**

This feature request has funding.

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by ross-spencer** [comment]
@ablwr just noting that it looks like the endpoint still needs documenting (for now) on the [API wiki](https://wiki.archivematica.org/Archivematica_API). Is it worth a new ticket while this one is in review?

**Comment by ablwr** [comment]
Thanks @ross-spencer! I was waiting for this to be merged. I'll add the docs right now.
