### ISSUE TITLE
Problem: dead code path in Review DIP from Store DIP job

### ISSUE THREAD

**Issue by sevein** [archivematica/Issues#62]
There is some code in place that attempts to show a "Review" button during "Store DIP" but it's broken. I've also been told that it can be removed because the reviewing is only useful when reviewing the contents after upload, i.e. job "Move to the uploadedDIPs directory".

This is at least true in qa/1.x: 729bda77b784c2f246f12e647e9ecd042cbe3836.

**Comment by sallain** [comment]
See #76 for an example of the confusion that this problem can cause.

**Comment by sromkey** [comment]
This is working as expected although DIPs don't appear to be copied to the uploadedDIPs directory when they should be... which I assume is a separate issue so I'll file that now.
