### ISSUE TITLE
Problem: black-box AMAUATs start the same transfer before each scenario

### ISSUE THREAD

**Issue by replaceafill** [archivematica/Issues#622]
**Expected behaviour**

An AIP based on the `DemoTransferCSV`sample transfer is completed once and reused by all the scenarios in the `@black-box` features.

**Current behaviour**

Each `black-box` scenario starts with the step `Given an AIP has been created and stored` which completes an AIP based on the `DemoTransferCSV`sample transfer.

The step always starts a new transfer with the same sample data and processing configuration every time it's called from an scenario making the test runs inefficient.

**Steps to reproduce**

Execute any of the `@black-box` feature tests.

**Your environment (version of Archivematica, OS version, etc)**

https://github.com/artefactual-labs/archivematica-acceptance-tests/commit/d4b81246b4292c8e7c950d3dbaaad23c8cc26584

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by ross-spencer** [comment]
Hi there @replaceafill preparing for the `1.10` release of the AMAUAT tests, can I verify that this issue can be moved into `review` or perhaps even `done` and closed?

**Comment by replaceafill** [comment]
Thank you @ross-spencer. I think we can move this to `Done`.

**Comment by ross-spencer** [comment]
Completed as part of our work with @wellcometrust
