### ISSUE TITLE
Problem: fixity app hardcoded to http rather than https

### ISSUE THREAD

**Issue by sromkey** [archivematica/Issues#63]
reported by @axfelix in fixity repo:

Probably fixable (I'll open a PR myself later this week), but we have this running on a server that was recently redeployed with https and it's now throwing

    Unable to connect to storage service instance at http://localhost:8000/ (is it running?)

**Comment by amayita** [comment]
I think this is fixed.
/etc/default/fixity allows for http or https url configuration.
