### ISSUE TITLE
Archivematica should pin exact package versions in requirements.txt for predictable deployments

### ISSUE THREAD

**Issue by alexwlchan** [archivematica/Issues#634]
**Please describe the problem you'd like to be solved.**
The current approach to dependency management is a collection of `requirements.txt` files that specify some top-level package boundaries, but don’t specify exact versions or transitive dependencies. For example:

https://github.com/artefactual/archivematica/blob/da59178679954f3fc496da538901234f987e99d4/src/archivematicaCommon/requirements/test.txt

```
-r base.txt

mock
pytest>=2,<3
pytest-django>=2,<3
pytest-pythonpath
tox
vcrpy>=1,<2
```

This means that if you build Archivematica using a Dockerfile (which is what we're doing at Wellcome), we'd get different versions on different days, depending on whether the package authors have released a new version. This can make debugging harder, because we're not working with a stable system.

This requirements file is a set of *top-level dependencies*. Archivematica should also have a `requirements.txt` that precisely pins the versions installed, so we can track changes to them.

**Describe the solution you'd like to see implemented.**
We're using [pip-tools](https://github.com/jazzband/pip-tools) to manage this in the Wellcome repo. See https://github.com/wellcometrust/archivematica/tree/wellcome-storage-service/src/archivematicaCommon/requirements

We rename the existing file to `.in`, e.g. `base.in`. Then we run `pip-compile`, which produces a list of exact versions, including all the transitive dependencies, and names that `base.txt`. That's what we use when building our Docker images.

**Describe alternatives you've considered.**
I've used pip-tools before, and it only deals with the requirements.txt files – otherwise you can keep using vanilla pip. I prefer this to tools like poetry or pipfile because it's a less intrusive change to the development process.

**Additional context**
We already have code for this working, and I'd be happy to PR it back if you think it's useful (or have an alternative you'd prefer.

Part of https://github.com/wellcometrust/platform/issues/3535

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by cole** [comment]
👍 on this from me, I think @alexwlchan has laid out the argument for build stability which is very important.

I would also be in favour of moving to a [Pipfile and Pipfile.lock](https://pipenv.readthedocs.io/en/latest/), but that is more work. Pinning versions is required anyways and a good first step.

I believe we're using [Pyup](https://pyup.io/) in other projects (it submits automatic update PRs, [like this one](https://github.com/CCA-Public/scope/pull/113) to update the pinned versions and it's working well.
