### ISSUE TITLE
Problem: documentation unclear on difference between "default" and "standard" AIP/DIP storage locations

### ISSUE THREAD

**Issue by sromkey** [archivematica/Issues#635]
**Version of the documentation**
1.7 and higher

**Page (and section, if applicable) where the issue occurs**
Ingest- Store AIP
and possibly- Archival Storage- storing the AIP
(side note, we may not need both of those sections?)

Access - Store DIP

**Description of the issue**
In the drop down when you choose an AIP storage location, you are in a default installation offer Default Location and Store in Standard Archivematica Directory. This is confusing to users.

**Suggested fix**
Clarify the usage of Default Location- it is designated in the Storage Service and may be the "Standard Archivematica Directory," or may be another location as decided by the Storage Service administrator.

**Comment by ThomasEdvardsen** [comment]
This also applies to the DIP location.

**Comment by sromkey** [comment]
Right you are @ThomasEdvardsen , I've edited to reflect that!

**Comment by sallain** [comment]
Resolved by archivematica/Issues#297
