### ISSUE TITLE
Problem: Version of METS in mets-reader-writer is an older version 1.11 vs. 1.12 (metsrw)

### ISSUE THREAD

**Issue by ross-spencer** [archivematica/Issues#637]
**Expected behaviour**

METS validation in mets-reader-writer should be done against the latest standard. 

**Current behaviour**

METS.xsd in mets-reader-writer is currently [`1.11`](https://github.com/artefactual-labs/mets-reader-writer/blob/bc6a6e1e4c7278e722170a128dfed618b17a47c7/metsrw/resources/mets.xsd#L21-L26) (May 2015) at the time of writing.

Currently mets.xsd from the Library of Congress is [`1.12`](https://github.com/mets/METS-schema/blob/3961fd2a9ff895104160088cdd3c8ceb7f153e54/mets.xsd#L21-L26) (May 2018).

**Options**

* Update the static file?
* Create a git submodule and update that periodically? 
* Something else? 

Related to https://github.com/archivematica/Issues/issues/245 

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by cole** [comment]
Good find! To start with I'd vote to just to update the static file — submodules have a bit of complexity overhead, and it doesn't seem like the METS XSD changes too often.

**Comment by ross-spencer** [comment]
Sounds good - thanks @cole - I might be able to get to this as part of my current work, so can approach it like that given the opportunity.

**Comment by ross-spencer** [comment]
Related to https://github.com/archivematica/Issues/issues/949

**Comment by sallain** [comment]
In #949 @evelynPM confirmed that both the transfer and AIP METS refer to the correct version of the schema; the METS files otherwise look fine. Is there anything else we need to look for to test this?

**Comment by replaceafill** [comment]
@sallain I'd say testing #949 is enough. The new "static file" mentioned in the first couple of comments here is now [updated](https://github.com/artefactual-labs/mets-reader-writer/blob/a82b873624b3865ac0f4ecea5366e647b83c483f/metsrw/resources/mets.xsd#L28) in the `metsrw` code.
