### ISSUE TITLE
Problem: documentation doesn't describe set up for DSpace as AIP storage location

### ISSUE THREAD

**Issue by sromkey** [archivematica/Issues#64]
**Please describe the problem you'd like to be solved.**

In the Storage Service documentation, there is a description of how to set up a DSpace Space, but no details on how to make an AIP storage location. There are some DSpace-specific details that should be documented in order to do that successfully.

**Additional context**

I am referring to the DSpace AIP storage workflow as it exists in 1.6.x and 1.7.x- there may be additional documentation required after changes from University of Edinburgh are merged into 1.8.x.

**Comment by sallain** [comment]
@romkey do you think that this was adequately addressed in artefactual/archivematica-storage-service-docs#14? You can see the changes in the SS docs [here](https://www.archivematica.org/en/docs/storage-service-0.13/administrators/#dspace-via-rest-api)

**Comment by ablwr** [comment]
I think this is fulfilled by the above-mentioned PR
