### ISSUE TITLE
Enhancement: Allow post store DIP callbacks in Storage Service

### ISSUE THREAD

**Issue by jraddaoui** [archivematica/Issues#641]
**Please describe the problem you'd like to be solved.**

See the related ADR: https://github.com/artefactual-labs/archivematica-architectural-decisions/pull/7/files

**Describe the solution you'd like to see implemented.**

To be discussed in the ADR process.

**Describe alternatives you've considered.**

Included in the ADR.

**Additional context**

Included in the ADR.

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by helrond** [comment]
see also #147

**Comment by jraddaoui** [comment]
Closed in favor of #147.
