### ISSUE TITLE
Problem: It's not easy to inspect the METS file once a package has been ingested

### ISSUE THREAD

**Issue by ross-spencer** [archivematica/Issues#644]
**Please describe the problem you'd like to be solved.**

As a developer I would like access to the METS file from the package without having to download the package. Often it is the contents of the METS that is most interesting to me and not the content of the AIP. 

**Describe the solution you'd like to see implemented.**

Similar to how users can access pointer files from the Archival Storage page associated with the package, it would be great to create a button to download the METS from the package as well.

**Describe alternatives you've considered.**

We could write a helper function for AM Client specifically enabling the extract of METS using the extract file capability recently developed. 

**Additional context**

An artifact of testing. But maybe it has some merit. 

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by sromkey** [comment]
I would like this as an archivist/analyst/tester too!!!

**Comment by bonniegee** [comment]
Chiming in to say I would find this really useful too!

**Comment by jraddaoui** [comment]
Hi all,

It's not a button, but there is a Storage Service API endpoint that could be used to extract and download just the METS file from an AIP:

```
<ss_url>/api/v2/file/<aip_uuid>/extract_file/?relative_path_to_file=<aip_name>-<aip_uuid>/data/METS.<aip_uuid>.xml
```

Alternatively, if you have a DIP created for the AIP, you can also download the METS file from it using the same endpoint. In this case, it will skip the extraction step as DIPs are always stored uncompressed (at the moment):

```
<ss_url>/api/v2/file/<dip_uuid>/extract_file/?relative_path_to_file=<aip_name>-<aip_uuid>/METS.<aip_uuid>.xml
```

Both require authorization but, as long as you're logged in the SS interface, session auth. will also work to download the METS through the browser.

The initial part of the relative path is usually `<aip_name>-<aip_uuid>`, but it can be checked in the current location path from the packages tables or in the following URL for each package:

```
<ss_url>/api/v2/file/<package_uuid>?format=json
```

I hope this helps!

**Comment by ross-spencer** [comment]
@sromkey for triage later, this one I think slipped through the tracking in Codetree (mainly because of my use of labels).

**Comment by sallain** [comment]
:sparkling_heart: MAGICAL :sparkling_heart: 

I've tested this in qa on Bionic and it works wonderfully for both newly-created AIPs and AIPs that already existed on the server before it was updated to include this enhancement.
