### ISSUE TITLE
Problem: when starting a transfer, Archivematica deletes (or attempts to delete) the files in the transfer source location

### ISSUE THREAD

**Issue by hakamine** [archivematica/Issues#646]
**Expected behaviour**
When starting a transfer, Archivematica shouldn't delete files in the transfer source location (it should just copy the transfer source files from the transfer source location to the processing directory)

**Current behaviour**
When starting a transfer, Archivematica attempts to move the transfer source files from the transfer source location to the processing directory, thus deleting the files from the transfer source location (when some conditions are fulfilled, ref. below)

**Steps to reproduce**
- Have a transfer source location with the following two conditions:
  - The transfer source location is in the same filesystem as the processing directory
  - File permissions of the transfer source files are such that Archivematica can read/write them (e.g., set the file owner of the transfer source files to user archivematica)
- Start a transfer
- After the transfer has started, the transfer source files are not in the transfer source location anymore

**Your environment (version of Archivematica, OS version, etc)**
AM 1.9/ SS 1.4

**Additional information**
This problem didn't occur in AM1.7, it started to happen when updating a server from 1.7 to 1.9

When starting a transfer, Archivematica attempts to move (instead of copying) the transfer source files using `locations.models.space:space:posix_move()` as shown in the SS logs:

<pre>
DEBUG     2019-04-07 14:49:20  locations.models.space:space:posix_move:282:  posix_move: source_path: var/archivematica/dspace_ready_to_ingest/ITEM@1828-1579.zip
DEBUG     2019-04-07 14:49:20  locations.models.space:space:posix_move:283:  posix_move: destination_path: /var/archivematica/sharedDirectory/tmp/tmp3AHl8o/ITEM@1828-1579.zip
DEBUG     2019-04-07 14:49:20  locations.models.space:space:posix_move:284:  posix_move: destination_space.path: /
INFO      2019-04-07 14:49:20  locations.models.space:space:move_rsync:481:  Moving from /var/archivematica/dspace_ready_to_ingest/ITEM@1828-1579.zip to /var/archivematica/sharedDirectory/tmp/tmp3AHl8o/ITEM@1828-1579.zip
</pre>

In case the transfer source files are not deleted, it is because the move operation failed (because of permissions, different filesystems, etc):
<pre>
INFO      2019-04-09 15:04:07  locations.models.space:space:move_rsync:481:  Moving from /home/artefactual/transfers/Images/. to /var/archivematica/sharedDirectory/tmp/tmpi4021X/images2/.
DEBUG     2019-04-09 15:04:07  locations.models.space:space:move_rsync:495:  os.rename failed, trying with normalized paths
DEBUG     2019-04-09 15:04:07  locations.models.space:space:move_rsync:504:  os.rename failed, falling back to rsync. Source: /home/artefactual/transfers/Images; Destination: /var/archivematica/sharedDirectory/tmp/tmpi4021X/images2
INFO      2019-04-09 15:04:07  locations.models.space:space:move_rsync:511:  rsync command: ['rsync', '-t', '-O', '--protect-args', '-vv', '--chmod=Fug+rw,o-rwx,Dug+rwx,o-rwx', '-r', '/home/artefactual/transfers/Images/.', '/var/archivematica/sharedDirectory/tmp/tmpi4021X/images2/.']
</pre> 

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by sallain** [comment]
@scollazo do any of the current 1.10 test sites match the conditions that cause this failure?

* The transfer source location is in the same filesystem as the processing directory
* File permissions of the transfer source files are such that Archivematica can read/write them (e.g., set the file owner of the transfer source files to user archivematica)

If not, can you replicate the above conditions on am110xenial?

**Comment by sromkey** [comment]
ping @scollazo ^ :)

**Comment by scollazo** [comment]
Verified this on am110bionic, closing
