### ISSUE TITLE
Problem: AMAUAT black box scenarios repeat the set up steps

### ISSUE THREAD

**Issue by replaceafill** [archivematica/Issues#649]
**Expected behaviour**

The black box feature files are as simple as possible.

**Current behaviour**

The scenarios in the three feature files repeat their `Given` and `When` steps like this:

```
    ...
    Given an AIP has been created and stored
    When the AIP is downloaded
    Then the physical structMap of the AIP METS accurately reflects the physical layout of the AIP
    ...
    Given an AIP has been created and stored
    When the AIP is downloaded
    Then every object in the AIP has been assigned a UUID in the AIP METS
    ...
```

These could be grouped together in a single scenario or scenario outline.

**Steps to reproduce**

See the [current black-box feature files](https://github.com/artefactual-labs/archivematica-acceptance-tests/tree/d4b81246b4292c8e7c950d3dbaaad23c8cc26584/features/black_box)

**Your environment (version of Archivematica, OS version, etc)**

https://github.com/artefactual-labs/archivematica-acceptance-tests/commit/d4b81246b4292c8e7c950d3dbaaad23c8cc26584

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by ross-spencer** [comment]
Completed as part of our work with @wellcometrust. [Epic here](https://github.com/archivematica/Issues/issues/467).
