### ISSUE TITLE
Problem: sampledata is missing some dirs at gitignore file

### ISSUE THREAD

**Issue by mamedin** [archivematica/Issues#65]
**Please describe the problem you'd like to be solved.**

After running `make simple` or `make all` these directories are not included in the `.gitignore` file

```
artefactual@mamedin-test:~/archivematica-sampledata$ git status
On branch master
Your branch is up-to-date with 'origin/master'.
Untracked files:
  (use "git add <file>..." to include in what will be committed)

	TestTransfers/dirs_with_various_encodings/
	TestTransfers/sample-zip-packages/

nothing added to commit but untracked files present (use "git add" to track)
```

**Describe the solution you'd like to see implemented.**

Adding these directories to the `.gitignore` file fixes the issue.

**Comment by sromkey** [comment]
Moved to verified and re-opened just for Waffle purposes.

**Comment by sromkey** [comment]
Looks like maybe this wasn't qa'd so adding it to the 1.8 milestone
