### ISSUE TITLE
Problem: detailed metadata implementation information is in the wiki

### ISSUE THREAD

**Issue by sallain** [archivematica/Issues#652]
**Version of the documentation**
All

**Page (and section, if applicable) where the issue occurs**
N/A

**Description of the issue**
There is a lot of [detailed metadata implementation information](https://wiki.archivematica.org/Metadata_elements) in the wiki, rather than the documentation. The wiki is difficult to navigate and, more importantly, is not a place we usually recommend people go to if they're trying to learn more about Archivematica

**Suggested fix**
Move this information to the documentation.

**Comment by sallain** [comment]
@sarah-mason This one might be of interest to you.

**Comment by sarah-mason** [comment]
@sallain @sromkey  - I have taken a look into the metadata elements section and have a few proposals that I would like your opinions on.

Metadata Elements subsections in wiki:

- **METS**
Referenced in the documentation, propose to move it to the Metadata section of the docs, https://www.archivematica.org/en/docs/archivematica-1.10/#metadata

- **PREMIS metadata: original files**
- **PREMIS metadata: normalized files**
- **PREMIS metadata: events**
I am less certain of what to do with these three sections, but the first two are tables of PREMIS elements found in original files and normalized files. The second lists 14 PREMIS events, each as a separate table. I do not think that is a comprehensive list, but it does explain a fair bit. It is possible that these could be moved to the section above where PREMIS rights are explained. The PREMIS section could have separate pages for these sections, but I am not entirely sure what the policy is on having so many subsections and .rst files.

- **PREMIS metadata: rights - 0.10**
I recommend deletion of this as we already have a new version of this in the docs.

- **PREMIS/METS for scalability**
- **RDF/OWL**
As already suggested by Ross in his spreadsheet of the wiki, I also think these two might be better as ADR(s). This would probably have to be logged as a separate issue in that case. But I don’t think the docs are the right place for it live.

**Comment by sromkey** [comment]
Regarding PREMIS metadata for events and files, we have functionality coming in 1.11 to import PREMIS events in xml format so it seems like a good opportunity to rethink how it is described in the docs.

**Comment by sallain** [comment]
@sarah-mason I agree with your suggestions, and like @sromkey think it would be a good time to rethink the `premis.rst` page. Frankly, it needs a good overhaul - `premis.rst` was last updated two years ago. Having a complimentary `mets.rst` page makes sense to me.

The PREMIS docs are definitely not up to date ([this page was last updated in 2011!](https://wiki.archivematica.org/PREMIS_metadata:_original_files)), and I suspect it will take considerable time to get them there. But I also think it would be okay to have an admonition on the docs page saying that this is a WIP since it's not describing user functionality, per se.

As an organizational note, my instinct would be a page for each metadata standard and how it is implemented, with sections for different facets of the implementation. I think you could decide, for PREMIS, if the original/normalized/events/rights breakdown makes sense. Presenting tables in the AM docs is not too bad - you can create a CSV and add it to a folder, then call it in the body of the RST page, just like adding an image. For an example, the table at [step 2 here](https://www.archivematica.org/en/docs/archivematica-1.10/user-manual/transfer/import-metadata/#adding-descriptive-metadata-to-a-directory) comes from [this CSV file](https://github.com/artefactual/archivematica-docs/blob/1.10/user-manual/transfer/_csv/directory-metadata.csv). The formatting is kind of weird on the page but it's functional. Same goes for code snippets - see the [scripts directory here](https://github.com/artefactual/archivematica-docs/tree/1.10/user-manual/transfer/scripts).

The style guide says to be cautious about adding new RST files - we have a lot already - but metadata is definitely an area where we could expand. I think you should be bold in reorganizing it!
