### ISSUE TITLE
Problem: create_dip in automation-tools does not work with PREMIS3 AIPs

### ISSUE THREAD

**Issue by ablwr** [archivematica/Issues#653]
**Expected behaviour**

create_dip.py in automation-tools should create a DIP. It's in the name!

**Current behaviour**

create_dip.py makes a package of some sort, with some things zipped inside, but inside are no objects.

**Steps to reproduce**

Using qa/1.10x, configure automation-tools and run create_dip. Unzip the package and see what is in there.

**Your environment (version of Archivematica, OS version, etc)**

Ubuntu 18.04 by way of Docker, qa branch (post-1.9.1, pre-1.10).

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by ablwr** [comment]
I believe the solution for this is to update metsrw in automation-tools and update the METS parsing within this script. It is the upgrade to PREMIS 3 that is causing files to not be found and added to the DIP package, because it is currently expecting and working with PREMIS 2.2.

**Comment by ablwr** [comment]
This is related to work done for #370.

**Comment by jraddaoui** [comment]
Hi @ablwr, this should be fixed now, would you like to give it a try? Thanks!

**Comment by ablwr** [comment]
yes!

**Comment by ablwr** [comment]
This is working well for me. I have to update the script in #107 so I'll be doing more testing, but this seems successful.
