### ISSUE TITLE
Problem: SS object_counting_disabled option fails

### ISSUE THREAD

**Issue by mamedin** [archivematica/Issues#657]
**Expected behaviour**

When this option (Administration>Settings second checkbox) is enabled in the Archivematica Storage Service, the number of files and sizes are not shown when listing the transfer sources in the dashboard.

**Current behaviour**

The dashboard shows all the transfer sources crossed and cannot select any directory.

**Steps to reproduce**

Enable it on SS and list transfers in the dashboard.

**Your environment (version of Archivematica, OS version, etc)**

Tested with AM1.9.1 and CentOS 

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by mamedin** [comment]
We need to confirm this option is explained in documentation.

**Comment by mamedin** [comment]
Workaround:

<pre>[root@am19centos archivematica-storage-service]# git diff storage_service/locations/models/space.py
diff --git a/storage_service/locations/models/space.py b/storage_service/locations/models/space.py
index c9b9189..7ef1f22 100644
--- a/storage_service/locations/models/space.py
+++ b/storage_service/locations/models/space.py
@@ -699,6 +699,7 @@ def path2browse_dict(path):
         full_path = os.path.join(path, name)
         properties[name] = {'size': os.path.getsize(full_path)}
         if utils.get_setting('object_counting_disabled', False):
+            directories.append(name)
             properties[name]['object count'] = '0+'
         elif os.path.isdir(full_path) and os.access(full_path, os.R_OK):
             directories.append(name)
</pre>

**Comment by ross-spencer** [comment]
Great spot @mamedin! Confirmed in the Docker environment too:

![image](https://user-images.githubusercontent.com/1880412/56289234-c1378600-6120-11e9-8a38-831b94c76927.png)

**Comment by sallain** [comment]
This works great.

**Comment by sallain** [comment]
@mamedin actually... is this an expected consequence of this feature? Everything has a 4KB size?

![Screenshot of Archivematica Dashboard - Transfer.jpg](https://codetreeusercontent.s3.amazonaws.com/uploads/9feb6f9e-9d82-416d-8259-d07cb8737dfe/Screenshot+of+Archivematica+Dashboard+-+Transfer.jpg)

**Comment by sallain** [comment]
Looks beautiful now!
