### ISSUE TITLE
Problem: MCPClient deploy still contains libxml2-utils

### ISSUE THREAD

**Issue by ross-spencer** [archivematica/Issues#658]
**Expected behaviour**

When we install dependencies we are only installing what is absolutely needed by Archivematica.

**Current behaviour**

Because of the changes in #283 we may no longer need to be explicit about installing libxml2-utils.

The libxml2-utils package is still installed via [here](https://github.com/artefactual/archivematica/blob/stable/1.9.x/src/MCPClient-base.Dockerfile#L49), [here](https://github.com/artefactual/archivematica/blob/a67d9d30832a313e49a8242d869739690b35e86c/src/MCPClient/osdeps/Ubuntu-18.json#L31) And [here](https://github.com/artefactual/archivematica/blob/a67d9d30832a313e49a8242d869739690b35e86c/src/MCPClient/osdeps/Ubuntu-16.json#L31)

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by ross-spencer** [comment]
Hi @sromkey adding `1.10` milestone as this was maintenance work that was a result of the custom structmap feature development: https://github.com/archivematica/Issues/issues/283 and was resolved in PR #1409.

**Comment by sallain** [comment]
@ross-spencer how can this be tested?

**Comment by ross-spencer** [comment]
Hi @sallain one way to do this would be to `ssh` into the deployment, and try and run `xmllint`. On my personal machine where it is installed still, I get this output: 
```
$ xmllint --version
xmllint: using libxml version 20904
   compiled with: Threads Tree Output Push Reader Patterns Writer SAXv1 FTP HTTP DTDValid HTML Legacy C14N Catalog XPath XPointer XInclude Iconv ICU ISO8859X Unicode Regexps Automata Expr Schemas Schematron Modules Debug Zlib Lzma 
```
But you would see that the command cannot be found. 

It was previously used for the microservice job: `Job Verify mets_structmap.xml compliance` but there wasn't a lot of output that would indicate this utility was being used vs. the replacement.

**Comment by sallain** [comment]
I get `xmllint: not found` errors so I'm going to go ahead and assume that this one is done :slightly_smiling_face:

**Comment by ross-spencer** [comment]
Errors FTW!
