### ISSUE TITLE
Problem: PREMIS Events generated during re-ingestion have only one Agent

### ISSUE THREAD

**Issue by evelynPM** [archivematica/Issues#659]
**Expected behaviour**
A PREMIS Event generated during re-ingestion should have three Agents.

**Current behaviour**
The Event shows links to three Agents but only one of the Agents is captured in the amdSec. This means that the Event is linking to two non-existent Agents.

![Screenshot from 2019-04-18 10-25-27](https://user-images.githubusercontent.com/14101311/56379828-83d90400-61c5-11e9-95e4-1fa7821ec6a7.png)

**Steps to reproduce**
Generate an AIP and place it in archival storage. Re-ingest the AIP.

**Your environment (version of Archivematica, OS version, etc)**
Tested on sandbox and AM demo

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by sevein** [comment]
Similar solution recently added to Ingest: https://github.com/artefactual/archivematica/commit/8d7807e8928a14249dbf7595e8f12773d89f931a.

**Comment by sevein** [comment]
I've tried in several ways but I haven't been able to reproduce in our 1.10 dev branch.

@evelynPM, could you please try to reproduce on a recent instance and/or share more instructions on how to reproduce it?

**Comment by evelynPM** [comment]
Evelyn to test on a 1.10-dev VM once one becomes available.

**Comment by evelynPM** [comment]
I reproduced this error on http://am110bionic.qa.archivematica.net. I created an AIP, then logged in as a different user, changed the PREMIS Agent and reingested the AIP. The new Agents were not created, but there were links to them in the new Events.

**Comment by sromkey** [comment]
@evelynPM I've tested but am not totally confident in the results. In [this METS](https://gist.github.com/sromkey/8043da179ce39ac526c17021d159ab42) which I have reingested as a different user, it looks like the agents for the repository and software (and initial user) are before the reingestion/deletion events, and the new user (the one who did the reingesting and deleting) are after. Is that ok?

**Comment by evelynPM** [comment]
Yes, that's fine. I tested again as well, logging in as a new user and changing the PREMIS Agent name and code before re-ingesting. The updated Agents were added to the amdSec.
