### ISSUE TITLE
Problem: It looks like create_event.py is an unused script in Archivematica

### ISSUE THREAD

**Issue by ross-spencer** [archivematica/Issues#665]
**Expected behaviour**

The Archivematica project doesn't need to maintain scripts that are unused.

**Current behaviour**

If I look for references to [create_event.py](https://github.com/artefactual/archivematica/blob/stable/1.9.x/src/MCPClient/lib/clientScripts/create_event.py) it seems unused in any other part of the system. see this search [result](https://github.com/artefactual/archivematica/search?q=create_event&unscoped_q=create_event). 

This should be easy enough to get a second opinion on and then remove from the code base. 

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by sevein** [comment]
It's used in quarantine, unquarantine and removal from backlog. I think that GH's search results are a bit unreliable matching contents in larger files like `workflow.json` - best to use git grep or similar.

**Comment by ross-spencer** [comment]
I see. Thanks @sevein. Closing this one out.
