### ISSUE TITLE
Problem: We haven't GitHub templates for releases (minor/point releases)

### ISSUE THREAD

**Issue by ross-spencer** [archivematica/Issues#667]
**Please describe the problem you'd like to be solved.**

Releases should be as consistent as possible. 

**Describe the solution you'd like to see implemented.**

_This is really just a formalization of work already started by folks like @sallain and @sevein and chatting to @scollazo in Slack seems to be a potentially good idea to push forward with a little more._ 

We have the possibility to use issues templates with GitHub, this form is an example of one. Issues templates are stored [here in this repository](https://github.com/archivematica/Issues/tree/master/.github/ISSUE_TEMPLATE). 

We also have an example of a 'major' Archivematica [release checklist](https://github.com/archivematica/Issues/issues/582)

And a [point release checkslist](https://github.com/archivematica/Issues/issues/581).

It would be great if we could round out these forms with all the information needed, and possibly expectations, e.g. clarification of expectations around [versioning](https://github.com/archivematica/Issues/issues/662#issuecomment-485832015). And then when a new release is on the horizon we have everything we need to create a new issue and select a template from the GitHub template to create a release quasi-epic.  

**Describe alternatives you've considered.**

We could do this ad-hoc per release, but we have tools that can help, so they might be a better approach.

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by sromkey** [comment]
This has sort of been in the back of my mind so I'm going ahead and assigning myself.
