### ISSUE TITLE
Problem: Storage service sort by size does not increment correctly

### ISSUE THREAD

**Issue by ablwr** [archivematica/Issues#678]
**Expected behaviour**

If I am sorting by size in the Storage Service, the files should rank themselves in by-biggest or by-smallest incrementing order.

**Current behaviour**

Sorting is happening based on the first number -- so 1.1GB is considered "smaller" than 1.5 MB, which is "smaller" than 105.7 MB.

See picture for example of what I mean:

![Screenshot from 2019-05-07 16-31-02](https://user-images.githubusercontent.com/3260492/57331038-b485cc80-70e5-11e9-9afd-44cde602423b.png)

**Steps to reproduce**

Add files of various sizes, taking care to add files that will be intentionally confusing to the system (like described above). Sort by size under "Packages" in the AM-SS. 

**Your environment (version of Archivematica, OS version, etc)**

RedHat 1.8.1

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by corinnemrogers** [comment]
Sort by size in the storage service is implementing correctly.
