### ISSUE TITLE
Problem: devtools repo is hard to maintain and Py3 incompatible

### ISSUE THREAD

**Issue by sevein** [archivematica/Issues#68]
And as a result, mostly broken, i.e. it works only against specific versions of Archivematica.
Related issue: https://github.com/artefactual/archivematica-devtools/issues/43.

> Much of the work done in this repo is based on interfaces that are not public APIs, e.g. graph-links accesses to the database and expect connection parameters to be located at a certain location - in this case the simplest compromise is to convert it into a django-admin command of the main app in the dashboard because that's where the models live and the dashboard knows how to access to the database. Each devtool has its own story so they'll have to be revisited individually.

My suggestions:
1. Update devtools repository with a deprecation warning and link to our maintenance tools docs.
2. Archive the repository.
3. Find the right place for each of the commands in devtools - see list below.

---

You can find the list here: https://github.com/artefactual/archivematica-devtools/tree/master/tools

### NO ACTION NEEDED - it's already part of Archivematica Dashboard

- graph-links
- json-links (never meged into devtools, lived in a branch)
- rebuild-elasticsearch-aip-index-from-files
- rebuild-transfer-backlog

### Move to fpr app

- add-format (it's an alias to add-fpr-rule)
- add-fpr-rule
- get-fpr-changes
- import-pronom-ids

### It's abandoned, could be removed

- linktool

This tools is not used anymore since now we're writing [migrations](https://github.com/artefactual/archivematica/tree/stable/1.7.x/src/dashboard/src/main/migrations) using Django's migration system. We're also working on pulling the workflow data from the database (see https://github.com/artefactual/archivematica/issues/1101).

### It should become part of Archivematica Dashboard

- mcp-rpc-cli
- create-many-transfers
- extract-mets-files-from-aips
- gearman-info
- rebuild-elasticsearch-aip-index-from-mets-files-only
- reindex-backlogged-transfers
- reindex-index-data
- stress-test-aip-indexing
- sword-diagnose

Some of the may not be needed anymore?

### It should be provided by packages/ansible

- restart-elasticsearch-if-down
- restart-services
- services

We should probably replace the three tools listed above with a Python script that is compatible with all the distros supported (related issue: https://github.com/artefactual/archivematica-devtools/issues/36) and it's installed by packages/ansible so it's available to the user without extra installation steps. It should also be able to run manage.py commands too (related issue: https://github.com/artefactual-labs/am-packbuild/issues/157).

**Comment by ross-spencer** [comment]
Hi @sevein with something like the RPC Client, do we have to consider the impact on behavior as well, i.e. right now, it is possible to dial into Gearman remotely on the right port and still perform the same function. With a Django management command, does this change to have to ssh into the dashboard? And is that preferable? Does it also impact the ability for someone else (or ourselves) to write a separate client to perform those functions? Just a few thoughts and questions as we figure out what maintenance of this set of utilities looks like.

**Comment by sevein** [comment]
That's a good point @ross-spencer, `mcp-rpc-cli` will require special treatment. It makes little sense to implement it as Django command. One option is to extend amclient (automation-tools) so it provides the same functionality but to access `getJobsAwaitingApproval` and `approveJob` remotely we'd need to implement the corresponding API endpoints in the Dashboard. A first iteration could use `/mcp/{list,execute}/` (used today by our JavaScript) but they're not part of the API and require form/cookie-based authentication so it's not ideal - I'd probably just go and add the API endpoints.

**Comment by sevein** [comment]
I've added the 1.13 milestone since devtools runs on Python 2. It should be possible make it Python 3 compatible but in the spirit of what this issue was trying to achieve, I suggest to:
* Archive the https://github.com/artefactual/archivematica-devtools repository,
* Provide alternative to mcp-rpc-cli as a Django management command (implementation details could be different but purpose should remain),
* Stop installing devtools from https://github.com/artefactual-labs/ansible-archivematica-src (qa/1.x)
* Remove devtools package from https://github.com/artefactual-labs/am-packbuild/search?q=devtools
* Remove mentions to devtools in https://github.com/artefactual/archivematica-docs/search?q=devtools
