### ISSUE TITLE
Problem: Storage Service doesn't support LDAP

### ISSUE THREAD

**Issue by sromkey** [archivematica/Issues#680]
**Please describe the problem you'd like to be solved.**
While the dashboard can be integrated with LDAP for user authentication, the Storage Service cannot. In some environments this is required. 

**Additional context**
This may be required for the NHA project.

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by cole** [comment]
We have a few options for providing LDAP authentication:

- Via [Shibboleth](https://www.shibboleth.net/). Shibboleth is already supported by Storage Service and can be configured with LDAP as an identity provider. This wouldn't require any code changes (in theory), but would probably be a significant amount of operations work. Also, I'd imagine there are probably a lot of users who already have an LDAP server, but are not running Shibboleth.
- Via nginx's [nginx-ldap-auth](https://github.com/nginxinc/nginx-ldap-auth). This would require some configuration of nginx on the operations side, and that we run an additional LDAP daemon process. In Storage Service, we'd have to add support for the auth headers provided by nginx (currently we only support Shibboleth specific ones), and probably write a [custom Django user backend](https://docs.djangoproject.com/en/1.8/topics/auth/customizing/#writing-an-authentication-backend).
- Via [django-auth-ldap](https://django-auth-ldap.readthedocs.io/en/latest/index.html). This is currently used in the dashboard, and seems to be mostly a matter of installing and configuring. Note that the latest version we can use currently is 1.3 (1.4+ requires Django 1.11).

I'd recommend we go with django-auth-ldap; it's the simplest option to maintain, and it's consistent with the Archivematica dashboard implementation.

**Comment by cole** [comment]
Two important points that I missed in my analysis:

 * Using django-auth-ldap for both storage service and the dashboard would require configuring LDAP settings in two places, which could be burdensome.
* Using nginx-ldap-auth for both storage service and the dashboard would allow users to sign in once for both services (SSO), a potentially large usability benefit.

Given those two items, I think the choice between django-auth-ldap and nginx-ldap-auth is less clear and probably merits more discussion.

**Comment by joel-simpson** [comment]
thanks @cole there are some interesting options there. 

I wonder if single-sign-on (SSO) is really a large usability benefit. Yes you have to login twice; but you are logging in with your standard user credentials. So it's still a good improvement over today (where you have to maintain identical username / password manually in both systems, or remember different credientials). And many Archivematica users don't need to log into storage service very often (or at all). 

So I'd lean towards django-auth-ldap approach for the sake of simplicity. That doesn't preclude using Shibboleth for those users who are happy with the extra configuration and maintenance required. 

But it would good to get input from an operations perspective... I believe @luisilara has some experience trouble-shooting LDAP configuration for users. Perhaps @dcraze has some thoughts too?

**Comment by luisilara** [comment]
Based on my last experience implementing ldap in archivematica I personally think django-auth-ldap would be a good choice,  nginx-ldap-auth seems to be simpler to implement however I haven't done any extensive research on this method yet but I found some points that I consider  django-auth-ldap is a good choice:

- We have a working setup on one of our clients and is working properly so far
- Fairly easy to setup once you have the correct server credentials ;) the easiest setup would be to add 4 env variables to accomplish this
- It looks like is more secure than the nginx-ldap-auth  which uses only base64 to scramble the credentials (still need to confirm this is the only method of encryption) vs django that can use TLS
- One point of configuration for the dashboard and the storage server using nginx-ldap-auth is simpler however sometimes we install the dashboard and the storage server in separate vm's which means that we will have to configure LDAP in two places (I could be wrong on this one)
- I learned that you can highly customize nginx-ldap-auth by creating your own multiple LDAP configurations and subclassing the backend https://django-auth-ldap.readthedocs.io/en/latest/custombehavior.html https://django-auth-ldap.readthedocs.io/en/latest/multiconfig.html 

I still need to understand more nginx-ldap-auth mechanisms but hope this helps a little

**Comment by sallain** [comment]
@dcraze is there a way to test this?

**Comment by dcraze** [comment]
@sallain We could test it with our office LDAP server if we had to.  Setting up a test LDAP would probably be better and something we need to do in the long run.

**Comment by mamedin** [comment]
It works fine. I tested with TLS and artefactual LDAP. Good job :)
