### ISSUE TITLE
Support zipped transfers

### ISSUE THREAD

**Issue by helenst** [archivematica/Issues#682]
**Please describe the problem you'd like to be solved.**
Archivematica currently supports transfers in the form of an unzipped directory, a zipped bag or an unzipped bag. We would like to be able to transfer from a plain (non-bagged) zipfile as this is the format in which our archives are likely to be provided.

**Describe the solution you'd like to see implemented.**
An zipfile option in the transfer type dropdown, which allows a zipfile to be selected and transferred

**Describe alternatives you've considered.**
The alternative would be for archivists to provide files in an unzipped directory format, but this would be less than optimal for their workflow, and it seems like this would be a useful feature for Archivematica.

**Additional context**
PR incoming :)

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by sromkey** [comment]
Hi @helenst a couple of questions...
- is a transfer type necessary? Could Archivematica just allow you to choose a zipped package as a Standard transfer?
- Do you propose supporting any type of zipped package or a specific one?
- The closest analogy being the zipped bag transfer, which doesn't allow the user to enter a transfer name (not actually sure why, it's a long history!) Do you propose the same idea here?
Thanks for the interesting idea!

**Comment by helenst** [comment]
Hi @sromkey
1. This would require Archivematica to allow zipfiles to be selected rather than greyed out under the standard transfer option, and presumably also add support to extract it. It seems to me that it's more in keeping with existing zipped/unzipped bag options to provide another transfer type but it's probably worth discussing which is best.
2. It would support the same set of compressed file types as the zipped bag feature (so gzips and anything that 7z can handle)
3. In my current implementation, I've followed the pattern of the zipped bag transfer so transfer name not required.

**Comment by sromkey** [comment]
@helenst Can you remind me if you are still requiring this functionality?

**Comment by helenst** [comment]
@sromkey Yes, we do still need this - we have it in our fork currently and are using it :-)

**Comment by evelynPM** [comment]
I think that following the workflow for zipped bag is the way to go here:
-Use the zipped package name as the transfer name
-Extract the contents immediately (not later in processing the way zipped packages within other transfer types are treated)
-Delete the original zipped package when contents have been extracted
-Create an ingestion premis event for each extracted file
-Do not create an unpacking premis event for each file
In the long term my preference would be to have only 1 transfer type which could handle both bag and non-bag zipped packages, but that development would more complex and it is not essential to this feature

**Comment by sromkey** [comment]
I agree with Evelyn's points above. In the future we could leverage this discussion into reducing the number of transfer types by having Archivematica detect whether or not something is a bag but that seems like scope-creep for this particular feature.

@helenst what do you think about implementing Evelyn's suggestions?

**Comment by helenst** [comment]
@sromkey I think this PR already implements the described workflow as far as I can tell. We unzip the transferred zipfile and then treat the contents the same way as a standard transfer - rather than treating it the same way as a zipfile that happens to be a file *within* a transfer.

Having the upload capable of detecting whether it is a bag sounds like a good idea for a future release.

**Comment by sromkey** [comment]
That sounds great @helenst !

**Comment by ross-spencer** [comment]
Moving into `review` thanks to all the help today! Thanks Sarah and Alex! Sample-data and docs in the associated PRs above.

**Comment by sallain** [comment]
I have just tried testing this and, alas, it hangs immediately (at a place I've never seen something hang before, so that's exciting, I guess.) @ross-spencer I used your zipped directory sampledata, specifically Images.tar.gz

[Screenshot of Archivematica Dashboard - Transfer.jpg](https://codetreeusercontent.s3.amazonaws.com/uploads/8bbfed0f-5ae8-47bb-a779-5cc3c4de8c5a/Screenshot+of+Archivematica+Dashboard+-+Transfer.jpg)

**Comment by ross-spencer** [comment]
Thanks @sallain I have confirmed this on Xenial too. I can confirm that this is also specific to the `Images.tar.gz` sample, the other two in the sample set [here](https://github.com/artefactual/archivematica-sampledata/tree/master/SampleTransfers/ZippedDirectoryTransfers#zipped-directory-sample-transfers) look okay. So, something about the interaction with the extract packages microservice and the `tar.gz` here itself. I'll investigate. **NB.** the sample-data needs to be updated on the testing servers for this sample data to appear, I thought it was part of the update job, but it might not be. Let me know if you want me to do that from the shell if it helps.

**Comment by sallain** [comment]
Gonna call this done! Tested on qa/1.x in all environments.
