### ISSUE TITLE
Problem: processing hangs in automation tools because UUID for ingest is missing in the Sqlite database

### ISSUE THREAD

**Issue by ross-spencer** [archivematica/Issues#690]
> From time to time the UUID is missing in the Sqlite database. Automation Tools will never get an update on the status for this unit since the UUID is missing and then constructs an api-call which is not valid.

Moved from the original ticket here: [automation-tools/issues#110](https://github.com/artefactual/automation-tools/issues/110)

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by ross-spencer** [comment]
There is a possibility that this is being caused by the logic in [this view](https://github.com/artefactual/archivematica/blob/qa/1.x/src/dashboard/src/components/api/views.py#L187-L201), and the automation-tools (I'd need to double check) triggering a new transfer based on status `COMPELTE` but not itself waiting for a `sip_uuid`. 

@replaceafill noticed this recently in the automated testing that we've been doing, and for all the states the endpoint tries to return information on, a consumer could find itself not updating its own state if it relies on the endpoint returning `COMPLETE` and doesn't continue polling until a `sip_uuid` is made available. 

This may impact the automation-tools. I should also look to see if it affects the automatic reingest code, cc. @scollazo which is part of the automation tools repository. 

I have made a note about how to use the status endpoint in the API [wiki page](https://wiki.archivematica.org/Archivematica_API#Status).

cc. @ThomasEdvardsen

**Comment by ross-spencer** [comment]
A quick note as I was just wondering this today, but when the transfer has been sent to `BACKLOG` its status looks as follows:
```json
{
"status": "COMPLETE",
"name": "21",
"sip_uuid": "BACKLOG",
"microservice": "Move transfer to backlog",
"directory": "21-4bab3e54-6423-48dd-849c-ddb7f068a23a",
"path": "/var/archivematica/sharedDirectory/watchedDirectories/SIPCreation/completedTransfers/21-4bab3e54-6423-48dd-849c-ddb7f068a23a/",
"message": "Fetched status for 4bab3e54-6423-48dd-849c-ddb7f068a23a successfully.",
"type": "transfer",
"uuid": "4bab3e54-6423-48dd-849c-ddb7f068a23a"
}
```

**Comment by ThomasEdvardsen** [comment]
Looking at this right now @ross-spencer . Is it best to check for sip_uuid length of 36 then?

**Comment by ross-spencer** [comment]
Ah, that's a very good point @ThomasEdvardsen! I could think of a few approaches approximating that, but understand @replaceafill is looking at this so will perhaps leave him to comment on what he's considering.

**Comment by ThomasEdvardsen** [comment]
I am not sure how long it takes before the sip_uuid are available @ross-spencer.
Would it make sense to replace [this](https://github.com/artefactual/automation-tools/blob/ae0428c4d3ac0d4796aca3cd783aea385150c0f8/transfers/transfer.py#L114-L119) code with:

```
    if (
        unit_info
        and unit_type == "transfer"
        and unit_info.get("status") == "COMPLETE"
        and unit_info.get("sip_uuid") != "BACKLOG"
    ):

        while unit_info.get("sip_uuid") is None:
            time.sleep(2)
```

**Comment by ThomasEdvardsen** [comment]
Have done a first PR for this now.
https://github.com/artefactual/automation-tools/pull/112

**Comment by ross-spencer** [comment]
Nice work @ThomasEdvardsen, I've let @replaceafill know and hopefully it shouldn't take too long to CR. Thanks for taking the time to submit a fix!

**Comment by replaceafill** [comment]
We haven't seen this in CI anymore after removing the `sip_uuid` check and changing the status endpoint to wait until a file is created on the unit.
