### ISSUE TITLE
Problem: Scan for viruses not being triggered after remove from quarantine

### ISSUE THREAD

**Issue by ross-spencer** [archivematica/Issues#691]
**Expected behaviour**

When a user removes a transfer from quarantine, it then moves to the scan for viruses microservice job. 

**Current behaviour**

It moves to identify file format instead missing scan for viruses. 

**Steps to reproduce**

1. Set AM to quarantine a transfer. 
2. Set remove from quarantine to `0` days.
3. Start a standard transfer, or another, e.g. bag transfer.
4. Given the option to remove the transfer from quarantine, do so. 
5. Observe the result. 

![image](https://user-images.githubusercontent.com/1880412/57787587-f4782f80-7735-11e9-88ee-dd85b387533a.png)

**Your environment (version of Archivematica, OS version, etc)**

https://sandbox.archivematica.org/transfer/, also seeing this in my `qa/1.x` dev environment.

**Additional context**

A sanity check is always welcome on this one, I don't use quarantine often so my workflow might not be right. 

Related to https://github.com/artefactual/archivematica/issues/598
---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by ross-spencer** [comment]
This is the screenshot from amflow for the standard transfer: 

![image](https://user-images.githubusercontent.com/1880412/57789557-7a49aa00-7739-11e9-885b-363fc425c6af.png)

**Comment by sallain** [comment]
Confirmed in qa/1.x as well (prior to 1.10 release).

Instead of fixing this, it has been proposed that we deprecate quarantine as it is dubiously useful.

**Comment by ross-spencer** [comment]
Related to https://github.com/artefactual/archivematica/issues/598 specifically, describing the complexity of the workflow at present https://github.com/artefactual/archivematica/issues/598#issuecomment-372423112.

**Comment by sromkey** [comment]
We're removing quarantine in 1.11 which can be done against issue #598, so I'm marking this one as Won't Fix.
