### ISSUE TITLE
Problem: AIP README file has overly detailed and inaccurate information about AIP METS structMAP

### ISSUE THREAD

**Issue by evelynPM** [archivematica/Issues#692]
**Expected behaviour**
the README file should accurately describe the contents of the AIP.

**Current behaviour**
The README file currently reads " As of Archivematica version 1.8, all AIP METS files contain a logical structural map which lists all files and directories including empty directories. The physical structural map accurately documents the final directory structure of the AIP. Because AIPs conform to the BagIt specification and because bags cannot contain empty directories, the logical structural map labelled "Normative Directory Structure" indicates how the AIP should be structured when the empty directories are reconstructed." 

However, AIPs without empty directories don't have the logical structMap, so the first sentence is inaccurate. Also, since there may be different structMaps added for different kinds of AIPs, this level of detail is problematic.

**Recommended change**
Suggested replacement wording "All AIP METS files contain a default physical structMap and may contain additional structMaps, either physical or logical, depending on the structure of the AIP."

**Your environment (version of Archivematica, OS version, etc)**

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by sallain** [comment]
@sevein or @ross-spencer or @ablwr or @cole - to address this, is it just this file that needs to be edited? https://github.com/artefactual/archivematica/blob/stable/1.9.x/src/MCPClient/lib/assets/README/README.html

**Comment by cole** [comment]
@sallain correct!

**Comment by evelynPM** [comment]
Fixed by https://github.com/artefactual/archivematica/pull/1423.
