### ISSUE TITLE
Problem: Centos upgrade doc is misleading, leading to failure when running dashboard migration

### ISSUE THREAD

**Issue by mamedin** [archivematica/Issues#699]
**Version of the documentation**

1.9.1

**Page (and section, if applicable) where the issue occurs**
https://www.archivematica.org/en/docs/archivematica-1.9/admin-manual/installation-setup/upgrading/upgrading/#upgrade-centos

Step 5.

**Description of the issue**

Running the doc command fails:

```sudo -u archivematica bash -c " \
    set -a -e -x
    source /etc/default/archivematica-dashboard || \
        source /etc/sysconfig/archivematica-dashboard \
            || (echo 'Environment file not found'; exit 1)
    cd /usr/share/archivematica/dashboard
    /usr/share/archivematica/virtualenvs/archivematica-dashboard/bin/python manage.py migrate --no-input
";
```
It works fine when removing the last string: "--no-input"

**Suggested fix**

Change to the CentOS dashboard migrate command to:

```

sudo -u archivematica bash -c " \
    set -a -e -x
    source /etc/default/archivematica-dashboard || \
        source /etc/sysconfig/archivematica-dashboard \
            || (echo 'Environment file not found'; exit 1)
    cd /usr/share/archivematica/dashboard
    /usr/share/archivematica/virtualenvs/archivematica-dashboard/bin/python manage.py migrate
";
```

**Comment by jorikvankemenade** [comment]
I have opened a PR for this issue. If anyone is available for a quick review than this should be an easy fix :).

**Comment by mamedin** [comment]
Thanks @jorikvankemenade :)

**Comment by ablwr** [comment]
Seems resolved? Please re-open if not!
