### ISSUE TITLE
Problem: JSON->CSV metadata conversion has bugs

### ISSUE THREAD

**Issue by jrwdunham** [archivematica/Issues#7]
Various bugs:

1. A JSON object value cannot be a number (int or float). If it is, `encode_item` will raise an uncaught exception.
2. If a JSON object is missing attributes that another one has, or if different JSON objects have corresponding values that are arrays with different lengths (or where one is an array but the other is a string), then the generated CSV will have mixed up columns. For a concrete example, consider the following user-supplied JSON:

       [
           {
               "dc.creator": ["Jim Bob"],
               "parts": "objects/",
               "dc.contributor": ["Sally Bean", "Nancy Pumpkin", "Mary Pea"],
               "dc.title": "A thing"
           },
           {
               "dc.creator": ["Frank Mills", "Sunny McRainbow"],
               "parts": "objects/filezilla.mfo",
               "dc.contributor": "Lucifer"
           }
       ]

   Currently, the CSV returned for this JSON will be:

       parts,dc.contributor,dc.contributor,dc.contributor,dc.creator,dc.creator,dc.title
       objects/,Sally Bean,Nancy Pumpkin,Mary Pea,Jim Bob,A thing
       objects/filezilla.mfo,Lucifer,Frank Mills,Sunny McRainbow

   <img width="646" alt="csv-actual" src="https://user-images.githubusercontent.com/2504271/42654307-08d39b46-85cd-11e8-9258-0db62ed2fd64.png">

   However, we should expect it to be:

       parts,dc.contributor,dc.contributor,dc.contributor,dc.creator,dc.creator,dc.title
       objects/,Sally Bean,Nancy Pumpkin,Mary Pea,Jim Bob,,A thing
       objects/filezilla.mfo,Lucifer,,,Frank Mills,Sunny McRainbow,

   <img width="672" alt="csv-expected" src="https://user-images.githubusercontent.com/2504271/42654308-08eab358-85cd-11e8-9da9-f315cb3d33b3.png">

**Note: a JSON object (and the equivalent CSV file) will both result in a METS file that contains empty elements:**

    <mets:dmdSec ID="dmdSec_2">
      <mets:mdWrap MDTYPE="DC">
        <mets:xmlData>
          <dcterms:dublincore xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:dcterms="http://purl.org/dc/terms/" xsi:schemaLocation="http://purl.org/dc/terms/ http://dublincore.org/schemas/xmls/qdc/2008/02/11/dcterms.xsd">
            <dc:contributor>Sally Bean</dc:contributor>
            <dc:contributor>Nancy Pumpkin</dc:contributor>
            <dc:contributor>Mary Pea</dc:contributor>
            <dc:creator>Jim Bob</dc:creator>
            <dc:creator/>
            <dc:title>A thing</dc:title>
          </dcterms:dublincore>
        </mets:xmlData>
      </mets:mdWrap>
    </mets:dmdSec>
    <mets:dmdSec ID="dmdSec_3">
      <mets:mdWrap MDTYPE="DC">
        <mets:xmlData>
          <dcterms:dublincore xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:dcterms="http://purl.org/dc/terms/" xsi:schemaLocation="http://purl.org/dc/terms/ http://dublincore.org/schemas/xmls/qdc/2008/02/11/dcterms.xsd">
            <dc:contributor>Lucifer</dc:contributor>
            <dc:contributor/>
            <dc:contributor/>
            <dc:creator>Frank Mills</dc:creator>
            <dc:creator>Sunny McRainbow</dc:creator>
            <dc:title/>
          </dcterms:dublincore>
        </mets:xmlData>
      </mets:mdWrap>
    </mets:dmdSec>

**Comment by peterVG** [comment]
Using the JSON file provided above on AM18.qa.bionic

![screen shot 2018-10-25 at 15 13 50](https://user-images.githubusercontent.com/672121/47533493-c948f400-d868-11e8-84bb-78d427befa5a.png)

it generates the correct metadata.csv during Transfer and includes it in the AIP.

![screen shot 2018-10-25 at 15 14 29](https://user-images.githubusercontent.com/672121/47533550-01e8cd80-d869-11e8-8d94-7e2a9fec79ba.png)
