### ISSUE TITLE
Directory creation error during move_or_merge

### ISSUE THREAD

**Issue by helenst** [archivematica/Issues#704]
**Expected behaviour**
If there's a nested directory in the destination directory of `move_or_merge` that matches one in the source directory, it should use the existing directory rather than failing.

**Current behaviour**
If there's a nested directory in the destination directory of `move_or_merge` that matches one in the source directory, it causes an error attempting to create the directory (since it already exists) and fails the workflow. (Original issue: https://github.com/wellcometrust/platform/issues/3509)

**Steps to reproduce**
We ran into this on occasions when Archivematica was redeployed (so services were restarted) during a transfer - some steps were re-run and this caused errors during move_or_merge when it was re-run and the destination directory already existed. There may be other ways to reproduce it too.

**Your environment (version of Archivematica, OS version, etc)**
Archivematica 1.9 (based on qa/1.x branch) using the docker compose environment.

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by replaceafill** [comment]
This was tested as part of https://github.com/archivematica/Issues/issues/1018
