### ISSUE TITLE
Problem: jhove output not added to METS in some versions

### ISSUE THREAD

**Issue by ablwr** [archivematica/Issues#705]
**Expected behaviour**

JHOVE validation report should be stored in the METS for each file within `<filestatus>` ... or maybe it actually should be `<premis:eventDetail>`? I'm not sure, but it's not storing in either most of the time, but sometimes under `<filestatus>`.

See related: https://github.com/archivematica/Issues/issues/524 (and I suppose investigation here will explain when/where this functionality lapsed)
Also a little bit related: https://github.com/archivematica/Issues/issues/164

**Current behaviour**

METS stores an empty, self-closing `<filestatus/>` in Archivematica qa/1.10.x, Archivematica 1.9.2 on Bionic, Archivematica 1.9.2 on Xenial. I am also seeing this behavior in AM 1.8 on Xenial.

Information stores as expected in Archivematica 1.9.2 on CentOS, 1.8/CentOS versions.

**Steps to reproduce**

- Navigate to an Archivematica on Bionic or Xenial, version 1.9.2
- Run a transfer
- Search for `filestatus` in METS

**Your environment (version of Archivematica, OS version, etc)**

AM1.9.2/Bionic

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by ablwr** [comment]
JHOVE changed their XML output namespace, so our FPR script must be updated as well, to match.

Assuming this and related issues will bring us to a latest JHOVE, the script will have to change from this line:
`status = doc.find('.{http://hul.harvard.edu/ois/xml/ns/jhove}repInfo/{http://hul.harvard.edu/ois/xml/ns/jhove}status')`
to this one:
`status = doc.find('.{http://schema.openpreservation.org/ois/xml/ns/jhove}repInfo/{http://schema.openpreservation.org/ois/xml/ns/jhove}status')`

And similarly in two lines below, for format and version.

**Comment by ablwr** [comment]
This seems resolved and covered by tested the above related items, so I am going to close this and consider it done.

**Comment by ross-spencer** [comment]
Hi @ablwr I believe this should keep the `1.10` milestone and remain open (`status: review`), and will be closed when the `1.10` milestone is resolved. If there is a specific commit that resolves this, or PR that does so then it would also be useful to the reader to reference it with the commit hash or the connected to keyword.
