### ISSUE TITLE
Problem: wording in compression algorithm choices is confusing

### ISSUE THREAD

**Issue by evelynPM** [archivematica/Issues#707]
**Expected behaviour**
Wording in configuration options presented to end-users should be as clear as possible.

**Current behaviour**
It's a minor issue but the wording for selecting 7z without compression has the word "copy" added to it, which is confusing to the user. Apparently that's because it invokes 7z in copy mode, but that's a detail that I think the user doesn't need to know.

![compression](https://user-images.githubusercontent.com/14101311/58290266-024d3680-7d6e-11e9-9b9d-1e2081a1c1ce.png)

**Steps to reproduce**
Go to the administration tab and edit the config settings. The wording appears in the drop-down menu for "Select compression algoirthm"

**Your environment (version of Archivematica, OS version, etc)**

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by evelynPM** [comment]
Added a triage release 1.10 label because this could be very quick fix with no downstream impact.

**Comment by ross-spencer** [comment]
@sromkey I was in this section of the code today for a Wellcome review. It's just a 2x line change, https://github.com/artefactual/archivematica/pull/1422/files so i put a quick PR against it. Can we put it into `1.10`?
