### ISSUE TITLE
Problem: Travis doesn't run linkcheck on documentation

### ISSUE THREAD

**Issue by sallain** [archivematica/Issues#708]
**Please describe the problem you'd like to be solved.**
Sphinx has a nice little feature called [linkcheck](http://www.writethedocs.org/guide/tools/testing/#link-testing) that will test out all the external links in the documentation and spit out a report of all the errors. It's helpful, but requires users to remember to run it manually.

**Describe the solution you'd like to see implemented.**
Include linkcheck as part of the standard Travis CI build for documentation.

Linkcheck is pretty heavy-handed so the fail conditions would need to be considered; we use some dummy links that get caught, for example. As per @ross-spencer's comment in #630, it's possible to create exclusion regex patterns to ignore certain links: http://www.sphinx-doc.org/en/1.2/config.html#confval-linkcheck_ignore.

See also this PR for more examples where valid links get caught by linkcheck: https://github.com/artefactual/archivematica-docs/pull/275

**Describe alternatives you've considered.**

**Additional context**
Originally filed by @ross-spencer as https://github.com/artefactual/archivematica-docs/issues/169

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by eviau-artefactual** [comment]
I believe that linkcheck is not available as a pre-commit... but I tried adding it to the tests here: https://github.com/artefactual/archivematica-docs/pull/433

**Comment by eviau-artefactual** [comment]
The linkcheck was implemented in https://github.com/artefactual/archivematica-docs/pull/439

It should work starting for versions 1.15 and up.

Thank you for filing this issue :sparkles:
