### ISSUE TITLE
Allow user to choose whether they receive fail report emails

### ISSUE THREAD

**Issue by bonniegee** [archivematica/Issues#709]
**Please describe the problem you'd like to be solved.**
We have several users with Dashboard logins on both our development and production environments. These users need to maintain their logins, but do not need to know every time a transfer fails--often failure is a result of testing another user is performing, or part of a project most users are not on. This is a particular problem in our development instance, where transfers fail more frequently, but is an issue our our production instance as well.

**Describe the solution you'd like to see implemented.**
I would like to see a checkbox on user profile pages (those viewed by individual users as well as admin users when managing other accounts) for whether they receive fail report emails.

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by sromkey** [comment]
Great idea- this has been identified as a pain point a number of times on the user forum.

**Comment by helrond** [comment]
I took a quick look at this today and have a couple of thoughts, but it would probably be good for someone more familiar with the codebase to weigh in on this.

It looks like there are two different reports Archivematica emails:
- fail reports: `src/MCPClient/lib/clientScripts/email_fail_report.py`
- normalization reports: `src/MCPClient/lib/clientScripts/normalize_report.py`

While both of these are HTML emails, the normalization report uses a template which wraps the report in some pretty UI elements, while the fail report seems more barebones. This means there are two places where the recipients queryset is created.

So if I'm understanding this correctly, I think there are a couple of ways of addressing this. All of them involve adding a boolean field to the User model and making the necessary adjustments in the views and templates. However, there's a range of other things that can be done:
- Perhaps the "simplest" fix would be to simply update the User queryset filters. This would need to be done in two different files
- This would also be an opportunity to factor out an abstract `send_system_email` function which could be called from multiple scripts.
- Some halfway steps might also be possible (creating a `get_system_email_recipients`) helper function, etc.

I'd be interested in hearing thoughts on these approaches. Depending on how involved this work is, I would be interested in submitting a PR.

**Comment by sevein** [comment]
Hi @helrond,

> - This would also be an opportunity to factor out an abstract send_system_email function which could be called from multiple scripts.
> - Some halfway steps might also be possible (creating a get_system_email_recipients) helper function, etc.

I like both. I'd probably go with the latter since smaller increments are usually safer and it doesn't touch on the topic of what should be the standard template that Archivematica uses which may be a longer discussion.

Should `get_system_email_recipients` be a `User` manager method? I usually feel unsure whether that's a good approach.

**Comment by helrond** [comment]
Thanks @sevein! According to the [Django docs](https://docs.djangoproject.com/en/2.2/topics/db/managers/#adding-extra-manager-methods), it does seem like model manager methods are the preferred way of doing this. I'll start working on this.

**Comment by sromkey** [comment]
Adding a label to triage for 1.11 because we're nearing code freeze for 1.10 (no pressure @helrond ;) )

**Comment by helrond** [comment]
I thought this one was going to be relatively easy but...alas! I assumed that the Archivematica already had a custom user model which overrides the default `django.contrib.auth.models.User` but it appears that is _not_ the case. That means, unless I am missing out on something, that adding a BooleanField for system email delivery as well as a manager method will actually be pretty invasive, and require substantial changes to forms and views. My understanding is that switching from the base `User` to a customized model is a non-trivial change to make once initial migrations have been run.

Archivematica does have a `UserProfile` model, but it seems like that's only used to link a `User` to an `Agent`, and is exclusively interacted with via Django signals (ie there don't appear to be any views or forms which touch this model). 

One (distasteful) option I've considered is introducing a new `UserOptions` (or similar) model that could be tied to a `User` via a OnetoOne field. That's a lot of overhead for one field though (and it doesn't AT ALL help to reduce existing complexity, it just makes it several degrees worse) so I'm really not thrilled by that idea.

Would be curious to hear if I'm missing something and/or if there are thoughts on other strategies to pursue!

**Comment by sevein** [comment]
> My understanding is that switching from the base User to a customized model is a non-trivial change to make once initial migrations have been run.

I think that it's a good investment since it would also enable us to add other functionality tailored to user preferences that we could add to Archivematica in the future, e.g. dashboard visualization, notifications or authentication settings.

I'm going to ping @cole since he's touched on many advanced topics in Django.

**Comment by helrond** [comment]
I agree that it could be a good investment of time, and I think _might_ also help to reduce some existing complexity a bit. That said, the [Django docs](https://docs.djangoproject.com/en/2.1/topics/auth/customizing/#changing-to-a-custom-user-model-mid-project) do indicate that this is a complex process, and honestly not one I'm convinced I'm qualified to take on.

**Comment by cole** [comment]
> My understanding is that switching from the base User to a customized model is a non-trivial change to make once initial migrations have been run.

@helrond  I think you're correct here: at this point switching to a custom user model (using a new database table) would require updating quite a few relations.

I think the solution I'd recommend here is extending the existing `UserProfile` model — it seems a bit pointless to me as is (why not just link `Agent` directly to the `User`? There is probably a reason that I'm missing) but even though it's not really used much, I don't think extending it should be harder than adding a new model. This approach would mean:
1. Adding a new boolean field to UserProfile
2. Creating a migration
3. Updating the querysets you've identified to filter on the new field
4. Changing the existing `ApiKeyForm` into a `UserProfileForm` or something similar (or adding a new one if that's easier) and adding a checkbox form field for failure report emails. This will also require changes to the `profile` view.

To me if we add a new `UserOptions` model, that is seems similar to `UserProfile` and could be a source of confusion in future. We could name the new model `NotificationOptions` or similar to avoid that, but I'm still not sure that's better than just adding the field to the existing model.

**Comment by helrond** [comment]
Thanks @cole - I was on this track earlier but was missing step 4. I think this makes sense as an approach. 

And I share your bafflement about what the `UserProfile` model is actually doing that a database field couldn't do...

**Comment by sallain** [comment]
This is working perfectly! If I deselect "Send system emails?", I do not get an email. I can also receive an email even if I'm not an administrator. Tested on qa/0.x on Bionic.
