### ISSUE TITLE
Feature: Add new api endpoint for AIP Migration

### ISSUE THREAD

**Issue by ablwr** [archivematica/Issues#71]
I would like to see this API endpoint for AIP migration added into the Storage Service's main codebase. This work was attempted before (see below) but the Storage Service has changed significantly since then, and this work could be done in a more optimal way. The interface and the endpoint can (and should) remain the same, but SS has advanced in its async capabilities and this endpoint especially should reflect that, as it is used to migrate very large AIPs and can be time-intensive.

I am not sure whether it's better to rebase the below PR or to start from scratch on this work -- I guess it depends on how much SS has changed between 0.7.x and current 0.11.x

Previous PR: https://github.com/artefactual/archivematica-storage-service/pull/143
Previous-previous PR: https://github.com/artefactual/archivematica-storage-service/pull/130
History of work: https://github.com/artefactual/archivematica/pull/366

Adding link to automation-tool script used in production at MoMA just for reference: https://github.com/artefactual/automation-tools/blob/qa/moma-storage-move-endpoint/storage/move_packages.py

**Comment by ablwr** [comment]
Maybe related is Issue #24

**Comment by jambun** [comment]
Hi @ablwr,

I have a first pass reimplementation up at:
https://github.com/hudmol/archivematica-storage-service/tree/dev/issue-71-move-aip-endpoint

There's definitely more to do, but it works for my simple test case.


Cheers,
James

**Comment by ablwr** [comment]
Hey great, thanks James!

I'm in a bit of a limbo but should have a new machine where I can set up a dev environment coming to me on Wednesday, so for now all I can review is the code, which reads pretty clearly to me. I still have a whole lot to learn about the codebase in general and how to test edge cases and weird situations though!

**Comment by jambun** [comment]
Hi again @ablwr - I've just pushed a couple more commits to the branch:
https://github.com/hudmol/archivematica-storage-service/tree/dev/issue-71-move-aip-endpoint

**Comment by ablwr** [comment]
Great! Do you feel ready to rebase and send a PR over?

**Comment by jambun** [comment]
I just sent a PR:
https://github.com/artefactual/archivematica-storage-service/pull/408

Two additional things I was planning to do:
  - Write the pointer file to a temp file and move into place to reduce the risk of blatting it. I just copied the pointer file update code from the original implementation. It works fine.
  - Change the SIP move implementation to use the new `move` method on the `Package` model. This is not directly related to this issue, but is an opportunity to refactor.

Probably neither of these needs to be done.

**Comment by ablwr** [comment]
Consolidated and cleaned up this code and made a new PR, above. Thank you!!

**Comment by ablwr** [comment]
Doh, meant to say that in the PR.

**Comment by peterVG** [comment]
Successfully moved AIP package using the API "move" command. Also outputting error feedback when using the command incorrectly (e.g. trying to move to current location).
