### ISSUE TITLE
Problem: events that occur pre-Archivematica are not easily captured in METS as PREMIS

### ISSUE THREAD

**Issue by sromkey** [archivematica/Issues#710]
**Please describe the problem you'd like to be solved.**
Some users want to be able to record PREMIS events that happen outside of Archivematica in the AIP METS file and there is currently not an easy (or any?) way to do that. The Dataverse workflow captures the Dataverse Agent for creating derivations prior to ingest to Archivematica; it should be possible to do so in other workflows.

**Describe the solution you'd like to see implemented.**
I'd like to see users be able to import PREMIS events in a csv format, similar to the import of PREMIS rights in csv. Bonus points for the ability to post via an API endpoint but I don't think that's necessary for the use case currently sponsored.

**Additional context**
This is a requirement of the NHA project.

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by sromkey** [comment]
On further discussion with the team and the [community](https://groups.google.com/forum/#!topic/archivematica/HciDqnHuNj0) accepting PREMIS events as xml would make more sense because many systems output PREMIS in xml format. Accepting a file (premis.xml) that contains valid v.3 PREMIS and importing to the AIP METS is the current solution under discussion.

**Comment by peterVG** [comment]
@replaceafill below is a first attempt at a Feature file for this import functionality as discussed with Joel. Please let me know if you see any errors or gaps.

     Feature: PREMIS Event XML import
          Scenario: Digital preservation events occur prior to the ingest of digital objects into Archivematica
               Given that a PREMIS XML file is generated after these events
               And the XML file includes PREMIS Event entities
               And the XML file includes PREMIS Object entities that are linked to the PREMIS Event entities through the LinkingEventIdentifier property

               When the PREMIS XML file is imported into Archivematica after the Objects are ingested
		
               Then the PREMIS XML import file Object, Event, and Agent entities are added to the Archivematica AIP METS file
               And the pre-ingest Objects are mapped to new Archivematica Objects using the PREMIS OriginalName property `

**Comment by replaceafill** [comment]
@peterVG Do you think we could write the `Given` steps something along the lines of:

```
# This transfer contains an XML file with 2 Object entities, 2 Event entities and 1 Agent entity
Given a "standard" transfer type located in "SampleTransfers/PremisEventsXMLImport"
```

and maybe move the details of the structure of the XML to a README file in the transfer directory (like [the Dataverse sample transfers](https://github.com/artefactual/archivematica-sampledata/tree/master/SampleTransfers/Dataverse)).

The advantage is that we wouldn't need to write any new steps code for this. The disadvantage is that it may be too obscure/confusing.

**Comment by peterVG** [comment]
@replaceafill That sounds good. I don't think it's too obscure and it would be good not to have to write any new steps code.

**Comment by evelynPM** [comment]
Would it be useful to add some lines at the end ensuring that the pre-ingest Events are not altered? For example:

`And the pre-ingest Event entities retain their original field values`
`And the pre-ingest Event entities are not linked to any new Agent entities generated by Archivematica`

**Comment by peterVG** [comment]
So a re-write incorporating both suggestions would result in:

     Feature: PREMIS Event XML import
          Scenario: Digital preservation events occur prior to the transfer of digital objects into Archivematica
          # The transfer contains a PREMIS XML file with 2 Object entities, 2 Event entities and 1 Agent entity
          
          Given a "standard" transfer type located in "SampleTransfers/PremisEventsXMLImport"
               And the PREMIS XML file includes Object entities that are linked to the Event entities through the LinkingEventIdentifier property

          When the PREMIS XML file is imported into Archivematica after the Objects are ingested

          Then the PREMIS XML import file Object, Event, and Agent entities are added to the Archivematica AIP METS file
               And the pre-ingest Objects are mapped to new Archivematica Objects using the PREMIS OriginalName property 
               And the pre-ingest Event entities retain their original field values`
               And the pre-ingest Event entities are not linked to any new Agent entities generated by Archivematica`

**Comment by ablwr** [comment]
I was testing https://github.com/archivematica/Issues/issues/967 and that particular issue passes, but I am getting a failure when testing this in qa/1.x right now on Generate METS.xml document:


```
No uuid for file: " %SIPDirectory%objects/metadata/transfers/premis-b84b9acd-b6e8-48ec-b51d-a5c93fba6dfc/checksum.md5 "
No uuid for file: " %SIPDirectory%objects/metadata/transfers/premis-b84b9acd-b6e8-48ec-b51d-a5c93fba6dfc/checksum.sha1 "
No uuid for file: " %SIPDirectory%objects/metadata/transfers/premis-b84b9acd-b6e8-48ec-b51d-a5c93fba6dfc/checksum.sha256 "
No uuid for file: " %SIPDirectory%objects/metadata/transfers/premis-b84b9acd-b6e8-48ec-b51d-a5c93fba6dfc/checksum.sha512 "
No uuid for file: " %SIPDirectory%objects/metadata/transfers/premis-b84b9acd-b6e8-48ec-b51d-a5c93fba6dfc/identifiers.json "
No uuid for file: " %SIPDirectory%objects/metadata/transfers/premis-b84b9acd-b6e8-48ec-b51d-a5c93fba6dfc/metadata.csv "
No uuid for file: " %SIPDirectory%objects/metadata/transfers/premis-b84b9acd-b6e8-48ec-b51d-a5c93fba6dfc/premis.xml "
No uuid for file: " %SIPDirectory%objects/metadata/transfers/premis-b84b9acd-b6e8-48ec-b51d-a5c93fba6dfc/rights.csv "
/var/archivematica/sharedDirectory/watchedDirectories/workFlowDecisions/metadataReminder/premis-32f55602-002e-4e9e-abb2-d60c1de8f854/metadata doesn't exist
```

(this overall feature may still be a work in progress, so I will leave that ticket open for future testing)

**Comment by ablwr** [comment]
PREMIS events should make it into the final METS file, right?

When I am testing, there are a few things I am seeing in the sample `premis.xml` file (in SampleTransfers/PremisImporter) that are not making it into the XML when I am viewing it before storing the AIP.

Here are a few things I'm not seeing:

```
<premis:objectIdentifier>
      <premis:objectIdentifierType>hdl</premis:objectIdentifierType>
      <premis:objectIdentifierValue>hdl:3847677</premis:objectIdentifierValue>
    </premis:objectIdentifier>
```


```
  <premis:event>
    <premis:eventIdentifier>
      <premis:eventIdentifierType>NRI Repository Event ID</premis:eventIdentifierType>
      <premis:eventIdentifierValue>NRI-016</premis:eventIdentifierValue>
    </premis:eventIdentifier>
    <premis:eventType>ingestion</premis:eventType>
    <premis:eventDateTime>2019-07-04T22:46:07.773391+00:00</premis:eventDateTime>
    <premis:eventDetailInformation>
      <premis:eventDetail>Acquired via records transfer 002/041</premis:eventDetail>
    </premis:eventDetailInformation>
    <premis:eventOutcomeInformation>
      <premis:eventOutcome/>
    </premis:eventOutcomeInformation>
    <premis:linkingAgentIdentifier>
      <premis:linkingAgentIdentifierType>repository code</premis:linkingAgentIdentifierType>
      <premis:linkingAgentIdentifierValue>NRI</premis:linkingAgentIdentifierValue>
    </premis:linkingAgentIdentifier>
  </premis:event>
```

I am seeing **some** PREMIS events make it through, but just via Exiftool data. I'm not seeing the data end up anywhere else.

**Comment by replaceafill** [comment]
Hello @ablwr :wave: 

Regarding the things you are not seeing:

1. The events importer doesn't update any file information from the `<premis:object xsi:type="premis:file">` elements in `premis.xml`. It only uses their `<premis:originalName>` subelements to find files in the database. That's why the information in the `<premis:objectIdentifier>` elements doesn't end up in the AIP METS.

2.  I just ran a transfer using the `SampleTransfers/PremisImporter` transfer and [this is the METS file I get in the AIP](https://gist.githubusercontent.com/replaceafill/364caf710161a13cb2d5c876b483ac7f/raw/543134ee1c58dcad1d01e6483d1147fdd93ccb4d/METS.ab454de7-e13f-42a1-b17b-e8aa975aa873.xml).

    The event you refer to is referenced by the `objects/bird.mp3` file, right? This is how that file looks in the `fileSec` of the METS (the one with `ADMID="amdSec_7"`):

    ![Captura de pantalla de 2020-01-06 09-15-35](https://user-images.githubusercontent.com/560781/71827931-e67d7300-3066-11ea-99b8-5644cf03170d.png)

    And this is where I see the event information being imported:

    ![Captura de pantalla de 2020-01-06 09-17-20](https://user-images.githubusercontent.com/560781/71827947-f1d09e80-3066-11ea-8d0d-b16c724dee1f.png)

    The only piece that gets lost in this case is the original event identifier (with type `NRI Repository Event ID` and value `NRI-016`). This is intended. Our models can only store UUID identifiers, so [if the identifier type is not UUID a warning is logged and a new identifier is generated](https://github.com/artefactual/archivematica/blob/6d84db86d7d8fa21cea6f79f4b2ef1ec4c9666ef/src/MCPClient/lib/clientScripts/load_premis_events_from_xml.py#L678-L680).

Let me know if I'm missing something from your comment.

**Comment by ablwr** [comment]
Oooh okay, great! Then this is working as expected.

**Comment by evelynPM** [comment]
I am seeing a problem in both Douglas' AIP mets file and one that I just created during testing. The problem is that some Events generated by Archivematica are adding an Agent from the imported premis file. For example, this validation Event in Douglas' example has four Agents: the standard 3 generated by Archivematica (which should be there) and one pulled in from the imported premis file (which shouldn't):
```
     <mets:digiprovMD ID="digiprovMD_11">
      <mets:mdWrap MDTYPE="PREMIS:EVENT">
        <mets:xmlData>
          <premis:event xmlns:premis="http://www.loc.gov/premis/v3" xsi:schemaLocation="http://www.loc.gov/premis/v3 http://www.loc.gov/standards/premis/v3/premis.xsd" version="3.0">
            <premis:eventIdentifier>
              <premis:eventIdentifierType>UUID</premis:eventIdentifierType>
              <premis:eventIdentifierValue>76344e49-dc83-4f66-940f-eec99e4caf18</premis:eventIdentifierValue>
            </premis:eventIdentifier>
            <premis:eventType>validation</premis:eventType>
            <premis:eventDateTime>2020-01-06T15:05:48.078247+00:00</premis:eventDateTime>
            <premis:eventDetailInformation>
              <premis:eventDetail>program="JHOVE"; version="1.20"</premis:eventDetail>
            </premis:eventDetailInformation>
            <premis:eventOutcomeInformation>
              <premis:eventOutcome>pass</premis:eventOutcome>
              <premis:eventOutcomeDetail>
                <premis:eventOutcomeDetailNote>format="JPEG"; result="Well-Formed and valid"</premis:eventOutcomeDetailNote>
              </premis:eventOutcomeDetail>
            </premis:eventOutcomeInformation>
            <premis:linkingAgentIdentifier>
              <premis:linkingAgentIdentifierType>preservation system</premis:linkingAgentIdentifierType>
              <premis:linkingAgentIdentifierValue>Archivematica-1.11</premis:linkingAgentIdentifierValue>
            </premis:linkingAgentIdentifier>
            <premis:linkingAgentIdentifier>
              <premis:linkingAgentIdentifierType>repository code</premis:linkingAgentIdentifierType>
              <premis:linkingAgentIdentifierValue>test</premis:linkingAgentIdentifierValue>
            </premis:linkingAgentIdentifier>
            <premis:linkingAgentIdentifier>
              <premis:linkingAgentIdentifierType>Archivematica user pk</premis:linkingAgentIdentifierType>
              <premis:linkingAgentIdentifierValue>1</premis:linkingAgentIdentifierValue>
            </premis:linkingAgentIdentifier>
            <premis:linkingAgentIdentifier>
              <premis:linkingAgentIdentifierType>repository code</premis:linkingAgentIdentifierType>
              <premis:linkingAgentIdentifierValue>NRI</premis:linkingAgentIdentifierValue>
            </premis:linkingAgentIdentifier>
          </premis:event>
        </mets:xmlData>
      </mets:mdWrap>
    </mets:digiprovMD>
```

**Comment by replaceafill** [comment]
I just investigated this and it seems to be a problem with the [`getAMAgentsForFile` helper](https://github.com/artefactual/archivematica/blob/baf565e4abc3bcf9480ee0784734ce9b0b223f63/src/archivematicaCommon/lib/databaseFunctions.py#L124), specifically [this part](https://github.com/artefactual/archivematica/blob/baf565e4abc3bcf9480ee0784734ce9b0b223f63/src/archivematicaCommon/lib/databaseFunctions.py#L150-L153) that will return all the `repository code` and `preservation system` agents for a file if an agent can't be gathered first from the SIP or the transfer.

This problem can be reproduced in `qa` without using the PREMIS event importer by adding a new agent with type `repository code` or `preservation system` directly through the database or the Django shell. Look for `repository code` in [this METS](https://gist.github.com/replaceafill/409971b71dca9a2f77bed911dbbda711) of a `SampleTransfers/Images/pictures` transfer with this agent inserted through MySQL:

![Captura de pantalla de 2020-01-14 16-46-49](https://user-images.githubusercontent.com/560781/72389244-871a0580-36ed-11ea-9a61-b505a8f9fb15.png)

If you see the METS in my previous https://github.com/archivematica/Issues/issues/710#issuecomment-571187252 you'll notice that the events created by the importer don't have this problem because they're created from a different helper function.

**Comment by evelynPM** [comment]
I've created a new issue for this at https://github.com/archivematica/Issues/issues/1072.

**Comment by sallain** [comment]
I have confirmed that this works on qa/1.x on RPM.
