### ISSUE TITLE
Problem: Delete links are not consistent in the Packages tab of the Storage Service

### ISSUE THREAD

**Issue by replaceafill** [archivematica/Issues#711]
**Expected behaviour**

After clicking a **Request Deletion** link (for AIPs and Transfers) a "Delete request created successfully." message is displayed.

After clicking a **Delete** link (for DIPs) a modal dialog is displayed asking for confirmation.

**Current behaviour**

These links only work as intended for the first batch of results (currently 10). If the original results are modified either by clicking the Next button below the table or by changing the Show entries dropdown, then:

* The **Request Deletion** links don't request any deletion and only scroll the page up and change the URL to `/packages/#`
* The **Delete** links delete the DIP immediately without showing the confirmation modal.

The reason is that these two handlers:

* https://github.com/artefactual/archivematica-storage-service/blob/82c5c7dcc3511d2c3bd382d9421e607dd1a4d65f/storage_service/static/js/project.js#L30 
* https://github.com/artefactual/archivematica-storage-service/blob/82c5c7dcc3511d2c3bd382d9421e607dd1a4d65f/storage_service/static/js/project.js#L76

don't react when the DOM is updated. Changing them to use jQuery's `on` should fix this.

**Steps to reproduce**

Populate the Storage Service with more than 10 objects (AIPs, Transfers, DIPs) and change the value of the Show entries dropdown from 10 to 100. Click the **Request Deletion** or **Delete** link of the 11th row and below.

**Your environment (version of Archivematica, OS version, etc)**

https://github.com/artefactual-labs/am/commit/034c16487630b3fbb054147660bc74bdcc9a82af with https://github.com/artefactual/archivematica-storage-service/commit/82c5c7dcc3511d2c3bd382d9421e607dd1a4d65f

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by sallain** [comment]
Great catch, @replaceafill.
