### ISSUE TITLE
Allow replicator locations on remote spaces in Storage Service, e.g. S3

### ISSUE THREAD

**Issue by cole** [archivematica/Issues#721]
**Please describe the problem you'd like to be solved.**

It is only possible via Storage Service admin to create a replicator location that relates to the Local Filesystem or GPG encrypted Local Filesystem space types. However, replicator locations that are manually created (via the database or Django admin) that relate to an S3 space seem to function correctly.

**Describe the solution you'd like to see implemented.**

Enable configuration of replicator locations for other space types (e.g. S3) via SS admin.

**Describe alternatives you've considered.**

Leave the Storage Service admin forms as is. It is possible to achieve basically the same functionality by configuring primary AIP storage on the remote location (e.g. S3) and replication to Local Filesystem, which is currently possible.

**Additional context**

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by cole** [comment]
Implementation of this change is probably just a matter of adding to the allowed purposes: https://github.com/artefactual/archivematica-storage-service/blob/d83d383f44dd258f6ba4c1b5a879ca22270e2ae6/storage_service/locations/models/s3.py#L40

**Comment by ross-spencer** [comment]
Related known issues: https://github.com/archivematica/Issues/issues/1149

However, issues aside, this works. I created a replication space in the storage service, pointing at S3. In the screenshot below we have two replicated packages, one on NFS and one on S3.

![image](https://user-images.githubusercontent.com/1880412/77372174-787a4b00-6d3b-11ea-9c66-68a952d9e2f0.png)

I can see that it stored successfully in the S3 dashboard:

![image](https://user-images.githubusercontent.com/1880412/77372258-ac557080-6d3b-11ea-9100-c8a73e4a8602.png)
