### ISSUE TITLE
Feature: add new API endpoint for Microservice & task status

### ISSUE THREAD

**Issue by joel-simpson** [archivematica/Issues#722]
**Please describe the problem you'd like to be solved.**
We need to expose the Job and Tasks database tables as resources in our REST API. This will help to make data about the performance of Archivematica more transparent and more easily accessible. 

There are several use cases where this will be helpful. 

- One is to help verify steps in our [automated acceptance tests](https://github.com/artefactual-labs/archivematica-acceptance-tests). 
- Another is to extract performance data (i.e. how long it took to execute a microservice or task). 
- Another use case is to provide better visibility of errors or failures, for example, in the automation tools (which currently only understands status at package level). 

(this was previously logged in our old issues repository here: https://github.com/artefactual/archivematica/issues/1113) 

**Describe the solution you'd like to see implemented.**
An API endpoint(s) that allows clients to retrieve 
-the status of a job (aka microservice) or exit code of a task  
-the start time, end time and duration (for performance stats) 
Ideally it might return stdout / stderr but I don't think that would be critical for a first iteration of this. Probably it should also return [task type](https://wiki.archivematica.org/MCPServer/TaskTypes) (e.g. run once, run for each file, etc.). 

For the purposes of the automated testing use case, I think we need a way to search for jobs / tasks performed on a particular package. For example, if I want to verify that the microservice "Bag Verification" ran successfully, I should be able to search for jobs executed of that type (i.e. bag verification), for a particular package (where package UUID is the input). 

**Describe alternatives you've considered.**
In the old issue we briefly considered [event-sourcing](https://github.com/artefactual/archivematica/issues/1113#issuecomment-498714561) as a different approach, but that requires significant change to each microservice. 

**Additional context**
We are currently planning to do this work as part of a project sponsored by Wellcome Collection to improve our automated testing coverage. 

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by currmie** [comment]
**Verified** (QA notes below; [endpoint descriptions updated](https://wiki.archivematica.org/Archivematica_API) on dev wiki)
Related docs issue: https://github.com/artefactual/archivematica-docs/issues/81

_Manually ran the following test scenarios on am110rpm.qa AND recorded outcomes for each respectively:_

_Scenario 1_: packages are extracted successfully
Given a "standard" transfer type located in "SampleTransfers/OfficeDocs"
Pay specific attention to these:

    And the "Scan for viruses on extracted files" job completes successfully 
    And the "Identify file format" job completes successfully 
    And the "Determine if transfer still contains packages" job completes successfully

**Call to the list jobs endpoint:**
`http GET http://am110rpm.qa.archivematica.net:81/api/v2beta/jobs/eff13570-f585-474b-8fbb-a95f8e00c126/ \ Authorization:'ApiKey test:eb9b3934c56de5c4eb22b2649637c9416e8912f1' `

**JSON response:**
`[
    {
        "status": "COMPLETE",
        "tasks": [
            {
                "uuid": "1c799082-59a6-4805-b00c-6f1f41340a11",
                "exit_code": 0
            },
            {
                "uuid": "35899fbe-c4b2-4281-b858-3c72330765ed",
                "exit_code": 0
            },
            {
                "uuid": "64cb7d9b-d34a-4e55-8739-9af359105bf2",
                "exit_code": 0
            },
            {
                "uuid": "6643dcd0-246f-4bdc-acf5-0b5be4348d15",
                "exit_code": 0
            },
            {
                "uuid": "8ee7a1c0-9b8d-4b81-aa59-8e00e68a6448",
                "exit_code": 0
            },
            {
                "uuid": "952d0630-bd92-4d6a-9329-49e60cbd9f05",
                "exit_code": 0
            },
            {
                "uuid": "99441560-74d9-4400-a00c-bfd4be825fac",
                "exit_code": 0
            },
            {
                "uuid": "abf203f6-7d62-4739-99c6-2f54a3ec0a2b",
                "exit_code": 0
            },
            {
                "uuid": "b5c3d71f-ca08-4525-bbcf-ebde41fda266",
                "exit_code": 0
            },
            {
                "uuid": "c7d92b3f-28c4-4f20-a065-4ca95ff559d1",
                "exit_code": 0
            },
            {
                "uuid": "d3ad7371-f13b-49c6-bd23-c232c8f85f89",
                "exit_code": 0
            },
            {
                "uuid": "fee94951-be68-415d-bf21-cd8702a3b80d",
                "exit_code": 0
            }
        ],
        "uuid": "aa716d60-ec96-467c-aa7c-9bc95e32bc61",
        "link_uuid": "7d33f228-0fa8-4f4c-a66b-24f8e264c214",
        "microservice": "Extract packages",
        "name": "Scan for viruses on extracted files"
    }
]
`

**Test outcome:** I was able to filter and search for various strings for units that passed either during transfer or ingest.

_Scenario 2:_ packages are not extracted successfully
    Given a "standard" transfer type located in "TestTransfers/broken_package_format_types"
    When the transfer compliance is verified
    Then the "Extract contents from compressed archives" job fails
    And the "Failed transfer" microservice is executed

**Call to the task information endpoint:**
`http GET http://am110rpm.qa.archivematica.net:81/api//v2beta/task/8cbdc4e3-45c5-4db5-9d7d-4cfc114f3982 \
  Accept:'*/*' \
  Authorization:'ApiKey test:eb9b3934c56de5c4eb22b2649637c9416e8912f1' `

**JSON response:**
`{
    "uuid": "8cbdc4e3-45c5-4db5-9d7d-4cfc114f3982",
    "file_name": "currmie_brokenPackage_api_testing-eff13570-f585-474b-8fbb-a95f8e00c126",
    "exit_code": 255,
    "time_created": "2019-07-11T20:08:36",
    "time_ended": "2019-07-11T20:08:36",
    "file_uuid": "",
    "duration": "< 1",
    "time_started": "2019-07-11T20:08:36"
}
`

**Test outcome:** I am able to retrieve info. about a failed task.

_Scenario 3:_ verify that the microservice "Bag Verification" ran successfully, I should be able to search for jobs executed of that type (i.e. bag verification), for a particular package (where package UUID is the input).

**Call to the list jobs endpoint:**
`http GET 'http://am110rpm.qa.archivematica.net:81/api/v2beta/jobs/75f438d0-2e3f-4896-b547-d264defe61b2/?name=Verify%20bag,%20and%20restructure%20for%20compliance' \
  Accept:'*/*' \
  Authorization:'ApiKey test:eb9b3934c56de5c4eb22b2649637c9416e8912f1'`

**JSON response:**
`[
    {
        "status": "COMPLETE",
        "tasks": [
            {
                "uuid": "44d38364-6f2e-41bf-a106-25d2a37fadfe",
                "exit_code": 0
            }
        ],
        "uuid": "f9475dc6-044e-4168-92df-3cfa3e37bed8",
        "link_uuid": "f0f64c7e-30fa-47c1-9877-43955680c0d0",
        "microservice": "Approve transfer",
        "name": "Verify bag, and restructure for compliance"
    }
]
`

**Test outcome:** I am able to search for jobs executed of type 'bag' for a particular package (where package UUID is the input).

**Comment by ross-spencer** [comment]
These QA/acceptance notes are really great to have and to be able to look back on @currmie! Thank you. 

And the docs - perfect! Thanks for doing that too. Douglas and I had been talking about getting that done, one lest thing! :nerd_face:
