### ISSUE TITLE
Problem: mcp-rpc-cli is not working

### ISSUE THREAD

**Issue by scollazo** [archivematica/Issues#728]
**Expected behaviour**
The [mcp-rpc-cli tool](https://github.com/artefactual/archivematica-devtools/blob/master/tools/mcp-rpc-cli) availabe at [am-devtools](https://github.com/artefactual/archivematica-devtools/), works

**Current behaviour**

When using mcp-rpc-cli, the following snippet can be found in mcpserver log:

<pre>
ERROR     2019-06-06 09:03:14  archivematica.mcp.server.rpcserver:RPCServer:wrap:186:  Exception raised by handler approveJob: 'user_id'
Traceback (most recent call last):
  File "/opt/archivematica/archivematica/src/MCPServer/lib/RPCServer.py", line 181, in wrap
    resp = handler(*args)
  File "/opt/archivematica/archivematica/src/MCPServer/lib/RPCServer.py", line 212, in _job_approve_handler
    user_id = str(payload["user_id"])
KeyError: 'user_id'
</pre>

And no changes are made to the transfers/ingests

**Steps to reproduce**

Run mcp-rpc-cli

**Your environment (version of Archivematica, OS version, etc)**

Archivematica 1.9.1 on Ubuntu 18.04

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by mamedin** [comment]
I could reproduce the same issue in AM stable/1.9.x

**Comment by scollazo** [comment]
I think this comes from https://github.com/archivematica/Issues/issues/529

**Comment by scollazo** [comment]
Fixed
