### ISSUE TITLE
Problem: There are potential improvements to the automation-tools install docs on docker

### ISSUE THREAD

**Issue by ross-spencer** [archivematica/Issues#729]
From the original issue via. @jorikvankemenade:

When using the installation instructions for using the automation tools with a docker install I ran into a few problems. I think these are more general problems of the installation instructions and I think it might be a good idea to update the instructions. Before doing that I would like to know if you agree.

Proposed changes:

* Add sudo to the commands for creating the automation directories. All parent directories are owned by root, not the user.

* Add instructions for creating the archivematica group and user. In my case they didn't exist - but this might be because of the docker installation.

* Add instrcutions for changing ownership of the new directories from root to the user.

If you think that this is a good idea I'll go ahead and create a PR for changing this.

Ref: https://github.com/artefactual/automation-tools/issues/114

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by ross-spencer** [comment]
Hi @jorikvankemenade. It sounds like a great idea. We'll need you to complete this [contributor's agreement](https://wiki.archivematica.org/Contributor_Agreement) and then when you submit your pull-request we'll go through a round of CR and then find an appropriate juncture to merge your changes.

**Comment by jorikvankemenade** [comment]
Thanks for the fast reply. I have signed and e-mailed the contributor's agreement. I'll open a PR as soon as it is ready.
