### ISSUE TITLE
Problem: Storage Service async manager is unable to log the task stack trace

### ISSUE THREAD

**Issue by sevein** [archivematica/Issues#742]
**Expected behaviour**
Storage Service should log the full stack trace when the Async Manager executes a deferred task that raises an uncontrolled error.

**Current behaviour**
The Async Manager in Storage Service does a poor job logging errors raised by deferred tasks as it only logs the message of the exception, e.g.:

    TypeError: expected string or buffer

This is likely going to be not enough information for a developer to understand the underlying issue.

**Steps to reproduce**
Implement and run a deferred task that raises an error.

**Your environment (version of Archivematica, OS version, etc)**
SS 0.12 or newer.

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by sromkey** [comment]
@sevein could you size this for us?
