### ISSUE TITLE
Problem: job move transfer to backlog fails

### ISSUE THREAD

**Issue by sevein** [archivematica/Issues#744]
**Expected behaviour**
"Move transfer to backlog" should run successfully.

**Current behaviour**
Job "Move transfer to backlog" fails. This is the error being logged:

```
movetobacklog_v1.0: INFO      2019-06-13 16:36:19,383  archivematica.mcp.client.move_to_backlog.main:183  Creating events...
movetobacklog_v1.0: INFO      2019-06-13 16:36:19,447  archivematica.mcp.client.move_to_backlog.main:186  Creating bag...
movetobacklog_v1.0: INFO      2019-06-13 16:36:19,584  archivematica.mcp.client.move_to_backlog.main:189  Indexing the transfer...
movetobacklog_v1.0: INFO      2019-06-13 16:36:19,909  archivematica.mcp.client.move_to_backlog.main:192  Calculating size...
movetobacklog_v1.0: INFO      2019-06-13 16:36:19,909  archivematica.mcp.client.move_to_backlog.main:208  Moving transfer to backlog...
movetobacklog_v1.0: WARNING   2019-06-13 16:36:24,077  archivematica.mcp.client.move_to_backlog.main:220  Moving to backlog failed: Failure storing file: <type 'exceptions.TypeError'>: expected string or buffer.
Moving to backlog failed: Failure storing file: <type 'exceptions.TypeError'>: expected string or buffer. See logs for more details.Traceback (most recent call last):
  File "/src/MCPClient/lib/job.py", line 111, in JobContext
    yield
  File "/src/MCPClient/lib/clientScripts/move_to_backlog.py", line 235, in call
    job.set_status(main(job, transfer_id, transfer_path, created_at))
  File "/src/MCPClient/lib/clientScripts/move_to_backlog.py", line 221, in main
    raise Exception(errmsg + " See logs for more details.")
Exception: Moving to backlog failed: Failure storing file: <type 'exceptions.TypeError'>: expected string or buffer. See logs for more details.
```

After some digging, this is what I've found:
In a recent refactor in our naming cleanup scripts, "name cleanup" PREMIS events stopped including a value in the `eventOutcomeDetailNote` attribute which used to be populated as follows:

    eventOutcomeDetailNote = "Original name=\"%s\"; cleaned up name=\"%s\"" % (src, dst)

This seems to be causing problems in SS where the value is expected to be populated. SS does not handle well the fact that it's not (see #742 and #743 for more).

**Steps to reproduce**
Send a transfer to backlog and see it fail!

**Your environment (version of Archivematica, OS version, etc)**
qa/1.x (since https://github.com/artefactual/archivematica/pull/1401 was merged)

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by evelynPM** [comment]
Fix verified on bionic 1.10
