### ISSUE TITLE
Storage Service does not update locations space usage when AIPs are deleted

### ISSUE THREAD

**Issue by andrewjbtw** [archivematica/Issues#757]
**Expected behaviour**

After an AIP is deleted, the space usage reported for that location should be reduced by the size of the deleted AIP.

**Current behaviour**

After an AIP is deleted, the space usage for the location remains the same.

**Steps to reproduce**

Delete an AIP.

**Your environment (version of Archivematica, OS version, etc)**

Archivematica 1.9.1 on Ubuntu 18.04

This seems related to https://github.com/archivematica/Issues/issues/495

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by sallain** [comment]
This was fixed as part of archivematica/Issues#312.

The fix is not retroactive - it will not fix the overall value if you deleted AIPs in the past, which caused this number to become incorrect. But going forward, the value will adjust as expected when AIPs are deleted.

Tested on qa/1.x on Bionic.
