### ISSUE TITLE
Problem: DMDID attributes not appearing in normative structMaps

### ISSUE THREAD

**Issue by evelynPM** [archivematica/Issues#768]
**Expected behaviour**
A normative structMap should have all of the DMDID attributes that the default structMap has.

**Current behaviour**
Normative structMaps have DMDID attributes for empty directories only.

**Steps to reproduce**
1. Ingest a transfer that has empty directories, making sure that the "document empty directories" micro-service config setting is set to yes.
2. Add DC metadata during processing, or include a descriptive metadata file in the transfer.
3. Review the AIP METS file. There will be a default structMap and a normative structMap, but the normative structMap will not have DMDID attributes for the dmdSecs containing the descriptive metadata.

**Your environment (version of Archivematica, OS version, etc)**

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by jraddaoui** [comment]
I found this issue while working on #914, looking at the `mets-reader-writer` code. However, at the moment it will require two different fixes for the normal workflow in the MCPClient scripts and for the re-ingest workflow in the `mets-reader-writer`, so I've removed the fix I had for the re-ingest process in https://github.com/artefactual-labs/mets-reader-writer/pull/76.

When we get to this issue, the re-ingest fix may be as easy as removing the following condition:

https://github.com/artefactual-labs/mets-reader-writer/blob/58c429289e11c21c2e95f32b11eac9508c39e849/metsrw/fsentry.py#L473

**Comment by sromkey** [comment]
We verified this during 1.13 release testing
