### ISSUE TITLE
Problem: "Job: Check transfer directory for objects" is executed for all completed transfers each time Archivematica services are restarted

### ISSUE THREAD

**Issue by hakamine** [archivematica/Issues#770]
**Current behaviour**
The Job: "Check transfer directory for objects" (Microservice: "Create SIP from Transfer") is re-executed for all completed transfers each time Archivematica services are restarted

**Steps to reproduce**
* Process a few transfers/ingests
* Restart Archivematica services (specifically the MCP server) a few times
* Check the transfer tab, all the transfers have the "Job: Check transfer directory for objects" executed many times (the number of times the MCP server was restarted) as shown:

<img width="670" alt="Screen Shot 2019-06-26 at 2 54 13 PM" src="https://user-images.githubusercontent.com/10160634/60217822-6efe9980-9822-11e9-93dd-22a21807a8d7.png">

**Your environment (version of Archivematica, OS version, etc)**
Any (checked in 1.6, 1.9, qa/1.x)

**Notes**
This may be related with #769 

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by replaceafill** [comment]
I talked to @cole about this today and it seems like the "Rename SIP directory with SIP UUID" job in the "Rename SIP directory with SIP UUID" microservice got affected by a change in the path of the SIP. The problem doesn't seem to affect a standard workflow, but this is displayed in the job page:

![Screenshot_2019-10-18 Archivematica Dashboard -](https://user-images.githubusercontent.com/560781/67123234-f0e94880-f1ac-11e9-8bad-088938f4fd79.png)

This is how the same job looks in 1.10.1:

![Screenshot_2019-10-18 Archivematica Dashboard -2](https://user-images.githubusercontent.com/560781/67123285-19714280-f1ad-11e9-8231-5af327455fcc.png)

**Comment by replaceafill** [comment]
The problem mentioned in my previous comment has been addressed in https://github.com/artefactual/archivematica/pull/1498

**Comment by ablwr** [comment]
I can't recreate this with 1.11 RC2 on RPM as much as I try, so it seems this is good-to-go!
