### ISSUE TITLE
Problem: Validate function of bind_pids occurs too early in the microservice script

### ISSUE THREAD

**Issue by ross-spencer** [archivematica/Issues#776]
**Expected behaviour**

When bind_pids is run its parameters are validated once they are all configured. 

**Current behaviour**

A change being made to make the parameter validation more robust for `1.10` happens too early in the microservice execution where the configuration parameters are still being set. 

See: [here](https://github.com/artefactual/archivematica/blob/69131e52488f17a071dd70756b05cedf92ce2fef/src/MCPClient/lib/clientScripts/bind_pids.py#L226-L230). Validation will ask for the `entity_type` to be set, but it's actually set a bit further along, [here](https://github.com/artefactual/archivematica/blob/qa/1.x/src/MCPClient/lib/clientScripts/bind_pids.py#L202). We need to set `entity_type` sooner, or move validation up a little.

Currently the microservice will fail with the microservice as it is at present. 

![image](https://user-images.githubusercontent.com/1880412/60677883-07c89100-9e83-11e9-85a9-80b31825ec2d.png)

**Additional context**

Identified running regression tests for the `qa/0.x`->`1.10` release of Archivematica. 

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by sallain** [comment]
@lwo just a note- if you are interested in testing this fix, it's available as part of the [rc1](https://github.com/artefactual/archivematica/releases/tag/v1.10.0-rc.1) tag of qa
