### ISSUE TITLE
Problem: default installation instructions do not create users

### ISSUE THREAD

**Issue by jhsimpson** [archivematica/Issues#78]
**Expected behaviour**
When following the installation instructions, the end result should be a fully working Archivematica installation with users created with working (known) login credentials.

**Current behaviour**
When installing Archivematica 1.7.2 using the default instructions from the documentation and selecting the ansible/vagrant/virtualbox method (usiing deploy-pub), no user is created in the storage service or dashboard.

It is possible to create the dashboard user via the welcome/installer page and the storage service user by logging into the vm and using the command line but the process is not yet documented, and the ansible role supports automating both processes. That automated method should be available in deploy-pub and described there and in the install instructions.

**Your environment (version of Archivematica, OS version, etc)**
deploying archivematica using deploy-pub (1.7.2-rc.2 am with 0.12.0-rc.1 ss using ansible/vagrant/virtualbox).

**Comment by sevein** [comment]
@mamedin has fixed the problem in #88.
CC @mamedin @scollazo should we move to verified?
