### ISSUE TITLE
Problem: There are no basic policies in Archivematica to perform AMAUAT or regression testing against

### ISSUE THREAD

**Issue by ross-spencer** [archivematica/Issues#780]
**Please describe the problem you'd like to be solved.**

A low-risk/low-controversy policy should be added to Archivematica to better-enable testing of the system's policy checking features. 

**Describe the solution you'd like to see implemented.**

Such a policy might test for a feature that is always anticipated will exist for a certain file format. E.g. for an audio format, (I presume) Mediaconch will always be able to test for the existence of a 'Duration'. 
```
General
Complete name                            : fmt-134-signature-id-266-good.mp3
Format                                   : MPEG Audio
File size                                : 5.71 MiB
Duration                                 : 2 min 29 s
```
If `Duration` doesn't exist for this MP3 for example, then we might have a preservation problem. But it is also a good way for us to verify the policy check has been triggered, both for a good file, and for a bad file:
```
General
Complete name                            : fmt-134-signature-id-279-skeleton.mp3
File size                                : 6.55 KiB
```

The expectation of such a test is that this would rarely, if ever fail, outside of AMAUAT/shake-down scenarios completed by the Archivematica team. 

**Describe alternatives you've considered.**

We could of course implement more complex policies, but there is only so much a system should be doing for a user where desired results may vary. 

**Additional context**

Opening this ticket for discussion with a proposed PR that might help better enable AMAUAT acceptance testing. 

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by sromkey** [comment]
@ablwr If you have time, do you want to take a look at this and give your thoughts?

**Comment by ablwr** [comment]
Yes!

**Comment by sallain** [comment]
This worked great in manual testing. I might add a little bit more info to the sampledata transfer's README about setting up the test, as I definitely forgot some steps :) I haven't tested the AMAUAT but I'll try to do so this afternoon.

**Comment by sallain** [comment]
@ross-spencer I tried to run the `ingest-policy-check` test but it's still looking for quarantine so it won't pass! I don't think it's a huge concern - it works fine manually - but would be good to fix up someday.

**Comment by ross-spencer** [comment]
Ah, interesting, @sallain can you just confirm your branch for AMAUAT is on [`qa/1.x`](https://github.com/artefactual-labs/archivematica-acceptance-tests/tree/qa/1.x) in your compose layout? The quarantine issue should be solved, but you just prompted me to verify this: https://github.com/archivematica/Issues/issues/1115 

**Notes on this ticket...**

To clarify for this particular issue, we didn't quite explore it to its conclusion of having AMAUAT directly connected to this new policy. I don't know how much it affects your acceptance of the ticket, but the sample-data for manual testing is one step further.

For the realization of my idea above, I think we'd need:

* To always have a policy available like this, 
* For it to work without modifying Archivematica, it would need to always be `enabled` which I also don't think is desirable, but which I think is the primary discussion issue created by this ticket.
* For anything else to work more kindly with folks' expectations of Archivematica, then that old badger: an API layer on top of the FPR would be needed so that `black-box` testing can:
   * Setup a test by creating and/or enabling a rule.
   * Start a transfer.
   * Read the Job output of the policy task and check its return code marks it as `Failed`.

We were close to realizing this in our selenium tests, but didn't quite get there, also noted in https://github.com/archivematica/Issues/issues/1115.

**Comment by sallain** [comment]
@ross I agree that it's not desirable to have a policy enabled by default, even if it is something very basic.

To me, the sampledata + instructions and an AMAUAT (even if it needs manual config first) feels sufficient to close off this ticket. We might only be half-way there but your notes in #1115 indicate there are other things that need doing to fix up this automated test. Thoughts?

**Comment by ross** [comment]
> @ross I agree that it's not desirable to have a policy enabled by default, even if it is something very basic.

Looks like you want @ross-spencer rather than @ross 😁

**Comment by ross-spencer** [comment]
> Looks like you want @ross-spencer rather than @ross

All views welcome my friend!! :slightly_smiling_face: 

@sallain sounds good to me. #1115 I'd mark as tangential and something I think we can do (something for that) prior to release of `amauat-1.11` as part of the `1.11` release procedure once (if) we confirm a go-ahead on that following backlog grooming next Monday. But thank you for putting me on that research track! :wink:

**Comment by sallain** [comment]
Ahhh sorry about that @ross!
