### ISSUE TITLE
Problem: "Check transfer directory for objects" executed multiple times

### ISSUE THREAD

**Issue by cole** [archivematica/Issues#782]
**Expected behaviour**
During transfer processing, "Check transfer directory for objects" should only be executed once.

**Current behaviour**
If there is any activity (e.g., by another transfer being processed) in the completedTransfers watched directory, it will trigger another execution of "Check transfer directory for objects".

<img width="969" alt="Screen Shot 2019-07-05 at 10 24 09 AM" src="https://user-images.githubusercontent.com/134694/60737437-a3074800-9f0f-11e9-8b2b-520ee384bd92.png">

**Steps to reproduce**
1. Start two transfers in quick succession
2. Observe one of them will have multiple runs of "Check transfer directory for objects".

**Your environment (version of Archivematica, OS version, etc)**

docker - qa/1.x

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by cole** [comment]
This is probably the same root cause as #770  — empty transfer folders seem to be left in the watched directory. It seems the move to the processing directory is moving the folder contents only.

**Comment by cole** [comment]
Adding the NHA label as this issue effectively blocks https://github.com/archivematica/Issues/issues/911.

**Comment by ablwr** [comment]
I've noticed this! And this appears to be resolved now, as much as I can test this. Tested in qa/1.x on Ubuntu Bionic via Docker (last commit: https://github.com/artefactual/archivematica/commit/baf565e4abc3bcf9480ee0784734ce9b0b223f63)
