### ISSUE TITLE
Problem: non executed tests in dashboard administration and fpr

### ISSUE THREAD

**Issue by jraddaoui** [archivematica/Issues#783]
**Expected behaviour**

The tests included in [this module](https://github.com/artefactual/archivematica/blob/qa/1.x/src/dashboard/src/components/administration/tests.py) and [this module](https://github.com/artefactual/archivematica/blob/qa/1.x/src/dashboard/src/fpr/tests.py) are executed in the CI process and they pass.

**Current behaviour**

They're ignored by `pytest` and not executed in the CI process.

**Steps to reproduce**

Run the tests locally or check the Travis CI output from a run of tests trying to find the execution of those modules by `pytest`.

**Your environment (version of Archivematica, OS version, etc)**

Docker environment, qa branches (pre 1.10).

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by ross-spencer** [comment]
I've added the triage label, maybe we can chat about it in the weekly tomorrow? While we're at code-freeze, new tests and ensuring tests pass feels important/beneficial enough to outweigh what that usually means for features. My 2¢ anyway! :)

**Comment by sallain** [comment]
@jraddaoui please look at this when you're done camping!

**Comment by jraddaoui** [comment]
Hi @sallain!

I've addressed Ross' feedback in the PR and requested another (code) review. I'll merge and mark this for (test) review after that.

**Comment by jraddaoui** [comment]
While most of this work is test related, there are a couple of forms/fields that should be tested in the FPR section, to verify that they work as before:

- Format form - Group field
- Rule form - Command field
