### ISSUE TITLE
Problem: Archivematica uses PRONOM v.94

### ISSUE THREAD

**Issue by ablwr** [archivematica/Issues#791]
Archivematica strives to be up to date with PRONOM release. A new PRONOM version has been released in between the anticipated 1.10 release and the previous release. 

The latest release is 95: https://www.nationalarchives.gov.uk/aboutapps/pronom/release-notes.xml

- [x] Update PRONOM entries (https://github.com/artefactual/archivematica/pull/1542)
- [x] Update FIDO (https://github.com/openpreserve/fido/releases)
- [x] Update FIDO in Archivematica (https://github.com/artefactual/archivematica/pull/1543)
- [x] (Wait for an) Update(d) Siegfried (https://github.com/richardlehane/siegfried/releases)
- [x] Update Siegfried in Archivematica (https://github.com/archivematica/Issues/issues/1075 via https://github.com/artefactual-labs/am-packbuild/pull/251)
- [x] Update FPR with FIDO/Siegfried versions (after much conflict -- https://github.com/artefactual/archivematica/pull/1547)

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by ablwr** [comment]
The v96 release is planned for the week of January 13th (see https://groups.google.com/forum/#!topic/pronom/deeeBDciT-s). I'll work on this task after that release, so Archivematica can have the latest (and I expect it'll be a large one).

**Comment by sallain** [comment]
I discussed with @ablwr and the only thing to confirm on this is that new formats from the two updates (v95 and v96) appear in the format list, which they do. Tested on qa/1.x on Bionic.
