### ISSUE TITLE
Problem: Cannot find replicated AIPs with original AIP UUID in 1.10-rc

### ISSUE THREAD

**Issue by ross-spencer** [archivematica/Issues#801]
**Expected behaviour**

If I search for an AIP with its UUID, then I can find its replicated version via the storage service search mechanism. Equally, I can perform a reverse lookup with the replicated UUID.

![image](https://user-images.githubusercontent.com/1880412/61460281-b2a27a00-a96e-11e9-80fb-8e394bf1a360.png)

**Current behaviour**

There seems to be a regression between `1.9` and `1.10-rc` where this isn't possible any more.

**Steps to reproduce**

* Create a replicator in `1.10-rc` and ensure it is configured to mirror the AIP store where you will store the AIP.
* Store an AIP.
* In the storage service, search for the original UUID and you will only see one result.
* Search for the replicated UUID and you will only see one result.
* There should be two for both.

**Your environment (version of Archivematica, OS version, etc)**

Discovered initially though AMAUAT testing. Verified running docker with the `1.10-rc` tag, and additionally on the sandbox `1.9` server while we wait for replication to be fixed on the other deployments.

**Additional context**

This looks will impact users ability to easily manage replicated packages. We have lost the `replicas` column. This will also impede this feature.

_Screenshots of the issue in `1.10`_

* Both packages:

![image](https://user-images.githubusercontent.com/1880412/61462600-2b0b3a00-a973-11e9-9e3f-62753fba54a3.png)

* Searching for the original

![image](https://user-images.githubusercontent.com/1880412/61462671-4b3af900-a973-11e9-80c4-b4b45bbdc89c.png)

* Searching for the replicated 

![image](https://user-images.githubusercontent.com/1880412/61462703-6148b980-a973-11e9-8ce2-b083986f65d7.png)

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Done:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by sallain** [comment]
This looks to be fixed! I have two replicated locations, hence the three packages overall.

![Screenshot of Archivematica Storage Service.jpg](https://codetreeusercontent.s3.amazonaws.com/uploads/1ff93c3b-69b9-4d98-8043-77b2fec9b609/Screenshot+of+Archivematica+Storage+Service.jpg)
