### ISSUE TITLE
Values of Total file size and Number of files reversed on Failure Report

### ISSUE THREAD

**Issue by bonniegee** [archivematica/Issues#802]
**Expected behaviour**
When viewing a failure report, I expect the "Total file size" column to show the total size of the SIP, and the "Number of files" to show the total number of files. For example:

Unit type | Total time processing | Total file size | Number of files | Average file size KB | Average file size MB
-- | -- | -- | -- | -- | --
SIP | 00:22:50 | 1643672961 |  70 | 23481.04230000 | 23.48104230

**Current behaviour**
The values of the Total file size and Number of files columns are switched. For example:

Unit type | Total time processing | Total file size | Number of files | Average file size KB | Average file size MB
-- | -- | -- | -- | -- | --
SIP | 00:22:50 | 70 | 1643672961 | 23481.04230000 | 23.48104230

**Steps to reproduce**
View a failure report from the Administration tab on the dashboard.

**Your environment (version of Archivematica, OS version, etc)**
1.9.1

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Done:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by sarah-mason** [comment]
This is still an issue in 1.10.1 (see attached image).
![EmailNotificationForErrors](https://user-images.githubusercontent.com/24920834/78903461-10ce3a80-7a73-11ea-9d23-79c78d51bd61.png)

**Comment by evelynPM** [comment]
This is still happening in 1.12. Could the issue be triaged for 1.13?

**Comment by jens-st** [comment]
This issue is still present in 1.13.0, effects the mail failure report too and the counted files and sizes do not seem to match as well.
![Screenshot_2021-09-01 Test Report 04](https://user-images.githubusercontent.com/54269233/131660935-7f9125fc-67f1-4407-b15b-918bc9e6f538.png)
```
TRANSFER (Unzipped bag):

AM-TEST-REPORT/
├── [        877]  bag-info.txt
├── [         53]  bagit.txt
├── [       4654]  data
│   └── [        558]  invalid.tif
├── [         51]  manifest-md5.txt
├── [        147]  manifest-sha512.txt
├── [        196]  tagmanifest-md5.txt
└── [        580]  tagmanifest-sha512.txt

       10654 bytes used in 1 directory, 7 files

FAILED TRANSFER (in .../sharedDirectory/failed/):

test_report-02b2f03e-d918-463f-ba9f-e4a5afdae24e
├── [     131519]  METS.02b2f03e-d918-463f-ba9f-e4a5afdae24e.xml
├── [     147608]  METS.02b2f03e-d918-463f-ba9f-e4a5afdae24e.xml.validatorTester.html
├── [       7522]  README.html
├── [       7348]  processingMCP.xml
├── [      92656]  submissionDocumentation
│   └── [      88560]  submissionDocumentation
│       └── [      84464]  transfer-test_report-22cb32f6-a691-4bcb-b718-262939262169
│           └── [      80368]  METS.xml
└── [     302970]  test_report-02b2f03e-d918-463f-ba9f-e4a5afdae24e
    ├── [        195]  bag-info.txt
    ├── [         55]  bagit.txt
    ├── [     294243]  data
    │   ├── [     131519]  METS.02b2f03e-d918-463f-ba9f-e4a5afdae24e.xml
    │   ├── [       7522]  README.html
    │   ├── [      39873]  logs
    │   │   ├── [        248]  FileUUIDs.log
    │   │   ├── [         36]  fileFormatIdentification.log
    │   │   ├── [       1773]  filenameChanges.log
    │   │   └── [      33720]  transfers
    │   │       └── [      29624]  test_report-22cb32f6-a691-4bcb-b718-262939262169
    │   │           └── [      25528]  logs
    │   │               ├── [       5802]  BagIt
    │   │               │   ├── [        877]  bag-info.txt
    │   │               │   ├── [         53]  bagit.txt
    │   │               │   ├── [        196]  tagmanifest-md5.txt
    │   │               │   └── [        580]  tagmanifest-sha512.txt
    │   │               ├── [      14866]  bulk-1b2db0bd-eefc-4b19-b286-117084f5bb44
    │   │               │   ├── [       1166]  exif.txt
    │   │               │   └── [       9604]  report.xml
    │   │               ├── [        607]  fileFormatIdentification.log
    │   │               └── [        157]  filenameChanges.log
    │   ├── [     105867]  objects
    │   │   ├── [        558]  invalid.tif
    │   │   ├── [      12653]  metadata
    │   │   │   └── [       8557]  transfers
    │   │   │       └── [       4461]  test_report-22cb32f6-a691-4bcb-b718-262939262169
    │   │   │           ├── [        167]  directory_tree.txt
    │   │   │           ├── [         51]  manifest-md5.txt
    │   │   │           └── [        147]  manifest-sha512.txt
    │   │   └── [      88560]  submissionDocumentation
    │   │       └── [      84464]  transfer-test_report-22cb32f6-a691-4bcb-b718-262939262169
    │   │           └── [      80368]  METS.xml
    │   └── [       5366]  thumbnails
    │       └── [       1270]  1b2db0bd-eefc-4b19-b286-117084f5bb44.jpg
    ├── [       3951]  manifest-sha512.txt
    └── [        430]  tagmanifest-sha512.txt

      693719 bytes used in 18 directories, 28 files
```

**Comment by melaniekung** [comment]
fix for this in [this pull request](https://github.com/artefactual/archivematica/pull/1799) for the next release (1.14.0)

**Comment by sromkey** [comment]
@melaniekung Would you be able to reopen this PR, or we can recreate it if that's complicated at the moment! Just let us know on this issue, thanks!

**Comment by sromkey** [comment]
I have tested for 1.14 and this is fixed (both in Admin tab and in the email report)
