### ISSUE TITLE
Problem: GPG/TRANSFORMKEY being lost when reingesting an encrypted AIP

### ISSUE THREAD

**Issue by ross-spencer** [archivematica/Issues#803]
**Expected behaviour**

Encryption information is preserved between pointer files following re-ingest.

**Current behaviour**

The `TRANSFORMKEY` is currently being stripped when an encrypted package is re-ingested.

**Steps to reproduce**

1. Setup encryption.
2. Store an AIP.
3. Download the pointer file. You'll see something like:
```xml
<mets:fileGrp USE="Archival Information Package">
      <mets:file ID="file-encrypt2-b903596e-600b-4057-9fb0-d9fd96a3f0df" GROUPID="Group-b903596e-600b-4057-9fb0-d9fd96a3f0df" ADMID="amdSec_9">
        <mets:FLocat xlink:href="/var/archivematica/sharedDirectory/www/AIPsStoreEncrypted/b903/596e/600b/4057/9fb0/d9fd/96a3/f0df/encrypt2-b903596e-600b-4057-9fb0-d9fd96a3f0df.7z" LOCTYPE="OTHER" OTHERLOCTYPE="SYSTEM"/>
        <mets:transformFile TRANSFORMKEY="EADE57C20EE40B97A3720013F7D8CDC4BFF25DBB" TRANSFORMTYPE="decryption" TRANSFORMORDER="1" TRANSFORMALGORITHM="GPG"/>
        <mets:transformFile TRANSFORMTYPE="decompression" TRANSFORMORDER="2" TRANSFORMALGORITHM="bzip2"/>
      </mets:file>
    </mets:fileGrp>
```
4. Reingest and download the pointer file, you will see something like:
```xml
    <mets:fileGrp USE="Archival Information Package">
      <mets:file ID="file-encrypt2-b903596e-600b-4057-9fb0-d9fd96a3f0df" GROUPID="Group-b903596e-600b-4057-9fb0-d9fd96a3f0df" ADMID="amdSec_11">
        <mets:FLocat xlink:href="/var/archivematica/sharedDirectory/www/AIPsStoreEncrypted/b903/596e/600b/4057/9fb0/d9fd/96a3/f0df/encrypt2-b903596e-600b-4057-9fb0-d9fd96a3f0df.7z" LOCTYPE="OTHER" OTHERLOCTYPE="SYSTEM"/>
        <mets:transformFile TRANSFORMTYPE="decompression" TRANSFORMORDER="1" TRANSFORMALGORITHM="bzip2"/>
      </mets:file>
    </mets:fileGrp>
```

**Your environment (version of Archivematica, OS version, etc)**

Docker compose running `1.10-rc1`.

**Additional context**

1. It would be great to verify this on an updated test-server (test-servers likely need to be updated because of https://github.com/archivematica/Issues/issues/684 (thanks @cole for pulling that issue up for me)). 
2. I can't establish a severity of this issue at the moment as I can't confirm the feature beyond the pointer file is working as anticipated. 

**NB.** Chatted to @sromkey shortly after the AM weekly. I wanted to confirm that this was a regression, and we thing so following the AMAUAT entry [here](https://github.com/artefactual-labs/archivematica-acceptance-tests/blob/7ee476d4b06c1ea6192374f80dbee7c9e04ef75f/features/core/aip-encryption.feature#L104-L111). I will add the `triage-1.11` tag as we also discussed that and the documentation approach might be enough for now. 

Additionally, this is also related to https://github.com/archivematica/Issues/issues/831 as it is another regression related to pointer files. 

**Feature file**

This feature belongs [here](https://github.com/artefactual-labs/archivematica-acceptance-tests/blob/47ac0f3719d0cb6b2735709b357bc7837e35e6ff/features/core/aip-encryption.feature) once this issue is fixed. It has been removed for now from the AMAUAT tessts:
```
@reencrypt-different-key
Scenario: Richard wants to confirm that he can re-encrypt an encrypted AIP with a new key. He has encrypted an AIP with GPG key A in space S. He later changed space S to use the more secure GPG key B. He wants to decrypt the AIPs encrypted with A and re-encrypt them with key B. Finally, he wants to delete the now unused key A from the storage service.
    Given there is a standard GPG-encrypted space in the storage service
    And an encrypted AIP in the standard GPG-encrypted space
    When the user creates a new GPG key and assigns it to the standard GPG-encrypted space
    And the user initiates a metadata-only re-ingest on the AIP
    And the user waits for the "Approve AIP reingest" decision point to appear and chooses "Approve AIP reingest" during ingest
    And the user downloads the AIP pointer file
    Then the AIP pointer file references the fingerprint of the new GPG key
```

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Done:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by replaceafill** [comment]
It seems this was caused by https://github.com/artefactual/archivematica-storage-service/pull/466 where the logic to read and write the pointer file of the reingest was changed from `lxml` to `metsrw`. At one point the original pointer file is read with `metsrw` in order to update it, but `metsrw` cannot parse `mets:transformFile` elements and those elements are lost. I've created https://github.com/artefactual-labs/mets-reader-writer/pull/78 to address that.

Now the `mets:fileSec` of the original pointer file looks like this:

```xml
  <mets:fileSec>
    <mets:fileGrp USE="Archival Information Package">
      <mets:file ID="file-pictures-1ece9355-9c9f-4073-84b2-42fd3eb25231" GROUPID="Group-1ece9355-9c9f-4073-84b2-42fd3eb25231" ADMID="amdSec_2">
        <mets:FLocat xlink:href="/var/archivematica/sharedDirectory/www/EncryptedAIPs/1ece/9355/9c9f/4073/84b2/42fd/3eb2/5231/pictures-1ece9355-9c9f-4073-84b2-42fd3eb25231.7z" LOCTYPE="OTHER" OTHERLOCTYPE="SYSTEM"/>
        <mets:transformFile TRANSFORMKEY="2EEF50B1409B6AE2ED0F685597132D745A7FA6D0" TRANSFORMTYPE="decryption" TRANSFORMORDER="1" TRANSFORMALGORITHM="GPG"/>
        <mets:transformFile TRANSFORMTYPE="decompression" TRANSFORMORDER="2" TRANSFORMALGORITHM="bzip2"/>
      </mets:file>
    </mets:fileGrp>
  </mets:fileSec>
```

And the `mets:fileSec` of the reingest (after simulating the `reencrypt-different-key` AMAUAT steps changing the encryption key of AIP Storage space) looks like this:

```xml
  <mets:fileSec>
    <mets:fileGrp USE="Archival Information Package">
      <mets:file ID="file-pictures-1ece9355-9c9f-4073-84b2-42fd3eb25231" GROUPID="Group-1ece9355-9c9f-4073-84b2-42fd3eb25231" ADMID="amdSec_4">
        <mets:FLocat xlink:href="/var/archivematica/sharedDirectory/www/EncryptedAIPs/1ece/9355/9c9f/4073/84b2/42fd/3eb2/5231/pictures-1ece9355-9c9f-4073-84b2-42fd3eb25231.7z" LOCTYPE="OTHER" OTHERLOCTYPE="SYSTEM"/>
        <mets:transformFile TRANSFORMALGORITHM="GPG" TRANSFORMTYPE="decryption" TRANSFORMORDER="1" TRANSFORMKEY="9930BB151314322119BBEE1F15F7420AB4DC4FF0"/>
        <mets:transformFile TRANSFORMTYPE="decompression" TRANSFORMORDER="2" TRANSFORMALGORITHM="bzip2"/>
        <mets:transformFile TRANSFORMTYPE="decompression" TRANSFORMORDER="1" TRANSFORMALGORITHM="bzip2"/>
      </mets:file>
    </mets:fileGrp>
  </mets:fileSec>
```

Even the `mets:transformFile` element with the `TRANSFORMKEY` has been updated you'll note two `mets:transformFile` elements for `decompression`. The implementation before https://github.com/artefactual/archivematica-storage-service/pull/466 explicitly [reset these elements before adding new](https://github.com/artefactual/archivematica-storage-service/blob/5fb80c554d3685dd3a81d182d64e70092ddcaa13/storage_service/locations/models/package.py#L3035-L3044) ones.

I'm now looking for a way to restore that behaviour and how https://github.com/archivematica/Issues/issues/1062 could affect it.

**Comment by sallain** [comment]
This is now working - a reingested AIP still has the key. @ross-spencer did you want to add the test back to the suite?
