### ISSUE TITLE
Problem: am/compose does not use Python 3

### ISSUE THREAD

**Issue by sallain** [archivematica/Issues#804]
**Please describe the problem you'd like to be solved.**
am/compose needs to use Python 3 as per the Python 3 [ADR](https://github.com/archivematica/archivematica-architectural-decisions).

**Describe the solution you'd like to see implemented.**
Refactor am/compose to use Python 3.

**Additional context**

---

**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Done:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by ross-spencer** [comment]
Closing as resolved/complete as it was verified that what was in-fact changing was the docker files associated with an environment, e.g. [here](https://github.com/artefactual/archivematica-storage-service/pull/480/commits/0772315a721946c3b9a5d86a2aef67cd9b9aace3) not the compose environment itself.
