### ISSUE TITLE
Refactor Archivematica to use Python 3

### ISSUE THREAD

**Issue by sallain** [archivematica/Issues#805]
**Please describe the problem you'd like to be solved**

Python 2 will not be supported past January 1, 2020. Archivematica is not fully
compatible with Python 3 yet. To avoid security and compatibility issues after
this date, Archivematica and all of its required components will need to run in
a Python 3 environment.

**Describe the solution you'd like to see implemented**

Refactor Archivematica and all required components to Python 3 by the end of 2019.

**Additional context**

* Architectural Decision Record (work in progress) for Python 3: https://github.com/archivematica/archivematica-architectural-decisions/pull/4
* @alexwlchan (Wellcome Trust) has created a Python3-compatible fork of python-gearman for Archivematica (see [gearman3](https://github.com/wellcometrust/python-gearman)).
* TravisCI has been used to test against Python 3 since it was set up back in 2017.
* This issue replaces:
  * #572, so that we can take advantage of Codetree's epic formatting
  * [Redmine #6079](https://projects.artefactual.com/issues/6079)
  * [Redmine #10564](https://projects.artefactual.com/issues/10564)

**Comment by dcraze** [comment]
###### do-not-edit-start-codetree-epic-issues

#### Issues in this epic:

Title | Milestone | Assignees | State
----- | --------- | --------- | -----
![](https://cdnjs.cloudflare.com/ajax/libs/octicons/4.4.0/svg/issue-opened.svg) [Refactor am/compose to use Python 3 #804](https://github.com/archivematica/Issues/issues/804) | N/A | N/A | Open


###### do-not-edit-end-codetree-epic-issues

**Comment by sromkey** [comment]
:snake: :tada: :cake: !
