### ISSUE TITLE
Problem: MCPserver does not use Python 3

### ISSUE THREAD

**Issue by sallain** [archivematica/Issues#807]
**Please describe the problem you'd like to be solved.**
[MCPserver](https://github.com/artefactual/archivematica/tree/a889605d8c97e114f8c0bc707d6a371030fb5c0b/src/MCPServer) needs to use Python 3 as per the Python 3 [ADR](https://github.com/archivematica/archivematica-architectural-decisions).

**Describe the solution you'd like to see implemented.**
Refactor MCPserver to use Python 3.

**Additional context**

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Done:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by sallain** [comment]
Related: #392

**Comment by ross-spencer** [comment]
From internal discussions we believe the MCP Server to be a good candidate to tackle early for `1.12`. Seeking to finalize any work required to run it using Python 3. The MCP server work was held off previously to complete scheduled client improvements. Those were made in such a way as to be complementary to the Python 3 migration. The MCP Server is also a neater encapsulation than some other pieces so should be relatively straightforward to do this with. It is likely a large part of MCP Server will be affected by https://github.com/archivematica/Issues/issues/809 and so the work on Archivematica-common -> Py3 will also need to be considered in scope.

**Notes on Python 2.7 in 2020:**

Python 2.7 final release in July 2020: [here](https://www.python.org/dev/peps/pep-0373/#id5)
Ubuntu 20.04 (LTS) and Python 2.7: [here](https://www.phoronix.com/scan.php?page=news_item&px=Ubuntu-20.04-Continue-Py2-Drop)
Python3 may be default in CentOS8/RHEL8: [here](https://developers.redhat.com/blog/2018/11/14/python-in-rhel-8/)
