### ISSUE TITLE
Problem: MCPClient does not use Python 3

### ISSUE THREAD

**Issue by sallain** [archivematica/Issues#808]
**Please describe the problem you'd like to be solved.**
[MCPClient](https://github.com/artefactual/archivematica/tree/a889605d8c97e114f8c0bc707d6a371030fb5c0b/src/MCPClient) needs to use Python 3 as per the Python 3 [ADR](https://github.com/archivematica/archivematica-architectural-decisions).

**Describe the solution you'd like to see implemented.**
Refactor MCPClient to use Python 3.

**Additional context**

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Done:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by sallain** [comment]
Related: #392

**Comment by helenst** [comment]
The fido command needs fixing. I played around with getting it to work but I don't have time to fully integrate it right now.

The following should work:

```
import os.path
import re
import subprocess
import sys

def file_tool(path):
    return subprocess.check_output(['file', path]).strip().decode("utf8")

class FidoFailed(Exception):
    def __init__(self, stdout, stderr, retcode):
        message = """ 
Fido exited {retcode} and no format was found.
stdout: {stdout}
---
stderr: {stderr}
""".format(stdout=stdout, stderr=stderr, retcode=retcode)
        super(FidoFailed, self).__init__(message)

def identify(file_):
    # The default buffer size fido uses, 256KB, is too small to be able to detect certain formats
    # Formats like office documents and Adobe Illustrator .ai files will be identified as other, less-specific formats
    # This larger buffer size is a bit slower and consumes more RAM, so some users may wish to customize this to reduce the buffer size
    # See: https://projects.artefactual.com/issues/5941, https://projects.artefactual.com/issues/5731
    cmd = ['fido', '-bufsize', '1048576',
           '-loadformats', '/usr/lib/archivematica/archivematicaCommon/externals/fido/archivematica_format_extensions.xml',
           os.path.abspath(file_)]
    process = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE, stdin=subprocess.PIPE)
    stdout, stderr = process.communicate()

    try:
        results = stdout.decode("utf8").split('\n')[0].split(',')
    except Exception as e:
        print(e)
        raise FidoFailed(stdout, stderr, process.returncode)

    if process.returncode != 0 or results[-1] == '"fail"':
        raise FidoFailed(stdout, stderr, process.returncode)
    else:
        puid = results[2]
        if re.match('(.+)?fmt\/\d+', puid):
            return puid
        else:
            sys.stderr.write("File identified as non-standard Fido code: {id}\n".format(id=puid))
            return "" 

def main(argv):
    try:
        print(identify(argv[1]))
        return 0
    except FidoFailed as e:
        file_output = file_tool(argv[1])
        # FIDO can't currently identify text files with no extension, and this
        # is a common enough usecase to special-case it
        if 'text' in file_output:
            print('x-fmt/111')
        else:
            return e
    except Exception as e:
        return e

if __name__ == '__main__':
    exit(main(sys.argv))
```

Mostly print statements, and a `decode`.

**Comment by ross-spencer** [comment]
From internal discussions MCP Client will be held off until `1.12` and we will see what we can achieve, pushing the rest to `1.13`. Detailed notes on this:

* We can cherry-pick what we can. 
* Previous migration work is very much in draft. 
* Questions remain around FPR and MCP Client scripts and finding a path of least resistance toward migrating them without having to write, for example, entire, brand-new Django migrations.

**MCP Client structure**

* The MCP Client can be looked as three layers:
   * Low-level MCP client architecture, the bit that communicates with the server and dashboard. This is looking okay as part of the initial sprint, but isn't yet perfect.
   * MCP Client scripts aka Microservice Jobs: These are the microservices as we know them! These all need to be looked at one-by-one and tested throughout each transfer type in Archivematica.
   * FPR scripts: These are executed optionally by some MCP Client scripts in the MCP Client virtual environment. These exist in the database, and in the current work we’ve done would require DB migrations to update, and are difficult to test. In an alternative world-view we might try and avoid this. 

By the end of `1.12` we may still need to run as Python 2. We anticipate Python 3 by `1.13`. Depending on Python 2.7 restrictions in 2020.

**Notes on Python 2.7 in 2020:**

Python 2.7 final release in July 2020: [here](https://www.python.org/dev/peps/pep-0373/#id5)
Ubuntu 20.04 (LTS) and Python 2.7: [here](https://www.phoronix.com/scan.php?page=news_item&px=Ubuntu-20.04-Continue-Py2-Drop)
Python3 may be default in CentOS8/RHEL8: [here](https://developers.redhat.com/blog/2018/11/14/python-in-rhel-8/)
