### ISSUE TITLE
Problem: mets-reader-writer does not use Python 3 (metsrw)

### ISSUE THREAD

**Issue by sallain** [archivematica/Issues#811]
**Please describe the problem you'd like to be solved.**
[mets-reader-writer](https://github.com/artefactual-labs/mets-reader-writer) needs to use Python 3 as per the Python 3 [ADR](https://github.com/archivematica/archivematica-architectural-decisions).

**Describe the solution you'd like to see implemented.**
Refactor mets-reader-writer to use Python 3.

**Additional context**
Some Python 3 compatibility work has already been done on mets-reader-writer. This component should be checked to ensure that all code has been refactored.

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Done:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by sallain** [comment]
Related: #580

**Comment by jraddaoui** [comment]
The mets-reader-writer CI already run the tests in 2.7 and 3.5 to 3.7 and the PR above adds 3.8 to that list. The coverage seems to be pretty good:

```
Name                                  Stmts   Miss Branch BrPart  Cover
-----------------------------------------------------------------------
metsrw/__init__.py                       15      0      0      0   100%
metsrw/di.py                             80      6     28      4    89%
metsrw/exceptions.py                      4      0      0      0   100%
metsrw/fsentry.py                       233     16    101      7    92%
metsrw/metadata.py                      291      6    112      8    96%
metsrw/mets.py                          325     12    137     12    94%
metsrw/plugins/__init__.py                0      0      0      0   100%
metsrw/plugins/premisrw/__init__.py       8      0      0      0   100%
metsrw/plugins/premisrw/premis.py       405     21    177     12    94%
metsrw/plugins/premisrw/utils.py         43      0      6      0   100%
metsrw/utils.py                          17      0      4      0   100%
metsrw/validate.py                       67      7     16      5    86%
-----------------------------------------------------------------------
TOTAL                                  1488     68    581     48    94%
```
