### ISSUE TITLE
Problem: ammcpc does not use Python 3

### ISSUE THREAD

**Issue by sallain** [archivematica/Issues#812]
**Please describe the problem you'd like to be solved.**
[ammcpc](https://github.com/artefactual-labs/ammcpc) needs to use Python 3 as per the Python 3 [ADR](https://github.com/archivematica/archivematica-architectural-decisions).

**Describe the solution you'd like to see implemented.**
Refactor ammcpc to use Python 3.

**Additional context**

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Done:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by jraddaoui** [comment]
Tests from ammcpc seem to be passing in Python 2.7 and 3.6 to 3.8, no idea about coverage ...

https://travis-ci.org/github/artefactual-labs/ammcpc
