### ISSUE TITLE
Problem: automation-tools does not use Python 3

### ISSUE THREAD

**Issue by sallain** [archivematica/Issues#815]
**Please describe the problem you'd like to be solved.**
[automation-tools](https://github.com/artefactual/automation-tools) needs to use Python 3 as per the Python 3 [ADR](https://github.com/archivematica/archivematica-architectural-decisions).

**Describe the solution you'd like to see implemented.**
Refactor automation-tools to use Python 3.

**Additional context**

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Done:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by ross-spencer** [comment]
This was verified as working in Python 3 by Tim so marking as resolved. Tim noted a test assertion we have a problem with across environments and outside of Travis in Py2 and Py3 we need to follow up on [at this line](https://github.com/artefactual/automation-tools/blob/master/tests/test_create_dip.py#L129).

**NB** https://travis-ci.org/artefactual/automation-tools CI was set at Python 3.6, but have added 3.5 [here](https://github.com/artefactual/automation-tools/pull/124) and it passes as anticipated. So moving this to done and we can merge that PR shortly.
