### ISSUE TITLE
Problem: amclient does not use Python 3

### ISSUE THREAD

**Issue by sallain** [archivematica/Issues#817]
**Please describe the problem you'd like to be solved.**
[amclient](https://github.com/artefactual-labs/amclient) needs to use Python 3 as per the Python 3 [ADR](https://github.com/archivematica/archivematica-architectural-decisions).

**Describe the solution you'd like to see implemented.**
Refactor amclient to use Python 3.

**Additional context**
Some Python 3 compatibility work has already been done on amclient. This component should be checked to ensure that all code has been refactored.

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Done:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by ross-spencer** [comment]
Travis CI updated to add Python 3.5 [here[(https://github.com/artefactual-labs/amclient/pull/9). With hte test coverage and where the amclient is called through tools such as automated-acceptance-tests or automation-tools in Python 3 we can have reasonable confidence that this works as anticipated. Some final verification might just be needed.

**Comment by replaceafill** [comment]
Verified this by creating a Python 3 virtualenv and installing the `amclient` package. Ran the tests and issued a few commads (list SS locations, create package, etc)
