### ISSUE TITLE
Problem: Files that have already been arranged are not greyed out on Appraisal tab

### ISSUE THREAD

**Issue by peterVG** [archivematica/Issues#821]
**Expected behaviour**
The files that have already been processed into a SIP using the 'tag and select' feature appear greyed out in the Backlog pane and can no longer be selected for inclusion into a new SIP.

**Current behaviour**
Already selected files are not greyed out. (they can't be selected for inclusion in a new SIP, an error message does appear).

**Steps to reproduce**
Create a SIP on the Appraisal tab using the "tag and select" method. Create a second SIP and look at the available files in the Backlog pane. Files that were included in the first SIP are not greyed out.

**Your environment (version of Archivematica, OS version, etc)**
AM 1.9.1 qa

related to issue #369

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Done:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by sallain** [comment]
As long as I refresh the page after creating the SIP per the method that Peter describes above, the files are greyed out and struck-through, which is good enough for me!
