### ISSUE TITLE
Problem: Directories are greyed out while they still contain files available for arrangement

### ISSUE THREAD

**Issue by peterVG** [archivematica/Issues#822]
**Expected behaviour**
On the Appraisal tab's backlog pane, if a directory contains files that have not yet been included in a SIP, the parent directory is not greyed out. The directory is only greyed out if all of the files it contains have been included in SIPs.

**Current behaviour**
When using the "tag and select" SIP creation method, the parent directory on the backlog pane will be greyed out if any of its files are included in the SIP, even if it still contains some unselected files.

**Steps to reproduce**
Create a SIP on the Appraisal tab using the "tag and select" method, selecting some files from a directory but not all. Create a second SIP and look at the available files in the Backlog pane. Directories that were included in the first SIP are greyed out.

**Your environment (version of Archivematica, OS version, etc)**
AM 1.9.1 QA

related to issue #369 

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Done:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by replaceafill** [comment]
I just discovered this issue is also present in 1.9 and it wasn't a regression introduced by the log/metadata changes as I first thought. Here's a screenshot from the AM sandbox (currently on 1.9):

![Captura de pantalla de 2019-07-25 23-11-59](https://user-images.githubusercontent.com/560781/61927367-c97a3b00-af31-11e9-8fd7-536e64f10c31.png)

As you can see a folder seems to be greyed out when its first (file?) child node has also been greyed out.

**Comment by sallain** [comment]
@replaceafill Yes, now that you write that out I realize that you're right, it's been an issue in the Appraisal tab all along. Going to propose that we leave this for 1.11 as it's not a regression.

**Comment by sallain** [comment]
This is now working as expected - the top-level directory is not greyed out/struck-through as long as there are objects remaining in the backlog.

![Screenshot of Archivematica Dashboard - Appraisal.jpg](https://codetreeusercontent.s3.amazonaws.com/uploads/b008ed1b-50db-4d79-95ea-b329f35b87cd/Screenshot+of+Archivematica+Dashboard+-+Appraisal.jpg)

**Comment by sallain** [comment]
NTS: check screenshots and update if needed.
