### ISSUE TITLE
Problem: Bulk Extractor CC/SSN results not displayed in Appraisal tab

### ISSUE THREAD

**Issue by sallain** [archivematica/Issues#824]
**Expected behaviour**
The Appraisal tab gives users a chance to review the outputs for two Bulk Extractor flags - credit card numbers and social security numbers (PII). A given file has to meet a few conditions:

* It has to contain a credit card number that Bulk Extractor recognizes
* **Yes** has to be selected for _Examine contents_ during transfer
* It has to be sent to the backlog

Assuming the above, when the file is selected in the backlog pane of the Appraisal tab, the user can view the outputs by selecting Analysis > Examine contents > Credit card numbers. It should look like this:

![image](https://user-images.githubusercontent.com/4612276/61669705-d7ac2b00-ac95-11e9-998f-f23a84444904.png)

**Current behaviour**

In the current qa, the outputs are not being shown in the Appraisal tab.

![image](https://user-images.githubusercontent.com/4612276/61669670-c105d400-ac95-11e9-8b3f-2cda63c81792.png)

Note that the Bulk Extractor logs are present in the AIP, so it looks like Bulk Extractor is being triggered properly.

**Steps to reproduce**

Run a transfer using SampleTransfers/DemoTransferCSV, ensuring that "Yes" is selected for Examine Contents.

**Your environment (version of Archivematica, OS version, etc)**
qa (1.10) on xenial and bionic

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Done:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by sallain** [comment]
My uneducated guess is that the path to the BE logs is hard-coded and that the path changed because of the SFU work to make the backlog package bag-compliant.

**Comment by replaceafill** [comment]
I'm working around the appraisal tab at the moment so I decided to investigate this. You are correct @sallain. The two paths that need to be updated for this to work again are:

- [The helper to index the bulk extractor reports](https://github.com/artefactual/archivematica/blob/c63c1195e61b39cc53ad9f176059b3dae854b04e/src/archivematicaCommon/lib/elasticSearchFunctions.py#L903)
- [The file view that gets the report information from the SS](https://github.com/artefactual/archivematica/blob/c63c1195e61b39cc53ad9f176059b3dae854b04e/src/dashboard/src/components/file/views.py#L160)

If I change these two paths in my dev instance to include the "data" directory introduced by the bags work I can see the "Content | Context" columns again.
