### ISSUE TITLE
Problem: derivation relationship isn't being written to pointer files that are derived from a source AIP

### ISSUE THREAD

**Issue by ross-spencer** [archivematica/Issues#831]
**Expected behaviour**

Spotted by @replaceafill. According to the AMAUAT acceptance tests then a derivation relationship is written to the pointer file for an AIP created from a source AIP. See [this line](https://github.com/artefactual-labs/archivematica-acceptance-tests/blob/47ac0f3719d0cb6b2735709b357bc7837e35e6ff/features/core/aip-encryption-mirror.feature#L56).

**Current behaviour**

This event is not written and so the AMAUAT test fails, and we're not writing potentially important information to the pointer file as anticipated. 

**Steps to reproduce**

1. Setup replication in `1.10-rc`.
2. Create a compressed AIP. 
3. View both pointer files created, only the source will have the derivation relationship object. 

E.g. 
```xml
    <premis:relationship>
      <premis:relationshipType>derivation</premis:relationshipType>
      <premis:relationshipSubType></premis:relationshipSubType>
      <premis:relatedObjectIdentifier>
        <premis:relatedObjectIdentifierType>UUID</premis:relatedObjectIdentifierType>
        <premis:relatedObjectIdentifierValue>4765411d-bbd8-47cd-88d6-29c65b140bc8</premis:relatedObjectIdentifierValue>
      </premis:relatedObjectIdentifier>
      <premis:relatedEventIdentifier>
        <premis:relatedEventIdentifierType>UUID</premis:relatedEventIdentifierType>
        <premis:relatedEventIdentifierValue>30bcf685-faf0-47db-9a95-2413e0e4ed4f</premis:relatedEventIdentifierValue>
      </premis:relatedEventIdentifier>
    </premis:relationship>
```

**Your environment (version of Archivematica, OS version, etc)**

Archivematica `1.10-rc`.

**Additional context**

I cannot verify how far this regression goes as the replicated AIPs associated with http://am19xenial.qa.archivematica.org seem to have non-conforming pointer files, and creating a new replicated package today is failing. We also recognize it is likely AMAUAT wasn't run on `1.9` before the final release as the recent AMAUAT fix-up work is correcting some issues introduced in `1.9`. 

Related to https://github.com/archivematica/Issues/issues/803 which is also a regression in the pointer file. 

Related to https://github.com/archivematica/Issues/issues/795 where the aip-encrypt-mirror test has the following line `And the replica AIP pointer file contains a PREMIS:OBJECT with a derivation relationship pointing to the master AIP and the replication PREMIS:EVENT` commented out to make it pass. 

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Done:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by sromkey** [comment]
@evelynPM could you take a look at an example and give us an assessment?

**Comment by evelynPM** [comment]
I am seeing the derivation relationship in the pointer files for both the source and replicated AIPS on my 1.10.1 test instance. However, in both pointer files, only the relationshipType semantic unit is being used. So it looks like this:
`<premis:relationship><premis:relationshipType>derivation</premis:relationshipType> 
  <premis:relationshipSubType/>`

What's missing is a value for the relationshipSubType semantic unit. It should be the same as what we do for the AIP METS file for relationships between original and normalized versions of a file, i.e. "has source" or "is source of". So for a replicated AIP, the output should look like this:
`<premis:relationshipType>derivation</premis:relationshipType>
  <premis:relationshipSubType>has source</premis:relationshipSubType>`

**Comment by evelynPM** [comment]
Closing this issue because the relationship container is present in the pointer files for replicated AIPs in 1.10.1. I've created a new issue for the lack of relationshipSubType values.
