### ISSUE TITLE
Problem: METS file fails validation when DC metadata present

### ISSUE THREAD

**Issue by evelynPM** [archivematica/Issues#843]
**Expected behaviour**
METS file with DC metadata validates in validators such as https://www.freeformatter.com/xml-validator-xsd.html. 

**Current behaviour**
METS file fails validation with the following error: `White Spaces Are Required Between PublicId And SystemId., Line '1', Column '50'.`
This appears to be happening because the DC schema has changed from http to https. So the problem can be rectified by changing the schema location URL in the DC namespace declaration as follows: 
`http://dublincore.org/schemas/xmls/qdc/2008/02/11/dcterms.xsd"` to 
` https://dublincore.org/schemas/xmls/qdc/2008/02/11/dcterms.xsd"`.
No other change seems to be needed.

**Steps to reproduce**
Create an AIP with DC metadata either entered via the GUI or ingested via CSV. Run the METS file through a validator.

**Your environment (version of Archivematica, OS version, etc)**

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Done:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by ross-spencer** [comment]
Spotted this convo in Slack - the change is possibly related to this possible 'hack' of the URIs in early July: https://twitter.com/DublinCore/status/1146010931840897025

![image](https://user-images.githubusercontent.com/1880412/62266199-a5ce5d80-b427-11e9-946b-2a2ab6038b13.png)

**Comment by sallain** [comment]
METS that includes DC metadata now validates using https://www.freeformatter.com/xml-validator-xsd.html.
