### ISSUE TITLE
Problem: New checksum verification requirements need an objects directory (but there may be a better way)

### ISSUE THREAD

**Issue by ross-spencer** [archivematica/Issues#844]
**Please describe the problem you'd like to be solved.**

Hashdeep utilities were replaced with hashsum from coreutils, and initial testing showed that to get the accuracy needed to verify checksums in a Archivematica transfer correctly, the `objects' directory would need to be encoded in the checksum  manifest itself. This is a reasonable sized change that does require users to modify workflows, and so was never particularly desirable, and the decision not made in isolation, nor without reasonable review and consultation. Some of this conversation is documented in the original ticket and the [PR](https://github.com/artefactual/archivematica/pull/1333#issue-244882096).

**Describe the solution you'd like to see implemented.**

With a little distance from the work, it seems that perhaps the `cwd` argument can also be set [here](https://github.com/artefactual/archivematica/blob/e9896baebb511ffd8f7aa6490c133c01e1a0399a/src/MCPClient/lib/clientScripts/verify_checksum.py#L105-L107) to point to the objects directory and still validate against the checksum files in the corresponding manifests. 

**Describe alternatives you've considered.**

Given we're so close to a release, reverting this change requires a bit of extra effort in testing, so it is perhaps more risky, but the effort required to change workflows is perhaps a bigger risk, if it doesn't need to be done. 

**Additional context**

Original bugfix tickets were:

Connected to archivematica/issues#346 
Connected to artefactual/archivematica#1061 

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Done:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by sallain** [comment]
This looks good - checksums included in transfers (in a bag or otherwise) are working as expected, and the resulting checksum manifest in the AIP bag looks great.
