### ISSUE TITLE
Problem: Gearman is not compatible with Python 3

### ISSUE THREAD

**Issue by ross-spencer** [archivematica/Issues#845]
The details for this ticket are here: https://github.com/archivematica/Issues/issues/573 

This is a duplicate to enable planning via Codetree. 

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Done:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by ross-spencer** [comment]
Comment left [here](https://github.com/wellcometrust/python-gearman/issues/10#issuecomment-522111367) with Alex. I think technically this should remain `in progress` though it is also technically blocked for now, and simultaneously in review? 🤯 We have enough to work with in the other Archivematica components right now. Once Alex completes that work, we will need to test a) it continues to work, and b) understand if we need to make any further changes as a result.

**Comment by sallain** [comment]
@ross-spencer Thanks - I think it's fine to leave it `in progress`.

**Comment by ross-spencer** [comment]
From internal discussions we have two approaches to this work now:

1. Fortify the current fork of Wellcome's work and bring it into the Artefactual-labs repository and run from a commit in `requirements.txt`. This is a low-impact, low-barrier approach to getting the Dashboard up and running in Python 3. We'd look to make a PR against the Wellcome branch asap.
2. Discuss with Wellcome their commitment to finishing the branch, and combining some of 1. effort, or seeking an updated published branch from them to work on.

We have what we need for now to keep pushing https://github.com/archivematica/Issues/issues/810 forward. `1.11` is expected to be published early February 2020.

**Notes on Python 2.7 in 2020:**

Python 2.7 final release in July 2020: [here](https://www.python.org/dev/peps/pep-0373/#id5)
Ubuntu 20.04 (LTS) and Python 2.7: [here](https://www.phoronix.com/scan.php?page=news_item&px=Ubuntu-20.04-Continue-Py2-Drop)
Python3 may be default in CentOS8/RHEL8: [here](https://developers.redhat.com/blog/2018/11/14/python-in-rhel-8/)

**Comment by ross-spencer** [comment]
I have created a draft PR on the Wellcome repo: [here](https://github.com/wellcometrust/python-gearman/pull/12)

We can run this via our requirements in the dashboard, and MCP Client and Server with:
```
https://github.com/ross-spencer/python-gearman@82fb2b4431fa5ffc89cd70eb1ff3c61a4d2f2512#egg=gearman3
```
Ideally, we'd bring this into `artefactual-labs` but we have a fork of the standard Python Gearman there which is in conflict with another fork. So:

1. We can decide what to do with our fork in artefactual-labs.
2. Ideally fork my changes from `ross-spencer/python-gearman`.
3. Run from the commit. 

Best case scenario, is Alex accepts the changes, or a subset, and we can run from Wellcome's branch, or package on PyPi. 

**Testing notes**

As per the original development, I have been running our rpc-client to test for compatibility. That is:

* [here](https://github.com/ross-spencer/archivematica-rpc-client)

With changes to make it work with the latest python-gearman branch, and `qa/1.x`. To run:

* Ensure it is configured to talk to your Archivematica. 
* Ensure that there are decision points that need resolving in your transfer or ingest workflow.
* Attempt to interact with the workflow based on the screen prompts from running: `$ ./mcp-rpc-cli.py`.

**Comment by ross-spencer** [comment]
Just moving this back into `refining` and adding the two `triage` labels for discussion at backlog grooming as a potential to descope. 

Testing notes are [here](https://docs.google.com/document/d/1E1JefhZRz0zPRcLBl3shE9z5dEMzwXakuAKGZPFwdA0/edit#heading=h.h6jik9h501zb).

Our two approaches are:

* Profile the new gearman work and try and understand where the bottleneck's are. We might not be able to achieve all that is required for this during our remaining 1.11 development window as profiling will also determine further development that is required.
* Continue to review the Dashboard changes now in isolation and merge those that we are comfortable with as being compatible with Python 2 and continue to run Python 2 in the short-term. Similar to the work we are close to completing with the [storage-service](https://github.com/artefactual/archivematica-storage-service/pull/519).

**Comment by replaceafill** [comment]
Taking Ross' performance analysis into account what we plan to do for `1.13.0` is to use [environment markers](https://www.python.org/dev/peps/pep-0508/#environment-markers) to keep the `gearman 2.0.2` package in Python 2 and use `gearman3 0.2.0` for Python 3.
