### ISSUE TITLE
Problem: Fido does not use Python 3

### ISSUE THREAD

**Issue by sallain** [archivematica/Issues#847]
This is a placeholder ticket for upgrading Fido to Python 3, created just so that we can track this work alongside the rest of the Python 3 project in Codetree.

Any work done should be reported on openpreserve/fido#79 rather than this ticket.

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Done:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by ross-spencer** [comment]
RC1 is available: [here](https://github.com/openpreserve/fido/releases/tag/v1.4.0rc1) via @ablwr and @carlwilson.

**Comment by carlwilson** [comment]
Thanks @ross-spencer I'll add that we'll be promoting the release candidate this week all been well.

**Comment by sromkey** [comment]
Fido 1.4.0 has been released which supports Python 3: https://github.com/openpreserve/fido/releases/tag/v1.4.0
