### ISSUE TITLE
Enhancement: Transfer Microservices/Tasks Gear opens up new tab

### ISSUE THREAD

**Issue by sallain** [archivematica/Issues#85]
_From @rogerlayton on July 11, 2018 12:29_

The Gear icon always opens up a new Tab in the Web Browser. This can lead to many open tabs.

Could this be changed to always open up in the same named Tab?

Alternatively, a setting to allow user to specific whether this should be new tab, new window or named window.

_Copied from original issue: artefactual/archivematica#1205_

**Comment by Slange-Mhath** [comment]
Hey, 
I was able to restore the default browser behavior so that clicking on the gear icon won't open a new tab or window. However, I am very unsure whether this is really a desirable outcome in terms of usability, as it means that the user has to navigate back to the dashboard again and again.

**Comment by sromkey** [comment]
I like @ross-spencer 's suggestion above, and if that's not feasible I would agree @Slange-Mhath - I don't think it's desirable actually to have to keep navigating back to the dashboard- in that case I would favour just closing this issue as a "won't-fix."
