### ISSUE TITLE
Problem: metadata only DIP upload fails with files without format version

### ISSUE THREAD

**Issue by jraddaoui** [archivematica/Issues#857]
**Expected behaviour**
Metadata only DIP upload to AtoM is performed correctly.

**Current behaviour**
It may fail at some point if one the files doesn't contain a format version in the METS file, creating only part of the resources in AtoM.

**Steps to reproduce**
In a default installation, create an AIP from the `SampleTransfers/Images` directory. From the AIP page in the dashboard, trigger a metadata only DIP upload ot an existing AtoM slug.

**Your environment (version of Archivematica, OS version, etc)**
RC-1.10, Docker Compose environment.

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Done:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by jraddaoui** [comment]
The error log ...

```
ERROR     2019-08-12 16:33:28  django.request:base:handle_uncaught_exception:256:  Internal Server Error: /archival-storage/4a2a0c37-331d-438c-b3d3-d8167f59d589/
 Traceback (most recent call last):
   File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
     response = wrapped_callback(request, *callback_args, **callback_kwargs)
   File "/src/dashboard/src/components/archival_storage/views.py", line 592, in view_aip
     name, uuid, form_upload.cleaned_data["slug"]
   File "/src/dashboard/src/components/archival_storage/atom.py", line 115, in upload_dip_metadata_to_atom
     client.add_digital_object(slug, **attrs)
   File "/usr/local/lib/python2.7/site-packages/agentarchives/atom/client.py", line 582, in add_digital_object
     new_object['slug'] = self._post(urljoin(self.base_url, 'digitalobjects'), data=json.dumps(new_object), expected_response=201).json()['slug']
   File "/usr/local/lib/python2.7/json/__init__.py", line 244, in dumps
     return _default_encoder.encode(obj)
   File "/usr/local/lib/python2.7/json/encoder.py", line 207, in encode
     chunks = self.iterencode(o, _one_shot=True)
   File "/usr/local/lib/python2.7/json/encoder.py", line 270, in iterencode
     return _iterencode(o, 0)
   File "/usr/local/lib/python2.7/json/encoder.py", line 184, in default
     raise TypeError(repr(o) + " is not JSON serializable")
 TypeError: ('format_version',) is not JSON serializable
```

Part of the related XML from the METS file, parsed by `mets-reader-writer` ...

```
<premis:size>125968</premis:size>
<premis:format>
  <premis:formatDesignation>
    <premis:formatName>Tagged Image File Format</premis:formatName>
    <premis:formatVersion></premis:formatVersion>
  </premis:formatDesignation>
  <premis:formatRegistry>
    <premis:formatRegistryName>PRONOM</premis:formatRegistryName>
    <premis:formatRegistryKey>fmt/353</premis:formatRegistryKey>
  </premis:formatRegistry>
</premis:format>
```

**Comment by jraddaoui** [comment]
Related `mets-reader-writer` issue: https://github.com/archivematica/Issues/issues/743 (thanks @sevein!).

In this case we're trying to access the properties with `getattr` in [here](https://github.com/artefactual/archivematica/blob/qa/1.x/src/dashboard/src/components/archival_storage/atom.py#L42-L63).

**Comment by sallain** [comment]
This is working!
