### ISSUE TITLE
Problem: Snippet of code is incorrect in start_reingest in the storage service

### ISSUE THREAD

**Issue by ross-spencer** [archivematica/Issues#863]
**Expected behaviour**

Errors are robust enough to return as expected.

**Current behaviour**

This [snippet of code](https://github.com/artefactual/archivematica-storage-service/blob/946a513da208f96c87b00f0ae86ad011d7e9baac/storage_service/locations/models/package.py#L1979-L1983) is malformed: 
```python
            return {
                'error': True,
                'status_code': 412,
                'message': _('No currently processing Location is associated with pipeline %(uuid)s') % {'pipeline': pipeline.uuid},
            }
```
I'm not familiar with the syntax, but it could be replaced with:
```python
            return {
                "error": True,
                "status_code": 412,
                "message": _(
                    "No currently processing Location is associated with pipeline {}"
                ).format(pipeline.uuid),
            }
```
The error seems to be because the code is looking for a Unicode encoded key, but the keys aren't in-fact Unicode encoded. I'd need to understand the library better to understand more about this. 

**Steps to reproduce**

This is reproduced under specific reingest conditions which I'm not sure how to control yet. 

**Your environment (version of Archivematica, OS version, etc)**

Seen on a client's site. Can also be manipulated locally to recreate the same error with the syntax.

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Done:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by sevein** [comment]
Our practice is to use named-string interpolation because that gives more context to translators, e.g. `I am %(age)s` (compared to `I am %d`) gives more context to the translator.

You're probably right about the Unicode issue but I think it also seems that the key we're passing doesn't match the name of the placeholder. It expects `uuid` but we're using `placeholder`.

```python
>>> "I am %(age)s" % {"pipeline": 60}
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
KeyError: 'age'

>>> "I am %(age)s" % {"age": 60}
'I am 60'
```

**Comment by ross-spencer** [comment]
Ah! That simple eh? Thanks @sevein I appreciate the help.

**Comment by replaceafill** [comment]
This has been fixed in https://github.com/artefactual/archivematica-storage-service/pull/627/commits/ce617b55e7a33f51eaefa6bf6df782e51bead703
