### ISSUE TITLE
Problem: some jobs run even when disabled

### ISSUE THREAD

**Issue by sevein** [archivematica/Issues#866]
**Expected behaviour**
Archivematica should avoid doing unnecessary work that relates to tasks/jobs that have been disabled by the user in the processing configuration page. If possible, this should be done within the workflow, to avoid scheduling work to clients which is expensive.

**Current behaviour**
Certain jobs in Archivematica are dispatched to workers when the processing configuration was already telling us that they were not required. E.g. "Persistent identifier (PID) declaration", "Bind PID", "Bind PIDs" or "Transcribe". The last two are particularly harmful because they are scheduled for every single file belonging to the package, creating a lot of unnecessary overheads.

The following SQL queries show the time spent in jobs that were supposed to be disabled in a dataset with 1k files. Times are higher as the Tasks table grows.

```
select Jobs.jobUUID, jobType, microserviceGroup, timestampdiff(microsecond, min(startTime), max(endTime))/1000000 as spent, count(Tasks.jobUUID) as tasks from Jobs inner join Tasks on (Jobs.jobUUID = Tasks.jobUUID) where microserviceGroup = "Bind PIDs" group by jobType;
+--------------------------------------+-----------------------------------------+-------------------+--------+-------+
| jobUUID                              | jobType                                 | microserviceGroup | spent  | tasks |
+--------------------------------------+-----------------------------------------+-------------------+--------+-------+
| fa38395b-8913-46a8-9865-c9ee68aae2c2 | Bind PID                                | Bind PIDs         | 0.9649 |  1006 |
| e7924dfc-0452-4643-861d-32aa7ca8ff06 | Bind PIDs                               | Bind PIDs         | 0.0249 |     1 |
| 469657b8-17bc-4e43-bf6c-d2354e1da482 | Persistent identifier (PID) declaration | Bind PIDs         | 0.0207 |     1 |
+--------------------------------------+-----------------------------------------+-------------------+--------+-------+

select Jobs.jobUUID, jobType, microserviceGroup, timestampdiff(microsecond, min(startTime), max(endTime))/1000000 as spent, count(Tasks.jobUUID) as tasks from Jobs inner join Tasks on (Jobs.jobUUID = Tasks.jobUUID) where microserviceGroup = "Transcribe SIP contents" group by jobType;
+--------------------------------------+------------+-------------------------+--------+-------+
| jobUUID                              | jobType    | microserviceGroup       | spent  | tasks |
+--------------------------------------+------------+-------------------------+--------+-------+
| 794793cb-ff79-4985-aeb2-9e311faed122 | Transcribe | Transcribe SIP contents | 6.3718 |  1000 |
+--------------------------------------+------------+-------------------------+--------+-------+
```

Policy checking is doing this right, using `MicroServiceChainChoice` to branch instead of having the tasks schedule only to return immediately. [See the graph](https://user-images.githubusercontent.com/606459/63213891-7295fa80-c0c6-11e9-9bdc-0c54121a9659.png).

**Steps to reproduce**
1. Disable **Bind PIDs**
2. Disable **Transcribe files (OCR)**
3. Process a transfer with N number of files
4. Observe the jobs and tasks registered under "Bind PIDs" and "Transcribe SIP contents"

**Your environment (version of Archivematica, OS version, etc)**
qa/1.x

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Done:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by ross-spencer** [comment]
Related? https://github.com/artefactual/archivematica/issues/940

**Comment by sevein** [comment]
With #1470 merged, "Bind PIDs" and "Transcribe SIP contents" become no-ops. So regardless the number of files you're dealing with you should just see a single decision job record for each in the database and zero tasks scheduled to clients.

**Comment by sevein** [comment]
I've used new UUIDs in the "Bind PIDs" and "Transcribe SIP contents" processing configuration choices. For the release that means that users upgrading will see their processing configs not remember the choices they made with these two. E.g., in the automated config, users would see prompts coming back again.

I can think of two options: we make a note in the release advising users to revisit/reset/update their processing configurations, or I submit a new PR bringing the old UUIDs, which would probably work but I haven't tried. Originally I didn't do the latter because the workflow changes I made use different entities - *chains* as opposed to *link replacements*.

**Comment by ross-spencer** [comment]
@sevein did the automated config get updated, or this is to note it didn't? 

We probably need to do this for ourselves as much as anything because the black-box automated tests expect Archivematica to come out of the box and run using that config. I think the other selenium tests will still work in this instance because the config is still done through clicking! So one less thing!

**Comment by sevein** [comment]
@ross-spencer I updated them. Fresh installs are immune to the problem. It's only during upgrades where you will likely have already a shared directory with XML configs in disk that need to be updated/reset.

**Comment by ross-spencer** [comment]
Ah, I see, nice :+1:

**Comment by ablwr** [comment]
Great fix here! Tested in qa/1.x (last commit: https://github.com/artefactual/archivematica/commit/6d84db86d7d8fa21cea6f79f4b2ef1ec4c9666ef).
