### ISSUE TITLE
Problem: antivirus scanning can't be disabled

### ISSUE THREAD

**Issue by sevein** [archivematica/Issues#869]
**Expected behaviour**
The user should be able to disable antivirus scanning. A good start could be to have a single toggle in processing configuration. Further development could consider controlling it via FPR.

**Current behaviour**
There are five places in the workflow where antivirus scanning happens unavoidably.
- Scan for viruses in metadata,
- Scan for viruses in submission documentation,
- Scan for viruses on extracted files,
- Scan for viruses (right after you skip quarantine), and
- Scan for viruses (right after email attachment extraction).

Related:
- https://groups.google.com/d/msg/archivematica/3JZbi315ezk/anKshJNiCO4J
- https://github.com/artefactual/archivematica/issues/598
- https://github.com/archivematica/Issues/issues/691

**Your environment (version of Archivematica, OS version, etc)**
All versions released to this day.

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Done:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by sromkey** [comment]
I agree that just being able to turn all five places with one toggle is a good first iteration and in fact might cover the vast majority of use cases... lots of folks do virus scanning in some manner before content hits the digital preservation system and they won't be concerned about whether it's on/off for submission docs, etc.

**Comment by sevein** [comment]
Sebastian from Bodleian has been working on a solution adding new decision points on each antivirus scanning workflow link. In the Dashboard, a single decision point is shown but when enabled it translated into five pre-configured choices in the XML document. See https://github.com/artefactual/archivematica/pull/1687/files for more details.

**Comment by sromkey** [comment]
Just tested- straight forward change from the user's point of view, and the METS looks correct too (e.g. no virus scanning events when turned off). Thank you @Slange-Mhath!
