### ISSUE TITLE
Problem: job output isn't captured when task errors

### ISSUE THREAD

**Issue by sevein** [archivematica/Issues#873]
**Expected behaviour**

Our docs state that the standard error stream should be captured in case of errors:

> Note that when output capturing is disabled the stdout will never be captured while the stderr **will only be captured when the preservation task returns a non-zero exit code (i.e., when it fails)**. This allows the user to get the performance benefits while still having useful debugging information in the case where a task fails.

**Current behaviour**

@sallain [reported](https://github.com/archivematica/Issues/issues/314#issuecomment-521823617) that the standard error isn't being captured at all making impossible to investigate what's happening from the web interface.

**Steps to reproduce**
See [@sallain's report](https://github.com/archivematica/Issues/issues/314#issuecomment-521823617) for more.

**Your environment (version of Archivematica, OS version, etc)**
Bug introduced when we did the batching work, so Archivematica 1.8+.

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Done:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by sevein** [comment]
#1474 (qa/1.x) and #1490 (stable/1.10.x) changes Archivematica so both standard error and standard output streams are captured when tasks fail.

**Comment by sromkey** [comment]
I tested this by using the fixityCheckShouldFail test transfer on both a 1.9.1 instance and a 1.10.1 instance and I can see the output capture on 1.10.1 whereas I cannot on 1.9.1. 

Marking as verified.

**Comment by sallain** [comment]
@sromkey Just being extra cautious - the failure info showed up in a 1.10.1 instance that has task output capturing turned off?
