### ISSUE TITLE
Problem: We have't a qa trunk branch for the Python migration

### ISSUE THREAD

**Issue by ross-spencer** [archivematica/Issues#880]
**Please describe the problem you'd like to be solved.**

Create a trunk branch for the Storage Service and Archivematica to be able to merge development branches into following code-review.

**Describe the solution you'd like to see implemented.**

The consensus seems to be: 

*  Create `qa/2.x` and `qa/1.x` for Archivematica and the Storage Service respectively. This will be based on `qa/1.x` and `qa/0.x`. For either branch, I believe we just need to make sure that branch protection is turned on, to make sure we can follow our existing development practices. I do not believe there are other things we need to consider around branch creation like this, but input is more than welcome. 

**Describe alternatives you've considered.**

We discussed taking a development branch and renaming it, but we have a process that works using a `qa` trunk, and then that can become a future release of either product. 

**Additional context**

Part of the Python 3 development project. 

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Done:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by sallain** [comment]
There are now branches for Archivematica and the Storage Service.

https://github.com/artefactual/archivematica/tree/qa/2.x
https://github.com/artefactual/archivematica-storage-service/tree/qa/1.x
