### ISSUE TITLE
Problem: Format identification errors are not being output from the FPR command

### ISSUE THREAD

**Issue by ross-spencer** [archivematica/Issues#882]
**Expected behaviour**

Format identification information is output in its entirety.  

**Current behaviour**

Take the Siegfried command ,there are suggested logs in the FPR script wrapping the tool:
```python
     raise ParseError('error matching key {}'.format(e))
     raise ParseError('no matches found')
     raise ParseError
     raise IdToolError('siegfried determined that the file format is UNKNOWN')
```
However, in Archivematica, if a format can't be identified, as an example, we see:
```
Error: IDCommand with UUID 76006ad7-a401-48f6-98f6-2efc01003276 exited non-zero.
```
**Steps to reproduce**

Take [this set of formats that  cannot be identified](https://github.com/artefactual/archivematica-sampledata/tree/6c0257b3fe6091da13a16458390d12bc718ecd5f/TestTransfers/synthetically_unknown_formats), and process them using a standard workflow. 

**Your environment (version of Archivematica, OS version, etc)**

Tested on Archivematica `1.7` and `1.9`, and `1.10`. 

**Additional context**

Connected to https://github.com/archivematica/Issues/issues/97 and reported [via PR](https://github.com/artefactual/archivematica/pull/1419) by Wellcome. 

Reporting this separately to #97 as that might be used to audit other command output, and we can attach the existing PR to this in the hope of triage for a near future release.

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Done:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by ross-spencer** [comment]
Related https://github.com/artefactual/archivematica/issues/1053 in that the ticket requests we capture more from the format identification scripts in the microservice job.

**Comment by ross-spencer** [comment]
**NB.** As an example, the `stderr` for an unidentified file in our [synthetic unknown sample set](https://github.com/artefactual/archivematica-sampledata/tree/master/TestTransfers/synthetically_unknown_formats) will be something like:
```
Error: IDCommand with UUID 75290b14-2931-455f-bdde-3b4b3f8b7f15 exited non-zero.
Error: siegfried determined that the file format is UNKNOWN
```
Using the associated PR.

**Comment by ablwr** [comment]
Tested in qa/1.x (6d84db86d7d8fa21cea6f79f4b2ef1ec4c9666ef)
