### ISSUE TITLE
Problem: Pointer file creation fails in Python 3

### ISSUE THREAD

**Issue by replaceafill** [archivematica/Issues#887]
**Expected behaviour**

Pointer files can be created in Python 2 and 3.

**Current behaviour**

Some of the logic to create pointer files (replicas and encryption) relies on PREMIS agents and events being unique and filtered using sets. See:

* https://github.com/artefactual/archivematica-storage-service/blob/83d7b5a7da79c158cb99bd0e3426b92fdde0d3f0/storage_service/locations/models/package.py#L1169-L1171
* https://github.com/artefactual/archivematica-storage-service/blob/83d7b5a7da79c158cb99bd0e3426b92fdde0d3f0/storage_service/locations/models/package.py#L1253-L1254

However these objects (subclassed from [PREMISElement](https://github.com/artefactual-labs/mets-reader-writer/blob/58c429289e11c21c2e95f32b11eac9508c39e849/metsrw/plugins/premisrw/premis.py#L36)) are not hashable, which [is a requirement of set operations](https://docs.python.org/3/reference/datamodel.html#object.__hash__), and they implement the `__eq__` method which [makes them fail in Python 3](http://python3porting.com/preparing.html#implementing-hash) with a `TypeError: unhashable type`. 

**Steps to reproduce**

I found this through the `aip-encrypt-mirror` AMAUAT tag using the [Python 3 branch of the SS](https://github.com/artefactual/archivematica-storage-service/tree/dev/issue-806-python-3-upgrade).

**Your environment (version of Archivematica, OS version, etc)**

https://github.com/artefactual-labs/am/commit/67dbcc0fbbf541ed2594c83078a4299c808fe84c using the [Python 3 branch of the SS](https://github.com/artefactual/archivematica-storage-service/tree/dev/issue-806-python-3-upgrade).

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Done:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by sromkey** [comment]
Tested with RC2, pointer files are being created.
