### ISSUE TITLE
Directory level AIP metadata is not indexed

### ISSUE THREAD

**Issue by helenst** [archivematica/Issues#888]
**Expected behaviour**
When directory level metadata is included in a transfer e.g. in `metadata/metadata.csv` with the name of a directory in the filename column, that metadata should be indexed into the elasticsearch `aipfiles` index so that it can be picked up by the Archival Storage search.

**Current behaviour**
The metadata is not indexed when assigned to a directory, so does not come up when searched for.

**Steps to reproduce**
Start a transfer with the CSVmultiLevel sample data (https://github.com/artefactual/archivematica-sampledata/tree/master/SampleTransfers/CSVmultiLevel). This contains a metadata file with both file and directory level entries.

Once transfer and ingest is complete and an AIP has been produced, attempt to search for it on the Archival Storage tab using the following terms (with default search form settings)

* `Vancouver` -> is contained in both file and directory level metadata, and the AIP is found.
* `Replication` -> is only in the file metadata, and the AIP is found.
* `discussion` -> is only in the directory level metadata. The AIP is not found.

**Your environment (version of Archivematica, OS version, etc)**
Ubuntu 18.04, qa/1.x

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Done:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by ablwr** [comment]
Tested in qa/1.x on CentOS (last commit: https://github.com/artefactual/archivematica/commit/baf565e4abc3bcf9480ee0784734ce9b0b223f63)
