### ISSUE TITLE
Problem: EventIdentifier isn't written for Event: Name cleanup

### ISSUE THREAD

**Issue by ross-spencer** [archivematica/Issues#890]
**Expected behaviour**

According to the PREMIS dictionary, Event ID is mandatory and non-repeatable. It should be output for all Event Types inArchivematica. 

**Current behaviour**

We're missing the event identifier in `Name cleanip`. We believe this to be a development regression, between `1.9.x` and `1.10.x`. 

```xml
    <mets:digiprovMD ID="digiprovMD_4">
      <mets:mdWrap MDTYPE="PREMIS:EVENT">
        <mets:xmlData>
          <premis:event xmlns:premis="http://www.loc.gov/premis/v3" xsi:schemaLocation="http://www.loc.gov/premis/v3 http://www.loc.gov/standards/premis/v3/premis.xsd" version="3.0">
            <premis:eventIdentifier>
              <premis:eventIdentifierType>UUID</premis:eventIdentifierType>
              <premis:eventIdentifierValue/>
            </premis:eventIdentifier>
            <premis:eventType>name cleanup</premis:eventType>
            <premis:eventDateTime>2019-08-30T13:28:06.300281+00:00</premis:eventDateTime>
            <premis:eventDetailInformation>
              <premis:eventDetail>prohibited characters removed: program="sanitize_names"; version="1.10.db4f6aca278e6daf2af160ed40349baf7c6f53af"</premis:eventDetail>
            </premis:eventDetailInformation>
            <premis:eventOutcomeInformation>
              <premis:eventOutcome></premis:eventOutcome>
              <premis:eventOutcomeDetail>
                <premis:eventOutcomeDetailNote>Original name="%transferDirectory%objects/chess-♕♖♗♘♙♚♛♜♝♞♟.txt"; cleaned up name="%transferDirectory%objects/chess-.txt"</premis:eventOutcomeDetailNote>
              </premis:eventOutcomeDetail>
            </premis:eventOutcomeInformation>
            <premis:linkingAgentIdentifier>
              <premis:linkingAgentIdentifierType>preservation system</premis:linkingAgentIdentifierType>
              <premis:linkingAgentIdentifierValue>Archivematica-1.10</premis:linkingAgentIdentifierValue>
            </premis:linkingAgentIdentifier>
            <premis:linkingAgentIdentifier>
              <premis:linkingAgentIdentifierType>repository code</premis:linkingAgentIdentifierType>
              <premis:linkingAgentIdentifierValue>AM qa/1.x SS qa/0x</premis:linkingAgentIdentifierValue>
            </premis:linkingAgentIdentifier>
            <premis:linkingAgentIdentifier>
              <premis:linkingAgentIdentifierType>Archivematica user pk</premis:linkingAgentIdentifierType>
              <premis:linkingAgentIdentifierValue>1</premis:linkingAgentIdentifierValue>
            </premis:linkingAgentIdentifier>
          </premis:event>
        </mets:xmlData>
      </mets:mdWrap>
    </mets:digiprovMD>
```

**Steps to reproduce**

Take the test transfer `TestTransfer/files_with_varioous_encodings/emoji` and try to generate a SIP or AIP. The event identifier will not be there. 

**Your environment (version of Archivematica, OS version, etc)**

All `qa/1.x` test environments. 

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Done:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by sromkey** [comment]
I have tested using the "chess" test transfer and can confirm that the name clean-up has the event identifier:

`<mets:digiprovMD ID="digiprovMD_4">
      <mets:mdWrap MDTYPE="PREMIS:EVENT">
        <mets:xmlData>
          <premis:event xmlns:premis="http://www.loc.gov/premis/v3" xsi:schemaLocation="http://www.loc.gov/premis/v3 http://www.loc.gov/standards/premis/v3/premis.xsd" version="3.0">
            <premis:eventIdentifier>
              <premis:eventIdentifierType>UUID</premis:eventIdentifierType>
              <premis:eventIdentifierValue>833643f6-461e-4d2c-94f4-6a7497d3c95d</premis:eventIdentifierValue>
            </premis:eventIdentifier>
            <premis:eventType>name cleanup</premis:eventType>
            <premis:eventDateTime>2019-10-10T15:00:08.817080+00:00</premis:eventDateTime>
            <premis:eventDetailInformation>
              <premis:eventDetail>prohibited characters removed: program="sanitize_names"; version="1.10.db4f6aca278e6daf2af160ed40349baf7c6f53af"</premis:eventDetail>
            </premis:eventDetailInformation>
            <premis:eventOutcomeInformation>
              <premis:eventOutcome></premis:eventOutcome>
              <premis:eventOutcomeDetail>
                <premis:eventOutcomeDetailNote>Original name="%transferDirectory%objects/chess-♕♖♗♘♙♚♛♜♝♞♟.txt"; cleaned up name="%transferDirectory%objects/chess-.txt"</premis:eventOutcomeDetailNote>
              </premis:eventOutcomeDetail>
            </premis:eventOutcomeInformation>
            <premis:linkingAgentIdentifier>
              <premis:linkingAgentIdentifierType>preservation system</premis:linkingAgentIdentifierType>
              <premis:linkingAgentIdentifierValue>Archivematica-1.10.1</premis:linkingAgentIdentifierValue>
            </premis:linkingAgentIdentifier>
            <premis:linkingAgentIdentifier>
              <premis:linkingAgentIdentifierType>repository code</premis:linkingAgentIdentifierType>
              <premis:linkingAgentIdentifierValue>AM qa/1.x SS qa/0x</premis:linkingAgentIdentifierValue>
            </premis:linkingAgentIdentifier>
            <premis:linkingAgentIdentifier>
              <premis:linkingAgentIdentifierType>Archivematica user pk</premis:linkingAgentIdentifierType>
              <premis:linkingAgentIdentifierValue>1</premis:linkingAgentIdentifierValue>
            </premis:linkingAgentIdentifier>
          </premis:event>
        </mets:xmlData>
      </mets:mdWrap>
    </mets:digiprovMD>`

Marking as verified.
