### ISSUE TITLE
Are reprocessed AIPs updated in an AIC?

### ISSUE THREAD

**Issue by nafeldman** [archivematica/Issues#895]
If an AIP is reprocessed that's part of an existing AIC does the AIC update accordingly or is some of the technical metadata/identifier based information different for the new file? 

For our configuration, AIPs are stored in GCS and not locally.

**Comment by sromkey** [comment]
Hi there,

No, AICs are not updated but it's also true that the UUID for the AIP remains the same even after reingesting. The technical information in the AIC is fairly limited.

Thanks for your question- in the future I'd encourage you to use our user forum: https://groups.google.com/forum/#!forum/archivematica . The Issues repository is for reporting bugs or feature/enhancement requests. Thanks!
