### ISSUE TITLE
Problem: Cannot create storage service location via amclient

### ISSUE THREAD

**Issue by ross-spencer** [archivematica/Issues#905]
**Please describe the problem you'd like to be solved.**

Amclient wraps Archivematica and the Storage Service's API functionality to make it easier to import into other python modules and to simplify the way API calls can be made.

[Create Location](https://wiki.archivematica.org/Storage_Service_API#Create_new_location) is not wrapped by this library:

```bash
curl -s -d '{
    "pipeline": ["/api/v2/pipeline/f00402be-8628-42c7-880f-d95886c0c25b/"],
    "purpose": "TS",
    "relative_path": "/home/path/to/my/location",
    "description": "location-description",
    "space": "/api/v2/space/fa14cdc5-6a50-436b-aa0a-38793c4c2860/"
}' \
    -X POST \
    -H "Authorization: ApiKey test:test" \
    -H "Content-Type: application/json" \
        "http://127.0.0.1:62081/api/v2/location/"
```

**Describe the solution you'd like to see implemented.**

Implement this in the amclient work. 

**Describe alternatives you've considered.**

For our Python-based work this is a gap right now. The complexity is passed down-stream on a case-by-case basis if it isn't implemented in the client module. 

**Additional context**

Related to https://github.com/archivematica/Issues/issues/448 where we are seeking to create a location for moving non-duplicate objects to. Example workflow:

1. Detect unique objects. 
2. Move unique objects to a new transfer source.
3. Monitor the new transfer source for non-duplicate transfer material and create a SIP. 

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Done:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by ross-spencer** [comment]
cc. @sromkey marking as `1.11` as this will also be part of the AM Client release as we bring that together. The work was sponsored by IISH.

**Comment by replaceafill** [comment]
Verified this by installing `amclient` in a Python 3 virtualenv and using the new `create-location` command :+1:
