### ISSUE TITLE
Problem: Archivematica does not output metrics to analyze its performance

### ISSUE THREAD

**Issue by peterVG** [archivematica/Issues#906]
**Please describe the problem you'd like to be solved.**
Provide output to the user that details the amount of time Archivematica spends per task as well as total time spent to process a SIP or AIP. This will allow users to identify and compare performance bottlenecks in their environment configuration.

**Describe the solution you'd like to see implemented.**
Integrate the https://prometheus.io/ service with AM to scrape metrics from MCP server and make them available for graphical analysis using https://grafana.com

**Describe alternatives you've considered.**
Using internal management commands to output performance metrics. Using Prometheus exclusively is more efficient.

**Additional context**

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Done:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by peterVG** [comment]
see PR https://github.com/artefactual/archivematica/pull/1443

**Comment by ross-spencer** [comment]
Tangentially related: https://github.com/artefactual/archivematica/issues/1014

**Comment by sallain** [comment]
Documentation should also be added for this feature. @cole has left a detailed document that can be used to add an Instrumentation section to the Archivematica docs (see Artefactual Google Drive, _Instrumenting Archivematica with Prometheus & Grafana_).

**Comment by replaceafill** [comment]
I've verified this in the docker development environment. I can visit the various metrics URLs for each component and the Grafana dashboard.

I filed https://github.com/archivematica/Issues/issues/1122 to track the user documentation related changes.
