### ISSUE TITLE
Performance: use scandir instead of os.listdir/os.walk

### ISSUE THREAD

**Issue by cole** [archivematica/Issues#908]
**Please describe the problem you'd like to be solved.**

Reading filesystem contents is slower than it could be.

**Describe the solution you'd like to see implemented.**

The [scandir package](https://pypi.org/project/scandir/), which is included in the 3.5 standard library, also works on 2.7. It provides a drop in replacement for `os.walk` that is 5-10x faster, and provides a slightly different API than `os.listdir` (called `scandir`) which is harder to benchmark but seems usually at least 2x as fast.

Grepping all client scripts for `os.walk` and replacing with the scandir version would be a very easy performance gain. Replacing `os.listdir` is slightly more involved, but not much.

**Describe alternatives you've considered.**

Leave listdir/walk calls as is.

**Additional context**

We've switched to scandir in a few places (sanitize names, MCP server) when working on performance related tasks, but it would be pretty easy to update all client scripts at once. 

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Done:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by cole** [comment]
@sromkey @joel-simpson this seems like a good candidate for the 1.11 milestone.

**Comment by ablwr** [comment]
I don't really know a way to specifically test this other than our standard stress-testing procedures. @sromkey if you agree, we can close the issue and consider it complete?

**Comment by sromkey** [comment]
That sounds about right to me unless @sevein has a different suggestion?

**Comment by sevein** [comment]
Sounds good to me!
