### ISSUE TITLE
Problem: MCPServer should reuse database connections

### ISSUE THREAD

**Issue by cole** [archivematica/Issues#913]
**Expected behaviour**

MCPServer should keep an open a connection to the database, and reuse it as much as possible, because establishing a connection takes time.

**Current behaviour**
Every time a function decorated by `auto_close_db` is used, the db connection is closed, and it is reestablished on the next query.

**Steps to reproduce**
 N/A

**Your environment (version of Archivematica, OS version, etc)**

Docker compose / qa/1.x
---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Done:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by sevein** [comment]
We confirmed this is the case using `SHOW FULL PROCESSLIST` and monitoring threads created by MySQL server.
