### ISSUE TITLE
Problem: orphan client script verifyAIP shouldn't exist

### ISSUE THREAD

**Issue by sallain** [archivematica/Issues#92]
_From @sevein on June 21, 2018 18:41_

[verifyAIP.py](https://github.com/artefactual/archivematica/blob/de1cfbb86bb3da53f1443c0ded6487b477a9a2af/src/MCPClient/lib/clientScripts/verifyAIP.py) should be removed because it was replaced by [verify_aip.py](https://github.com/artefactual/archivematica/blob/de1cfbb86bb3da53f1443c0ded6487b477a9a2af/src/MCPClient/lib/clientScripts/verifyAIP.py) (see 9451abf682987f718266b809d26aeb15ac848e5a).

_Copied from original issue: artefactual/archivematica#1159_

**Comment by sevein** [comment]
This looks like it was fixed at some point but the issue was never updated.
