### ISSUE TITLE
Feature: make SS DEFAULT_FROM_EMAIL and EMAIL_USE_TLS configurable in mail settings

### ISSUE THREAD

**Issue by mamedin** [archivematica/Issues#921]
**Please describe the problem you'd like to be solved.**

There are some mail settings hard-coded, for example TLS is enabled and the default mail_from (webmaster@localhost) is not configurable.

**Describe the solution you'd like to see implemented.**

Django variables `EMAIL_USE_TLS` and `DEFAULT_FROM_EMAIL` could be read from default/sysconfig SS config file with "environ.get" as done in other mail settings.

**Describe alternatives you've considered.**

**Additional context**

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Done:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by uofmsean** [comment]
Could we get EMAIL_SUBJECT_PREFIX configurable as well?

**Comment by mamedin** [comment]
> Could we get EMAIL_SUBJECT_PREFIX configurable as well?

 :+1: any other EMAIL variable to be added?

**Comment by uofmsean** [comment]
> > Could we get EMAIL_SUBJECT_PREFIX configurable as well?
> 
> 👍 any other EMAIL variable to be added?

Adding EMAIL_BACKEND would then cover them all I think.

**Comment by mamedin** [comment]
> > > Could we get EMAIL_SUBJECT_PREFIX configurable as well?
> > 
> > 
> > 👍 any other EMAIL variable to be added?
> 
> Adding EMAIL_BACKEND would then cover them all I think.

👍  Thanks!

**Comment by mamedin** [comment]
> > > Could we get EMAIL_SUBJECT_PREFIX configurable as well?
> > 
> > 
> > 👍 any other EMAIL variable to be added?
> 
> Adding EMAIL_BACKEND would then cover them all I think.

@uofmsean Sorry, I forgot to add the change you suggested. I'm going to create a new issue to add these variables to Archivematica and Storage Service. Thanks!

**Comment by mamedin** [comment]
> > > > Could we get EMAIL_SUBJECT_PREFIX configurable as well?
> > > 
> > > 
> > > 👍 any other EMAIL variable to be added?
> > 
> > 
> > Adding EMAIL_BACKEND would then cover them all I think.
> 
> @uofmsean Sorry, I forgot to add the change you suggested. I'm going to create a new issue to add these variables to Archivematica and Storage Service. Thanks!

New feature request: https://github.com/archivematica/Issues/issues/1298

**Comment by amayita** [comment]
I have tested/reviewed that the new added variables work as intended.
