### ISSUE TITLE
Problem: S3 us-east-1 fails when chosen as region in the Storage Service

### ISSUE THREAD

**Issue by fitnycdigitalinitiatives** [archivematica/Issues#922]
**Expected behaviour**
us-east-1 should be able to be selected as a region

**Current behaviour**
Due to a known [issue](https://github.com/boto/boto3/issues/125) with Boto3, when a bucket is created in region us-east-1, a LocationConstraint cannot be specified because it is the default. This causes create_bucket to fail. Have tested using alternate region and it works. This is due to a recent [commit](https://github.com/artefactual/archivematica-storage-service/commit/c9462b175e239176659acbcbc22999bb7a26186e) in Storage Service 0.15
Furthermore, the Region field cannot be left blank.
**Steps to reproduce**
In 1.10 Storage Service, add new S3 space with us-east-1, and then add s3 AIP location. Try to ingest and store AIP in s3

**Your environment (version of Archivematica, OS version, etc)**
Storage Service 0.15

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Done:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by ross-spencer** [comment]
Hi @fitnycdigitalinitiatives. Thanks for reporting this. If you need this sooner rather than later and have the capacity to submit a PR for this, we can provide a contributors agreement and make the time to CR and put this forward for Archivematica `1.11`. I've put a triage label on to roll into discussions for `1.11` as well.

**Comment by fitnycdigitalinitiatives** [comment]
@ross-spencer I could probably do that sometime next week.

**Comment by ross-spencer** [comment]
That would be amazing Joseph, if you get around to it, information about the contributors agreement, the agreement itself, and where to send it is [here](https://github.com/artefactual/archivematica-docs/wiki/Contributor's-agreement).

**Comment by fitnycdigitalinitiatives** [comment]
Hey @ross-spencer, just made the [pull-request](https://github.com/artefactual/archivematica-storage-service/pull/488) and sent in the contrib. agreement. Let me know if I made any blunders (I haven't submitted PR's before).

**Comment by ross-spencer** [comment]
Awesome, thank you Joseph. I will highlight this to the team next week, and get reviewing, and let you know, and figure out which release it can get into. Thank you so much!

**Comment by replaceafill** [comment]
Works nicely :+1:
