### ISSUE TITLE
Problem: References need to be updated to 1.9.x to 1.10.x in upgrade instructions

### ISSUE THREAD

**Issue by uofmsean** [archivematica/Issues#925]
**Version of the documentation**
1.10 Upgrade (online)

**Page (and section, if applicable) where the issue occurs**
https://www.archivematica.org/en/docs/archivematica-1.10/admin-manual/installation-setup/upgrading/upgrading/#upgrade-centos

**Description of the issue**
Step 2 still shows the repo files being updated from 1.8.x to 1.9.x

**Suggested fix**
Update sed command to modify 1.9.x to 1.10.x

**Comment by ross-spencer** [comment]
Hi @uofmsean just looking through CentOS issues today, I feel like the link above is resolved? Does it look right to you now?

**Comment by uofmsean** [comment]
It looks fine now. Thank you!

**Comment by ross-spencer** [comment]
Great stuff! Thanks @uofmsean
