### ISSUE TITLE
Problem: missing git tags in amclient repo

### ISSUE THREAD

**Issue by sevein** [archivematica/Issues#929]
**Expected behaviour**
The amclient git repo should use tags to identify releases.

**Current behaviour**
We've made three releases so far: https://pypi.org/project/amclient/#history but we have no tags in git: https://github.com/artefactual-labs/amclient/releases.

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by ross-spencer** [comment]
Related to https://github.com/archivematica/Issues/issues/543

**Comment by ross-spencer** [comment]
AMClient has been released as `v1.0.0`. I followed this process:
```
 2263  git tag -a v1.0.0 -m "AMClient v1.0.0"
 2265  git push origin v1.0.0
 2278  sudo make clean
 2282  sudo make package-upload
```
And it is now available on PyPi: https://pypi.org/project/amclient/ the [release](https://github.com/artefactual-labs/amclient/releases/tag/v1.0.0) page shows the tag on GitHub. 

We haven't the historical hashes for the packages, but a rule-of-thumb might be to query the `version` history in the `amclient` repo: [here](https://github.com/artefactual-labs/amclient/commits/master/amclient/version.py)

For each future release-candidate/release we can adopt the same process which would be similar to that of `mets-reader-writer`. 

I feel like without docs there's a chance we'll miss a step as the team grows over time. If the need for this gets more important then I feel like we could create a deployment script for both `mets-reader-writer` and `amclient` and then similar repositories can use the same template. I suppose it depends on cost-benefit.

**Comment by ross-spencer** [comment]
@sevein do you have any ideas how to resolve this particular ticket?

**Comment by sevein** [comment]
With the new tag you've added I think this issue is resolved.

What do you mean by deployment script?

**Comment by ross-spencer** [comment]
Cool! 

Deployment script, just my terminology being off, I meant a release script to take care of tagging, push to PyPi etc.
