### ISSUE TITLE
Docs: metadata.csv files must be utf-8 encoded, but is not represented in documentation

### ISSUE THREAD

**Issue by ablwr** [archivematica/Issues#930]
**Version of the documentation**

1.10

**Page (and section, if applicable) where the issue occurs**

https://www.archivematica.org/en/docs/archivematica-1.10/user-manual/transfer/import-metadata/

**Description of the issue**

The Archivematica documentation does not specify that metadata.csv files should be UTF-8 encoded, and only UTF-8 encoded.

Attempts to import metadata using nonstandard text encodings can result in unexpected errors, such as a failure during the Generate METS.xml step of the process, with no clear indication that this is the problem.

**Suggested fix**

We update the docs to address this. It'd also be great to refine error reporting around this issue so that users know it is an encoding issue, but there could be other causes for failure within that service.

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] Documentation regarding this issue has been written and merged
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by JG260914** [comment]
Dear Ashley,

Thank you for your remark. We are going through situations where Archivematica cannot pass our descriptive metadata (Dublin Core) to the corresponding dmdSecs sessions in METS. As a question (and suggestion for additional documentation), I would like to ask for a collaboration explaining how the spreadsheet creation and saving process containing this descriptive metadata must be performed so that these metadata are transposed into METS. The version used is still 1.9.1.
Thank you for your attention.
João Guilherme Machado

**Comment by ablwr** [comment]
Hi @JG260914 -- I don't know how you are creating your spreadsheets, but when I make them using a utility like LibreOffice or Excel, there is usually a way to specify that the characters should be UTF-8, and it will make the spreadsheet UTF-8 as well.

**Comment by JG260914** [comment]
Hi Ashley!

I recently got to use Libreoffice Calc saved in UTF-8.
I use exactly the spreadsheet structure that is given as an example on the Archivematica website (for entering descriptive metadata via CSV) with respect to Dublin Core.
In the SIP framework I create a directory with the dossier title and within that directory I create two subfolders with the names "metadata" and "objects". Inside the "metadata" folder I insert the Dublin Core spreadsheet according to the Archivematica site example and in the "objects" folder I insert the video files which are the objects in our collection. In the tests I have not been able to get this DC metadata of spreadsheets to be incorporated in dmdSec in METS AIP. Only by manual and direct insertion into the software could I incorporate this information. But our real need is for metadata to be transposed to METS AIP via CSV and not manually. Would you have any suggestions?
Thanks!

**Comment by JG260914** [comment]
Hi Ashley!

I recently got to use Libreoffice Calc saved in UTF-8.
I use exactly the spreadsheet structure that is given as an example on the Archivematica website (for entering descriptive metadata via CSV) with respect to Dublin Core.
In the SIP framework I create a directory with the dossier title and within that directory I create two subfolders with the names "metadata" and "objects". Inside the "metadata" folder I insert the Dublin Core spreadsheet according to the Archivematica site example and in the "objects" folder I insert the video files which are the objects in our collection. In the tests I have not been able to get this DC metadata of spreadsheets to be incorporated in dmdSec in METS AIP. Only by manual and direct insertion into the software could I incorporate this information. But our real need is for metadata to be transposed to METS AIP via CSV and not manually. Would you have any suggestions?
Thanks!

**Comment by ablwr** [comment]
@JG260914 --I admit that the import metadata workflow can be very confusing. I assume that you're not bagging the files using BagIt, because the workflow is a little different for that (the filepaths in the CSV must be prefixed with /data). But even without bagging, it may have something to do with the filepath.

If you aren't bagging, can you rename the objects folder as something else, like "videos", and try to have the filepath in the CSV be "objects/videos/file1.mkv"? It may be that the `objects` folder name is sensitive because of the aforementioned Bag workflow and the paths are getting confused. You could also try "objects/objects/file1.mkv" to see if that works.

**Comment by JG260914** [comment]
Regarding your placement "If you are not packaging, can you rename the object folder as something else, such as" videos ", and try to make the file path in CSV" objects / videos / file1.mkv "?" , would you be referring to the path I should enter in the column (in this case, the first column of the spreadsheet with the DCs) with the file name in the spreadsheet?
tanks

**Comment by ablwr** [comment]
Yes, in the spreadsheet under filename!

**Comment by JG260914** [comment]
"objects / videos / Anima Saúde Rattus Rattus ARCA.mp4"...seria dessa maneira, Ashley?

**Comment by ablwr** [comment]
Sim, seria dessa maneira. (Did I get that right?)

"objects/videos/Anima Saúde Rattus Rattus ARCA.mp4"

I can't guarantee that will work, but I have a hunch that it might work. Also, no spaces between the slashes in the path name. The spaces in the filename could also be an issue...

**Comment by JG260914** [comment]
Yes, Ashley!
I will test now ... another question ... should the METS pointer file display the dmdSec generated in METS AIP or not?
Thank you for your support

**Comment by ablwr** [comment]
@JG260914 No, the pointer file isn't going to hold that information
