### ISSUE TITLE
Problem: FITS is configured on as a default in the FPR but its output can take a long-time for large numbers of files

### ISSUE THREAD

**Issue by ross-spencer** [archivematica/Issues#933]
**Please describe the problem you'd like to be solved**

FITS can be triggered for two reasons in the FPR:

1. By default when no other characterization tool is associated with a format.
2. When associated with a format. 

In case (1) where a file isn't identifiable using Siegfried or Fido, and FITS remains as default, then where a lot of files are processed which match that profile, e.g. research data formats, then FITS will "characterize" them all. 

FITS can take a long time to do this, generates a lot of output, and consumes a lot of memory as it is doing so. There are a number of FITS related issues in the Github repository:

* https://github.com/artefactual/archivematica/issues/1118#issuecomment-428616472
* https://github.com/archivematica/Issues/issues/502 
* https://github.com/archivematica/Issues/issues/703
* https://github.com/archivematica/Issues/issues/357

Some discussion on the forum:

* https://groups.google.com/d/msg/archivematica/EuEg54prWAU/0HWucW2zBAAJ 

Via [#315](https://github.com/archivematica/Issues/issues/315#issuecomment-511905922) for ~46,000 plain-text files, each containing a 40-byte string; FITS can take the following amount of time (`1hr, 22 mins, 29 seconds`):

```
+----------+--------------------------------------------+-----------+-------+-----------------+
| Phase    | microserviceGroup                          | CPU Time  | Tasks | duration        |
+----------+--------------------------------------------+-----------+-------+-----------------+
| Transfer | Characterize and extract metadata          | 159:58:16 | 46864 | 01:22:29.086781 |
+----------+--------------------------------------------+-----------+-------+-----------------+
```

Example output for  ~9000 of the same file:

```
+----------+--------------------------------------------+-----------+-------+-----------------+
| Phase    | microserviceGroup                          | CPU Time  | Tasks | duration        |
+----------+--------------------------------------------+-----------+-------+-----------------+
| Transfer | Characterize and extract metadata          | 159:58:16 | 9372  | 3:17:52         |
+----------+--------------------------------------------+-----------+-------+-----------------+  
```

**Describe the solution you'd like to see implemented**

Initially, we would like to make FITS an opt-in FPR rule rather than a default rule that acts as a  'catches-all' characterization for all unidentified file-formats. Partially discussed in [703](https://github.com/archivematica/Issues/issues/703#issuecomment-496675937) above. 

As an opt-in choice, where FITS is identified as adding value to the characterization of a specific format it can be added to that format. Where users would like to have FITS configured as a catch-all format it can be configured as such. See below. 

**Describe alternatives you've considered**

* Full deprecation, (analysis required)
* In combination with full deprecation, replace FITS with some of its component parts, e.g. `stat`, if desirable. Also discussed in #703. 
* Additional alternative suggestions welcomed. 

**Additional context**

Any tool can be configured as a catch-all in Archivematica by creating a rule against `Unknown: Default Format: Unknown file format`. FITS looks like this at present. 

![image](https://user-images.githubusercontent.com/1880412/66337838-3782ab80-e940-11e9-90bb-0e5b2d9e42fb.png)

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged
- [ ] Details about this issue have been added to the release notes

**Comment by sromkey** [comment]
I'm not sure when exactly this changed but FITS is now configured off by default in a new installation.
