### ISSUE TITLE
Problem: Drop-down menu in Backlog and Appraisal tabs say SIP UUID instead of Transfer UUID 

### ISSUE THREAD

**Issue by evelynPM** [archivematica/Issues#938]
**Expected behaviour**
In the Backlog and Transfer tabs, users are able to select "transfer UUID" as a field to search on.

**Current behaviour**
The drop-down menu in the search box says "SIP UUID". This actually searches the transfer UUID (since no SIP has been created yet) but the labelling is confusing.

![Screenshot from 2019-10-08 13-56-32](https://user-images.githubusercontent.com/14101311/66432978-24b9b680-e9d4-11e9-8939-3caed139a3c0.png)

**Steps to reproduce**
Start a transfer and place the transfer in backlog. Go to the Backlog or Appraisal tab and conduct a search.

**Your environment (version of Archivematica, operating system, other relevant details)**
AM 1.10

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [x] All pull requests related to this issue are properly linked
- [x] All pull requests related to this issue have been merged
- [x] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [x] Documentation regarding this issue has been written and merged
- [x] Details about this issue have been added to the release notes (if applicable)

**Comment by replaceafill** [comment]
I think we only need to update [this line](https://github.com/artefactual/archivematica/blob/6eb57c8af5154e292b9a495e3f81490ba382d38e/src/dashboard/src/media/js/ingest/backlog.js#L39) and any associated test.

**Comment by ablwr** [comment]
For testing: Just peep on these two fields when the 1.11 release candidate is available!

**Comment by sallain** [comment]
LGTM! Tested on qa/1.x on Bionic.
