### ISSUE TITLE
Problem: Storage Service import_aip limited config options cause issues

### ISSUE THREAD

**Issue by hakamine** [archivematica/Issues#940]
**Expected behaviour**
Storage Service's [import_aip](https://github.com/artefactual/archivematica-storage-service/blob/cf5f85794dc2864c87968046c3500bf5182b4eab/storage_service/common/management/commands/import_aip.py) management command should be flexible enough to work in different scenarios reliably.

**Current behaviour**
When using import_aip on a client environment, found the following issues:
- import_aip decompresses the AIP to be imported in a temp directory created under the system's default (normally /tmp in linux ). In some systems the partition/volume used for /tmp is limited in size, producing the command to fail when the size of the AIP to import is larger than this when uncompressed.
- import_aip checks if the AIP already exists in the Storage Service database (by checking its uuid), and if so it asks the user to manually confirm if overwriting the existing entry is desired. This makes it hard to use in batch scripts (as processing will block waiting for user input)

**Steps to reproduce**
Run the import_aip management command in a environment as described above

**Your environment (version of Archivematica, operating system, other relevant details)**
AM/SS 1.10/0.15

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [x] All pull requests related to this issue are properly linked
- [x] All pull requests related to this issue have been merged
- [x] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by hakamine** [comment]
Fixed by https://github.com/artefactual/archivematica-storage-service/pull/486

**Comment by replaceafill** [comment]
I verified this by downloading an existing AIP from `am111bionic` and importing it from a custom temporary directory set up in my docker-compose environment. I also tested the new `--force` flag by importing a second AIP with a different compression mechanism and an altered UUID in the METS file path to overwrite an existing AIP.
