### ISSUE TITLE
Performance: Dashboard and SS default # of workers should be >1

### ISSUE THREAD

**Issue by cole** [archivematica/Issues#944]
**Expected behaviour**

Dashboard and Storage Service stay responsive to HTTP requests.

**Current behaviour**

Both the dashboard and storage service default to a single Gunicorn worker process, using gevent. While gevent should be able to handle more requests per worker, there are still many places (C API calls for example, in any lxml usage, etc) where the event loop will be blocked.

We could modify the code to run all of these via a thread pool, but it probably doesn't matter so much if the worker is blocked, as long as there is another one to pick up the task.

**Steps to reproduce**

Send multiple concurrent requests to the dashboard or SS.

**Your environment (version of Archivematica, operating system, other relevant details)**

docker / qa/1.x

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by cole** [comment]
Related: https://github.com/archivematica/Issues/issues/785, https://github.com/archivematica/Issues/issues/730

**Comment by sevein** [comment]
@mamedin is going to change our Ansible role so the Gunicorn default is set to 3 workers in SS when using MySQL; and 1 worker otherwise.
