### ISSUE TITLE
Problem: We need to refine storage service user configuration

### ISSUE THREAD

**Issue by ross-spencer** [archivematica/Issues#948]
**Please describe the problem you'd like to be solved**

I'd like to ensure that once a user is configured in the storage service then administrators have to make a more conscious decision about elevating privileges. I'd like to make sure that there is always one administrator available in the storage service too. 

Related to  https://github.com/archivematica/Issues/issues/945 

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [x] All pull requests related to this issue are properly linked
- [x] All pull requests related to this issue have been merged
- [x] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged
- [x] Details about this issue have been added to the release notes

**Comment by sromkey** [comment]
I've just tested by creating a new non-admin user and logging in as that user- can confirm that the non-admin user can only change expected elements of their profile (name, username, email, password).
