### ISSUE TITLE
Problem: AIP METS and pointer METS files reference outdated METS schema

### ISSUE THREAD

**Issue by evelynPM** [archivematica/Issues#949]
**Expected behaviour**
METS files produced by Archivematica should have the latest version of the mets schema referenced in xsi:schemaLocation. The current version is 1.12, so the schema location should be `http://www.loc.gov/standards/mets/version112/mets.xsd.`

**Current behaviour**
METS schema location is currently `http://www.loc.gov/standards/mets/version111/mets.xsd.` Note that no other changes would be required to the METS file, since the files are valid against the 1.12 version of the METS schema.

**Steps to reproduce**
Open an AIP METS or pointer METS file and look at the namespace declaration for the METS file. 

**Your environment (version of Archivematica, operating system, other relevant details)**
http://am110bionic.qa.archivematica.net/ (AM 1.10.1 test environment)

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by ross-spencer** [comment]
**NB.** I noticed a very recent point release, 1.12.1 on the METS WG Github, that doesn't seem to have made it to the LOC website yet, [PR here](https://github.com/mets/METS-schema/pull/1) and [schema docs](here). (The change just adds comments and no functional changes. 

We might also update:

* [mets-reader-writer](https://github.com/artefactual-labs/mets-reader-writer/blob/master/metsrw/resources/mets.xsd).
* [Archivematica's schema for validating custom structMap is at 1.12](https://github.com/artefactual/archivematica/blob/stable/1.10.x/src/MCPClient/lib/assets/mets/mets.xsd),

**Comment by sromkey** [comment]
@replaceafill could you size this please?

**Comment by replaceafill** [comment]
The 1.12.1 release @ross-spencer mentioned in his latest comment has already been published:

* [METS Schema current version is 1.12.1](http://www.loc.gov/standards/mets/mets.xsd)
* [METS Schema 1.12.1](http://www.loc.gov/standards/mets/version1121/mets.xsd).

I'd say this is 1-2 hours, including https://github.com/archivematica/Issues/issues/637, which should be milestoned accordingly.

**Comment by evelynPM** [comment]
@replaceafill I just realized we should make sure that the transfer METS file references the right mets schema too (not just the AIP METS and pointer files).

**Comment by replaceafill** [comment]
@evelynPM Confirmed. I sent a transfer to the backlog and checked that the `metadata/submissionDocumentation/METS.xml` file starts with:

```xml
<?xml version='1.0' encoding='UTF-8'?>
<mets:mets xmlns:mets="http://www.loc.gov/METS/" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" OBJID="7a0d7dbf-f390-4de0-962f-3d1bc82c774e" xsi:schemaLocation="http://www.loc.gov/METS/ http://www.loc.gov/standards/mets/version1121/mets.xsd">
  <mets:metsHdr CREATEDATE="2020-01-08T17:27:08" LASTMODDATE="2020-01-08T17:27:34">
...
```

This was achieved by [updating the `SCHEMA_LOCATIONS`](https://github.com/artefactual-labs/mets-reader-writer/commit/aedc6669b9259de64118f46acd54f5c48967a571#diff-58bc2c80ae7591f28b8a4a82f1efb605L21) in the `mets-reader-writer` which is used by the `createTransferMETS_v1.0 ` client script to create the file.

**Comment by evelynPM** [comment]
Verified on AM 1.11-qa (bionic)

**Comment by sallain** [comment]
NTS: check METS files across documentation to make sure they're up to date.
