### ISSUE TITLE
Problem: Rename SIP UUID directory fails on CentOS

### ISSUE THREAD

**Issue by mamedin** [archivematica/Issues#951]
**Expected behaviour**

The `Rename SIP directory with SIP UUID` microservice doesn't fail.

**Current behaviour**

The `Rename SIP directory with SIP UUID` microservice fails with error:

``` 
Oct 15 15:07:33 mamedin-ansible-rpms-centos-src su: (to root) artefactual on pts/1
Oct 15 15:07:35 mamedin-ansible-rpms-centos-src python: archivematicaClient.py: ERROR     2019-10-15 13:07:35,019  archivematica.common:retryOnFailure:326:  Failed to complete transaction "Write task results" after 10 retries
Oct 15 15:07:35 mamedin-ansible-rpms-centos-src python: archivematicaClient.py: ERROR     2019-10-15 13:07:35,019  archivematica.mcp.client:execute_command:267:  Exception while processing task movesip_v0.0: 'ascii' codec can't decode byte 0xe2 in position 29: ordinal not in range(128)
Oct 15 15:07:35 mamedin-ansible-rpms-centos-src python: Traceback (most recent call last):
Oct 15 15:07:35 mamedin-ansible-rpms-centos-src python: File "/usr/lib/archivematica/MCPClient/archivematicaClient.py", line 256, in execute_command
Oct 15 15:07:35 mamedin-ansible-rpms-centos-src python: retryOnFailure("Write task results", write_task_results_callback)
``` 

**Steps to reproduce**

Deploy Archivematica `qa/1.x` on CentOS with ansible and try any transfer.

It works fine on:
* Ubuntu and Archivematica `qa/1.x`
* CentOS and Archivematica `stable/1.10.x`

**Your environment (version of Archivematica, operating system, other relevant details)**

CentOS 7, Archivematica `qa/1.x`

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by replaceafill** [comment]
I investigated this today and the underlying cause is [this broken job](https://github.com/archivematica/Issues/issues/770#issuecomment-543907891).

This is showing as a decode error in the QA CentOS environments because they include more locales than the Ubuntu environment and the error message looks like this (notice the `‘` characters):

```
oct 18 20:05:03 centos7slave-19 python[24991]: mv: cannot move ‘/var/archivematica/sharedDirectory/currentlyProcessing/demotransfer4-02b949dd-ed14-47fb-84f7-0458b7f45d18’ to a subdirectory of itself, ‘/var/archivematica/sharedDirectory/currentlyProcessing/demotransfer4-02b949dd-ed14-47fb-84f7-0458b7f45d18/demotransfer4-02b949dd-ed14-47fb-84f7-0458b7f45d18’
```

At some point (I couldn't pin it down), we're doing something with the non-ascii output of the command (maybe saving it to the db?) without handling it properly.

**Comment by ablwr** [comment]
Yep, this bug is all better! Tested on qa/1.x (1.11 proto-RC) -- fixed
