### ISSUE TITLE
Problem: Packages are not filtered in the Location detail view

### ISSUE THREAD

**Issue by replaceafill** [archivematica/Issues#953]
**Expected behaviour**

When looking at a location in the Storage Service, its Packages table only shows the packages stored in that location.

**Current behaviour**

The Packages table of a location shows **all** the packages without filtering them for that location only. The behaviour is the same of the `/packages` view.

This is a regression introduced in https://github.com/archivematica/Issues/issues/676 where the [datatable_utils.py](https://github.com/artefactual/archivematica-storage-service/blob/816d352436e778d11e3af4e1cf2b4eae5d573c57/storage_service/locations/datatable_utils.py) module doesn't consider the location uuid.

**Steps to reproduce**

1. Run a demo transfer and store an AIP and a DIP.
2. Go to the Locations tab of the storage service
3. Check the location you selected to store the AIP and you'll see the AIP and the DIP in the Packages table

![aip-storage](https://user-images.githubusercontent.com/560781/66955844-75f32700-f020-11e9-906b-8a20adc81785.png)

4. Go back to the Locations tab and check the location you selected to store the DIP. The AIP and the DIP are displayed in the Packages table.

![dip-storage](https://user-images.githubusercontent.com/560781/66955862-7be90800-f020-11e9-91a2-1d4854b14006.png)

**Your environment (version of Archivematica, operating system, other relevant details)**

Docker dev environment with qa branches

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by ablwr** [comment]
Tested on qa/1.x (1.11 proto-RC) -- fixed
