### ISSUE TITLE
Documentation: Ingest tab does not list microservices the way Transfer tab does

### ISSUE THREAD

**Issue by sarah-mason** [archivematica/Issues#954]
**Version of the documentation**
1.10

**Page (and section, if applicable) where the issue occurs**
Section on Ingest Tab: https://www.archivematica.org/en/docs/archivematica-1.10/user-manual/ingest/ingest/#ingest

**Description of the issue**
The Ingest Tab does not have a list of the major microservices that run and what their purpose is unlike the Transfer Tab (see here: https://www.archivematica.org/en/docs/archivematica-1.10/user-manual/transfer/transfer/#transfer-tab-microservices).

While much of the Ingest Tab does follow the major microservices, it does not have a list like this and while less microservices run in the transfer tab, this may help provide some additional clarity for users.

**Suggested fix**
Add a list of microservices that run in the Ingest tab (it does not have to be complete).

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] Documentation regarding this issue has been written and merged
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by ross-spencer** [comment]
Relating this tangentially to this issue [#802, here](https://github.com/artefactual/archivematica/issues/802). It was briefly discussed in the analyst weekly meeting and the rationale of approaching this in docs is observed and acknowledged. Additional to that, I wonder if there is still a way to leverage a component components of archivematica to help support alt-text or tool-tips in the user interface whereby someone could hover over a processing configuration option, or indeed, microservice job, and receive summary information about what that job does. Hopefully starting a discussion about that here, but this might be better suited to another ticket in-time.

**Comment by sarah-mason** [comment]
I think that's a really good idea from a user perspective @ross-spencer! It would allow people to get some useful prompts without having to find the docs every time.
