### ISSUE TITLE
Problem: MySQL settings are often too low in default deployments

### ISSUE THREAD

**Issue by ross-spencer** [archivematica/Issues#956]
**Please describe the problem you'd like to be solved**

The Archivematica database stores `stdout` and `stderr` output for microservices and this can often be too much data for current settings. We will often change clients to these settings [here](https://projects.artefactual.com/issues/12585#2-Mysql-Changes).

**Describe the solution you'd like to see implemented**

For the changes described above, e.g.
```
max_allowed_packet = 1G
innodb_log_file_size = 1G
```
Persist those in our deployment settings in playbooks? And Docker-compose settings. 

**Describe alternatives you've considered**

We can leave this as is, but there is a support cost per change we need to make around this. 

**Additional context**

No additional context at present. 

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged
- [ ] Details about this issue have been added to the release notes

**Comment by ablwr** [comment]
+1 for this, from a support management perspective. This change has made a big difference for a client working with a lot of embedded Exif data.
