### ISSUE TITLE
Problem: Storage service version hasn't been updated to 0.15.1

### ISSUE THREAD

**Issue by ross-spencer** [archivematica/Issues#958]
**Please describe the problem you'd like to be solved**

We need to update the version number for a point release of the storage service.

**Describe the solution you'd like to see implemented**

Update the storage service [version number](https://github.com/artefactual/archivematica-storage-service/blob/stable/0.15.x/storage_service/storage_service/__init__.py)!

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [x] All pull requests related to this issue are properly linked
- [x] All pull requests related to this issue have been merged
- [x] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [x] Documentation regarding this issue has been written and merged
- [x] Details about this issue have been added to the release notes

**Comment by sromkey** [comment]
I can see the version updated in a test VM. :)
