### ISSUE TITLE
Documentation: "Scaling Archivematica" docs need to be updated

### ISSUE THREAD

**Issue by cole** [archivematica/Issues#961]
**Version of the documentation**
1.10

**Page (and section, if applicable) where the issue occurs**
Installation Setup -> Customization -> Scaling Archivematica

**Description of the issue**

The configuration options available for controlling Archivematica threads have changed for 1.11, and the docs need to be updated to reflect that. `ARCHIVEMATICA_MCPSERVER_PROTOCOL_LIMITTASKTHREADS` has been removed in favour of `ARCHIVEMATICA_MCPSERVER_MCPSERVER_RPC_THREADS` and `ARCHIVEMATICA_MCPSERVER_MCPSERVER_WORKER_THREADS`.

**Suggested fix**

Update section.

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [x] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [x] Documentation regarding this issue has been written and merged
- [x] Details about this issue have been added to the release notes (if applicable)

**Comment by sallain** [comment]
Added the 1.11 milestone as the docs are ready to go, but we're waiting to create the 1.11 docs branch until closer to release time. All this will need is a rebase and merge.
