### ISSUE TITLE
Reindexing a large transfer backlog erroneously adds files from all previously-indexed items to each successive item

### ISSUE THREAD

**Issue by daaang** [archivematica/Issues#962]
**Expected behaviour**
I can reindex a transfer backlog of 613 items (totaling 1,782,982 files).

**Current behaviour**
It runs out of memory after a few days, indexing about 80 of the items and exiting with an error code. Upon examination, we determined this was because it was counting each item more than once.

For example, if we had items A, B, and C, and they looked like this:

```
A
`-- a.txt
B
`-- b.txt
C
`-- c.txt
```

Then they're indexed as if they looked like this:

```
A
`-- a.txt
B
|-- a.txt
`-- b.txt
C
|-- a.txt
|-- b.txt
`-- c.txt
```

When in reality many of the items have more than 100,000 files, this becomes a problem very quickly.

**Steps to reproduce**
As per [the documentation](https://www.archivematica.org/en/docs/archivematica-1.9/admin-manual/maintenance/maintenance/#transfer-indexes), run this:

```bash
sudo -u archivematica bash -c "set -a -e -x; source /etc/default/archivematica-dashboard; cd /usr/share/archivematica/dashboard; /usr/share/archivematica/virtualenvs/archivematica-dashboard/bin/python manage.py rebuild_transfer_backlog --transfer-backlog-dir <path_to_backlog>"
```

You'll see that items contain files they should not contain.

**Your environment (version of Archivematica, operating system, other relevant details)**
Archivematica v1.9.2, Ubuntu bionic, in the process of upgrading from v1.8.1 with a very large transfer backlog.

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by ross-spencer** [comment]
This fix was primarily an intellectual one, as it was a sub-optimal approach to code. The efficacy was never truly tested, but for 1.11 release testing we can do so, easily at least in Docker. Even with relatively few files as Python tries to work through a data-structure only growing in detritus its performance should degrade. Once that data-structure's use is optimized to not maintain and add to state, it should speed up. Let's see...

-----
Broken code: `src/archivematicaCommon/lib/elasticSearchFunctions.py`

fixed commit: `82c624`
previous commit without fix: `ac3a20`

1. Make sure we're on the fixed commit: `ross-spencer@artefactual:~/git/artefactual-labs/am/src/archivematica/src/archivematicaCommon/lib$ git checkout 82c624 elasticSearchFunctions.py`

2. Test its speed:
```
ross-spencer@artefactual:~/git/artefactual-labs/am/compose$ time sudo make manage-dashboard ARG="rebuild_transfer_backlog"
[sudo] password for ross-spencer: 
docker-compose run \
	--rm \
	--entrypoint /src/dashboard/src/manage.py \
		archivematica-dashboard \
			rebuild_transfer_backlog
Starting compose_redis_1         ... done
Starting compose_mysql_1         ... done
Starting compose_elasticsearch_1 ... done
Starting compose_archivematica-storage-service_1 ... done
Starting compose_gearmand_1                      ... done
WARNING: This script will delete your current Elasticsearch transfer data, rebuilding it using files.
Are you sure you want to continue?

Type "yes" to continue, or "no" to cancel:  yes
Rebuilding "transfers" index from /var/archivematica/sharedDirectory/www/AIPsStore/transferBacklog/originals.
Connected to Elasticsearch node am-node (v6.5.4).
Deleting all transfers and transfer files in the "transfers" and "transferfiles" indexes...
Creating indexes...
Importing self-describing transfer 92448782-40b3-4af9-beaa-8190fe324512.
Importing self-describing transfer b5c03567-7217-4508-adc9-76ec29568a1a.
Importing self-describing transfer 9ddda570-acf2-44ec-b581-780352e57c05.
Importing self-describing transfer 2ddc62f9-556b-48a1-ba3e-bf4e886cf3de.
Importing self-describing transfer b40946b9-3329-44bf-86cf-0ce415fff5ac.
Importing self-describing transfer f2b234de-6159-4741-937f-c273600e800c.
6 transfers indexed!

real	1m6.008s
user	0m1.184s
sys	0m0.144s
```
3. We can also see the file counts are correct:

![image](https://user-images.githubusercontent.com/1880412/77434173-d9933480-6db6-11ea-846a-66f23333e756.png)

4. repeat for the broken commit: `ross-spencer@artefactual:~/git/artefactual-labs/am/src/archivematica/src/archivematicaCommon/lib$ git checkout ac3a20 elasticSearchFunctions.py`

```
ross-spencer@artefactual:~/git/artefactual-labs/am/compose$ time sudo make manage-dashboard ARG="rebuild_transfer_backlog"
docker-compose run \
	--rm \
	--entrypoint /src/dashboard/src/manage.py \
		archivematica-dashboard \
			rebuild_transfer_backlog
Starting compose_mysql_1         ... done
Starting compose_archivematica-storage-service_1 ... done
WARNING: This script will delete your current Elasticsearch transfer data, rebuilding it using files.
Are you sure you want to continue?

Type "yes" to continue, or "no" to cancel:  yes
Rebuilding "transfers" index from /var/archivematica/sharedDirectory/www/AIPsStore/transferBacklog/originals.
Connected to Elasticsearch node am-node (v6.5.4).
Deleting all transfers and transfer files in the "transfers" and "transferfiles" indexes...
Creating indexes...
Importing self-describing transfer 92448782-40b3-4af9-beaa-8190fe324512.
Importing self-describing transfer b5c03567-7217-4508-adc9-76ec29568a1a.
Importing self-describing transfer 9ddda570-acf2-44ec-b581-780352e57c05.
Importing self-describing transfer 2ddc62f9-556b-48a1-ba3e-bf4e886cf3de.
Importing self-describing transfer b40946b9-3329-44bf-86cf-0ce415fff5ac.
Importing self-describing transfer f2b234de-6159-4741-937f-c273600e800c.
6 transfers indexed!

real	2m29.989s
user	0m0.688s
sys	0m0.127s
```

We can also observe the file counts are incorrect, i.e. they've been accumulating this whole time and it is just a handful of transfers:

![image](https://user-images.githubusercontent.com/1880412/77433999-8e792180-6db6-11ea-9c9c-0321c29f48fa.png)

I have tested on Docker, working on the release servers will just take a bit  of configuration and a bit more time, someone might be able to take that on if they feel it necessary.
