### ISSUE TITLE
Problem: Identifiers.json import fails if 'Bind PIDs' config option is not set to 'Yes'

### ISSUE THREAD

**Issue by peterVG** [archivematica/Issues#963]
**Expected behaviour**
Values from the `/metadata/identifiers.json` file are imported successfully regardless of whether the `Bind PIDs` microservice is enabled or not in the Archivematica configuration settings. See https://www.archivematica.org/en/docs/archivematica-1.10/user-manual/transfer/transfer/#transfer-pids

**Current behaviour**
Identifiers.json import fails if 'Bind PIDs' config option is not set to 'Yes'. This is due to the changes made in https://github.com/artefactual/archivematica/pull/1470. This was done for performance reasons by avoiding running the `Bind PIDs` microservice when it is not being used. However, identifiers.json import is currently a job within this microservice.

**Changed Behaviour**
Move the `Import identifiers.json` Job to the `Characterize and extract metadata` microservice where it fits more logically with the other Jobs. This means it runs in every instance without requiring a configuration change to `Bind PIDs` (which is really related to integration with an external Handle server, not metadata import). This also avoids user confusion when the `Bind PID` microservice fails but identifiers.json import is still successful.

**Your environment (version of Archivematica, operating system, other relevant details)**

1.x QA

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by replaceafill** [comment]
@peterVG @sromkey I found that if we move the existing job to the `Characterize and extract metadata` we would lose the ability to assign persistent identifiers to SIPs (because they're not created yet at that point).

In order to keep this job in the Ingest tab we could alternatively extract it to a different group. Maybe under the `Process metadata directory` microservice?

**Comment by sromkey** [comment]
That makes sense to me @replaceafill !

**Comment by ross-spencer** [comment]
Hi folks, I accidentally code-reviewed this while it was WIP but it did trigger a thought or two. 

We have a `Characterize and extract metadata` microservice job in both the transfer and ingest tab. But (I believe) we only have `Process metadata directory` in the Ingest tab which seems to align with the description, so you'd still only be creating an AIP with persistent identifiers. The SIP wouldn't contain them. So if the desire is to have them available in the SIP too, per work done to make the SIP more complete, it would need to be in the transfer tab. Possibly under `Characterize and extract metadata` there. But I might be missing something about new workflows, e.g. it seems these aren't user submitted identifiers.json files? and I stumbled on this so please feel free to ignore. 

As this is a regression, an alternative solution might have been to simply put the behavior as it was in `1.10`. So in the [docs](https://www.archivematica.org/en/docs/archivematica-1.10/user-manual/transfer/transfer/#transfers-with-existing-persistent-identifiers) you will see it sits before the Bind PIDs decision point to run whether toggled on/off. From testing it did seem the grouping was not intuitive, but perhaps also changing the name of the microservice group to reflect its work with identifiers is an alternative idea?

**Comment by peterVG** [comment]
There was a regression between 1.10 and qa/1.11 that skipped identifiers.json import while it was configured as a Job under a disabled Bind PID microservice. This was apparently caused by artefactual/archivematica#1470. For this reason and to avoid running Bind PID when just identifiers.json import is needed, the Job was moved to the next logical Ingest microservice which is `Process metadata directory`. This makes sense to me @replaceafill

**Comment by ablwr** [comment]
Review of this seems contingent on a WIP documentation by @peterVG, is that right?

**Comment by peterVG** [comment]
@ablwr the docs are done. see https://github.com/artefactual/archivematica-docs/tree/dev/issue-971-import-identifiers.json

**Comment by ablwr** [comment]
Whoops -- just saw the "closed" and didn't click through to see the link. OK, I will test! Thanks.

**Comment by ablwr** [comment]
Yes, this works now! I saw it not work in stable, and work in qa/1.x (last commit: https://github.com/artefactual/archivematica/commit/6d84db86d7d8fa21cea6f79f4b2ef1ec4c9666ef), and the docs are all set as well.
