### ISSUE TITLE
Problem: It is difficult to simply combine status for different package types in AM where amclient might offer that possibility

### ISSUE THREAD

**Issue by helrond** [archivematica/Issues#972]
**Please describe the problem you'd like to be solved**
Checking the status of a package (by which I mean a package that Archivematica considers either a “transfer” or an “ingest”) requires hitting two different endpoints. 

**Describe the solution you'd like to see implemented**
Add a helper function to amclient to check the `/api/ingest/status/<UUID>` endpoint, and then proceed to the `/api/transfer/status/<UUID>`. So something like:

```
def get_status(self, uuid):
    try:
        return utils._call_url_json("/api/ingest/status/{}".format(uuid)
    except Exception as e:
        return utils._call_url_json("/api/transfer/status/{}".format(uuid)
```

I'd obviously target the exception a little more specifically, but would need to do some testing to figure out all the possible exceptions that might be thrown.

**Describe alternatives you've considered**
Building an endpoint for this in the `v2beta` namespace, I guess?

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged
- [ ] Details about this issue have been added to the release notes

**Comment by sevein** [comment]
Unfortunately, `utils._call_url_json` doesn't raise and it masks the underlying errors. E.g. it would return [errors.ERR_INVALID_RESPONSE](https://github.com/artefactual-labs/amclient/blob/cb9a5961d38d72da18955a7fdc05df77be344476/amclient/errors.py#L3) if the status code isn't 200, but you wouldn't be able to tell if you're dealing with a 4xx (where you may want to move to transfer) or a 5xx (where you'd want to retry or raise). Ross filed an issue where he goes into more detail: https://github.com/archivematica/Issues/issues/488.

An option for v1 could be to have AMClient accept an optional callable that could be used in place of "utils._call_url_json". It'd be messy but necessary?

**Comment by helrond** [comment]
Thanks, I just took a look at #488 and I see what you're saying. If I'm reading correctly, @ross-spencer is saying that changing the behavior of amclient (i.e. having it behave in a more pythonic way) would require some reworking in all the contexts in which it is currently used.

I will be stuck on a plane for 11 hours tomorrow so I'll see if I can knock together a PR.

**Comment by ross-spencer** [comment]
Related to https://github.com/archivematica/Issues/issues/626

**Comment by helrond** [comment]
Just added a [WIP PR](https://github.com/artefactual-labs/amclient/pull/11) - would appreciate a sanity check.

**Comment by ross-spencer** [comment]
hi @sromkey I've added `1.11` to this as it will make it into `1.11` as part of the amclient work there, does that work for you? We can remove if not. It's already in review, we can probably just close this otherwise.

**Comment by replaceafill** [comment]
Verified this by installing `amclient` in a Python 3 virtualenv, instantiating the `AMClient` class and invoking its `get_unit_status` method.

It's worth mentioning that this new method can't be invoked from the command line yet.
