### ISSUE TITLE
Problem: Cannot use S3 as a transfer source

### ISSUE THREAD

**Issue by ross-spencer** [archivematica/Issues#975]
**Please describe the problem you'd like to be solved**

Wellcome have submitted a [PR](https://github.com/artefactual/archivematica-storage-service/pull/459) seeking to use S3 as a transfer source. 

**Describe the solution you'd like to see implemented**

We need to review this requirement and ensure it works in the best way possible for all users of the storage service and S3 who would also like this capability.

**Describe alternatives you've considered**

Don't implement this, however it seems a reasonable enough extension of the S3 adapter's capabilities. 

**Additional context**

None other than the above. 

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged
- [ ] Details about this issue have been added to the release notes

**Comment by ross-spencer** [comment]
**Testing notes**

* A bucket has been created in S3 called `2813279b-43d2-42a6-b413-888a2689417d`
* In there sits a transfer folder with three transfers.
   * A zipped bag. 
   * DemoDataCSV
   * A transfer with a single file. 
* Testers will be able to see the transfer layout via the transfer browser. 

To test:

1. Set up an S3 space with a named bucket as above; and configure a transfer source location (location path `/`)
2. Your regular AIP store will be fine for storing the data. 
3. Open Archivematica and browse to your new transfer source. 
4. Find one of the above documented transfers and attempt to create an AIP. 
5. The AIP, e.g. the DemoDataCSV should have anticipated properties as per a standard transfer. For DemoDataCSV checksum comparison will fire which is a good way to ensure the S3 data is being pulled down as anticipated. Same for the zipped bag.

**Comment by ablwr** [comment]
LGTM. Tested on qa/1.x (https://github.com/artefactual/archivematica/commit/baf565e4abc3bcf9480ee0784734ce9b0b223f63, proto-1.11 RC candidate). @helenst looks like you're up for updating the docs for this issue, so I will leave this open.

**Comment by replaceafill** [comment]
Docs have [been updated](https://github.com/artefactual/archivematica-storage-service-docs/pull/32) to specify this new behaviour.
