### ISSUE TITLE
[Question] Trying to install on Debian Stretch

### ISSUE THREAD

**Issue by neves01** [archivematica/Issues#976]
Greetings guys,

I am trying to install Archivematica (1.10.x 1.9.x 1.8.x - [link](https://www.archivematica.org/pt-br/docs/archivematica-1.8/admin-manual/installation-setup/installation/install-ubuntu/#install-pkg-ubuntu)) on the Debian system (9 and 10) and I am not succeeding. I tried to follow the installation steps of Ubuntu (Bionic and Xenial) but in the end installation of archivematica-mcp-client fails. In general the message shows mediaconch and libavcodec-extra57 packages are not compatible.

Are there any more steps I can do?

Thanks.

**Comment by sromkey** [comment]
Hi there- supported installation environments are described here:
https://www.archivematica.org/en/docs/archivematica-1.10/admin-manual/installation-setup/installation/installation/#installation
Please feel free to post install questions to our user forum:
https://groups.google.com/forum/#!forum/archivematica
