### ISSUE TITLE
Problem: metadata icon tooltip is in Spanish

### ISSUE THREAD

**Issue by sallain** [archivematica/Issues#98]
_From @sevein on June 18, 2018 20:48_

It reads "Metadatos" instead of "Metadata".

https://github.com/artefactual/archivematica/blob/3794deb8353d3cef847ba9d2cf8538665924ada6/src/dashboard/src/templates/ingest/grid.html#L179

_Copied from original issue: artefactual/archivematica#1146_

**Comment by currmie** [comment]
Hmm, I'm still seeing this on am19xenial in the Ingest tab.

**Comment by sallain** [comment]
Oddly enough, I'm seeing it in English on both Transfer and Ingest, on a newly-deployed upgraded site. @currmie maybe try updating xenial?

**Comment by currmie** [comment]
Verified on xenial today, all good now!
