### ISSUE TITLE
Problem: Service startup time for clamd in CentOS (at least) can cause a playbook to fail

### ISSUE THREAD

**Issue by ross-spencer** [archivematica/Issues#980]
**Expected behaviour**

CentOS deployment using ansible is slick as a whistle!

![whistle](https://i.giphy.com/media/11BVzJf1NYWEo/giphy.webp)

**Current behaviour**

I believe all the settings in the ansible-deployment are fine, it's just that sometimes the time taken to start `clamd` on CentOS can cause the service not to start failing the playbook. 

**Steps to reproduce**

Try running the CentOS playbook for the sanbox deploys and you should see occasional failures here.

**Your environment (version of Archivematica, operating system, other relevant details)**

```
/etc/system-release
CentOS Linux release 7.6.1810 (Core) 
```

**Workaround**

1. One approach is to restart the daemon directly. 

2. My approach after some googling was to increase the service timeout:
```
Edit file /usr/lib/systemd/system/clamd@.service
```
```
[Unit]
Description = clamd scanner (%i) daemon
Documentation=man:clamd(8) man:clamd.conf(5) https://www.clamav.net/documents/
# Check for database existence
# ConditionPathExistsGlob=@DBDIR@/main.{c[vl]d,inc}
# ConditionPathExistsGlob=@DBDIR@/daily.{c[vl]d,inc}
After = syslog.target nss-lookup.target network.target

[Service]
Type = forking
ExecStart = /usr/sbin/clamd -c /etc/clamd.d/%i.conf
Restart = on-failure
TimeoutSec = 180  <------ added this
```
Which was just enough to get me up and running!

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by sromkey** [comment]
Due to recent updates this is now working fine!
