### ISSUE TITLE
Problem: pipeline UUID isn't exposed via the API

### ISSUE THREAD

**Issue by sevein** [archivematica/Issues#983]
**Please describe the problem you'd like to be solved**
It does not seem to be possible to retrieve the unique identifier of an Archivematica pipeline via the API. The identifier can be found however in the web interface (Administration » General).

This could be useful for users managing multiple Archivematica pipelines that are provisioned dynamically. Ideally, capturing the identifier of a pipeline would not require manual configuration steps such looking up the identifier via the web interface.

**Describe the solution you'd like to see implemented**
A new `X-Archivematica-ID` header in API responses, only to be included when the authorization stage has succeeded. An additional `X-Archivematica-Version` header could be added to identify the current version of Archivematica deployed.

```
> GET /api/status/ HTTP/1.1

< HTTP/1.1 200 OK
< X-Archivematica-Version: 1.11.0
< X-Archivematica-ID: bd889bc0-223f-4b5a-9a6d-8de3ccbda5cb
< Server: nginx/1.14.0
< Content-Type: application/json
{}
```

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [x] All pull requests related to this issue are properly linked
- [x] All pull requests related to this issue have been merged
- [x] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [x] Documentation regarding this issue has been written and merged
- [x] Details about this issue have been added to the release notes

**Comment by sevein** [comment]
For QA, the following cURL command prints the headers returned by one of our API responses:

    $ curl -v -Ls -H "Authorization: ApiKey test:test" 127.0.0.1:62080/api/processing-configuration/default/ 1>/dev/null

Within the response headers, you should see these two:

    < X-Archivematica-Version: 1.11.0
    < X-Archivematica-ID: 4e7e9300-2da4-4300-9ea1-187cda970e68

**Comment by ablwr** [comment]
All good here. X-Archivematica-ID is different but I assume that's expected.
