### ISSUE TITLE
Problem: gettext machine object files are not generated as part of an Archivematica deployment

### ISSUE THREAD

**Issue by ross-spencer** [archivematica/Issues#984]
**Expected behaviour**

**NB.** *`gettext` is a de-facto standard for enabling translation. `.po` files contain source strings and translated strings. Those are compiled to `.mo` files for efficient use in a programming language. `.mo` files are read to be able to display strings in the user-interface. More info [here](https://en.wikipedia.org/wiki/Gettext).*

I am able to choose the language I want to see Archivematica in when I select a language from the administration tab. The text on the left-hand side below is the correct appearance of Archivematica if the dashboard command `compilemessages` has been run without error. 

![image](https://user-images.githubusercontent.com/1880412/68626136-8dfc8000-04d2-11ea-9298-b5408216d0df.png)

**Current behaviour**

There are two slightly different behaviors when you are running docker vs. a more traditional ansible style deployment. 

The `.mo` files on my CentOS deployment simply haven't been created:
```
[centos@analyst-ross-vm src]$ tree locale/
locale/
├── en
│   └── LC_MESSAGES
│       ├── djangojs.po
│       └── django.po
├── es
│   └── LC_MESSAGES
│       ├── djangojs.po
│       └── django.po
├── fr
│   └── LC_MESSAGES
│       ├── djangojs.po
│       └── django.po
```
It looks like they need to be part of the ansible-playbook used to stand this up.

In docker the root issue seems to be that to run `compilemessages` manually, a volume with write permissions is needed otherwise the following message appears: `The po files under /src/dashboard/src/locale/fr/LC_MESSAGES are in a seemingly not writable location. mo files will not be updated/created.` 

**Steps to reproduce**

1. Take a vanilla new deployment of Archivematica and try to switch the language in the admin tab. There should be no difference between the English language version and the selected language (you can see part of a string translated in this screenshot (`modifier`): 

![image](https://user-images.githubusercontent.com/1880412/68626913-5989c380-04d4-11ea-912d-5f5037a5d4e9.png)
 
2. Also, in docker-compose attempt: `make manage-dashboard ARG=compilemessages` and observe the behavior.

**Your environment (version of Archivematica, operating system, other relevant details)**

As described above, `1.10`/`qa.1.x` release of Archivematica. The sandbox is also impacted [here](https://sandbox.archivematica.org/).

**Notes**

I tried the volume below:

* `- "../src/archivematica/src/dashboard/src/locale/:/src/dashboard/src/locale/:rw"` 

Perhaps this needs to be more granular? 

The correct screenshot taken above was once the repository was setup as follows:
```
root@7e2ae77093c2:/src/dashboard/src/locale# ls -la fr/LC_MESSAGES/
total 180
drwxr-xr-x 2          1000          1000  4096 Nov 11 21:43 .
drwxr-xr-x 3          1000          1000  4096 Nov  7  2018 ..
-rwxrwxrwx 1 archivematica archivematica 13207 Nov 11 21:57 djangojs.mo
-rwxrwxrwx 1 archivematica archivematica 20441 Nov 11 10:20 djangojs.po
-rwxrwxrwx 1 archivematica archivematica 37352 Nov 11 21:57 django.mo
-rwxrwxrwx 1 archivematica archivematica 97075 Nov 11 21:36 django.po
```
And then the french language could be selected and then displayed as desired. 

* From the container:

   * `docker-compose exec --user=root archivematica-dashboard bash`
   * `cd /src/dashboard/src`
   * `python manage.py compilemessages`

And messages are generated as anticipated.

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by ross-spencer** [comment]
I'm seeing an error caused by [this country code](https://github.com/artefactual/archivematica/blob/ef3af9fb58ac700dfca2a350095ef13a0c396e9c/src/archivematicaCommon/lib/countryCodes.py#L1) in am/common today, which does seem a little errant.

**Comment by ross-spencer** [comment]
The reason they don't show up in source control is that they are part of the `.gitignore` file for the dashboard [here](https://github.com/artefactual/archivematica/blob/6d84db86d7d8fa21cea6f79f4b2ef1ec4c9666ef/.gitignore#L2). I am not sure if this is in error. One other approach to the problem described above could be to commit these files so that they are available once AM is installed. There are still processes missing between any particular solution right now.

**Comment by sevein** [comment]
I prefer to run compilemessages with my own uid, so I don't end up with root-owned files in my local checkouts (see example below), but otherwise it'd be good to have your https://github.com/artefactual-labs/am/pull/90/files merged.

    docker-compose exec --user=(id -u) archivematica-dashboard bash -c "cd /src/dashboard/src && ./manage.py compilemessages"   

The Dockerfile(s) should also run compilemessages to guarantee an initial build of the messages. But that would be a lower priority since we don't distribute Docker images.

> The reason they don't show up in source control is that they are part of the .gitignore file for the dashboard here. I am not sure if this is in error. One other approach to the problem described above could be to commit these files so that they are available once AM is installed. There are still processes missing between any particular solution right now.

Yeah, that was intentional. I don't want to track binary artifacts because we'd have to be constantly commiting new versions to avoid outdated translations in our deployments. For similar reasons, we don't track our frontend artifacts. Build artficats are generally not version controlled. Running compilemessages at build time is the way to go, requiring changes in packages and the Ansible role.

You'll see the approach is different in apps vs packages/libraries. E.g. mercurial runs msgfmt at build time, but a package like django-debug-toolbar or django itself track the mo files in source control to avoid you dealing with the conversion process, the additional build time, the dependency on msgmft, etc...
