### ISSUE TITLE
Problem: replicator does not replicate re-ingested AIPs or delete replicated copies of AIPS when deleted

### ISSUE THREAD

**Issue by corinnemrogers** [archivematica/Issues#985]
**Expected behaviour**
When replication is configured in the storage service, and then when an AIP is reingested from the AM dashboard, one might expect that the reingested AIP would be replicated.

**Current behaviour**
* The original replicated AIP remains unchanged when the source AIP is reingested.
* The replication relationship from the original AIP pointer file is no-longer there. 
* The src->repl relationship is gone in the Packages table of the storage service.
* The repl->src relationship is still present, but technically incorrect. 

**Steps to reproduce**
Configure replications; create an AIP; review the AIP and its replica; reingest the AIP; review the replica

**Your environment (version of Archivematica, operating system, other relevant details)**
AM 1.10.1 / SS 0.15

**Additional context**

*[2019-12-10]: RS added pointer file behavior. Tested on AM 1.10.*

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by corinnemrogers** [comment]
This issue has been updated to reflect behaviour on reingest only; deleted AIPs are not deleted from the replication location, however this is considered to be expected behaviour.

**Comment by RedHaxor** [comment]
I solved this problem for us by adding: self.create_replicas() to line 2390 of https://github.com/artefactual/archivematica-storage-service/blob/stable/0.15.x/storage_service/locations/models/package.py#L2390   
! Not much testing has been done.

**Comment by ross-spencer** [comment]
@RedHaxor how are you finding your workaround for this? I'm seeing new replicas being made each time there is a reingest, so there's a trail of each old replica with a different UUID going back to the first. Just looking at how that can be cleaned up a bit now.

**Comment by tw4l** [comment]
@ross-spencer Feel free to ignore if it's not helpful but this WIP management task for the Storage Service might provide an example of how to clean up replicas before creating new ones (just bear in mind there are some CR revisions still to be done, such as changing existing replica status to "DELETED" in the Storage Service db rather than deleting the entries outright): https://github.com/artefactual/archivematica-storage-service/pull/544

**Comment by ross-spencer** [comment]
@tw4l that's awesome! Thank you!

**Comment by ross-spencer** [comment]
Related: https://github.com/archivematica/Issues/issues/359.

**Comment by ross-spencer** [comment]
Problem statement about the handling of replicas through the process of reingest (or re-creation) in Archivematica [here](https://docs.google.com/document/d/1FjGrtj7XxtiaG-dNkvFlrpd-ZhBOwsmEz6YB4J5joUs/edit#). The decision outcome is to implement the features that support Option 1 in the short-term with a recognition that other pieces might need to be put in place in future.

**Comment by ross-spencer** [comment]
Following up on https://github.com/archivematica/Issues/issues/985#issuecomment-748187383 what users will need to be aware of with this first approach, is that, if they replicate _n_ times, they will end up with _n-1_ deleted packages, and _1_ uploaded replica, plus the original.

![image](https://user-images.githubusercontent.com/1880412/103644280-1da98d00-4f24-11eb-829c-6c04ad19801b.png)

**Comment by sromkey** [comment]
Tested this, it works as expected now- 
- I created an AIP and stored in a location with a replicator
- I reingest the AIP
- Checked the replicated package and confirmed that it had been updated (e.g. reingestion event in the METS was present)
- I then proceeded to delete the AIP and confirmed that the replica was also deleted.
