### ISSUE TITLE
Archivematica dev-tools graph-links doesn't work with AM 1.10

### ISSUE THREAD

**Issue by arifshaon** [archivematica/Issues#998]
**Expected behaviour**
Should produce a graphical view of the AM process chain.

**Current behaviour**
Throws the following exception:

_mysql_exceptions.ProgrammingError: (1146, "Table 'MCP.MicroServiceChainLinks' doesn't exist")

**Steps to reproduce**

**Your environment (version of Archivematica, operating system, other relevant details)**
Archivematica 1.10
Ubuntu 18.04.3

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged (if applicable)
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by ross-spencer** [comment]
Hello there Arif, 

The workflow model changed in Archivematica 1.9 with the workflow itself being encoded in a source controlled JSON object called [workflow.json](https://github.com/artefactual/archivematica/commits/stable/1.10.x/src/MCPServer/lib/workflow.py).

The model you see in workflow.json is still largely a mapping of what existed in the MCP database so I won't go into that here.

The virtues I have observed is that the new method has made it easy to add, remove, and modify chainlinks (largely microservice jobs) without having to create code to perform a Django database migration. We hope too that the method will help with translation of workflow objects which is something we're looking into now. Being in source control the model is greater to understand for a larger number of developer types.

To your point, we are unlikely to make the dev-tools method work with AM 1.10. We have replaced it with the [`amflow`](https://github.com/artefactual-labs/amflow) tool available at that link. 

I recommend checking out the `README.md` and seeing if you can get it up and running and the information you need out of it. Should you have any difficulties then perhaps open a ticket in the Google Group for [Archivematica](https://groups.google.com/forum/#!forum/archivematica). And we can share additional tips and help there. Of course, any bugs or feature requests, please log them here in GitHub.
